### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by johnfelipe** [interlegis/sapl#1]
I can translate to spanish but internationalization is possible?

**Comment by marciomazza** [comment]
Greetings. It is most welcome!

We are already working on that and our plan is to make a fully internationalized project.
As soon as we finish the next release it will be possible to receive translations.

**Comment by rougeth** [comment]
:+1:

**Comment by johnfelipe** [comment]
Next realese es 3.0, when release it?

**Comment by marciomazza** [comment]
That will be 3.1.

We do not have a precise release date yet, but will probably have an alpha by late august.

**Comment by johnfelipe** [comment]
And can i begin translate strings, may be transifex?

**Comment by johnfelipe** [comment]
Do you have django.po ready, i want begin translate strings to spanish

**Comment by marciomazza** [comment]
Internationalization is planned for version 3.2, but, to meet your request in issue #1 we are trying to find ways to include it sooner in 3.1.

The code is partly internationalized. That means we can generate a gettext translation file and also use transifex. But all our strings are still in Portuguese. We plan to change them to english strings and move them to a translation file, but cannot do it now.

Do you feel comfortable to translate from Portuguese to Spanish?

If you do, we can use Portuguese as the base language and make the switch to English latter on.

**Comment by johnfelipe** [comment]
Yes i feel comfortabke translate from portuguese, i want contribute, and transifex is a good way, send me link and begin translation

**Comment by marciomazza** [comment]
Ok, then. We will set that up and post the link here.

**Comment by johnfelipe** [comment]
Stay alert

**Comment by marciomazza** [comment]
Here it is. The transifex project is:

https://www.transifex.com/projects/p/sapl-sistema-de-apoio-ao-processo-legislativo

I hope I have made things right. I think you can simply join it there and start working.
Please let let me know if you have any issues.

**Comment by marciomazza** [comment]
I have completed the localization setup and put together instructions for translators here:

https://github.com/interlegis/sapl#instructions-for-translators

**Comment by johnfelipe** [comment]
Spanish strings are translate it in 100%

**Comment by marciomazza** [comment]
That's great. Thanks a lot.

As we advance in the development we will periodically update the translation base. We hope that as soon as we finish you'll be able to use the release.

**Comment by johnfelipe** [comment]
What is progress for next full realese, please tell me a month, tnks

**Comment by johnfelipe** [comment]
Any progress?

**Comment by johnfelipe** [comment]
Any progress?

**Comment by johnfelipe** [comment]
date to stable realese?

**Comment by marciomazza** [comment]
John Felipe,

We have not been answering your questions promptly. Sorry about that.

We do not have a definitive date for a stable release, but we will probably have a beta release by the end of March 2016.

**Comment by johnfelipe** [comment]
Hi again, pls tell me, is march now..

**Comment by marciomazza** [comment]
We're sorry but we will only be able to fish by May or June.

**Comment by johnfelipe** [comment]
Is july pls tell me if release is complete?

**Comment by marciomazza** [comment]
Sorry, @johnfelipe, it is not. Our team is currently very reduced, and a change of priorities deviated us from course.
We still have some issues to resolve, you can check them here:
https://github.com/interlegis/sapl/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1

We still need some months to cut a beta release.

**Comment by johnfelipe** [comment]
Its ready an UI?
