### ISSUE TITLE
Sessão Plenária: listas de presenças vazias

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1001]
As listas de presenças à sessão plenária e à Ordem do Dia estão vazias.

**Comment by edwardoliveira** [comment]
São todas? Teria como fornecer uma sessão de exemplo?

**Comment by andreagudo** [comment]
Testei com a sessões ordinárias de 29/09/2014 e 23/04/2012 e Extraordinária de 23/12/2013. Parece ocorrer em todas.

**Comment by edwardoliveira** [comment]
Isso é problema de migração. Se vc entrar nas listas de presença de cada uma delas, marcar algumas e salvar, elas aparecerão tanto no resumo quanto no PDF da sessão.

**Comment by LucianoAlmeida** [comment]
Aparentemente a base de dados antiga não estava refletindo a migração dessa lista de presenças. Fazendo testes localmente, o @marciomazza e eu descobrimos que agora está sendo migrado, portanto essa issue será fechada. Quando a nova base de dados for colocada para homologação, se este problema persistir, peço para que abra novamente esta issue.

**Comment by andreagudo** [comment]
Resolvido.
