### ISSUE TITLE
Pdf do resumo da sessão: uniformizar espaçamento

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1002]
Uniformizar o espaçamento entre os títulos de cada uma das partes dos Expedientes da sessão e seus conteúdos.

**Comment by edwardoliveira** [comment]
Até onde eu sei, as partes do Expediente são um texto único que é impresso. Assim, não sei se é possível fazer isso, pra falar a verdade.

**Comment by andreagudo** [comment]
Deve ter como, pois entre o conteúdo de Correspondência Expedida e Oradores do Pequenos Expediente há um espaço que foge ao padrão. Mas talvez a issue #1003 deve ser resolvida antes.
![captura de tela de 2017-04-11 14 39 37](https://cloud.githubusercontent.com/assets/19169882/24922506/f45f03aa-1ec4-11e7-8e85-f405044e3d01.png)

**Comment by edwardoliveira** [comment]
Seria colocar mais uma quebra de linha antes dos títulos (Apreciação Ata, Tribuna Livre, Correspondência Expedida, Expedientes Diversos, etc)?

**Comment by andreagudo** [comment]
Penso que sim.

**Comment by edwardoliveira** [comment]
Adicionei uma quebra de linha ANTES do título. Precisaria adicionar uma DEPOIS? 

Por sinal, seria interessante ver este caso específico da imagem acima. Qual o dia, mês e ano dessa sessão?

**Comment by andreagudo** [comment]
Sessão de 29/09/2014. Agora funcionou, inclusive para outras sessões. Seria bom uniformizar o espaçamento entre os títulos e conteúdos das demais partes, onde não há espaçamento (Informações Básicas, Mesa Diretora, Lista de Presença da Sessão, Matérias do Expediente, Oradores do Expediente, Lista de Presença da Ordem do Dia, Matérias da Ordem do Dia e Oradores das Explicações Pessoais)

**Comment by edwardoliveira** [comment]
@andreagudo Fecha se o espaçamento está OK. Senão, reabrir.

**Comment by andreagudo** [comment]
Resolvido.
