### ISSUE TITLE
Pdf da sessão: ordem das partes dos Expedientes está incorreta

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1003]
A ordem das partes dos Expedientes no pdf da sessão não corresponde à ordem do resumo.

**Comment by edwardoliveira** [comment]
São todas? Teria como fornecer uma sessão de exemplo?

**Comment by andreagudo** [comment]
Penso que em todas. Exemplo da sessão de 11/11/2013:
![captura de tela de 2017-04-11 14 57 46](https://cloud.githubusercontent.com/assets/19169882/24923248/54532f8c-1ec7-11e7-9197-a498c5b81176.png)

**Comment by eduardocalil** [comment]
@andreagudo Você pode explicar com mais detalhes o problema?

**Comment by andreagudo** [comment]
Veja na sessão de 11/11/2013. A ordem em que aparecem as partes dos Expedientes (Apreciação de Atas, Correspondência Expedida, ....) , no pdf do resumo não corresponde à ordem do resumo. Isso é importante, pois se trata da cronologia da sessão.

**Comment by edwardoliveira** [comment]
Favor verificar se está OK agora.

**Comment by andreagudo** [comment]
Resolvido.
