### ISSUE TITLE
PDF da sessão: resultados da votação não corresponde ao do resumo

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1004]
Isso vale para Matérias do Expediente e para Ordem do Dia. Testei para a Sessão Ordinária de 29/09/2014.

**Comment by edwardoliveira** [comment]
@andreagudo Favor verificar se foi consertada, por favor. Reabrir caso contrário.

**Comment by andreagudo** [comment]
Resolvido.

**Comment by edwardoliveira** [comment]
Mantém aberta???

**Comment by andreagudo** [comment]
Não, fecho. Foi engano.
