### ISSUE TITLE
Matérias Legislativas sem autoria

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1005]
Matérias Legislativas sem autoria registrada.

**Comment by edwardoliveira** [comment]
São todas? Teria como fornecer uma sessão de exemplo?

**Comment by andreagudo** [comment]
Todas.

**Comment by eduardocalil** [comment]
@andreagudo Poderia explicar melhor essa issue?

**Comment by andreagudo** [comment]
Não há autor em nenhuma matéria. Deve ser problema de migração.

Em 17/04/2017 11:49, "eduardocalil" <notifications@github.com> escreveu:

**Comment by eduardocalil** [comment]
Ok. Então é com o @LucianoAlmeida

**Comment by edwardoliveira** [comment]
@andreagudo Não aparece no detalhe da Matéria, certo? Não aparece no relatório também?

**Comment by andreagudo** [comment]
Isso eu não havia percebido. Mas testei há pouco, está resolvido.
