### ISSUE TITLE
Sessão Plenária: sem resultado da votação na Ordem do Dia

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1006]
Não aparecem os resultados das votações na Ordem do Dia, apesar de o sistema informar corretamente, nos dados das matérias legislativa, a data em que foi votada. Pode ser problema de migração. Testado com a Sessão Ordinária de 29/09/2014.

**Comment by andreagudo** [comment]
Questão já tratada na issue #604

**Comment by edwardoliveira** [comment]
@andreagudo Oi André, favor verificar se essa questão foi resolvida. Obrigado!

**Comment by andreagudo** [comment]
Resolvida.
