### ISSUE TITLE
PDF da sessão: resultado da votação em parte errada da sessão

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1007]
A data da votação está correta, disponível nos dados da matéria legislativa. Lá, essa data é um link que leva às Matérias da Ordem do Dia da sessão em que a matéria foi votada. Aí, porém, não consta o resultado, como relatado na issue #1006 . No pdf, porém, o resultado aparece corretamente na Ordem do Dia. Mas também aparece, indevidamente, nas Matérias do Expediente, já que em Agudo não são votadas matérias nesta parte da sessão. Testado com a sessão de 29/09/2014.

**Comment by edwardoliveira** [comment]
@andreagudo Veja se essa issue foi consertada, por favor.

**Comment by andreagudo** [comment]
Resolvida em parte. No Resumo não aparecem as Observações. No pdf não pude testar, pois deu o seguinte erro:
ExpatError at /relatorios/278/sessao-plenaria

not well-formed (invalid token): line 102, column 216

Request Method: 	GET
Request URL: 	http://sapl31agudo.interlegis.leg.br/relatorios/278/sessao-plenaria
Django Version: 	1.9.12
Exception Type: 	ExpatError
Exception Value: 	

not well-formed (invalid token): line 102, column 216

Exception Location: 	/usr/lib/python3.4/xml/dom/expatbuilder.py in parseString, line 223
Python Executable: 	/var/interlegis/.virtualenvs/sapl/bin/python3
Python Version: 	3.4.3
Python Path: 	

['/var/interlegis/sapl',
 '/var/interlegis/.virtualenvs/sapl/bin',
 '/var/interlegis/sapl',
 '/var/interlegis/.virtualenvs/sapl/lib/python3.4',
 '/var/interlegis/.virtualenvs/sapl/lib/python3.4/plat-x86_64-linux-gnu',
 '/var/interlegis/.virtualenvs/sapl/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/var/interlegis/.virtualenvs/sapl/lib/python3.4/site-packages']

Server time: 	Seg, 17 Abr 2017 16:19:01 -0300

**Comment by edwardoliveira** [comment]
Esse erro no PDF é a issue https://github.com/interlegis/sapl/issues/1009 que ainda não consegui identificar o que pode estar causando o erro. :disappointed_relieved: Vou dedicar a tarde pra tentar identificar que caracter pode estar causando o erro. Esse relatório PDF abre no SAPL 2.5?

**Comment by andreagudo** [comment]
Agora está abrindo para o pdf para 29/09/2014.

**Comment by edwardoliveira** [comment]
@andreagudo Favor verificar se o erro em http://sapl31agudo.interlegis.leg.br/relatorios/278/sessao-plenaria foi corrigido. Verei o restante dessa issue em breve!

**Comment by edwardoliveira** [comment]
@andreagudo Saberia me dizer se essas observações aparecem no PDF? Que observações são essas? Dos expedientes? Da votação?

**Comment by andreagudo** [comment]
Me equivoquei, a sessão que tem tal erro é a ordinária de 09/06/2014, por exemplo. As observações aparecem no pdf, abaixo do resultado da votação (no caso de Agudo, na Ordem do Dia). Mas também devem aparecer nos Expedientes, pois há quem faça votações nessa parte da sessão.

**Comment by andreagudo** [comment]
Esclarecendo: as observações aparecem na tela Ordem do Dia, mas não no resumo.

**Comment by andreagudo** [comment]
As observações aparecem no pdf e na Ordem do Dia, mas não no resumo.

**Comment by edwardoliveira** [comment]
@andreagudo Essa issue foi resolvida?

**Comment by andreagudo** [comment]
Resolvido.
