### ISSUE TITLE
Pdf da sessão: ementa repetida no campo Resultado da Votação

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1008]
Isso ocorre tanto nas Matérias do Expediente quanto na Ordem do Dia. Testado com a Sessão Ordinária de 16/03/2015.

**Comment by edwardoliveira** [comment]
@andreagudo André, essa repetição aparece porque o relatório imprime logo abaixo do resultado o campo observação_resultado. Este campo está sendo preenchido com a ementa da matéria votada. Quando eu tiro esse campo fica assim:

![image](https://cloud.githubusercontent.com/assets/9326037/24924040/d2646358-1ec9-11e7-8872-715a1a2b8def.png)

Pelo que vc conhece dos usos é pra tirar a impressão dessa observação mesmo??? /cc @LeandroRoberto

**Comment by andreagudo** [comment]
Não há mais ementa repetida. Mas o campo Observação deve pemanecer para algum registro sobre a votação. No nosso caso, usamos para o resultado da votação de emendas. Mas nunca preenche-lo com a ementa.
