### ISSUE TITLE
Migração Base - Parlamentares

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1010]
Está sendo migrado para o 3.1 parlamentares que no 2.5 estão com ind_excluido = 1

**Comment by DTILegBG** [comment]
mas nem todos, exemplo: o id 51 não foi migrado
![image](https://cloud.githubusercontent.com/assets/13314947/25089695/9298848a-2355-11e7-90b9-1e8fd70b1767.png)
Enquanto os id 41 e 42 foram migrados

**Comment by LucianoAlmeida** [comment]
Esse problema semelhante ao relatado na issue #1013, veja o comentário https://github.com/interlegis/sapl/issues/1013#issuecomment-294498523 para entender o que está acontecendo.

Em resumo, a migração está correta. O problema é de inconsistência nos dados do banco do sapl 2.5.
