### ISSUE TITLE
Sessão - Observações junto ao resultado de votação

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1011]
Colocar as observações da votação junto ao resultado de votação  nas matérias do expediente e da ordem, como é feito no 2.5. A observação está sendo gravada e recuperada, porém não está sendo mostrada para o usuário anônimo
![image](https://cloud.githubusercontent.com/assets/13314947/25089188/21f56098-2352-11e7-810a-e3678e43e3e4.png)

**Comment by edwardoliveira** [comment]
@andreagudo @DTILegBG Eu retirei a observação porque o texto da observação estava vindo com o mesmo conteúdo do texto da ementa, issue #1008 Entre em acordo pra ver se volta ou não?

**Comment by DTILegBG** [comment]
Aqui usamos o campo observação para descrever votação

Segue:

http://sapl.camarabento.rs.gov.br/consultas/sessao_plenaria/agenda_sessao_plen_mostrar_proc?cod_sessao_plen=355&dat_sessao=03/04/2017

Matérias da ordem do dia, 2


Para constar, a observação está em sessao_registrovotacao coluna 
observacao e o conteúdo foi migrado correto do sapl 2.5


Em 17/04/2017 12:57, Edward escreveu:

**Comment by edwardoliveira** [comment]
Tá. Mas se voltar esse campo, volta o bug #1008. E aí, volta @andreagudo ?

**Comment by andreagudo** [comment]
Não sei se volta, mas não deveria. O campo Observação nada tem a ver com a ementa. Então, tal campo deve ficar, recurando a oservação registrada na votação. Como ocorre para o PL 18/2017, em http://sapl.agudo.rs.leg.br/consultas/sessao_plenaria/materias_ordem_dia_sessao_form?cod_sessao_plen=278&dat_sessao= .

**Comment by edwardoliveira** [comment]
Eu acabei de subir uma mudança que verifica se os textos são iguais e daí não imprime se este for o caso, mas posso verificar se a observação da votação está pegando do lugar certo agora.

**Comment by DTILegBG** [comment]
resolvido

**Comment by andreagudo** [comment]
Tenho que reabrir. As Observações aparecem na Ordem do Dia e no pdf. Mas não no Resumo da sessão.

**Comment by edwardoliveira** [comment]
@andreagudo Vê se foi agora.

**Comment by DTILegBG** [comment]
Resolvido !!
