### ISSUE TITLE
Migração - Tipo documento Administrativo

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1013]
Migrou para o 3.1 o tipo documento administrativo parecer que estava com ind_excluido no 2.5
![image](https://cloud.githubusercontent.com/assets/13314947/25089545/8b560612-2354-11e7-83cc-15f2e5a7a2d5.png)

os outros que estavam com ind_excluido não foram migrados

**Comment by LucianoAlmeida** [comment]
Isso não é um erro de migração. Esse é um problema recorrente de inconsistência nas bases de dados do sapl 2.5, praticamente todas as bases em que testamos tem algum problema semelhante.

No sapl 3.1, temos todas as FKs protegidas contra exclusão do tipo cascade que faria uma exclusão não somente do objeto desejado, mas também de todos os que dependem dele. Esse é um ponto muito importante durante a migração, principalmente para migração de documentos.

No sapl 2.5, quando um objeto era marcado para exclusão, nenhum dos que dependiam deste eram colocados junto para exclusão. Logo, nas primeiras versões da migração, muitos dados eram excluídos quando não deveriam, o que está errado.

Essa inconsistência apareceu primeiro durante a migração de documentos. O script de migração de documentos buscava um objeto para anexar o seu respectivo documento, mas, por vezes, esse objeto não existia por conta de sua exclusão indevida, pois algum dependente estava marcado para excluir e este também acabou sendo excluído.

Nessa versão mais atual da migração de dados, quando encontramos uma entrada marcada com ind_excluido = 1, tentamos excluir ela, mas como as FKs estão protegidas contra exclusão tipo cascade, se houver algum outro objeto que dependa deste, não podemos excluir. Como não foi possível excluir algo que estava marcado para exclusão, salvamos uma entrada nos Problemas da Migração e continuamos a migrar.
