### ISSUE TITLE
Corrigir view do Manual Online do Sistema

### ISSUE THREAD

**Issue by eliseuegewarth** [interlegis/sapl#1018]
A Ajuda do SAPL 31 esta com os links de redirecionamento em branco e dispara a seguinte exceção para os links válidos:
`HelpView is missing the permission_required attribute. Define HelpView.permission_required, or override HelpView.get_permission_required().`

**Comment by paulot12** [comment]
Onde está disponível o manual?

**Comment by edwardoliveira** [comment]
Que manual?

**Comment by marciomazza** [comment]
Existe uma ajuda online do sistema, em formato de manual. Os links de ajuda contextual apontam para esse "Manual" que foi migrado do sapl 2.5 sem muita revisão.

Além disso existe uma manual à parte, que está sendo revisado pelo Jefferson e logo estará disponível. Sugiro que futuramente a Ajuda do Sistema reflita esse manual à parte.

Essa issue trata simplesmente, pelo que estou entendendo, de ajustar uma view  para que a Ajuda do Sistema volte a funcionar.

**Comment by eduardocalil** [comment]
As telas de ajuda que foram implementadas até o momento são do SAPL 2.5. Esta issue poderá ser finalizada quando o manual que está sendo feito pelo Adalberto ficar pronto.

**Comment by 54adal** [comment]
Estamos terminando a revisão do Caderno de Exercícios para as oficinas de SAPL 3.1 que ocorrerão no ano que vem. Não chega a ser um manual! Trata-se de um caderno com exercícios práticos através de inclusão de dados fictícios num SAPL  de treinamento. Mas acredito que poderá ajudar na compreensão do sistema. Assim que estiver pronto, colocaremos no COLAB.
Esperamos terminar a revisão até  o Natal.
grato
Adal
