### ISSUE TITLE
Migração cria várias legislaturas, sessões plenárias e sessões legislativas indevidamente

### ISSUE THREAD

**Issue by cristian-longhi** [interlegis/sapl#1021]
Após a migração, foi identificado que o banco contém vários registros de sessão plenária indevidos:
![pesquisa de sessao plenaria](https://cloud.githubusercontent.com/assets/22030378/25195357/bed15742-2513-11e7-8153-19275137f499.png)
Ao consultar a Sessão Plenária, há somente uma matéria na ordem do dia. A mesma matéria no SAPL 2.5 não está vinculada a nenhuma sessão plenária. Parece que a migração cria uma legislatura, uma sessão legislativa e uma sessão plenária para cada matéria legislativa nesta situação.

**Comment by andreagudo** [comment]
No caso de Agudo, gerou uma legislatura que corresponde, na verdade, à sessão legislativa atual:
![captura de tela de 2017-04-20 14 07 39](https://cloud.githubusercontent.com/assets/19169882/25243404/4eaf71c2-25d3-11e7-822c-ed961a9c116c.png)

**Comment by LucianoAlmeida** [comment]
No atual processo de migração, este erro não aparecerá mais.
Peço para que testem novamente, e reportem em novas issues caso esse problema apareça novamente.

**Comment by marciomazza** [comment]
Como @LucianoAlmeida disse, nós mudamos a abordagem de migração em #1376 e esses erros não aparecerão mais. Caso percebam algum problema do tipo por favor reportem.
