### ISSUE TITLE
Erro ao selecionar outra legislatura

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1024]
![captura de tela de 2017-04-20 14 14 07](https://cloud.githubusercontent.com/assets/19169882/25243553/c8a86b50-25d3-11e7-96b4-b3ca7ed632bb.png)

**Comment by edwardoliveira** [comment]
@andreagudo O @eduardocalil refez essa parte de Mesa Diretora. Poderia verificar se ainda persiste este erro?

**Comment by andreagudo** [comment]
O erro persiste. Ocorre nas pesquisa da Mesa Diretora.

**Comment by edwardoliveira** [comment]
@eduardocalil Teria como olhar esse ticket também já que vc está olhando aquele outro bug em Mesa Diretora? :+1:

**Comment by eduardocalil** [comment]
@andreagudo Você poderia detalhar, por favor, o caminho que gera o erro? Onde você clicou, passo-a-passo. Para que possamos reproduzir o bug e descobrir o que está acontecendo.

**Comment by eduardocalil** [comment]
Essa issue é o mesmo problema da #1069 . O problema ocorre somente para usuário anônimo.

**Comment by andreagudo** [comment]
Resolvida.
