### ISSUE TITLE
Migração: todos os parlamentares como titular

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1026]
O campo "Ttular?" não havia no 2.5. Todos os parlamentares passaram, indevidamente, a ser titulares com a migração.

**Comment by LucianoAlmeida** [comment]
Está certo sobre a não existência do campo titular. Como ele não existia, não há o que ser migrado e ele assume o valor padrão, no caso verdadeiro, tornando todos os parlamentares titulares. Pra resolver esse bug, gostaria de saber uma coisa: o que torna um parlamentar titular?

**Comment by andreagudo** [comment]
O que torna um parlamentar titular é ter sido eleito na eleição. Isso é algo extra Câmara e, assim sendo, não há no SAPL algo que controle. Exceto essa informação "Titular", que está sendo implementada agora. Então, penso que isso terá que ser informado manualmente, parlamentar por parlamentar. Para legislaturas recentes é fácil, mas para as antigas...

**Comment by LucianoAlmeida** [comment]
Se não há realmente como saber pelos dados do banco se o parlamentar é titular, isso não é um problema de migração. Infelizmente não sei resolver esse problema.
