### ISSUE TITLE
Migração: parlamentar inexistente

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1027]
Na Legislatura 14 aparece o parlamentar Luiz Alves de Lima, que nunca existiu. Ocorre o mesmo em outras legislaturas, com outros parlamentares inexistentes. Em princípio, os que estão sem partido.

**Comment by LucianoAlmeida** [comment]
Essa entrada, assim como várias outras que deveriam ser excluídas, ainda existe porque conta de inconsistência nos bancos de dados legados, logo o problema não é da migração. Esses problemas devem ser resolvidos individualmente e com calma.
Leia o comentário que fiz na issue https://github.com/interlegis/sapl/issues/1013#issuecomment-294498523 para entender o porque dessa e outras entradas ainda existirem.

**Comment by andreagudo** [comment]
Bem, são os seguintes os parlamentares inexistentes:
Legislatura 11: A, A e Mauro Marques
Legislatura 14: Luiz Alves de Lima
Legisaltura 12: Arnaldo Kilian (há dois, somente o KiLLian é correto)

**Comment by LucianoAlmeida** [comment]
Eu entendi seu questionamento, eles realmente estão marcados para ser excluídos, porém eles **não podem ser excluídos**, por isso ainda existem.

Vamos pegar o caso do parlamentar Luiz Alves de Lima. Este parlamentar está sendo referenciado por:
1. Dependentes Maria Cristina de pk=1 e João Paulo de pk=2;
2. Mandato de pk=1;
3. ComposicaoMesa de pk=1;
4. Participacao (do app comissoes) de pk=1 e pk=3.

Logo, para eu poder excluir esse parlamentar, tenho que excluir primeiro **todas essas referências** citadas acima, porém estas referências **não estão marcadas para exclusão**!!! Logo, por causa da inconsistência do banco e para garantir a integridade do mesmo, eu **não posso excluir** este parlamentar durante a migração!
Novamente, esse é um erro de inconsistência do banco, não da migração. Essa entrada está marcada nos problemas da migração quando entra no painel de administradores, que serve como um lembrete de que há erros e eles devem ser verificados um a um e com cuidado.

**Comment by LucianoAlmeida** [comment]
Este erro, assim como comentado na issue #1021, não deverá aparecer novamente.

**Comment by marciomazza** [comment]
Como @LucianoAlmeida disse, nós mudamos a abordagem de migração em #1376 e esses erros não aparecerão mais. Caso percebam algum problema do tipo por favor reportem.
