### ISSUE TITLE
Migração: muitas comissões ativas

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1028]
Indevidamente. No 2.5 há o campo Situação, com as opções ativa, inativa e extinta.

**Comment by LucianoAlmeida** [comment]
Poderia dar exemplos? Não entendi direito o problema.

**Comment by andreagudo** [comment]
Primeiro, aqui também parace haver comissões demais.
Segundo, a situação de Agudo é a seguinte, segundo o 2.5, abaixo. O que define a situação é a data de extinção.
![captura de tela de 2017-04-24 15 09 46](https://cloud.githubusercontent.com/assets/19169882/25351883/69bd01e8-2900-11e7-9f93-5401f8a4c10e.png)

**Comment by LucianoAlmeida** [comment]
Esse problema já foi resolvido na issue #831.
Aparentemente isso é um problema da de dados migrada do 3.1 que é antiga. Na próxima migração feita já deverá estar funcionando corretamente.

**Comment by andreagudo** [comment]
Ainda não funcionou, todas estão ativas. No 2.5 não há opção ativa/inativa, apenas "Data Extinção" e "Data Término".  Se Data Extinção ou Data Término forem válidas, a situação das comissões são, respectivamente, Extinta e Inativa. Caso contrário, é ativa.  No 3.1 é diferente, há possibilidade de mudar a situação optando entre ativa/inativa, o que gerou esse problema na migração.

**Comment by LucianoAlmeida** [comment]
@LeandroRoberto, esse campo de situação do SAPL 2.5 tornou-se apenas um booliano chamado ativo no 3.1. Ele não mostra se a situação está extinta, apenas se está ativa ou inativa. A modelagem está errada então?

**Comment by andreagudo** [comment]
A ser revolvida pela #1209
