### ISSUE TITLE
Migração - Resultado de votação matérias da ordem do dia

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1029]
SAPL 2.5
http://sapl.camarabento.rs.gov.br/consultas/sessao_plenaria/materias_ordem_dia_sessao_form?cod_sessao_plen=356&dat_sessao=10/04/2017

SAPL 3.1
http://sapl3beta.camarabento.rs.gov.br/sessao/356/ordemdia

Imagem Logado
![image](https://cloud.githubusercontent.com/assets/13314947/25348418/8bc04aa4-28f4-11e7-8a97-848f0672793e.png)

Clicando no link "aprovado por unanimidade"
é apresentado um server erro 500

**Comment by LucianoAlmeida** [comment]
No link que me passou do sapl 3.1, nessa ordem nº 2 - "Ementa nº 5 de 2017" - não estou conseguindo ver esse link Aprovado por Unanimidade. Ele está como "Não há resultado"
Nos demais resultados, não há links também. @edwardoliveira, isso deveria ser assim mesmo?
Esse erro tem mesmo relação com migração?

**Comment by LucianoAlmeida** [comment]
@DTILegBG, gostaria que revisasse essa issue. Segundo o Edward, esse era um erro de tela e foi concertado ontem.

**Comment by DTILegBG** [comment]
sim, está resolvido, na verdade não era problema de migração. Obrigado
