### ISSUE TITLE
Autorização

### ISSUE THREAD

**Issue by eduardoedson** [interlegis/sapl#103]
Implementar autorização de todo o sistema:
* definir roles
* definir permissões
* ajustar cada interface para atender às permissões

**Comment by edwardoliveira** [comment]
@eduardoedson Agora que temos uma tela de login prestes a ser integrada ao master ( #316 ), talvez esteja na hora de começarmos a olhar isso.

**Comment by eduardocalil** [comment]
Conversando com o Morale, ele me passou as seguintes informações:

Devem ser criadas as permissões citadas abaixo:

1. **Administrador**

-Pode cadastrar novos usuários, somente. 

- Não possui as permissões dos operadores, pode cadastrar. 


2. **Operador Geral**

- Tem todas as permissões sobre todos os módulos/apps.


3. **Operador de Protocolo**

- Pode operar somente no módulo Protocolo.

4. **Operador de Sessão**

- Pode operar somente no módulo Sessão.

5. **Operador de Comissão**

- Pode operar somente no módulo Comissão.

6. **Autor**

- Pode criar novas Proposições.

**Comment by eduardocalil** [comment]
Além disso, algum operador pode acumular permissões. Por exemplo, ter permissões sobre protocolo e sessão.

**Comment by eduardocalil** [comment]
Também é um desejo da comunidade que, para o futuro, seja implementada uma permissão específica por Comissão.

**Comment by eduardoedson** [comment]
Esses usuários tem permissão para criar/editar e a permissão de deletar fica só pro Operador Geral?
@marciomazza @morale

**Comment by eduardocalil** [comment]
Posteriormente deve ser feita a camada de negócios da Autorização de Proposições. Pois um Autor só pode ver suas Proposições.

**Comment by LeandroRoberto** [comment]
Vale dar uma olhada nessa ferramenta... https://pypi.python.org/pypi/rules
São os predicados... uma das possibilidades é encapsular informação por usuário... conheci ela através do wikilegis

**Comment by andreagudo** [comment]
O operador_autor está tendo acesso indevido às Tabelas Auxiliares.
