### ISSUE TITLE
Resultado Votação

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1031]
Logado, clicando nos detalhes da votação das matérias da ordem do dia, o "resultado da votação" não é exibido

![image](https://cloud.githubusercontent.com/assets/13314947/25351255/822dcd36-28fe-11e7-8943-b632e5c48c51.png)

**Comment by edwardoliveira** [comment]
@DTILegBG Atualize aí e veja se resolveu. Caso contrário, favor reabrir a issue. :+1:

**Comment by DTILegBG** [comment]
@edwardoliveira ainda não resolveu

**Comment by edwardoliveira** [comment]
Me dá um exemplo de sessão onde não aparece o resultado de votação, por favor. Estou testando com a tua base de dados hoje.

**Comment by edwardoliveira** [comment]
@DTILegBG Existia *dois* problemas com esse bug. O primeiro é o que vc descreveu e o segundo é que na listagem da tela anterior a descrição dos resultados estava errada. Teria como verificar se os resultados dessa sessão batem? Isto é, entre o 2.5 e o 3.1? Obrigado!
