### ISSUE TITLE
Adicionar matéria ordem do dia

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1032]
Ao adicionar matéria na ordem do dia, quando já existem matérias adicionadas ao expediente, ao informar um numero da ordem para matéria da ordem do dia que já exista uma matéria adicionada ao expediente, o sistema retorna erro

**Comment by edwardoliveira** [comment]
Não entendi essa descrição.

"ao informar um numero da ordem para matéria da ordem do dia que já exista uma matéria adicionada ao expediente" 

**Vc quer dizer que nas matérias do expediente existe uma matéria cadastrada um número de ordem 1, e daí se for inserida uma OUTRA matéria na ordem do dia com número de ordem 1 e dá erro????**

**Comment by DTILegBG** [comment]
Isso ai

Em 2017-04-25 12:11, Edward escreveu:

**Comment by edwardoliveira** [comment]
Vê se consertou, por favor. Se não eu abro de novo.

**Comment by DTILegBG** [comment]
agora gera erro 500


  Server Error (500)


Em 26/04/2017 11:14, Edward escreveu:

**Comment by edwardoliveira** [comment]
Vc tem que colocar DEBUG=True no ".env" e reiniciar o servidor pra mensagem de erro aparecer. Teria como fazer isso? 

Quando o DEBUG=False só dá o código 500 que não adianta nada!

**Comment by DTILegBG** [comment]
até mesmo quando não existe matéria na mesma posição no expediente


Em 26/04/2017 11:14, Edward escreveu:

**Comment by DTILegBG** [comment]
claro !


Em 26/04/2017 11:25, Edward escreveu:

**Comment by edwardoliveira** [comment]
Cometi um erro na nomeação de variável. Subi um fix.
