### ISSUE TITLE
Anular votação matéria da ordem do dia

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1033]
Ao escolher "anular votação "sim e salvar o sistema volta e continua a mostrar na tela o resultado da votação, clicando no link logado apresenta erro 500

**Comment by edwardoliveira** [comment]
Eu tentei simular esse erro em uma sessão aqui e não consegui. Anulei a votação da matéria e daí voltou pra tela abaixo:

![image](https://cloud.githubusercontent.com/assets/9326037/25391686/2ff51484-29ad-11e7-9a13-0490e46ee69d.png)

*Vc consegue reproduzir esse erro consistentemente?*

**Comment by DTILegBG** [comment]
Sim, estou testando na base importada...


Em 25/04/2017 11:49, Edward escreveu:

**Comment by edwardoliveira** [comment]
Então me passa umas sessões pra testar aqui...

**Comment by edwardoliveira** [comment]
@DTILegBG OK, não estou afirmando que essa issue está consertada. Acho que ainda tem uns erros que podem ser de modelagem, lógica da tela ou importação dos dados (devo ver isso amanhã). Teria como verificar se o comportamento descrito nessa issue foi solucionado? Mesmo que tenha sido eu tenho umas dúvidas sobre a modelagem e lógica que vou verificar.

**Comment by DTILegBG** [comment]
Agora parece que está tudo normal.
