### ISSUE TITLE
INTEGRAÇÃO

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1034]
Integração entre o SAPL 3.1 e o e-mail oferecido pelo Interlegis. É possível enviar as proposições aprovadas nas reuniões pelo e-mail?

**Comment by edwardoliveira** [comment]
*Não.*

Mas isso está no nosso radar. Vc mesmo abriu essa issue anteriormente #912  e vamos trabalhar nisso assim que desafogarmos aqui. Estamos sem pessoal pra tocar todas as idéias, infelizmente. E a comunidade, com raríssimas exceções, só sabe pedir sem oferecer nenhuma ajuda em troca. :disappointed:

Mas a idéia é boa! Só vou fechar essa issue é uma duplicata de #912 

Até mais,
