### ISSUE TITLE
Migração: comissões inexistentes

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1035]
Questão semelhante à #1027 , relativa a parlamentares. As inexistente são: Comissão de Educação, Comissão de Redação e Comissão de Segurança.

**Comment by LucianoAlmeida** [comment]
Não entendi a pergunta... Essas comissões estão sendo migradas indevidamente ou não estão sendo migradas quando deveria?
Vendo aqui seu banco do sapl 2.5, essas comissões citadas estão marcadas para exclusão, o que justifica a não migração delas.

**Comment by LucianoAlmeida** [comment]
O comentário https://github.com/interlegis/sapl/issues/1027#issuecomment-297453862 que fiz na issue semelhante dos parlamentares.
Esse, aparentemente, não é um problema de migração, mas de inconsistência da sua base de dado. Ela deve ser tratada com calma e cuidado para manter a integridade do banco.

**Comment by andreagudo** [comment]
As comissões que mencionei não devem ser migradas.

**Comment by LucianoAlmeida** [comment]
Então teremos que fazer as mudanças na mão, porque a migração **exige** que ela exista, por isso ainda está sendo migrada.

**Comment by LucianoAlmeida** [comment]
Este erro, assim como comentado nas issues #1021 e #1027 não deverá mais aparecer.

**Comment by marciomazza** [comment]
Como @LucianoAlmeida disse, nós mudamos a abordagem de migração em #1376 e esses erros não aparecerão mais. Caso percebam algum problema do tipo por favor reportem.
