### ISSUE TITLE
Migração: dados que aparecem no rodapé

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1036]
![captura de tela de 2017-04-25 09 27 56](https://cloud.githubusercontent.com/assets/19169882/25385200/a09faa1e-2999-11e7-87d0-a82fc50fb8c1.png)

**Comment by LucianoAlmeida** [comment]
Se não me engano, isso é migrado junto com os documentos, assim como o brasão (issue #1040). Está com problemas porque essa máquina de homologação não possui essa migração de documentos ainda.

**Comment by LucianoAlmeida** [comment]
Essas informações não parecem estar nem no banco de dados, nem no banco de documentos. Após fazer a migração de documentos, essas são as mensagens que aparece, indicando devem ser preenchida a mão:

Nome da Casa Legislativa:
![image](https://cloud.githubusercontent.com/assets/4074173/26016105/08fc069a-373a-11e7-83fd-6ea9e9017443.png)

Dados da Casa Legislativa:
![image](https://cloud.githubusercontent.com/assets/4074173/26016383/2786abc8-373b-11e7-9d09-aefccc234505.png)

**Comment by andreagudo** [comment]
Resolvida.
