### ISSUE TITLE
Migração: normas relacionadas não aparecem

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1038]
Ou não foram migradas corretamente?

**Comment by andreagudo** [comment]
Mas houve nova migração de Agudo, acesso dados de 2017.

**Comment by andreagudo** [comment]
Testado hoje. Há matérias com parte dos relacionamentos migrados e com nenhum relacionamento migrado (P. ex., Leis 734/1990 e 732/1990, respectivamente).

**Comment by LucianoAlmeida** [comment]
Olá @andreagudo, seria possível me enviar algum tipo de link desses relacionamentos que estão com problema?

**Comment by andreagudo** [comment]
Os links abaixo são das mesmas normas acima mencionadas.

http://sapl31agudo.interlegis.leg.br/norma/pesquisar?tipo=1&numero=734&ano=&data_0=&data_1=&data_publicacao_0=&data_publicacao_1=&ementa=&assuntos=&salvar=Pesquisar

http://sapl31agudo.interlegis.leg.br/norma/pesquisar?tipo=1&numero=732&ano=&data_0=&data_1=&data_publicacao_0=&data_publicacao_1=&ementa=&assuntos=&salvar=Pesquisar

**Comment by LucianoAlmeida** [comment]
Essa issue foi resolvida no PR #1321. O problema era por conta do campo ind_excluido, que esperava-se que fosse do tipo inteiro, mas na tabela de vinculo_norma_juridica era do tipo char.

**Comment by andreagudo** [comment]
Resolvida.
