### ISSUE TITLE
Listas de presenças a sessões e Ordem do Dia

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1039]
Usar os nomes parlamentares, não os verdadeiros, como é feito no 2.5.

**Comment by DTILegBG** [comment]
http://sapl3beta.camarabento.rs.gov.br/sessao/171/presencaordemdia
São mostrados como presença na ordem do dia  e como presença na sessão, só os parlamentares que estão ativos hoje, para sessões anteriores isso gera problemas

**Comment by andreagudo** [comment]
No caso de Agudo não há o problema de aparecer só os ativos nas listas de sessões anteriores.

**Comment by DTILegBG** [comment]
![tela](https://cloud.githubusercontent.com/assets/13314947/25481510/de6e6886-2b23-11e7-9c2f-d1cd93a6520b.PNG)

![banco](https://cloud.githubusercontent.com/assets/13314947/25481517/e4863924-2b23-11e7-970d-fc5bb748b744.PNG)

**Comment by DTILegBG** [comment]
e o mesmo para presença da ordem do dia

![base](https://cloud.githubusercontent.com/assets/13314947/25482290/87e03a54-2b27-11e7-93d1-ca39af174635.PNG)
![telaordem](https://cloud.githubusercontent.com/assets/13314947/25482292/8adf95a6-2b27-11e7-8c0c-2e85fbea3e8a.PNG)

**Comment by edwardoliveira** [comment]
@andreagudo Favor verificar se foi resolvido (visualização e edição), por favor.

@DTILegBG Façamos assim: vc poderia criar uma outra issue (com a descrição e screenshot que vc postou acim) para discutirmos e tentar encontrar um jeito de compatibilizar os parlamentares antigos e novos?

**Comment by andreagudo** [comment]
No caso de Agudo não havia esse problema.

**Comment by andreagudo** [comment]
Resolvido.

**Comment by andreagudo** [comment]
Esse problema passou a ocorrer para Agudo depois da migração de 05/06/2017.

**Comment by eliseuegewarth** [comment]
@andreagudo O foco dessa issue é colocar o nome de parlamentar na lista de presença e Ordem do dia certo?

**Comment by andreagudo** [comment]
O foco da issue é colocar o nome parlamentar (Cardosinho, Titirica, João das Couves, etc...). Considero resolvida.
