### ISSUE TITLE
Migração: dados do cabeçalho

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1040]
Brasão não migrou, nem o tipo da casa legisaltiva.
![captura de tela de 2017-04-26 09 45 35](https://cloud.githubusercontent.com/assets/19169882/25435262/d1fea3d6-2a65-11e7-9500-fb461f6b98ed.png)

**Comment by LucianoAlmeida** [comment]
O brasão é importado após fazer a migração dos documentos, que é feito por um script diferente do de migração de dados. O brasão não está aparecendo na máquina de homologação porque essa migração de documentos não foi realizada ainda.

**Comment by andreagudo** [comment]
Resolvida.
