### ISSUE TITLE
Partido do parlamentar no resumo da sessão

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1041]
Não aparecer o partido do parlamentar no resumo da sessão, na Mesa Diretora e nas listas de presença na sessão e na Ordem do Dia. No 2.5 está assim
![captura de tela de 2017-04-26 09 54 27](https://cloud.githubusercontent.com/assets/19169882/25435439/6392e1e0-2a66-11e7-9cc0-b87f0ccb8b80.png)

**Comment by edwardoliveira** [comment]
@andreagudo Favor verificar se ficou faltando algum lugar.

**Comment by andreagudo** [comment]
Resolvido.
