### ISSUE TITLE
Resumo da sessao

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1043]
Os oradores devem ficar na mesma coluna
![captura de tela de 2017-04-26 10 24 47](https://cloud.githubusercontent.com/assets/19169882/25436751/ab8d2448-2a6a-11e7-8613-3249efb2beb1.png)

**Comment by edwardoliveira** [comment]
@andreagudo Veja se solucionou o problema. Favor testar com várias sessões, de preferência com e sem info de discurso. :+1:

**Comment by andreagudo** [comment]
O problema persiste. Não usamos o campo do discurso.

**Comment by andreagudo** [comment]
Resolvido.

**Comment by andreagudo** [comment]
Reabri por engano.
