### ISSUE TITLE
Erro ao gerar o pdf do resumo da sessão ordinária de 06/03/2017

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1044]
ExpatError at /relatorios/409/sessao-plenaria
not well-formed (invalid token): line 102, column 4213
Request Method:	GET
Request URL:	http://sapl31agudo.interlegis.leg.br/relatorios/409/sessao-plenaria
Django Version:	1.9.12
Exception Type:	ExpatError
Exception Value:	
not well-formed (invalid token): line 102, column 4213
Exception Location:	/usr/lib/python3.4/xml/dom/expatbuilder.py in parseString, line 223
Python Executable:	/var/interlegis/.virtualenvs/sapl/bin/python3
Python Version:	3.4.3
Python Path:	
['/var/interlegis/sapl',
 '/var/interlegis/.virtualenvs/sapl/bin',
 '/var/interlegis/sapl',
 '/var/interlegis/.virtualenvs/sapl/lib/python3.4',
 '/var/interlegis/.virtualenvs/sapl/lib/python3.4/plat-x86_64-linux-gnu',
 '/var/interlegis/.virtualenvs/sapl/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/var/interlegis/.virtualenvs/sapl/lib/python3.4/site-packages']
Server time:	Qua, 26 Abr 2017 10:22:47 -0300

**Comment by edwardoliveira** [comment]
@andreagudo Verifique se solucionou, por favor. Caso contrário pode reabrir.

**Comment by andreagudo** [comment]
Resolvida.
