### ISSUE TITLE
Migração: formato da hora de encerramento da sessão

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1045]
Sessão ordinária de 06/03/2017: Encerramento: 06/03/2017 - 21;01
Isso pode estar gerando o erro #1044 ?

**Comment by LucianoAlmeida** [comment]
Seria possível postar o link da entrada que contém o erro?

**Comment by andreagudo** [comment]
http://sapl31agudo.interlegis.leg.br/sessao/409

**Comment by andreagudo** [comment]
Resolvido.

**Comment by andreagudo** [comment]
Houve regressão depois da migração de 05/06/2017.

**Comment by andreagudo** [comment]
Não houve regressão. Estava errado no 2.5.
