### ISSUE TITLE
Erro em parser de relatório PDF

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#1046]
sessão ordinária 23/07/2017

 ValueError at /relatorios/413/sessao-plenaria
findSpanStyle not implemented in this parser
paragraph text '<para><span style="font-size: 11.424px; background-color: rgb(255, 255, 255);">Ata n</span><sup style="background-color: rgb(255, 255, 255);">os</sup><span style="font-size: 11.424px; background-color: rgb(255, 255, 255);">6/2017 e 7/2017: aprovadas por unanimidade.<br/></span></para>' caused exception
Request Method:  GET
Request URL:  http://sapl31agudo.interlegis.leg.br/relatorios/413/sessao-plenaria
Django Version:  1.9.12
Exception Type:  ValueError
Exception Value:  
findSpanStyle not implemented in this parser
paragraph text '<para><span style="font-size: 11.424px; background-color: rgb(255, 255, 255);">Ata n</span><sup style="background-color: rgb(255, 255, 255);">os</sup><span style="font-size: 11.424px; background-color: rgb(255, 255, 255);">6/2017 e 7/2017: aprovadas por unanimidade.<br/></span></para>' caused exception
Exception Location:  /var/interlegis/.virtualenvs/sapl/lib/python3.4/site-packages/reportlab/platypus/paraparser.py in findSpanStyle, line 1207
Python Executable:  /var/interlegis/.virtualenvs/sapl/bin/python3
Python Version:  3.4.3
Python Path:  
['/var/interlegis/sapl',
 '/var/interlegis/.virtualenvs/sapl/bin',
 '/var/interlegis/sapl',
 '/var/interlegis/.virtualenvs/sapl/lib/python3.4',
 '/var/interlegis/.virtualenvs/sapl/lib/python3.4/plat-x86_64-linux-gnu',
 '/var/interlegis/.virtualenvs/sapl/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/var/interlegis/.virtualenvs/sapl/lib/python3.4/site-packages']
Server time:  Qua, 26 Abr 2017 10:57:41 -0300

**Comment by edwardoliveira** [comment]
@andreagudo Veja se consertou, por favor.

Os caracteres de formatação no texto do expediente bagunçam **muito** a geração de relatório. Estou tentando ver se a "solução" que encontrei resolve essa issue e a issue #1009, mas precisamos checar mais relatórios e situações.

**Comment by andreagudo** [comment]
Informei a data errada da sessão, agora está corrigida. É 27/03/2017.
