### ISSUE TITLE
Migração: Assunto de matérias legislativas 

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1047]
O Assunto das matérias legislativas está com "??????????", apesar de não usarmos esse critério.

**Comment by LucianoAlmeida** [comment]
Isso significa que um Assunto da Matéria que não existia, mas era necessário, foi criado.
Novamente, erro de inconsistência do banco de dados legado.

**Comment by andreagudo** [comment]
Necessário? Nunca usamos tal campo.
