### ISSUE TITLE
Migração: status de matéria

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1048]
O status de matéria legislativa Autógrafo foi migrado como "??????????" e sigla "??????????".

**Comment by LucianoAlmeida** [comment]
Problema semelhante a esse: https://github.com/interlegis/sapl/issues/1047#issuecomment-298039679

**Comment by andreagudo** [comment]
Não creio que seja semelhante #1047 , pois usamos direto esse status Autógrafo.

**Comment by LucianoAlmeida** [comment]
As interrogações indicam que alguma entrada importante não existia e teve que ser criada pela migração.
Como não temos o conteúdo da entrada que foi necessária ser criada, colocamos a string "??????????" justamente pra indicar que isso foi criado durante a migração e que não sabemos o seu conteúdo. 
Como é criado algo que não existia durante a migração, ambos os casos (este e o de #1047) são semelhantes. Estes casos devem ser verificados com calma **após a migração** pois são entradas necessárias que não existiam.

**Comment by andreagudo** [comment]
Abaixo os status existentes no 2.5, lá está "Autógrafo".
![captura de tela de 2017-05-05 08 03 12](https://cloud.githubusercontent.com/assets/19169882/25743239/c13a5030-3169-11e7-9d8e-873ee333a79e.png)

**Comment by LucianoAlmeida** [comment]
Essa issue me ajudou a encontrar um problema no script de migração. Durante a migração, estava fazendo a busca pela última entrada de `StatusTramitacao`, porém este método estava me retornando um valor errado, por isso a entrada "Autógrafo" estava sendo substituido pelas interrogações. 
Contudo, essa entrada que possui várias interrogação continuará existindo, pois existe uma `Tramitacao` que não possui referência para nenhum `StatusTramitacao`, logo, por não haver referência e ser um campo obrigatório, tenho que criar um stub.

**Comment by andreagudo** [comment]
Embora o status Autógrafo agora esteja correto, continuar havendo um status "??????????"
![captura de tela de 2017-08-11 15 11 14](https://user-images.githubusercontent.com/19169882/29226197-7fe2e684-7ea7-11e7-92e7-545e0d754e2c.png)
