### ISSUE TITLE
Erro resultado votação matéria do expediente

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1049]
Sapl 3.1 matéria não votada
http://sapl3beta.camarabento.rs.gov.br/sessao/145/expedientemateria?page=1

SAPL 2.5  - Aprovado por unanimidade
http://sapl.camarabento.rs.gov.br/consultas/sessao_plenaria/agenda_sessao_plen_mostrar_proc?cod_sessao_plen=145&dat_sessao=12/08/2013

E pelo banco, a principio, a matéria está votada e aprovada por unanimidade

![capturar](https://cloud.githubusercontent.com/assets/13314947/25453291/bddb9a2e-2a9e-11e7-912f-4d596c342d49.PNG)

**Comment by edwardoliveira** [comment]
@LucianoAlmeida e @marciomazza esse parece ser um bug meio grave. Quando da migração, as matérias **votadas no expediente** foram salvas em RegistroVotacao na coluna **ordemdia_id** ao invés de ser no campo **expediente_id**.
