### ISSUE TITLE
Filiação Parlamentar

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1050]
Na lista de Parlamentares o parlamentar aparece sem partido e está correto
http://sapl3beta.camarabento.rs.gov.br/parlamentar/?pk=14

Porém no detalhe
http://sapl3beta.camarabento.rs.gov.br/parlamentar/22

Porem no detalhe como filiação aparece a ultima, mesmo tendo data de desfiliação.

**Comment by edwardoliveira** [comment]
Sim. Essa tela mostra o *histórico* de filiações, e não somente a última. A idéia é que possam ser cadastradas filiações partidárias antigas e não somente a última. É essa a dúvida ou entendi errado? Se entendi pode reabrir a issue.

![image](https://cloud.githubusercontent.com/assets/9326037/25488224/e15bc9e4-2b3c-11e7-8668-7ce2186eb5de.png)

**Comment by DTILegBG** [comment]
Sim, correto, porem falo do detalhe inicial do parlamentar

![detalhe](https://cloud.githubusercontent.com/assets/13314947/25488621/dce90830-2b3d-11e7-8667-5aad6d655c37.png)

**Comment by edwardoliveira** [comment]
ops, ok.

**Comment by edwardoliveira** [comment]
@DTILegBG Subi umas mudanças, mas acredito que ainda possam ter lugares onde o perfil do parlamentar está com filiação errada. Assim sendo, vou reabrir essa issue e daí teria como vc testar e verificar onde ainda está errado? Me passa os links e tal. Se estiver tudo OK pode fechar a issue.

**Comment by DTILegBG** [comment]
Resolvido!!
