### ISSUE TITLE
Erro na criação de uma proposição

### ISSUE THREAD

**Issue by falcao934jef** [interlegis/sapl#1053]
http://sapl31agudo.interlegis.leg.br

Erro encontrado ao tentar adicionar um "tipo de proposição"
Fluxo: Tabelas auxiliares -> Tipo de Proposição -> Adicionar tipo de proposição -> Inserir dados e tentar salvar.

![photo_2017-04-27_10-43-16](https://cloud.githubusercontent.com/assets/10059935/25486095/79692e5e-2b36-11e7-9f6a-07382315439b.jpg)

**Comment by edwardoliveira** [comment]
Eu testei aqui e funcionou. Ainda tá acontecendo esse erro?

**Comment by eduardocalil** [comment]
@falcao934jef

**Comment by falcao934jef** [comment]
Não está acontecendo o erro mais! Certinho aqui.
