### ISSUE TITLE
Parlamentares presentes na sessão e ordem do dia

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1054]
http://sapl3beta.camarabento.rs.gov.br/sessao/171/presencaordemdia
São mostrados como presença na ordem do dia e como presença na sessão, só os parlamentares que estão ativos hoje, para sessões anteriores isso gera problemas

![banco](https://cloud.githubusercontent.com/assets/13314947/25488423/57524d58-2b3d-11e7-86c8-59263bb67c99.PNG)
![tela](https://cloud.githubusercontent.com/assets/13314947/25488424/57534604-2b3d-11e7-8231-6be78a4eca1f.PNG)

**Comment by eduardocalil** [comment]
**Problema:**

Para todo Parlamentar existe uma **flag** booleana que diz se ele está ativo ou não. E essa é a condição para ele aparecer na lista de **Presentes**. Entretanto, este **NÃO** é um parâmetro adequado para saber se o Parlamentar estava **ativo** na Sessão em questão, pelo fato de ele mudar a cada Legislatura.

**Solução:**

 Uma solução seria somente listar Parlamentares os quais tiveram **Mandato** em vigor durante **Data** da Sessão. Entretanto, o vereador pode não estar ativo durante certos períodos de seu Mandato.
Sendo assim, a solução que eu pensei e gostaria de saber a opinião de vocês é:

- Criar, dentro de Mandato, uma tela que lista todos os **Períodos** nos quais o parlamentar esteve em atividade **durante** o mandato em questão.
- Sendo assim, listaria na **Presença** da Sessão somente os parlamentares que estavam ativos na época da Sessão. Ou seja, os parlamentares que o período em atividade coincidiu com a data da Sessão.

**Comment by eduardocalil** [comment]
@DTILegBG @andreagudo @LeandroRoberto @edwardoliveira

**Comment by andreagudo** [comment]
Primeiro, no 2.5 tal problema não existe.
Segundo, creio que a issue https://github.com/interlegis/sapl/issues/413 poderia solucionar esta questão, pois trata dos períodos de afastamento do parlamentar.

**Comment by DTILegBG** [comment]
No resumo das sessões a informação está correta, segue resumo da mesma sessão acima
![image](https://cloud.githubusercontent.com/assets/13314947/25995919/ed1b2a18-36ea-11e7-9f99-51a9ae0c46e2.png)

**Comment by andreagudo** [comment]
No pdf do resumo também está correto. Teria que ajustar nas Presenças à sessão e nas Presenças Ordem do Dia.

**Comment by cristian-longhi** [comment]
Algumas sugestões que podem encaminhar solução:
1) Manter somente os parlamentares que estão com mandato nesta legislatura e hoje como ativos, definindo como ativo = false todos com mandato apenas até a legislatura anterior e naturalmente os licenciados, suplentes, etc.;
2) A exibição para usuário anônimo não deve levar em consideração se o parlamentar está ativo ou não, somente o registro na tabela devida;
3) Na tela em que o operador logado registra a presença, poderia haver uma flag "exibir somente parlamentares ativos", marcada por padrão, para preenchimento durante a sessão plenária em tempo real. Caso necessário corrigir um dado antigo, o campo desmarcado exibiria todos os parlamentares da legislatura.
O que acham?

**Comment by DtiLegBG** [comment]
Resolvido !!
