### ISSUE TITLE
Pesquisa de matérias legislativas - adicionar informações

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1055]
Falta adicionar estas informações aos detalhes no resultado da pesquisa das matérias
Processo
Protocolo Geral - Data da Entrada
Ultima Ação (Texto da Ação - Ultima tramitação)

SAPL 3.1
![image](https://cloud.githubusercontent.com/assets/13314947/25494227/533a83a4-2b4f-11e7-9ca3-d3d8b69f8b51.png)
http://sapl3beta.camarabento.rs.gov.br/materia/pesquisar-materia?tipo=1&numero=&ano=2012&numero_protocolo=&data_apresentacao_0=&data_apresentacao_1=&data_publicacao_0=&data_publicacao_1=&autoria__autor=&autoria__autor__tipo=&relatoria__parlamentar_id=&local_origem_externa=&tramitacao__unidade_tramitacao_destino=&tramitacao__status=&em_tramitacao=&o=&materiaassunto__assunto=&ementa=&salvar=Pesquisar

SAPL 2.5
![image](https://cloud.githubusercontent.com/assets/13314947/25494243/62e7183a-2b4f-11e7-9808-0acd038d8e4e.png)
http://sapl.camarabento.rs.gov.br/generico/materia_pesquisar_proc?incluir=0&existe_ocorrencia=0&total_materias=%3CShared.DC.ZRDB.Results.Results+instance+at+0x7f1be865cc20%3E&lst_tip_materia=1&txt_numero=&txt_ano=2012&txt_npc=&txt_num_protocolo=&dt_apres=&dt_apres2=&dt_public=&dt_public2=&hdn_txt_autor=&hdn_cod_autor=&lst_tip_autor=&lst_cod_partido=&txt_relator=&txt_assunto=&rad_tramitando=&lst_localizacao=&lst_status=&rd_ordenacao=1&rd_ordem_td=1&chk_coautor=&btn_materia_pesquisar=Pesquisar

**Comment by edwardoliveira** [comment]
Eu não me lembro de ter visto esse campo `Processo` em algum model... Provavelmente foi renomado. Tem idéia de em qual coluna e tabela ele se encontra?

**Comment by DTILegBG** [comment]
O que é chamado de processo  na verdade é outras numerações
A informação vem daqui

https://github.com/interlegis/sapl/blob/master/sapl/materia/models.py#L440

Em 2017-04-27 17:40, Edward escreveu:

**Comment by DTILegBG** [comment]
tabela materia_numeracao coluna numero_materia


Em 27/04/2017 17:40, Edward escreveu:

**Comment by edwardoliveira** [comment]
@DTILegBG Verifica se solucionou, por favor.

**Comment by DTILegBG** [comment]
Resolvido
