### ISSUE TITLE
Protocolo - Mostrar nome do autor

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1057]
Exibir nome do autor do protocolo
Exemplo protocolo id 10304

![image](https://cloud.githubusercontent.com/assets/13314947/25498337/fb9ebff2-2b5d-11e7-9f31-e9c23b76a7f8.png)

![base-protocolo](https://cloud.githubusercontent.com/assets/13314947/25498441/59e12348-2b5e-11e7-9bec-bf3a925b86d2.PNG)

![nome-parlamentar](https://cloud.githubusercontent.com/assets/13314947/25498371/201bbfba-2b5e-11e7-9f9c-6212696652aa.PNG)

**Comment by edwardoliveira** [comment]
@DTILegBG Verifica se consertou, por favor. Para mais de um protocolo de preferência.:+1:

**Comment by DTILegBG** [comment]
Ok resolvido !!
