### ISSUE TITLE
Erro ao excluir um "Tipo de Proposição"

### ISSUE THREAD

**Issue by falcao934jef** [interlegis/sapl#1060]
Erro ao tentar excluir qualquer "Tipo de Proposição", os registros em que ele é referenciados não está sendo mostrado corretamente.

Sistema -> Tabelas Auxiliares -> Tipos de Proposição -> confirmar qualquer exclusão.

![image](https://cloud.githubusercontent.com/assets/10059935/25619191/6002f59c-2f20-11e7-9fb3-69cb4ab46c24.png)

**Comment by eduardocalil** [comment]
Fechei a issue. Confira se resolveu, por favor. Caso contrário reabra a mesma @falcao934jef

**Comment by falcao934jef** [comment]
@eduardocalil A referência a qual impossibilita a exclusão continua como "none/none" em caso de exclusão.

**Comment by edwardoliveira** [comment]
Eu esqueci de fazer a atualização da máquina. Agora está como abaixo. Vou fechar essa issue.

![image](https://cloud.githubusercontent.com/assets/9326037/25671997/5893de32-3008-11e7-9a17-8c74abcf699d.png)
