### ISSUE TITLE
Títulos incompletos em Assunto de Norma Jurídica

### ISSUE THREAD

**Issue by falcao934jef** [interlegis/sapl#1065]
No Módulo Normas Jurídicas - O assunto de Norma Jurídica se encontra com os títulos incompletos.

![image](https://cloud.githubusercontent.com/assets/10059935/25746971/283c300c-317c-11e7-870b-c5ac08310c19.png)

**Comment by DTILegBG** [comment]
Você fala com a descrição, se for isso, no 2.5 a descrição não era obrigatória e parece que o funcionamento está ok no 3.1, testando em base legada.

**Comment by falcao934jef** [comment]
@DTILegBG creio que há um erro nos títulos mesmo. Mas ainda assim, seria uma dúvida para que não haja nenhuma inconsistência no manual.

![image](https://cloud.githubusercontent.com/assets/10059935/25823084/4d6b4ad8-3411-11e7-83a4-e48007e253ea.png)

**Comment by edwardoliveira** [comment]
@falcao934jef Confere se resolveu, por favor.

**Comment by falcao934jef** [comment]
@edwardoliveira Resolvido
