### ISSUE TITLE
Resultado de votação não mostra votantes para usuário anônimo e votação nominal

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1066]
Quando o tipo de votação selecionada para a matéria era nominal, para o usuário anônimo era apresentado o resultado como um link, sendo possível clicar e ver como cada parlamentar votou
http://sapl.camarabento.rs.gov.br/consultas/sessao_plenaria/materias_expediente_sessao_form?cod_sessao_plen=349&dat_sessao=

![painel](https://cloud.githubusercontent.com/assets/13314947/25754493/ca7eec60-3195-11e7-948f-9001b061c541.PNG)

![image](https://cloud.githubusercontent.com/assets/13314947/25754572/1f9161f6-3196-11e7-8daa-eda6fef0ddc9.png)

No 3.1 isso não ocorre
http://sapl3beta.camarabento.rs.gov.br/sessao/349/expedientemateria

**Comment by edwardoliveira** [comment]
Eu cliquei no primeiro registro aqui embaixo:

![image](https://cloud.githubusercontent.com/assets/9326037/25860678/ae94eb00-34b8-11e7-8d4a-4fcae9fdc20b.png)

E apareceu essa tela abaixo:

![image](https://cloud.githubusercontent.com/assets/9326037/25860701/c3593370-34b8-11e7-8d34-92707afc3c22.png)

É isso?

**Comment by DTILegBG** [comment]
isso ai, mas desta forma, mas para usuário anônimo.



Em 09/05/2017 13:09, Edward escreveu:

**Comment by edwardoliveira** [comment]
@DTILegBG Verifique se solucionou ou não.

**Comment by DTILegBG** [comment]
Resolvido !!
