### ISSUE TITLE
Usuário anônimo causa erro ao selecionar legislatura.

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#1069]
![image](https://cloud.githubusercontent.com/assets/9326037/25862361/266b9cd2-34be-11e7-8f6d-76929f2702e9.png)

**Comment by edwardoliveira** [comment]
Favor olhar também o ticket https://github.com/interlegis/sapl/issues/1024
Tem a ver com essa tela.

**Comment by eduardocalil** [comment]
@edwardoliveira As duas issues são sobre o mesmo problema

**Comment by edwardoliveira** [comment]
Legal. Dá pra matar dois coelhos com uma cajadada só.
