### ISSUE TITLE
VOTAÇÃO DO PARLAMENTAR

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1073]
Após a votação do parlamentar, pelo módulo parlamentar, quando confirma o voto, tem se ainda a opção de mudar o voto. Era para ao confirmar o voto, voltar para a tela inicial do SAPL

**Comment by edwardoliveira** [comment]
Isso foi decisão de projeto. Enquanto a votação não se encerra o parlamentar pode mudar de voto.
