### ISSUE TITLE
Acompanhar matéria

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1075]
Como cadastrar o e-mail para acompanhamento de matéria no SAPL 3.1?

**Comment by edwardoliveira** [comment]
Questão não pertinente ao sistema de issues do Github. Fechada.

**Comment by LeandroRoberto** [comment]
Está sem esta funcionalidade... vi que existe Views em materia/views.py... mas não aparece na interface... 
![image](https://cloud.githubusercontent.com/assets/9630623/25962795/871527f4-3655-11e7-9221-51c4c048bd1c.png)

**Comment by edwardoliveira** [comment]
Implementamos essa funcionalidade mais de um ano atrás. Não está na listagem de matéria, mas na parte de tramitação.
