### ISSUE TITLE
Criar possibilidade de geração de impressos

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1079]
Impressos são importantes, como as etiquetas. Seria importante gerar impressos de matérias legislativas, de preferência que fosse possível escolher os campos a serem impressos.

**Comment by eduardocalil** [comment]
@andreagudo Seria essa funcionalidade? http://sapl.agudo.rs.leg.br/generico/impressos/materia_impresso_form

**Comment by andreagudo** [comment]
Sim, mas é para matérias legislativas, não normas jurídicas.

**Comment by eduardocalil** [comment]
Ok. Já temos uma issue mais geral sobre essa tela, que é a #542. Resolveremos ela e, consequentemente, esta. Sendo assim, issue fechada.
