### ISSUE TITLE
Adicionar acompanhamento de tramitação na listagem de matérias legislativas.

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#1081]
A listagem de matérias legislativas não apresenta a opção de acompanhar a tramitação de matérias.

**Comment by LeandroRoberto** [comment]
**Está sem esta funcionalidade... vi que existe Views em materia/views.py... mas não aparece na interface...**

![image](https://cloud.githubusercontent.com/assets/9630623/25963919/75ace930-3659-11e7-9a18-266f8ab97965.png)

**Comment by andreagudo** [comment]
Ao inserir o e-mail, responde
SMTPServerDisconnected at /materia/5963/acompanhar-materia/
Connection unexpectedly closed

**Comment by eduardocalil** [comment]
Essa issue é resolvida substituindo-se o valor **EMAIL_HOST_USER**, pelo valor de **EMAIL_SEND_USER**, no **.env**. Quando puder, troque isso no servidor de testes, @edwardoliveira. Então avise para que o @andreagudo possa testar (:

**Comment by edwardoliveira** [comment]
@andreagudo alterei na máquina de homologação. Favor testar.

**Comment by andreagudo** [comment]
Não deu erro. Mas depois de cadastrar o e-mail cai na tela abaixo. Nada a ver.
![captura de tela de 2017-05-22 13 47 22](https://cloud.githubusercontent.com/assets/19169882/26319541/d19ffabc-3ef5-11e7-927b-11d36a50e2ab.png)

**Comment by andreagudo** [comment]
Registrei o e-mail, mas não recebi mensagem. Serviço não funciona.

**Comment by edwardoliveira** [comment]
A tela de cadastro está muito bugada. Além deste redirect nada a ver, tinha um erro de indentação que impedia a chamada à função que envia o email. Mas mesmo com esse erro de indentação resolvido ainda não consigo enviar o email, pois dá um erro no servidor daqui. Amanhã vou conversar com o Fábio da Infra pq sei que ele andou mudando a configuração do servidor de email recentemente.

**Comment by edwardoliveira** [comment]
@andreagudo O @eduardocalil reimplementou esta funcionalidade e testamos. Poderia testar aí pra ver se resolveu? Obrigado!

**Comment by andreagudo** [comment]
Tudo resolvido. Cadastramento do e-mail, confirmação do cadastramento e recebimento de notificações de tramitação.
