### ISSUE TITLE
Tramitação de Comissões Inativas

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1082]
#661 Voltou a ocorrer o seguinte problema na tramitação: entre as Unidades Local e Destino, no caso de comissões, são listadas comissões ativas e inativas; deveriam ser listadas apenas as ativas na data da tramitação.

**Comment by eduardocalil** [comment]
Na criação de uma tramitação também? Vamos supor que esteja sendo adicionada uma Tramitação antiga e a Comissão estava ativa na época mas não está hoje? @andreagudo

**Comment by eduardocalil** [comment]
Acho que entendi. Você quer, ao inserir a data da tramitação, que a listagem seja alterada e só possua comissões ativas?

**Comment by andreagudo** [comment]
Isso mesmo, as ativas.

**Comment by eduardocalil** [comment]
@andreagudo Nós (Eu, @edwardoliveira, Sesóstris e Matheus) tivemos mais de uma conversa sobre esses requisitos de interatividade das telas dos SAPL. Atualmente, estamos encontrando muita dificuldade para encaixar este comportamento dinâmico de tela no framework interno usado pelo sistema. Estamos estudando a melhor forma de reestruturar o código deste framework, que foi feito internamente, para as necessidades desta e de outras issues semelhantes. Nem todas as telas do SAPL 3.1 utilizam este framework e nessas temos prontamente adicionado os recursos de iteratividade solicitados. Por essa razão, colocaremos essa issue como futuro, mas estamos muito empenhados em solucionar essa limitação imposta pelo framework.

Nos pareceu, que esta issue incorpora problemas de funcionalidade também. Então, seria possível criar outras issues relativas a esses erros?

**Comment by andreagudo** [comment]
Ok, assim farei.

**Comment by andreagudo** [comment]
Parece que são listadas todas as comissões ativas. Sobre ativação/inativação ver #1028

**Comment by andreagudo** [comment]
Esse problema afeta a indicação de relatores.

**Comment by andreagudo** [comment]
Parece que a issue está resolvida no caso das unidades destino. Alguém poderia confirmar? Ainda vou testar o caso da unidade local para matérias novas que vierem a ter tramitação.
