### ISSUE TITLE
Edição da relatoria: composição da comissão com todos os parlamentares

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1084]
A issue #662 resolveu a lista de membros da comissão entre os quais é escolhido o relator, quando da inclusão da relatoria. Ao editar a relatoria, porém, voltam a aparecer todos os parlamentares cadastrados. Também nessa situação deveriam ser listados apenas os membros atuais da Comissão.
![captura de tela de 2017-05-12 16 13 11](https://cloud.githubusercontent.com/assets/19169882/26013533/495bf7f0-372f-11e7-86d4-45a1a55fd955.png)

**Comment by eliseuegewarth** [comment]
Corrigido no PR #1213. Teste assim que o @edwardoliveira aceitar o PR.

**Comment by andreagudo** [comment]
Resolvida.
