### ISSUE TITLE
Documento acessorio administrativo

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1087]
Está na model, no form, mas não aparece botão para acesso.
Algumas considerações sobre o assunto do @LeandroRoberto 

- DocumentoAcessorioAdministrativoCrud é um Crud... tem que ser transformado em MasterDetailCrud

- um subnav_docadm.yaml tem que ser criado ou um botão Docs Acessórios ser adicionado ao lado do botão tramitações (inclusive esse botão não é o padrão das outras telas... a mioria das telas usam subnav.yaml... "ahhh mais como vai ter mais de uma subnav na mesma app..." é possível, leia o helpzinho em sapl/base/templatetags/menu.py) app matéria faz isso... tem um subnav para matéria e outro para proposição

- dentre alguma outra coisinha...

**Comment by edwardoliveira** [comment]
@DTILegBG Teria como vc tentar fazer essa issue? Vamos tentando te ajudar...

**Comment by eduardocalil** [comment]
@DTILegBG Confira o funcionamento, por favor. Caso haja algum problema, reabra esta ou crie outra issue se for algo pontual.

**Comment by DTILegBG** [comment]
Resolvido !! obrigado
