### ISSUE TITLE
Erro na criação de uma "Anexada" 

### ISSUE THREAD

**Issue by falcao934jef** [interlegis/sapl#1089]
Ao tentar criar uma Anexada dentro de uma matéria, menção ..., o input de "Número" ao tentar criar números, a reação é: Mensagens de alerta.

![image](https://cloud.githubusercontent.com/assets/10059935/26112164/83214336-3a2d-11e7-9b52-8e3110ce80c6.png)

Quando inserido  as letras no campo "numero" e clicado em "salvar", ele me direciona para uma tela de erro: sem nenhuma mensagem de feedback.

![image](https://cloud.githubusercontent.com/assets/10059935/26112232/b80e81bc-3a2d-11e7-833f-a49304963119.png)

O teste de inclusão foram feitos nessas duas URL's: 
http://sapl31agudo.interlegis.leg.br/materia/5943/anexada
http://sapl31demo.interlegis.leg.br/materia/1973/anexada

**Comment by DTILegBG** [comment]
Acho que é porque não existe a matéria criada a ser anexada


Em 16/05/2017 11:50, Jefferson Douglas Dias Falcão escreveu:

**Comment by falcao934jef** [comment]
@DTILegBG Mas no caso deveria me reportar uma mensagem de erro, ou de alerta e não página de erro, ou não?
