### ISSUE TITLE
Protocolar Matéria - recuperar texto da ementa e autor - número matéria

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1095]
Em protocolo, protocolando uma matéria são completados o nome do autor e a ementa, seguindo é clicado no botão criar matéria, o sistema não traz o autor cadastrado para o protocolo para a matéria, não traz a ementa cadastrada no protocolo e o número da matéria que é mostrado é o numero do protocolo, quando o correto deveria ser o proximo numero para aquele tipo de matéria.

**Comment by DTILegBG** [comment]
Olhando aqui, não esta gravando a ementa do protocolo na tabela do banco protocoloadm_protocolo

**Comment by DTILegBG** [comment]
nem tipo_protocolo que nos migrados esta como 0

**Comment by DTILegBG** [comment]
Gravação de ementa resolvido em
https://github.com/interlegis/sapl/pull/1112

**Comment by eduardocalil** [comment]
@DTILegBG Sobre o autor, aquele é um **formulário simplificado** de criação de matéria. Caso queira incluir uma **autoria**, deve-se ir até a Matéria e editá-la.

**Comment by DTILegBG** [comment]
ok, mas só para constar no sapl 2.5, ao protocolar uma matéria no 
protocolo geral, na sequencia de telas criar a matéria, o autor já era 
adicionado conforme protocolo.


Em 22/05/2017 13:56, Eduardo Calil escreveu:

**Comment by eduardocalil** [comment]
@DTILegBG Vou verificar. Mas já testa aí se as outras funcionalidades que você solicitou estão ok. Eu fiz um commit parcial resolvendo alguns dos problemas relatados nessa issue. Após testar, liste aqui o que ainda falta, por favor.

**Comment by DTILegBG** [comment]
Ficou muito bom, ficamos pendentes do autor

e algumas melhorias seria


quando a natureza do processo é matéria legislativa, não deveria 
aparecer o campo interessado, mas poderia mostrar o autor ja nos 
resultados da pesquisa além do já exibido nos detalhes. Além de exibir 
se existe matéria vinculada sem ser necessário ir aos detalhes



Em 22/05/2017 14:12, Eduardo Calil escreveu:

**Comment by eduardocalil** [comment]
O que seria esse tipo_protocolo? Não temos nenhuma tabela relacionada a isso.

**Comment by DTILegBG** [comment]
![image](https://cloud.githubusercontent.com/assets/13314947/26373561/58db0f34-3fd8-11e7-9d3f-40b2cdee0ae9.png)

**Comment by eduardocalil** [comment]
Ok. Mas o que esse campo quer dizer? O que é o 1? Já que não tem nenhuma tabela sendo relacionada, ou seja, não é uma FK.

**Comment by eduardocalil** [comment]
Descobri já. Se for 0 é Administrativo, se for 1 é Legislativo.

**Comment by eduardocalil** [comment]
@DTILegBG Fechei a issue. Confira, por favor, se resolveu tudo o que foi pedido. Caso contrário, reabra a mesma.

OBS: No formulário simplificado de criar matéria a partir de um protocolo, coloca-se automaticamente o autor do protocolo como primeiro autor da matéria. Confira isso também.

**Comment by DTILegBG** [comment]
eu acho que o 0 e 1 dessa coluna tipo_protocolo se refere se o protocolo é de entrada ou saída, se for administrativo ou legislativo funciona da mesma forma, mas está na coluna tipo_processo. vou me certificar.
