### ISSUE TITLE
Todos os autores disponíveis para seleção

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1096]
Estão sendo mostrados para seleção em protocolo e matérias, todos os autores, inclusive os inativos no sistema

**Comment by eduardocalil** [comment]
Mas se for uma matéria ou protocolo antigo? De uma época na qual o autor, que se encontra inativo no momento, estava ativo?

**Comment by andreagudo** [comment]
Devem ser listados apenas os parlamentares ativos. Para registrar uma matéria antiga, deve-se ativar seu autor.

**Comment by LeandroRoberto** [comment]
quanto a matérias já resolvido em #1328, quanto a protocolo será resolvido pela #1354 que também faz parte da refatoração de #1328
