### ISSUE TITLE
Assunto protocolo

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1097]
para os novos protocolos não são exibidas as ementas cadastradas
![image](https://cloud.githubusercontent.com/assets/13314947/26216449/85cd57e2-3bda-11e7-8206-423d3f2b5bc4.png)

quando a natureza do processo é matéria legislativa, não deveria aparecer o campo interessado, mas poderia mostrar o autor ja nos resultados da pesquisa além do já exibido nos detalhes. Além de exibir se existe matéria vinculada sem ser necessário ir aos detalhes

**Comment by DTILegBG** [comment]
sobre a ementa #1095

**Comment by edwardoliveira** [comment]
OK, eu subi o commit https://github.com/interlegis/sapl/commit/10839b1d9de53f89ea02f87f0f3d1071f4a73991 

Veja se resolveu a issue, por favor. Outra coisa, tem um exemplo de protocolo (número/ano) com máteria vinculada pra eu dar uma olhada? Ficou faltando isso...

**Comment by eduardocalil** [comment]
@DTILegBG
