### ISSUE TITLE
Autor de documentos acessórios das matérias

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1104]
O campo para adicionar a autoria de documentos acessórios nas matérias legislativas no sapl 2.5 era um campo de texto livre para digitar
SAPL 2.5

![image](https://cloud.githubusercontent.com/assets/13314947/26260721/a1156a56-3ca4-11e7-962b-c4150afed576.png)

sapl 3.1
![image](https://cloud.githubusercontent.com/assets/13314947/26260637/49e74c40-3ca4-11e7-9996-51d6a7ca81c0.png)

**Comment by edwardoliveira** [comment]
Corrigido por https://github.com/interlegis/sapl/pull/1110/files#diff-383de06339a768049f6d6b0a321dc128L954

**Comment by eduardocalil** [comment]
@DTILegBG Assim não fica melhor para garantir que será inserido um Autor registrado?

**Comment by DTILegBG** [comment]
O problema que nos documentos acessórios podem vir documentos de vários 
autores, exemplo, um parecer de conselho, que o pessoal digita o texto 
livre, no sapl 2.5 é feito desta forma, tanto que não é feito referência 
aos autores, é gravado o texto


Em 24/05/2017 09:06, Eduardo Calil escreveu:
