### ISSUE TITLE
Falta campo de pesquisa por número de processo nas matérias legislativas

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1105]
Falta campo de pesquisa por número de processo nas matérias legislativas, esse número de processo é o famoso 
![image](https://cloud.githubusercontent.com/assets/13314947/26260824/1df1b5b6-3ca5-11e7-9036-65fb16a67d89.png)

SAPL 2.5
![image](https://cloud.githubusercontent.com/assets/13314947/26260753/ce30e0ba-3ca4-11e7-969a-0bbbf57c14aa.png)

SAPL 3.1
![image](https://cloud.githubusercontent.com/assets/13314947/26260774/df949cde-3ca4-11e7-8052-a2469ba53cdc.png)

**Comment by eduardocalil** [comment]
@DTILegBG Isso é realmente necessário? O que seria o campo **Número de Processo**? Ele não consta atualmente na nossa tabela de Matérias.

**Comment by DTILegBG** [comment]
Pois é. O número de processo para nós funciona da seguinte forma, uma 
matéria recebe um número de protocolo e número de matéria, para ela é 
aberto um processo que ai leva este número.

no banco é referenciado aqui




no sistema é cadastrado aqui









Em 24/05/2017 08:57, Eduardo Calil escreveu:
