### ISSUE TITLE
Tramitação em lote

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1111]
Deveria só esta sendo listadas as matérias que estão com ultima tramitação na unidade destino selecionada.

![image](https://cloud.githubusercontent.com/assets/13314947/26318275/05d492d4-3ef1-11e7-886e-42199ee444f5.png)

![image](https://cloud.githubusercontent.com/assets/13314947/26318285/14aa1b80-3ef1-11e7-96b7-ed744e771cdf.png)

![image](https://cloud.githubusercontent.com/assets/13314947/26318376/4bf37654-3ef1-11e7-84a8-6640adf2fc92.png)

**Comment by eduardocalil** [comment]
@DTILegBG Fechei. Confira se está OK, por favor.
