### ISSUE TITLE
Migrações especiais para StatusTramitacao e outros

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#112]
Escrever migrações especiais para StatusTramitacao(+adm), TipoProposicao e Tramitacao (turno)

**Comment by LeandroRoberto** [comment]
Inclua-se rotina especial para migração de assuntos das normas jurídicas.
Assuntos e normas possuem um relacionamento NxN mas no sapl antigo os
códigos assuntos são armazenados em uma string separados por ponto e
vírgula dentro da tabela normajuridica

Em ter, 12 de jan de 2016 às 11:49, Marcio Mazza <notifications@github.com>
escreveu:

> Escrever migrações especiais para StatusTramitacao(+adm), TipoProposicao e
> Tramitacao (turno)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/interlegis/sapl/issues/112>.
>
-- 
att.
Leandro Roberto Silva
Câmara Municipal de Jataí

**Comment by marciomazza** [comment]
Vide #18.

**Comment by LucianoAlmeida** [comment]
Tenho dúvidas quanto a algumas dessas tramitações especiais:

1. Em StatusTramitacao(Administrativo), o `indicador` teria valores 'F' para fim da tramitação (quando `ind_fim_tramitacao=1` na tabela antiga) e 'R' para retorno (quando `ind_retorno_tramitacao=1`), mas há ainda a opção quando ambos `ind_fim_tramitacao=0` e `ind_retorno_tramitacao=0`. O que deveria ser colocado no campo `indicador` neste caso, visto que não aceita valores nulos e nem em branco?
2. Não entendi qual a migração especial em TipoProposicao.
3. Não entendi também qual a migração especial em Tramitacao.

Se o ponto 2 e 3 for a validação das choices, a issue #114 seria derivada dessa?

**Comment by LucianoAlmeida** [comment]
Após conversar com o @marciomazza, ficou decidido que essa isse será dividida para facilitar a compreensão dos problemas.

A migração de `StatusTramitacao` já foi resolvida na Pull Request #431 e uma segunda issue duplicada do mesmo problema foi criada e será fechada (issue #368).
A migração de `StatusTramitacaoAdministrativo`, que não estava explicitado na issue #114 que foi resolvida no Pull Request #431, será resolvida em uma nova issue (issue de número #475).
A migração de `TipoProposicao` será feita em uma issue separada dessa (issue de número #476)
A migração de `Tramitacao` já foi resolvida também na Pull Request  #431.
