### ISSUE TITLE
Protocolo - Protocolar Matéria

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1122]
No sapl 2.5, quando protocolada uma matéria, era gravado na tabela protocoloadm_protocolo, coluna tipo_protocolo o valor 0, que é o tipo de protocolo "recebido". Agora não está sendo gravado.

e para protocolo de documento está gravando invertido o valor

0 = recebido
1 = enviado

![image](https://cloud.githubusercontent.com/assets/13314947/26413224/a907c1f6-4081-11e7-8c6a-5c8bb9c8f9f9.png)

**Comment by DTILegBG** [comment]
sapl 2.5
![image](https://cloud.githubusercontent.com/assets/13314947/26420807/2e9271c8-409a-11e7-9406-3bdc4a22b85c.png)


sapl 3.1
![image](https://cloud.githubusercontent.com/assets/13314947/26420836/3fce7658-409a-11e7-8848-ca4410d8f221.png)

**Comment by edwardoliveira** [comment]
Vc pegou um bug daqueles!!! Favor verificar a solução, please.
