### ISSUE TITLE
Tramitação em lote

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1123]
Quando da tramitação em lote, mesmo selecionando urgente não, sempre é gravado true no banco

![image](https://cloud.githubusercontent.com/assets/13314947/26414414/86148d74-4085-11e7-878c-bc4960cace87.png)

sendo tramitado normal, sem ser por lote, funciona ok.

Também seria interessante existir como no sapl 2.5, um botão para selecionar todas as matérias da lista para tramitação - Selecionar todos

**Comment by edwardoliveira** [comment]
Vou adicionar o selecionar todos já já. Mas esse patch resolve o sempre True.
