### ISSUE TITLE
Documento acessório em lote.

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1124]
Lista das matérias resultantes da busca, possíveis de serem marcadas ficam fora da ordem de nº de matéria.

**Comment by eduardocalil** [comment]
@DTILegBG Manda um print e a url, por favor

**Comment by DTILegBG** [comment]
Ocorre no acessório em lote

http://sapl3beta.camarabento.rs.gov.br/materia/acessorio-em-lote?tipo=14&data_apresentacao_0=11%2F05%2F2017&data_apresentacao_1=25%2F05%2F2017&salvar=Pesquisar

o pessoal me falou que essa mesma lista fica em ordem na tramitação em lote

![lmmiahefnmmlffcp](https://cloud.githubusercontent.com/assets/13314947/26547337/e86a1dd2-4444-11e7-930f-8ee95724f9ae.png)

**Comment by eduardocalil** [comment]
@DTILegBG Acho que o problema foi resolvido. Confira aí, por favor. Caso não tenha resolvido, favor reabrir esta issue.
