### ISSUE TITLE
Ata, pauta, anexo - Caminho dos arquivos

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1125]
os caminhos para ata, pauta e anexo, quando estes documentos são salvos pelo sistema estão fora do padrão dos documentos importados

![image](https://cloud.githubusercontent.com/assets/13314947/26421785/ab0d1732-409d-11e7-8f9d-23a90ca3206c.png)

**Comment by edwardoliveira** [comment]
Isso é muito estranho... Olhei o código e vi isso aqui:

```
def pauta_upload_path(instance, filename):
    return texto_upload_path(instance, filename, subpath='pauta')

def ata_upload_path(instance, filename):
    return texto_upload_path(instance, filename, subpath='ata')

def anexo_upload_path(instance, filename):
    return texto_upload_path(instance, filename, subpath='anexo')
``` 

** Será que essas pastas aí não foram criadas ANTES das mudanças na função texto_upload_path?** Teria como testar fazendo o upload de uma ata, uma pauta e um anexo e vendo se eles vão parar no lugar certo?

**Comment by edwardoliveira** [comment]
Opa, vi aqui. Isso tem a ver com aquele lance de agrupar por ano em MateriaLegislativa, lembra?

**Comment by edwardoliveira** [comment]
@DTILegBG O que houve: com aquela modificação de colocar as matérias ordenadas por ano utilizando `subpath` a Ata, Pauta, e Anexo, cujos subpath são seus respectivos nomes passaram a ser impressos antes da PK da instância do model. 

Verifique se consertou (e não quebrou o upload de matérias). :pray:
