### ISSUE TITLE
Migração - protocolo_id

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1128]
para protocolo administrativo não está sendo importado o protocolo_id

![image](https://cloud.githubusercontent.com/assets/13314947/26455244/0fdb3962-4140-11e7-8551-2b3233e4b290.png)

**Comment by edwardoliveira** [comment]
@LucianoAlmeida Ah, essa foi uma modificação relativamente recente que fizemos. O Protocolo acabou virando chave estrangeira de DocumentoAdministrativo. ANTES tinha (na verdade ainda tem, mas será removido) um campo numero_protocolo em DocumentoAdministrativo. Assim, quando queriamos recuperar o protocolo a partir do DocumentoAdministrativo pegávamos esse campo numero_protocolo e o campo ano, que era compartilhado entre o DocumentoAdministrativo e o Protocolo.

Mas nos foi informado que em alguns casos é possível um Protocolo e um DocumentoAdministrativo terem anos distintos. Desta forma, fizemos esse "ajuste", e daí precisamos refazer essa parte na migração. Desculpa. :(

**Comment by LucianoAlmeida** [comment]
Essa issue foi finalizada juntamente com a issue #1154.
