### ISSUE TITLE
Erro ao salvar edição da tramitação

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1129]
![image](https://cloud.githubusercontent.com/assets/13314947/26461217/c5bc354e-4152-11e7-9b8f-c515761578c0.png)

**Comment by DTILegBG** [comment]
parei o gunicorn, iniciei novamente e funcionou...

**Comment by eduardocalil** [comment]
@DTILegBG @edwardoliveira Fechamos essa issue?

**Comment by DTILegBG** [comment]
sim, podemos fechar
