### ISSUE TITLE
Apagar pasta antiga quando mudar o código da casa legislativa

### ISSUE THREAD

**Issue by eduardoedson** [interlegis/sapl#113]

**Comment by edwardoliveira** [comment]
Removi o código da casa legislativa do path no file system porque dá muito problema quando muda-se o código. Além disso, teremos somente uma casa legislativa por ambiente então não existe uma necessidade real de diferenciar por código. Caso essa necessidade apareça no futuro podemos usar o ``id`` (PK da tabela).
