### ISSUE TITLE
Migração - ordem do dia

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1131]
para as importadas não existe este resultado de votação
para as feitas pelo sistema a informação é gravada

no 2.5 não existia a informação votacao_aberta, é importada em branco
![image](https://cloud.githubusercontent.com/assets/13314947/26463943/5ad58e9c-415c-11e7-9f26-14c07a8945ff.png)

**Comment by LucianoAlmeida** [comment]
@DTILegBG Existe alguma votação que possa estar aberta enquanto estiver fazendo a migração?
Uma votação aberta dessa de OrdemDia poderia ficar aberta por muitos meses?

**Comment by DTILegBG** [comment]
acho que independente, porque essa informação não existia no 2.5 então deveriam ser importada todas como False e era isso
