### ISSUE TITLE
Migração -  materia_acompanhamentomateria

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1132]
o campo confirmado é importado com o booleano false, não deveria ser true?

![image](https://cloud.githubusercontent.com/assets/13314947/26465096/5b1a39bc-4160-11e7-8fee-73928d9ab91e.png)

**Comment by LucianoAlmeida** [comment]
Esse deve ser o valor padrão da migração? Quando ele deve ser falso?

**Comment by DTILegBG** [comment]
no sapl 2.5 não existia essa coluna, mas penso que no 3.1 ela seja usada para validar o mail de acompanhamento, para os acompanhamentos migrados dos sapl 2.5, teria que ser migrado como True, porque teoricamente deveriam ja ter sido validados. ok?

**Comment by LucianoAlmeida** [comment]
Edward, você que criou esse campo, a utilidade dele é essa mesmo que o @DTILegBG está pensando?

**Comment by edwardoliveira** [comment]
Sim. Pode deixar tudo como True.
