### ISSUE TITLE
Migração - Registros duplicados de votação

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1133]
mesmo cod_materia e mesmo cod_ordem na base do sapl 2.5

esse bug gera o seguinte erro no sapl 3.1
get() returned more than one RegistroVotacao — it returned 2!

![image](https://cloud.githubusercontent.com/assets/13314947/26497004/20394090-4200-11e7-9a83-455092f035ed.png)

**Comment by LucianoAlmeida** [comment]
@DTILegBG, como seria possível saber qual duplicata deveria ser excluída?

**Comment by DTILegBG** [comment]
baseado neste exemplo, que é o único que consegui identificar que tem quantidade de votos diferentes, o primeiro está correto, acho que é por ai o caminho, o primeiro é o correto e o resto desconsiderado

**Comment by DTILegBG** [comment]
Resolvido pela 
https://github.com/interlegis/sapl/tree/1106-dados-duplicados-constraint
