### ISSUE TITLE
Mesa diretora

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1134]
quando selecionada uma sessão de uma legislatura anterior, a mesa diretora é mostrada desta forma

![image](https://cloud.githubusercontent.com/assets/13314947/26502582/b0ac6dc4-4213-11e7-94b6-0a6f1c000e69.png)

quando da legislatura atual
![image](https://cloud.githubusercontent.com/assets/13314947/26502689/248d45ec-4214-11e7-834f-e1aba79d8250.png)

quando de uma sessao criada na atual legislatura mas sem uma mesa cadastrada
![image](https://cloud.githubusercontent.com/assets/13314947/26502714/418738f6-4214-11e7-95af-82bda05c7d73.png)

**Comment by eduardocalil** [comment]
Mesmo problema da **Mesa Diretora** antiga da Casa Legislativa, que já foi refatorada. Nesse caso, deve ser consertada a **Mesa** de Sessão Plenária.

**Comment by eduardocalil** [comment]
@DTILegBG Confira, por favor. Caso não esteja ok, reabra esta issue.
