### ISSUE TITLE
Normas Jurídicas - Normas relacionadas

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1136]
para o usuário anônimo

nos detalhes da norma
![image](https://cloud.githubusercontent.com/assets/13314947/26548092/bf60f1f0-4448-11e7-8c77-e12b75ec43c7.png)

clicando em normas relacionadas
![image](https://cloud.githubusercontent.com/assets/13314947/26548099/cbf7ca60-4448-11e7-88b6-36a89090986e.png)

http://sapl3beta.camarabento.rs.gov.br/norma/14160/normarelacionada

**Comment by eduardocalil** [comment]
@DTILegBG O problema não ficou claro. Poderia detalhar melhor por favor?

**Comment by DTILegBG** [comment]
Claro, nem sei se chaga a ser um problema, mas só para termos isso claro, no detalhe da norma é apresentado 2 relacionamentos, o alterado e o revogado pela, enquanto clicando na aba normas relacionadas e mostrado somente uma norma
