### ISSUE TITLE
Regressão nas informações de documentos administrativos nos protocolos

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1140]
Deixaram de aparecer, nos protocolos, informações sobre docs adms vinculados e, nos docs adms, sobre os protocolos vinculados Ver #925

**Comment by eduardocalil** [comment]
Poderia exemplificar com prints?

**Comment by andreagudo** [comment]
Conforfme abaixo. O ideal é o protocolo e documento administrativo fossem links.
![captura de tela de 2017-05-29 15 53 23](https://cloud.githubusercontent.com/assets/19169882/26559620/1b0a1930-4487-11e7-85f2-29460f0a8dd0.png)
![captura de tela de 2017-05-29 15 53 52](https://cloud.githubusercontent.com/assets/19169882/26559633/2499c752-4487-11e7-8b2f-eacd3cbc8c0e.png)

**Comment by edwardoliveira** [comment]
Eu olhei e o código está lá, não houve mudanças. **Talvez** estejemos diante de uma grande inconsistência de dados (vou fazer um nova importação amanhã sem falta).

**Comment by andreagudo** [comment]
Resolvida.
