### ISSUE TITLE
Autores - Espaço e Vírgula 

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1141]
![image](https://cloud.githubusercontent.com/assets/13314947/26562692/ffaf2c3a-449e-11e7-9818-63e6dc2ae30a.png)

**Comment by edwardoliveira** [comment]
@DTILegBG Veja se consertou.

**Comment by DTILegBG** [comment]
voltou a aparecer todos os autores nesta consulta.

ja tinha sido consertado por esta

https://github.com/interlegis/sapl/issues/1118

**Comment by DTILegBG** [comment]
https://github.com/interlegis/sapl/pull/1146
