### ISSUE TITLE
Matéria legislativa: informar Data Fim Prazo

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1145]
Informar a Data Fim Prazo da última tramitação no resultado da pesquisa de matéria legislativa, na tela abaixo.
![captura de tela de 2017-05-30 08 37 10](https://cloud.githubusercontent.com/assets/19169882/26581550/80178222-4513-11e7-9fa7-60c4553fade0.png)

**Comment by andreagudo** [comment]
@eduardocalil Me referi à Dada Fim Prazo da última tramitação, que poderia aparecer no final da tela acima. O que inseriste foi Data Fim Prazo da matéria (o prazo para ser votada). O ideal seria manter as duas datas no relatório, mas com títulos diferentes.

**Comment by edwardoliveira** [comment]
@andreagudo Inclui a data fim prazo de tramitação. Veja se resolveu, por favor.

**Comment by andreagudo** [comment]
Resolvido.
