### ISSUE TITLE
Alterar formato da data

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1147]
Alterar o formato da data para o padrão da língua portuguesa na tela abaixo
![captura de tela de 2017-05-30 08 47 02](https://cloud.githubusercontent.com/assets/19169882/26581908/3a7595f4-4515-11e7-9cf8-7c5db77971f8.png)

**Comment by edwardoliveira** [comment]
Com a ajuda do @LeandroRoberto, resolvido. :+1:

**Comment by andreagudo** [comment]
Resolvido.
