### ISSUE TITLE
Sessão Plenária - Mesa Diretora

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1148]
Não funciona o botão incluir
![image](https://cloud.githubusercontent.com/assets/13314947/26582972/8b99b0f6-4519-11e7-974b-ac5c76d4bd42.png)

**Comment by eduardocalil** [comment]
Você tentou com qual tipo de usuário?

**Comment by DTILegBG** [comment]
testei com usuário admin e operador, reinicie o serviço do sapl

**Comment by edwardoliveira** [comment]
Teria como descrever os passos para reproduzir esse erro? Essa mesa diretora é de uma nova sessão plenária???

**Comment by DTILegBG** [comment]
Isso, isso mesmo, foi criada uma nova sessão e agora está sendo alimentado com os dados.
http://sapl3beta.camarabento.rs.gov.br/sessao/363/mesa

**Comment by edwardoliveira** [comment]
Ah, entendi. Então isso deve ser um bug específico de nova mesa para uma nova sessão. Entendeu @eduardocalil ?

**Comment by eduardocalil** [comment]
@edwardoliveira @DTILegBG  Descobri o erro. Acho que será solucionado com um **_collectstatic_**. O problema é de **csrf token** na chamada POST do Ajax. Eu criei uma função que gera o csrf token para essas chamadas e coloquei no **app.js**, chama-se _getCookie_. O que deve ter acontecido é que ela não foi para a pasta de collected statics da máquina de homologação.

**Comment by DTILegBG** [comment]
Opa, agora funcionou, obrigado
