### ISSUE TITLE
Manual SAPL 3.1

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1150]
Já está disponível o manual do SAPL 3.1?

**Comment by sesostris** [comment]
Bom dia, Paulo. As issues do github devem ser usadas EXCLUSIVAMENTE para reportar erros no sistema ou registrar demandas de novas funcionalidades. Não se deve abrir issues para esclarecer dúvidas. Para isso, existe a lista de discussão GITEC.

**Comment by sesostris** [comment]
Tendo este ponto esclarecido, vamos ao problema do manual:

1. O manual do SAPL 3.1 está sendo produzido em um projeto próprio, em https://github.com/interlegis/sapl-manual.

2. Este é um projeto à parte e também é **COLABORATIVO**. Está sendo coordenado por @falcao934jef

3. Sendo um projeto COLABORATIVO, você, que demonstra grande interesse em sua conclusão, pode auxiliar nos trabalhos, colaborando na produção do manual. Sinta-se à vontade para entrar em contato com o @falcao934jef para ver como você pode colaborar.

Contamos com sua participação no projeto do manual e esperamos, sinceramente, que você *não abra mais nenhuma issue para fazer perguntas*, pois, por não ser o canal correto, tumultua o processo de trabalho e causa desconforto para a equipe de desenvolvimento.
