### ISSUE TITLE
Compilação - Editor simples / tynemce

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#1152]
Quando é salvo na base de dados os dados editados pelo editor simples e tynemce os dados são salvos da forma abaixo
Ocorrem problemas se foi usado o editor tynemce para fazer e depois o simples para editar

Editor Simples
É o Município de Bento Gonçalves autorizado a alienar o imóvel a seguir descrito: "Uma área de terras contendo quatrocentos metros quadrados (400,00m2), relativa a uma parte do lote rural número sessenta e oito(68) da Linha terceira Secção Rio das Antas, distrito de Faria Lemos, neste município, sem benfeitorias, com as seguintes medidas e confrontações: Norte, na extensão de vinte metros (20,OOm), com terras de Ervino Dalla Colletta e Armindo Agostinho Pozza; Sul, na mesma extensão, com terras de Frederico AntônioFaccin; Leste, na extensão de vinte metros (20,OOm), com a Estrada Municipal; Oeste, na mesma extensão com terras de Frederico Antônio Faccin".

Editor TyneMce
![image](https://cloud.githubusercontent.com/assets/13314947/26678675/fe7b780e-46a7-11e7-9fc3-0848000819ba.png)

**Comment by LeandroRoberto** [comment]
é o contrário isso, não!!!... uma vez editado o TyneMce quando volta para o editor simples, o texto fica em formato html

**Comment by DTILegBG** [comment]
comportamento esperado
