### ISSUE TITLE
Migração - Relacionar protocolo em documento administrativo

### ISSUE THREAD

**Issue by LucianoAlmeida** [interlegis/sapl#1154]
A migração não está relacionando o documento administrativo e protocolo. Deve-se procurar o protocolo usando o numero_protocolo e ano presentes do documento administrativo.

**Comment by DTILegBG** [comment]
penso que seja a mesma issue
https://github.com/interlegis/sapl/issues/1128

**Comment by DTILegBG** [comment]
e mais essa
https://github.com/interlegis/sapl/issues/1140

**Comment by edwardoliveira** [comment]
@DtiLegBG Muito bem observado!!! Sim, são a mesma issue. Fechando uma, resolvemos as três. 😄 O @LucianoAlmeida não vem hoje, mas até amanhã teremos isso corrigido. 👍
