### ISSUE TITLE
Acompanhamento de matéria: e-mail com dados errados

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1155]
"Data da ação" e "Texto da ação" não mostram informações da última tramitação.

**Comment by edwardoliveira** [comment]
Veja se consertou, por favor. Caso contrário abrimos de novo.

**Comment by andreagudo** [comment]
Não consertou.

**Comment by andreagudo** [comment]
Está dando erro nas tramitações
![captura de tela de 2017-06-01 15 36 19](https://cloud.githubusercontent.com/assets/19169882/26695177/423aebd2-46e0-11e7-90b4-15104e27e041.png)

**Comment by edwardoliveira** [comment]
Culpa minha! Favor verificar se está funcionando agora, e se o bug original desta issue foi resolvido.

**Comment by andreagudo** [comment]
Ok, tudo resolvido.
