### ISSUE TITLE
Lista de Parlamentares: coluna sem titulo

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1158]
Coluna sem título, para todos os parlamentares consta "Não Informado".
![captura de tela de 2017-06-01 08 10 06](https://cloud.githubusercontent.com/assets/19169882/26677370/fe32a1e8-46a1-11e7-8fc8-280c3958c518.png)

**Comment by eduardocalil** [comment]
Essa mensagem de 'Não informado' foi inserida para que os campos vazios não aparecessem em branco nas telas. Isso acabou refletindo nos campos de imagem.

Todos os Parlamentares obrigatoriamente terão foto? Se colocar o nome "Foto" na coluna sem título, ficaria OK essa mensagem de 'Não Informado'?

**Comment by andreagudo** [comment]
Obrigatoriamente, não. Ok, "Foto" no lugar de "Não Informado".

**Comment by edwardoliveira** [comment]
Veja se consertou, por favor.

**Comment by andreagudo** [comment]
Resolvido
