### ISSUE TITLE
Compilação - Inserir em ou após

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1159]
Por algumas vezes é apresentado comportamento estranho ao adicionar dispositivos, depois de adicionado, volta para a tela, sem aparecer, atualizando f5, ai sim aparece para edição

![image](https://cloud.githubusercontent.com/assets/13314947/26690444/be19dfb2-46cf-11e7-8770-767d1ffa260a.png)

![image](https://cloud.githubusercontent.com/assets/13314947/26690459/ca94e160-46cf-11e7-8bc0-b10a29f070b4.png)

![image](https://cloud.githubusercontent.com/assets/13314947/26690465/d3cfef54-46cf-11e7-9768-37f86f08df9f.png)

**Comment by marciomazza** [comment]
@LeandroRoberto em que milestone devemos classificar essa issue?

**Comment by DtiLegBG** [comment]
Resolvido !!
