### ISSUE TITLE
Sessão Plenária: erro ao gerar pdf do resumo

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1171]
Page not found (404)
Request Method:	GET
Request URL:	http://sapl31agudo.interlegis.leg.br/relatorios/417/sessao-plenaria
Raised by:	sapl.relatorios.views.relatorio_sessao_plenaria

**Comment by edwardoliveira** [comment]
Quando a casa legislativa não está configurada ele lança uma exceção de page not found.

**Comment by edwardoliveira** [comment]
Nem sei se essa é realmente a melhor opção, mas estou aberto a sugestões (não fui eu quem implementou esse recurso de retornar 404).
