### ISSUE TITLE
Mandatos do parlamentar: campo como "Não informado"

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1176]
Quando não há coligação aparece "Não informado", sendo que, como não havia coligação, o correto seria deixar o campo em branco. Já na coluna "Nº Votos Recebidos (Coligação)", penso que deveria aparecer o total de votos obtidos pelo partido, caso não exista coligação, conforme #694.

**Comment by edwardoliveira** [comment]
@eduardocalil Isso aparece também em datas que são None/null tipo data de desfiliação do parlamentar. Vamos ter que ver a melhor maneira de contornar isso. :+1:

**Comment by eliseuegewarth** [comment]
@andreagudo , a parte relacionada ao "Não informado" da #1176 esta resolvida. Quanto a parte "Já na coluna "Nº Votos Recebidos (Coligação)", penso que deveria aparecer o total de votos obtidos pelo partido, caso não exista coligação", sugiro que crie uma outra issue para discutirmos a viabilidade dessa mudança.

**Comment by eliseuegewarth** [comment]
Aguardando @edwardoliveira aceitar o PR

**Comment by andreagudo** [comment]
Primeira parte resolvida. Quanto à segunda, já existe a issue #694
