### ISSUE TITLE
Relatórios: Matérias em Tramitação -  erro em Local Atual

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1177]
Na coluna Local A
![captura de tela de 2017-06-07 14 47 45](https://user-images.githubusercontent.com/19169882/26893452-c912af22-4b91-11e7-8c51-c31a4cbf7561.png)
tual está aparecendo informação da localização atual, que deve ser a Unidade Destino da última tramitação.

**Comment by edwardoliveira** [comment]
Teria como colocar o link dessa tela?

Obrigado!

**Comment by andreagudo** [comment]
http://sapl31agudo.interlegis.leg.br/sistema/relatorios/materia-por-tramitacao

**Comment by edwardoliveira** [comment]
Veja se consertou, por favor.

**Comment by andreagudo** [comment]
Resolvida.
