### ISSUE TITLE
Relatórios: Presença nas sessões

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1178]
O período abaixo devia considerar a sessão de 29/05/2017, que teve todos os Vereadores presentes. Não houve Ordem do Dia, por isso não há presenças nela.
![captura de tela de 2017-06-07 15 06 08](https://user-images.githubusercontent.com/19169882/26893872-1b42ac06-4b93-11e7-9bd1-1db3c3565961.png)

**Comment by edwardoliveira** [comment]
Qual o link desse relatório? Não me lembro de ter trabalhado nele...

**Comment by andreagudo** [comment]
http://sapl31agudo.interlegis.leg.br/sistema/relatorios/presenca

**Comment by eduardocalil** [comment]
A issue #1304 foi fechada. Sendo assim, esta também deverá ser. @andreagudo Teste, por favor, se está tudo OK.

**Comment by eduardocalil** [comment]
@andreagudo Poderia detalhar melhor o problema, por favor?

**Comment by andreagudo** [comment]
O relatório só mostra o cabeçalho, sem informações sobre presenças. Veja o caso abaixo, parecido com o anterior, relativo ao período em que foi realizada a sessão de posse (01/01/2017). 
![captura de tela de 2017-08-09 17 09 30](https://user-images.githubusercontent.com/19169882/29141749-e128e980-7d25-11e7-8b5e-6f88ebc69046.png)

**Comment by andreagudo** [comment]
Ainda não resolvido. Não aparece nenhuma presença 2017.
![captura de tela de 2017-09-06 15 06 02](https://user-images.githubusercontent.com/19169882/30127354-5495b2b8-9315-11e7-9c33-e530fb559b2f.png)

**Comment by eduardocalil** [comment]
Corrigido. Confira lá, por favor.

**Comment by andreagudo** [comment]
Aparecem no relatório, indevidamente, parlamentares de outras legislaturas.

**Comment by edwardoliveira** [comment]
@andreagudo Trata-se de um problema de migração que o @eduardocalil identificou ao trabalhar nessa issue. *Parlamentares que estavam sem data de fim de mandato estavam, quando da migração, recebendo a data fim da última legislatura.*

Iremos consertar isso no script de migração e fazer uma nova migração de Agudo para consertar esse problema. /cc @LucianoAlmeida @marciomazza

**Comment by eduardocalil** [comment]
@andreagudo O problema é este relatado pelo @edwardoliveira. Estou fechando esta issue. Caso tenha qualquer problema relacionado a esta funcionalidade, por favor, abra **outra** issue.
