### ISSUE TITLE
Relatórios: Histórico de tramitações

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1179]
Em pesquisa feita para o período 01/06/2017 e 30/06/2017, o Projeto de Lei 28/2017 aparece três vezes, apesar de só haver um Projeto de Lei com tal número em 2017.
![captura de tela de 2017-06-07 15 17 57](https://user-images.githubusercontent.com/19169882/26894446-d4f1041c-4b94-11e7-83ed-de8b7d0f0c1d.png)

**Comment by eduardocalil** [comment]
@andreagudo Qual o link?

**Comment by andreagudo** [comment]
http://sapl31agudo.interlegis.leg.br/sistema/relatorios/historico-tramitacoes

**Comment by edwardoliveira** [comment]
Veja se solucionou, por favor.

**Comment by andreagudo** [comment]
Resolvida.

**Comment by andreagudo** [comment]
Reabri por engano.
