### ISSUE TITLE
Erro ao criar um proposição

### ISSUE THREAD

**Issue by falcao934jef** [interlegis/sapl#1182]
No ambiente de teste que estou usando, sapl.teste.df.leg.br, ao tentar criar uma proposição, a seguinte tela de erro é exibida:
![image](https://user-images.githubusercontent.com/10059935/26936803-fd1e7594-4c45-11e7-9048-1632510a99f1.png)

Sistema -> tipo de proposição -> adicionar tipo de proposição -> salvar

**Comment by LucianoAlmeida** [comment]
Alguma migração de banco de dados do SAPL 2.5 para o SAPL 3.1 foi feita?
Se sim, isso pode ser problema no migrador.

**Comment by LucianoAlmeida** [comment]
@eliseuegewarth acabou de descobrir que é erro de migração sim.
Logo mais o problema será solucionado
