### ISSUE TITLE
Votação com perfil de votante

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1184]
http://sapl3beta.camarabento.rs.gov.br/sessao/364

Ao tentar votar ocorre o seguinte:

![image](https://user-images.githubusercontent.com/13314947/26973634-c5592c5a-4ced-11e7-8f11-cc4c74661826.png)

Voto Parlamentar

![image](https://user-images.githubusercontent.com/13314947/26973585-9a472508-4ced-11e7-9048-adf2c96db23e.png)

Debug=true
![image](https://user-images.githubusercontent.com/13314947/26973548-747e38d4-4ced-11e7-84a4-86c03a52e58c.png)

Debug=false

![image](https://user-images.githubusercontent.com/13314947/26973499-4c668400-4ced-11e7-8849-5f40d6aeca88.png)

**Comment by eduardocalil** [comment]
Você tem que seguir os seguintes passos:

1. Ir em Parlamentares
2. Selecionar o parlamentar desejado
3. No subnav da tela de detail, clicar em Usuário
4. Criar um usuário votante para aquele parlamentar

Depois disso nos informe se está tudo ok

**Comment by DtiLegBG** [comment]
Opa, agora sim, eu realmente não tinha feito isso. Obrigado
