### ISSUE TITLE
links nas proposições enviadas pelo Autor

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1187]
Nas proposições enviadas pelo autor seria interessante mostrar 

link direto para a matéria gerada
link para a matéria vinculada
link para doc gerado

![image](https://user-images.githubusercontent.com/13314947/27037925-d388dca2-4f5f-11e7-8458-70a31268152c.png)

**Comment by eliseuegewarth** [comment]
Qual o tipo de operador utilizado e tela dessa funcionalidade?

**Comment by eliseuegewarth** [comment]
Você tem algum exemplo desse na sua base de dados?
