### ISSUE TITLE
Pauta de Sessão em PDF

### ISSUE THREAD

**Issue by fabiobelo** [interlegis/sapl#1195]
Não estou conseguindo gerar o pdf. 
Me retorna o erro:

ProgrammingError at /relatorios/2/sessao-plenaria
relation "sessao_resumoordenacao" does not exist
LINE 1: ...o"."nono", "sessao_resumoordenacao"."decimo" FROM "sessao_re...

O que pode ser?

**Comment by edwardoliveira** [comment]
Vc rodou os migrations? Esta tabela foi adicionada recentemente. Essa tabela sessao_resumoordenacao foi feita para reordenar as seções do resumo.

Para reordenar as seções, vc deve ir em Tabelas Auxiliares -> Ordenação Resumo e salvar o registro lá.

**Comment by edwardoliveira** [comment]
Alguma novidade?

**Comment by fabiobelo** [comment]
Atualizei todos os arquivos e dependências. Esta funcionando perfeitamente.

**Comment by edwardoliveira** [comment]
Excelente. Vou fechar essa issue então.
