### ISSUE TITLE
Criação de Tipos Proposições duplicadas

### ISSUE THREAD

**Issue by eliseuegewarth** [interlegis/sapl#1196]
Ao enviar formulário com dados que ja existem, o sistema persiste duplicatas.

**Comment by edwardoliveira** [comment]
Essa issue é complicada porque são campos CharField e daí uma simples vírgula a mais fará com que sejam dois registros diferentes (ainda mais porque a PK é o id). Podemos colocar unique nos campos, mas acho que isso não seja suficiente pelo que acabei de citar. Infelizmente, o controle de duplicatas nesse caso deve ser feito pelos mantenedores do sistema, eu acredito.
