### ISSUE TITLE
Menu de acesso a Matérias das quais o Parlamentar é autor

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1200]
No sapl 2.5, acessando o menu Parlamentar, existe um menu chamado proposições, para acesso direto as proposições daquele parlamentar.
http://sapl.camarabento.rs.gov.br/consultas/parlamentar/proposicao/proposicao_index_html?cod_parlamentar=8

![image](https://user-images.githubusercontent.com/13314947/27296742-75c35860-54f8-11e7-95b6-9492bf4357c5.png)

No sapl 3.1 não existe esse menu
http://sapl3beta.camarabento.rs.gov.br/parlamentar/8

**Comment by edwardoliveira** [comment]
Essas proposições são aquelas incorporadas, certo? E estão disponíveis para usuário anônimo e outros?

**Comment by DtiLegBG** [comment]
Pois é, não, essas são as matéria das quais o parlamentar é autor, inclusive deveriam ser tratadas por exemplo como assinatura e não como proposições, no 3.1 tem menu específico para as proposições
