### ISSUE TITLE
Painel eletrônico de votação

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1201]
No caso da votação nominal, não seria correto no painel ser mostrado como cada parlamentar votou e não só os presentes e o resultado?

**Comment by eduardocalil** [comment]
@DtiLegBG Sobre o voto do parlamentar na frente do nome, eu consertei. Confere lá, por favor.

**Comment by DtiLegBG** [comment]
ainda não consegui fazer funcionar/aparecer

**Comment by eduardocalil** [comment]
![votonomin](https://user-images.githubusercontent.com/14843060/27408288-4a35ac46-56b2-11e7-898d-88d6ba6e1ced.png)

**Comment by eduardocalil** [comment]
@DtiLegBG Você pode me mandar, via Telegram, um vídeo da sua tela enquanto você reproduz esse erro passo-a-passo?

**Comment by paulot12** [comment]
Não aparece o voto após o nome do parlamentar

**Comment by eduardocalil** [comment]
Resolvido

**Comment by DtiLegBG** [comment]
Favor reabrir, não está resolvido

![image](https://user-images.githubusercontent.com/13314947/29833962-a8b44d8a-8cc3-11e7-920a-4b829a11d35b.png)

**Comment by DtiLegBG** [comment]
Resolvido!
seguindo a dica do @cristian-longhi 
Nos tipos de resultado  da votaçao, tem que ser informado Aprovado ou Reprovado na natureza do tipo. Dai ele mostra o voto.
