### ISSUE TITLE
Voto eletrônico - Parlamentar

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1202]
O Parlamentar clicando em votar matéria, se não existe nenhuma matéria em votação é exibida uma tela com a seguinte frase "Nenhuma sessão com matéria aberta." , nas não dando a possibilidade de voltar.
Para o caso de haver alguma matéria em votação, é apresentada as opções de votação, porém, depois de votado e fechada a votação daquela matéria não é atualizada a tela, e o usuário continua com a matéria ja voltada em tela, sem opções de atualizar tela, votar, voltar...

**Comment by eduardocalil** [comment]
Como assim "__ não dando a possibilidade de voltar__"?

**Comment by eduardocalil** [comment]
Sobre o voto do parlamentar na frente do nome, eu consertei. Confira lá, por favor.

**Comment by eduardocalil** [comment]
@DtiLegBG Coloquei refresh automático na tela também. Se estiver tudo ok, feche esta issue.

**Comment by DtiLegBG** [comment]
ok, mas creio que falte um botão para voltar para o sapl quando "Nenhuma sessão com matéria aberta."

**Comment by eliseuegewarth** [comment]
O Botão "voltar" é uma solução melhor que o refresh automático sobre o ponto de vista de Usabilidade. Evita comportamentos inesperados e o usuário não vai ficar confuso.

**Comment by eduardocalil** [comment]
Por que ele ficaria confuso?

**Comment by eduardocalil** [comment]
Seria algo a mais na tela

**Comment by eduardocalil** [comment]
@DtiLegBG Confira se está ok, por favor.

**Comment by DtiLegBG** [comment]
Resolvido, obrigado !!
