### ISSUE TITLE
Frente Parlamentar

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1203]
Todos os Parlamentares ficam disponíveis para serem marcados na composição da frente, penso que uma solução seria a mesma encontrada pelo cristian-longhi para presenças nas sessões

**Comment by eliseuegewarth** [comment]
@DtiLegBG, pode especificar melhor o problema? (se tiver imagens melhor ainda)

**Comment by DtiLegBG** [comment]
Claro, todos os parlamentares ficam disponíveis para serem incluídos na frente, inclusive os inativos. O cristian fez uma solução para esse mesmo problema onde todos os parlamentares ficaram disponíveis para inclusão na sessão ordinária. Ele colocou essa caixa...

![image](https://user-images.githubusercontent.com/13314947/27395850-97f36520-5687-11e7-8954-01369df3c711.png)

**Comment by eduardocalil** [comment]
- [ ] Criar o html do formulário

- [ ] Criar lógica para aparecer a seleção de parlamentares de acordo com as mudanças nos campos de **Data Criação** e **Data Dissolução**

-[ ] Criar checobox que seleciona se aparecerão somente os ativos naquele intervalo ou todos os parlamentares

-[ ] Ao dar clique duplo no parlamentar desejado, ele é listado abaixo da caixa de seleção.

-[ ] Criar botão de remover ao lado. Caso seja removido, ele volta para a caixa de seleção.

**Comment by eduardocalil** [comment]
@DtiLegBG Veja se está ok, por favor.
