### ISSUE TITLE
Migração - Comissões

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1209]
Teria que ser levado em conta também a data de término, além da data de extinção para migrar com o status de inativo para a comissão.

**Comment by andreagudo** [comment]
As comissões abaixo constam no 2.5 como inativas, embora não tenham data de extinção nem de término, o que as fez migrarem como ativas. Ver no 2.5 o que as tornava inativas. 
http://sapl31agudo.interlegis.leg.br/comissao/25
http://sapl31agudo.interlegis.leg.br/comissao/32
http://sapl31agudo.interlegis.leg.br/comissao/28
