### ISSUE TITLE
Retirar null=True de CharField e TextField

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#121]
Retirar null=True CharField e TextField e **preencher com vazio na migração**

**Comment by marciomazza** [comment]
**Revisado.**

Precisamos ajustar a migração do legado para converter null para a string vazia em CharFields e TextFields. Abri a issue #200.

**Comment by edwardoliveira** [comment]
@marciomazza @eduardoedson Desculpa, não entendi o propósito desta mudança. Além disso, isso não vai gerar problema no ``./manage.py migrate`` com colunas que tenham ``null``? É pra isso que serve a issue #200?

**Comment by marciomazza** [comment]
@edwardoliveira percebeu que o migrate não roda, pois há campos com valor nulo. Precisamos fazer um script de migração dos dados para rodar antes do `./manage.py migrate`

**Comment by marciomazza** [comment]
Fiz esse script para rodar antes do `migrate`:
https://github.com/interlegis/sapl/blob/master/scripts/convert_null_to_empty_in_all_char_fields.py

A rigor teríamoa que colocar esse código nos aquivos de migração, mas por simplicidade sugiro que simplesmente rodemos a funcão do script num shell antes de rodar a migração.
