### ISSUE TITLE
Tramitação: Unidade Local não deve sofrer mudança

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1215]
Na tela Adicionar Tramitação a Unidade Local pode ser mudada, o que é indevido. O sistema responde a tal mudança com "A origem da nova tramitação deve ser igual ao destino da última adicionada!" e não salvando a nova tramitação. De qualquer forma, o ideal seria que o campo Unidade Local não pudesse ser editado.
![captura de tela de 2017-06-21 09 38 58](https://user-images.githubusercontent.com/19169882/27384571-b8163a98-5665-11e7-863f-800f1ff63b3f.png)

**Comment by edwardoliveira** [comment]
@andreagudo Por favor, faça uns testes com tramitações novas, tramitações inicias de matérias, etc. pra ver se a solução atende. Senão pode reabrir.

**Comment by andreagudo** [comment]
Funcionou na tramitação em lote. Na tramitação individual a Unidade Local não fica disponível pra alteração, mas acaba não sendo salva. Além disso, tal campo não abre opções de preenchimento. 
![captura de tela de 2017-06-21 14 46 32](https://user-images.githubusercontent.com/19169882/27398636-c9a5b7fe-5690-11e7-94d3-26127849440c.png)

Além disso, ao excluir as tramitações existentes e incluir-se uma nova primeira, está assumindo a CCJ como Unidade Local, não sendo possível edição.
![captura de tela de 2017-06-21 14 54 14](https://user-images.githubusercontent.com/19169882/27398935-a8da2af4-5691-11e7-828f-359c6b5de4ea.png)

**Comment by eduardocalil** [comment]
@andreagudo Na tela de edição é possível esconder a Unidade Local. Entretanto, no de criação, fica complicado pelo seguinte motivo: _E se for a primeira tramitação?_

O sistema já tem mecanismos que impedem que a unidade local seja diferente da de destino, mesmo que o usuário tente alterar a unidade local.

**Comment by andreagudo** [comment]
O problema original da issue foi resolvido: ao Adicionar Tramitação, a tela mostra a Unidade Local correta, sendo indisponível qualquer mudança. Ocorre que, ao salvar, o sistema não reconhece tal campo como preenchido, retornando para editar a Unidade Local que, além de estar em branco, não disponibiliza opções. Nas telas logo acima, a última corresponde à solução do problema original; e a anterior, ao erro ao salvar.

**Comment by eduardocalil** [comment]
Confira se está ok, por favor @andreagudo
