### ISSUE TITLE
Tramitação em lote: primeira tramitação com Unidade Local já preenchida

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1217]
A primeira tramitação já mostra a Unidade Local preenchida com a primeira da lista, embora permita alteração. O ideal seria estar em branco.
![captura de tela de 2017-06-21 14 37 15](https://user-images.githubusercontent.com/19169882/27398183-54eb4114-568f-11e7-9fd4-7ef0f0f138ee.png)

**Comment by edwardoliveira** [comment]
@andreagudo Veja se consertou, por favor. Caso contrário, favor reabrir.

**Comment by andreagudo** [comment]
Resolvida.
