### ISSUE TITLE
Tramitação em lote: Unidade Local clicável

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1218]
Na tramitação em lote, a Unidade Local aparece preenchida corretamente, mas o campo está disponível para alteração, embora com única opção. O ideal seria tal campo não ser sequer clicável.
![captura de tela de 2017-06-21 15 01 23](https://user-images.githubusercontent.com/19169882/27399396-037a3462-5693-11e7-8ad7-553bea9d8139.png)

**Comment by eduardocalil** [comment]
Confira se está ok, por favor @andreagudo

**Comment by andreagudo** [comment]
Resolvido.
