### ISSUE TITLE
Tramitação em lote salva corretamente, mas resposta inadequada

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1222]
A reposta devia ser a lista de tramitações, mas está sendo esta
![captura de tela de 2017-06-22 14 06 53](https://user-images.githubusercontent.com/19169882/27446518-3ab907ca-5754-11e7-94cb-07b2eeb6d22b.png)

**Comment by edwardoliveira** [comment]
@andreagudo Poderia me fornecer uma sequência de passos para replicar esse processo? Um vídeo seria excelente, para que eu possa replicar os passos aqui?

**Comment by andreagudo** [comment]
Devo ter me enganado. A resposta da figura acima está correta no caso da pesquisa na não ter encontrado matérias com os critérios definidos. O que está ocorrendo é que a tramitação é salva e retorna para a tela da pesquisa recentemente feita.
![captura de tela de 2017-06-27 09 51 02](https://user-images.githubusercontent.com/19169882/27588337-36d35d86-5b1e-11e7-8879-4effe587e165.png)

Imaginei que a resposta poderia ser a lista de tramitações. Mas isso não serve para uma tramitação em lote.
