### ISSUE TITLE
Permitir que a numeração de protocolo começe de um número informado

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#1223]
A numeração de protocolo por ano ou única sempre começa de um, mas deveria ser possível criar a partir de um número informado (ex: 1340) de tal forma que os próximos protocolos fossem 1340/2017, 1341/2017, etc.

**Comment by andreagudo** [comment]
Isso é assunto das Tabelas Auxiliares.

**Comment by eduardocalil** [comment]
@edwardoliveira Era para ter fechado esta issue? Seu commit não fechou automaticamente.

**Comment by VictorFabreF** [comment]
Issue já resolvida.
