### ISSUE TITLE
Primeira tramitação em lote: Unidade Local indisponível para optar

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1224]
O campo Unidade Local não mostra opções.
![captura de tela de 2017-06-22 14 57 31](https://user-images.githubusercontent.com/19169882/27448462-3710a482-575b-11e7-91ee-19e5daa8fc82.png)

**Comment by eduardocalil** [comment]
Deve ser porque Primeira Tramitação em Lote usa o mesmo template de Tramitação em Lote. O atributo **disabled** deve ser setado no `get_context_data`, não no template.

**Comment by andreagudo** [comment]
Revolvida.
