### ISSUE TITLE
Tramitação individual recentemente salva deve levar à lista de tramitações

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1225]
Tem levado aos detalhes da tramitação recentemente salva, dando a impressão de que houve algo errado. Semelhante à #1222

**Comment by edwardoliveira** [comment]
@andreagudo Favor conferir se resolveu.

**Comment by andreagudo** [comment]
Deu o seguinte erro
![captura de tela de 2017-06-22 16 36 25](https://user-images.githubusercontent.com/19169882/27452497-12bec36c-5769-11e7-8432-d03dc723bc45.png)

**Comment by edwardoliveira** [comment]
Essa tela de erro tem relação com Tramitação mas não com essa issue tratada no commit https://github.com/interlegis/sapl/commit/105873d738ca60b64a27fdc04d345c28c21cddd1 . Houve algum problema na atualização da tramitação via email que inviabilizou a criação da Tramitação.

**Comment by andreagudo** [comment]
Testei novamente com a Indicação 10/2017. Fiz nova tramitação, resultado ok. Depois cadastrei email para acompanhamento, ok. Confirmei o email, ok. Fiz outra tramitação, sem problema. Todas as tramitações foram registradas.
