### ISSUE TITLE
Pesquisa Matéria Legislativa deve permitir filtrar por autor principal e co-autoria

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#1229]
Atualmente não é possível filtrar a lista de pesquisas por Autoria.primeiro_autor na pesquisa de matéria legislativa.

**Comment by edwardoliveira** [comment]
Este "bug" foi detectado durante a resolução da issue #1200

**Comment by eduardocalil** [comment]
Isso se trata de um problema maior causado pela estrutura com a qual as queries da lib **django-filter** são executadas. Uma das soluções é fazermos um fork da lib e fazermos modificações nessa estrutura.
