### ISSUE TITLE
Migrar Localidade deixando apenas municípios

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#123]
Vide #143

**Comment by edwardoliveira** [comment]
@LeandroRoberto Como??? O que é pra fazer aqui??? :astonished:

**Comment by LucianoAlmeida** [comment]
Eu também estou sem entender o que é fazer nessa issue.

**Comment by marciomazza** [comment]
A tabela original de Localidade tem municípios, UF's e talvez outras coisas.
Eu tive a impressão de que deveria haver um model só de municípios, mas posso estar enganado.
Alguém precisa olhar como esse dado é usado na aplicação e ver se a issue realmente se aplica ou eu entendi errado.

Em todo o caso sugiro deixar essa issue por último entre as issues de migração. Tem prioridade muito baixa.

**Comment by marciomazza** [comment]
Considerar usar https://pypi.python.org/pypi/django-municipios

**Comment by LeandroRoberto** [comment]
não digo para saap, por exemplo, mas para sapl não acho necessário nem ao menos ter cadastro de município.

**Comment by DtiLegBG** [comment]
@edwardoliveira , será que essa issue ainda faz sentido? não daria para fechar ela?

**Comment by edwardoliveira** [comment]
Temos que ver com o Mazza pois se trata de coisa de migração. @marciomazza podemos fechar?

**Comment by marciomazza** [comment]
Estou retirando o label **migração** dessa issue, pois ela não tem a ver com migrar as bases antigas de 2.5 para o 3.1. 
Tb estou fechando para tratarmos do assunto na #143.
