### ISSUE TITLE
Parlamentar - Submenus desaparecem

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1230]
ao clicar no submenus de parlamentar, especificamente nos menus mandato e matéria, todos menus são desaparecem
![image](https://user-images.githubusercontent.com/13314947/27634095-5ff2eb7c-5bd8-11e7-882d-ae5fadd927cc.png)

Exemplo clicando em menu mandato
![image](https://user-images.githubusercontent.com/13314947/27634121-71d70cba-5bd8-11e7-8ff3-ff6e45cc77d6.png)

**Comment by DtiLegBG** [comment]
tem um defeito de layout que joga o rodapé para a direita, alinha com a tabela de autoria e co-autoria.
faltou fechar a tabela em co-autoria

**Comment by edwardoliveira** [comment]
@DtiLegBG Vê se resolveu, por favor.

**Comment by DtiLegBG** [comment]
Resolvido !!
