### ISSUE TITLE
Filtragem de matéria legislativa pelo campo Em tramitação não está funcionando

### ISSUE THREAD

**Issue by cristian-longhi** [interlegis/sapl#1235]
Para qualquer opção no campo - Tanto faz, Sim ou Não - a pesquisa traz como resultado as matérias com "Em tramitação = Sim".

**Comment by DtiLegBG** [comment]
Resolvida pelo
https://github.com/interlegis/sapl/commit/267bcac78589b238b401b12e94204d7c409caff1
