### ISSUE TITLE
Migração: problema em Generic Relation em Autores

### ISSUE THREAD

**Issue by LucianoAlmeida** [interlegis/sapl#1240]
No momento que o script de migração exclui stubs de parlamentares, há exclusão em cascata, causando a exclusão também de autores.
A solução talvez seria verificar a relação entre eles, contudo a relação inversa não está funcionando, pois o campo parlamentar_set (https://github.com/interlegis/sapl/blob/master/sapl/parlamentares/models.py#L302) não pode ser acessado no objeto Parlamentar.

**Comment by LucianoAlmeida** [comment]
No final deste parágrafo do manual do Django (https://docs.djangoproject.com/en/1.11/ref/contrib/contenttypes/#reverse-generic-relations) é informado de que as Generic Relations não possuem o parâmetro on_delete, não sendo possível fazer a proteção contra exclusão em cascata.
As opções dadas são: não usar generic relation ou criar um sinal pre_delete.

**Comment by LucianoAlmeida** [comment]
@LeandroRoberto @marciomazza  @edwardoliveira
Não sei o que poderia fazer neste caso. Alguém tem alguma ideia?

**Comment by LeandroRoberto** [comment]
Pra efeito de documentação, no link citado pelo @LucianoAlmeida é apresentado `related_query_name` que permite fazer o teste da relação inversa via queryset.

`related_query_name` podem ser usados nos queryset's dos models que possuem atributos do tipo  `GenericForeignKey`

exemplo no sapl:
sapl/base/models.py...
```
...
class Autor(models.Model):
...
    content_type = models.ForeignKey(
        ContentType,
        blank=True, null=True, default=None)
    object_id = models.PositiveIntegerField(
        blank=True, null=True, default=None)
    autor_related = GenericForeignKey('content_type', 'object_id')
...

```
do outro lado os `GenericRelation`, como em sapl/parlamentares/models.py...
```
...
class Parlamentar(models.Model):
...
    # campo conceitual de reversão genérica para o model Autor que dá a
    # o meio possível de localização de tipos de autores.
    autor = SaplGenericRelation(
        Autor,
        related_query_name='parlamentar_set',
        fields_search=(
            # na primeira posição dever ser campo simples sem __
            ('nome_completo', '__icontains'),
            ('nome_parlamentar', '__icontains'),
            ('filiacao__partido__sigla', '__icontains'),
        ))
...
```
esse conjunto permite as consultas diretas e reversas... 

**quando via autor, pela classe:**
```Autor.objects.filter(parlamenar_set__nome='fulano')```

**quando via autor, pela objeto:**
```
autor = Autor.objects.first()
autor.parlamentar_set.all()
```
observe que:
quando via objeto, os `related_query_name` só podem ser usados um de cada vez...
quando via classe os `related_query_name` podem ser usados em conjunto, como numa possibilidade de estar pesquisando em `GenericRelation` diferentes, exemplo:
```
Autor.objects.filter(
    Q(parlamenar_set__nome='fulano') | Q(comissao_set__nome='ccj')
)
```

**quando via parlamentar ou outro model associado:**
usando o atributo do tipo `GenericRelation` em Parlamentar ou outro model.
```
parlamentar = Parlamentar.objects.first()
parlamentar.autor.all()

comissao = Comissao.objects.first()
comissao.autor.first()

bloco = Bloco.objects.get(pk=5)
bloco.autor.last()
```
para o caso de autores no sapl, as `GenericForeignKey` são OneToOne e isso é tratado por
`unique_together = (('content_type', 'object_id'), )` no model Autor, mas o django é preparado para trabalhar as `GenericForeignKey` com ManyToOne.
