### ISSUE TITLE
Migrar documentos do editor SDE (editor xml no zope)

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#125]
SDE é o editor estruturado XML antigo, que apenas algumas casas usam.

Precisamos de alguma migração desses documentos, nem que seja de uma versão transformada deles, como em HTML ou docx.

Como pouca gente usa (mesmo?) vale a pena deixarmos essa migração para uma versão seguinte?

**Comment by marciomazza** [comment]
@LeandroRoberto nos lembrou que um exemplo de Câmara que usa o SDE é Guariba-SP (Luis Carlos Sponhardi é de lá, membro do GITEC).

**Comment by marciomazza** [comment]
Devemos avaliar a adequação de migrar para o novo módulo de proposições usando o editor de texto articulado feito por @LeandroRoberto.

**Comment by marciomazza** [comment]
Estou na dúvida se isso é mesmo pro milestone `Futuro`. Que vcs acham @edwardoliveira, @LeandroRoberto ?

1) O que faremos com as casas que usam?

2) O que faremos com os documentos legados feitos no SDE?

**Comment by LeandroRoberto** [comment]
o html gerado poderia vir para dentro de um Texto Articulo do tipo genérico (a ser configurado), não programado e sim, configurado...

**Comment by LeandroRoberto** [comment]
além disso, não imagino como resolver

**Comment by marciomazza** [comment]
O que observei ao fazer a migração de documentos é que os aquivos gerados pelo SDE são `xml`'s com algumas folhas `XSL` associadas.
Portei essas folhas de uma base típica o sapl 2.5 em eab4eac.
Com isso os arquivos gerados pelo SDE podem ser visualizados corretamente no browser.

É importante ficarmos atentos ao migrar os documentos das diversas bases hospedadas porque, teoricamente, acho que os usuários pdem ter criados *modelos* diferentes para o SDE e modificado ou acrescentado suas folhas de estilo. É improvável, mas se isso tiver acontecido podemos ter de fazer adaptações acrescentando mais folhas ou tornando as folhas `xsl` configuráveis por banco (agora são fixas, nos arquivos estáticos).

**Comment by marciomazza** [comment]
Ao refazer a migração de documentos acessando o ZODB diretamente percebi que exitem objetos do SDE que não migrei. Os objetos que encontrei são têm meta_type `SDE-Document` e classe `Products.StructuredDoc.StrDoc.StrDoc` e estavam em `sapl_documentos/proposicao` em um ZODB.

Acho que os xml's que encontrei são uma saída do SDE, uma espécie de "versão final". Estou entendendo que os originais editáveis são esses objetos que encontrei.

Estou reabrindo então essa issue.

A princípio podemos:

1. Extrair a estrutura de dados e exportar como um yaml. Depois podemos avaliar se convertemos para o novo formato de proposição; **ou**
2. usamos o código do SDE para obtermos o xml final (se for assim mesmo que a coisa funciona).

**Comment by LeandroRoberto** [comment]
acredito que o xml seja o resultado dos objetos. Esse xml é renderizado em html via xslt... então, acredito que o mais simples a se fazer é capturar esse html já renderizado e passar para um html2pdf qualquer e armazenar essa base legada como um pdf da proposição.

**Comment by marciomazza** [comment]
A rotina criada em #1584 exporta os dados dos documentos do SDE em formato yaml.

É preciso agora transformar esses dados exportados no xml usando o código do SDE
(https://colab.interlegis.leg.br/browser/publico/SDE/trunk)

**Comment by marciomazza** [comment]
Eu tentei portar a renderização de XML do SDE para a migração, mas me deparei com um cenário complexo demais para o que parece ser um pequeno número de casas que utilizam esse módulo.

Decidi, a princípio, fazer _scraping_ dos documentos rederizados. Caso isso se mostre realmente insuficiente podemos repensar.
