### ISSUE TITLE
Ordem do Dia: incluir matéria já incluída nas Matérias do Expediente

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1254]
Deve ser possível incluir na Ordem do Dia matérias constantes das Matérias do Expediente da mesma sessão. Atualmente a resposta é "Essa matéria já foi cadastrada". Porém, tal resposta deve ser mantida se a matéria estiver sendo incluída na mesma parte da sessão.

**Comment by edwardoliveira** [comment]
@andreagudo Favor verificar se solucionou dentro de alguns minutos.

**Comment by andreagudo** [comment]
Resolvida.
