### ISSUE TITLE
Adicionar várias matérias nas Matérias do Expediente: pesquisa

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1257]
Pesquisa de matérias a serem adicionadas não funciona adequadamente. Exemplo: pesquisando pelos critérios Requerimentos de Lei de 2017, não retorna nenhum.

**Comment by eduardocalil** [comment]
@andreagudo Existe uma condição para uma Matéria aparecer como opção para ser adicionada. O seu status atual deve ser 'Ordem do Dia'.

**Comment by andreagudo** [comment]
Essa resposta é correta para a #1256 , não para esta. No 2.5 há uma pesquisa por status a partir do botão "gerar pauta", devendo se escolher o que quiser.
![captura de tela de 2017-08-11 14 33 14](https://user-images.githubusercontent.com/19169882/29224796-2cff7176-7ea2-11e7-8db5-5210c3f82db4.png)

**Comment by eduardocalil** [comment]
@andreagudo Não entendi. Poderia explicar mais detalhadamente? Esta issue fala sobre **Adicionar Várias Matérias** e em seguida você falou sobre **Gerar Pauta**

**Comment by andreagudo** [comment]
No 2.5, nas Matérias do Expediente, há as opções "Incluir Matéria no Expediente", "Incluir Várias Matérias no Expediente" e "Gerar Pauta". Geralmente uso essa última que, diferente da segunda, seleciona matérias segundo qualquer status, e não um pré-definido (como ocorre com a inclusão de várias matérias no Expediente e na Ordem do Dia). Considero isso muito útil, pois as casas legislativas usam, muitas vezes, status diferentes para essa etapa da tramitação. Assim, "Gerar Pauta" mostra a tela aí acima, que permite que sejam colocadas várias Matérias do Expediente numa só operação, segundo o critério de status.

**Comment by eduardocalil** [comment]
Adicionei a opção de filtra por status. Por favor, verifique se está do jeito que gostaria. Caso contrário, reabra esta issue.

**Comment by andreagudo** [comment]
Resolvido.
