### ISSUE TITLE
Reordenar Matérias não funciona

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1258]
Botão Reordenar Matérias não funciona nas Matérias do Expediente, nem na Ordem do Dia.

**Comment by edwardoliveira** [comment]
Este botão está com nome errado, na minha opinião. O que ele faz _na verdade_ é arrumar os buracos de uma lista de Expediente ou Ordem Dia que tenham números de ordem mudados ou ordens apagadas.

Exemplo: suponha que tenhamos as ordems 1, 2, 3, 4. Daí Apagamos a de número 3, deixando as ordens como 1, 2, 4. Este botão ordenar conserta isso fazendo com que a numeração final fique 1, 2, 3. Neste caso, se eu quisesse que a matéria 2, por exemplo, virasse a de número 3, eu a editaria para seu número de ordem ser 4. Ficaria 1, 3, 4. Assim, clicando no reordenar ele iria para 1, 2, 3, preservando sempre a ordem. 

Para reordenar mesmo é preferível usar o método de arrastar e soltar que o @eduardocalil implementou.

**Comment by andreagudo** [comment]
Ótimo. Corrigindo o nome do botão, a issue pode ser fechada.
