### ISSUE TITLE
Modo de exibição de janela sem adornos

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#126]
O sapl 2.5 tem a opção de rederizar suas páginas de adornos (cabeçaloh, rodapé), pra inclusão em outros sites, como o do portal modelo.

Parece que no sapl 2.5 esta funcionalidade é ativada passando o parâmetro `iframe=1` nas urls.
@jeanferri tem mais informações.

**Comment by eliseuegewarth** [comment]
Resolvido em #1204
