### ISSUE TITLE
Votação de Matéria com 0 parlamentares

### ISSUE THREAD

**Issue by falcao934jef** [interlegis/sapl#1263]
Ao tentar realizar a votação de uma matéria de 0 parlamentares presentes.

Para realizar a votação com nenhum parlamentar presente, ele abre a votação sendo impossível digitar valores acima de 0.

![image](https://user-images.githubusercontent.com/10059935/28027314-1d5afd86-656f-11e7-91af-006fe79ef69a.png)

Em Matérias de Ordem do Dia, ao tentar realizar qualquer uma das votações ([15ª Sessão Ordinária da 1ª Sessão Legislativa da 15ª Legislatura](http://sapl31agudo.interlegis.leg.br/sessao/430/ordemdia))

**Comment by edwardoliveira** [comment]
@falcao934jef Eu desabilitei a abertura de votação quando não houver presença para aquela sessão plenária. Vou fazer um novo release. Verifica se consertou.

**Comment by falcao934jef** [comment]
@edwardoliveira Resolvido :)
