### ISSUE TITLE
indexação para pesquisa textual de novos arquivos

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1264]
Fazer a indexação automática para pesquisa textual em novos arquivos

**Comment by edwardoliveira** [comment]
Teria como vc testar essa indexação? Ver se ainda ocorrem memory leaks com o upload de matérias????

Precisa descomentar essas linhas: https://github.com/interlegis/sapl/blob/master/sapl/materia/signals.py#L12-L15 e daí reiniciar o servidor, eu acho. Não dá pra colocarmos isso num release novo pq se o memory leak ainda persistir isso vai potencialmente impactar os SAPL 3.1 que estão já hospedados aqui. Inclusive, os signals.py em sapl/norma também deveria estar comentado, mas não foi por algum motivo. :man_shrugging:

**Comment by edwardoliveira** [comment]
Essa issue foi resolvida pelos commits aa77412623c0598326e4d70b27e9884e25465924 , 71491c33dd3769b66bc98199e6d8027f6862e4e5, e 71491c33dd3769b66bc98199e6d8027f6862e4e5.
