### ISSUE TITLE
Inclusão de autoria de matéria legislativa: Filtrar nomes por tipo de autor

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1265]
No 2.5, ao incluir o autor de uma matéria, o sistema apresenta os campos Tipo e Nome, com o segundo oferendo opões de acordo com o Tipo. O 3.1 está apresentando, no campo Nome, todos os possíveis, independentemente de tipo.
![captura de tela de 2017-07-10 16 02 12](https://user-images.githubusercontent.com/19169882/28035192-16e57dee-658a-11e7-8f91-375dff2fab77.png)
![captura de tela de 2017-07-10 16 07 08](https://user-images.githubusercontent.com/19169882/28035195-1c79172a-658a-11e7-9299-6e4e6bdfae72.png)

**Comment by DtiLegBG** [comment]
Os autores do tipo parlamentar não estão sendo carregados corretamente
![image](https://user-images.githubusercontent.com/13314947/28797627-57467160-7618-11e7-9f27-43659c454eb9.png)

Desta lista só 4 estão ativos, e esta lista deveria ter 17.

**Comment by LeandroRoberto** [comment]
Resolvido por #1328

**Comment by andreagudo** [comment]
O parlamentares não está sendo listados, seja de que legislatura for a matéria.
