### ISSUE TITLE
Usuário e senha django

### ISSUE THREAD

**Issue by fabiobelo** [interlegis/sapl#1266]
Bom dia, nobres! Alguém sabe me informar o usuário e senha do django? 

Gostaria de administrar os usuários?

Outra questão, quando não trabalho com o DEBUG=TRUE como tenho acesso? devo criar usuários antes?

**Comment by edwardoliveira** [comment]
Os usuários são administrados via http://url:8000/admin

Vc deve criar um super usuário antes de poder criar os usuários e daí logar na URL correspondente. Veja mais detalhes em https://docs.djangoproject.com/en/1.11/ref/django-admin/#django-admin-createsuperuser

Ao criar um usuário vc deve configurar as ROLES dele (ex: operador_geral, operador_materia, etc).

**Comment by fabiobelo** [comment]
Amigo, consegui realizar a ação com o comando: ./manage.py createsuperuser
