### ISSUE TITLE
Adicionar várias matérias na ordem do dia

### ISSUE THREAD

**Issue by fabiobelo** [interlegis/sapl#1268]
Ao clicar em selecionar várias matérias na ordem do dia e no expediente não retorna nenhum dado, mesmo tendo diversas matérias cadastras.

Como devo proceder? Alguém já passou pelo mesmo 'problema'?

**Comment by edwardoliveira** [comment]
Sim, acabamos de fechar duas issues sobre isso.

As matérias a serem adicionadas na Ordem do Dia ou Expediente tem que estar com status de tramitação atual 'Ordem do Dia'. Senão não aparecem mesmo.

**Comment by fabiobelo** [comment]
Onde consigo alterar o status?

**Comment by edwardoliveira** [comment]
Na tramitação da matéria.
