### ISSUE TITLE
Controle de Painel Eletrônico inativo

### ISSUE THREAD

**Issue by falcao934jef** [interlegis/sapl#1269]
A utilização para controle do Painel Eletrônico dentro de uma sessão plenária, se encontra com os botões inativos, ou seja, não retornam nenhuma ação.

**Caminho**
Sessões Plenária -> Painel Eletrônico -> Controlador do Painel

![image](https://user-images.githubusercontent.com/10059935/28117694-db411472-66e4-11e7-90e4-222aac56d84c.png)

**Comment by eduardocalil** [comment]
Com qual usuário você estava?

**Comment by edwardoliveira** [comment]
Acabou que esta tela não é mais necessária dada a reestruturação do painel. Assim, removemos esta tela (MUITO ANTIGA) do SAPL.
