### ISSUE TITLE
Migração de documentos

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1277]
Foram retiradas do arquivo sapl/utils.py as duas funções abaixo no seguinte PR
https://github.com/interlegis/sapl/commit/71491c33dd3769b66bc98199e6d8027f6862e4e5#diff-248fb73d01307eb54567bfe0ba11d306

def save_texto(sender, instance, **kwargs):
    update_index = UpdateIndexCommand()
    update_index.start()

def delete_texto(sender, instance, **kwargs):
    update_index = UpdateIndexCommand()
    update_index.start()

No entanto o migrador de documentos precisa delas
https://github.com/interlegis/sapl/blob/master/sapl/legacy/migracao_documentos.py#L17

**Comment by eribeiro** [comment]
Precisa não.

O q o script tá fazendo é desligar os signals dessas funções. Como elas não são mais necessárias (nem devem ser utilizadas) basta remover toda e qualquer referência a essas funções do arquivo de migração. Dá pra resolver isso com um PR simples. O que NÃO DEVE SER FEITO é ret9rnar essas funções para o código (como não são mais utilizadas não tem nem porque desligar)

**Comment by DtiLegBG** [comment]
opa, vou testar, se eu conseguir fazer funcionar, faço o PR. Obrigado !!

**Comment by DtiLegBG** [comment]
resolvido!
https://github.com/interlegis/sapl/pull/1279
