### ISSUE TITLE
Criar pasta media no checkout do repositório

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1278]
Seria interessante criar a pasta media no projeto, esta pasta é criada só quando é feito o upload de algum arquivo. Porem se for feito a instalação nova, posterior migração de documentos, esta pasta tem que ser criada para posicionar os documentos do sapl 2.5 para migração em media/sapl_documentos

**Comment by marciomazza** [comment]
Basta "versionar" a pasta `media` vazia, com algum arquivo vazio (pois o `git` não versiona pastas).
