### ISSUE TITLE
Migração - Migração de documentos

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1280]
Ao migrar documentos, o migrador parou neste ponto

#### Migrando texto_original de Proposicao ####
---------------------------------------------------------------------------
DoesNotExist                              Traceback (most recent call last)
/var/interlegis/sapl/sapl/legacy/migracao_documentos.py in migrar_docs_por_ids(tipo)
    173                     id = match.group(1)
--> 174                     obj = tipo.objects.get(pk=id)
    175

/var/interlegis/.virtualenvs/sapl/lib/python3.5/site-packages/django/db/models/manager.py in manager_method(self, *args, **kwargs)
    121             def manager_method(self, *args, **kwargs):
--> 122                 return getattr(self.get_queryset(), name)(*args, **kwargs)
    123             manager_method.__name__ = method.__name__

/var/interlegis/.virtualenvs/sapl/lib/python3.5/site-packages/django/db/models/query.py in get(self, *args, **kwargs)
    386                 "%s matching query does not exist." %
--> 387                 self.model._meta.object_name
    388             )

DoesNotExist: Proposicao matching query does not exist.

During handling of the above exception, another exception occurred:

UnboundLocalError                         Traceback (most recent call last)
<ipython-input-2-e410b87655fe> in <module>()
----> 1 migrar_documentos()

/var/interlegis/sapl/sapl/legacy/migracao_documentos.py in migrar_documentos()
    230         DocumentoAcessorioAdministrativo,
    231     ]:
--> 232         migrar_docs_por_ids(tipo)
    233
    234     sobrando = [os.path.join(dir, file)

/var/interlegis/sapl/sapl/legacy/migracao_documentos.py in migrar_docs_por_ids(tipo)
    189                     msg = '  {} (pk={}) não encontrado para documento em [{}]'
    190                     print(msg.format(
--> 191                         tipo.__name__, id, destino))
    192
    193

UnboundLocalError: local variable 'destino' referenced before assignment

**Comment by marciomazza** [comment]
@DtiLegBG Ainda está com esse problema?

**Comment by DtiLegBG** [comment]
sim, fiz novamente uma migração de teste o problema se repetiu.

**Comment by marciomazza** [comment]
@DtiLegBG Acredito que esteja resolvido agora. Pode fazer um teste com seus dados?
