### ISSUE TITLE
Relatórios - Matérias por Ano, Autor e Tipo 

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1284]
Seria interessante que neste relatório fossem mostrados os totais por autor, além do total geral. Ficando desnecessário mostrar as matérias

No sapl 2.5

![image](https://user-images.githubusercontent.com/13314947/28422498-957d7056-6d3e-11e7-8f96-84bb7731f5bc.png)

No sapl 3.1
![image](https://user-images.githubusercontent.com/13314947/28422881-bc41b246-6d3f-11e7-85a8-22cd974c590f.png)

http://sapl3beta.camarabento.rs.gov.br/sistema/relatorios/materia-por-ano-autor-tipo?ano=2016&salvar=Pesquisar

**Comment by eduardocalil** [comment]
@DtiLegBG Não entendi. Poderia detalhar um pouco melhor, por favor?

**Comment by DtiLegBG** [comment]
No SAPL 3.1 só é mostrado o quadro de quantidades para o geral, além deste seria interessante manter o que existe no 2.5 que é mostrar as quantidades também por autor. Já exibir uma relação das matérias por autor se faz desnecessário tendo em vista estar contemplada em outro relatório.

http://sapl.camarabento.rs.gov.br/relatorios_administrativos/propositurasAnoAutorTipo/view?ano=2017

http://sapl3beta.camarabento.rs.gov.br/sistema/relatorios/materia-por-ano-autor-tipo?ano=2017&salvar=Pesquisar

**Comment by edwardoliveira** [comment]
@DtiLegBG Por favor, verifique se esse commit soluciona essa issue. Se não, favor reabrir.

**Comment by DtiLegBG** [comment]
No sapl 2.5 não eram considerados as matérias em que o autor era co-autor, mas dessa forma também não deixa de estar certo.
Resolvido !
