### ISSUE TITLE
Pesquisa Textual - Ordenar

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1287]
Seria interessante ordenar de alguma forma o resultado da pesquisa textual

![image](https://user-images.githubusercontent.com/13314947/28430049-6427b590-6d55-11e7-9562-4eb62e70b4b4.png)

uma sugestão seria por ano/tipo
Também seria interessante na medida do possível manter o padrão das outras telas de resultado de pesquisa onde é mostrado o total de resultados encontrados e no rodapé o paginador

![image](https://user-images.githubusercontent.com/13314947/28430073-87e394e0-6d55-11e7-85b3-201cf3a30c6a.png)

Outra telas de resultado
![image](https://user-images.githubusercontent.com/13314947/28430136-bf8fde44-6d55-11e7-986e-73b7c5e1e0df.png)

**Comment by eduardocalil** [comment]
Eu e o @edwardoliveira pesquisamos durante a semana passada um meio de ordenar, mas vimos que exigiria muitas mudanças porque a máquina de busca textual traz os registros por ordem de relevância em relação aos termos pesquisados. Isto exigiria customização de classes de baixo nível do haystack e poderia prejudicar a relevância dos resultados trazidos só por causa da ordenação. Além disso, numa busca textual que traz mais do que 1 model geraria ainda mais complexidade de implementação.
