### ISSUE TITLE
Pesquisa de Autoria

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1289]
Na pesquisa de autoria deve ser possível pesquisar todos os autores do sistema, não somente os ativos.
Seria o caso de poder fazer a pesquisa em matérias por autores que não estão mais ativos.

![image](https://user-images.githubusercontent.com/13314947/28438086-47d388f6-6d73-11e7-8593-661fa794abea.png)

**Comment by DtiLegBG** [comment]
Além de somente estarem sendo pesquisado os ativos, só estão sendo pesquisados os autores do tipo parlamentar ativos

**Comment by eduardocalil** [comment]
@eliseuegewarth

**Comment by eliseuegewarth** [comment]
O PR #1315 resolve essa issue, mas a issue #1096 deve ser reaberta. Uma boa opção para solucionar a #1096 é usar um ModelChoiceField como utilizado na issue #1290.
@edwardoliveira @DtiLegBG

**Comment by DtiLegBG** [comment]
Está resolvido ! Acho que não devemos abrir a 1096, vou monitorar a inclusão de autoria nas matérias após o merge, se não estiver ok, abro uma exclusivamente sobre.
