### ISSUE TITLE
Texto Integrais - Abrir em nova janela

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1295]
Os textos integrais de matérias, normas, geração de pdf de sessão estão sendo aberto na mesma janela, obrigando o usuário a usar o botão de voltar do browse.

**Comment by eduardocalil** [comment]
Infelizmente, devido a bibliotecas internas do SAPL, essa mudança alteraria a forma como as telas são renderizadas, o que poderia trazer problemas para outros tipos de links que não sejam arquivos PDF. Entretanto, com a volta do Mazza, em agosto, poderemos ver se existe alguma forma mais segura de fazer isso.

Para contornar esta situação, você poderá clicar com o botão central do mouse (scroll) sobre o link e uma nova aba será aberta.
