### ISSUE TITLE
Frentes Parlamentares

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1296]
As resoluções que criam as frentes aqui em Bento Gonçalves, definem cargos para os Parlamentares

http://sapl3beta.camarabento.rs.gov.br/media/sapl/public/normajuridica/2017/19020/19021-texto-integral.pdf

Acho que seria interessante ou nas tabelas auxiliares criar os cargos de frente, como é feito com as comissões, ou um campo de texto livre ao lado de cada parlamentar integrante para adicionar o cargo/função

![image](https://user-images.githubusercontent.com/13314947/28524383-9d4c9e18-7056-11e7-9b97-a3d1cf87eb85.png)

**Comment by marimendes** [comment]
Boa tarde @DtiLegBG. Você sabe me disser quais são esses cargos? Ex: Presidente, vice...

**Comment by edwardoliveira** [comment]
Relaciona-se a #1798 #561 #1798 #1936 #1392
