### ISSUE TITLE
Menu para acesso as frentes Parlamentares

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1297]
Acho que teria que ser colocado um submenu em "atividade legislativa" - discutir se é o local correto ou institucional -  para listar as frentes parlamentares, a exemplo do que é feito com as comissões.

**Comment by DtiLegBG** [comment]
#1296

**Comment by eliseuegewarth** [comment]
@edwardoliveira

**Comment by edwardoliveira** [comment]
@eliseuegewarth O que tem esse issue? Quer fazer pro 3.1? Por mim, tudo bem.

**Comment by eduardocalil** [comment]
Foi decidido em reunião que esta issue é inválida, pois `Frente` é uma `Tabela Auxiliar`. Por esse motivo, será fechada.

**Comment by andreagudo** [comment]
Mas somente o usuário admin poderá acessar as frentes, mesmo que seja apenas para pesquisa?

**Comment by DtiLegBG** [comment]
@eduardocalil você não acha importante um tela pública de consulta onde sejam listadas todas as frentes?
uma lista como essa
http://sapl.camarabento.rs.gov.br/sistema/frente/
Onde essa tela pudesse ser alcançada pelo menu institucional.

Da forma que está, se tem acesso as frentes que o parlamentar faz parte
http://sapl.camarabento.rs.gov.br/parlamentar/54/frente

porém não se sabe quantas frentes existem

**Comment by DtiLegBG** [comment]
Resolvido
https://github.com/interlegis/sapl/commit/cfd0775c7f84ea0fbede8e7c26ca06e6ad6d812b
