### ISSUE TITLE
Atualizar versão do Django para 1.9

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#13]
Funcionalidades de terceiros parecem estar sendo rapidamente atualizadas.  Temos então alguns detalhes no SAPL e já foi identificado também a mesma necessidade no fork sass-processor que está neste repositório.

**Comment by marciomazza** [comment]
* retirar a restricão `django<1.9` do requirements.txt 
* rodar `pip install --upgrade -r requirements/dev-requirements.txt`
* testar
