### ISSUE TITLE
API de dados abertos

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#130]
Usar django-rest-framework, provavelmente.

**Comment by eliseuegewarth** [comment]
Qual a extensão dessa API? Que dados vamos disponibilizar?

**Comment by JDias** [comment]
Eu não conheço o sistem, então perdão se estiver falando besteira no lugar errado.
Procurei documentação acerca da API e achei esse ticket.
Gostaria saber se tem API, mas não sei se dados abertos seria o termo.
Gostaria dos dados de tramitação, por exemplo (como provavelmente o sigalei https://sigalei.com.br usa)
