### ISSUE TITLE
Relatórios - Presenças nas sessões

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1304]
Existem diferenças nos percentuais. Quanto aos percentuais das sessões pode ser questão de arredondamento, quanto ao percentuais na ordem do dia, existe um problema relacionado ao total, o valor total do cabeçalho de ordem do dia  em alguns caso é menor que o valor individual de presenças

http://sapl3beta.camarabento.rs.gov.br/sistema/relatorios/presenca?data_inicio_0=01%2F01%2F2017&data_inicio_1=25%2F07%2F2017&salvar=Pesquisar

SAPL 3.1

![image](https://user-images.githubusercontent.com/13314947/28583481-aea1b8a8-713f-11e7-960c-997a9662396c.png)

SAPL 2.5

![image](https://user-images.githubusercontent.com/13314947/28583263-f2afa74a-713e-11e7-8b39-62e27fb331a1.png)

**Comment by DtiLegBG** [comment]
O total correto no sapl 3.1 que deveria aparecer no cabeçalho seriam 28, conforme sapl 2.5

**Comment by DtiLegBG** [comment]
Pelo que pude entender o que acontece é o seguinte, agora falando somente de sapl 3.1:

O total de 27 ordens do dia é baseado no registros da tabela sessao_ordemdia:

![image](https://user-images.githubusercontent.com/13314947/28825656-8c2dd0a0-769d-11e7-8136-0cedcaae7b50.png)


![image](https://user-images.githubusercontent.com/13314947/28825779-04ad7b84-769e-11e7-9fa9-61053f8b258c.png)

ocorre que para uma sessão não existiram matérias na ordem, portanto não gerando registro na tabela sessao_ordemdia, mas foi registrada a presença do parlamentar para aquela ordem do dia mesmo sem matérias:

![image](https://user-images.githubusercontent.com/13314947/28825895-66574900-769e-11e7-9362-03fef1775e16.png)


Aqui o registro de presença na sessao_plenaria_id 348. E como visto acima não existe esse registro 348 na tabela sessao_ordemdia porque não foram incluídas matérias.

![image](https://user-images.githubusercontent.com/13314947/28825984-b3fe8e48-769e-11e7-9e06-98e4a179bc46.png)

**Comment by andreagudo** [comment]
Apenas para constar, visando implementação futura, pois penso ser algo mais complexo. O percentual de presenças deveria considerar as sessões e ordens do dia em que o parlamentar deveria ter participado, mas está considerando as realizadas. Isso leva a um erro de interpretação, fazendo concluir que houve faltas em períodos em que o parlamentar não estava no mandato e, portando, sequer poderia ter participado de sessões. Penso que há relação com a #413 .

**Comment by DtiLegBG** [comment]
E o registro de presença na ordem do dia é necessário para a votação das matérias do expediente, então neste caso não seria possível somente excluir a presença da ordem do dia, tendo em vista existirem matérias no expediente

**Comment by DtiLegBG** [comment]
Parece que a forma mais correta é pegar o maior valor de presenças e considerar como total

**Comment by DtiLegBG** [comment]
#1178

**Comment by eduardocalil** [comment]
@DtiLegBG Feito. Teste, por favor, e se estiver tudo ok feche esta issue.

**Comment by DtiLegBG** [comment]
Resolvido! obrigado
