### ISSUE TITLE
Pauta da Sessão - Expedientes

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1305]
Para as pautas importadas do sapl 2.5 a exibição de caracteres especiais está ok, porém para as cadastradas no sapl 3.1 não. Na geração do pdf está ok tanto para as importadas quanto para as cadastradas

![image](https://user-images.githubusercontent.com/13314947/28584370-de28021e-7142-11e7-915f-48fefd570bfa.png)

Seria interessante também que fosse mantido as quebras de linhas, conforme exibido nos expedientes da sessão e no pdf da pauta

![image](https://user-images.githubusercontent.com/13314947/28584585-a4e2cdc6-7143-11e7-9ed5-154e1fa37a4b.png)

**Comment by DtiLegBG** [comment]
Na base do 3.1 a diferença de como estão armazenados os dados importados e cadastrados
![image](https://user-images.githubusercontent.com/13314947/28584742-35ced50a-7144-11e7-9287-087fb3be39cf.png)

**Comment by edwardoliveira** [comment]
Acredito que a renderização vai estar correta depois do commit 5f49e3b . Poderia testar por favor?

Caso contrário, só reabrir esta issue.

**Comment by DtiLegBG** [comment]
Problema com os caracteres especiais resolvidos, o detalhe seria inserir as quebras de linha
http://sapl3beta.camarabento.rs.gov.br/sessao/pauta-sessao/372

**Comment by DtiLegBG** [comment]
Resolvido !!
