### ISSUE TITLE
Migração - Texto articulado

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1306]
As tabelas de compilação não estão sendo mais populadas durante a migração

**Comment by DtiLegBG** [comment]
Existe algum problema quanto ao script de popular o banco
https://github.com/interlegis/sapl/blob/master/sapl/compilacao/compilacao_data_tables.sql

Rodando por uma console do pgadmin:
query result with 1 row discarded.

query result with 1 row discarded.

query result with 1 row discarded.

ERROR:  duplicate key value violates unique constraint "compilacao_tipodispositivorelationship_pai_id_06790a7a_uniq"
DETAIL:  Key (pai_id, filho_permitido_id, perfil_id)=(119, 122, 1) already exists.
********** Error **********

ERROR: duplicate key value violates unique constraint "compilacao_tipodispositivorelationship_pai_id_06790a7a_uniq"
SQL state: 23505
Detail: Key (pai_id, filho_permitido_id, perfil_id)=(119, 122, 1) already exists.

No log após a instalação, não sei em qual momento
Ocorreu erro na importação: INSERT INTO compilacao_tipodispositivorelationship (filho_permitido_id, pai_id, filho_de_insercao_automatica, perfil_id, quantidade_permitida, permitir_variacao) VALUES (122, 119, false, 1, -1, false);duplicate key value violates unique constraint "compilacao_tipodispositivorelationship_pai_id_06790a7a_uniq"
DETAIL:  Key (pai_id, filho_permitido_id, perfil_id)=(119, 122, 1) already exists.

Ocorreu erro na importação: INSERT INTO compilacao_tipodispositivorelationship (filho_permitido_id, pai_id, filho_de_insercao_automatica, perfil_id, quantidade_permitida, permitir_variacao) VALUES (122, 119, false, 2, -1, true);duplicate key value violates unique constraint "compilacao_tipodispositivorelationship_pai_id_06790a7a_uniq"
DETAIL:  Key (pai_id, filho_permitido_id, perfil_id)=(119, 122, 2) already exists.

**Comment by DtiLegBG** [comment]
o erro acontece a neste ponto
https://github.com/interlegis/sapl/blob/master/sapl/compilacao/compilacao_data_tables.sql#L260-L264

**Comment by LucianoAlmeida** [comment]
@LeandroRoberto, esse problema eu não sei resolver. Seria possível dar uma olhada nela?

**Comment by LeandroRoberto** [comment]
não é um problema de migração.

**Comment by LeandroRoberto** [comment]
@DtiLegBG, acredito que está resolvido...
