### ISSUE TITLE
Acompanhamento de matéria

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1307]
O acompanhamento de matéria só deve estar disponível para matérias em tramitação

![image](https://user-images.githubusercontent.com/13314947/28618688-a9e123de-71db-11e7-898f-52f1ae9c55bb.png)

![image](https://user-images.githubusercontent.com/13314947/28618661-958daf06-71db-11e7-88fb-af1afb5f512a.png)

**Comment by edwardoliveira** [comment]
Particularmente, eu acho que deve estar sempre disponível, esteja a matéria em tramitação ou não.

Se a matéria começar a ser tramitada seria interessante enviar o email para os interessados, visto que o que interessa é acompanhar a matéria e não a tramitação em si.

/cc @LeandroRoberto @andreagudo o que vcs acham?

**Comment by andreagudo** [comment]
Entendo que o usuário pode acompanhar a tramitação da matéria, não ela própria. Então, o acompanhamento só faz sentido para as que estão em tramitação.

**Comment by eliseuegewarth** [comment]
E se o usuário quiser receber notificações sobre a matéria quando ela começar a ser tramitada? @DtiLegBG @andreagudo

**Comment by DtiLegBG** [comment]
Abri essa issue porque no sapl 2.5 funciona da forma apontada na issue. Porém a minha opinião particular é que todas matérias deveriam ser passíveis de acompanhamento, ou seja, continuar da forma que está no sapl 3.1 pelo seguinte motivo.
Aqui no final do ano todas as matérias são arquivadas(param de tramitar), são desarquivadas mediante solicitação. Se alguém quiser se cadastrar para acompanhar uma matéria que não está tramitando e por ventura poderia voltar a tramitar não conseguiria, ou seja, vejo como uma ferramenta a mais de monitoramento.

@andreagudo, posso fechar ?

**Comment by andreagudo** [comment]
Permitir acompanhamento de matérias que não mais tramitam pode gerar confusão para os leigos, especialmente. Além disso, as matérias, ao serem desarquivadas, devem tramitar para algum lugar, o que poderia ser acompanhado de mudança no indicador de tramitação para "sim", voltando a permitir o acompanhamento. É possível implementar isso? Não sendo, me rendo aos argumentos do @DtiLegBG .

**Comment by DtiLegBG** [comment]
Essa questão de alterar o indicador para sim já existe, no indicador de tramitação/status de tramitação como retorno. Então quando uma matéria está no arquivo e é tramitada com um status de tramitação que tenha como indicador retorno,  o indicador em tramitação é alterado automaticamente para sim. Mas o galho é o cidadão querer se cadastrar para acompanhamento da matéria, enquanto ela estiver no arquivo, para caso ela volte a tramitar ser avisado

**Comment by andreagudo** [comment]
Ok, concordo.
