### ISSUE TITLE
Painel

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1312]
Painel aberto mesmo sem nenhuma matéria para votação

**Comment by eduardocalil** [comment]
Por favor nos envie um PrintScreen e o caminho que gerou o erro

**Comment by paulot12** [comment]
É possível abrir o painel, mesmo sem nenhuma votação?

**Comment by edwardoliveira** [comment]
Sim. Mas deve aparecer uma mensagem do tipo "Nenhuma matéria sendo votada".

**Comment by eduardocalil** [comment]
Na verdade ele mostra que o Painel de Votação está fechado. Entretanto, ele mostra a última matéria votada, tendo como prioridade a Ordem do Dia. Ou seja, se uma Ordem do Dia foi votada e não há nenhuma outra votação aberta, o que aparecerá será o resultado da Ordem do Dia.
