### ISSUE TITLE
Customizar o painel de votação para que apareça o brasão da casa legislativa

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1319]
É possível adaptar o layout do painel para cada Casa Legislativa?

**Comment by paulot12** [comment]
Aparecer a logomarca do Poder Legislativo.


________________________________
De: Edward <notifications@github.com>
Enviado: segunda-feira, 31 de julho de 2017 14:08
Para: interlegis/sapl
Cc: paulot12; Author
Assunto: Re: [interlegis/sapl] Mudar o layout do painel (#1319)


Não. Atualmente o layout é fixo. Seria alterar em que sentido? O que poderia ser customizado?

**Comment by marimendes** [comment]
![captura de tela de 2017-09-21 15-42-34](https://user-images.githubusercontent.com/11450196/30714102-0951a9d6-9ee8-11e7-90d7-1e25b688f5ab.png)
![captura de tela de 2017-09-21 16-14-05](https://user-images.githubusercontent.com/11450196/30714109-0d0364ac-9ee8-11e7-956d-bfe6cd1caccc.png)

Como não foi especificado o local do logotipo, fizemos esses dois casos como exemplo. Qual local você acharia melhor? Observe também que foi usado como exemplo uma imagem com o fundo branco e houve um contraste pois o painel possui fundo preto.

**Comment by paulot12** [comment]
A QUARTA IMAGEM -  EM CIMA DO NOME "PAINEL ENCONTRA-SE FECHADO"

________________________________
De: Mariana Mendes <notifications@github.com>
Enviado: quinta-feira, 21 de setembro de 2017 16:27
Para: interlegis/sapl
Cc: paulot12; Author
Assunto: Re: [interlegis/sapl] Customizar o painel de votação para que apareça o brasão da casa legislativa (#1319)


[captura de tela de 2017-09-21 15-42-34]<https://user-images.githubusercontent.com/11450196/30714102-0951a9d6-9ee8-11e7-90d7-1e25b688f5ab.png>

[https://user-images.githubusercontent.com/11450196/30714102-0951a9d6-9ee8-11e7-90d7-1e25b688f5ab.png]

[captura de tela de 2017-09-21 16-14-05]<https://user-images.githubusercontent.com/11450196/30714109-0d0364ac-9ee8-11e7-956d-bfe6cd1caccc.png>

[https://user-images.githubusercontent.com/11450196/30714109-0d0364ac-9ee8-11e7-956d-bfe6cd1caccc.png]

Como não foi especificado o local do logotipo, fizemos esses dois casos como exemplo. Qual local você acharia melhor? Observe também que foi usado como exemplo uma imagem com o fundo branco e houve um contraste pois o painel possui fundo preto.
