### ISSUE TITLE
Colocar a "ementa" na tramitação em lote

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1320]
É possível colocar a "ementa" ao pesquisar para tramitar em lote?

**Comment by edwardoliveira** [comment]
Não.

**Comment by paulot12** [comment]
Como colocar as matérias no pefil da cada parlamentar?


________________________________
De: Edward <notifications@github.com>
Enviado: segunda-feira, 31 de julho de 2017 18:37
Para: interlegis/sapl
Cc: paulot12; Author
Assunto: Re: [interlegis/sapl] Colocar a "ementa" na tramitação em lote (#1320)


Não.

**Comment by DtiLegBG** [comment]
Definindo a autoria da matéria.  Ou seja na matéria cadastrar autor.



Em 2017-07-31 19:14, paulot12 escreveu:

**Comment by paulot12** [comment]
Nós cadastramos, mas não aparece.

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Rogério Frá<mailto:notifications@github.com>
Enviado:segunda-feira, 31 de julho de 2017 19:17
Para: interlegis/sapl<mailto:sapl@noreply.github.com>
Cc:paulot12<mailto:paulotorres839@hotmail.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [interlegis/sapl] Colocar a "ementa" na tramitação em lote (#1320)

Definindo a autoria da matéria. Ou seja na matéria cadastrar autor.



Em 2017-07-31 19:14, paulot12 escreveu:
