### ISSUE TITLE
Refatorar rotina de Autor, Autoria e pesquisas de Autor.

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#1328]
Refatoração contemplará issues, #1096, #1273, #1265, #1324, #1289, #1327

**Comment by LeandroRoberto** [comment]
#1273 resolvido diretamente no master com o commit b437f1e

**Comment by DtiLegBG** [comment]
sobre o #1273

ao editar um autor, clicando em salvar

Exception Value: | 'str' object has no attribute 'username'
-- | --
/var/interlegis/sapl/sapl/base/forms.py in clean, line 244

**Comment by DtiLegBG** [comment]
#1354

**Comment by DtiLegBG** [comment]
#1359

**Comment by LeandroRoberto** [comment]
#1359 resolvido em https://github.com/interlegis/sapl/commit/cb9d9c558bb802966c1f3b562bb336530c821071

**Comment by fabiobelo** [comment]
Resolvido, amigos! Obrigado!
