### ISSUE TITLE
Frentes: opção "Listar somente os parlamentares ativos" não funciona

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1329]
![captura de tela de 2017-08-02 09 52 33](https://user-images.githubusercontent.com/19169882/28874489-6bf77cca-7768-11e7-9348-d38575565121.png)

**Comment by eliseuegewarth** [comment]
@andreagudo. A pesquisa "somente parlamentares ativos" implementada pelo @eduardocalil recupera somente os parlamentares que possuem mandato na data de criação da Frente, ou entre as Datas de Criação e Dissolução da Frente, caso a segunda seja informada. Detectou algum caso extraordinário?

**Comment by andreagudo** [comment]
A esse critério ter que ser acrescido o fato do parlamentar estar ativo, pois está sendo listado um inativo, Márcio Halberstadt. Para não precisar desse outro critério, deveria ser resolvida a #413 , onde as datas de afastamento poderiam ser registradas. Tal issue, porém, foi fechada.

**Comment by eliseuegewarth** [comment]
@eduardocalil @edwardoliveira, Alguma solução ou sugestão?

**Comment by LeandroRoberto** [comment]
buscas de autores possíveis também se baseia em mandato... a solução do 2.5 resolve tecnicamente o problema mas não é a solução conceitual... um vez eleito, o parlamentar possui um mandato e só.

**Comment by eduardocalil** [comment]
Concordo, Leandro. É necessário que isso seja discutido e seja tomada uma decisão. Por enquanto, estamos baseando nossa solução nesta convenção antiga, que, de toda forma, é mais consistente do que o campo **Ativo.**

**Comment by andreagudo** [comment]
Teste de inclusão de novo mandato para o parlamentar em uma mesma legislatura
![captura de tela de 2017-08-16 08 04 45](https://user-images.githubusercontent.com/19169882/29360671-702ffc7a-825a-11e7-8e39-aa56467acb04.png)

**Comment by andreagudo** [comment]
Ao incluir novo mandato para o parlamentar, mesmo numa mesma legislatura, várias informações já existentes devem ser novamente registradas: Coligação, Votos Recebidos, Expedição do Diploma e Vereador Titular.

**Comment by eduardocalil** [comment]
@andreagudo Esse último problema relatado deve estar em outra issue.
