### ISSUE TITLE
Erro ao incorporar proposição

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1341]
Em protocolo/receber proposição

![image](https://user-images.githubusercontent.com/13314947/28933343-2006af48-7853-11e7-8d64-47c1a351a91a.png)

ao clicar em incorporar

![image](https://user-images.githubusercontent.com/13314947/28933473-8b3e1c88-7853-11e7-9575-7aa1085bf438.png)

Ocorre o erro

![image](https://user-images.githubusercontent.com/13314947/28933298-f7ed999a-7852-11e7-9d9e-4e70075dd8f9.png)

**Comment by edwardoliveira** [comment]
![image](https://user-images.githubusercontent.com/9326037/28934547-bf058174-7857-11e7-8fb4-bde941ae805f.png)

Mais uma vez é um erro do Whoosh. Reindexando resolve some com o erro, mas tem que ver porque ele está gerando esse tipo de erro aí. Já é a segunda vez que isso acontece (a primeira foi com a issue https://github.com/interlegis/sapl/issues/1325 )
