### ISSUE TITLE
Anular protocolo com Documentos Vinculados.

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1342]
Não sei se faz sentido, mas está sendo possível anular protocolo com documentos vinculados

![image](https://user-images.githubusercontent.com/13314947/28933875-2d194d56-7855-11e7-8757-7f73c5c7b6d6.png)

Me parece que o correto seria o usuário se obrigado a excluir o documento vinculado e depois poder cancelar o protocolo

**Comment by edwardoliveira** [comment]
A checagem é tranquila de fazer, mas não posso opinar sobre isso pq não conheço a realidade de uso diário do sapl. /cc @LeandroRoberto @andreagudo ?

**Comment by andreagudo** [comment]
Parece não fazer sentido. Há muito poucas situações em que um protocolo é anulado. Há poucos dias geramos dois protocolos, um deles por engano, para um mesmo documento que entrou na Casa. Um deles foi anulado. Mas, se chegou a gerar um documento administrativo, poderia o protocolo ser anulado? Penso que não.
