### ISSUE TITLE
Vincular a matéria legislativa existente

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1344]
Penso que deveria ser alterado o termo vincular pelo termo anexar, pois de fato é o que acontece

no momento da criação da proposição
![image](https://user-images.githubusercontent.com/13314947/28938109-69ff8268-7863-11e7-9590-4df34b659378.png)

no momento do recebimento
![image](https://user-images.githubusercontent.com/13314947/28938259-df235f2e-7863-11e7-8133-7c82d054eeb9.png)

**Comment by edwardoliveira** [comment]
Se uma matéria é emenda da outra existe uma relação matéria principal -> matéria secundária. Aí o termo ANEXAR se aplica, mas e no caso de uma matéria que revoga outra? Não existe necessariamente uma relação de "pai e filho", pois ambas tem o mesmo status, e somente uma suplanta a outra. Assim sendo, me parece que o termo VINCULAR é mais genérico, pois engloba tanto anexos quanto relações no mesmo nível.

**Comment by DtiLegBG** [comment]
Acho que você tem toda razão.  Porém quando referenciada uma matéria existente a relação que é criada é de anexo.  Passando a matéria vinculada ser um anexo da matéria vinculante ou anexadora. Ou não estou sabendo usar isso

**Comment by edwardoliveira** [comment]
Entendi. Mas prefiro deixar como está.

**Comment by andreagudo** [comment]
Apensar ou anexar proposição é um ato formal do processo legislativo (p. ex., um PL pode ser anexado/apensado a outro). Há uma parte específica nas matérias onde se faz isso (figura abaixo). É diferente o que sistema faz ao acrescentar uma matéria legislativa nova, como uma emenda, que deve ter, necessariamente, um vínculo com outra proposição a qual se refere. Então, uma matéria pode nascer com tal vínculo, mas nunca anexada ou apensada. 
![captura de tela de 2017-08-03 17 12 48](https://user-images.githubusercontent.com/19169882/28941705-33ef9c38-786f-11e7-97bc-75addf0b099c.png)
