### ISSUE TITLE
Não aparece todos os autores 

### ISSUE THREAD

**Issue by fabiobelo** [interlegis/sapl#1347]
Ao adicionar autoria e selecionar parlamentares - aparecem apenas 10, sendo que estão cadastrados 23 e estão todos ativos.
![ss](https://user-images.githubusercontent.com/5943692/28972794-62cff32a-7907-11e7-89f8-f5d50eef5a95.png)

**Comment by eduardocalil** [comment]
Acredito que este problema será resolvido assim que pull request #1349 for mergeada.

**Comment by edwardoliveira** [comment]
Acabei de fazer o merge desse PR. Poderia testar?

**Comment by DtiLegBG** [comment]
Para mim resolvido !

**Comment by fabiobelo** [comment]
Atualizei, porém, agora ao escolher o tipo como parlamentar não mostra nenhum resultado.

**Comment by marciomazza** [comment]
@LeandroRoberto Talvez tenha relação com #1328

**Comment by LeandroRoberto** [comment]
@fabiobelo, foi refatorado ontem, testei novamente nessa manhã...  pode testar por favor!?
