### ISSUE TITLE
Resultado de pesquisa de matérias: votação em dois turnos

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1352]
O resultado da pesquisa de matérias apresenta "Data da última votação". No caso de dois turnos, aparecerá somente a última. Seria interessante que fossem mostradas as datas das duas votações.
![captura de tela de 2017-08-07 14 15 53](https://user-images.githubusercontent.com/19169882/29037732-4bd6a1b6-7b7b-11e7-96d2-46feab47ea7f.png)

**Comment by edwardoliveira** [comment]
Se for mostrada as datas das duas votações não seria "data da **última** votação", certo?

**Comment by andreagudo** [comment]
Isso. "Votado em", ou algo parecido, em cada votação, resolveria.

**Comment by andreagudo** [comment]
Resolvido.
