### ISSUE TITLE
Matéria Legislativa - Adicionar várias autorias

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1353]
Ao clicar no botão para incluir várias autorias na matéria legislativa
![image](https://user-images.githubusercontent.com/13314947/29037695-13ab2cc6-7b7b-11e7-95db-8b341ab3cbd7.png)

São exibidos todos os autores do sistema para seleção
![image](https://user-images.githubusercontent.com/13314947/29037707-28e74566-7b7b-11e7-83f1-b996456d402b.png)

Seria interessante seguir a ideia de exibir somente os ativos

**Comment by marciomazza** [comment]
Tem relação com a o trabalho do leandro em #1328.

**Comment by LeandroRoberto** [comment]
Resolvido por #1328
