### ISSUE TITLE
Protocolo, protocolar matéria - Autoria

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1354]
No protocolo de matéria, as autorias são mostradas todas em um único box, seria interessante utilizar da mesma forma que na autoria de matéria, ou seja, filtrando por tipo

![image](https://user-images.githubusercontent.com/13314947/29037901-f766675a-7b7b-11e7-82bd-2c582f0cece1.png)

**Comment by LeandroRoberto** [comment]
@edwardoliveira, a solução dada em AutoriaCrud com o javascript de autoria_form.html resolve bem essa questão.

**Comment by edwardoliveira** [comment]
Massa, vou adaptá-la para essa situação. :+1:

**Comment by LeandroRoberto** [comment]
Resolvido por #1328
