### ISSUE TITLE
Edição na altura da foto (thumbnail) na listagem dos parlamentares 

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#1355]
A fim de manter a proporção da altura x largura da foto (thumbnail) na listagem dos parlamentares no SAPL 3.1, sugiro a alteração de 106 x 109 px para 106 x 141 px. Acredito que desta forma, a foto não ficaria com o pequeno achatamento hoje existente.

grato

Adal

**Comment by edwardoliveira** [comment]
@54adal Essa alteração terá efeito na próxima release do sistema que será feita amanhã ou __no mais tardar__ na segunda. Se na semana que vem não ficar a contento ou vc achar melhor alterar então reabrimos a issue, OK?

**Comment by DtiLegBG** [comment]
Para as imagens do parlamentares na mesa, está ok
http://sapl3beta.camarabento.rs.gov.br/mesa-diretora/

Porém para as imagens nos parlamentares, não alterou
http://sapl3beta.camarabento.rs.gov.br/parlamentar/

**Comment by edwardoliveira** [comment]
@DtiLegBG Tô achando que precisaria reiniciar o servidor aí para não pegar do cache. :thinking: Porque apesar a altura não está atualizando.
