### ISSUE TITLE
Implementar visão reduzida de parlamentares.

### ISSUE THREAD

**Issue by ramiroluz** [interlegis/sapl#1357]
Existia na versão 2.5 parâmetros de url que permitiam páginas do SAPL fossem embutidas no portal modelo. Por exemplo:

http://sapl.pirai.rj.leg.br/consultas/parlamentar/parlamentar_mostrar_proc?cod_parlamentar=11&iframe=1

Seria interessante implementar uma maneira de realizar o mesmo no sapl3. Algo que permita embutir informações do sapl no portal modelo.

**Comment by eliseuegewarth** [comment]
Relacionada à issue #127
