### ISSUE TITLE
Reversão: issues 680 e 681

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1358]
Ao adicionar matérias na Ordem do Dia e nas Matérias do Expediente, as ementas não aparecem. Parece ser uma reversão na issues #680 e #681 .

**Comment by edwardoliveira** [comment]
@andreagudo Poderia me passar um ou mais exemplos de sessão plenárias cujas ementas não estejam aparecendo, por favor?

**Comment by andreagudo** [comment]
http://sapl31agudo.interlegis.leg.br/sessao/430/expedientemateria

Além dessa, provavelmente as sessões abaixo, onde estava testando algo com a Indicação 19/2017:
http://sapl31agudo.interlegis.leg.br/sessao/430/ordemdia
http://sapl31agudo.interlegis.leg.br/sessao/429/ordemdia
Ver #1368 e #1385

**Comment by edwardoliveira** [comment]
Testei com esses exemplos e funcionou agora.

**Comment by andreagudo** [comment]
Resolvida.

**Comment by andreagudo** [comment]
Tive que reabrir.
http://sapl31agudo.interlegis.leg.br/sessao/610/expedientemateria
Estranhamente, funciona nas sessões abaixo
http://sapl31agudo.interlegis.leg.br/sessao/611/expedientemateria
http://sapl31agudo.interlegis.leg.br/sessao/611/ordemdia
