### ISSUE TITLE
Algumas sugestões para o SAPL

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#1363]
Verificar a possibilidade de:

. Mostrar a foto dos membros da mesa diretora do mesmo tamanho da foto dos parlamentares;
. Deixar a Sessão Legislativa atual como default quando entrar na tela da Mesa Diretora, da mesma forma como é apresentada a Legislatura (atual);
. Inserir a tabela de partidos do TSE no sistema;
. Inserir a tabela dos cargos da mesa no sistema (Presidente, Vice-Presidente, Primeiro-Secretário e Segundo-Secretário).
grato
Adal

**Comment by marciomazza** [comment]
TODO: Criar uma issue para cada uma dessas ideias.

**Comment by 54adal** [comment]
ok!

2017-08-08 14:23 GMT-03:00 Marcio Mazza <notifications@github.com>:

**Comment by edwardoliveira** [comment]
Issues individuais foram abertas para essas sugestões.
