### ISSUE TITLE
Matérias da Ordem do Dia: erro ao acessar na sessão de 01/07/2017

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1368]
![captura de tela de 2017-08-08 14 47 25](https://user-images.githubusercontent.com/19169882/29086361-b952db6a-7c48-11e7-8e5f-6aa053732876.png)

**Comment by edwardoliveira** [comment]
Pra essa Sessão Plenária foram encontrados os seguintes registros:

```
Ordem: 1 - 14ª Sessão Ordinária da 1ª Sessão Legislativa da 15ª Legislatura - Votação: Aprovado por unanimidade - Matéria: Projeto de Lei nº 27 de 2017
Ordem: 1 - 14ª Sessão Ordinária da 1ª Sessão Legislativa da 15ª Legislatura - Votação: Aprovado por unanimidade - Matéria: Projeto de Lei nº 27 de 2017
Ordem: 2 - 14ª Sessão Ordinária da 1ª Sessão Legislativa da 15ª Legislatura - Votação: Aprovado por maioria - Matéria: Projeto de Lei nº 24 de 2017
```
Com os respectivos ids: 644, 643, 642. Os dois primeiros são os registros duplicados que estão gerando o erro. Pela proximidade de IDs eu diria que são erros de migração. Mas não tem como afirmar com certeza.

Por conta disso, eu acabei de adicionar dois campos de data_hora para sabermos quando os registros foram criados e modificados. Faremos uma nova migração hoje e daí observamos o comportamento, ok?

**Comment by andreagudo** [comment]
Está ocorrendo o mesmo com as sessões migradas de 15/05/2017 (10º ordinária) e 22/05/2017 (5ª extra e 11ª ordinária) e fictícias de 01/06/2017 (13ª ordinária), 07/06/2017 (6ª extra) e 07/07/2017 (15ª ordinária).

**Comment by edwardoliveira** [comment]
Corrigo para a sessões. Não tenho como testar as fictícias porque fizemos uma nova migração e elas foram apagadas. Poderia criar de novo para vermos se conseguimos reproduzir o erro de novo?

**Comment by andreagudo** [comment]
Não consegui reproduzir o erro.

**Comment by edwardoliveira** [comment]
OK, assim que acontecer de novo abra um novo ticket pra que possamos verificar o mais rápido possível. Adicionei campos que gravam a data de criação e alteração do registro, assim teremos como saber se foi um erro de tela ou de migração.
