### ISSUE TITLE
Remover criação de User das telas de vinculação de Autor e Votante

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#1370]
Vide:
https://github.com/interlegis/sapl/issues/923#issuecomment-286747012

**Comment by LeandroRoberto** [comment]
comentários na imagem:
![image](https://user-images.githubusercontent.com/9630623/29088950-32519fa8-7c51-11e7-9a6a-66bfc923843c.png)

**Comment by eliseuegewarth** [comment]
@marciomazza qual é o path dessa tela de adicionar "Votante" citada no título da issue? Para a tela de criação de autores eu já fiz as alterações necessárias.
