### ISSUE TITLE
Tipo Resultado da Votação

### ISSUE THREAD

**Issue by eduardocalil** [interlegis/sapl#1372]
Cada Câmara possui a liberdade de inserir, com o nome quiser, os `Tipos de Resultados de Votação`. Sendo assim, seus nomes podem ser diferentes em cada Casa.

Portanto, devemos modificar a nossa lógica que faz verificações do tipo:

```
if resultado_votacao == 'Aprovado por maioria'
```

**Comment by edwardoliveira** [comment]
@eduardocalil Eu fiz o merge do PR da @marimendes porque não vi nenhum erro. Mas verifica se o commit está ok pra vc também.

**Comment by marciomazza** [comment]
A gente precisa refletir um pouco quando coisas desse tipo surgirem.

Acho que teria sido mais interessante reduzir as opções: tornar tipo de resultado de votação *hardcoded* : **Aprovado** ou **Rejeitado**.
