### ISSUE TITLE
Incluir períodos de afastamento no Relatório de Presenças dos Parlamentares

### ISSUE THREAD

**Issue by eduardocalil** [interlegis/sapl#1373]
É importante que seja informado também, neste relatório, o número de Sessões em que o Parlamentar estava ativo e em quantas destas ele estava presente, não somente o número total de Sessões que existiram no período inserido na pesquisa. O motivo disso é que podem ter ocorrido Sessões em datas em que o Parlamentar estava inativo e estas não devem ser contabilizadas na medida de sua participação.

**Comment by DtiLegBG** [comment]
Ou seja, deveriam existir períodos para o mandato, além da possibilidade de cadastrar faltas justificadas

**Comment by LeandroRoberto** [comment]
#413

**Comment by LeandroRoberto** [comment]
Não resolver antes de resolver a #413. Já existe um dialogo informal entre eu, @andreagudo e @DtiLegBG. Tratar das nuances da solução de registro de periodo de mandato com estes membros antes da modelagem e implementação.

**Comment by edwardoliveira** [comment]
@LeandroJatai Essa issue ainda é pertinente? A #413 já foi integrada ao projeto.
