### ISSUE TITLE
Pesquisa de matérias: indicações de 2017

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1385]
![captura de tela de 2017-08-10 14 14 21](https://user-images.githubusercontent.com/19169882/29182728-5bca20ae-7dd6-11e7-9125-68c12c2ada86.png)

**Comment by andreagudo** [comment]
Na verdade, o erro ocorre também não definindo o ano.

**Comment by edwardoliveira** [comment]
Esse erro foi culpa minha. Fiz uma alteração para adicionar essas novas colunas, mas a máquina de homologação de Agudo estava com algum problema em alterações de tabelas do banco. Agora fizemos uma nova migração hoje de manhã e o erro foi resolvido.

**Comment by andreagudo** [comment]
Resolvida.
