### ISSUE TITLE
Fotos dos parlamentares 

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#1386]
Como sugestão, 

Aumentar um pouco mais as fotos dos parlamentares, como também as fotos da Mesa Diretora.
Caso não vejam necessidade, que ambas sejam do mesmo tamanho. (foto Mesa diretora x Parlamentares)
grato

**Comment by edwardoliveira** [comment]
Que tamanho vc sugere para as fotos de parlamentares e da mesa diretora?

**Comment by edwardoliveira** [comment]
Relacionada à issue: https://github.com/interlegis/sapl/issues/1355
