### ISSUE TITLE
Inserção da tabela de Partidos políticos do TSE

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#1388]
Sugestão:

Inserir a tabela de partidos do TSE, afim de agilizar o preenchimento dos dados cadastrais do parlamentar.
grato

**Comment by edwardoliveira** [comment]
@LucianoAlmeida e @marciomazza, que influências isso pode ter na migração? Estou pensando na eventualidade disso duplicar registros nessas tabelas... :thinking:

**Comment by edwardoliveira** [comment]
Relacionada a https://github.com/interlegis/sapl/issues/1389

**Comment by eliseuegewarth** [comment]
Segundo o que o @LucianoAlmeida me explicou, a migração faz um DB flush (trunca as tabelas), então os dados introduzidos automaticamente serão excluidos no início da migração.
