### ISSUE TITLE
Tabela de cargos da Mesa Diretora

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#1389]
Sugestão:
Inserir a tabela dos cargos da mesa diretora no sistema (Presidente, Vice-Presidente, Primeiro-Secretário e Segundo-Secretário) deixando a opção de inserção de outros cargos.

Justificativa: Facilitar na formação da Mesa Diretora e evitar que o operador digite errado ou em CAIXA ALTA, mantendo assim um padrão no sistema.

**Comment by edwardoliveira** [comment]
@LucianoAlmeida e @marciomazza, que influências isso pode ter na migração? Estou pensando na eventualidade disso duplicar registros nessas tabelas... :thinking:

**Comment by edwardoliveira** [comment]
https://github.com/interlegis/sapl/issues/1388

**Comment by eliseuegewarth** [comment]
@54adal você tem a lista de Cargos já no padrão? Se possível disponibilize ela para eu terminar essa tarefa.
