### ISSUE TITLE
Sugestão de nomes no Módulo Bancadas

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#1391]
No Módulo Bancadas , sugeriria a troca ou complementação de alguns nomes, como se segue:
. MÓDULO BANCADAS, para um nome mais abrangente. Talvez MÓDULO DE REPRESENTAÇÕES?? ou quem sabe outro!?
. BANCADAS para BANCADA PARTIDÁRIA
. BLOCO para BLOCO PARTIDÁRIO
. FRENTE para FRENTE PARLAMENTAR

**Comment by edwardoliveira** [comment]
@andreagudo @LeandroRoberto @DtiLegBG O que vcs acham? De acordo? Alguma outra sugestão?

**Comment by LeandroRoberto** [comment]
pra contribuir, alguns dados:
http://www2.camara.leg.br/glossario/b.html
http://www2.camara.leg.br/deputados/frentes-e-grupos-parlamentares

![image](https://user-images.githubusercontent.com/9630623/29222404-b6c3b2fa-7e98-11e7-8533-ffdf42575f7d.png)

![image](https://user-images.githubusercontent.com/9630623/29222423-c7144160-7e98-11e7-9d9e-f6c5f4bac1bc.png)

![image](https://user-images.githubusercontent.com/9630623/29222503-16853a2e-7e99-11e7-92ff-5b4e55bbad4b.png)

![image](https://user-images.githubusercontent.com/9630623/29222518-26a30134-7e99-11e7-8d5d-9edfde8cef4b.png)
