### ISSUE TITLE
Retificação da #1391

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#1394]
Havia sugerido a troca do nome de Módulo Bancadas para Módulo Agrupamentos, e depois de conversar com pessoa do legislativo, o mesmo sugeriu Módulo de Representações...
Fica aí mais uma sugestão!!

**Comment by andreagudo** [comment]
Essa retificação poderia ter sido feita na própria issue retificada, clicando no lápis acima da descrição. Evitaria essa nova. Então, 54adal, podes fazer essa mudança e fechar esta issue 1391.

**Comment by 54adal** [comment]
opa, obrigado!! Estou aprendendo ainda a usar esse tal de GitHub...rssss
valeu!

Em 11 de agosto de 2017 09:24, André Brum da Silva <notifications@github.com

**Comment by 54adal** [comment]
Preferi alterar a 1391 pois existem outras sugestões do mesmo módulo lá. Posso apagar esta então?

**Comment by andreagudo** [comment]
Podes fechar.
