### ISSUE TITLE
Coligações - Botão composição da coligação 

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1395]
Em tabelas auxiliares / Modulo Parlamentares / Coligação é exibido o botão composição da coligação, mesmo sem selecionar nenhuma coligação
![image](https://user-images.githubusercontent.com/13314947/29214609-66851b0e-7e7e-11e7-9ed0-b99fb308ae36.png)

então clicando no botão

![image](https://user-images.githubusercontent.com/13314947/29214623-74155be4-7e7e-11e7-93e8-657910d3bed5.png)

**Comment by edwardoliveira** [comment]
@LeandroRoberto Sabe me dizer o que é isso? Tô perdido, rs.

**Comment by eduardocalil** [comment]
@LeandroRoberto O botão de Composição de Coligação sumiu com o seu commit

**Comment by LeandroRoberto** [comment]
sumiu... é um masterdetail... deve aparecer só no detail e no update

**Comment by eduardocalil** [comment]
Tem razão, me enganei.
