### ISSUE TITLE
Migração: Indicação 31/2017 não teve tramitação migrada.

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1396]
Não percebi para outras matérias.

**Comment by edwardoliveira** [comment]
@marciomazza @LucianoAlmeida

**Comment by DtiLegBG** [comment]
O que deve ter acontecido é que a primeira matéria deve ter sido excluída no 2.5, mas como ela tinha um vínculo de autor, o migrado não conseguiu excluir ela definitivamente. Então existem 2 matérias iguais, na segunda onde foram feitas as tramitações e que não foi excluída, migrou certa.

![image](https://user-images.githubusercontent.com/13314947/29224866-73d7fd7a-7ea2-11e7-95a4-d4db28c40161.png)

**Comment by DtiLegBG** [comment]
o mesmo acontece em 
![image](https://user-images.githubusercontent.com/13314947/29224990-0105f83c-7ea3-11e7-8c3e-fb975211cfbc.png)

**Comment by andreagudo** [comment]
Requerimentos 4/2017 e 9/2017 tiveram apenas uma tramitação migrada.

**Comment by marciomazza** [comment]
@andreagudo Pode verificar se o problema persiste?

**Comment by andreagudo** [comment]
Resolvida.
