### ISSUE TITLE
Não gera o pdf do resumo da sessão plenária

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1397]
![captura de tela de 2017-08-11 14 07 24](https://user-images.githubusercontent.com/19169882/29223895-8766c168-7e9e-11e7-82e3-cf2362a31ec8.png)

**Comment by edwardoliveira** [comment]
Esse erro é porque a configuração da casa legislativa foi perdida quando da migração de hoje de manhã. Veremos uma forma de melhorar esse processo e não perder mais dados que são **exclusivos** do 3.1. Até lá vá em Tabelas Auxiliares -> Configurações Gerais -> Casa Legislativa. 

Perdão pelo inconveniente.

**Comment by andreagudo** [comment]
ok.
