### ISSUE TITLE
Fale conosco, no rodapé, não funciona

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1399]
![captura de tela de 2017-08-11 16 42 24](https://user-images.githubusercontent.com/19169882/29229336-2f2d2db4-7eb4-11e7-9f96-bd5b2614b42a.png)

**Comment by edwardoliveira** [comment]
Agora ele leva para o email da Casa, assim como no SAPL 2.5.

**Comment by andreagudo** [comment]
Ao clicar, abre para configurar o cliente de e-mail.
![captura de tela de 2017-08-11 17 13 36](https://user-images.githubusercontent.com/19169882/29230258-8f594070-7eb8-11e7-896f-a05ed7531aa1.png)

**Comment by edwardoliveira** [comment]
Porque o email não está configurado na máquina local do *usuário*. Mas esse tipo de link (`mailto: camara@camaraagudo.rs.gov.br`) é o mesmo que existe no SAPL 2.5. É isso mesmo @LeandroRoberto ?
