### ISSUE TITLE
É possível editar o número das sessões, usando o mesmo número

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1400]
http://sapl31agudo.interlegis.leg.br/sessao/pesquisar-sessao?data_inicio__year=2017&data_inicio__month=&data_inicio__day=&tipo=&salvar=Pesquisar

**Comment by edwardoliveira** [comment]
Como? Desculpa, não entendi.

**Comment by andreagudo** [comment]
![captura de tela de 2017-08-11 17 11 08](https://user-images.githubusercontent.com/19169882/29230164-1f4279b4-7eb8-11e7-8a46-27034328a3d3.png)

**Comment by edwardoliveira** [comment]
@andreagudo Favor testar e reabrir caso o problema persista.

**Comment by andreagudo** [comment]
Resolvida.
