### ISSUE TITLE
Novo campo em TipoResultadoVotacao

### ISSUE THREAD

**Issue by eduardocalil** [interlegis/sapl#1403]
Com o merge da **PR** #1401, será necessário uma forma para que o novo campo da tabela **TipoResultadoVotacao**, **natureza_tipo**, seja preenchido nos dados migrados.

**Comment by andreagudo** [comment]
Parece que está gerando um erro no resumo da sessão
![captura de tela de 2017-08-17 08 17 15](https://user-images.githubusercontent.com/19169882/29409910-bc07d620-8324-11e7-99ec-9500a5efa6a5.png)
