### ISSUE TITLE
Resumo da sessão: manter tamanho padrão das fontes

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1404]
Em Expedientes, o conteúdo de Apreciação de Atas está com tamanho da fonte fora do padrão.
![captura de tela de 2017-08-15 16 32 15](https://user-images.githubusercontent.com/19169882/29332818-c1a671d4-81d7-11e7-9cde-5f067ecd304e.png)

**Comment by edwardoliveira** [comment]
Me passa o número dessa Sessão Plenária, por favor.

**Comment by andreagudo** [comment]
Acontece em todas. Mas abaixo está o link
http://sapl31agudo.interlegis.leg.br/sessao/495/resumo

**Comment by andreagudo** [comment]
Está saindo assim também na aba Expedientes, em Expedientes Diversos, Apreciação de Atas.

**Comment by edwardoliveira** [comment]
Uma das razões é porque o texto rico está sendo utilizado na parte de expedientes, talvez porque foi copiado e colado de um documento Open Office ou Word. Esta parte do sistema preserva as formatações de texto (bold, itálico, etc).

Para evitar isso deve-se remover a formatação especial de texto. Selecione o texto da seção "Apreciação de Atas", por exemplo, e clique na opção Text->Clear Text Formatting. Em seguinda clique em "Salvar". Isso vai retirar a formatação especial das seções.

**Comment by andreagudo** [comment]
Resolvido.
