### ISSUE TITLE
Substituir filiação atual em Resumo da Sessão e Presença 

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1412]
#1180 

http://sapl3beta.camarabento.rs.gov.br/sessao/224/resumo
especialmente Vereador Moisés Scussel Neto / PMDB

no resumo está correto

porém na presença da sessão e da ordem do dia não

http://sapl3beta.camarabento.rs.gov.br/sessao/224/presenca
- Vereador Moisés Scussel Neto / PSDB

**Comment by eduardocalil** [comment]
Isso foi feito ontem. Atualize sua máquina, por favor.

**Comment by DtiLegBG** [comment]
Pois é, fiz a atualização e o erro continua
First, rewinding head to replay your work on top of it...
Fast-forwarded master to 90f29b89b31a01c85f935b41e0ad6e1a7f1d9d7b.

**Comment by eduardocalil** [comment]
Verificarei isso então

**Comment by eduardocalil** [comment]
Verifique se a máquina de Bento já possui este commit cc5b119

**Comment by DtiLegBG** [comment]
sim

git log --oneline -n 5
1ea08c6 Implementa script check_migrations (#1411)
0877f6c Ajusta import triplicado
cc5b119 Bug Fix
90f29b8 Fix #1178 refatora presenca parlamentar (#1398)
f897ddc Fix #1406 (#1407)

**Comment by eduardocalil** [comment]
Realmente, havia um caso que não estava sendo tratado, quando estava como **Usuário Anônimo**. Acredito que esteja resolvido agora.

**Comment by DtiLegBG** [comment]
Resolvido !

**Comment by andreagudo** [comment]
Para Agudo ainda não. Caso da Verª Izabel Lamaison http://sapl31agudo.interlegis.leg.br/sessao/229/resumo e Hasso Bräunig

**Comment by edwardoliveira** [comment]
Veja assim que possível. Faltou atualizar.

**Comment by andreagudo** [comment]
Resolvida.
