### ISSUE TITLE
Audiência Pública

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1413]
Criar um espaço feito "Sessão Plenária" para as audiências públicas.

**Comment by eduardocalil** [comment]
Poderia descrever detalhadamente esta nova funcionalidade?

**Comment by paulot12** [comment]
Para colocar as atas, áudios das audiências públicas e o que foi discutido.


________________________________
De: Eduardo Calil <notifications@github.com>
Enviado: segunda-feira, 21 de agosto de 2017 11:27
Para: interlegis/sapl
Cc: paulot12; Author
Assunto: Re: [interlegis/sapl] Audiência Pública (#1413)


Poderia descrever detalhadamente esta nova funcionalidade?

**Comment by marimendes** [comment]
Seria de grande ajuda se pudessem prospectar aí todos os campos que entrariam nessa versão, com seus respectivos nomes e tipos (char, string, int, boolean, etc).

**Comment by edwardoliveira** [comment]
A primeira iteração dessa tela foi efetivada pelo commit: 44db00165521530d6439bc9e06ceb71eb8088590 (master -> 3.2)
