### ISSUE TITLE
Resultado da votação

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1414]
Esteja disponível para o público cada voto na matéria nominal.

**Comment by eduardocalil** [comment]
Para que possa aparecer, você deve entrar nas **Tabelas Auxiliares**, com algum usuário de perfil **Operador Geral** ou **Administrador**. Em seguida, deve-se ir até **Tipo de Resultado da Votação** e alterar manualmente cada registro, inserindo a **Natureza do Tipo** em cada um deles. Caso o tipo não seja de aprovação e nem de rejeição, deve continuar vazio.

O caminho da **url** com a listagem dos **Tipos de Resultado da Votação** é: _/sistema/sessao-plenaria/tipo-resultado-votacao/_

**Comment by eduardocalil** [comment]
Faça isso e, caso tenha resolvido, favor fechar esta issue.

**Comment by eliseuegewarth** [comment]
@paulot12 caso o problema persista após seguir os passos que o @eduardocalil descreveu acima, reabra a issue.
