### ISSUE TITLE
Erro na inserção de Tipo de Proposição no Módulo Proposições

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#1415]
Ao digitar PROJETO DE LEI COMPLEMENTAR, no campo Descrição no Módulo Proposições/Tipo de Proposição, aparece o  erro abaixo. O sistema alega que o tipo de proposição PROJETO DE LEI ORDINÁRIA (que foi digitado anteriormente) já existe!!. Mas o que foi digitado neste momento foi PROJETO DE LEI COMPLEMENTAR.
grato! 

print do erro!
![image](https://user-images.githubusercontent.com/30807716/29524963-9db4f234-8667-11e7-91f3-f0244e3fb5d1.png)

**Comment by LeandroRoberto** [comment]
faltou informação em seu print... o que foi colocado no campo "Seleção de Tipo"?

**Comment by LeandroRoberto** [comment]
o texto que foi digitado na descrição é irrelevante... é um texto que vai aparecer para o autor de proposições. O que importa é que esse "Tipo de Proposição" que está sendo criado é referente a uma matéria legislativa (isso é amarrado quando quem está fazendo o cadastro selecionou
"Tipo de Materia Legislativa" em "Definição de Tipo"... 
essa seleção em faz o conteúdo da caixa "Seleção de Tipo" mudar para os registros criados referentes ao que foi colocado em "Definição de Tipo"... 
veja que selecionar "Tipo de Materia Legislativa" faz aparecer os itens cadastrados aqui: 
/sistema/materia/tipo/
veja que selecionar "Tipo de Documento" faz aparecer os itens cadastrados aqui: 
/sistema/materia/tipo-documento/

Quando o sistema diz que já existe "Tipo de Proposição" associado a um "Tipo de Matéria Legislativa" criada para ser um "Projeto de Lei", isso não tem nada haver com a descrição colocada... tem haver sim, com um outro "Tipo de Proposição" criado anteriormente e que já está listado em:
/sistema/proposicao/tipo/

**Comment by 54adal** [comment]
Olá Leandro, tudo bem? Demorei um pouco para te responder!  Confesso que ainda estou aprendendo a usar o Github e não acompanhei o desenrolar da minha solicitação.
Então não posso cadastrar o tipo de Proposição com a Descrição "PROJETO DE LEI COMPLEMENTAR" com definição de tipo "TIPO MATÉRIA LEGISLATIVA" e selecionando tipo "PROJETO DE LEI"?? é isso?
O que vc me sugere? Pode ser que eu esteja fazendo confusão com os termos PROPOSIÇÃO x MATÉRIA.
um abraço

**Comment by LeandroRoberto** [comment]
@54adal, flexibilizamos essa possibilidade... em breve estará disponível, 
vc poderá ter dois "tipos de proposição" com o mesmo "tipo de matéria legislativa" selecionado.

**Comment by 54adal** [comment]
Muito obrigado!
