### ISSUE TITLE
MIgração: Tipos de Expediente

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1418]
Foram migrados Tipos de Expediente não existentes, provavelmente apagados no 2.5: Apresentação de proposições e VII - Explicações Pessoais.

**Comment by LucianoAlmeida** [comment]
Este erro, assim como comentado nas issues #1021, #1027 e #1035 não deverá mais aparecer.

**Comment by marciomazza** [comment]
Como @LucianoAlmeida disse, nós mudamos a abordagem de migração em #1376 e esses erros não aparecerão mais. Caso percebam algum problema do tipo por favor reportem.
