### ISSUE TITLE
Adicionar telas que mostram vinculo User<-->Votante e User<-->Autor

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#1419]
Adicionar duas `ListViews` para que o `admin` possa verificar quais usuários estão vinculados a quais autores em uma listagem só. O mesmo para User e Votante.

**Comment by eliseuegewarth** [comment]
@edwardoliveira, as telas:
http://127.0.0.1:8000/admin/parlamentares/votante/
http://127.0.0.1:8000/admin/base/autor/
já contem essas informações. Você quer uma com template customizado ou já é o suficiente?

**Comment by edwardoliveira** [comment]
@eliseuegewarth Sim, bem sacado! Fechando essa issue. Lembre-se de passar isso pro Adalberto para que ele possa incluir numa seção "Administração do SAPL", por favor.
