### ISSUE TITLE
Exibir todos sem paginar

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1423]
Quando os registros das matérias da ordem do dia e do expediente são paginados, acaba inviabilizando a ordenação das matérias arrastando para reposicionar caso tenha que mudar de página

Seria interessante que nesse tipo de tabela tivesse a opção de mostrar todos

http://sapl3beta.camarabento.rs.gov.br/sessao/376/ordemdia

**Comment by eduardocalil** [comment]
A solução que nós encontramos seria não paginarmos essas telas. A paginação é feita para que a renderização das mesmas não demore. Como geralmente tem poucas matérias a serem votadas em uma Sessão, a falta de paginação não teria um grande impacto.

O que acham @LeandroRoberto @andreagudo @DtiLegBG ?

**Comment by DtiLegBG** [comment]
Por mim tudo bem, acho que é uma solução!

**Comment by edwardoliveira** [comment]
+1.

**Comment by DtiLegBG** [comment]
Ainda não esta ok.

**Comment by edwardoliveira** [comment]
Testamos aqui e funcionou. Pode ser que o problema seja na atualização do repo git na máquina aí conforme parece ser com a https://github.com/interlegis/sapl/issues/1424 também.

**Comment by DtiLegBG** [comment]
Funcionou conforme #1424 
Obrigado!
