### ISSUE TITLE
Editar dados Básicos sessão - Erro ao salvar

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1424]
O que consegui identificar foi:
Quando a sessão é a numero 1, ao editar e salvar acontece o seguinte erro

![image](https://user-images.githubusercontent.com/13314947/29614864-3db1a27a-87e2-11e7-89af-7aff6e721a39.png)

**Comment by edwardoliveira** [comment]
Isso não é erro. Foi feito para resolver o bug: https://github.com/interlegis/sapl/issues/1400 , isto é, não permitir a duplicidade de números de sessão para a mesma legislatura E sessão legislativa. Pela mensagem, já existe um número 1 para a 17a. Legislatura e 1a. Sessão Legislativa.

**Comment by DtiLegBG** [comment]
Ok, mas como por exemplo incluir a ata da sessão depois de criada ?

**Comment by DtiLegBG** [comment]
Quando é outro numero que não seja 1 é possível, editando e salvando, sendo a sessão de numero 1 apresenta o erro acima.

**Comment by edwardoliveira** [comment]
OK, vou reabrir essa issue pra **você** submeter um conserto pra esse erro. E vamos conversando a partir daí.

**Comment by andreagudo** [comment]
A issue #1400 trata da criação de uma sessão a partir da edição do número de uma já existente. Uma espécie de "salvar como" que criava várias sessões com o mesmo número. Penso que a presente issue trate da necessidade de conseguir editar dados de uma sessão, desde que não seja o número.

**Comment by edwardoliveira** [comment]
@andreagudo Pois é, foi o que eu entendi também. Qualquer valor pode ser editado da sessão **desde que** não seja pra um número existente em **outra** sessão.

Se o SAPL não está fazendo isso, isto é, dando erro pra qualquer outro campo, ou está permitindo duplicar (ou triplicar, etc) números que não sejam o 1 então tem-se um erro no patch do #1400.

**Comment by edwardoliveira** [comment]
@DtiLegBG @andreagudo Conforme conversa com o Rogério, alterei para o número ser único por legislatura, sessão e tipo. Se não funcionar, favor reabrir a issue.

**Comment by DtiLegBG** [comment]
ainda não está ok

![image](https://user-images.githubusercontent.com/13314947/29662959-738fb1b2-889f-11e7-8da2-f935d209e1d4.png)

**Comment by DtiLegBG** [comment]
@edwardoliveira , falando novamente com o @andreagudo , depois de alguns testes, chegamos a conclusão que o 2.5 não impede nada, nem mesmo números duplicados para o mesmo tipo e sessão legislativa. Ele somente sugere a próxima numeração sequencial por legislatura.

Entendemos por bem no 3.1 fazer o seguinte controle:
Não permitir duplicar o numero por tipo na sessão legislativa. Desta forma atenderia a todos e teria o mínimo controle

**Comment by edwardoliveira** [comment]
Tem algum problema com a atualização da máquina aí porque a mensagem de erro foi modificada no master. Veja aqui: https://github.com/interlegis/sapl/blob/master/sapl/sessao/forms.py#L75-L78

Enquanto na screenshot acima está como __"Número de Sessão Plenária já existente para a Legislatura e Sessão Legislativa informadas. Favor escolher um número distinto."__

**Comment by DtiLegBG** [comment]
Verdade.
Fiz
git fetch origin
git reset --hard origin/master

e funcionou.
Obrigado
