### ISSUE TITLE
Remover Municípios

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#143]
Verificar se tabela de Localidades (Municípios) é a do IBGE e uniformizar com sigi
Vide #123 
Considerar usar https://pypi.python.org/pypi/django-municipios (que usa os códigos do IBGE)

Considerar se deixamos apenas municípios mesmo na tabela (agora tem Estados e acho que Regiões).

@LeandroRoberto comentou que não acha necessário esse cadastro de municípios no SAPL
(https://github.com/interlegis/sapl/issues/123#issuecomment-343898568)

**Comment by DTILegBG** [comment]
na tabela parlamentares_municipio faltam alguns se comparado a tabela do ibge dtb_2015
ftp://geoftp.ibge.gov.br/organizacao_do_territorio/estrutura_territorial/divisao_territorial/2015/dtb_2015.zip

**Comment by marciomazza** [comment]
Faz sentido faltarem alguns. Me parece que é uma versão antiga de uma base do IBGE.

**Comment by marciomazza** [comment]
Estou retirando o label **migração** dessa issue, pois ela não tem a ver com migrar as bases antigas de 2.5 para o 3.1. Se trata de uma ideia de reestruturação a ser feita posteriormente e que podemos discutir com calma.

**Comment by marciomazza** [comment]
Em conversa com @edwardoliveira, vi que ele concorda com @LeandroRoberto: o SAPL não precisa desse cadastro.

Se não houver objeções de mais ninguém vou transformar as referências as municípios em campos de texto simples.

O que é na verdade acho útil pra controle do Interlegis é adicionar um campo com o código do SIGI em CasaLegislativa (opcional) e preenchê-lo nos sistemas hospedados por nós.

**Comment by marciomazza** [comment]
Vou fazer dessa forma, então.
Coloquei de volta o label `migração`, enfim. Percebi que com essa mudança preciso sim adaptar a rotina de migração do 2.5 para o 3.1.
