### ISSUE TITLE
Adicionar matérias ordem do dia e expediente

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1431]
Sumiu o form para adicionar matérias a ordem do dia e ao expediente.
Ao clicar em sessão, ordem do dia, adicionar matéria a ordem do dia, a tela fica como segue
também ocorre com as matérias do expediente

![image](https://user-images.githubusercontent.com/13314947/29773502-2b40d886-8bd4-11e7-9db0-8fd116a36dd7.png)

**Comment by edwardoliveira** [comment]
Olhando isso nesse exato momento. Estamos adicionando alguns testes e por isso deve ter ocorrido um erro meu ou de outra pessoa. Vou identificar o commit e reverter.

Att,
Edward

**Comment by edwardoliveira** [comment]
Acredito que tenha sido resolvido com o commit https://github.com/interlegis/sapl/commit/2808f4fa79276c927e1080839b6f7878c32f9a24

**Comment by DtiLegBG** [comment]
Resolvido ! Obrigado.
