### ISSUE TITLE
Impressos - Adicionar etiqueta

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1436]
Em Bento Gonçalves, no 2.5 usamos a etiqueta gerada pelo seguinte: impresso/ficha/selecionada

O perfil dela é o seguinte:
http://repositorio.interlegis.gov.br/ILSAPL/branches/2.5/skins/sk_sapl/generico/impressos/materia_ficha_selec_proc.dtml

Ela gera a seguinte etiqueta:

![image](https://user-images.githubusercontent.com/13314947/29840116-3932c2d4-8cd7-11e7-8c28-e83f97638f52.png)

Usamos para as capas dos processos
![image](https://user-images.githubusercontent.com/13314947/29840130-4ac973f8-8cd7-11e7-8580-21db934337e6.png)

![image](https://user-images.githubusercontent.com/13314947/29840137-520df490-8cd7-11e7-95de-de0641c1c137.png)

Ela contem os seguintes campos:
O número do Processo
tipo da matéria numero e ano
Data da entrada:
Autor:
Ementa:
Despacho Inicial:

e tem um espaço para anotações 
<strong></strong><br>
<strong>________________NORMA JURÍDICA_________________</strong><br><br>
<strong>_________________________________________________</strong>
   </div>

**Comment by DtiLegBG** [comment]
para pesquisa após clicar no menu os campos são
![image](https://user-images.githubusercontent.com/13314947/29840632-0e3c8996-8cd9-11e7-9e09-ce8b17a31220.png)

posterior tem uma tela de seleção
![image](https://user-images.githubusercontent.com/13314947/29840672-301e44d2-8cd9-11e7-99f5-21d41346b7b4.png)

**Comment by marimendes** [comment]
@DtiLegBG Eu gostaria de saber melhor como funciona essa Norma Jurídica que veio vazia no exemplo que foi passado e também se existe outro dado que pode vir vazio dessa forma.

**Comment by DtiLegBG** [comment]
Então.  Norma jurídica só cria um espaço na etiqueta para anotação manual depois do final da tramitação do projeto, se ele virar lei, faz uma anotação manual nesse espaço. 
Os outros dados da etiqueta são alimentados pelo sistema, podem vir vazios caso não cadastrados na matéria. Mas são todos cadastraveis na matéria
