### ISSUE TITLE
Painel de votação: indicar discussão de matéria

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1439]
Toda votação é precedida de uma discussão. O painel poderia indicar a matéria que estaria em discussão, antes de registrar a votação. Talvez acrescentar um botão "Abrir discussão" que indicaria, no painel, "Matéria em Discussão"; tal botão mudaria para "Encerrar discussão" que, clicado, faria o painel mudar para como está hoje, "Matéria em votação".

**Comment by 54adal** [comment]
Nesta mesma linha do André, e observando algumas sessões plenárias de outras casas, percebi que nem toda a Matéria do Expediente vai à votação. Algumas vezes vai apenas para leitura e/ou discussão. e algumas vezes as casas nem votam no Expediente, fica pra Ordem do Dia. Se eu estiver correto, gostaria de sugerir que no título do campo Tipo de votação, alteraria para Tipo de Votação/Discussão ou Tipo de Votação/Leitura. E  acrescentaria o item Discussão ou Leitura  antes dos itens Simbólica, Nominal e Secreta, evitando desta forma a criação de mais um campo. E ao selecionar o item Discussão ou Leitura, inibir no resultado o botão [Abrir Votação], aparecendo tão somente a opção selecionada. O que acham???
![image](https://user-images.githubusercontent.com/30807716/31687420-ef8ae2b2-b367-11e7-8a83-50ffcfc32df7.png)

**Comment by morale** [comment]
Adal, aqui me parece q o André está sugerindo um STATUS sobre o andamento onde a votação é um desses status.

**Comment by andreagudo** [comment]
Morale e Adal, não propus um status novo, mas uma indicação no painel de que a matéria está em discussão. Acho ótima a sugestão do Adal.
