### ISSUE TITLE
PDF de telas

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#144]
No sapl 2.5 é possível gerar um pdf para qualquer tela.

Devemos preservar essa funcionalidade? A impressão do próprio navegador não é suficiente?

**Comment by edwardoliveira** [comment]
-1 pra essa issue. Não vejo necessidade de imprimir em PDF se tem a impressão de tela. No máximo, podemos disponibilizar uma tela com CSS diferente (tipo o que faz o GMail) quando for imprimir. O que acham @eduardoedson e @LeandroRoberto ?

**Comment by edwardoliveira** [comment]
status: anteriormente bloqueado por #37, verificar viabilidade.

**Comment by edwardoliveira** [comment]
@marciomazza @eduardoedson Enquanto implementava os filtros dos relatórios PDF ontem eu vi que em muitos casos, os botões "PDF" no canto superior direito é que disparam os relatórios. A maioria (todos?) os relatórios foram portados por mim e pelo Eduardo na semana passada. Assim, precisamos decidir se vamos seguir o modelo 2.5 (uma tela de pesquisa + pdf ou criar somente a tela de pesquisa. A verificar...

**Comment by edwardoliveira** [comment]
Pois é. Ainda tenho a mesma opinião de 26 de Janeiro. Acho que podemos fechar esta issue e o Morale e André Brum poderiam nos ajudar a identificar quais botões de disparo os relatórios. **Acho** que não devem faltar muitos, e como os relatórios foram portados, será questão de adicionar um botão com os parâmetros de pesquisa, isto é, não é tão mais complexo. Aconselho a fechar esta issue e tratar os relatórios caso a caso.

**Comment by marciomazza** [comment]
Ok.
