### ISSUE TITLE
Tela de detalhe de norma dentro de pauta da sessão

### ISSUE THREAD

**Issue by eduardoedson** [interlegis/sapl#145]
http://devsapl25.interlegis.leg.br:8080/cm_agu/sapl/consultas/materia/materia_mostrar_proc?cod_materia=1938

http://devsapl25.interlegis.leg.br:8080/cm_agu/sapl/consultas/norma_juridica/norma_juridica_mostrar_proc?cod_norma=3636

**Comment by LeandroRoberto** [comment]
não sei do que se trata!

**Comment by marciomazza** [comment]
@eduardoedson Isso ainda é válido?

**Comment by eduardoedson** [comment]
Não encontrei nada equivalente no 31, acho que não é mais necessário.
