### ISSUE TITLE
Exclusão de Matéria Legislativa não autorizada

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#1453]
Ao tentar excluir uma matéria legislativa criada apenas como teste, o sistema alega que o mesmo não pode ser deletado porque foi referenciado por outro registro, que é o mesma matéria.
Ex: ao tentar excluir o PL 040/2017, o sistema apresenta a mensagem a seguir:
![image](https://user-images.githubusercontent.com/30807716/30060809-42f1f5d0-921b-11e7-8d78-c5ea67730c47.png)

**Comment by DtiLegBG** [comment]
Opa, isso não é um bug pelo que dá para entender, acontece que tem autoria cadastrada para a matéria, então primeiro tem que se excluir a autoria e posterior excluir a matéria

**Comment by eduardocalil** [comment]
Era exatamente isso.
