### ISSUE TITLE
Aparecer o voto no painel

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1455]
Bom dia! Estamos com dificuldade de aparecer o voto ao lado de cada parlamentar no painel. Como resolver?

**Comment by DtiLegBG** [comment]
Nos tipos de resultado  da votaçao, tem que ser informado Aprovado ou Reprovado na natureza do tipo. Então ele mostra o voto.

**Comment by paulot12** [comment]
Não apareceu o voto? Colocamos aprovado ou rejeitado e não apareceu o voto.

**Comment by eduardocalil** [comment]
Acredito que quando a PR #1454 for mergiada o problema será resolvido.

**Comment by edwardoliveira** [comment]
@paulot12 Eu adicionei as alterações do @eduardocalil no código principal do projeto. Poderia atualizar o código do projeto e verificar se o voto aparece agora?

**Comment by edwardoliveira** [comment]
@paulot12 Alguma informação se o bug foi consertado ou não?

**Comment by paulot12** [comment]
Não foi consertado. Ainda dá o bug. Tem como resolver?


________________________________
De: Edward <notifications@github.com>
Enviado: segunda-feira, 11 de setembro de 2017 08:46
Para: interlegis/sapl
Cc: paulot12; Mention
Assunto: Re: [interlegis/sapl] Aparecer o voto no painel (#1455)


@paulot12<https://github.com/paulot12> Alguma informação se o bug foi consertado ou não?

**Comment by edwardoliveira** [comment]
Vamos olhar isso essa semana.

**Comment by edwardoliveira** [comment]
@paulot12 Qual a casa legislativa de vcs? Estamos precisando de acesso para ver as votações e testar pq não está funcionado. Poderia nos fornecer acesso de usuário (com permissão para abrir votação) ao sistema também?

**Comment by edwardoliveira** [comment]
@paulot12 Qual a casa legislativa de vocês? Poderia nos fornecer acesso de usuário que possa ver e abrir/fechar votação para que possamos testar e verificar esse bug? O mais rápido possível. Obrigado!!!

**Comment by eduardocalil** [comment]
Pergunte aos técnicos da sua Câmara qual é o último commit do repositório de vocês.

O comando é: `$ git log --oneline -1`

Nos diga qual é a saída.

**Comment by edwardoliveira** [comment]
@paulot12 Verificando aqui vimos que as votações para a Câmara de Caruaru estão em sua grande maioria como "Simbólica". Este tipo de votação NÃO preserva os votos individuais de cada parlamentar, por isso os votos não aparecem no PAINEL. Ao adicionar uma matéria na ordem dove-se explicitamente selecionar o tipo de votação como 'nominal'.
