### ISSUE TITLE
Erro durante atualização

### ISSUE THREAD

**Issue by fabiobelo** [interlegis/sapl#1466]
Bom dia, amigos!

Ao realizar o comando: **./manage.py migrate** após a cópia da última versão daqui, dá erro. Segue print.

![_bug_install](https://user-images.githubusercontent.com/5943692/30276488-629a972e-96db-11e7-8a00-088a88dd98f7.png)

**Comment by eliseuegewarth** [comment]
@fabiobelo verifique no seu banco de dados essa inconsistência. tem uma duplicação de dados em Autoria. Existem 2 autorias de materia cadastradas da mesma maneira. Procure no seu banco de dados na tabela materia_autoria filtrando pela tuplas que contem autor_id = 15 e materia_id = 206. A duplicação esta ai.

**Comment by fabiobelo** [comment]
Consegui realizar a atualização. Realmente estavam duplicados na tabela materia_autoria. 
Obrigado!
