### ISSUE TITLE
Erro em Autoria Materia 

### ISSUE THREAD

**Issue by fabiobelo** [interlegis/sapl#1470]
Bom dia, amigos! Esta com erro ao adicionar autoria e escolher parlamentares. Não lista os parlamentares.
 
![erro_autoria](https://user-images.githubusercontent.com/5943692/30329260-2dcc6bda-97a8-11e7-829b-c46d73c2be7a.png)

**Comment by eduardocalil** [comment]
Existem dois objetos, **Autor** e **Parlamentar**. Para que o Parlamentar seja listado, ele precisa estar vinculado a um registro na tabela de Autor.

1) Vá até Tabelas Auxliares
2) Clique em Autor e Adicionar Autor
3)  Selecione **Parlamentar** em Tipo Autor
4) Selecione o Parlamentar
5) Insira o nome de usuário do Parlamentar

**Comment by fabiobelo** [comment]
Todos estão os parlamentares estão como autor, eduardocalil. Não lista.

**Comment by eduardocalil** [comment]
Algum dos Parlamentares que são Autores possuem **Mandato** vigente na **Data de Apresentação** da Matéria. Confira isso, por favor.

**Comment by fabiobelo** [comment]
Sim, todos eles!

**Comment by eduardocalil** [comment]
Qual sua Câmara? O SAPL está hospedado aí ou conosco? Caso esteja hospedado aí, você teria como nos enviar um backup do seu Banco de Dados?

**Comment by eduardocalil** [comment]
Confira se a **Data de Apresentação** da Matéria está dentro do intervalo de Mandato de algum Parlamentar.

**Comment by fabiobelo** [comment]
Câmara de Caruaru/PE, estamos utilizando no servidor da casa. Segue o banco de dados.

[sapl_backup_13092017__final.backup.zip](https://github.com/interlegis/sapl/files/1300837/sapl_backup_13092017__final.backup.zip)

**Comment by eduardocalil** [comment]
O problema é o seguinte:

Só são listados os Parlamentares que estavam ativos na **Data de Apresentação** da Matéria. Ou seja, somente aqueles em que o intervalo de seu **Mandato** coincide com a **Data de Apresentação**.

A **Data de Apresentação** deste **Requerimento** é **14/02/2017**.
A **Data de Início do Mandato** dos Parlamentares que supostamente estariam ativos está **07/07/2017**.

Faça a mudança e confira aí. Testei aqui e funcionou perfeitamente ajustando os Mandatos.

**Comment by edwardoliveira** [comment]
@fabiobelo Outro problema com relação aos dados está na issue https://github.com/interlegis/sapl/issues/1455 (ver meu último comentário.
