### ISSUE TITLE
Erro Adicionando Proposição

### ISSUE THREAD

**Issue by fabiobelo** [interlegis/sapl#1473]
Amigos, quando o parlamentar vai adicionar uma proposição agora, em vincular matéria legislativa, esta retornando a última matéria para qualquer parlamentar. 
![sem titulo](https://user-images.githubusercontent.com/5943692/30381189-0ff20ed8-9872-11e7-8c8f-e757be733eec.png)

**Comment by eduardocalil** [comment]
@fabiobelo Você poderia responder a issue #1470, por favor?

**Comment by edwardoliveira** [comment]
Poderia nos fornecer mais detalhes sobre esse bug????

**Comment by fabiobelo** [comment]
Pode fechar a issue, ao atualizar a data de ativo dos parlamentares, voltou ao normal.
