### ISSUE TITLE
Arquivo de Licença

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#148]
Criar e publicar arquivo de licença GPL 2.0 para o projeto.
Incluir cabeçalhos em todos os fontes.

**Comment by edwardoliveira** [comment]
@marciomazza Tá ligado que essa issue é bem mais complicada que aparenta, né? Digamos que a licença para o SAPL seja GPL. Então teremos que varrer *todas* as dependências (django, libs, frameworks como DRF, etc) pra ver se a licença delas é compatível com GPL. Caso contrário, terá que ser uma outra (Apache, MIT, BSD, etc).

**Comment by marciomazza** [comment]
Eu estou um pouco na dúvida acerca dessa necessidade, já que nós não distribuimos as dependências com o código, apenas listamos.

**Comment by edwardoliveira** [comment]
Sim, vc tem razão, mas *acho* que mesmo assim tem que listar as licenças das libs em um arquivo LICENSE.

**Comment by edwardoliveira** [comment]
http://opensource.stackexchange.com/q/1357

http://programmers.stackexchange.com/q/135296/205471

**Comment by eribeiro** [comment]
Pelo visto acima só o fato de linkar as libs pode ou não ser considerado trabalho derivativo. A definição de linking: https://en.m.wikipedia.org/wiki/GPL_linking_exception
