### ISSUE TITLE
Salvar matéria somente depois de informar o autor. 

### ISSUE THREAD

**Issue by matiasvictor** [interlegis/sapl#1481]
Dúvida enviada: É possível alterar o SAPL para não permitir salvar dados de matéria sem que antes o AUTOR tenha sido informado?

**Comment by edwardoliveira** [comment]
Não. Primeiro cria-se a matéria e depois atribui-se a autoria. Uma das razões é que uma matéria pode ter vários autores. Então, incluí-los na hora do cadastro da matéria iria complicar mais a tela. Então a resposta a esta issue é não.
