### ISSUE TITLE
Planejar migração de todos os bancos

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#1486]
Escrever um plano de migração (**muito breve**), com:
* pessoas e papeis: quem vai trabalhar e o que cada um vai fazer
* fases da migração: 
    - por exemplo: migramos 1o 20 casas, depois 50 casas, depois 200, etc
    - o que fazemos em cada fase
* forma de acompanhamento: pelo OSTicket? planilhas? pasta no drive?

## Ideias

- [x] Avisar todas as casas para se prepararem. O contato com todas elas serve para mapear todos os contatos técnicos das casas que ficarão responsáveis pela conferência dos dados.
- [x] Escolher para a 1a fase casas com pessoas dispostas a colaborar na conferência
- [ ] Pode haver resistência de algumas casas. Precisamos de pessoas capazes de conversar bem com elas e convencê-las da vantagem e necessidade de migrar.
...

**Comment by eliseuegewarth** [comment]
Documentação SAPL 2.5 atualizada [(documentação gerada)](https://github.com/interlegis/sapl/wiki/Migra%C3%A7%C3%A3o-sapl-2.5-para-3.1).
