### ISSUE TITLE
ABERTURA DO PAINEL

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1487]
Sugiro abrir o painel só com as presenças registradas no SAPL. Pois, tem reuniões que não há votação.

**Comment by edwardoliveira** [comment]
Vc diz só permitir a abertura do Painel se a lista de presença **não** estiver vazia?

**Comment by paulot12** [comment]
Abrir o painel sem nenhuma matéria para votar. Abrir com com as presenças.

**Comment by edwardoliveira** [comment]
Entendi
