### ISSUE TITLE
Avaliar esforço de migrar do Foundation para o Bootstrap

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#150]
# Motivação #
Temos usado o Zurb Foundation como framework css desde o começo da implementação das interfaces. Na verdade fizemos um breve setup com Bootstrap e o abandonamos logo no início. A brevidade do commit cf834f1 demonstra esse fato.

A motivação principal para a escolha do Foundation foi o fato de ele ser mais "neutro" que o Bootstrap, deixando mais livre o trabalho do designer. Isso, entretanto, significa que precisamos de um designer para chegar a um resultado final adequado. Tínhamos um designer com grande capacidade criativa, e, portanto, essa "neutralidade" parecia uma vantagem.

Agora não temos mais designer e provavelmente não teremos. Temos encontrado dificuldade em encontrar personalizações do Foundation para algumas partes da interface.

A vantagem do Bootstrap é que tanto nós agora quanto futuros clientes terão mais facilidade em encontrar snippets, plugins, personalizações para estender o sistema. Vide exemplos em http://startbootstrap.com/bootstrap-resources

# Tarefa #
Avaliar qual o esforço de converter o código atual para usar o Bootstrap ao invés do Zurb Foundation.

**Comment by marciomazza** [comment]
Começando a análise me deparei com um fato que ocorre em todo o projeto: uma quantidade grande de código duplicado (copiado e colado) nos templates.

Em princípio deveríamos refatorar o código para retirar essas duplicidades para então converter a markup para o Bootstrap.

**Comment by marciomazza** [comment]
Talvez possamos usar algo como isso para manter os block grids:
https://gist.github.com/ChrisTM/8346916

**Comment by marciomazza** [comment]
Identifiquei esses pontos que precisam ser alterados:

- grid
- button's
- blockgrids
- menu (do trabalho do caio)
- pagination
- datepicker (usamos uma extensão do foundation)

Além disso precisamos avaliar quanto do trabalho do caio depende do Foundation e se ficamos ou não com o design que ele fez.

**Comment by marciomazza** [comment]
Tb precisamos ver com @LeandroRoberto quanto de seu trabalho é afetado e de sua disposição em mudar parao Bootstrap.

**Comment by marciomazza** [comment]
Analisando as duplicidades nos templates acredito que elas não aumentam significativamente o trabalho de conversão. Nesse caso não precisamos nos preocupar em removê-las antes da conversão.

**Comment by LeandroRoberto** [comment]
quanto app compilacao. Só as telas de cadastro de notas e vides usam foundation... grids e buttons, datepicker.

**Comment by marciomazza** [comment]
Então, em resumo, o trabalho parece simples, e grande parte dele é troca de texto via expressões regulares.
