### ISSUE TITLE
Ordem Alfabética no painel 

### ISSUE THREAD

**Issue by fabiobelo** [interlegis/sapl#1502]
Amigos, não está em ordem alfabética normal. a vereadora esta fora da ordem. Segue imagem. 

![ordem_al](https://user-images.githubusercontent.com/5943692/30882963-19251e04-a2e1-11e7-8c49-f8fac07e6423.png)

**Comment by eduardocalil** [comment]
A ordem alfabética está correta. O problema é o prefixo **Vereador(a)** que vocês inseriram no nome do Parlamentar.
