### ISSUE TITLE
Colocar digito verificador

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1503]
Sugiro colocar dígito verificador para verificar a autenticidade da proposição. 

Quando for protocolar a proposição, gerar um código para verificar a autenticidade da proposição. 

![1](https://user-images.githubusercontent.com/26234950/31048901-679b0d9e-a5fe-11e7-8b5a-5cdea52c0a32.jpg)

**Comment by eduardocalil** [comment]
Por favor, seja mais claro. Detalhe sua sugestão e, se possível, ilustre-a com **PrintScreen** das telas.

**Comment by paulot12** [comment]
Ao protocolar a proposição e ser recebida no SAPL, automaticamente, ser gerado um código para verificar a autenticidade da proposição. E esse código será exibido na proposição.

**Comment by paulot12** [comment]
Como o print acima

**Comment by eduardocalil** [comment]
#969
