### ISSUE TITLE
Protocolar proposição

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1504]
Quando for protocolar a proposição, exibir o número correspondente para aquela proposição.

**Comment by eduardocalil** [comment]
Por favor, seja mais claro. Detalhe sua sugestão e, se possível, ilustre-a com **PrintScreen** das telas.

**Comment by paulot12** [comment]
![screenshot_2017-10-02-14-18-55](https://user-images.githubusercontent.com/26234950/31098278-6ed742a8-a798-11e7-8fb2-b2be69470075.png)

Ao protocolar a proposição, quando colocar o tipo de proposição, aparecer o número da proposição a ser criada.

**Comment by eduardocalil** [comment]
O que vocês acham? @edwardoliveira @marciomazza @LeandroRoberto @andreagudo @DtiLegBG

**Comment by LeandroRoberto** [comment]
O número existirá... será mostrado nas visualizações... acho criei uma numeração sequencial por parlamentar e, se não me falha a memória, reiniciando anualmente e pode até ser mostrado um max_codigo_... mas um detalhe importante... deve estar ciente que este não é o número da futura matéria visto que esta só receberá número quando aceita no protocolo... numero de proposição é diferente de número de matéria.
