### ISSUE TITLE
Tramitação 

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1505]
Quando tramitar documentos/matérias para departamentos, gerar um aviso ao departamento sobre a tramitação de documento/matéria.

**Comment by morale** [comment]
a versão 2.5 já previa o cadastro de emails para notificação, o q já contemplaria essa demanda.

**Comment by edwardoliveira** [comment]
Inclusive esse cadastro de email foi portado para a versão 3.1 também.
