### ISSUE TITLE
Ordem do Dia/Expediente

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1508]
Sugiro opção de "marcar todas" as proposições e votações.

**Comment by eduardocalil** [comment]
Por favor, seja mais claro. Detalhe sua sugestão e, se possível, ilustre-a com **PrintScreen** das telas.

**Comment by paulot12** [comment]
![screenshot_2017-10-02-14-21-06](https://user-images.githubusercontent.com/26234950/31098169-23b0a2b0-a798-11e7-8a80-14a2370c60d7.png)

Opção para selecionar todas as matérias a serem inclusas no expediente/ordem do dia e também selecionar a votação.
