### ISSUE TITLE
Autor e Tipo de Autor

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#1511]
Para facilitar na lógica da alimentação das tabelas auxiliares, sugiro transferir o item Autor e o Tipo de Autor que estão hoje no módulo Configurações Gerais, para o Módulo Proposições ou para o Módulo Matéria Legislativa.
grato

**Comment by LeandroRoberto** [comment]
@54adal, não concordo! Se vc coloca em Matéria, a ideia de que também serve para Proposição fica confusa... se vc coloca em Proposição, também gerará dúvida se isso serve é uma configuração de Matéria... Autor é uma coisa genérica, que se relaciona com várias partes do sistema: 
com frente, bloco e bancada, que estão no módulo de bancadas;
com parlamentar que está no módulo parlamentar;
com comissão que está no módulo comissões...
atualmente estará sendo usado em Proposições e Matérias, porém, em breve poderá associado a Documentos Administrativos, Documentos Acessórios e/ou outras coisas futuras que venham a surgir nas versões futuras...
No início do projeto Autor e TipoAutor realmente ficavam não só conceitualmente mas fisicamente dentro do módulo Matéria e era simbolicamente lincado (criando duplicidade de locais de acesso) ao módulo proposições, porém, em determinado ponto do projeto, para tornar Autor algo genérico e não atrelado a nenhuma funcionalidade especifica que viesse complicar seu uso genérico, foi separado conceitualmente (retirando duplicidades de acesso e deixando claro que é algo geral em configurações gerais) e fisicamente, saindo fisicamente do módulo materia e indo para o módulo que tecnicamente e fisicamente chamamos de módulo base, ou "configurações gerais"

**Comment by 54adal** [comment]
Obrigado! Estava vendo apenas como autor de proposição ou matéria legislativa, como na versão 2.5. Aqui  ele é muito mais abrangente!
Fechada a questão!
