### ISSUE TITLE
Mensagens de alerta em exclusões de matérias legislativas

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1516]
Criar mensagem de alerta em exclusão de matéria legislativa caso ela seja referida em uma sessão plenária ou anexada a outra matéria, impedindo a exclusão. Informar as sessões em que é referida e anexações existentes, ativas ou passivas ("tem como anexa a matéria x"; "foi anexada à matéria y").

**Comment by eduardocalil** [comment]
Isso já é feito.

![image](https://user-images.githubusercontent.com/14843060/31351567-f2b744c4-ad01-11e7-918f-b3c555981ba6.png)

**Comment by andreagudo** [comment]
Penso que a tela acima não deveria permitir confirmação da exclusão. O ideal seria apenas uma mensagem "continuar" (algo assim) para serem excluídas anexações e referências em sessões.

**Comment by edwardoliveira** [comment]
Essa tela não permite confirmar a exclusão do registro. É que essa tela de apagar é gerada automaticamente pelo SAPL (ao invés de fazer várias telas, fez-se uma e reaproveitou). Assim, mesmo o usuário clicando em "Confirmar" o registro não vai ser apagado porque existem as dependências acusadas em vermelho. O que acha?

**Comment by andreagudo** [comment]
Se não exclui, ótimo. Mas pode restar confusão se o camarada optar por confirmar, pensando que a matéria será excluída.

**Comment by edwardoliveira** [comment]
Entendo. Podemos ver a possibilidade de customizar esse botão pra que nessa tela ele possa ser "continuar" ou mesmo redirecionar pra outra tela. :+1:

**Comment by andreagudo** [comment]
Penso que a solução acima não foi implementada. Vejam a tela abaixo, à qual cheguei por dentro de uma sessão plenária:
![captura de tela de 2018-06-01 11-17-09](https://user-images.githubusercontent.com/19169882/40845592-94e9540a-658d-11e8-9b7d-fb30479df440.png)

**Comment by VictorFabreF** [comment]
Apesar de ser possível chegar nessa tela, ao tentar excluir uma matéria vinculada a uma sessão aparece a mensagem de erro como mostrado na imagem abaixo.

![image](https://user-images.githubusercontent.com/19825887/40846883-3889d456-6591-11e8-9eb9-06a53731fd77.png)

**Comment by andreagudo** [comment]
Por segurança, não tentei confirmar a exclusão na tela acima... rsrs. Sugiro deixar apenas um botão que leve às Matérias do Expediente ou à Ordem do Dia, para evitar confusões.
