### ISSUE TITLE
Organizar colab e wiki do github para remover duplicidades

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#1520]
Entre outras duplicidades que estão começando a surgir, bem como fragmentação da wiki-sapl, ou seja, um pouco no colab e um pouco no github... em específico, seria importante o arquivo docker-compose.yml apresentado em https://colab.interlegis.leg.br/wiki/SAPL31Docker fosse retirado e apenas referênciado ao arquivo versionado e interno ao projeto no github, a saber https://github.com/interlegis/sapl/blob/master/docker-compose.yml

**Comment by edwardoliveira** [comment]
Feito a referência no COLAB. :+1:

**Comment by edwardoliveira** [comment]
@LeandroRoberto Pode fechar essa issue? Mais alguma sugestão de mudança?
