### ISSUE TITLE
Resultado de votos

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1529]
Quando for fechar a votação nominal, aparecer o resultado de quantos votos SIM, NÃO E ABSTENÇÃO. Para colocar o resultado da votação.

**Comment by edwardoliveira** [comment]
Como assim? Poderia ser mais específico? Quando uma votação nominal é fechada aparece um link na listagem de matéria

![image](https://user-images.githubusercontent.com/9326037/31550583-3b6f5e1e-b008-11e7-9a63-3146c887904e.png)

Daí quando se clica no link mais a direita aparece uma tela de detalhes (para usuários logados).

![image](https://user-images.githubusercontent.com/9326037/31550603-4a9c9410-b008-11e7-9e07-cd26cc4116e8.png)

**Comment by paulot12** [comment]
Para colocar o resultado da votação. Se ele foi APROVADO OU REJEITADO, faz-se necessário a totalização de votos SIM, NÃO E ABSTENÇÃO. 

Quando o parlamentar votar automaticamente atualizar a quantidade de votos SIM, NÃO E ABSTENÇÃO.

**Comment by sconetto** [comment]
@eduardocalil @edwardoliveira Eu fiz uma implementação de uma contagem para a totalização dos votos em votações nominais, atualmente está desta forma:

![image](https://user-images.githubusercontent.com/11671985/32052153-13b612d6-ba36-11e7-9068-062d9973c1da.png)

está de acordo com o que foi solicitado? o código está numa branch em separado '1529-resultado-votacao-nominal'

**Comment by edwardoliveira** [comment]
Eu acredito que sim. Mas o @paulot12 pode dizer se é isso que ele estava imaginando.

**Comment by sconetto** [comment]
@paulot12 tem algum parecer sobre essa issue?

**Comment by paulot12** [comment]
ÓTIMO. ISSO MESMO.


________________________________
De: João Pedro Sconetto <notifications@github.com>
Enviado: terça-feira, 31 de outubro de 2017 13:38
Para: interlegis/sapl
Cc: paulot12; Mention
Assunto: Re: [interlegis/sapl] Resultado de votos (#1529)


@paulot12<https://github.com/paulot12> tem algum parecer sobre essa issue?
