### ISSUE TITLE
Erro ao abrir etiqueta de protocolo

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1532]
Na tela abaixo, clicando na etiqueta do protocolo, ocorre o erro a seguir:
![captura de tela de 2017-10-13 14 21 24](https://user-images.githubusercontent.com/19169882/31558133-133fc32e-b022-11e7-8e56-31b6f2001b37.png)
![captura de tela de 2017-10-13 14 19 56](https://user-images.githubusercontent.com/19169882/31558139-17a62e1c-b022-11e7-8d9e-8329fa54a344.png)

**Comment by edwardoliveira** [comment]
@andreagudo Pelo que eu soube houve uma migração de dados já com a rotina de migração do @marciomazza, daí a Casa Legislativa tem que ser reconfigurada.

![image](https://user-images.githubusercontent.com/9326037/31624476-9519444a-b281-11e7-8490-df0ed4e69579.png)

**Comment by andreagudo** [comment]
Resolvida.
