### ISSUE TITLE
Autoincremento quebrado em Presença na Sessão e na Ordem do Dia após migração

### ISSUE THREAD

**Issue by cristian-longhi** [interlegis/sapl#1538]
O id das tabelas **sessao_sessaoplenariapresenca** ou **sessao_presencaordemdia** , autoincremental, está iniciando a partir do 1. Como já há dados da migração, está dando erro. Não permite incluir em nova sessão plenária nem alterar sessões existentes.

![captura de tela de 2017-10-17 14-09-41](https://user-images.githubusercontent.com/22030378/31676070-3abaed7c-b345-11e7-9a3a-4abe354e8b21.png)

**Comment by edwardoliveira** [comment]
@marciomazza 
@LucianoAlmeida

**Comment by edwardoliveira** [comment]
@cristian-longhi Vc rodou os scripts de migração recentes?

**Comment by cristian-longhi** [comment]
@edwardoliveira, não. Quais são esses scripts?
