### ISSUE TITLE
Erro ao incluir documento acessório

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1539]
Ao incluir um documento acessório específico a uma matéria, no sapl 2.5 ocorre normalmente, no 3.1 ocorre o seguinte:
Request URL:  http://sapl31demo.interlegis.leg.br/materia/1970/documentoacessorio/create
Django Version:  1.9.12
Exception Type:  MagicException
Exception Value:  
b'cannot allocate 1160237656 bytes (Cannot allocate memory)application/zip'
Exception Location:  /var/interlegis/.virtualenvs/sapl/lib/python3.4/site-packages/magic.py in errorcheck_null, line 180
Python Executable:  /var/interlegis/.virtualenvs/sapl/bin/python3

o arquivo em questão está em formato zip e tem o tamanho aproximado de 140 mg

**Comment by sconetto** [comment]
@DtiLegBG Estou vendo aqui pelo o seu erro que o documento acessório tem aproximadamente 1160MB (Megabytes) o que dá mais ou menos 1,1 GB (Gigabytes), pode confirmar para mim ? (o 140mg ficou dúbio)

**Comment by DtiLegBG** [comment]
no 2.5 o documento referente é esse:
http://sapl.camarabento.rs.gov.br/sapl_documentos/materia/27122

**Comment by edwardoliveira** [comment]
A @marimendes adicionou a extensão `zip` na lista de formatos permitidos. Caso o erro persista, favor reabrir a issue.
