### ISSUE TITLE
refatorar código para migrar do Bower para Yarn

### ISSUE THREAD

**Issue by eliseuegewarth** [interlegis/sapl#1540]

**Comment by LeandroRoberto** [comment]
Sendo feito em https://github.com/interlegis/sapl/tree/1540-migra-frontend

**Comment by LeandroRoberto** [comment]
1. remove django-bower, django-sass-processor, lib-sass, drunken-parrot-flat-ui e elimina todas as libs javascript e todo código scss/css do projeto sapl.
2. cria projeto de front-end usando [Vue Cli 3](https://cli.vuejs.org/) mantendo com Yarn
3. separa tema oficial para sapl em outro projeto (https://github.com/interlegis/sapl-oficial-theme) com implementação básica onde este tema faz pequenas adequações no bootstrap4 para funcionalidades do sapl.
4. implementa no front-end a leitura de temas através do arquivo .env do projeto sapl
5. implementa front-end com multiplas entradas para módulos Vue diversos e independentes para o sapl.
6. já foi planejado um caminho para incorporação de multiplos temas para adeixar um 'operador-geral' (por exemplo) trocar temas na interface web mas nesta issue isso não será feito.
