### ISSUE TITLE
Lista dos parlamentares na votação nominal

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#1541]
Para evitar enganos na hora de marcar o voto do parlamentar, sugiro aproximar mais o campo **Nome** do campo de **votação**, ou senão colocar uma linha interligando os dois campos, para melhor orientação na hora de selecionar o tipo de voto. Confesso que tive dificuldades em registrar os votos!!
grato

![image](https://user-images.githubusercontent.com/30807716/31721887-4f849c3a-b3f9-11e7-8101-b70617a38708.png)

**Comment by sconetto** [comment]
@54adal essa aproximação ficaria boa?
![image](https://user-images.githubusercontent.com/11671985/31768326-a82ff938-b4ad-11e7-8fc8-d1a0ddcebb06.png)

**Comment by 54adal** [comment]
Como os itens não estão totalmente alinhados, creio que poderiam aproximar um pouco mais, ou senão e para não ter nenhuma dúvida na marcação do voto, sugeriria colocar bordas nos nomes dos parlamentares, da mesma forma como estão nos votos. Se for uma câmara grande ou uma assembleia, essa lista aumentaria bastante, podendo acontecer equívocos nesta marcação.

![image](https://user-images.githubusercontent.com/30807716/31771853-62b32916-b4bc-11e7-976c-8259d3285a66.png)
