### ISSUE TITLE
Erro ao criar matéria a partir de proposição. 

### ISSUE THREAD

**Issue by matiasvictor** [interlegis/sapl#1550]
Boa tarde,

Fizemos o recebimento de uma proposição.
Ao criar a Matéria Legislativa, automaticamente o SAPL colocou o número incremental nela (1564), porém o número dela em nossos registros é outro (1430), então fizemos a edição da Matéria Legislativa de número 1564 para inserirmos o número real (1430). Porém, ao invés de alterar a Matéria Legislativa, o SAPL criou uma nova matéria idêntica, com o novo número informado.

Agora temos uma nova matéria que deverá sem inserida com o número 1564, e o SAPL não permite, devido ao fato de já ter uma utilizando o número.
Tentamos fazer a exclusão da Matéria de Número 1564, mas a mensagem de erro em anexos foi apresentada.

O mesmo problema aconteceu com a matéria de número 1565, que na real deveria ser a 1432.

![saplerro](https://user-images.githubusercontent.com/20505134/31901291-c69e5afe-b7ff-11e7-85e9-2cc88a253bbd.png)

**Comment by edwardoliveira** [comment]
então fizemos a edição da Matéria Legislativa de número 1564 para inserirmos o número real (1430)}

Vocês editaram na tela de `Atividade Legislativa->Materia Legislativa`, pesquisando a matéria de número 1564 de 2017, clicando no registro e daí fazedo a edição e mudando o campo `número` para 1430? E mesmo assim criou registro duplicado?

Se pudesse detalhar os passos do recebimento da proposição até a duplicação do registro para que possamos reproduzir aqui seria de grande ajuda.

**Comment by matiasvictor** [comment]
O gabinete do vereador encaminhou uma proposição via SAPL, e entregou o recibo de envio, com o código do documento, ao departamento legislativo.
O departamento legislativo recebeu a proposição de forma manual e gerou o número 1430 para ela.
Depois, ao receber (incorporar) a mesma proposição pelo SAPL (criando a matéria legislativa), o sistema gerou o número 1564 de forma automática.
Então editamos a matéria legislativa no SAPL, alterando o número para 1430.
Porém, ao salvar, ao invés da matéria 1564 ter sido alterada, uma nova matéria foi criada, idêntica, com o número 1430, ou seja, há duas matérias iguais, apenas com os números diferentes, a 1430 e a 1564.

Agora temos uma nova matéria, cujo número manual é 1564, e não podemos inseri-la no SAPL com este número devido a duplicidade da matéria informada anteriormente.

Devido ao fato de estarmos migrando para o processo digital agora, algumas proposições ainda estão sendo recebidas de forma manual, acarretando este problema.

**Comment by victormorsil** [comment]
Boa tarde edwardoliveira, alguma novidade sobre o assunto?

**Comment by edwardoliveira** [comment]
@victormorsil Ainda não. Precisaríamos simular por aqui o passo-a-passo para entender que bug é esse.

**Comment by LeandroRoberto** [comment]
PR #1607
