### ISSUE TITLE
Colocar botão de iniciar cronômetro no próprio Painel Eletrônio

### ISSUE THREAD

**Issue by eduardocalil** [interlegis/sapl#1551]
Evitaria a dessincronização que ocorre atualmente entre a tela de operação e a de visualização do painel.

**Comment by marimendes** [comment]
Um botão para cada (discurso, aparte e questão de ordem) ou um geral?

**Comment by eduardocalil** [comment]
Um botão para cada. Minha sugestão é transferir toda a funcionalidade de operação para o próprio painel.

**Comment by 54adal** [comment]
1) Nas oficinas de SAPL, algumas câmaras tem questionado o fato de o cronômetro do Discurso parar quando é acionado o botão do Aparte. Eles comentam que o tempo do Aparte deveria correr junto ao tempo do Discurso, ou seja, o tempo do discurso não para!!
2) Liberar os demais botões que hoje, ficam desabilitados quando algum é acionado;
3) Acionar um sinal sonoro automático e diferenciado, para soar à 30s do término de quaisquer dos tempos;
4) Inserir um botão de sinal sonoro,  para ser acionado a qualquer tempo;

**Comment by VictorFabreF** [comment]
A dessincronização já foi resolvida.
