### ISSUE TITLE
Migração do 2.5 para o 3.1

### ISSUE THREAD

**Issue by marcosliell** [interlegis/sapl#1552]
Boa tarde, sou da Câmara de Água Boa - MT, temos o SAPL instalado em um servidor local e liberado para acesso externo (http://sapl.aguaboa.mt.leg.br:8080). É o 2.5 puro, sem nenhuma modificação, rodando no Ubuntu.

Estou querendo realizar a migração para o 3.1, conforme os tutoriais que estão disponíveis aqui.

O que a comunidade aconselha? Já troquei uma ideia com o @LeandroRoberto mas ainda tenho medo que algo possa não funcionar e ficar com meu sistema parado.. até mesmo porque utilizamos o sistema de protocolo para tudo que chega na casa.

Assim, aceito ideias, dicas, sugestões para ver o que é melhor.

Obrigado.

**Comment by edwardoliveira** [comment]
Na minha opinião, a forma mais segura de se fazer isso é arrumar uma máquina virtual ou física e instalar um segundo SAPL, o 3.1, nela. Daí vc segue o procedimento de migração, mas deixando o 2.5 intacto. Daí pra frente é auditar o novo SAPL nessa segunda máquina, para possíveis inconsistências de dados, modo de usar, etc. Somente quando tiver mais certeza de que os dados estão OK e que o sistema está amigável ao seu uso então compensaria fazer uma *outra* migração (desta vez em definitivo, para pegar os dados mais atuais) e daí "desligar" o 2.5.

**Comment by LeandroRoberto** [comment]
Concordo com @edwardoliveira.

**Comment by LucianoAlmeida** [comment]
Acrescentaria ainda a **necessidade de sempre fazer backups** da sua base de dados do SAPL 2.5, pois, durante a migração, os dados que estiverem no banco a ser migrado serão apagados.

**Comment by marcosliell** [comment]
Ok amigos, irei instalar em outra máquina e fazer a migração sem alterar o 2.5 em funcionamento. O que me sugerem de OS? Ubuntu está bom?

**Comment by sconetto** [comment]
@marcosliell acredito que a última versão LTS do Ubuntu está ótimo para sua demanda. O link para download https://www.ubuntu.com/download/desktop.

**Comment by eliseuegewarth** [comment]
@marcosliell, como ressaltado pelo @LucianoAlmeida , é importante que você faça backups do seu sistema antes de qualquer coisa.
O processo de migração está brevemente descrito [(neste link)](https://github.com/interlegis/sapl/wiki/Migra%C3%A7%C3%A3o-sapl-2.5-para-3.1).
Você vai instalar o SAPL diretamente na máquina ou vai usar [docker](https://www.docker.com/what-docker)?

**Comment by marcosliell** [comment]
Pretendo instalar diretamente na Máquina, sou um pouco leigo quanto a isso, então não sei o que é docker... hehehe

Sim, o backup sempre é feito aqui....

**Comment by marciomazza** [comment]
O [Docker](https://www.docker.com/)  é uma forma de compartilhar a própria instalação.
Usando nossa configuração (do Docker) vc teria um esforço muito pequeno de instalação.
Em contrapartida precisaria aprender Docker, que é uma coisa a mais.
Eu diria que se vc pretende instalar outros softwares na infra da sua câmara, é um conhecimento que pode te facilitar muito a vida. Tem configurações Docker prontas pra quase tudo que vc imaginar por aí.

**Comment by marciomazza** [comment]
Pedi a uns colegas dica de material em português de Docker e me indicaram esse livro:
https://leanpub.com/dockerparadesenvolvedores

Certamente também existem tutoriais gratuitos.

**Comment by marciomazza** [comment]
Pedi a uns colegas dica de material em português de Docker e me indicaram esse livro.
Ao que parece é gratuito, com opção de compra de valor livre.
https://leanpub.com/dockerparadesenvolvedores

Certamente também existem tutoriais gratuitos.

**Comment by marciomazza** [comment]
Parece que, por enquanto, a dúvida está sanada. Caso necessário, por favor reabra essa issue.

**Comment by marcosliell** [comment]
Amigos, instalei o Ubuntu em uma nova maquina, e estou instalando todo o ambiente para o SAPL 3.1... Parei na seguinte parte do tutorial:

Instalação e configuração das dependências do projeto
    Acesse o terminal e entre no virtualenv:
    workon sapl
    Instalar dependências python:
    pip install -r /var/interlegis/sapl/requirements/dev-requirements.txt
    Configurar Postgresql:

Logo abaixo fala se eu estiver migrando, a hora é agora, para migrar o banco... então eu vou para o tutorial da migração... e parei aqui:

Instalar Dependências::
          pip3 install -r requirements/migration-requirements.txt
Criar um arquivo sapl/legacy/.env com o seguinte conteúdo (parametros de acesso ao banco 2.5)::

Instalou as dependências da migração normal, mas não sei criar esse arquivo... mas as configurações eu sei fazer... irei puxar o banco via IP, não local host, pois está na mesma rede. Isso da certo neh?

O que faço a partir de agora? Se puderem me ajudar... sou um pouco leigo no linux, mas com paciência vamos conseguir.. Obrigado

**Comment by eliseuegewarth** [comment]
Olá @marcosliell fiz  uma pequena atualização na documentação adicionando o comando para criação do arquivo. [link aqui](https://github.com/interlegis/sapl/wiki/Migra%C3%A7%C3%A3o-sapl-2.5-para-3.1#migra%C3%A7%C3%A3o-de-dados-do-sapl-25)

Você pode utilizar o comando abaixo para criar o arquivo. Ajuste o caminho do arquivo para a pasta onde você clonou o projeto SAPL3.1:
```
touch /caminho_sapl/sapl/sapl/legacy/.env
```

Este arquivo geralmente não é visível, mas você pode abrir o mesmo pelo terminal se quiser edita-lo. Substituir `nano` por um editor de texto de sua preferência(Ex: subl, vi (ou vim, atom):
OBS: nano e vi(ou vim) são editores que vem em qualquer versão ubuntu, além do gedit.
```
nano /caminho_sapl/sapl/sapl/legacy/.env
```

Espero ter ajudado.

**Comment by marcosliell** [comment]
Obrigado... eu descobri ontem com o @LeandroRoberto que preciso finalizar toda a instalação do 3.1 e depois migrar... logo, finalizei ontem toda a instalação, hoje irei começar o processo de migração... e esse arquivo foi criado, agora ficou fácil entender, só editar ele.. Muito Obrigado... qualquer dúvida posto aqui.

**Comment by LeandroRoberto** [comment]
para efeito de registro nessa issue, como te expliquei pelo whatsapp, a mensagem ali quis dizer restauração de uma base de dados que já é do sapl 3.1 (ou seja, dada uma reinstalação do 3.1 por estar mudando de servidor, por exemplo)... e não com relação a migração de 2.5 para 3.1...
retirei essa informação do how-to de instalação para não gerar dupla interpretação...
