### ISSUE TITLE
Votação Nominal: Salvar um registro prévio com os votos dos Parlamentares

### ISSUE THREAD

**Issue by eduardocalil** [interlegis/sapl#1556]
A votação nominal permite duas formas de votar:

1. Votação interativa pelo Parlamentar
2. Marcação do voto do Parlamentar feita manualmente pelo operador

Ao votar, o parlamentar gera um registro em **VotoParlamentar**. Então, quando o operador clica no botão de **Atualizar**, os votos são atualizados na tela de Votação Nominal. Entretanto, os que foram marcados manualmente pelo operador não ficam registrados e voltam ao estado de **Não Votado**.

Minha sugestão é que seja feita uma chamada **ajax** que, ao selecionar o voto de algum Parlamentar, seja criado um registro em **VotoParlamentar**. Sendo assim, ao atualizar a tela as informações inseridas previamente não serão perdidas.

OBS: Lembrar que, caso o voto seja modificado para "Não Votou", deve-se apagar o registro do voto do parlamentar.

**Comment by cristian-longhi** [comment]
Como funcionalidade complementar, a criação desse registro no momento do voto também possibilitaria que o painel sinalizasse de alguma forma que o parlamentar já votou, por exemplo alterando a cor do seu nome.
