### ISSUE TITLE
Criação de registros duplicados ao clicar mais de uma vez em botão de ação

### ISSUE THREAD

**Issue by sconetto** [interlegis/sapl#1557]
Ao clicar em fechar votação (imitando o fluxo de votação de uma máteria nominal), quando efetuado dois clicks ele cria dois registros da votação dando o erro quando a página tenta recuperar a votação informando que foi retornado mais de um registro para o _get_ daquela requisição. Vide imagem:
![image](https://user-images.githubusercontent.com/11671985/32058192-26e86f04-ba48-11e7-9237-1f1ddeeb56a9.png)

**Comment by marciomazza** [comment]
Eu contornei esse problema nos forms do crud em 221e61d8d5b3af5557c7dd5af976be965a4d4ec9.
Veja se isso resolve e, caso não resolva, podemos aplicar a mesma ideia nesse form e onde mais for.

Podemos enumerar os pontos em que o problema acontece?

**Comment by sconetto** [comment]
@marciomazza o problema que eu tive foi ao registrar o resultado de uma votação nominal, quando cliquei em fechar votação duas vezes ele gerou os dois registros de votação, então acredito que seria interessante também bloquear nesse ponto

**Comment by sconetto** [comment]
@marciomazza adicionei ao template (no local onde eu presenciei o erro) um código JS que desativa o botão após o primeiro click no 1a50baa73c425af0861e99aa04a71a5652f79c1c, dessa forma não será enviado dois registros evitando o erro do print que mandei, acho que seria válido verificarmos onde mais essa ação seria necessária, como você disse, enumerar onde  este problema acontece.

**Comment by edwardoliveira** [comment]
@sconetto @marciomazza com tua solução de `disabled` no botão de `Salvar` esta issue pode ser fechada, não?

**Comment by sconetto** [comment]
@edwardoliveira pode sim, essa correção já foi 'mergeada' a branch master pelo PR https://github.com/interlegis/sapl/pull/1564!

**Comment by edwardoliveira** [comment]
Bom! Fechando então.
