### ISSUE TITLE
Turno(tipo votação) resumo sessão plenária - Matérias do expediente e ordem do dia

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1559]
No resumo da Sessão Plenária, nas matérias da ordem do dia, falta exibir o turno
http://sapl.camarabento.rs.gov.br/sessao/388/resumo

![image](https://user-images.githubusercontent.com/13314947/32070846-505d764e-ba6c-11e7-8266-afe465197e19.png)

conforme o 2.5

![image](https://user-images.githubusercontent.com/13314947/32070872-625806ca-ba6c-11e7-8458-80ee3cd4c0f5.png)

**Comment by edwardoliveira** [comment]
Veja se essa modificação solucionou o problema, por favor. Caso contrário reabrimos a issue.

**Comment by DtiLegBG** [comment]
No resumo está ok.
http://sapl.camarabento.rs.gov.br/sessao/388/resumo
Porém no pdf aparecer Turno: mas sem informação
http://sapl.camarabento.rs.gov.br/relatorios/388/sessao-plenaria

Também seria interessante que fosse exibida a informação de turno, estando nos menus matérias da ordem do dia e expediente, não só no resumo.
http://sapl.camarabento.rs.gov.br/sessao/388/ordemdia

Outra coisa que acho que seria interessante, seria abreviar "Numero de Protocolo" para simplesmente "Protocolo" e o mesmo para "Numero de Processo" para "Processo" visualmente ficaria melhor e não comprometeria a informação

![image](https://user-images.githubusercontent.com/13314947/32166033-d3839594-bd4b-11e7-9a62-f0ae0a4ff19f.png)

**Comment by DtiLegBG** [comment]
e no resumo falta a informação de protocolo e processo

**Comment by edwardoliveira** [comment]
@DtiLegBG Como saberemos que uma determinada `Tramitacao` é para inclusão na ordem do dia? Sabendo isso é só fazer um `.filter()`, mas me foge como poderíamos fazer isso sem usar a busca da descrição do `StatusTramitacao`. 

@LeandroRoberto alguma ideia?

/cc @eduardocalil

**Comment by DtiLegBG** [comment]
No 2.5 o que pega o turno é esse cara
http://repositorio.interlegis.gov.br/ILSAPL/trunk/skins/sk_sapl/zsql/tramitacao_turno_obter_zsql.zsql

pelo que da para entender pega o ultimo turno diferente de vazio

sgl_turno <> "" and
          ind_ult_tramitacao=1 and
          ind_excluido=0

**Comment by DtiLegBG** [comment]
Agora pensando dessa forma teria o seguinte problema

No caso de duas sessões. Na primeira a matéria foi em 1 votação
E na segunda sessão foi em segunda votação
como iria ficar a exibição do turno na 1ª sessão

**Comment by edwardoliveira** [comment]
No caso agora exposto, a votação da matéria neste caso sofre duas tramitações? Entra na ordem do dia duas vezes?

Se for o caso (sim para as duas questões), podemos filtrar pelas tramitações <= data da sessão plenária visualizada.

**Comment by DtiLegBG** [comment]
Sim, duas tramitações para duas sessões diferentes, mas pode acontecer de ter duas sessões no mesmo dia.

**Comment by edwardoliveira** [comment]
Mas duas sessões no mesmo dia ainda são duas sessões diferentes, não? 

No caso de duas sessões no mesmo dia pegaria a `Tramitacao` naquele dia (turno = inclusão na ordem do dia) a não ser que existam duas tramitações, uma para cada sessão do dia?

**Comment by DtiLegBG** [comment]
Responde a pergunta anterior
Mas duas sessões no mesmo dia ainda são duas sessões diferentes, não?
Sim, mesmo sendo no mesmo dia são duas sessões diferentes.

No caso de duas sessões no mesmo dia pegaria a Tramitacao naquele dia (turno = inclusão na ordem do dia) a não ser que existam duas tramitações, uma para cada sessão do dia?
sim, para cada sessão é feito uma tramitação, até porque o turno muda e ele é cadastrado na hora da tramitação.

**Comment by edwardoliveira** [comment]
OK, então teria que ver como filtrar `Tramitacao` por data e hora da sessao plenária, e não somente data. Acredito que isso não seja possível no momento. :( Mas vou checar aqui.

**Comment by DtiLegBG** [comment]
De qualquer forma, o filtro por data já seria um inicio.

**Comment by edwardoliveira** [comment]
Sim, vamos fazer esse filtro por data e pegando o último turno não vazio.

**Comment by LeandroRoberto** [comment]
em resposta: a https://github.com/interlegis/sapl/issues/1559#issuecomment-340808811

pra que? não parece condizer com o que vinha sendo discutido acima... 

- é  para uma inclusão automática?
    Isso é complicado mas possível. Possível se "unidades de tramitação"  (UT) forem configuradas com uma informação (um choice tipificando as UTs) que diz que se uma matéria for encaminhada para tal unidade essa unidade imputa inclusão numa sessão plenária...

- é para disponibilizar na lista de inserções múltiplas?
isso é tranquilo, pode ter o mesmo princípio acima, uma buscar todos os documentos que estejam na UT, por exemplo, UT "Plenário"...

**Comment by edwardoliveira** [comment]
>> pra que? não parece condizer com o que vinha sendo discutido acima...

Realmente não condiz. Viajei na questão. Mas o Rogério elucidou o que ele queria.

**Comment by edwardoliveira** [comment]
@DtiLegBG Os commits da semana passada agora permitem recupera o turno mais recente que não é nulo, certo? Teria como verificar isso?

__Ainda falta bolar uma forma de filtrar por datas para uma matéria que é votada em duas sessões diferentes.__

**Comment by edwardoliveira** [comment]
@DtiLegBG Sabe me dizer se aparece o turno correto agora? Pelo menos para as matérias que não tiveram votação em duas sessões plenárias no mesmo dia?

**Comment by DtiLegBG** [comment]
Resolvido ! obrigado.
