### ISSUE TITLE
Não aparecem as autorias dos parlamentares

### ISSUE THREAD

**Issue by alessandrams** [interlegis/sapl#1560]
Ao acessar um parlamentar e clicar em "Matérias", aparece a informação "Esse parlamentar não é autor de materia". Porém o parlamentar foi cadastrado como autor de várias matérias.

**Comment by edwardoliveira** [comment]
Fechando essa issue, conforme discutimos offline: o usuário cadastrou o TipoAutor `Vereador` sem vinculá-lo ao model Parlamentar e daí cadastrou os parlamentares vinculando-os a esse TipoAutor. Assim, os registro no model Autor ficaram sem `content_type` e `object_id`. Daí não era possível recuperar as matérias do parlamentar.
