### ISSUE TITLE
Pauta da Sessão - Detalhes das matérias

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1562]
Ao acessar os detalhes das matérias estando posicionado na pauta das seções o layout ficou estranho, além de ter sumido por exemplo os textos integrais
http://sapl.camarabento.rs.gov.br/sessao/pauta-sessao/2962/ordem/

![image](https://user-images.githubusercontent.com/13314947/32167517-37c5174a-bd50-11e7-9e73-a955fb444f8d.png)

**Comment by edwardoliveira** [comment]
Trata-se de outra tela. Essa é bem antiga, e muito provavelmente foi feita por causa da seção de Tramitações no screenshot acima. Eu inseri umas quebras de linha para consertar um pouco o layout, mas vamos adicionar mais informações para melhorar essa tela.

**Comment by DtiLegBG** [comment]
No sapl 2.5, os detalhes da matéria são exibidos da mesma forma, independente se o usuário vem de sessão plenária ou pauta da sessão. Penso que deveria ser assim no 3.1. Ou seja, quando posicionada em pauta da sessão e clicar em detalhes da matéria, as informações serem iguais aos detalhes da matéria de quando posicionado em sessão plenária.

**Detalhes da matéria sessão plenaria**

![image](https://user-images.githubusercontent.com/13314947/32218137-2074661a-be11-11e7-8f9b-cf3aa4fa3fe3.png)

**Detalhes da matéria pauta**

![image](https://user-images.githubusercontent.com/13314947/32218179-478f6c2c-be11-11e7-831e-a59a8336f70f.png)

**Inclusive a url é a mesma**

**Comment by eduardocalil** [comment]
@DtiLegBG Qual o caminho que você percorreu para chegar nessa url? (http://sapl.camarabento.rs.gov.br/sessao/pauta-sessao/2962/ordem/)

O que acha de remover esta URL e redirecionar o usuário diretamente para a tela de detalhes da matéria?

**Comment by DtiLegBG** [comment]
eu acho ótimo,  como acontece olhando os detalhes da matéria indo pela ordem do dia.

O caminho percorrido para a url acima é:
inicio/pauta da sessão/escolha da sessao/clicar na materia

**Comment by edwardoliveira** [comment]
@DtiLegBG Oi, poderia testar essa mudança? Agora redirecionamos para o detalhe de matéria. Obrigado!

**Comment by DtiLegBG** [comment]
Ficou muito bom, Obrigado !

**Comment by DtiLegBG** [comment]
Problemas, não está indo para os detalhes da matéria correspondente

![image](https://user-images.githubusercontent.com/13314947/32668472-d6fb7af2-c624-11e7-964c-8bca12260778.png)

Exemplo:  clicando nos detalhes desse pedido de informações
![image](https://user-images.githubusercontent.com/13314947/32668434-afa53740-c624-11e7-8174-77faf7db1bf0.png)

è direcionado para essa indicação
![image](https://user-images.githubusercontent.com/13314947/32668455-c54a853c-c624-11e7-910f-e6ab3ce045f7.png)

**Comment by edwardoliveira** [comment]
_Me parece_ que Pedido de Informações é um documento administrativo e não uma matéria legislativa. Assim, quando se clica no link ele redireciona para uma matéria legislativa com a mesma PK do documento administrativo.

Eu não sabia que em Pauta de Sessão entravam documentos administrativos... Poderia confirmar se Pedido de Informações é um doc adm, por favor?

**Comment by DtiLegBG** [comment]
Resolvido, obrigado !!
