### ISSUE TITLE
Pesquisa matérias legislativas

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1563]
Ao preencher alguns dados no form de pesquisa de matéria legislativa e clicar em pesquisar, ocorre o seguinte:
No chrome o botão desabilita e a seta do mouse vira um sinal de proibido
no firefox ocorre o mesmo, porem mostra resultados

**Comment by DtiLegBG** [comment]
Voltei para a atualização anterior a essa e está funcionando
https://github.com/interlegis/sapl/commit/221e61d8d5b3af5557c7dd5af976be965a4d4ec9

**Comment by sconetto** [comment]
Rogério, quando você clica no form de pesquisa ele deixar de mostrar o resultado no Chrome?

**Comment by DtiLegBG** [comment]
não mostra na verdade
