### ISSUE TITLE
Comissões - Cadastro de Reuniões

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1566]
Criar a possibilidade de cadastro de reuniões para cada comissão, com possibilidade de upload de arquivos, cadastro de url de audio/video, cadastro da hora e local da reunião e demais.

**Comment by edwardoliveira** [comment]
@DtiLegBG Nós vamos criar esse CRUD de Reuniões de Comissões para o 3.1. Seria de grande ajuda se vc pudesse prospectar aí todos os campos que entrariam nessa versão, com seus respectivos nomes e tipos (char, string, int, boolean, etc).

**Comment by DtiLegBG** [comment]
Então, vai aqui minha sugestão de campos e posterior aceitação/alteração dos demais coloco os tipos e afins.
Só um pitaco. Esse cadastro de reuniões também será importante ser feito para  frentes. : )

Campos:

Seleção de Período Composição da Comissão
Tipo da reunião
Número
Ano
Data
Hora Início
Hora fim
Local
Observações
URL vídeo
URL áudio
Ata Reunião

Documentos Acessórios
Tipo / Texto Integral

Membros Presentes

Faltas Justificadas
Vereador / justificativa / Texto Integral

@LeandroRoberto @andreagudo

**Comment by morale** [comment]
sugestão para acrescentar: 
- objetivo da reunião:  .... char 
- pauta (relação dos assuntos/matérias  a serem analisadas na reunião)    
- função dos participantes na reunião: (presidente, relator, membro)
- para cada item da pauta: 
  - parecer  ...char  
  - resultado do parecer ( favorável, contrário, outro...)
  - encaminhamento/tramitar para: Presidência, Sessão Plenária, Arquivo, ...

**Comment by marimendes** [comment]
@DtiLegBG Obrigada pelas considerações. Nós já implementamos as duas primeiras (Tipo e Tema).
A terceira consideração é um pouco mais complicada, estamos pensando em como iremos fazer isso sem afetar a tela de cadastro de reunião.
