### ISSUE TITLE
Erro migração timestamp de protocolos

### ISSUE THREAD

**Issue by eliseuegewarth** [interlegis/sapl#1567]
Ao migrar dados de protocolos, a hora é decrescida em 2 ou 3 horas (dependendo do horario de verão).
Provavelmente esta relacionada a issue #1338.

**Comment by edwardoliveira** [comment]
O sistema usa UTC, o SAPL 2.5 deve estar usando BRT.

**Comment by marciomazza** [comment]
@eliseuegewarth  Onde foi que isso aconteceu?

**Comment by eliseuegewarth** [comment]
O problema foi reportado pelo @cristian-longhi . Isso aconteceu quando ele executou uma migração.
@cristian-longhi o timezone da máquina do seu SAPL esta usando TZ=UTC ou BRT?

**Comment by cristian-longhi** [comment]
**USE_TZ = True** no settings.py, conforme o arquivo no GitHub. Alguma outra configuração que tem de ser verificada?

**Comment by eliseuegewarth** [comment]
Na verdade estava falando sobre a configuração da sua máquina. você testou isso localmente certo? Qual a Timezone da máquina onde você testou?

**Comment by cristian-longhi** [comment]
Ok. Está usando UTC.
timezone America/Sao_Paulo.

**Comment by marciomazza** [comment]
Abri a issue #1693 para resolver esse problema de forma geral para todas as _datas com tempo_ ou _tempos_.

**Comment by marciomazza** [comment]
@cristian-longhi Vc conseguiu resolver seu problema particular, ou seja, no fim das contas vc conseguiu migrar suas datas corretamente?

**Comment by cristian-longhi** [comment]
@marciomazza , o que eu fiz foi tratar os dados após a migração com SQL:

- update protocoloadm_protocolo set timestamp = timestamp + interval'3 hours' where extract(timezone_hour FROM timestamp) = -3;
- update protocoloadm_protocolo set timestamp = timestamp + interval'2 hours' where
extract(timezone_hour FROM timestamp) = -2;

Dessa forma resolvemos o horário do protocolo, que entendo ser a informação mais importante do campo, ainda que possa desconsiderar o fuso.
Não efetuamos a migração definitiva, fizemos apenas em testes, de modo que uma solução mais adequada ainda será bem vinda.

**Comment by marciomazza** [comment]
Com o que foi feito em #1693, a rotina de migração agora adiciona a informação de timezone aos campos `DateTimeField` e `TimeField` que não vierem com timezone do mysql.

Como @cristian-longhi já resolveu seu problema (e tb pode usar a rotina nova) estou fechando essa issue.
