### ISSUE TITLE
Erro ao excluir matéria legislativa

### ISSUE THREAD

**Issue by matiasvictor** [interlegis/sapl#1589]
Bom dia,

Ao tentarmos excluir uma Matéria Legislativa, a mensagem em anexos é exibida e a Matéria não é excluída.
O problema está ocorrendo com duas Matérias Legislativas, ambas em anexos.

Onde posso remover a referência mencionada na mensagem de erro para prosseguir com a exclusão da Matéria Legislativa?

Atte.

![saplerromateria1](https://user-images.githubusercontent.com/20505134/32729819-3182dac6-c86c-11e7-972f-a4a1443e64da.png)
![saplerromateria2](https://user-images.githubusercontent.com/20505134/32729821-31a1d9bc-c86c-11e7-81a1-fdd67186d87a.png)

**Comment by edwardoliveira** [comment]
Vc deve remover a Autoria da Matéria Legislativa para poder excluir essas duas matérias. Estamos analisando a opção de apagar Autoria e Proposição quando a matéria legislativa indicada for apagada.

**Comment by edwardoliveira** [comment]
Olá @matiasvictor, ontem fizemos um patch para que quando for apagada uma Matéria Legislativa as estruturas dependentes dela sejam apagadas automaticamente (o clássico CASCADE). Inicialmente, tinhamos restringido o CASCADE em todos os models por questão de consistência de dados, mas conforme discutimos com outros desenvolvedores, iremos abrir exceções como essa de Matéria Legislativa para facilitar a operação do sistema. Este patch (PR) ainda está sob revisão, mas espero poder integrá-lo à base do SAPL ainda esta semana.

Enquanto isso, como escrevi acima, você pode apagar a Autoria das duas matérias supra citadas e daí remover essas matérias. Favor me informar se obteve sucesso nessa segunda abordagem.

**Comment by victormorsil** [comment]
Bom dia edwardoliveira.

Fiz conforme mencionado e não obtive problemas, as matérias foram excluídas.

Há alguma previsão sobre a aplicação deste patch que você mencionou?

**Comment by LeandroRoberto** [comment]
já está disponível na release https://github.com/interlegis/sapl/releases/tag/3.1.35-BETA

**Comment by edwardoliveira** [comment]
err... não sei se ficou nessa versão, mas vou lançar a 36 hoje.

**Comment by edwardoliveira** [comment]
A versão 3.1.36-BETA já se encontra no Docker Hub.

**Comment by victormorsil** [comment]
Ok Edward.
qualquer problema voltarei a comunicar.
Obrigado.
