### ISSUE TITLE
Retirar necessidade de usar collectstatic para em desenvolvimento

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#1592]
Nesse momento é necessário rodar `./manage.py collectstatic` para desenvolvimento. Retirar essa necessidade seguindo as instruções a seguir:
https://docs.djangoproject.com/en/dev/howto/static-files/#serving-static-files-during-development

Ajustar a documentação de desenvolvimento:
https://github.com/interlegis/sapl/blob/master/docs/instalacao31.rst

**Comment by LeandroRoberto** [comment]
aqui https://github.com/interlegis/sapl/blame/master/sapl/urls.py#L73-L81 está de acordo com a orientação da documentação. Desta forma, e a muito tempo, nem mesmo é necessário rodar `collectstatic`, desde que DEBUG=True.

sobre a documentação... https://github.com/interlegis/sapl/commit/9bf85eac02e20bf4158563bb223dc3f85a0b2229
