### ISSUE TITLE
Usabilidade - Despacho inicial para Matérias

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1598]
Na tela dos detalhes da matéria, no menu despacho inicial, normalmente aqui o despacho ocorre para mais de um local, então seria interessante que nessa tela os locais pudessem ser marcados antes de salvar, possibilitando a multi opção.

**Comment by edwardoliveira** [comment]
Vc está sugerindo substituir a tela de adição de despacho inicial por uma tela com checkboxes ou seria a criação de uma nova tela (despacho inicial em lote)?

**Comment by DtiLegBG** [comment]
substituir a tela de edição de despacho por uma tela com checkbox
