### ISSUE TITLE
Adicionar botão "Admin" para acessar painel administrativo no menu "Sistema"

### ISSUE THREAD

**Issue by eliseuegewarth** [interlegis/sapl#1599]
Adicionar um atalho para o Painel administrativo no menu "Sistema". Deixar visível apenas para perfil de usuário "Administrador"

**Comment by edwardoliveira** [comment]
Essa funcionalidade foi adicionada no commit af5fa36b9f3fdb75aae2598870b10200b65639e1

**Comment by edwardoliveira** [comment]
Ops, vacilo meu. Isso será em outro commit.
