### ISSUE TITLE
Migrar sass para less

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#16]

**Comment by marciomazza** [comment]
Sei que andamos conversando sobre isso e que eu mesmo manifestei que talvez fosse interessante migrar para *less*.

O que eu não sabia é que o Zurb Foundation não tem uma versão em *less*, somente em *sass*.
O Zurb Foundation é o framework que usamos como base em no design do sapl 3.1 nesse momento.

Neste caso, acho que enquanto estivermos usando o Foundation, faz mais sentido ficar com o *sass* mesmo, evitando que tenhamos que usar dois preprocessadores de css na mesma aplicação.

Vide https://github.com/zurb/foundation-sites/issues/370#issuecomment-6258330
