### ISSUE TITLE
Normas Jurídicas, cadastro

### ISSUE THREAD

**Issue by ivanlucio10** [interlegis/sapl#1600]
Ao cadastrar normas jurídicas, ao preencher os campos na sequencia, tipo, numero, ano, data, ... quando escolhe a Matéria Legislativa, numero e ano referente a norma, os campos anteriores preenchidos perdem suas informações.

**Comment by edwardoliveira** [comment]
![out-1](https://user-images.githubusercontent.com/9326037/33086325-5c70dec8-cece-11e7-9886-cd92cd7eedfe.gif)

Eu não consegui reproduzir o erro, conforme segue animação acima. Vcs estão utilizando a versão mais recente do SAPL (3.1.34-BETA)?

**Comment by ivanlucio10** [comment]
Edward, resolvido, acontecia na 2.5, agora esta corrigido, Obrigado!
