### ISSUE TITLE
Ajustar migração para escopo publico/privado

### ISSUE THREAD

**Issue by eliseuegewarth** [interlegis/sapl#1601]

**Comment by LucianoAlmeida** [comment]
@eliseuegewarth, está falando da migração de documentos?
Se sim, isso já está sendo feito.

**Comment by eliseuegewarth** [comment]
Se já tiver uma issue relacionada aberta, favor encerrar esta issue.

**Comment by LucianoAlmeida** [comment]
Veja o commit https://github.com/interlegis/sapl/pull/1093/commits/1e897acb959fca43f9a55f0b1932035cde5464df, do PR #1093, que resolveu a issue #1092.
