### ISSUE TITLE
Mesa diretora - Sessão Plenária

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1603]
Em sessão plenária, abertura, mesa, quando não existe mesa cadastrada para a sessão a exibição fica dessa forma para o usuário anônimo

![image](https://user-images.githubusercontent.com/13314947/33122303-fd4e4a26-cf5d-11e7-8e5d-efbafe2f3d72.png)

para as sessão onde as mesas ja foram cadastradas fica dessa forma
![image](https://user-images.githubusercontent.com/13314947/33122363-2493ecc6-cf5e-11e7-8cfb-ecbaae11d6ce.png)

**Comment by edwardoliveira** [comment]
@DtiLegBG Vê se resolveu aí com o último commit no master, _se possível_.

**Comment by DtiLegBG** [comment]
Resolvido! obrigado.
