### ISSUE TITLE
Exclusão Tramitação - status de tramitação

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1604]
Ao incluir uma tramitação à matéria, em que esta tramitação tenha seu indicador de tramitação definido nas tabelas auxiliares como fim, a matéria em questão passa de "em tramitação - sim para não" corretamente. Se essa tramitação por ventura for excluída, não seria o caso de alterar novamente a matéria de "em tramitação - não para sim" ?

**Comment by edwardoliveira** [comment]
Sim. Vc consegue fazer isso?

**Comment by DtiLegBG** [comment]
gostaria, mas penso que esteja acima das minhas condições.  : )

**Comment by edwardoliveira** [comment]
@DtiLegBG Quando possível, favor verificar se agora está revertendo para `em_tramitacao=True` quando a última tramitação apagada é 'F'.

**Comment by DtiLegBG** [comment]
Não funcionou aqui ..

**Comment by edwardoliveira** [comment]
Vc reiniciou o servidor? Essa alteração mexe com Signals do Django e portanto pode ser necessário reiniciar o SAPL. Aqui funcionou: apaguei a última tramitação como 'F' e 'em_tramitacao' foi de 'Não' para 'Sim'.

**Comment by DtiLegBG** [comment]
Sim, reiniciei o servidor e não funcionou.

**Comment by edwardoliveira** [comment]
Me diz uma coisa: é para pegar de turno de `Tramitacao`, certo?

As inclusões e alterações da Tramitação estavam checando o `status da tramitação` ( materia.status.indicador == 'F' )
