### ISSUE TITLE
Tramitação em Lote

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1605]
Ao incluir uma tramitação em lote, em que o status de tramitação tenha sido definido como fim nas tabelas auxiliares, não está alterando "em tramitação" da matéria para "não".
Ao incluir uma tramitação a matéria, não sendo em lote esta funcionando ok

**Comment by edwardoliveira** [comment]
@DtiLegBG Quando puder, verificar se agora a tramitação em lote muda o status de *'em tramitação'* para 'Não' quando o turno é final. Se ainda tiver problema é só reabrir a issue. :)

**Comment by DtiLegBG** [comment]
Identificamos esse problema novamente
@edwardoliveira

**Comment by edwardoliveira** [comment]
Acredito que esteja relacionado a #1637

**Comment by edwardoliveira** [comment]
@DtiLegBG Eu fiz revert de commits prévios, favor testar.

**Comment by DtiLegBG** [comment]
esse mesmo com o revert não funcionou

**Comment by edwardoliveira** [comment]
Tá. Vou olhar isso com calma.

**Comment by edwardoliveira** [comment]
Fiz um novo commit. Veja se solucionou o problema desta vez.

**Comment by DtiLegBG** [comment]
Opa, resolvido. Obrigado !
