### ISSUE TITLE
Matéria Anexada

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1608]
Seria interessante criar um link para acesso direto a matéria quando anexada ao projeto, como acontecia no sapl 2.5

![image](https://user-images.githubusercontent.com/13314947/33268115-1bb485a8-d363-11e7-9a90-e01a6557b140.png)

![image](https://user-images.githubusercontent.com/13314947/33268132-3328d5ea-d363-11e7-85e7-ba5c61ff8c16.png)

Nesta tela de detalhe da matéria anexada, poderia ter o link direto para a matéria
![image](https://user-images.githubusercontent.com/13314947/33268153-4d92b1a8-d363-11e7-8872-3811f93c5b0a.png)

**Comment by marimendes** [comment]
Seria um link para a matéria principal ou para a anexada?

**Comment by DtiLegBG** [comment]
Para a matéria anexada

**Comment by edwardoliveira** [comment]
Os dados da aba `Início` nos detalhes de Matéria Legislativa são gerados automaticamente o que dificulta a inserção dos links lá, infelizmente. 

![image](https://user-images.githubusercontent.com/9326037/33277803-c5012b4e-d380-11e7-9596-9e06d3dfeffb.png)

Algum outro ponto onde poderíamos colocar esses dados?

**Comment by DtiLegBG** [comment]
Quem sabe nessa tela
![image](https://user-images.githubusercontent.com/13314947/33277988-498b3f1c-d381-11e7-9368-da1f64197ede.png)

Se for criada uma coluna nessa tela  chamada "data da desanexação" é a única informação que está nos detalhes e não nessa tela. Então essa tela de detalhes se torna desnecessária. Então o link para a matéria pode ir para o lugar onde hoje está o link para os detalhes.
