### ISSUE TITLE
nas inserções de normas confusão é gerada no registro de numeração.

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#1609]
confira aqui: https://youtu.be/GwVFQYImU1w?t=1434

**Comment by marimendes** [comment]
O certo séria quando não ter número, ao invés de começar com 1, começar vazio?

**Comment by LeandroRoberto** [comment]
apesar de no vídeo eu ter falado que era um erro e ainda sim, na segunda tentativa, que é onde começa o link acima, eu acabei não vendo o que fato ocorre, depois, revendo o vídeo, vi que não é erro mas é um procedimento que confundirá o usuário, com certeza... 
o procedimento trivial seria retirar esse javascript, mas tenho outra sugestão... apenas inverter o layout, trocando o campo ano e número acho que resolve... por que? veja que o sistema tenta trazer o número ligado ao tipo e ao ano, daí, o usuário digita o número e por certo, num lançamento de uma base histórica irá trocar o ano, isso acionará o JS e apagará o que o usuário digitou em número... a inversão de layout acho que resolve...

**Comment by marimendes** [comment]
Fiz a troca na branch https://github.com/interlegis/sapl/tree/1609-numero-norma-juridica. Poderia fazer o teste por favor?

**Comment by LeandroRoberto** [comment]
acho que ficou legal assim...
