### ISSUE TITLE
Usabilidade - Dar informações ao usuário na tela pesquisa textual

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#1612]
explicação no vídeo https://youtu.be/DQ7Ief00z-M no intervalo de 5:00 a 6:30

**Comment by edwardoliveira** [comment]
https://www.youtube.com/watch?v=DQ7Ief00z-M&t=5m0s

**Comment by edwardoliveira** [comment]
Veja se o commit #b94c91a é uma solução a contento. Esqueci de colocar "Fixes #1612", rsrsrs. :see_no_evil:

**Comment by LeandroRoberto** [comment]
resolvido... um dúvida meus testes estão sendo feito no whoosh...
ele só indexa palavras exatas?
não traz palavrar por partes? por exemplo... no vídeo uso duas normas, ambas tem a palavra "providências" na ementa... essas duas normas só são listadas se eu digitar a palavra exata... não me traz nada se por exemplo eu digitar "provid" ou "providência"

**Comment by LeandroRoberto** [comment]
para produção o sorl resolve isso com um índice que considera as variações da língua portuguesa?

**Comment by edwardoliveira** [comment]
Para resolver isso tem que usar um analisador ngram. Basicamente ele indexa a palavra toda e _todas_ as sequências de letras da palavra. Ex: hello, he, h, hel, ... , el, ell, llo, lo, o. Aí da pra procurar por trecho mas o índice aumenta consideravelmente de tamanho pelo que eu sei.

Parece que o Whoosh suporta ngram como o Solr, mas nunca customizei. Vide abaixo:

http://whoosh.readthedocs.io/en/latest/api/analysis.html#whoosh.analysis.NgramAnalyzer

**Comment by edwardoliveira** [comment]
O Solr pode resolver isso de duas formas, pelo que me lembro vagamente: ngrams ou stemming. Steamming é reduzir a palavra ao seu radical. Exemplo: 'trabalho', 'trabalhadores' viram só 'trabalh'

**Comment by LeandroRoberto** [comment]
issue futura... hehehe

**Comment by edwardoliveira** [comment]
kkkkkkk

**Comment by edwardoliveira** [comment]
Outra opção ao ngram é o stemming: http://whoosh.readthedocs.io/en/latest/stemming.html

Ele retira o sufixo das palavras usando heurísticas: `trabalhador` e `trabalho` vira `trabalh`
