### ISSUE TITLE
Resultado de votação no Painel Eletrônico

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#1613]
Solicitação:
No Painel Eletrônico, trocar o texto "Matéria em Votação" para "Matéria Votada" e o resultado "Aprovado/Rejeitado" por "Aprovada/Rejeitada", depois de fechada a votação.

Justificativa:
No caso do resultado da votação, no feminino sempre combinará com o termo "Matéria". Se ficar no masculino, não vai combinar com o tipo de matéria "Emenda", por exemplo.

**Comment by sconetto** [comment]
@54adal a troca do resultado para combinar como você pediu acredito que seja plausível para não causar ambiguidade na apresentação do painel (pois os valores "Aprovado/Rejeitado" vinham desta forma para concordar com o resultado na página de detalhes da votação), mas agora a troca do "Matéria em Votação" não acho interessante pois o resultado vai dar a ideia se já foi finalizada a votação enquanto o "Matéria Votada" indica que a matéria foi votada mesmo antes de se apresentar o resultado. O que acha?
