### ISSUE TITLE
Criar codigo de barras para número do documento (proposição)

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#1615]
Sugestão (Câmara de Joinville SC)
Criar código de barras do número do Documento (proposição) aos moldes do número do protocolo, para facilitar a recepção/incorporação do documento pelo Operador de Protocolo.

Justificativa:
O código é muito grande/complexo para ser digitado pelo operador no campo Código do documento, caso o mesmo não possa copiar/colar, por exemplo.
Fazendo a recepção com um leitor ótico, além de aumentar a velocidade da recepção, inibiria o erro de digitação.

**Comment by JDias** [comment]
Curiosidade: algum motivo para ser código de barras ao invés de qr code?

**Comment by edwardoliveira** [comment]
Queremos trocar os códigos de barra por QR code na próxima versão (3.2).

**Comment by edwardoliveira** [comment]
@54adal Feito.

![image](https://user-images.githubusercontent.com/9326037/34167660-88fdda16-e4c9-11e7-852e-5821ca77b7be.png)

**Comment by 54adal** [comment]
Muito obrigado!!
