### ISSUE TITLE
Sugestões para os cronômetros do painel eletrônico

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#1616]
Algumas sugestões para o uso dos cronômetros e alarmes:

1. Nas oficinas de SAPL, algumas câmaras tem questionado o fato de o cronômetro do Discurso parar quando é acionado o botão do Aparte. Relatam que o tempo do Aparte deveria correr junto ao tempo do Discurso, ou seja, o tempo do discurso não pararia!!
2. Liberar os demais botões, que hoje ficam desabilitados quando algum é acionado;
3. Acionar um sinal sonoro automático e diferenciado, para soar à 30s (por exemplo) do término de quaisquer dos tempos;
4. Inserir um botão de sinal sonoro, para ser acionado a qualquer tempo;
5. Permitir que os tempos dos cronômetros possam ser alterados dinamicamente no próprio painel eletrônico, ou numa outra tela popup.

**Comment by arthurcmm** [comment]
Este aviso sonoro precisa ser opcional. É necessário ter-se opção de setar o aviso ou não, pois atualmente o sinal sonoro é obrigatório, interferindo na fala do vereador durante seu aparte ou questão de ordem. No caso de algum cronometro estar setado em 30 segundos, atualmente entra em looping, não parando mais. Para encerrar o aviso sonoro  (contornar este bug) é necessário atualizar a página.
