### ISSUE TITLE
Usabilidade - ordem nas combos espalhadas pelo sistema

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#1620]
ponderação de Flávio Mattos, feita na lista gitec.
[link para a postagem aqui](https://colab.interlegis.leg.br/archives/thread/gitec/ordem-de-exibicao-dos-resultados-nas-combobox-e-nas-listas#msg-161203)

**Reprodução aqui:**
olá. Gostaria de fazer uma sugestão para a próxima atualização do SAPL 3.1. Tenho percebido que algumas combos, quando clicamos nela para selecionar uma opção, as possibilidades estão em ordem alfabética, o que é certo, mas algumas não estão, o que gera confusão e perda de tempo procurando pela opção certa.

Como exemplo, cito a tela de Pesquisa de Matéria Legislativa. Na combo Tipo de Matéria, os resultados estão dispostos em ordem alfabética. Nas combos Tipo de Autor e Relatoria também. Já na combo Unidade Destino não, o que me obriga a ter que olhar um por um dos resultados para encontrar o necessário.

O mesmo ocorre com algumas listas de resultados. Ao clicar em SISTEMA - TABELAS AUXILIARES - MÓDULO MATÉRIA LEGISLATIVA - TIPO DE MATÉRIA LEGISLATIVA, todos os resultados que estão cadastrados são exibidos em ordem alfabética pela coluna DESCRIÇÃO (o que eu considero correto). Já ao clicar em SISTEMA - TABELAS AUXILIARES - MÓDULO MATÉRIA LEGISLATIVA - TIPOS DE DOCUMENTO, os resultados cadastrados são exibidos fora de ordem, o que me obriga a ter que olhar um por um dos resultados para encontrar o necessário.

É apenas uma dica, mas acredito que iria facilitar muito a vida tanto dos responsáveis pelo gerenciamento do SAPL, quanto dos munícipes que irão utilizar o sistema para fazer pesquisas.

**Comment by edwardoliveira** [comment]
Coloquei o número errado no comentário do commit. O commit é #44ad5f0
