### ISSUE TITLE
Migrar para django 1.11 juntamente com suas dependências

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#1621]
Em outro projeto onde uso o sapl como uma app tive a necessidade de migrar para o Django 1.11, dentre as maiores dificuldades que tive foi com compatibilidade nas funcionalidades que usam django-filter. Em meu projeto elas já foram solucionadas, porém para eu usar as funcionalidades do sapl precisará migrá-lo para Django 1.11... assim que congelar a versão 3.1 me ofereço para fazer as alterações de código necessárias para que o 3.2 esteja em django 1.11

**Comment by edwardoliveira** [comment]
A versão será congelada em Janeiro, assim que lançarmos oficialmente. :+1:

**Comment by LeandroRoberto** [comment]
isso... o django 1.11 é LTS... 1.9 e 1.10 não... 2 não será e só 2.2 voltará a ser LTS... tive um certo trabalho para tornar meu projeto compativel com 1.11 sendo sapl da 1.9 mas deu certo... acho relevante sapl ir para 1.11 que é LTS... e tem features relevantes principalmente quanto a manipulação de querysets...

qdo abrir desenvolvimento da 3.2 to na área pra migrar...

**Comment by edwardoliveira** [comment]
Massa! Vai ser em Janeiro mesmo. :smiley:

**Comment by VictorFabreF** [comment]
@LeandroRoberto, eu estou tentando migrar o django filter para a versão 1.0, mas me deparei com uma dificuldade. O ```MethodFilter``` não existe mais, só que eu não consegui entender como eliminar ele de ```class SaplGenericRelationSearchFilterSet(FilterSet)``` (api/forms linha 18) da maneira que está no tutorial de migração em https://django-filter.readthedocs.io/en/master/guide/migration.html . Você tem alguma dica sobre como proceder?
