### ISSUE TITLE
Usabilidade - funcionalidade da tecla ENTER na tela

### ISSUE THREAD

**Issue by matoscas** [interlegis/sapl#1624]
olá. Estava na tela de Adicionar Autor, selecionei o tipo (parlamentar), digitei duas letras para pesquisar e teclei ENTER. A tecla executou a ação do botão SALVAR, e não do botão FILTRAR. Como ainda não havia sido selecionado nenhum vereador, apareceu mensagem de erro.  No meu entendimento como Analista de Sistemas, a tecla ENTER não deve ser utilizada para executar a ação de botão SALVAR, pois é muito comum usar essa tecla para sair de um campo e ir para o próximo. Sugiro que a funcionalidade desta tecla, quando estiver sendo utilizado um campo de pesquisa, seja para executar a ação da pesquisa em si, e não de salvar o formulário.

**Comment by edwardoliveira** [comment]
Duplicata da issue https://github.com/interlegis/sapl/issues/649
