### ISSUE TITLE
Falha ao Incorporar/Devolver Proposição em "Protocolo -> Receber Proposições"

### ISSUE THREAD

**Issue by claudineidias** [interlegis/sapl#1628]
Em receber proposições após inserir recibo de envio da tela Incorporar/Devolver aparece a seguinte mensagem e não permite prosseguir: "Dados de Confirmação invalidos."

**Comment by victormorsil** [comment]
Bom dia.
Este problema já foi resolvido?
Estamos tendo o mesmo problema e temos o SAPL hospedado junto ao Interlegis, como proceder para a correção deste problema?

**Comment by eliseuegewarth** [comment]
@victormorsil o problema já foi resolvido na release 3.1.41-BETA. Atualize a versão do seu sistema.

**Comment by victormorsil** [comment]
@eliseuegewarth obrigado, solicitarei a atualização do mesmo.
