### ISSUE TITLE
Corrigir tutorial para condizer com a realidade na execução

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#1636]
[No tutorial de instalação do ambiente desenvolvimento](https://github.com/interlegis/sapl/blob/master/docs/instalacao31.rst) é relatado que para criar os usuários deve se ter DEBUG =True, porém, no commit https://github.com/interlegis/sapl/commit/847a28721a7b1b86f49c590e3f7d21e44b54db62 foi modificado e tornado explicito a criação dos usuários trivais... caso a pessoa que esteja seguindo o tutorial queira criar os usuários, como ele deve proceder..

![image](https://user-images.githubusercontent.com/9630623/33900528-dae6f0e8-df55-11e7-859b-6cdd8b91786e.png)

**Comment by LeandroRoberto** [comment]
@marciomazza foi uma alteração sua, tome nota, por favor!

**Comment by edwardoliveira** [comment]
@eliseuegewarth Já fez essa issue?
