### ISSUE TITLE
Matérias Legislativas - Filtro em tramitação

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1637]
Na pesquisa de matérias legislativas, na escolha "em tramitação", o filtro "não" não está funcionando. Ou seja, não estão retornando as matérias que não estão tramitando, o resultado é idêntico a opção sim.

![image](https://user-images.githubusercontent.com/13314947/33939850-d9dccf6c-dff3-11e7-990f-94ab9e19aaea.png)

**Comment by edwardoliveira** [comment]
Oi, saberia me dizer se mais algum outro campo apresenta esse bug?

**Comment by edwardoliveira** [comment]
@DtiLegBG Eu fiz um revert de commits prévios. Favor testar.

**Comment by edwardoliveira** [comment]
@marimendes e @eliseuegewarth e @sconetto, algum de vocês poderia investigar porque o Calil colocou a choice field dos formulários Django filter como 0 e 1 ao invés de False e True? Eu mudei para True/False e parou de funcionar! Qq coisa vemos com ele, se ele ainda lembrar, kkkk.

**Comment by DtiLegBG** [comment]
Agora funcionando !
