### ISSUE TITLE
Ajuda com Migração

### ISSUE THREAD

**Issue by marcosliell** [interlegis/sapl#1638]
Boa Tarde amigos, sou da Câmara de Água Boa - MT, temos o SAPL 2.5 instalado em um servidor Ubuntu local e acesso externo configurado. Tudo funcionando ok.

Conforme o Issue 1552 (https://github.com/interlegis/sapl/issues/1552) que está fechado, lá eu perguntei qual a melhor maneira para começar a migração do SAPL 2.5 para o 3.1.

Semana passada comecei a migração em um novo servidor, nosso 2.5 está intacto, sem sofrer interferências, estou testando em uma nova máquina assim como recomendado.

Tive a ajuda em alguns casos do @LeandroRoberto , muito obrigado.

Segui esses tutoriais:
1º - https://github.com/interlegis/sapl/blob/master/docs/instalacao31.rst
2º - https://github.com/interlegis/sapl/blob/master/docs/deploy.rst

Ao final o SAPL 3.1 rodou na máquina em localhost.

Porém cheguei quando a máquina é reiniciada, preciso fazer o serviço manualmente para rodar o SAPL 3.1. Não encontrei documentação como na versão 2.5 para deixar ele todo funcional.

Peço a ajuda de vocês, pois meu conhecimento é limitado no linux e configurações de servidores, para me orientar quais os próximos passos: 
- Posso testar a migração?
- Se tudo ocorrer bem, depois de alguns testes, posso migrar definitivo?
- O SAPL 3.1 está pronto para uso em uma casa legislativa?
- Quais as novidades que ele tem quanto ao 2.5?
- Como atualizo as modificações realizadas pelos contribuidores? (no 2.5 era subversion)

Enfim, gostaria de respostas para algumas ou todas essas dúvidas, pois gostaríamos de colocar em funcionamento o SAPL 3.1 aqui.

Obrigado mais uma vez. Agradeço a compreensão de todos.

**Comment by edwardoliveira** [comment]
Olá,

**Dúvidas devem ser postadas na lista do GITEC.** Lá vc obterá não somente o feedback do pessoal do Interlegis, mas de membros da comunidade que já estão utilizando o 3.1. Esse canal de issues é para reportar bugs e sugerir novas funcionalidades ao projeto SAPL. Assim sendo, vou responder suas dúvidas aqui, mas fecharei a issue porque ela foge do propósito desse canal.


> Posso testar a migração?

Sim. É até recomendado fazer isso para verificar se os scripts de migração encontram alguma inconsistência de dados na tua base 2.5!

Usualmente existe um punhado de inconsistências na base do 2.5, e o script trata a maioria, mas pode ter alguma inconsistência não tratada, e específica da tua base de dados do 2.5, que devemos incorporar ao script. Mas somente testando com os dados do 2.5 podemos ter certeza. 

> Se tudo ocorrer bem, depois de alguns testes, posso migrar definitivo?

Sim, se vc tiver **absoluta certeza** que após a migração para os dados foram todos corretamente migrados, sem ausências nem inconsistências. Sabemos de pelo menos uma casa legislativa que fez isso. Mas a checagem é um processo demorado e cuidadoso, portanto vai levar algum tempo. Isso porque os scripts de migração estão em constante desenvolvimento e novos bugs podem ser descobertos na migração.

> Quais as novidades que ele tem quanto ao 2.5?

Trata-se de um sistema totalmente novo, reescrito do zero, mas que espelha as funcionalidades do 2.5. Em termos de mudanças a interface gráfica é mais moderna, temos o painel eletrônico para votações, e o editor de leis embutido. A utilização de uma plataforma mais moderna para a reescrita do SAPL permitirá adicionar mais novidades na versão 3.2.

> Como atualizo as modificações realizadas pelos contribuidores?

Agora usamos o git e o github. Nessa página mesmo temos as novas versões do SAPL 3.1 que lançamos com a frequência aproximada de uma vez por semana (as vezes mais no caso de bugs urgentes).
