### ISSUE TITLE
Pesquisa Textual

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1639]
No resultado da pesquisa textual é exibido o texto "O texto desta norma foi removido recentemente. Em breve ela sairá desta listagem."
Só que os textos estão

![image](https://user-images.githubusercontent.com/13314947/33991931-cf5b2b1e-e0b7-11e7-9215-e59057934649.png)

**Comment by edwardoliveira** [comment]
@DtiLegBG Veja se agora está OK. Senão reabrimos a issue.
