### ISSUE TITLE
Discussão - Normas Jurídicas

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1640]
Pensando nas Leis Orçamentárias, acho que seria interessante criar no cadastro de normas jurídicas um campo para cadastro de fim de eficácia. Para na pesquisa ter a opção de filtrar.

Ainda sobre normas, nos tipos de vínculos criados nas tabelas auxiliares, acho interessante criar um campo onde pudesse se definir se aquele vínculo é uma revogação total. Isso iria refletir na pesquisa onde se poderia filtrar por "revogada = sim/não/qualquer"

@LeandroRoberto @edwardoliveira @andreagudo

**Comment by morale** [comment]
Nota: as normas que são revogadas também perdem eficácia, não?

**Comment by LeandroRoberto** [comment]
Nos textos articulados, quando usados, já existe essa funcionalidade dispositivo a dispositivo ou a partir  do dispositivo de vigência que reseta as datas de vigência e eficácia de todos os outros dispositivos.
