### ISSUE TITLE
Considerar a adição de django-simple-history ao SAPL

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#1644]
A lib [django-simple-history](https://django-simple-history.readthedocs.io/en/latest/) oferece uns recursos bem interessantes para gerar e manter tabelas de auditoria em paralelo as tabelas originais com mudanças mínimas nos models. Pode ser uma boa ideia incorporar ao SAPL.

**Comment by marciomazza** [comment]
É importante enumerar o que queremos de uma solução desse tipo. Os principais usos que me ocorrem são:

* log de auditoria: quem fez o que quando
* mecanismo de reversão: desfazer mudanças

Uma coisa muito importante é que a solução não perca dados de histórico com as mudanças de estrutura do banco. Por exemplo: Se removemos um campo de um model o que acontece com o histórico desse campo? E ao excluir um model?

**Comment by edwardoliveira** [comment]
@marciomazza Bem, a solução adota `django-reversion` **perde** dados. :man_shrugging:
