### ISSUE TITLE
Recebimento de proposições

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#1649]
Ao receber uma proposição, se deixar o campo REGIME DE TRAMITAÇÃO em branco e clicar em incorporar,  aparecerá uma tela apenas com o texto Proposição x/xxx e o botão Texto Eletrônico da Proposição.

grato

**Comment by edwardoliveira** [comment]
Adalberto, o @LeandroRoberto gentilmente corrigiu esse bug e fiz um novo release hoje de manhã. Daqui para a tarde deve ter terminado a construção das imagens Docker e daí vou pedir ao Fábio que reinicie todas as instâncias hospedadas aqui. Vc poderá testar a correção então.

Me avise se deu tudo certo ou não.

**Comment by edwardoliveira** [comment]
Vou fechar essa issue. Se por acaso ainda tiver com problema é só me informar o número da issue que reabro.
