### ISSUE TITLE
combo parlamentar em Adicionar Participação em Comissão traz resultados duplicados

### ISSUE THREAD

**Issue by matoscas** [interlegis/sapl#1654]
olá. Percebi que, ao adicionar participantes em uma comissão, ao clicar na combo PARLAMENTAR, aparecem todos os parlamentares cadastrados (deveria aparecer somente os da legislatura correspondente ao Período de Composição selecionado), e ainda aparecem vários parlamentares duplicados, como pode ser visto na imagem abaixo:
![image](https://user-images.githubusercontent.com/34271281/34304677-e0dbd7b0-e721-11e7-85e8-c1cca648b19a.png)

estou fazendo algo errado, ou é um bug?

**Comment by matoscas** [comment]
acabei de constatar que a mesma coisa está acontecendo na combo PARLAMENTAR da tela de Adicionar Unidade de Tramitação.

**Comment by edwardoliveira** [comment]
@matoscas Fizemos um release no começo dessa semana que resolve essa issue. Poderia testar e nos dizer se resolveu para o primeiro caso?

Eu tinha perdido o segundo caso (`Adicionar Unidade de Tramitação`) no meio dos meus emails (por isso é sempre bom abrir issue no github **também**), mas se funcionar para `Adicionar Participação em Composição` então replicamos lá. E lançamos uma nova versão o mais rápido possível!

**Comment by matoscas** [comment]
Edward, acabei de testar aqui, e ainda aparecem todos os parlamentares, e os que tem mais de 1 mandato aparecem duplicados.

**Comment by edwardoliveira** [comment]
Vocês estão usando a versão 3.1.45 (lançada ante ontem)?

Se vocês não estiverem hospedados aqui no Interlegis, teria como me enviar via email ou Telegram um dump da base de dados aí pra fazermos uns testes aqui?

Me gera um dump do banco Postgres do SAPL 3.1 via pgAdmin3 e fazendo um backup do tipo 'custom'. Aí podemos ver porque no caso de vocês ainda não está funcionando...

**Comment by matoscas** [comment]
O nosso SAPL está hospedado aí no Interlegis. É automático a mudança de versão, não é? Testei agora de novo e continua do mesmo jeito.

**Comment by marimendes** [comment]
Bom dia @matoscas. Você sabe me informar se o erro continua?

**Comment by matoscas** [comment]
olá. Não, o erro foi corrigido, aparecem somente os vereadores da legislatura atual. Não testei para cadastrar comissões antigas, pois não há campo para vincular a comissão a uma legislatura, acredito que o sistema vai pegar pela data de criação da comissão, mas ainda não testei.
