### ISSUE TITLE
sequencial de numeração para cada tipo de matéria legislativa

### ISSUE THREAD

**Issue by matoscas** [interlegis/sapl#1664]
olá. Surgiu uma dúvida aqui, no nosso regimento interno fala que a numeração dos Projetos de Lei Complementar (PLC) e as Propostas de Emenda à Lei Orgânica do Município (PELOM) seguem numeração de acordo com a Legislatura (a cada 4 anos), e não anual, como as demais matérias legislativas. Conforme sugestão do Leandro, acredito que retirar a sequência de numeração da tela de Configurações da Aplicação e transferi-la para a tela de Tipo de Matéria Legislativa, para que ao cadastrar cada tipo seja informado qual o sequencial de numeração, seria melhor.

**Comment by DtiLegBG** [comment]
Bom dia.
@VictorFabreF , a ideia é que ao parametrizar o tipo de numeração nos tipos das matérias, ao cadastrar uma nova matéria, escolhendo o tipo, o sistema mostre o ultimo número daquele tipo de matéria cadastrada +1 ?
Se for para ser dessa forma ainda não está funcionando.

**Comment by VictorFabreF** [comment]
Bom dia, 
foi o @edwardoliveira quem implementou essa funcionalidade, eu apenas fiz o merge da branch. Acho que ele irá saber responder melhor esta questão. Obrigado.

**Comment by edwardoliveira** [comment]
Sim, a ideia é que mostre o último tipo de matéria, MAS ainda seguindo o parâmetro informado (por ano, sequencial único ou legislatura). Se não for informado para aquele tipo de matéria então ele pega da configuração geral. 

Por que não está funcionando? Seja mais específico. Ele não está trazendo número algum? Está trazendo o último número ao invés do número + 1?

**Comment by DtiLegBG** [comment]
Bom dia @edwardoliveira 
Mesmo em tabelas auxiliares, matérias legislativas, tipos de matérias legislativas a sequencia de numeração ter sido informada "Sequencial por ano", quando em atividade legislativa, matéria legislativa, adicionar matéria legislativa é escolhido o tipo, independente do tipo  o número que é trazido é o ultimo maior número +1 independente do tipo

**Comment by DtiLegBG** [comment]
@edwardoliveira , ainda não, se quiser testar. saplbeta.camarabento.rs.gov.br
user e senha no telegran

**Comment by edwardoliveira** [comment]
Eu não quero acesso remoto. Eu preciso de duas coisas:

1) Um dump da tua base. Me envia por Telegram;

2) Um passo-a-passo do que você está fazendo e o que espera ver, a saber:

2.1) Qual a configuração geral da numeração (em Tabelas Auxiliares -> Configurações da Aplicação);
2.2) Qual a configuração de numeração para o tipo de matéria em questão;
2.3) Qual a tela que vc está acessando (Cadastrar Matéria Legislativa? Protocolar Documento?);
2.4) Qual o tipo de matéria que vc está escolhendo? E o ano?
2.5) Qual o número vc espera receber? O que está vindo nesse caso?

Por último, suponha que a numeração original seja por sequencial único, sendo o último número 1873/2018, por exemplo. Daí, suponha que pro tipo de Matéria Legislativa Projeto de Lei vc coloca a sequencial como "por ano". Mesmo agora ele tendo um sequencial por matéria, ele vai pegar o maior número daquele ano, que é 1874. Só ano que vem é que ele vai resetar pra 1 de novo. Entendeu? Vc está ciente disso, né?

**Comment by DtiLegBG** [comment]
Bom dia, o link que te enviei é de base sapl de teste, caso pudesse ajudar.
Respondendo:
2.1)
![image](https://user-images.githubusercontent.com/13314947/36896072-f49e77f8-1def-11e8-9135-e9fb5d1cbb70.png)


2.2)
![image](https://user-images.githubusercontent.com/13314947/36896089-07413a44-1df0-11e8-89b2-460c5bef23af.png)

2.3)
Cadastrar Matéria Legislativa

2.4)
Independente

2.5)
Pretendido:
Escolhendo o tipo de Matéria "Indicação" a sugestão de próximo número deveria ser 269
Escolhendo o tipo de Matéria "Projeto de Lei Ordinária" a sugestão de próximo número deveria ser 31
Escolhendo o tipo de Matéria "Requerimento" a sugestão de próximo número deveria ser 6
Isso acontece quando o fluxo é "protocolar documento" e depois criar matéria.


Voltando ao item 2.3, quando seguido o fluxo "Protocolar Documento", e depois criar matéria, funciona perfeitamente. como dito, o comportamento diferente do pretendido acontece somente quando o operador vai diretamente em "Cadastrar matéria legislativa"

**Comment by edwardoliveira** [comment]
Preciso de acesso direto ao PostgreSQL *também*. Por isso é melhor o dump. E pq acesso local é mais rápido (loopback interface)

**Comment by edwardoliveira** [comment]
Um instante, vc cadastrou a configuração global como numeração por ano e cada um dos tipos de matéria como sequencial por ano *também*? Não é assim q se usa. Vc cadastra as numerações dos tipos q diferem! E outros herdam do global!!! 

Manda o dump da base e olharemos isso.

**Comment by edwardoliveira** [comment]
Manda o dump da base e olharemos isso.

**Comment by matoscas** [comment]
então, como coloquei na issue 1727, até ontem o sistema estava gerando números individuais por tipo de matéria, por exemplo, para Projeto de Lei, vinha como último o 12, para Indicação, o 400 e poucos, para requerimentos o 30 e poucos, e assim por diante. Hoje, quando fomos cadastrar um projeto de lei, apareceu automatico o num. 419. Para o requerimento também. Se até ontem estava gerando certo, e hoje não está mais, tem alguma coisa errada.

**Comment by matoscas** [comment]
o meu sistema está hospedado aí no interlegis.

**Comment by matoscas** [comment]
quando vamos fazer a incorporação das proposições geradas pelos vereadores, está dando o mesmo erro.
Ao incorporar um projeto de lei, puxou o num. 400 e poucos, e não o 12, como estava fazendo até ontem.
