### ISSUE TITLE
Exibição votação nominal para usuário anônimo

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1670]
Nas matéria do expediente o resultado da votação é um link que leva ao extrato da votação

![image](https://user-images.githubusercontent.com/13314947/35150435-85782478-fd01-11e7-8c3b-428524a3305b.png)

![image](https://user-images.githubusercontent.com/13314947/35150417-6fbf42b0-fd01-11e7-8550-7fa3605b8a5f.png)

O mesmo deveria acontecer com as matérias na ordem do dia, porém não acontece
parece que falta montar a url
https://github.com/interlegis/sapl/blob/master/sapl/sessao/views.py#L360
https://github.com/interlegis/sapl/blob/master/sapl/sessao/views.py#L491

**Comment by marimendes** [comment]
Bom dia @DtiLegBG, teria como você me enviar um dumb seu? Pois eu tentei replicar o erro aqui na minha maquina e não consegui. O mesmo para a issue #1671 . Lembrando que o link só deve aparecer se a pessoa estiver logada.

**Comment by DtiLegBG** [comment]
" Lembrando que o link só deve aparecer se a pessoa estiver logada." Acho que não, acho que deve aparecer para o usuário anônimo ter conhecimento de como cada um votou. Exemplo acontece nas matérias do expediente
http://sapl.camarabento.rs.gov.br/sessao/369/expedientemateria

**Comment by marimendes** [comment]
Foi decidido nas issues passadas que o link só deverá aparecer se for uma
votação nominal. Caso ela seja simbólica ou secreta só irá aparecer o
resultado mesmo e não um link. Acho que seja o caso dessa issue.

Grata,

Mariana de Souza Mendes
Estudante de Engenharia de Software - UnB/Gama

Em 22 de janeiro de 2018 12:04, Rogério Frá <notifications@github.com>
escreveu:

**Comment by marimendes** [comment]
Foi decidido nas issues passadas que o link só deverá aparecer se for uma votação nominal. Caso ela seja simbólica ou secreta só irá aparecer o resultado mesmo e não um link. Acho que seja o caso dessa issue.

**Comment by DtiLegBG** [comment]
isso, isso mesmo, se a votação for nominal o link deve aparecer, hoje não está aparecendo nas matérias com votação nominal nas matérias da ordem do dia

**Comment by DtiLegBG** [comment]
Bom dia.  Ainda existe problema
Para usuário anônimo
![image](https://user-images.githubusercontent.com/13314947/35434193-67359664-026d-11e8-9881-10043051c4c5.png)


Para o usuário logado
![image](https://user-images.githubusercontent.com/13314947/35434217-7f9fb414-026d-11e8-9606-488b6fffa932.png)

**Comment by DtiLegBG** [comment]
http://saplbeta.camarabento.rs.gov.br/sessao/367/ordemdia

**Comment by marimendes** [comment]
O erro foi corrigido mas ainda não foi mergeado. Falarei com o Edward para
fazer isso.

Em 26 de jan de 2018 07:50, "Rogério Frá" <notifications@github.com>
escreveu:
