### ISSUE TITLE
Painel de Votação

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1672]
1  -Quando aberto o painel, sem abrir nenhuma matéria para votação, palavras são cortadas na esquerda
![image](https://user-images.githubusercontent.com/13314947/35215830-ad887ca4-ff4c-11e7-912d-84afa94749b3.png)

2 - É criada uma barra de rolagem horizontal que fica sempre, independente dos dados exibidos em tela

3 - Quando "Não votou" é quebrada linha e a visualização fica confusa
![image](https://user-images.githubusercontent.com/13314947/35216014-4e4dca04-ff4d-11e7-985b-55cab354b4fa.png)

 4 -  Oradores. A ideia seria exibir os oradores do expediente ? , mas e quando a matéria a ser votada é da ordem do dia que não existe a possibilidade de cadastrar oradores para a ordem do dia ? . Penso que talvez seria o caso de tirar oradores do painel.

5 - Barra de rolagem vertical. Ocorre que quando a ementa tem 3 linhas ou mais. O problema disso é ter que ficar escolhendo o que do painel vai ficar em tela. Penso que o painel deveria ter tamanho fixo e os textos serem truncados ao atingir o tamanho máximo.

**Comment by VictorFabreF** [comment]
Boa tarde,
Eu não consegui replicar na minha máquina os problemas descritos nos itens 1, 2, 3 e 5. Qual a versão do SAPL que você está usando (se possível indicar o commit)? Qual  browser e sistema operacional utilizados?
Para tratar o item 4, eu criei a issue #1676.

**Comment by DtiLegBG** [comment]
Olá. 
Windows 64
Firefox 58.0
sapl - 73a3b1a Troca integração do py.test com ipdb pelo pdb++

Obrigado

**Comment by DtiLegBG** [comment]
Chrome Versão 63.0.3239.132 (Versão oficial) 64 bits ocorre o mesmo

**Comment by VictorFabreF** [comment]
Boa tarde,
testando aqui o Painel só consegui replicar o erro 3 ao diminuir muito o tamanho da tela. A situação em que ele ocorre é a mesma no seu caso? Saberia nos dizer por que você precisa fazer isso?

**Comment by DtiLegBG** [comment]
Bom dia. Agora está sem barra horizontal, porém a visualização ficou muito confusa e criou uma barra enorme de rolagem vertical.

![image](https://user-images.githubusercontent.com/13314947/35504341-f7894dd8-04c9-11e8-8a97-1cba1907d2a7.png)

Essa maquina é de testes, caso queira as credenciais de acesso me chame no telegran, acho que vai ficar melhor de ver o que acontece.

Sobre diminuir o tamanho de tela, testei em outras maquinas e o comportamento é igual, estou usando o browser em tela cheia f11

**Comment by marimendes** [comment]
Assim fica melhor? ![captura de tela de 2018-01-29 08-24-08](https://user-images.githubusercontent.com/11450196/35505667-f755cdb0-04cd-11e8-84bd-d68176bf8369.png)

**Comment by DtiLegBG** [comment]
Talvez fosse melhor colocar o horário atual na mesma linha da data e horário de inicio, identificando como sendo horário atual, já eliminaria algumas linhas, para a matéria em votação distribuiria para toda a tela na parte inferior como estava no inicio. já o resultado de votação que aparece abaixo da matéria em votação colocaria junto ao resultado, e todo o bloco resultado abaixo do bloco de cronometro. então a lista de oradores que é dinâmica teria espaço para crescer sem empurrar o resto para baixo.
