### ISSUE TITLE
Instalação em VPS

### ISSUE THREAD

**Issue by fabiobelo** [interlegis/sapl#1680]
Como proceder em instalação numa VPS?

**Comment by eribeiro** [comment]
https://www.digitalocean.com/community/tutorials/how-to-deploy-a-local-django-app-to-a-vps

http://michal.karzynski.pl/blog/2013/06/09/django-nginx-gunicorn-virtualenv-supervisor/

**Comment by fabiobelo** [comment]
Segui todos os passos, mas, não esta funcionando. Não sai do Welcome to nginx. :(
