### ISSUE TITLE
Protocolo de proposições

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1683]
Quando for protocolar proposições ter a opção também de protocolar anexos à proposição. 

Ex: Requerimento 1/2018 - anexo: Imagem

**Comment by VictorFabreF** [comment]
Existe a possibilidade de anexar documentos acessórios na Matéria Legislativa, portanto quando uma proposição vira matéria os documentos podem ser anexados. Caso o anexo seja uma imagem, exporte para PDF e anexe na matéria.
