### ISSUE TITLE
Substituir proposição

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1684]
Quando for editar e reenviar a proposição. Puder limpar e já anexar o novo documento.

**Comment by tapumar** [comment]
Olá, @paulot12.
Para substituir um documento, pode anexar o documento novo sem precisar marcar a opção limpar, fazendo com que o antigo seja substituido automaticamente. Deixando a opção limpar apenas para quando quiser limpar o campo sem anexar um novo na hora. :)
