### ISSUE TITLE
Expedição do Diploma obrigatoria

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1699]
No cadastro de mandato, a data de expedição de diploma é uma informação obrigatória. Para cadastro de legislatura passada obriga os operadores a cadastrar uma data qualquer para poder adicionar o mandato, já que em muitos casos, não é possível localizar a data correta.
Data de Expedição do Diploma tem mesmo a necessidade de ser obrigatória?

**Comment by edwardoliveira** [comment]
Particularmente, sou contra tirar a obrigatoriedade de campos, a não ser que tenha uma razão técnica suficientemente forte como uma mudança na modelagem de dados que afete esse campo. Mas vamos ver o que o restante do pessoal acha, ok?

**Comment by DtiLegBG** [comment]
Claro !
@andreagudo @LeandroRoberto

**Comment by LeandroRoberto** [comment]
em caso de registros históricos é bem complicado... veja... identificar datas de expedição de diploma de vereadores de todas as minhas 19 legislaturas... vai ser colocado qualquer data messssmo.

**Comment by edwardoliveira** [comment]
Tentei imaginar casos em que ter data de diplomação seria interessante, mas não encontrei nenhum. Como agora data inicio de mandato é obrigatório, podemos remover a obrigatóriedade de campo. Vamos fazer isso.
