### ISSUE TITLE
Painel Eletrônico

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1706]
Quando aberto o painel eletrônico, Abrir Votação, de uma matéria que está na Ordem do dia, a lista de presentes que é exibida no painel é a informada na Abertura/Presença, onde o correto deveriam ser os presentes informados em Ordem do dia/Presença ordem do dia.  A partir da segunda matéria que é aberta a votação na ordem do dia, a lista de presenças que é exibida é a correta, ou seja, a informada em Ordem do dia/Presença ordem do dia.

Melhoria:
Na tela de registro de votação, onde o operador informa o resultado, informar após "ainda não votaram", o total de presentes
![image](https://user-images.githubusercontent.com/13314947/36427141-127a4760-162b-11e8-95ab-6b3a5dff8f8b.png)

No painel, aumentar a fonte dos tipos resultado e quantidades.
![image](https://user-images.githubusercontent.com/13314947/36427195-342a26a0-162b-11e8-9c4a-e965b40f2aca.png)

**Comment by VictorFabreF** [comment]
Boa tarde,
Simulei na minha máquina uma situação para tentar gerar o erro quanto às presenças e ele não ocorreu aqui. Tudo me pareceu funcionar de acordo com o normal. Seguem as capturas de tela do meu teste. 

![photo_2018-02-20_13-21-54](https://user-images.githubusercontent.com/19825887/36435741-406a8336-1641-11e8-91e8-e16e5e0932ce.jpg)

![photo_2018-02-20_13-22-40](https://user-images.githubusercontent.com/19825887/36435742-409026a4-1641-11e8-919e-302804c07738.jpg)

Você poderia mandar capturas de tela do erro ocorrendo, por favor?

**Comment by DtiLegBG** [comment]
Boa Tarde.
Presença na ordem do dia sem cadastrar presença em abertura/presença
![image](https://user-images.githubusercontent.com/13314947/36436102-2b671f2a-1642-11e8-889a-fe59f1842f7a.png)

Registrando em abertura/presença
![image](https://user-images.githubusercontent.com/13314947/36436139-4609f2da-1642-11e8-8111-1588f0120d1b.png)

Desmarcando em ordem do dia/presença ordem do dia
![image](https://user-images.githubusercontent.com/13314947/36436244-7b8ada3c-1642-11e8-9c16-810eade870c1.png)

Lembrando que a partir da votação do segundo projeto da ordem do dia, funciona como esperado

**Comment by VictorFabreF** [comment]
Ainda não conseguimos replicar os erros aqui nas nossas máquinas. Poderia mandar um screencast desde a abertura da sessão até o acontecimentos dos erros, por favor?

**Comment by DtiLegBG** [comment]
Bom dia.
@VictorFabreF , cara, não consegui mais reproduzir o erro, rss.
Que bom! muito obrigado

**Comment by VictorFabreF** [comment]
Que ótimo! Vou fechar a issue então, se o erro voltar a acontecer reabrimos.
