### ISSUE TITLE
Erro ao incorporar proposição

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1708]
**O erro acontece para as proposições que nas tabelas auxiliares, tipos de proposição, na definição de tipos é escolhido "Tipo de documento".**

![image](https://user-images.githubusercontent.com/13314947/36437103-dc7a06e0-1644-11e8-85b0-d57700ce9736.png)

**Feito isso o autor cria uma proposição com um texto eletrônico**

![image](https://user-images.githubusercontent.com/13314947/36437497-ec2d073a-1645-11e8-9e6d-a0ad1e7454b9.png)

**Ao incorporar a proposição acontece o erro**

![image](https://user-images.githubusercontent.com/13314947/36437601-35ee64c2-1646-11e8-845a-9fe280cbcc35.png)

![image](https://user-images.githubusercontent.com/13314947/36437426-b41b2d9a-1645-11e8-9c71-c5c2b2f596a4.png)

**Comment by VictorFabreF** [comment]
Boa tarde, ontem e hoje foram feitas algumas alterações nessa parte de proposição. Você poderia testar novamente e ver se o erro ainda persiste? Obrigado

**Comment by DtiLegBG** [comment]
Bom dia.
Sim, ainda acontece.

**Comment by VictorFabreF** [comment]
Bom dia, você pode mandar por favor então uma sequência de screen shots ou então um screencast dos passos que fazem o erro ocorrer, por favor?
Não consegui reproduzir aqui o erro. Qual o formato do arquivo que está sendo anexado na proposição?
Obrigado

**Comment by VictorFabreF** [comment]
Bom dia, o erro ainda persiste?
