### ISSUE TITLE
faltando parlamentares na tela Adicionar Autoria e outras

### ISSUE THREAD

**Issue by matoscas** [interlegis/sapl#1709]
olá. Estamos com um problema, estão faltando 2 parlamentares na combo de autor quando tento adicionar uma ou várias autorias a um processo legislativo. Os vereadores estão cadastrados como autor corretamente (até mesmo porque se não estivessem, seus assessores não conseguiriam protocolar matérias no sistema). Em outras telas que aparece a mesma combo, faltam os dois vereadores. Na tela de Tabelas Auxiliares / Autores, eles estão lá, todos os 13. Os vereadores que estão faltando na lista são o Luiz Alfredo e o Edoel Rocha.

**Comment by matoscas** [comment]
onde está escrito "faltando na lista" leia-se "faltando na combo"

**Comment by edwardoliveira** [comment]
Teu SAPL está hospedado no Interlegis? Qual a casa? 

O que temos visto por aqui é que quando faltam parlamentares é porque a data de início de mandato não foi informada, ou porque o parlamentar consta como Inativo. Ambas as situações podem ser verificadas na tela de Parlamentares, e sanadas por lá também.

**Comment by matoscas** [comment]
olá Edward. A data de início de mandato está correta, e o parlamentar está ativo. Nosso sapl está hospedado aí no interlegis, Campo Mourão-PR, como eu disse, os parlamentares conseguem incluir proposições corretamente no sistema, mas os citados não aparecem nas combos de parlamentares.

**Comment by VictorFabreF** [comment]
Boa tarde
Eu fui analisar a base de dados e vi que existem algumas inconsistências. No sistema, deve-se criar apenas um perfil para cada parlamentar e então criar um mandato para este perfil dentro de cada legislatura em que ele for eleito. Na sua base existe um perfil para cada mandato do parlamentar. 
Dessa maneira podem ocorrer erros como o que está ocorrendo com você. O autor vinculado ao vereador Luiz Alfredo é da legislatura de 2005-2008, dessa maneira o atual perfil dele não possui um autor vinculado e não será possível então adicionar autoria para ele. Deve-se juntar todos os perfis em apenas um. No caso do vereador Edoel Rocha o perfil vinculado a autor é da legislatura 2001-2004 e ocorre o mesmo problema que com o vereador Luiz Alfredo.

**Comment by matoscas** [comment]
Bom dia Victor. Era exatamente isso, fui conversar com a servidora responsável pelo cadastro, e ela me confirmou que cadastrou varias vezes o vereador, uma para cada mandato. Excluí os cadastros, adicionei os mandatos a um único cadastro, e deu certo. Só que eu tenho uma sugestão a dar. Como o cadastro do vereador é único, não seria melhor adicionar a foto no mandato, ao invés de adicionar no cadastro? Veja o seguinte, no exemplo do Edoel, ele foi vereador em 2000, 2008 e agora. Você concorda que a foto à época da 1ª já não pode ser usada agora na última? Na minha concepção, o correto seria que a foto ficasse vinculada ao mandato, pois quando for exibida a pagina dos Parlamentares, a foto que vai aparecer será a foto correspondente à época em que ele foi vereador, porque se eu colocar a foto atual dele, vai dar uma diferencinha de 18 anos atrás (heheheh).

**Comment by VictorFabreF** [comment]
Boa tarde
Que ótimo que você conseguiu resolver o seu problema. 
Obrigado pela sugestão sobre a foto, iremos analisar aqui e ver se será implementada, enquanto isso você pode atualizar a foto no cadastro do parlamentar para uma mais recente.
Até mais.
