### ISSUE TITLE
Implementar telas que disparam relatórios PDF

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#172]
Agora que já temos a estrutura para rodar os relatórios, precisamos criar as telas que "disparam" os relatórios PDF.

**Comment by edwardoliveira** [comment]
Continuação da issue #37

**Comment by marciomazza** [comment]
@edwardoliveira explicou que não existe um ponto central de visualização dos relatórios, mas sim que os links para os relatórios estão espalhados pelo sistema.

**Comment by edwardoliveira** [comment]
SIm, isso mesmo. E já colocamos nas telas necessárias (relatório de sessão, etiquetas, por exemplo). Assim, não vejo razão para manter este ticket aberto.
