### ISSUE TITLE
Formatar mudança de linha nos campos text do crud

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#1722]
As mudanças de linha `\n` dos campos TextField, ao que parece, estão sendo exibidas nas telas de leitura do crud.

Por exemplo no campo `observacao` de `DocumentoAdministrativo`.

**Comment by edwardoliveira** [comment]
Como assim? Pra aparecer na tela teria que ser um `<br/>`, não? Eu e a @tapumar testamos aqui e parece que renderiza sem a quebra como visto na figura. Vc quer que o \n seja retirado? Ou substituido por um <br>?

![image](https://user-images.githubusercontent.com/9326037/36745220-95f3a828-1bcd-11e8-89de-3b405c303f0e.png)

**Comment by marciomazza** [comment]
Eu acho que deveria trocar `\n` por algo como `<br/>`, ou usar algum estilo
tipo `<pre>` (se é que existe isso) ou usar o `<pre>`. Não sei realmente
qual a melhor solução.

2018-02-27 14:50 GMT-03:00 Edward <notifications@github.com>:

**Comment by marciomazza** [comment]
Fechado em 74f91f0f77e12107

**Comment by marciomazza** [comment]
Precisamos reverter em 724d9da7 devido a #1757

**Comment by VictorFabreF** [comment]
Fechado em fe3ad35
