### ISSUE TITLE
Redirecionamento de urls antigas com defeito

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#1723]
Pelo menos o redirecionamento para documento administrativo parece não funcionar.
Ex.(quando existe um doc adm com id=483 na base): 
`localhost:8000/sapl/cadastros/documento_administrativo/documento_administrativo_mostrar_proc?cod_documento=483`

Fazer uma revisão completa de todos os redirecionamentos.
Escrever testes.

**Comment by edwardoliveira** [comment]
Isso não tinha sido feito pelo @eliseuegewarth ?

**Comment by VictorFabreF** [comment]
#127

**Comment by eliseuegewarth** [comment]
Como dito pessoalmente, o escopo definido para a issue #127 eram apenas urls públicas, para usuários não logados, tornando essa issue inválida.
