### ISSUE TITLE
Erro mas filiações partidárias

### ISSUE THREAD

**Issue by matoscas** [interlegis/sapl#1724]
Olá. Há um erro na tela de Filiações partidárias, no cadastro dos parlamentares. Vou citar o exemplo do meu vereador. O Edilson Martins foi vereador em nossa casa de leis na legislatura anterior e agora na atual. Na anterior, pelo PSD, e agora, pelo PR. Ele se filiou no PSD em 04/10/2011, e desfiliou-se em 15/03/2016. No dia seguinte, filiou-se no PR, no qual está até hoje. Eis aqui o problema. Ao incluir os dois mandatos, e as duas filiações partidárias (com as datas acima), na tela dos Parlamentares, ao selecionar a legislatura atual, aparece que ele está no PR, corretamente, mas ao selecionar a legislatura anterior, também aparece PR, e não PSD. Aí fui nas filiações, alterei a data da filiação ao PR para 01/01/2017, e alterei a data de desfiliação do PSD para 31/12/2016, aí o sistema exibe corretamente, na legislatura atual PR e na anterior PSD. Isso está incorreto, afinal ele foi eleito pelo PSD na legislatura passada, e só mudou para a reeleição. O sistema deveria vincular a filiação partidária com a data de início do mandato, e não no intervalo inteiro, pois todos os vereadores que mudam de partido, eles não o fazem somente depois que acaba o mandato, fazem antes da eleição.

**Comment by andreagudo** [comment]
Ocorre que a mudança partidária ocorreu "antes da eleição", isto é, durante o mandato anterior. Nesse caso, o partido que aparece é o último em que o parlamentar filiou-se naquela legislatura. Não acho isso incorreto, até porque há um registro das mudanças de partido para consulta.

**Comment by edwardoliveira** [comment]
Eu compartilho a opinião do @andreagudo
