### ISSUE TITLE
problema numeração de proposições (URGENTE)

### ISSUE THREAD

**Issue by matoscas** [interlegis/sapl#1727]
Olá. Aconteceu alguma coisa no sapl de ontem pra hoje, porque fomos cadastrar um projeto de lei no sistema hoje, e ao invés de puxar o número 12, que está na sequencia, ele estava puxando o 419, que é a sequencia das indicações. Fui testar inserindo um requerimento, e acontece a mesma coisa, o requerimento está no número 30, e ele puxa automático o 419, fui simular um Projeto de Emenda à Lei Orgânica, que deveria ser o número 1, e também aparece o número 419 no sequencial automático. Gostaria de saber o que aconteceu, pois até ontem estava normal. Estou com a prefeitura aqui precisando cadastrar projeto de lei.

**Comment by matoscas** [comment]
Percebi que na tela de Tipos de Matérias Legislativas, há a opção de vincular o sequencial de numeração, não me lembro de ter visto isto lá antes, se foi implementado de ontem pra hoje, acredito que está havendo algum erro.

**Comment by DtiLegBG** [comment]
#1664
