### ISSUE TITLE
problema de numeração no sapl

### ISSUE THREAD

**Issue by matoscas** [interlegis/sapl#1729]
olá Edward, aqui é o Flávio da Camara Municipal de Campo Mourão-PR. Nosso sapl está hospedado no interlegis. Conforme já havia explicado na issue 1727, acho que ainda há um problema com a numeração das proposições. Quando eu abro a tela de Matérias Legislativas, e clico em Adicionar Matéria Legislativa, está funcionando corretamente, para cada Tipo de Matéria, após selecionar o ano, a numeração muda, sempre pegando o último número de cada tipo. Até aí blz. Só que quando o responsável pelo Depto Legislativo foi incorporar uma proposição do tipo Requerimento no sistema, vindo de um dos gabinetes de vereadores, o sistema puxou automaticamente o último número das Indicações (400 e poucos), quando o correto seria ele ter puxado o dos requerimentos (30 e poucos). Por conta disso, o servidor fez a incorporação, mas depois de incorporada, ele teve que abrir a matéria e alterar o número.

**Comment by edwardoliveira** [comment]
Fizemos um novo release: 3.1.57, e reiniciamos as máquinas hospedadas aqui. Poderia verificar se o problema ainda persiste?

**Comment by matoscas** [comment]
olá Edward, acabamos de testar, e ao incorporar um requerimento, pegou certinho a numeração. Obrigado pela atenção.
