### ISSUE TITLE
PROPOSITURA APROVADA

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1746]
É necessário criar uma função no SAPL para "carimbar" as proposições que forem APROVADAS, REJEITADAS, RETIRADA DE PAUTA. Ou seja aparecer um código no texto original informando se a mesma foi aprovada, rejeitada e retirada de pauta.

**Comment by edwardoliveira** [comment]
Você diz quando as proposições forem incorporadas aparecer no texto original a palavra "APROVADA" ou "REJEITADA" caso contrário? E esse retirada de pauta seria na sessão plenária?

**Comment by andreagudo** [comment]
Entendo que o paulo12 quer o resultado da pesquisa de proposições informe na primeira tela, no caso daquelas que tiveram tramitação encerrada, se elas foram aprovadas, rejeitadas ou retiradas. Poderia ser uma informação inserida no sistema a partir de uma tramitação.

**Comment by paulot12** [comment]
No texto original da proposição aparecer a palavra "APROVADA" e "REJEITADA" caso contrário. E retirada de pauta seria na Sessão Plenária.

**Comment by VictorFabreF** [comment]
Duplicada na issue #2478
