### ISSUE TITLE
Implementar no SAPL Agenda Telefônica com acesso rápido - ideia Futura

### ISSUE THREAD

**Issue by VincyAfonso** [interlegis/sapl#1747]
Com o intuito de auxiliar as recepções (Telefonista) das Câmaras facilitando o acesso rápidos aos números de  telefones salvos.

**Comment by sesostris** [comment]
Agenda telefônica e controle de telefonia não guarda relação com processo legislativo. Esta issue não é pertinente ao projeto SAPL e não será implementada.
