### ISSUE TITLE
Encerrar votação nominal ao efetuar o seu registro e informar aos parlamentares 

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#1748]
No momento do registro, no encerramento da votação, o parlamentar ainda consegue votar ... sugerimos enviar mensagemao parlamentar sobre o encerramento e inibir os botões de votação. Também seria interessante que o botão digitado pelo parlamentar na votação fosse esmaecido de modo a permitir visualmente saber o que foi votado.

**Comment by VictorFabreF** [comment]
Issue #1780 e esta são muito semelhantes. A @marimendes já está resolvendo isso.
