### ISSUE TITLE
botões EDITAR e EXCLUIR na tela de Tipo de Autor não funcionam

### ISSUE THREAD

**Issue by matoscas** [interlegis/sapl#1752]
olá. Aqui é da Câmara Municipal de Campo Mourão-PR, sapl hospedado no interlegis. Os botões acima não estão executando ação nenhuma, nem edita o nome e nem exclui o registro.

**Comment by edwardoliveira** [comment]
Poderia enviar screenshots da tela?

**Comment by matoscas** [comment]
![image](https://user-images.githubusercontent.com/34271281/37344770-08f76c74-26aa-11e8-89af-bf33d3730639.png)
Fica nessa tela, ao clicar no botão SALVAR não faz nada. No excluir a mesma coisa, ao clicar em CONFIRMAR não exclui o registro.

**Comment by matoscas** [comment]
no registro, a palavra Poder Executivo está inteira em maiúsculo, cliquei em editar para colocar só a primeira letra em maiúsculo, e ao clicar no salvar nao faz nada. Ele deveria voltar para a tela com os registros, mas não sai daí.

**Comment by edwardoliveira** [comment]
Já identicamos o problema, estamos corrigindo.

**Comment by edwardoliveira** [comment]
O problema foi resolvido. Na próxima versão, que sairá ainda hoje este bug não estará mais lá.
