### ISSUE TITLE
Botão abrir votação

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1755]
Na sessão plenária, matérias da ordem do dia

![image](https://user-images.githubusercontent.com/13314947/37402664-3630d614-276b-11e8-8ee4-401d730366a6.png)

**Comment by marimendes** [comment]
Boa tarde @DtiLegBG. Os outros botões e imagens da página carregam corretamente? Apenas esse botão não está aparecendo?

**Comment by DtiLegBG** [comment]
Boa tarde @marimendes , a principio com o restante está ok, era somente esse botão que se conseguiu identificar o problema.

**Comment by rannyel** [comment]
Boa tarde. Também estou com o mesmo problema.

**Comment by marimendes** [comment]
O problema já foi identificado, iremos lançar um release com a correção.
