### ISSUE TITLE
RECEBER PROPOSIÇÕES

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1761]
É possível receber proposições sem o recibo de envio? Se puder como faço?

**Comment by rannyel** [comment]
@paulot12 Bom dia. Sim, é possível. 

Você precisa acessar "tabelas auxiliares", logo em seguida acessar "Configurações da aplicação", após isso verificar na linha "Proposições e protocolos" a opção "Protocolar proposição somente com recibo?"  Nesse momento, você poderá escolher "Sim" ou "Não". Então, clique em "salvar".

Aqui em Vitória da Conquista nós alteramos esse modo de recebimento nessa semana porque estava dando muito trabalho digitar o código inteiro. Contudo, por causa do controle de recebimento, nós não avisamos isso aos assessores. Então, o que ocorre na prática é que ao enviar uma proposição, eles continuam tendo a geração do recibo. Nós aguardamos que eles enviem esse recibo e então recebemos a proposição sem precisar digitar o código. 

Para receber, você acessa "Protocolo", em seguida "Receber Proposições", após isso "Proposições Não Recebidas". Nessa página você visualizará na última coluna "Código do Documento" os códigos das proposição enviadas. Estarão na cor azul. Você clicará nesse código e em seguida incorporará a proposição sem precisar digitar o código.

![receber_sem_protocolo](https://user-images.githubusercontent.com/37225107/37462032-4725cdd4-282f-11e8-84d4-e87805da0e79.png)

**Comment by VictorFabreF** [comment]
É possível receber as proposições sem o recibo de envio. Basta seguir os passos abaixo:
1) Estando logado no sistema como administrador você irá em tabelas auxiliares.
![image](https://user-images.githubusercontent.com/19825887/37461837-8b2979fa-282e-11e8-997d-e0ef1d807515.png)

2) Você então deverá ir em configurações da aplicação.
![image](https://user-images.githubusercontent.com/19825887/37461863-a1369638-282e-11e8-9570-5aaa505aa0f4.png)

3) No campo "Protocolar somente com recibo?" deverá escolher a opção "Não" e salvar as configurações.
![image](https://user-images.githubusercontent.com/19825887/37461891-c374d2a0-282e-11e8-8ad2-846788c8f909.png)

4) Ao ir então em "Receber Proposições" -> "Proposições Não Recebidas" terá uma nova coluna na tabela chamada "Código do Documento" na qual aparecerá um link que o enviará para o recebimento da proposição.
![image](https://user-images.githubusercontent.com/19825887/37462110-883beb64-282f-11e8-9719-a0152add840e.png)

Observação: Esse novo modo de receber proposições só será possível para proposições enviadas após a alteração da configuração.

**Comment by paulot12** [comment]
Ok. Obrigado!


________________________________
De: VictorFabreF <notifications@github.com>
Enviado: quinta-feira, 15 de março de 2018 09:02
Para: interlegis/sapl
Cc: paulot12; Mention
Assunto: Re: [interlegis/sapl] RECEBER PROPOSIÇÕES (#1761)


É possível receber as proposições sem o recibo de envio. Basta seguir os passos abaixo:

  1.  Estando logado no sistema como administrador você irá em tabelas auxiliares.
[image]<https://user-images.githubusercontent.com/19825887/37461837-8b2979fa-282e-11e8-997d-e0ef1d807515.png>

[https://user-images.githubusercontent.com/19825887/37461837-8b2979fa-282e-11e8-997d-e0ef1d807515.png]

  2.  Você então deverá ir em configurações da aplicação.
[image]<https://user-images.githubusercontent.com/19825887/37461863-a1369638-282e-11e8-9570-5aaa505aa0f4.png>

  3.  No campo "Protocolar somente com recibo?" deverá escolher a opção "Não" e salvar as configurações.
[image]<https://user-images.githubusercontent.com/19825887/37461891-c374d2a0-282e-11e8-8ad2-846788c8f909.png>

  4.  Ao ir então em "Receber Proposições" -> "Proposições Não Recebidas" terá uma nova coluna na tabela chamada "Código do Documento" na qual aparecerá um link que o enviará para o recebimento da proposição.
[image]<https://user-images.githubusercontent.com/19825887/37462110-883beb64-282f-11e8-9719-a0152add840e.png>

Observação: Esse novo modo de receber proposições só será possível para proposições enviadas após a alteração da configuração.
