### ISSUE TITLE
MATÉRIAS DA ORDEM DO DIA

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1762]
Sugiro disponibilizar a ferramenta para quando clicar no resultado da votação, o usuário deslogado, possa visualizar a votação. Quantidade de votos sim, não, abstenção.

**Comment by VictorFabreF** [comment]
Isso seria em que tipo de votação? 
Essa funcionalidade já existe para votação nominal.

**Comment by paulot12** [comment]
Votação simbólica.


________________________________
De: VictorFabreF <notifications@github.com>
Enviado: quinta-feira, 15 de março de 2018 11:51
Para: interlegis/sapl
Cc: paulot12; Author
Assunto: Re: [interlegis/sapl] MATÉRIAS DA ORDEM DO DIA (#1762)


Isso seria em que tipo de votação?
Essa funcionalidade já existe para votação nominal.

**Comment by edwardoliveira** [comment]
Veja se resolveu a isso a contento, por favor. Caso contrário é só reabrir que olhamos de novo.
