### ISSUE TITLE
ESCOLHER AUTOR NA PRIMEIRA TELA

### ISSUE THREAD

**Issue by Neybson** [interlegis/sapl#1763]
Sugiro que o cadastro da Matéria Legislativa tenha ao mesmo tempo (que foi um grande avanço no Sapl 3.0) a escolha do autor. Essa medida vai economizar muito trabalho dos operadores!

**Comment by edwardoliveira** [comment]
Um informe:

A sugestão é interessante, mas devo frisar que novos recursos **não serão mais implementados** na versão 3.1, que a partir de agora encontra-se congelada. Iremos avaliar e, eventualmente, implementar isso para versões futuras do SAPL (3.2, 3.3, etc). No momento iremos corrigir erros e melhorar o desempenho do 3.1.

**Comment by edwardoliveira** [comment]
Vou reabrir esta issue porque ficou faltando o autor na tela de formulário simplificado de criação de matéria e temos que ver se deixamos ou não a select trazer todos os autores (inativos, etc).
