### ISSUE TITLE
Cadastrar arquivo com discurso do orador ou orador do expediente

### ISSUE THREAD

**Issue by cristian-longhi** [interlegis/sapl#1766]
Após cadastrar um orador para explicações pessoais / orador de expediente, não há um campo para upload do arquivo com o discurso na íntegra, somente o link para vídeo do discurso, se for o caso.
Embora seja um recurso que atualmente não vem sendo muito utilizado, temos na base do SAPL 2.5 um histórico de discursos antigos que entendo ser necessário disponibilizar também no 3.1.

**Comment by cristian-longhi** [comment]
@marimendes, @edwardoliveira , é isso mesmo o que precisamos, no entanto, faltou o campo para upload do arquivo na tela dos oradores das Explicações Pessoais...

**Comment by edwardoliveira** [comment]
Favor verificar agora...

**Comment by cristian-longhi** [comment]
Ok!
