### ISSUE TITLE
NÚMERO DA PROPOSIÇÃO

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1767]
Sugiro indicar o número da proposição a ser criada quando for enviar a proposição pelo SAPL. Exemplo: Tipo de Matéria Legislativa: Requerimento (aparecer o número da matéria a ser incorporada).

**Comment by VictorFabreF** [comment]
Sua sugestão é para indicar o futuro número que a matéria legislativa a ser criada a partir daquela proposição terá (ex: a proposição 30/2018 vai gerar a indicação 5 de 2018) ou para indicar o número da proposição (ex: foto a seguir)?
![image](https://user-images.githubusercontent.com/19825887/37529268-7957bd1c-2915-11e8-800c-6695746a1b8e.png)

**Comment by paulot12** [comment]
Isso mesmo indicar o futuro número que a matéria legislativa a ser criada a partir daquela proposição terá (ex: a proposição 30/2018 vai gerar a indicação 5 de 2018)

**Comment by edwardoliveira** [comment]
Essa ideia é interessante, mas vc tem que estar ciente de que se trata de um número **SUGERIDO** porque se dois ou mais autores estiverem fazendo proposições do tipo indicação e submeterem mais ou menos no mesmo tempo, um vai pegar a 5 de 2018, o outro vai pegar o 6 de 2018 e assim sucessivamente. "Reservar" números accarreta mais problemas que soluções. Mas **acho** que podemos colocar algo assim na tela:

`indicação 5/2018 (número provável ou sugerido).`
