### ISSUE TITLE
Diretório "None" no sistema de arquivos de proposições

### ISSUE THREAD

**Issue by cristian-longhi** [interlegis/sapl#1770]
O caminho no banco de dados das proposições, quando migradas, ficam com a seguinte estrutura no sistema de arquivos:
![proposicao migrada](https://user-images.githubusercontent.com/22030378/37607291-68cf0bf4-2b76-11e8-9f0e-7501b140b41a.png)
Porém, ao se efetuar o upload manual, surge um diretório None:
![proposicao manual](https://user-images.githubusercontent.com/22030378/37607377-a0b03e80-2b76-11e8-8fff-c37a2c02021f.png)

**Comment by marimendes** [comment]
Boa tarde @cristian-longhi. Teria como você me enviar um print da página inteira? eu tentei replicar o error aqui e não consegui. 
![captura de tela de 2018-03-19 13-38-55](https://user-images.githubusercontent.com/11450196/37609371-b89b562e-2b7b-11e8-887f-4763ff99a898.png)

**Comment by marimendes** [comment]
Você pode me enviar um dumb?

**Comment by cristian-longhi** [comment]
@marimendes, a tela é esta mesmo do teu print. Olhando ela e vendo que deveria ter 2018 no lugar do None, fiz um teste para inclusão de proposição, e dá certo:
![nova proposicao](https://user-images.githubusercontent.com/22030378/37610295-ff33644e-2b7d-11e8-9850-c5bfeed78b96.png)
O problema ocorre se alterar o arquivo vinculado a uma proposicao já existente.

**Comment by marimendes** [comment]
Mandei um mensagem no seu telegram pedindo o seu dumb, pois aqui mesmo alterando um arquivo vinculado de uma proposição já existente não consegui replicar o erro.
