### ISSUE TITLE
Modulo Bancadas Parlamentares - Frente Parlamentar não lista os parlamentares

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#1772]
Ao incluir Frente Parlamentar, o sistema não mostra a lista de parlamentares, para que seja selecionado os respectivos participantes. Numa versão anterior  (final dezembro passado), era possível selecionar, conforme figura capturada naquele mês.

grato

![image](https://user-images.githubusercontent.com/30807716/37616450-b5d0d064-2b8e-11e8-900a-1a0e4df98335.png)

**Comment by edwardoliveira** [comment]
Acabei de corrigir esse bug no commit 67fb477, vamos fazer um release do 3.1.64 com essa correção e daí vc poderá testar (mais pro meio da tarde, ok?). O build das imagens demora uma hora.
