### ISSUE TITLE
AVISO DE TRAMITAÇÃO

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1775]
É interessante indicar que tem tramitação nova para aquele determinado setor.

Exemplo: O gabinete da presidência da Câmara tramita documento para o gabinete do vereador, então o gabinete do vereador recebe um sinal informando que tem nova tramitação.

**Comment by edwardoliveira** [comment]
Um informe:

A sugestão é interessante, mas devo frisar que novos recursos **não serão mais implementados** na versão 3.1, que a partir de agora encontra-se congelada. Iremos avaliar e, eventualmente, implementar isso para versões futuras do SAPL (3.2, 3.3, etc). No momento iremos corrigir erros e melhorar o desempenho do 3.1.
