### ISSUE TITLE
Tipo de Proposição - não aceita inclusão para tipo materia legislativa / tipo documento

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#1777]
Emite a mensagem "Formulário inválido. Registro não foi criado"

**Comment by tapumar** [comment]
Existe algum tipo de documento criado em tabelas auxiliares - tipo de documento?

**Comment by edwardoliveira** [comment]
Conforme a @tapumar perguntou, isso é mais uma falta de dados que um erro em si. Eu coloquei uma modal na tela que irá disparar quando inexistirem dados e daí explicar onde o usuário deve cadastrá-las.

https://github.com/interlegis/sapl/commit/ab8fb6ac022469b6ae4cfb9d22d54077d10507d1
