### ISSUE TITLE
Tramitação em lote / Primeira tramitação

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1779]
Em atividade Legislativa/Tramitação em Lote/Primeira Tramitação, cadastrando uma primeira tramitação, as matérias selecionadas deveriam ter seu status "Em tramitação = Não" alterado para sim. Não está acontecendo

em tempo, status de tramitação, com indicação de retorno cadastrado nas tabelas auxiliares.

**Comment by edwardoliveira** [comment]
Veja se a issue foi resolvida agora. Caso contrário, só reabrir e vemos o que faltou.
