### ISSUE TITLE
Painel Eletrônico - Cronômetro "Questão de Ordem" deve travar os outros dois

### ISSUE THREAD

**Issue by VictorFabreF** [interlegis/sapl#1782]
Ao se iniciar a contagem do cronômetro "Questão de Ordem", a contagem dos outros dois cronômetros deve ser parada.

**Comment by edwardoliveira** [comment]
Talvez tenhamos que fazer isso mesmo pro 3.1. :( Um usuário reclamou mais ou menos disso recentemente...

**Comment by cesaraugc** [comment]
Mergeado na master. Estará disponivel na versão 3.2.
