### ISSUE TITLE
campo Código em Tabelas Auxiliares/Casa Legislativa

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#1783]
Existe a necessidade deste campo no formulário de preenchimento dos dados da Casa Legislativa? 
Posso retirá-lo do caderno de exercícios?

grato
Adal

**Comment by edwardoliveira** [comment]
Cara, esse código veio do 2.5 e eu não tenho a mínima ideia de pra que ele serve. Acho que sim, podemos retirar do caderno de exercícios. Quanto a retirar da tela temos que ver se não vai dar problema com a migração do 2.5 para o 3.1.
