### ISSUE TITLE
implementação de dispositivo para as ocorrências de alterações de nomes de partidos políticos

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#1784]
Temos percebido ultimamente que vários partidos andaram trocando de nome. Se trata de fato que esta se tornando corriqueiro. No SAPL não temos como mencionar esses episódios. Como não é recomendável a simples troca do nome no sistema, para não perder o histórico (do  nome antigo), o que está sendo recomendado e a extinção do partido com o nome antigo, e a criação do mesmo partido com o novo nome, o que ao meu ver, não seria o correto. Sugiro dessa forma, implementação de um dispositivo para mencionar essa troca de nome. Outra opção (paliativa) seria a criação de um campo OBSERVAÇÃO na tela de entrada de dados do partido. Assim, quando o mesmo fosse extinto (em função da alteração do nome), mencionaria na observação que o mesmo trocou de nome e passou a se chamar de xxxx a partir daquela data. E no "novo partido" mencionaria que anteriormente à aquela data (de criação) se chamava yyyy.
grato
Adal

**Comment by edwardoliveira** [comment]
A ideia de criar um histórico de nomes faz sentido, mas gera uma série de problemas, na minha opinião. Por exemplo, isso complicaria as telas de pesquisa: buscar pelo nome mais recente? Fazer uma varredura em todos os nomes que o partido já teve e pesquisar por eles? Então, não acho prudente implementar esse requisito como deveria ser por hora. Já a opção da Observação é bem mais tranquila e sem grandes impactos, i.e., daria pra fazer imediatamente. Mas como congelamos o 3.1 isso ficará eventualmente para versões futuras do sistema.
