### ISSUE TITLE
Melhorar str de AcompanhamentoMateria

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#1785]
` AcompanhamentoMateria.__strt__` está usando um hash. Tornar mais legível.

**Comment by sconetto** [comment]
@edwardoliveira @marciomazza 
Dessa issue eu tenho a seguinte sugestão (se for acatada posso fazer a correção, já que é algo simples)
Acredito que a melhor forma seria Matéria + E-mail + Data do Cadastro.
