### ISSUE TITLE
erro 404 not found na tramitação em lote

### ISSUE THREAD

**Issue by matoscas** [interlegis/sapl#1789]
olá. Aqui é da Câmara de Campo Mourão-PR, sapl hospedado no interlegis, está dando erro 404 not found ao fazer tramitação em lote. Seleciono o menu Atividade Legislativa / Tramitação em lote. Na tela que abre, seleciono INDICAÇÃO no tipo, Coord. Assuntos Legislativos - CAL na unidade, Para Providências no status. Na tela seguinte, aparecem 105 resultados. Seleciono a data, unidade de destino (Plenario), status (incluído no expediente), se é urgente ou nao e o texto da ação. Seleciono da indicação n° 415 em diante, clico no botão SALVAR, e então após alguns segundos, aparece a tela de 404 not found. Voltei na tela,  selecionei da indicação 415 até a 435, cliquei em salvar, e foi com sucesso. O que pode ser???

**Comment by VictorFabreF** [comment]
Boa tarde, 
este erro pode ser causado por um problema de rede. Não conseguimos reproduzir ele aqui. Caso ele ocorra de forma intermitente deve ser de fato um problema de conexão de rede, caso você consiga replicar o erro sistematicamente, avise aqui por favor.
