### ISSUE TITLE
Período Composição de Comissão - A interseção deve ser vazia entre eles.

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#1793]
A função não deve permitir definição de períodos de composição em que haja interseção entre eles, por não fazer sentido.

**Comment by edwardoliveira** [comment]
@morale Assim que liberarmos um release (hoje ainda, mas reiniciaremos as máquinas amanhã a pedido do Fábio), favor testar se o problema foi resolvido a contento. Caso contrário, reabrimos a issue, ok?
