### ISSUE TITLE
Ajustar migração de Assunto em Norma

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#18]
Atentar para relacionamento NxN... Com isso atentar para migração da base antiga que guarda a referência em uma string separada por (;) e controla as visualizações,  edições e inserções via aplicação.

**Comment by marciomazza** [comment]
@LeandroRoberto mudou o model normajuridica de 
https://github.com/interlegis/sapl/blob/045333ed672dd974eba2312785f917ae1516fbfa/norma/models.py#L90
para
https://github.com/interlegis/sapl/blob/master/norma/models.py#L105

A migração precisa ser ajustada.
