### ISSUE TITLE
Rever campos data_hora_criacao e data_hora_atualizacao em RegistroVotacao

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#1800]
Os campos `data_hora_criacao` e `data_hora_atualizacao` em `RegistroVotacao` foram adicionados em f61081a1be1748694930 mas não parecem ser usados em nenhum lugar no sistema. Também não estão no sapl 2.5, portanto não são migrados.

Lembrando, usamos o `django-reversion` para log de alterações.

Estes campos devem mesmo estar aí?

**Comment by edwardoliveira** [comment]
Boa! Realmente esses campos foram colocados aí para eventual auditoria nos registros, mas realmente não são necessários.
