### ISSUE TITLE
Justificativa de ausência

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1801]
É necessário quando for registrar a presença dos parlamentares na Sessão Plenária ter um campo ao lado do nome do parlamentar para o registro de ausência do mesmo.

Ex: Parlamentar XXXX - Justificativa de Ausência: YYYYYYY

**Comment by matoscas** [comment]
Como a minha issue foi adicionada aqui, vou comentar. Na minha opinião, o registro da ausência não pode ser feito na tela de Presença, porque essa tela serve para registrar a presença para tora a ordem do dia, então todas as matérias que forem votadas vão considerar essa presença. A ausência deve ser incluída na tela da Votação da matéria, pois o vereador pode se ausentar da votação de determinada matéria, e não da ordem do dia inteira.
