### ISSUE TITLE
Painel Eletrônico - Ajustar data e hora

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#1810]
1) Ao iniciar o painel, o mesmo mostra a data e hora de abertura que foi previsto no cadastro. Porém, logo abaixo da logomarca da Casa, mostra somente a hora corrente. Creio que deve constar a data e a hora corrente, portanto, sugiro adicionar a data corrente à frente da hora corrente que já consta.
2) No painel do votante, do mesmo modo, constam a hora e a data que foram cadastradas na abertura. Sugiro alterar para a ordem (data e hora), como no painel principal, da abertura como sendo "previstas", e indicar também a data e hora correntes, as quais deverão prevalecer como sendo as de votação.

**Comment by VictorFabreF** [comment]
No commit 3cbdbec o ponto 1 foi corrigido. Mais mudanças serão necessárias para que se possam ser satisfeitos os requisitos em 2, portanto será criada uma nova issue e depois um novo commit referente a ela.
