### ISSUE TITLE
tipo votação - excluir tipo votação secreta

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#1817]
emenda à constituição federal eliminou o voto secreto.

**Comment by andreagudo** [comment]
Acho importante manter a votação secreta, pois há Câmaras, como a nossa, que está registrando sessões e votação antigas.

**Comment by 54adal** [comment]
A idéia foi minha, mas de fato, esqueci que os registros de acontecimentos de fatos passados devem ser fidedignos ao ocorrido na época!
Obrigado André pela lembrança!
