### ISSUE TITLE
Erro 404 Not Found

### ISSUE THREAD

**Issue by rannyel** [interlegis/sapl#1832]
Bom dia. Ao acessar a página do sapl aqui de Vitória da Conquista/BA, retorna-se o seguinte erro "404 not found nginx/1.10.3".

https://sapl.vitoriadaconquista.ba.leg.br/

Obrigado.

**Comment by edwardoliveira** [comment]
Esse erro aí é de configuração do SAPL. Vocês estão hospedados no Interlegis? Se estão instalados localmente estão fazendo via Docker?

**Comment by edwardoliveira** [comment]
Nesse tipo de erro, abra um ticket em https://suporte.interlegis.leg.br 

Reiniciamos o servidor e voltou a funcionar.
