### ISSUE TITLE
Audiência Pública

### ISSUE THREAD

**Issue by rosenocmcc** [interlegis/sapl#1839]
Na última atualização que fizemos veio o link para cadastrar audiências públicas, o que é muito bom. Só que quando fui transferir o cadastro para o formulário deu erro. Não efetuou o cadastro.

Temos mais um problema ali. Ele vincula a Audiência a uma proposição legislativa. Aqui na nossa casa efetuamos audiências públicas para o Executivo apresentar as metas fiscais. Como posso cadastrar, já que tenho que definir sempre um tipo de proposição?

Obrigado

**Comment by edwardoliveira** [comment]
Descreva o passo-a-passo para que possamos corrigir esse bug para as versões futuras do SAPL.

Audiência Pública não está disponível no 3.1. Ainda estamos trabalhando nisso. Você não deve clonar mais do master e sim usar este aqui:

`git clone -b 3.1.x --single-branch git://github.com/interlegis/sapl`

O `master` está em desenvolvimento para novas versões do SAPL a serem usadas daqui uns 6 meses. Vc ficar atualizando via master pode quebrar tua instalação do SAPL a qualquer momento. Mas vamos olhar isso assim que vc criar a issue no GH.



Essas issues não estão sendo criadas em https://www.github.com/interlegis/sapl/issues , assim NUNCA que a gente vai enxergá-las sem vir aqui, o que é contra-producente. Favor abrir essas issues no projeto correto.

**Comment by rosenocmcc** [comment]
Obrigado pela informação Edward. Para colaborar embora a previsão seja para o futuro, encampei no nosso sapl as audiências públicas. O nosso banco de dados é de dois anos, portanto são poucas audiências e isso me permitiu que eu me proponha a ser piloto de teste para ajudar no projeto que é otimo.
Hoje pelo que está disponível para mim, não é possível cadastrar as audiências porque o link apresenta um bug. 
1 - Ele não cadastra a vinculação com a matéria legislativa, isso faz com que não seja possível abrir o cadastro posteriormente.
Esses bugs não impedem o cadastro
2 - Para cada registro novo, o sistema cadastra novamente um conjunto no tipo de audiência.
3 - Sempre que é editado o formulário, altera automaticamente a data para a data atual.
4 - O campo Tema da Audiência Pública está limitado a 100 caracteres, a meu sentir seria ideal 200 caracteres, pois ali vamos especificar que tipo de audiência está ocorrendo.

**Comment by rosenocmcc** [comment]
Sugestão para melhorar
1 - Permitir que seja incluído mais de uma matéria legislativa na mesma audiência pública, pois isso é muito usual nas Câmaras do Municípios pequenos como o nosso.
2 - Criar um link que permita o acesso a Audiência pública através das matéria legislativa, como é feito para as Sessões Plenárias.
