### ISSUE TITLE
Remover filtro "lookup" desnecessário

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#184]
Para acessar a chave *k* de um dicionário **d** em um template basta escrever `d.k`. Se não existir a chave não aparece nada simplesmente (sem erros).

Por exemplo, ao invés de escrever: 
```
tipo_pk="{{item|lookup:'tipo_pk'}}">{{item|lookup:'provavel'}}
```
basta escrever: 
```
tipo_pk="{{item.tipo_pk}}">{{item.provavel}}
```

Remover o filtro `lookup` em
https://github.com/interlegis/sapl/blob/master/base/templatetags/common_tags.py#L31
e usar a notação padrão onde ele foi utilizado.

**Comment by marciomazza** [comment]
@LeandroRoberto

**Comment by LeandroRoberto** [comment]
@marciomazza, para as partes citadas, bem como em outras idênticas, a orientação foi seguida, porém mesmo assim, não é possível a remoção do filtro "lookup" pois existem chaves que não estão fixas no código como em:

https://github.com/interlegis/sapl/blob/compilacao/templates/compilacao/text_list_bloco.html#L54

entre outros pontos do código.

ps: atualmente o filtro lookup está como em:
https://github.com/interlegis/sapl/blob/compilacao/base/templatetags/common_tags.py#L31

por ter se, até então, mostrado ineficiente para múltiplas lógicas...
Caso esteja de acordo, é só fechar a issue.

**Comment by marciomazza** [comment]
+1
