### ISSUE TITLE
Painel Eletrônico

### ISSUE THREAD

**Issue by rosenocmcc** [interlegis/sapl#1840]
Começamos a utilizar o painel eletrônico em dois telões de 60 polegadas. Faço a conexão com dois chromecast. Atualizo todo o painel sem problema nenhum, inclusive nas votações. O que está me causando um transtorno é que não consigo utilizar os cronômetros a partir da máquina operadora, só consigo acionar 1 por vez através do navegador que eu conectei o chromecast com a TV. Tens alguma dica?

PS: No SAPL 3.0 eu consigo fazer o monitoramento do cronometro através da máquina operadora.

**Comment by edwardoliveira** [comment]
O cronômetro só pode ser acionado a partir da máquina operadora. Não há a possibilidade de abrir o cronômetro de outra máquina. Estamos estudando outras alternativas de cronômetro para superar essa limitação.
