### ISSUE TITLE
Pdf do resumo da sessão: Oradores Explicações Pessoais

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1843]
Lista de oradores fora de ordem. Ver #1876

**Comment by marimendes** [comment]
Você poderia me explicar melhor esse "fora de ordem"? Eu testei aqui e a ordem parecia certa.

**Comment by andreagudo** [comment]
![captura de tela de 2018-04-10 13-36-53](https://user-images.githubusercontent.com/19169882/38570443-4093baae-3cc4-11e8-8e11-c8fdc09902d1.png)

**Comment by marimendes** [comment]
Não consegui replicar esse erro aqui, mas darei uma olhada! Obrigada.

**Comment by andreagudo** [comment]
https://sapl3.agudo.rs.leg.br/relatorios/1793/sessao-plenaria

**Comment by andreagudo** [comment]
Não ocorre tal erro em todas as sessões. Será um problema gerado em eventual edição da ordem?

**Comment by edwardoliveira** [comment]
Resolvido pelo commit aab8ddffb51896
