### ISSUE TITLE
Migração: texto de requerimentos criados sem formatação

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1846]
Os textos de requerimentos criados no editor SDE migraram sem formatação nem brasão.

**Comment by VictorFabreF** [comment]
Boa tarde,

Você pode por favor colocar a URL de um deles para olharmos?

**Comment by andreagudo** [comment]
Está assim: https://sapl3.agudo.rs.leg.br/media/sapl/public/materialegislativa/2017/7142/7142_texto_integral.xml
Deveria ser assim: https://sapl.agudo.rs.leg.br/sapl_documentos/materia/7142_texto_integral

**Comment by andreagudo** [comment]
Permanece o problema.

**Comment by marciomazza** [comment]
Temos de fazer uma release nova para que a correção apareça.
Assim que fizermos avisamos aqui pra vc testar.

**Comment by andreagudo** [comment]
Pois está corrigido.
