### ISSUE TITLE
Migração: usuário secretaria não migrado como autor

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1849]
Embora migrado e conseguindo se logar, o usuário secretaria não acessa proposições. A resposta está na figura abaixo.
![captura de tela de 2018-04-10 16-49-48](https://user-images.githubusercontent.com/19169882/38580246-d1f6596e-3cdf-11e8-928c-0dc47f4aee82.png)
 Todas as proposições, porém, são desse usuário.

**Comment by edwardoliveira** [comment]
@tapumar Vimos aqui e isso pode ser um problema de migração e não de código. O model `Autor` deve estar ligado a um `User` e nesse caso de `Secretaria` ele não está. Então não precisa do PR nesse caso. :+1: 

@andreagudo Esse vínculo pode ser feito na tela Tabelas Auxiliares -> Autor. Daí Clicar no nome da secretária (ou comissão ou parlamentar) e clicar em em Editar e vincular a Secretaria um usuário existente. Mas vamos ver por aqui se esse vínculo automático poderia ser feito via migração. /cc @marciomazza

**Comment by andreagudo** [comment]
Ok, @edwardoliveira , consegui vincular e ter acesso às proposições.

**Comment by marciomazza** [comment]
Estou reabrindo para investigar pq o vínculo entre usuário e autor não está acontecendo.
