### ISSUE TITLE
Relatórios - Fim de Prazo de Tramitações

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1850]
Indicar no relatório os critérios selecionados na pequisa.
![captura de tela de 2018-04-11 09-11-38](https://user-images.githubusercontent.com/19169882/38615852-7f98540e-3d68-11e8-8f85-2ad9bb0bbea8.png)

**Comment by edwardoliveira** [comment]
Estive vendo isso aqui, mas a biblioteca que usamos para pesquisar parece não ter essa opção. Vamos continuar procurando.

**Comment by edwardoliveira** [comment]
Estivemos discutindo isso e infelizmente não tem como atender esse pedido. Fica para quando substituirmos a interface toda do SAPL no futuro.
