### ISSUE TITLE
Matérias Legislativas e normas jurídicas - pesquisa textual não funciona

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1851]
Não funciona para qualquer dos tipo de documento selecionado. A resposta é sempre "Nenhum texto encontrado!". Para documentos acessórios (arquivos em pdf, pdf/a e odt) pesquisei por "parecer". Para matérias legislativas (arquivos em pdf, pdf/a e xml) pesquisei "lei" e "indicação". Para normas (arquivos em pdf, pdf/a e html) pesquisei por "lei".

**Comment by tapumar** [comment]
Bom dia @andreagudo. Tem certeza que existem arquivos com essas palavras pesquisadas? Estou testando aqui a pesquisa para Materias Legislativas e Normas Juridicas, no formato pdf e odt, e parece estar funcionando.

**Comment by andreagudo** [comment]
Bem, há a seguinte matéria:
https://sapl3.agudo.rs.leg.br/media/sapl/public/materialegislativa/2017/7319/7319_texto_integral.xml
Fiz a pequisa abaixo:
![captura de tela de 2018-04-11 10-13-56](https://user-images.githubusercontent.com/19169882/38618851-208e8416-3d71-11e8-926f-204800591de1.png)

**Comment by andreagudo** [comment]
Há a matéria
https://sapl3.agudo.rs.leg.br/materia/8449

![captura de tela de 2018-04-11 10-17-31](https://user-images.githubusercontent.com/19169882/38619013-943ea9d6-3d71-11e8-8263-6750a2e02bcc.png)
