### ISSUE TITLE
Pauta da Sessão

### ISSUE THREAD

**Issue by ivanlucio10** [interlegis/sapl#1857]
Ao apresentar a pauta da sessão, mostra apenas os campos para busca, quando o correto é mostrar os dados de identificação da ultima sessão com link para acesso a essa sessão.
Também falta complementar a pauta com apenas as "matérias do expediente e da ordem do dia" que devem ser mostradas apos clicar no link referido. Hoje a pesquisa da pauta remete para sessão plenária o que é incorreto.

**Comment by edwardoliveira** [comment]
As mudanças que vc está solicitando são para um novo relatório, e fica complicado alterar este relatório  que já vem sendo utilizado há 16 anos por outras casas legislativas. Portanto, não vamos modificar o relatório que já existe, mas vc pode abrir uma nova issue para adicionar mais um relatório com as informações resumidas e links, se assim desejar, que faremos nas versões futuras (final de 2018, início de 2019). Ou, como se trata de software livre, pode adicionar vc mesmo e submeter um Pull Request via Github que daí podemos integrar na versão 3.2 ou até 3.1 do SAPL.

**Comment by morale** [comment]
Não é uma ideia, mas sim uma necessidade que funcionava na 2.5 e não está contemplada na 3.1.
