### ISSUE TITLE
Tabelas Auxiliares/Modulo Sessão Plenária/Ordenação do Resumo

### ISSUE THREAD

**Issue by ivanlucio10** [interlegis/sapl#1859]
Em Ordenação do Resumo: Caso o usuário deseje mostrar apenas 4 itens (mesa diretora, lista de presença, matérias do expediente e ordem do dia), o sistema apresenta erro, não permitindo mostrar apenas a quantidade de itens desejados.

**Comment by edwardoliveira** [comment]
Atualmente não existe a funcionalidade de limitar os itens mostrados no resumo. Mas vamos implementar isso para a versão 3.2 que deve sair por volta de Outubro/Novembro de 2018.

**Comment by ivanlucio10** [comment]
Então na pauta da sessão deixar mostrando apenas matérias do expediente e matérias ordem do dia, pois como esta fica muito confuso. isso temos urgência!

**Comment by marimendes** [comment]
Esse problema foi resolvido no commit eac2c71. Por tanto estarei fechando a issue.
