### ISSUE TITLE
Votação Nominal: falta mostrar o placar do resultado

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#1863]
Na votação nominal aparece os votos dos parlamentares, mas deveria ao final mostrar também um placar com as quantidades totais de votos sim/não/abstenção, parecido com o que é mostrado na simbólica.

**Comment by edwardoliveira** [comment]
Isso já é mostrado, conforme visto na imagem abaixo para votação nominal. Não seria a resolução de tela da TV aí que está "comendo" essa parte?

![image](https://user-images.githubusercontent.com/9326037/38733149-3d7e552e-3ef7-11e8-8a53-f886bc4f5983.png)
