### ISSUE TITLE
Norma Jurídica - preenche, no formulário de adição, dados de referência a uma Matéria Legislativa, indevidamente.

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#1868]
Ao incluir uma norma jurídica, a função está preenchendo indevidamente os dados de uma matéria legislativa de modo aleatório (não houve seleção/informação) para referenciar uma matéria legislativa.

**Comment by marimendes** [comment]
Os dados da matéria que você se refere são: matéria, ano da matéria e número?

**Comment by edwardoliveira** [comment]
Vc está se referindo à imagem abaixo? Se for então não se trata de dados aleatórios. O sistema recupera o último número daquele tipo de matéria legislativa. E mesmo assim, ele só dispara quando se seleciona o ano e tipo da norma.


![image](https://user-images.githubusercontent.com/9326037/38877983-4b130062-4236-11e8-91ef-bdab60116560.png)
