### ISSUE TITLE
Adicionar Sessão Plenária: Sessão Legislativa atual

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1871]
Ao adicionar uma Sessão Plenária, que venha preenchida a Sessão Legislativa atual, como ocorre com a legislatura.
![captura de tela de 2018-04-16 07-47-30](https://user-images.githubusercontent.com/19169882/38805032-c6ea23c4-414a-11e8-9b66-2241c5fd1c32.png)

**Comment by tapumar** [comment]
Bom dia @andreagudo. Já foi corrigido na issue #1858
