### ISSUE TITLE
Mesa da Sessão Plenária: membros em ordem alfabética

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1874]
Apresentar em ordem alfabética a lista de parlamentares para composição da Mesa da Sessão Plenária.
![captura de tela de 2018-04-16 08-12-27](https://user-images.githubusercontent.com/19169882/38806055-769e8b0e-414e-11e8-9369-ec7ffed8e8ce.png)

**Comment by andreagudo** [comment]
O ideal é que a lista para escolha dos membros da mesa esteja em ordem de nome parlamentar, pois é o mais usado.

**Comment by sconetto** [comment]
@edwardoliveira 
Eu fiz uns testes locais e está acontecendo o seguinte:
Na primeira vez que o sistema carrega a página está mostrando o nome completo do parlamentar, após fazer uma inserção ou deleção mostra o nome do parlamentar (acredito que o nome que ele é conhecido), se você recarregar a página ele volta a mostrar por nome completo, temos que investigar.
Agora dos parlamentares inativos eu não consegui replicar @andreagudo @edwardoliveira.

**Comment by andreagudo** [comment]
Os inativos aparecem antes de recarregar a página, no caso, Márcio e João.
![captura de tela de 2018-04-20 16-01-35](https://user-images.githubusercontent.com/19169882/39068874-3e9c0ca4-44b4-11e8-9879-e95dc2da2f13.png)
