### ISSUE TITLE
Sessão Plenária: erro ao adicionar várias matérias na Ordem do Dia

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1882]
Usando a opção "Adicionar várias matérias" na Ordem do Dia, o sistema responde o seguinte, apesar das matérias terem sido incluídas corretamente.
![captura de tela de 2018-04-16 10-37-56](https://user-images.githubusercontent.com/19169882/38812407-95e9c4d8-4162-11e8-948f-0a9da933f5e8.png)

**Comment by VictorFabreF** [comment]
Bom dia, 
Esta tela está aparecendo porque após inserir as matérias em Ordem do Dia para votação a pesquisa é refeita e como as matérias já foram inseridas ela retorna com nenhum resultado. Uma mensagem de sucesso agora será apresentada ao operador quando as matérias forem inseridas. Como na imagem abaixo.

![image](https://user-images.githubusercontent.com/19825887/38819752-9b495e24-4172-11e8-8360-18d6735283a1.png)
