### ISSUE TITLE
Sessão Plenária: numeração automática em Oradores do Expediente

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1895]
Implementar numeração automática na ordem dos Oradores do Expediente para evitar falha do operador. Isso ocorreu no caso abaixo, já que o sistema está aceitando repetição do número de ordem.
https://sapl3.agudo.rs.leg.br/sessao/1854/oradorexpediente

**Comment by tapumar** [comment]
Para evitar falha do operador foi colocada uma verificação da ordem, impedindo a criação de numeros repetidos

**Comment by andreagudo** [comment]
Houve reversão desse problema.
![captura de tela de 2018-06-05 11-08-50](https://user-images.githubusercontent.com/19169882/40981277-f4e00748-68b0-11e8-9da3-b01520f678b8.png)
