### ISSUE TITLE
Sessão Plenária: ordem de membros da mesa

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1896]
A ordem dos membros da mesa da sessão plenária está investida na tela de composição e no pdf do resumo.
https://sapl3.agudo.rs.leg.br/sessao/1852/mesa

**Comment by VictorFabreF** [comment]
Bom dia, 
A ordem nesta tela se dá pela ordem inversa de inclusão. Portanto o primeiro a ser incluído, será o mais baixo na tela.
Na tela abaixo, a ordem coincide com a do PDF do resumo.
https://sapl3.agudo.rs.leg.br/sessao/1834/mesa
Para obter a ordem desejada inclua primeiro o Secretário, depois o Vice-Presidente e por último o Presidente.
