### ISSUE TITLE
Sessão Plenária: ordem alfabética em listas de presença

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1898]
Nas listas de presença da sessão plenária e da ordem do dia a ordem alfabética não está obedecida plenamente.
https://sapl3.agudo.rs.leg.br/sessao/1855/presenca
https://sapl3.agudo.rs.leg.br/sessao/1855/presencaordemdia

![captura de tela de 2018-04-18 08-18-27](https://user-images.githubusercontent.com/19169882/38928994-52ef41e6-42e1-11e8-95da-cef522ca1b43.png)

**Comment by andreagudo** [comment]
Permanece o problema. Em https://sapl3.agudo.rs.leg.br/sessao/1857/resumo tal problema é claro, pois Léo está presente.

**Comment by andreagudo** [comment]
Tal problema ocorre também na lista de parlamentares por legislatura:
https://sapl3.agudo.rs.leg.br/parlamentar/?pk=5
![captura de tela de 2018-05-15 16-24-05](https://user-images.githubusercontent.com/19169882/40078921-7cea8fd8-585c-11e8-8f69-69b6c4b6bdb6.png)

https://sapl3.agudo.rs.leg.br/parlamentar/?pk=7

**Comment by sconetto** [comment]
@andreagudo pode por favor indicar novamente os erros, se eles persistem e atualizar os links?

**Comment by andreagudo** [comment]
Sim, persistem os erros de ordem alfabética.
https://sapl.agudo.rs.leg.br/sessao/1857/presenca
https://sapl.agudo.rs.leg.br/sessao/1857/presencaordemdia
https://sapl.agudo.rs.leg.br/parlamentar/?pk=5

**Comment by sconetto** [comment]
@edwardoliveira eu fiz um outro fix na branch 1898-fix-ordem-parlamentares, nos meus testes resolveu o problema, poderia fazer o teste e avaliar a correção?

**Comment by edwardoliveira** [comment]
Este bug é um problema da distribuição Linux onde rodam os SAPL. Esta versão em particular, Alpine Linux, não tem suporte a internacionalização, e nem parece que vai ter tão cedo.


Assim, não somente o Python/Django como o próprio banco de dados tem que utilizar a codificação norte-americana. Nos meus últimos testes nessa issue eu verifiquei que o erro ocorre até quando se usa Python puro, totalmente fora do SAPL. E refazer as imagens em outra distro não é algo simples e rápido, principalmente porque os gerenciadores de pacotes e libs nativas do Linux mudam muito.

**Comment by marimendes** [comment]
@andreagudo você sabe me informar se esse erro ainda persiste? fiz novos testes aqui no meu dumb e está tudo certo.

**Comment by edwardoliveira** [comment]
Acredito que o erro persiste @marimendes. Vc testou na tua máquina local, não? O Ubuntu/Debian não tem esse problema, mas distribuição Linux que usamos para o Docker (Alpine Linux) não tem suporte a internacionalização. E nem tem previsão de quando vão suportar isso. Minha ideia é migrar para o debian-stretch, mas isso implica em modificar porções do Dockerfile para instalar as libs o que pode ser uma boa dor de cabeça, mas podemos tentar fazer isso. :)

**Comment by andreagudo** [comment]
Issue resolvida.
