### ISSUE TITLE
Rever django-admin-bootstrapped

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#1902]
(Teoricamente isso é necessário para #1827 !)

O projeto django-admin-bootstrapped suporta até Django 1.8 e parece abandonado.
Existem muitos forks e pelo menos um deles suporta até Django 1.11: https://github.com/rubgombar1/django-admin-bootstrapped

Avaliar o que fazer:
* trocar para um fork?
* trocar para outro projeto que estilize o admin?
* ... ?

**Comment by VictorFabreF** [comment]
Resolvido no commit cd20072
