### ISSUE TITLE
Documento administrativo: edição de dados

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1904]
Ao editar os dados de um documento administrativo existente, responde que o documento já existe, como se estivesse sendo incluído um novo. Tentei apenas inserir dados que estavam em branco, número e ano do protocolo. Dá o mesmo resultado se não mexer em nenhum campo.
https://sapl3.agudo.rs.leg.br/docadm/540/edit
![captura de tela de 2018-04-19 08-38-55](https://user-images.githubusercontent.com/19169882/38989515-8691162e-43ad-11e8-82bc-d5fa8bc23bbd.png)

**Comment by edwardoliveira** [comment]
Feito. Estará disponível na próxima versão.
