### ISSUE TITLE
Ajustar croping para fotografias de parlamentares

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#1905]
Alguns thumbnails estão cortando demais as fotos.
Parece que precisamos obedecer o _aspect ratio_ da foto original.

![screenshot from 2018-04-19 15-53-11](https://user-images.githubusercontent.com/579665/39012085-d17adc42-43e9-11e8-8b23-639e70750187.png)

**Comment by marciomazza** [comment]
@LeandroRoberto Alguma dica?

**Comment by LeandroRoberto** [comment]
ao criar um parlamentar, o cropping cria uma caixa centralizada na imagem... para escolher o melhor ajuste, o usuário deve clicar em editar e ajustar manualmente... tradicionalmente, como por exemplo, todas as redes sociais disponibilizam uma ferramenta de cropping para enquadrar as fotos de perfil. Neste exemplo, contudo, são soluções mais sofisticadas que conseguem disponibilizar o corte diretamente no upload com preview... no nosso caso, de forma mais simples, mas para já contar com o cropping, este só pode ser feito na edição.
Pode parecer irrelevante no momento para o sapl 3.1... mas com certeza em breve, poderemos ter soluções como essa: https://www.jatai.go.leg.br/parlamentar que fica inviável sem cropping.

![image](https://user-images.githubusercontent.com/9630623/39012948-4b0d795a-43ec-11e8-862a-b94ad94058b5.png)
