### ISSUE TITLE
Sessão Plenária: ordem de parlamentares para incluir em Explicações Pessoais

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1908]
A ordem de parlamentares está estranha: https://sapl3.agudo.rs.leg.br/sessao/1854/orador/create
![captura de tela de 2018-04-23 08-07-46](https://user-images.githubusercontent.com/19169882/39123271-b9f7979a-46cd-11e8-948a-1f2e00d85b1a.png)

**Comment by sconetto** [comment]
@andreagudo 
Essa ordenação é dada pelo nome completo do parlamentar, mas como na criação ele mostra o nome como o parlamentar é conhecido a ordem pode parecer estranha.
