### ISSUE TITLE
Radiobuttons e checkboxes incorretos no bootstrap e crispy-forms

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#191]
A mudança de Foundation (:shit:) para Bootstrap (:trophy:) quebrou __todos__ os radio buttons das telas do SAPL. :boom: Na quinta e sexta, comecei a investigar o que poderia ser. Se remover a class CSS "radio" dos input text -- via Chrome DevTools --, as options são renderizadas normalmente. Isto parece implicar um problema no CSS. :unamused: **MAS** eu encontrei esta issue aqui: https://github.com/maraujop/django-crispy-forms/issues/337 que pode indicar que o problema é mais em baixo...

**Comment by LeandroRoberto** [comment]
O problema é um conflito entre o tema drunken-parrot e a escrita do crispy_forms... deve se customizar a renderização do crispy_forms para que se adeque ao drunken-parrot

**Comment by marciomazza** [comment]
Ou ajustar o css que o drunken parrot alterou. Isso seis feito em static/styles/app.scss

**Comment by edwardoliveira** [comment]
@marciomazza @LeandroRoberto Pergunta sincera: vale a pena continuar usando o drunken-parrot? Fora o aspecto estético, não vi maiores vantagens no seu uso. Pelo visto até agora, suas desvantagens (choque com crispy_forms, necessidade explícita de JavaScript) ofuscam suas vantagens (que seriam quais?)

**Comment by marciomazza** [comment]
O drunken-parrot é um tema para bootstrap.

Temos algumas opções em relação a temas:
 * Não usar tema nenhum: somente o bootstrap cru.
 * Usar esse tema adaptando quando necessário
 * Usar um outro tema

**Comment by eribeiro** [comment]
Entendi.

**Comment by LeandroRoberto** [comment]
imaginava que um tema não poderia exigir código específico como acontece nos radios e checkbox...

**Comment by marciomazza** [comment]
Tb imaginava

**Comment by marciomazza** [comment]
Fix um hack imediato para deixar de esconder radios e checkboxes: 237f0d8

Vou deixar essa issue aberta para darmos uma solução definitiva depois. Não vou trabalhar nela agora, devido a outras prioridades.

**Comment by LeandroRoberto** [comment]
Resolvido
