### ISSUE TITLE
Sessão Plenária: formatação em Expedientes Diversos gera erro pdf

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1911]
Quando se cola nos Expedientes Diversos texto com formatação e se tenta gerar o pdf, mostra Server Error (500).
https://sapl3.agudo.rs.leg.br/sessao/1854/resumo

 O ideal seria colar em texto puro. No 2.5 há tal possibilidade, como mostra a figura 
![captura de tela de 2018-04-23 15-27-53](https://user-images.githubusercontent.com/19169882/39145734-0623a1d0-470b-11e8-867b-a7a35e940bda.png)
abaixo

**Comment by edwardoliveira** [comment]
No widget de texto rico que a gente usa a retirada de formatação de texto é um pouco diferente. Vc deve colar o texto, selecionar ele todo e daí selecionar a opção Format->'Clear formatting'.

![image](https://user-images.githubusercontent.com/9326037/39194279-bca45a64-47b3-11e8-86f7-f37bb3c87d3b.png)
