### ISSUE TITLE
Sessão Plenária: lista presenças Ordem do Dia X sessão

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1912]
Está sendo possível registrar presenças na Ordem do Dia mesmo sem registro de presenças à sessão. Verificar como funciona no 2.5 e se isso é conveniente.

**Comment by tapumar** [comment]
Oi @andreagudo, conversando com o @edwardoliveira, vimos que em algumas casas legislativas um parlamentar pode ter presença na ordem do dia sem ter a presença no expediente(sessão), então não é conveniente implementarmos essa modificação.
