### ISSUE TITLE
Votação na Ordem do Dia!!

### ISSUE THREAD

**Issue by Neybson** [interlegis/sapl#1913]
Estava registrando a votação das matérias na Ordem do Dia, utilizando o Painel Eletrônico e recorrentemente o computador ficou travando, e no meio de um registro de votações, cujo mesmo estava sendo feito por mim como operador e não pelos Vereadores, o sistema travou em meu computador e quando reiniciei a máquina ele não mais entrou naquela Ordem do Dia, onde aparece o seguinte erro: Server Error (500). Mas o pior é que não consigo mais registrar nenhuma votação nas sessões que ocorreram depois, pois o sistema retorna dizendo que já existe uma matéria aberta pra votação.

**Comment by edwardoliveira** [comment]
Quase certeza que foram criados mais de um RegistroVotacao para essa sessão plenária (deve existir somente um). Isso é uma inconsistência de dados que ainda não conseguimos identificar exatamente porque ocorre. Se o teu sistema não está hospedado no Interlegis vc terá que acessar o BD (via pgAdmin3, por exemplo) e deletar os registros duplicados que estarão na tabela sessao_registrovotacao. Caso o SAPL esteja hospedado no Interlegis então abra um ticket em https://suporte.interlegis.leg.br para que possamos realizar esse procedimento de remoção.

**Comment by Neybson** [comment]
Entendi! Edward meu sistema não está hospedado no Interlegis, vc teria algum script para que eu possa realizar isso: "acessar o BD (via pgAdmin3, por exemplo) e deletar os registros duplicados que estarão na tabela sessao_registrovotacao."?

**Comment by edwardoliveira** [comment]
Não tenho script nenhum. O pgAdmin é uma GUI, mas você poderia fazer via script `.sql` e submeter via `psql`. Mas tome cuidado porque vc deve pesquisar exatamente quais registros devem ser apagados e depois apagar por um desses dois modos **com extremo cuidado**.

**Comment by edwardoliveira** [comment]
Na próxima versão o SAPL não mais dará erro caso encontre registros de votação duplicados e pegará o último registro inserido sempre. Isso deve mitigar o problema, mas não resolver as inconsistências.

**Comment by edwardoliveira** [comment]
A nova versão do SAPL tenta evitar que ocorra o erro ao existirem dados duplicados. Ele não previne a criação desses dados ainda. Veja se funciona assim.

**Comment by Neybson** [comment]
Eu fiz a atualização, mas ainda contém o erro! Não estou conseguindo resolver!

**Comment by VictorFabreF** [comment]
Boa tarde,
Você teria como fazer um dump do seu banco e disponibilizar via dropbox, onedrive ou semelhante?

**Comment by Neybson** [comment]
Vou tentar fazer o dump, pq antes em zope eu sabia, mas como a plataforma mudou eu tenho que aprender ainda, tem como me ajudar nisso?

**Comment by VictorFabreF** [comment]
Boa tarde,
Hoje de manhã houve uma mudança que provavelmente resolverá seu problema. Por favor atualize seu sistema e verifique se o problema foi corrigido. Caso não tenha sido, nos avise que te ajudaremos a fazer o dump

**Comment by Neybson** [comment]
Fiz a atualização da versão 3.1.78, mas não corrigiu!!

**Comment by Neybson** [comment]
Fiz a atualização para a versão 3.1.79 e resolveu!!

**Comment by edwardoliveira** [comment]
Não. Ela não resolveu, apenas contornou o problema. Ainda resta saber porque alguns registros estão sendo gerados em duplicata e eliminá-los do BD, mas isso foge do escopo dessa issue aqui.
