### ISSUE TITLE
Normas jurídicas: relação de normas relacionadas na tela de adicionar

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1918]
Como vê-se abaixo, as normas relacionadas estão registradas:
https://sapl3.agudo.rs.leg.br/norma/3743
Mas a lista de normas relacionadas talvez devesse a aparecer na tela abaixo:
https://sapl3.agudo.rs.leg.br/norma/3743/normarelacionada

**Comment by VictorFabreF** [comment]
Bom dia, 
Analisando o sistema, percebemos que ao clicar na aba "Normas Relacionadas" são mostradas apenas as normas relacionadas que a norma altera e não as que alteram ela. Mas no campo "Relacionamentos" são mostradas todas as normas como era no SAPL 2.5. A referida aba é necessária para se adicionar normas que a norma irá alterar, mas não acrescenta nenhuma nova informação para o usuário não logado.
Desta forma pensamos em alterar o nome da aba para algo como "Alterações em outras normas" e esconder esta aba para o usuário não logado, além de colocar o nome "Normas Relacionadas" no lugar de "Relacionamentos". O que acha?
@LeandroRoberto,  quando se usa compilação é diferente? O que você acha da solução proposta?

**Comment by LeandroRoberto** [comment]
acho coerente esconder "Normas Relacionadas" para usuários anônimos e com isto termos apenas na telas de detalhes...
quanto a tela detalhes, não sei como é no do 2.5 e nem se o que tenho hoje no 3.0 é o oficial desta versão
mas na minha instancia esses relacionamentos se chamam "Vinculação Ativa" e "Vinculação Passiva"
veja este exemplo:
http://sapl.camarajatai.go.gov.br/sapl/consultas/norma_juridica/norma_juridica_mostrar_proc?cod_norma=2572
![image](https://user-images.githubusercontent.com/9630623/39640650-0b76622c-4fa2-11e8-9247-5b6547577916.png)

Neste exemplo é possível ver uma norma pode ser alterada e alteradora ao mesmo tempo...
aí está a 3066 que tem um Vínculo Ativo com a 2805 pois age sobre ela... além disso tem várias outros Vínculos passivos, que são outras leis agindo sobre a 3066.

**Comment by VictorFabreF** [comment]
Muito obrigado, Leandro!

**Comment by VictorFabreF** [comment]
Fechado em 605165f8caff02112a140dec4ee650a515759a11

**Comment by andreagudo** [comment]
O usuário operador agora não tem onde incluir normas relacionadas.
