### ISSUE TITLE
Superuser (admin) sem acesso à Administração de Usuários

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1919]
Tal opção sequer aparece no menu Sistema.
![captura de tela de 2018-05-02 15-33-45](https://user-images.githubusercontent.com/19169882/39542259-731b4468-4e1e-11e8-903a-4a95f901ef07.png)

**Comment by marciomazza** [comment]
@andreagudo Qual usuário vc está usando?
Nös estamos limitando o número de usuários superuser e provavelmente seu usuário não foi migrado com esse perfil.

**Comment by andreagudo** [comment]
São dois usuários admin, nenhum acessando administração de usuários: sapladm, cm_agu.

**Comment by marciomazza** [comment]
Dei permissão de superusuário para ambos. Teste, por favor. @andreagudo

**Comment by andreagudo** [comment]
Funcionou. Mas esses usuários serão migrados com tal permissão?

**Comment by marciomazza** [comment]
Sim... Se ao refazermos a migração vc perceber qualquer problema me avise diretamente.
Eu sugiro que vc escolha até 2 usuários apenas para serem administradores de usuários e me avise diretamente quais são.

**Comment by andreagudo** [comment]
Ok. Os administradores de usuários que havia indicado são os únicos.
