### ISSUE TITLE
Tabelas Auxiliares: ordem das coligações

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1921]
Definir a ordem da coligações por legislatura em https://sapl3.agudo.rs.leg.br/sistema/coligacao/?page=1

**Comment by edwardoliveira** [comment]
Tá mandando pra essa tela aqui:

![image](https://user-images.githubusercontent.com/9326037/39577594-27e1d76a-4eb8-11e8-91e8-6bd45f14dcdb.png)

**Comment by andreagudo** [comment]
É que precisa estar logado. Ver se dá em https://sapl3.agudo.rs.leg.br/sistema/coligacao/
![captura de tela de 2018-05-03 10-11-41](https://user-images.githubusercontent.com/19169882/39578433-8a180cae-4eba-11e8-8c53-8460f3d4ab47.png)
