### ISSUE TITLE
Teclas de votação

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#1928]
Sugiro criar teclas no teclado para a votação: V - Abrir a tela de votação; S- Sim; N- Não e A- Abstenção. 

Facilitando a votação pelo TECLADO

**Comment by paulot12** [comment]
Já está disponível na atualização geral?

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by tapumar** [comment]
Amanhã já deve estar disponível, na versão 3.1.132

**Comment by paulot12** [comment]
Ok! Obrigado!

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
