### ISSUE TITLE
Ordenar proposições não recebidas por qualquer campo do cabeçalho

### ISSUE THREAD

**Issue by cristian-longhi** [interlegis/sapl#1934]
Na tela do operador de consulta às proposições não recebidas,

![visao operador](https://user-images.githubusercontent.com/22030378/40062199-3c035098-584a-11e8-9ea9-a472dce15bde.png)

 seria útil que o cabeçalho possibilitasse a ordenação ascendente/descendente por qualquer um dos campos, conforme escolha do usuário. É a mesma funcionalidade na visão das proposições pelo autor:

![visao autor](https://user-images.githubusercontent.com/22030378/40062085-e72132b6-5849-11e8-9a71-73690ea85fcd.png)

Tal recurso, aliado ao recebimento de proposições sem recibo, agilizará muito os processos internos, sobretudo nas Câmaras com grande volume de matérias legislativas a cada sessão.

**Comment by rosenocmcc** [comment]
Muito importante essa atualização, pois isso dificulta enormemente o manejo das proposições, pois as mesmas são carregadas na página de forma desordenada.
