### ISSUE TITLE
Bancadas Parlamentares

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1936]
Tem a possibilidade de criar as Bancadas Parlamentares.
Tem a possibilidade de criar os cargos para as Bancadas Parlamentares.
Agora é necessário criar a possibilidade de ligar o parlamentar a uma bancada e a possibilidade de informar o cargo.

**Comment by DtiLegBG** [comment]
#1935

**Comment by andreagudo** [comment]
Considerar a issue #561

**Comment by 54adal** [comment]
#1392

**Comment by edwardoliveira** [comment]
Relaciona-se a #1798 #561 #1798 #1392

**Comment by rjoao** [comment]
Issue duplicada #1390.
