### ISSUE TITLE
Data de filiação é preenchida automaticamente ao editar filiação partidária

### ISSUE THREAD

**Issue by matoscas** [interlegis/sapl#1939]
olá. Há um problema na tela de Filiação Partidária. Ao se editar uma filiação partidária já existente, o campo Data de Filiação é automaticamente alterado para a data atual, substituindo a data digitada anteriormente.

**Comment by VictorFabreF** [comment]
Bom dia,
Tentei replicar o erro localmente com diversos parlamentares e não consegui. 
Você poderia mandar capturas de tela mostrando isso ocorrer? O ideal seria uma captura da tela da listagem das filiações (antes da edição) e uma captura da tela de edição.
Se possível mandar também os links das telas em que o erro for detectado.
Muito obrigado.

**Comment by DtiLegBG** [comment]
Para mim, esse e outros comportamentos estranhos acontecem utilizando o chrome. Fiz o teste aqui e consegui replicar o problema utilizando o chrome, usando o firefox não acontece.

**Comment by DtiLegBG** [comment]
Usando o firefox, editando a filiação, por vezes traz a data atual e por vezes traz a data gravada. Se limpo o cache do navegador, na primeira vez que edito, traz a data gravada, na segunda já é trazida a data atual.

**Comment by sconetto** [comment]
@DtiLegBG aqui no meu firefox não consegui replicar também não, fui nas opções de Network do firefox e desativei o cache e ative, em todas ele trazia a data gravada, e em casos de novas filiações ele trás em branco. Será que é algum auto complete do navegador? Tem alguma suspeita?

**Comment by DtiLegBG** [comment]
Testei agora com o Chrome,  mesmo limpando o cache, e traz a data atual. Posso gravar um vídeo se ajudar. Nem imagino o que pode ser

**Comment by sconetto** [comment]
vou averiguar se tem algum javascript de preenchimento de data mas tá muito estranho.

**Comment by VictorFabreF** [comment]
@DtiLegBG, foi feito um fix para essa issue. Você poderia por favor testar e ver se o problema persiste?

**Comment by edwardoliveira** [comment]
@DtiLegBG Vc poderia nos fornecer um usuário e senha (via Telegram) para que possamos reproduzir esse erro aí no sistema de vocês?

PS: não iremos alterar nada, só verificar a mudança de valor do campo pq não conseguimos reproduzir aqui.

**Comment by DtiLegBG** [comment]
para mim esse e outros comportamentos estranhos que por vezes ocorrem se resolvem reiniciando o supervisor.

**Comment by matoscas** [comment]
estou meio enrolado aqui, vou fazer mais testes depois, se persistir o erro, reporto aqui.

**Comment by edwardoliveira** [comment]
Encontramos o erro. Estamos fazendo um patch para consertar todos esses casos.
