### ISSUE TITLE
Implementar tela de Protocolo -> Documento

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#194]
Ditto.

**Comment by marciomazza** [comment]
Revisado. Com alteração. Vide 719cc87 e cb98a8b.

Vamos procurar usar as CBV adequadas sempre que possível.
Nesse caso troquei uma combinação de `FormMixin, GenericView` e algum código em `get` em `post` por uma `CreateView` com apenas um `get_initial` (que era o que havia de diferente mesmo).
