### ISSUE TITLE
Tabela reversion_version e reversion_revision ficando gigantes

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1940]

**Comment by LeandroRoberto** [comment]
Não acho necessário impl algo para essa issue
eu colocaria uma instrução no crontab:
uma dessas do exemplo (acho interessante a opção conjunta

   /manage.py deleterevisions --keep=3 --days=30

que significa, limpe todos os models em todas as apps. Mantenha as revisões dos últimos 30 dias  e ao menos 3 versões das revisões mais antigas

![image](https://user-images.githubusercontent.com/9630623/48166487-e0a7c880-e2cf-11e8-88db-396a078a9dd5.png)

**Comment by edwardoliveira** [comment]
Boa ideia, mas eu preferiria uns 180 dias pro caso de vir usuário reclamar que o dado "sumiu"

**Comment by LeandroJatai** [comment]
@DtiLegBG, adotou um procedimento que não precisará interferência no projeto? se não, jogaremos essa issue para sapl 3.2... se sim, fecharemos a issue, ok!?

**Comment by DtiLegBG** [comment]
eu coloquei a instrução na cron como sugerido. Obrigado
