### ISSUE TITLE
Erro na inclusão de Nome de Comissão acima de 50 caracteres

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#1946]
Ao inserir um Nome de Comissão acima de 50 caracteres aparece a mensagem Error 500. Mas na edição o sistema aceita.
grato

**Comment by VictorFabreF** [comment]
Bom dia,
Foi estipulado anteriormente que o nome deveria ser de até 50 caracteres. Caso necessário os nomes podem ser abreviados e explicados na finalidade da comissão. Iremos restringir para a edição o número de caracteres também.

**Comment by 54adal** [comment]
Positivo! Obrigado
