### ISSUE TITLE
Autor de matéria: limitar por legislatura

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1952]
Ao incluir o autor de uma matéria, todos os parlamentares autores ficam disponíveis. Deveriam ficar disponíveis apenas os da legislatura correspondente à data de apresentação da matéria.

**Comment by edwardoliveira** [comment]
Não necessariamente. Se algum usuário do SAPL precisar inserir matérias legislativas de legislaturas anteriores como fica?

**Comment by edwardoliveira** [comment]
Vc diz na tela de cadastro inicial da matéria? Ou vc está se referindo ao ato de cadastrar a matéria sem autor e daí cadastrar posteriormente o(s) autor(es) via aba de Autoria?

**Comment by andreagudo** [comment]
No cadastro da tela inicial.

**Comment by edwardoliveira** [comment]
Mas a data de apresentação pode não ter sido informada ainda.

**Comment by andreagudo** [comment]
Realmente. Então, pode ficar como está, já que há alternativa de filtro na aba Autoria.
