### ISSUE TITLE
Cabeçalho e menu desaparecem

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1961]
O cabeçalho e o menu depareceram, tanto no Firefox quanto Chromium (uso Ubuntu), o que torna impossível logar. Ocorre, aparentemente, depois de lidar com os link do Portal Modelo para o SAPL, alguns com o sufixo &iframe=1.   Ctrl + f5 não resolve. Isso já ocorria com o 2.5, mas bastava reiniciar o navegador para voltar a funcionar.
![captura de tela de 2018-06-04 15-27-40](https://user-images.githubusercontent.com/19169882/40934655-e0117cca-680b-11e8-8efe-777d4f28b6fa.png)

**Comment by andreagudo** [comment]
Realmente, acabou de ocorrer: é só navegar, no Portal Modelo, pelos links que o integram ao SAPL, que os menus deixam de aparecer no navegador.

**Comment by edwardoliveira** [comment]
Sim. Para voltar a aparecer deve-se inserir o sufixo `?iframe=1` no final da URL. Ou abrir uma outra sessão do browser.

**Comment by andreagudo** [comment]
@edwardoliveira , infelizmente as sugestões acima funcionavam com o 2.5, no 3.1 não funcionam.

**Comment by DtiLegBG** [comment]
o correto é
?iframe=0

**Comment by edwardoliveira** [comment]
Perdão, escrevi errado. É `iframe=0`. De fato, poderia ser melhor, mas não encontramos uma forma melhor de fazer. Até lá, vamos usando essa mesmo, mas se tiver uma sugestão que dê pra implementar faremos imediatamente.
