### ISSUE TITLE
Normas Jurídicas

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1964]
Está sendo possível criar no sistema normas do mesmo tipo, com a mesma data e o mesmo ano.

Se esse for um comportamento que vai ser permitido, para os relacionamentos terão que ser listadas as normas correspondentes aos dados informados para ser possível escolher a qual norma se deseja criar o vínculo.
@andreagudo @LeandroRoberto  @marciomazza

**Comment by 54adal** [comment]
Caro Rogério, você está se referindo a normas com números diferentes? Nesse caso, não vejo problema de terem sido criados com o mesmo tipo e data, correto?

**Comment by lizianem** [comment]
Prezado, trata-se de Resoluçoes de mesmo numero e ano, mas com conteudo diferente, pois foram editadas por orgaos diferentes

**Comment by DtiLegBG** [comment]
Tipo, Número, data, ano  iguais.
