### ISSUE TITLE
Relatório Presença nas Sessões

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1965]
Mesmo definindo data inicial e final neste ano, são mostrados todos os parlamentares cadastrados no sistema. Acho que seria interessante mostrar somente os parlamentares que tem mandato  no período correspondente pesquisado.
http://sapl.camarabento.rs.gov.br/sistema/relatorios/presenca?data_inicio_0=01%2F01%2F2018&data_inicio_1=05%2F06%2F2018

**Comment by morale** [comment]
A considerar o mandato do parlamentar, a função deverá verificar somente as sessões que foram realizadas no período informado e dentro do mandato. Por exemplo: Suponha que ocorreram 60 sessões no período indicado, o parlamentar esteve presente em apenas 20 sessões de um total de 30 sessões ocorridas dentro do mandato dele. Nesse caso, o percentual de presenças a ser obtido deverá ser de 20/30 e não 20/60.

**Comment by Neybson** [comment]
Inclusive para ajudar, as Sessões que importam para os fins de processos (inclusive de extinção de mandato) dizem respeito apenas às Sessões Ordinárias, assim sugiro que ao pesquisar as presenças nas Sessões o relatório também pergunte de que Sessões é a pesquisa, ou seja, uma divisão entre as Sessões Ordinárias, Extraordinárias, e as demais que existirem.

**Comment by DtiLegBG** [comment]
Resolvido !!
