### ISSUE TITLE
Edição do resultado da votação

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1966]
No 2.5 é possível editar o placar e o resultado da votação. Seria importante implementar isso no 3.1, no qual é possível apenas a anulação da votação, o que não é o caso.

**Comment by edwardoliveira** [comment]
O 2.5 não tem painel, portanto é diferente do 3.1, que tem uma série de tabelas para trabalhar a votação e exibição dos dados. O mais importante: _ao anular a votação os registros são apagados._ 

Esse comportamento é diferente de protocolo, por exemplo, pois ao anular o protocolo o registro ainda existe mas com o campo `anulado` preenchido. Desta forma, não vejo porque não poderia usar esse recurso para "editar" a votação (i.e., anular e entrar com os dados de novo), pois entendo que a necessidade de editar surge de um erro de entrada de dados, por exemplo.

**Comment by andreagudo** [comment]
Ok. Imaginava que a anulação era para outra situação (por exemplo, uma votação que, efetivamente, teve que ser refeita, mas mantendo o resultado anterior, embora inválido). Então, para corrigir, usa-se a anulação. Obrigado.
