### ISSUE TITLE
SAPL 3.1 não prevê pedido de vistas de matéria na Sessão Plenária

### ISSUE THREAD

**Issue by matoscas** [interlegis/sapl#1973]
Olá. Aqui é da Câmara de Campo Mourão-PR, sapl 3.1 hospedado no interlegis, gostaria de fazer uma sugestão, o sistema não prevê o pedido de vistas de matérias na Sessão Plenária. Em conversa com o Morale, o mesmo recomendou que fosse adicionado o tipo de resultado de votação "Matéria não votada", e colocado observação. Mas há um problema nisso, pois afinal de contas, a matéria não foi para votação. O pedido de vistas é feito durante a discussão, e não na votação, desta forma, eu, como Analista de Sistemas, considero errado abrir a votação para justificar a vista, até mesmo porque o sistema não aceita deixar os campos da votação em branco, então eu teria que registrar todos os votos no Não (mais errado ainda).

**Comment by matoscas** [comment]
Comentei com ele a possibilidade de colocar um botão de VISTAS, logo abaixo do botão de ABRIR VOTAÇÃO na lista das matérias, e ao clicar nesse botão, abriria uma tela para colocar a observação, e ao retornar para a tela da lista de matérias, a coluna RESULTADO exibiria essa observação. Deixo aqui essa observação, e espero que seja pensado algo a respeito, pois é muito comum acontecer pedido de vistas em matérias que foram para votação.

**Comment by andreagudo** [comment]
Em Agudo não temos vistas na Ordem do Dia, apenas nas comissões. De qualquer modo, nossa solução para vistas nas comissões poderia ser usada no caso da Ordem do Dia.
No SAPL de Agudo, vistas é um status da tramitação. Assim, nós "tramitaríamos" a matéria do Plenário para o próprio Plenário, com o status "Vistas", e colocamos detalhes como o autor do pedido de vistas no campo Observações. Não é uma solução ótima, mas é uma "second best" ... rsrs. O correto seria tramitar do Plenário para o gabinete do parlamentar, e... agora mesms decobri que é possível registrar um parlamentar como unidade de tramitação, o que melhoraria essa solução que damos. Vou testar por aqui.

**Comment by LeandroRoberto** [comment]
aqui em Jataí, registro não só o pedido de vistas (onde uso campo Sim (1), Não (0), Não votou(n presentes - 1)... mas registro também o pedido de prazo regimental, e aí sim tenho variações nos campos Sim e Não, além de informar no campo observações... além do tipo de votação, que no sapl só tem rejeitado e aprovado... por aqui incluí algo mais.
![image](https://user-images.githubusercontent.com/9630623/47013371-4ebbfe00-d11d-11e8-85dd-6aa9988cbf55.png)

No fim... interpreto que a votação é do item OrdemDia e não da MateriaLegislativa... claro, materia é rejeitada e/ou aprovada em sua votação... mas ela só está na sessão, e assim trata o sapl, por ser um item da OrdemDia e a este pode em tempo de discussão pode ter pedido de vista e prazo regimental e em tempo de votação, rejeitado e aprovado... 

assim além do fluxo das tramitações (fluxo este que infelizmente, ainda, não registra automaticamente o que acontece nas sessões plenárias) tenho um histórico isolado das sessões
![image](https://user-images.githubusercontent.com/9630623/47013625-3ac4cc00-d11e-11e8-8c7e-b0889be7c96b.png)

Vide exemplo completo:
http://sapl.camarajatai.go.gov.br/sapl/consultas/materia/materia_mostrar_proc?cod_materia=13352
