### ISSUE TITLE
SAPL 3.1 não prevê vereador ausente em votação de matéria na sessão plenária

### ISSUE THREAD

**Issue by matoscas** [interlegis/sapl#1974]
Olá. O sistema não prevê o caso dos vereadores que se ausentam em alguma votação de matéria durante a sessão plenária. Para registrar a ausência, tenho que ir na tela da presença, desmarcar o vereador q se ausentou, salvar, abrir novamente a matéria para votação, registrar no campo da observação que o vereador se ausentou, salvar, voltar na tela da presença, marcar novamente o vereador e salvar, para continuar a votar as matérias em que ele esteve presente. Na tela de registro de votação, tem três campos para registrar os votos: Sim, Não e Abstenções. Seria interessante incluir um campo para os Ausentes, pois ausência não é a mesma coisa que abstenção. Aí sim, no campo da observação registrar quem se ausentou. Deixo aqui o registro, e espero que seja pensado em algo para solucionar o problema. Obrigado.

**Comment by edwardoliveira** [comment]
Duplicata de #1801
