### ISSUE TITLE
Problemas na inclusão de sessão

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#198]
Estava eu verificando o funcionamento do datepicker adicionado recentemente no projeto e, para isso, abri uma tela qualquer, a tela em questão foi Sessão Plenária... como não vi nenhuma issue sobre os problemas encontrados, vou relatá-los.

1) Ao Clicar em Atividade Legislativa -> Sessão Plenária o link que abre é
http://localhost:8000/sessao/sessao-list onde possui uma tabela fora dos padrões do bootstrap e um botão [Adicionar Sessão plenária] que encaminha para o link http://localhost:8000/sessao/cadastro onde o datepicker e o jquery-mask-plugin estão funcionando... o cadastro é efetuado, porém está aceitando gravar por exemplo: 22:85 para horário de início e horário de fim

2) é de costume, ao menos meu, mudar o local de análise apenas mudando a url... o que fiz abrindo http://localhost:8000/sessao/. Este link, abre um lista diferente do primeiro, já com configurações do bootstrap para a tabela, porém o link de [Adicionar Sessão Plenária] está com url encaminhada para http://localhost:8000/sessao/create que também insere normalmente sem erros, porém o jquery-mask-plugin não está funcionando, além disso, está aceitando hora e minutos como citado acima... 

ps: o .../edit chama o mesmo formulário de .../create 
queria ver apenas ver datepicker funcionando, mas como me deparei com essas questões, achei por bem relatar aqui...

**Comment by eduardoedson** [comment]
Tinhamos feito outra tela de listagem pois a gerada automaticamente estava com muitos dados desnecessários, então fizemos outra para tentar aproximar mais do 2.5.
A tela de cadastro foi feita pois a /create estava com algum problema, que não me lembro agora.

**Comment by marciomazza** [comment]
Esses problemas foram resolvidos por #307
