### ISSUE TITLE
Edição de autor de matéria: opções indisponíveis na tela Início

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1986]
Na tela Início não é possível editar o autor da matéria legislativa, não aparecem opções.
![captura de tela de 2018-06-11 08-05-26](https://user-images.githubusercontent.com/19169882/41228434-be32b46e-6d4e-11e8-9d64-084ddc1102ee.png)

**Comment by VictorFabreF** [comment]
Bom dia,
Para editar ou acrescentar autoria é necessário ir na aba "Autoria" em "Matéria Legislativa". Estes campos só estão disponíveis na criação da matéria para se acrescentar o primeiro autor.

**Comment by andreagudo** [comment]
Ok. Então, o ideal é que tais campos não aparecessem na tela de edição.

**Comment by 54adal** [comment]
Concordo! na Versão 3.2!
