### ISSUE TITLE
Adicinar Sessão Plenária: não oferece o próximo número da sessão

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1987]
Ao Adicionar Sessão Plenária, dentro de uma mesma legislatura, mas no ano seguinte, o sistema não está oferecendo o próximo número para o tipo selecionado. No caso abaixo, o número deveria ser 164.
![captura de tela de 2018-06-11 10-39-53](https://user-images.githubusercontent.com/19169882/41235196-98b66be8-6d64-11e8-994a-6bba9a6359ec.png)

**Comment by VictorFabreF** [comment]
Boa tarde,
A sugestão de número é baseada na Sessão Legislativa dentro de uma Legislatura. Dessa forma, para continuar a numeração apenas por Legislatura, o usuário deve cadastrar manualmente o número que deseja que seja iniciado ao cadastrar a primeira  Sessão Plenária e as demais seguirão este mesmo número.
Caso deseje que este comportamento seja uma configuração do sistema, abra uma issue fazendo tal requisição para que em uma futura versão (3.2 ou superior) ela possa ser implementada.

**Comment by andreagudo** [comment]
Ok. Estranho, porém, o fato de, no exemplo acima, ser oferecido o número 10, já que ainda não havia sessão ordinária cadastrada nesse ano.
