### ISSUE TITLE
Gerar código de barras do comprovante

### ISSUE THREAD

**Issue by eduardoedson** [interlegis/sapl#199]

**Comment by eduardoedson** [comment]
#193 termina o comprovante

**Comment by edwardoliveira** [comment]
@marciomazza PR para revisão: https://github.com/interlegis/sapl/pull/202

**Comment by edwardoliveira** [comment]
@eduardoedson Implementei a geração do código de barras e do número de "autenticação" (que nada mais é que uma string contendo o tipo de processo + data + número do protocolo, kkkkkk). Está tudo no PR acima.
