### ISSUE TITLE
Edição Norma Jurídica

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#1994]
Depois dessa atualização
https://github.com/interlegis/sapl/commit/fd670f9810ddd5080fc167e88736c232f090a1d7
Editando a norma, ao salvar o sistema reclama que existe norma idêntica.

**Comment by edwardoliveira** [comment]
Corrigido no commit https://github.com/interlegis/sapl/commit/cd7fb03b4710bc2888a9cf884b5faaddcfe1a009
