### ISSUE TITLE
Server error (500) em Documentos Administrativos

### ISSUE THREAD

**Issue by filipeaas** [interlegis/sapl#1996]
Algumas casas migradas estão com esse erro, na parte de documentos administrativos, aparentemente as mesmas não possuem documentos no sapl 2.5, podendo ser a causa do erro.

**Comment by edwardoliveira** [comment]
Poderia nos fornecer um exemplo de casa onde ocorre isso? Sempre acontece na parte de documentos administrativos?

**Comment by edwardoliveira** [comment]
Este problema ainda está ocorrendo?

**Comment by edwardoliveira** [comment]
Caso esse erro ainda ocorra peça para o reiniciarem os containeres Docker dessas instâncias. Se o problema persistir mesmo após a reinicialização então reabra essa issue.
