### ISSUE TITLE
Normas Jurídicas - Mesmo tipo/Mesmo número/Datas diferentes

### ISSUE THREAD

**Issue by lizianem** [interlegis/sapl#1998]
Em Porto Alegre/RS, temos Leis e Decretos com mesmo número, mas datas diferentes. Vejam exemplos das Leis 13: 

•	**Lei Ordinária 13/1947**. AUTORIZA A ALIENAÇÃO DE UM IMÓVEL, MEDIANTE CONCORRÊNCIA PÚBLICA.
•	**Lei Ordinária 13/1938**. CRIA A CADERNETA DE REGISTRO FISCAL DE PROPRIEDADE; REGULA A CONCESSÃO DE ALVARÁS DE LICENÇA PARA LOCALIZAÇÃO DE ESTABELECIMENTOS E DETERMINA A REALIZAÇÃO DO CENSO IMOBILIÁRIO E O DOS ESTABELECIMENTOS COMERCIAIS, INDUSTRIAIS E PROFISSIONAIS, EXISTENTES NO MUNICÍPIO DE PORTO ALEGRE.
•	**Lei Ordinária 13/1924** - Norma com vigência esgotada - DECRETA E PROMULGA A REFORMA PARCIAL DOS ARTS. 6º, 36, 39 E 47 DA LEI ORGÂNICA DO MUNICÍPIO DE PORTO ALEGRE.

Não posso deixar de cadastrar as leis de 1938 e 1924 no SAPL, pois refletem o histórico do processo legislativo do Brasil da época (as décadas de 1910 a 1940 foram bem peculiares quanto a emissão de legislação, sobretudo nos governos de Getúlio Vargas). Não apenas Porto Alegre apresenta estas características, mas outras cidades brasileiras também. 

Como procedo?

**Comment by DtiLegBG** [comment]
Pois é, aqui em Bento Gonçalves/RS também temos casos assim, leis de mesmo número de anos diferentes.

Existe o controle no sapl desde a versão 2.5 para cadastro não permitir normas com mesmo Tipo, numero e ano.

Nesse caso que você apresenta em que tem tipos iguais, números iguais mas em anos diferentes o sistema vai deixar cadastrar sem problemas
