### ISSUE TITLE
Painel: não aparece a lista de parlamenteres

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1999]
Não aparecem os parlamentares presentes, nem à sessão,
![captura de tela de 2018-06-12 14-50-36](https://user-images.githubusercontent.com/19169882/41307584-febc3b66-6e4f-11e8-8a89-098b347cd953.png)
 nem à Ordem do Dia. Testado com a sessão https://sapl.agudo.rs.leg.br/sessao/2051

**Comment by marimendes** [comment]
Eu não consegui replicar o erro aqui. Como está a lista de presença dessa sessão?

**Comment by 54adal** [comment]
Andre, você marcou a presença dos parlamentares  na ordem do dia?

**Comment by 54adal** [comment]
Já vi, estão com presença!

**Comment by sconetto** [comment]
@andreagudo tem como passar para gente um usuário administrador do sistema do seu SAPL para que possamos ver um dado? (passar via Telegram)
