### ISSUE TITLE
Install process in ubuntu

### ISSUE THREAD

**Issue by johnfelipe** [interlegis/sapl#2]
I want begin installation of SAPL, SAAP y Portal Modelo in latest version, please share me installation process for one of them
Tnks

**Comment by johnfelipe** [comment]
Pls again tell me how install 3 apps

**Comment by marciomazza** [comment]
At Interlegis wiki you can find information about SAPL, SAAP, Portal Modelo and other products (in Portuguese):
https://colab.interlegis.leg.br/wiki

Please do note that the current released version of SAPL is 2.5.

We are right in the middle of a busy transition to the new release 3.1, so sorry if we take some time to answer. This github project is specific to the development of the this new version. It will be ready in the next months. Internationalization is planned for version 3.2, but, to meet your request in issue #1 we are trying to find ways to include it sooner in 3.1.
