### ISSUE TITLE
Migrar null para a string vazia em CharFields e TextFields

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#200]

**Comment by edwardoliveira** [comment]
@marciomazza Esta issue não foi realizada por aquele script que vc fez????

**Comment by marciomazza** [comment]
Aquele script era uma adaptação da base atual (para ela mesma, digamos).
Essa tarefa se refere à migração da **base legada** para a atual.
Em geral, tudo que marquei com o label **`migração`** se refere à rorina de migração dos **dados legados**.
