### ISSUE TITLE
Erro ao Adicionar Matéria Legislativa

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2003]
Ao adicinar o Requerimento 17/1988 no sistema, apareceu o erro abaixo. Depois, ao voltar e salvar de novo, deu certo.
![captura de tela de 2018-06-12 16-33-00](https://user-images.githubusercontent.com/19169882/41312946-dd310c9c-6e5e-11e8-9e5d-b8a18a02b156.png)

**Comment by VictorFabreF** [comment]
Boa tarde,
Percebi que existem outras abas do SAPL abertas no navegador, caso você em alguma delas tenha se deslogado e entrado com outro usuário, este erro é de fato esperado. Consegui replicá-lo nestas condições. Foi isso que aconteceu?

**Comment by edwardoliveira** [comment]
@andreagudo Favor confirmar a descrição que o @VictorFabreF forneceu. Se persistir reabrir a issue com uma descrição do passo-a-passo **detalhado** de como reproduzir essa issue.

**Comment by andreagudo** [comment]
Não, era sempre o mesmo usuário. Mas erro não voltou.
