### ISSUE TITLE
Oradores do Expediente: número de ordem ao editar

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2004]
Ao editar dados dos Oradores do Expediente, nem sempre o número de ordem oferecido para salvar é o original. É comum não querer alterá-lo.

**Comment by 54adal** [comment]
Eles são livres para edição, justamente para permitir a  alteração da ordem que se queira.  Agora, ele não renumera os demais automaticamente.

**Comment by andreagudo** [comment]
Mas está oferecendo um número diferente do original.

**Comment by 54adal** [comment]
Como assim? poderia dar um exemplo?

**Comment by andreagudo** [comment]
Clicando no botão editar, abre a tela de edição, oferecendo outro número de ordem, inclusive um já usado.

**Comment by 54adal** [comment]
Na verdade pra vc passar um orador na frente do outro por exemplo, o quinto orador trocar de lugar com o quarto. Dessa forma, edita o 4 para 5, e vice-versa! Pode não ser o meio mais fácil de fazer mas atende. Acho que poderíamos sugerir para a próxima versão, um drag-and-drop, assim como feito na troca de ordem de matérias do expediente e da ordem do dia.

**Comment by andreagudo** [comment]
Aí que está, Adalberto, não quero mudar a ordem, mas outro campo. E o
sistema sugere mudança da ordem.

Em qua, 13 de jun de 2018 12:12 PM, 54adal <notifications@github.com>
escreveu:

**Comment by edwardoliveira** [comment]
Vc testou de novo hoje? O erro persiste?
