### ISSUE TITLE
Painel: tamanho e resolução do brasão

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2005]
Estudar melhor relação tamanho/resolução para o brasão. O que coloquei, apesar de adequado em termos de tamanho para as páginas, mas não tem resolução boa. Foi reduzido de um original maior, de boa qualidade.  O considero grande para o painel. Considerar #1963
![captura de tela de 2018-06-12 14-52-05](https://user-images.githubusercontent.com/19169882/41356648-b2ce33de-6efa-11e8-8333-eb0b5cdf3254.png)

**Comment by 54adal** [comment]
Creio que podemos de fato diminuir um pouco esse brasão, até para ganhar mais espaço no painel. Fica a idéia!

**Comment by 54adal** [comment]
Vamos diminuir 50%, o que acha?

**Comment by 54adal** [comment]
feito!!
