### ISSUE TITLE
Erro ao adicionar Sessão Plenária: Sessões Legislativas demais

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2006]
Ocorreu a alguns minutos, na legislatura 7. Mudei para outras, voltei à 7, e não mais se repetiu.
![whatsapp image 2018-06-13 at 11 01 36 am](https://user-images.githubusercontent.com/19169882/41357473-a1474806-6efc-11e8-8876-a3695e35b02b.jpeg)

**Comment by VictorFabreF** [comment]
Boa tarde,
Isso parece ter sido um erro de assincronia da chamada JavaScript. Não consegui replicar aqui este mesmo erro. Como você também parece não ter conseguido recriar o erro, vou fechar a issue e caso volte a ocorrer peço para que você reabra. Obrigado.
