### ISSUE TITLE
Mostrar a data da sessão em cada uma de suas partes

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2010]
Facilitaria para o usuário se os títulos de cada uma das partes da sessão tivesse sua data ao final, depois de "...ª Legislatura".
![captura de tela de 2018-06-13 15-13-47](https://user-images.githubusercontent.com/19169882/41369840-6b82d22e-6f1c-11e8-946c-5014050db3dd.png)

**Comment by edwardoliveira** [comment]
@marciomazza Tem como colocar isso?

**Comment by edwardoliveira** [comment]
Seria interessante, mas mesmo que a gente colocasse, isso, o título iria ficar ainda mais poluído do que já está. Portanto, não.
