### ISSUE TITLE
Mudança de cor ao fazer uso da palavra

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#2013]
Ao parlamentar fazer uso da palavra o nome do mesmo muda de cor no painel eletrônico de votação.

**Comment by 54adal** [comment]
Sugestões para melhoramento do sistema serão sempre bem-vindos. Sua recomendação será analisada para uma possível implementação na próxima versão (3.2).

obrigado

**Comment by cesaraugc** [comment]
Issue a ser considerada: #2186

**Comment by cesaraugc** [comment]
Funcionalidade adicionada ao sapl 3.2 com o commit 3c65098.
