### ISSUE TITLE
Sessão Plenária - Ocorrências da Sessão

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#2030]
Seria importante a criação de um campo texto semelhante aos de expediente que poderia ser chamado de "Ocorrências da Sessão" para que pudessem ser registrados fatos que ocorreram durante a sessão, ex:
Alteração de pauta
Retirada de projetos
Interrupção de sessão 
e por ai vai.....
Tal cadastro poderia ser feito em sessão plenária, menu abertura, submenu Ocorrências da Sessão.
No resumo e no pdf poderia aparecer como ultimo item.

@andreagudo @LeandroRoberto @edwardoliveira

**Comment by AndreSouto** [comment]
Como seria essa tela ? Seria interessante se você nos fornecesse mais detalhes de como seria campo para ajudar na implementação.

**Comment by DtiLegBG** [comment]
Penso que o cadastro possa ser algo assim
![image](https://user-images.githubusercontent.com/13314947/45703708-7edaa600-bb4b-11e8-9fb1-c62059886220.png)

um texto livre a ser digitado
