### ISSUE TITLE
Customização dos nomes dos cronômetros

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2034]
Cada casa regulamenta os tipos de manifestação com nomes e tempos diferentes. Seria interessante permitir a customização dos nomes dos cronômetros. Por exemplo, no caso de Agudo, o tempo de um discurso no Grande Expediente é diferente do tempo de uma manifestação em discussão de uma matéria na Ordem do Dia. Ambos, porém, teriam que ser cronometrados no Cronômetro de Discursos.
Alternativamente, poderiam ser criados mais tempos para o cronômetro de Discursos. Durante a sessão, antes de iniciar a contagem, o operador optaria pelo tempo regimental correspondente.

**Comment by cesaraugc** [comment]
Mergeado na master. Estará disponível na versão 3.2.
