### ISSUE TITLE
erro na incorporação de proposição após seu recebimento no protocolo

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#2038]
Na oficina de SAPL em Natal, utilizando o cursosapl01.interlegis.leg.br, ao tentar incorporar uma proposição após o seu recebimento no protocolo, ocorreu o seguinte erro:
![image](https://user-images.githubusercontent.com/30807716/41799483-18509cf2-7648-11e8-9858-6f012524d5d0.png)

**Comment by edwardoliveira** [comment]
Isso é um bug na incorporação onde a numeração é gerada por Legislatura.
