### ISSUE TITLE
Empate de Votação

### ISSUE THREAD

**Issue by ClebersonBrandao** [interlegis/sapl#2050]
No momento da sessão plenária, quando houver empate na votação nominal, o Presidente precisa desempatar. Porém não tem opção de desempate e abrir a opção pro Presidente votar. Sugestão: Antes de fechar a votação, constatado a votação em empate, uma pergunta "Houve Empate?" de clicar em SIM, abre nova votação pro Presidente.

**Comment by marimendes** [comment]
Issue duplicada #2051

**Comment by 54adal** [comment]
Verificando melhor, constatamos (Victor!) que da forma que está implementado, é possível sim registrar o desempate da votação. Para isso, o presidente só poderá votar para desempatar o placar. Esse voto será registrado pelo operador do sistema, obviamente sob a orientação da presidência, logo após clicar em REGISTRAR VOTAÇÃO, onde nesse momento, serão bloqueados os terminais de votação (inclusive o do presidente). Confere!??
