### ISSUE TITLE
Empate no painel eletrônico

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#2051]
Em caso de empate na votação, o presidente é quem daria a palavra final. Como poderíamos fazer para que o presidente pudesse votar, mesmo depois de encerrada a votação?

**Comment by marimendes** [comment]
Issue duplicada #2050

**Comment by 54adal** [comment]
Verificando melhor, constatamos (Victor!) que da forma que está implementado, é possível **sim** registrar o desempate da votação. Para isso, _**o presidente só poderá votar para desempatar o placar**_. Esse voto será registrado pelo operador do sistema, obviamente sob a orientação da presidência, logo após clicar em REGISTRAR VOTAÇÃO, onde nesse momento será bloqueado os terminais de votação (inclusive o do presidente). Confere!??
