### ISSUE TITLE
Controlar a execução do "manage.py rebuild_index"

### ISSUE THREAD

**Issue by cristian-longhi** [interlegis/sapl#2055]
O comando 'python3 manage.py rebuild_index' está sendo executado toda vez que subimos o container com 'docker-compose up -d'. Este processo utiliza todo o recurso da CPU, e aqui em nossa base está levando pouco mais de dois dias para concluir. O processo executa alterando ou não a versão da imagem interlegis/sapl. Além disso, como exclui a indexação anterior, a pesquisa textual pode não trazer todas as ocorrências da expressão pesquisada se for executada no meio do processo.
Poderia haver a possibilidade de não excluir os índices e apenas atualizá-los periodicamente com as novas inserções de Normas, Matérias e Documentos Acessórios.

**Comment by edwardoliveira** [comment]
Sim. Também fomos afetados por essa reindexação. Reutilizar o índice é algo que faremos agora. Haverá um novo volume no docker-compose.yml

```
sapl_index:/var/interlegis/sapl/whoosh
```
Na última versão do docker-compose.yml retiramos a reindexação automática. Por hora, para fazê-la deve-se entrar na instância Docker onde se encontra o SAPL e rodar o comand `./manage.py rebuild_index` manualmente. Assim dá para fazer em horários de menor atividade como finais de semana ou horários noturnos. Mas estamos neste exato momento verificando a possibilidade de ter um terceiro container para executar a indexação + mudar para o Solr. Estou trabalhando nessa issue. Mas vc pode já baixar o último docker-compose.yml que não haverá esse problema. Vc sabe como entrar dentro de um container rodando?

**Comment by cristian-longhi** [comment]
Oi @edwardoliveira . Sei, sim. Fiz alguns testes também para rodar o rebuild_index no cron, e devo rodar em seguida um release  mais atual do container, para minimizar a situação.

**Comment by edwardoliveira** [comment]
Deve-se atentar para o fato de que o ideal é **não rodar** o rebuild_index no container SAPL. Estamos vendo como fazer isso sem ter que usar o container do SAPL.

**Comment by cristian-longhi** [comment]
Outra situação que verificamos, apenas para confirmar a urgência deste caso, é que se a indexação do whoosh está completa algumas atualizações no banco de dados demoram muito e não concluem por timeout do nginx. 
Por exemplo: Tramitações em lote.
- Com arquivos no diretório whoosh - 30 matérias no máximo;
- Com diretório whoosh vazio - fizemos o teste com 122 matérias e deu certo.
Não é raro termos tramitação de 50, 60 matérias por sessão.
Conseguimos tramitar mais de 30 com a indexação alterando timeout  (200s) e max-request (1000), e ainda inserindo a diretiva proxy_read_timeout (200s), mas demorou bastante para concluir.

**Comment by edwardoliveira** [comment]
Obrigado pelas informações.

Desabilitamos busca textual no commit 234be7e5 até que tenhamos uma solução para esses problemas. Portanto, a solução por hora é **não haverá busca textual** nesta versão do SAPL. Até desabilitamos os botões nos releases anteriores para evitar trazer dados defasados ou incorrer em erros como este recentemente reportado. **Devemos retormar a tentativas de solucionar essa issue ainda no mês de Agosto, mas não existe previsão alguma para solucionar esse problema.**
