### ISSUE TITLE
Campo que vincula documento ao protocolo

### ISSUE THREAD

**Issue by eduardoedson** [interlegis/sapl#206]
Continuação de #194

**Comment by eduardoedson** [comment]
http://localhost:8000/protocoloadm/137/2015/protocolo_mostrar
Campo que gera um link para o documento criado

**Comment by edwardoliveira** [comment]
Oi @eduardoedson, acho que consegui identificar a ligação entre os dois models. ``protocoloadm.models.Protocolo`` tem o campo ``numero``, e este campo está referenciado como ``numero_protocolo`` nos models ``protocoloadm.models.DocumentoAdministrativo`` e ``materia.models.MateriaLegislativa``.

Não existe Foreign Key ligando (não sei se devemos modificar o esquema de banco pra colocar...), mas pelo que vi, é assim que ele faz a ligação. Acho que estamos pegando errado nessa tela: de ``DocumentoAcessório``. 

**Ah! Por conta disso, se o protocolo for de uma matéria legislativa (tip_processo = 1) então a label será ``Matéria Vinculada``, mas caso seja um documento administrativo (tip_processo = 0) então a label será ``Documento Vinculado``.**
