### ISSUE TITLE
Pesquisa de normas jurídicas

### ISSUE THREAD

**Issue by neynunes** [interlegis/sapl#2072]
Olá, estou testando o SAPL 3.1 e percebi que a pesquisa de normas jurídicas não retorna resultado caso seja acrescentado o número "0" antes da numeração da norma.

**Comment by 54adal** [comment]
Vamos estudar essa implementação. Até porque, é factível que em algum momento, o cidadão vai colocar um  0 antes do número, e não localizará a norma pretendida! Já na Matéria, esse problema não ocorre!
obrigado

**Comment by edwardoliveira** [comment]
Este campo não é numérico porque precisamos compatibilizar os vários formato como, por exemplo, Lei 3449, Lei 3450, lei  3450-A, lei 3450-B, lei 3451. Sendo assim, recomenda-se utilizar a numeração sem zero à esquerda.

**Comment by edwardoliveira** [comment]
Com o último commit o problema pode ser mitigado ao não permitir que usuários entrem com zeros à esquerda do valor. Zeros no meio o no final são permitidos. A questão óbvia que surge dessa mudança é o que fazer com aqueles que já entraram com valores como "000598". Nesse caso, teremos que rodar algum processo para verificar, ao menos nas casas hospedadas no ILB, se existe alguém nessa situação e daí rodar comandos SQL para remover esses zeros. Não vejo como isso possa ter afetado casas migradas, pois na versão 2.5 esse valor era numérico (como disse antes essa alteração foi feita no commit #879.

**Comment by lizianem** [comment]
Como farei para recuperar todos os atos já inseridos e que apresentam 0 na frente?
Faz parte da nomenclatura da norma essa numeração. O usuário está acostumado com isso.

**Comment by edwardoliveira** [comment]
> Como farei para recuperar todos os atos já inseridos e que apresentam 0 na frente?

Esse problema ainda não tem solução. Estamos vendo a melhor forma de contornar esse impedimento, sem gerar outros problemas.

**Comment by edwardoliveira** [comment]
Vide https://github.com/interlegis/sapl/issues/2747#issuecomment-486383777
