### ISSUE TITLE
Status de tramitação sem Indicador da Tramitação

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#2073]
Se o campo de Indicador de Tramitação ficar vazio, não haverá a possibilidade de alterar ou excluir esse status, uma vez que o campo é o próprio link para edição.
Problema apontado por Daniel - Ronda Alta RS na segunda parte do ticket (fechado) #557380

**Comment by sconetto** [comment]
Correção feita mudando o link para os detalhes do status para a sigla (que é item obrigatório no status tramitação), assim que o _commit_ com a correção for _mergeado_ a branch principal a nova _release_ conterá a correção do bug.

**Comment by edwardoliveira** [comment]
Tá dando erro no CI: https://travis-ci.org/interlegis/sapl/builds/403126631?utm_source=github_status&utm_medium=notification

**Comment by edwardoliveira** [comment]
O erro era porque o `cmp` foi retirado do Python3. Retirei essa chamada e fiz um rebase e agora pasou.
