### ISSUE TITLE
Campo Observação da Reunião de Comissão limitado

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#2078]
Campo Observação da Reunião de Comissão limitado a 150 caracteres. Acho que poderia ser um pouco maior.

**Comment by marimendes** [comment]
Bom dia @54adal. Quantos caracteres seria o ideal?

**Comment by 54adal** [comment]
Acho que uns 500 caracteres. Qual tem sido o tamanho padrão dos outros campos OBS?
