### ISSUE TITLE
Botão "Pesquisa Texual sumiu"

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#2082]
o botão para pesquisa textual não aparece mais na visão do sistema , porém acessando a url /sistema/search , consegue fazer a pesquisa
PS: Solr está executado

![image](https://user-images.githubusercontent.com/1524415/42908649-e311ab6a-8ab7-11e8-9de5-d700f98eac4d.png)
![image](https://user-images.githubusercontent.com/1524415/42908680-faf35d5a-8ab7-11e8-9c31-f9367b849edb.png)

**Comment by 54adal** [comment]
Caro Puera,

Esse botão foi retirado temporariamente! Estamos trabalhando para melhorar essa pesquisa textual!

**Comment by edwardoliveira** [comment]
@puera Estamos fazendo a reescrita de toda essa parte da busca textual para evitar erros de estouro de memória e lentidão na reindexação de grandes quantidades de documentos. Vc pode acompanhar o progresso por este PR: https://github.com/interlegis/sapl/pull/2100

Até lá, a pesquisa textual não deve ser utilizada, pois trará dados incompletos ou talvez dado nenhum.
