### ISSUE TITLE
Pauta da Sessão

### ISSUE THREAD

**Issue by ivanlucio10** [interlegis/sapl#2087]
Ao clicar em Pauta da Sessão, mostrar somente os campos que tenha conteúdo, por exemplo se não tiver mateira no expediente não aparecer nada, hoje esta aparecendo assim (Matérias do Expediente
Não existem Matérias de Expediente para essa Sessão Plenária)

**Comment by sconetto** [comment]
@ivanlucio10 vamos analisar com todos da equipe a sua sugestão e passamos um retorno!

**Comment by edwardoliveira** [comment]
Retirar as seções que estão sem dados vai gerar dezenas de tickets perguntando "porque a seção Matérias do Expediente sumiu?" ou "O sistema não está trazendo todas as seções" ou ainda "O sistema está trazendo informação incompleta". Se mais casas dentre as 800 pedirem isso a gente pode considerar no futuro. Por hora não vamos mexer nisso não.
