### ISSUE TITLE
Papel de Autor para os não parlamentares

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#2092]
Com a retirada de Autor na lista de papeis na criação de usuários, deixando tão somente o papel Parlamentar (que posteriormente receberá a vinculação de Votante), como se daria a atribuição do papel de Autor às comissões, ao chefe do poder executivo, etc.  A título de sugestão, retornaria o papel Autor na criação do usuário, trocando apenas o nome Autor para Autor não parlamentar ou Outros Autores, para não confundirem com o Autor (parlamentares) que já é criado automaticamente na inclusão dos mesmos. O que acham?

grato

**Comment by edwardoliveira** [comment]
Na próxima versão o perfil AUTOR já estará de volta.
