### ISSUE TITLE
Atribuição automática de autor e votante ao parlamentar ativo e da legislatura atual

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#2093]
Sugiro para a próxima versão (3.2), a possibilidade de vinculação automática dos papeis de Autor e Votante para o parlamentar ATIVO e da LEGISLATURA ATUAL, na criação do usuários Parlamentar. Deixando apenas a configuração de vinculação manual do papel de Autor, somente para os parlamentares de outras legislaturas (passadas).
grato

**Comment by VictorFabreF** [comment]
Na versão atual já é criado o papel de Autor no ato de criação do perfil do Parlamentar, mesmo que ele esteja inativo e não seja da legislatura atual.

**Comment by 54adal** [comment]
Positivo! Obrigado!
