### ISSUE TITLE
Presença na Sessão Plenária

### ISSUE THREAD

**Issue by Neybson** [interlegis/sapl#2095]
Estivemos em migração do 3.0 para 3.1 no mês de junho e portanto agora estamos recompondo as presença das sessões daqueles mês! Durante o mês de julho assumiram novos Vereadores por 120 dias, mas acontece que quando abrimos as sessões do Mês de junho os Vereadores que aparecem naquelas Sessões são os atuais e não os da época! Acredito que tenha que mudar os parâmetros!!

**Comment by edwardoliveira** [comment]
Qual a versão do SAPL (exemplo: 3.1.104) que vocês estão utilizando? Este SAPL está hospedado no Interlegis?

**Comment by Neybson** [comment]
A versão é 3.1.104 e o SAPL não está hospedado no Interlegis (Câmara Municipal de Fortaleza/CE)

**Comment by cristian-longhi** [comment]
@Neybson, na tela de presenças, tanto da Sessão Plenária quanto da Ordem do Dia, há uma caixa de seleção "Exibir somente parlamentares ativos", que fica marcada por default. Se desmarcares esta opção, aparecerão para seleção todos os parlamentares da legislatura, ativos ou não.

**Comment by Neybson** [comment]
Eu fiz isso Cristian, mas o ideal é a Sessão traga os Vereadores que estavam ativos naquela Sessão, pois aqui em Fortaleza nós temos 43 Vereadores e temos pelo menos 10 suplentes em curso e esse número varia muito. Fica muito difícil pq temos que estar contextualizando naquela Sessão quem estava ativo. Mesmo porque aqui queremos resgatar as Sessões desde 1948 e se não houver essa indexação ficará quase que impossível.

**Comment by cristian-longhi** [comment]
Entendi a tua necessidade e achei a ideia interessante (poderia ser utilizada como  medida de efetividade de mandato também). Atualmente, porém, não há registro de períodos de atividade do parlamentar no SAPL, apenas se o parlamentar está ou não ativo no momento. Ainda que implementado futuramente, para estes registros históricos que pretendes terás que valer-se dos registros de parlamentares por legislatura e de outros documentos, como as atas das Sessões.

**Comment by edwardoliveira** [comment]
Essa questão ainda é pertinente?

**Comment by cesaraugc** [comment]
Caso a issue ainda seja pertinente, pode reabrir.
