### ISSUE TITLE
Pauta em PDF!!

### ISSUE THREAD

**Issue by Neybson** [interlegis/sapl#2096]
Quando acessamos ao link pauta das Sessões, automaticamente nos remete à pauta da última Sessão gerada que contém 3 colunas: Matéria, Emenda e Situação. A Situação mostra o último andamento cadastrado o que é ótimo, porém quando clicamos em "Impressão PDF" aparece ao invés de "Situação", aparece "Resultado da Votação", o que complica pois muda tudo. É possível que o arquivo em PDF tenha as mesmas 3 colunas do arquivo original?

**Comment by edwardoliveira** [comment]
@andreagudo @LeandroRoberto @DtiLegBG Alguma objeção a mudar o PDF? Esses relatórios em PDF foram a única coisa que reaproveitamos do SAPL 2.5 (literalmente copiando para o 3.1). O que vocês sugerem?

**Comment by Neybson** [comment]
Explico: A pauta é um documento que antecede a Sessão Plenária, sendo assim não é interessante que nela haja o resultado da votação (que nem aconteceu ainda), e sim a sua tramitação para a Sessão. A sessão já traz a estrutura correta, mas quando vc clica em "Impressão PDF" aí ela muda a estrutura.

**Comment by LeandroRoberto** [comment]
inclusive acho que a tramitação das matérias da pauta da sessão pretendida deveria ser congelada, visto que se posteriormente vc tramita a matéria, a pauta da não reflete o cenário inicial daquela sessão.

**Comment by Neybson** [comment]
Perfeito Leandro, isso mesmo!!

**Comment by edwardoliveira** [comment]
> inclusive acho que a tramitação das matérias da pauta da sessão pretendida deveria ser congelada, visto que se posteriormente vc tramita a matéria, a pauta da não reflete o cenário inicial daquela sessão.

Poderiam abrir uma segunda issue para lidar com esse caso?

**Comment by Neybson** [comment]
Na atualização 3.1.117 foi alterada a pauta em PDF, porém só é gerada nessa pauta os arquivos que estão destinados à Ordem do Dia, quando na verdade deveria ser disponibilizada toda a pauta em PDF, da forma que ela aparece em HTML.

**Comment by marimendes** [comment]
@Neybson Bom dia, você poderia me mandar um print da tela?

**Comment by Neybson** [comment]
Essa é uma pauta da nossa Casa:
http://cmfor3.virtuaserver.com.br/sessao/pauta-sessao/937
E essa é a geração do PDF:
http://cmfor3.virtuaserver.com.br/relatorios/pauta-sessao/937/

**Comment by Neybson** [comment]
Veja que a geração do PDF só constam as matérias que vão à Ordem do Dia e as demais são omitidas

**Comment by edwardoliveira** [comment]
@marimendes O commit 59bc747ba0a31ac95a introduziu um bug. 
```
        numeracao = Numeracao.objects.filter(materia=votacao.materia).first()
        if numeracao is not None:
              numeracao = numeracao.first()
``` 
Acontece que numeracao não tem método `first()`

**Comment by sconetto** [comment]
@edwardoliveira vimos que você fez um commit ontem corrigindo esse bug e com o dump que temos aqui de Fortaleza o relatório gerou sem problemas, a correção que você faz é satisfatória para fechar a issue? Foi feita uma release de versão com essa correção?

**Comment by edwardoliveira** [comment]
Sim, vamos gerar um release hoje de manhã! :+1:
