### ISSUE TITLE
Tamanho do campo do nome de Comissão limitado à 50 caractereres

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#2097]
Atenção na migração do 2.5 para 3.1 com nomes de Comissão acima de 50 caracteres. Ao tentar editá-los no 3.1, poderá ocorrer Error 500.

**Comment by edwardoliveira** [comment]
Nos forneça um exemplo de casa onde ocorra isso.

**Comment by 54adal** [comment]
![image](https://user-images.githubusercontent.com/30807716/43535451-73952454-9590-11e8-9429-d97aae8bb535.png)

Teste feito no sapl.teste.df.leg.br
