### ISSUE TITLE
Audiências Públicas sem possibilidade de Edição

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#2101]
Ao criar uma Audiência Pública e salva-la, não aparecem os metadados da matéria legislativa inseridas no preenchimento. 
Ao clicar em Editar, só  aparece o título da audiência criada.
grato

**Comment by 54adal** [comment]
Edição de uma Audiência continua só aparecendo o título.

**Comment by VictorFabreF** [comment]
Vi que esse problema ocorre quando não tem uma matéria legislativa vinculada à Audiência Pública, vou ver o que pode estar causando isso e corrigir.
