### ISSUE TITLE
Relatório Normas Jurídicas: segundo critério de ordem

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2104]
O relatório de normas jurídicas tem, por primeiro critério de ordem, a data por ordem decrescente. O segundo critério é o Número, em ordem crescente, que deveria mudar para decrescente.
https://sapl.agudo.rs.leg.br/norma/pesquisar?tipo=12&numero=&ano=2018&data_0=&data_1=&data_publicacao_0=&data_publicacao_1=&ementa=&assuntos=
![captura de tela de 2018-08-02 08-30-28](https://user-images.githubusercontent.com/19169882/43581175-6fa4b8ca-962e-11e8-8ff0-5281b41c1888.png)

**Comment by edwardoliveira** [comment]
O @DtiLegBG fez um commit ano passado que transformou o `numero` em alfanumérico: #879. Assim sendo, a ordenação da figura se deve a isso. Não tem solução que não seja retornar esse campo para numérico. Passamos quase a tarde inteira tentando encontrar maneiras de manter como alfa-numérico e ordenar corretamente, mas não sei se vai ser possível. Não vou fechar essa issue porque ainda continuamos tentando encontrar uma solução que agrade a todos, e por isso não vou fechar essa issue, mas a chance de ficar sem solução é grande.
