### ISSUE TITLE
Atas 

### ISSUE THREAD

**Issue by neynunes** [interlegis/sapl#2113]
As atas das sessões poderiam ser geradas automaticamente pelo sistema.

**Comment by 54adal** [comment]
Caro Ney,

Não sei se seria possível gerar uma ata fechada, mas quem sabe um rascunho de ata, podendo o(a) secretário(a) complementar os dados posteriormente. 
Fica a sugestão para uma nova versão!
obrigado
Adal

**Comment by neynunes** [comment]
Ok. Obrigado, amigo.

-------- Mensagem original --------
De : 54adal <notifications@github.com>
Data: 07/08/2018 11:36 (GMT-03:00)
Para: interlegis/sapl <sapl@noreply.github.com>
Cc: neynunes <neynunes@hotmail.com>, Author <author@noreply.github.com>
Assunto: Re: [interlegis/sapl] Atas (#2113)


Caro Ney,

Não sei se seria possível gerar uma ata fechada, mas quem sabe um rascunho de ata, podendo o(a) secretário(a) complementar os dados posteriormente.
Fica a sugestão para uma nova versão!
obrigado
Adal
