### ISSUE TITLE
Recebimento de Proposições

### ISSUE THREAD

**Issue by neynunes** [interlegis/sapl#2115]
Ao ordenar por data de envio as "Proposições não recebidas", o sistema sempre retorna à primeira página, não ordenando as demais.

**Comment by 54adal** [comment]
Caro Ney,

Fiz o teste aqui na minha máquina e o sistema ordenou sem problemas. Poderia tentar novamente e me relatar? Recomendo sempre fazer um print screen com erro e anexar à Issue.
grato
Adal
![image](https://user-images.githubusercontent.com/30807716/43782295-68e1df94-9a35-11e8-95a2-4105a9010a88.png)

**Comment by neynunes** [comment]
Adalberto,

Ele ordena a primeira página somente. Ao clicar na segunda e solicitar a ordenação o sistema retorna à página inicial. Aí o sistema ordenou tudo?


-------- Mensagem original --------
De : 54adal <notifications@github.com>
Data: 07/08/2018 11:32 (GMT-03:00)
Para: interlegis/sapl <sapl@noreply.github.com>
Cc: neynunes <neynunes@hotmail.com>, Author <author@noreply.github.com>
Assunto: Re: [interlegis/sapl] Recebimento de Proposições (#2115)


Caro Ney,

Fiz o teste aqui na minha máquina e o sistema ordenou sem problemas. Poderia tentar novamente e me relatar? Recomendo sempre fazer um print screen com erro e anexar à Issue.
grato
Adal
[image]<https://user-images.githubusercontent.com/30807716/43782295-68e1df94-9a35-11e8-95a2-4105a9010a88.png>

**Comment by 54adal** [comment]
Perfeitamente! Ele ordenou a primeira e a segunda página.
 Agora como está só em uma página, não tem como eu fazer os prints de tela para vc dar uma olhada. De toda forma, se continuar dando esse problema aí, retome o contato.
grato
Adal
