### ISSUE TITLE
Error 500 ao protocolar documentos

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#2116]
"Sempre que tentamos protocolar um documento, dá erro Server Error (500) no SAPL". (Câmara Municipal de Conselheiro Lafaiete - MG) - Ticket #787770

**Comment by sconetto** [comment]
@54adal é preciso coletar mais informações acerca, talvez um vídeo ou _prints_ com os passos para recriar o erro para que possamos avaliar.

**Comment by 54adal** [comment]
ok, Já solicitei à cm!

**Comment by daniellainacio** [comment]
![errosapl1](https://user-images.githubusercontent.com/13997355/43834859-229b0748-9ae6-11e8-8e94-2062f86b3733.jpg)
![errosapl2](https://user-images.githubusercontent.com/13997355/43834862-22b80f3c-9ae6-11e8-88bc-48126511d7cc.jpg)

**Comment by daniellainacio** [comment]
Ao clicar em Protocolar documento, automaticamente, é redirecionado para a página de erro.

**Comment by VictorFabreF** [comment]
Esse problema foi corrigido com o commit 759a902, assim que o sistema for atualizado ele não deve mais ocorrer.

**Comment by daniellainacio** [comment]
Existe previsão para essa atualização do sistema?

**Comment by VictorFabreF** [comment]
O sistema já deve estar atualizado
