### ISSUE TITLE
Resultado da última votação aparece no painel mesmo estando fechado

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#2117]
Após uma votação, ao Iniciar o Painel completo sem abri-lo, aparece o texto do resultado da última votação (mesmo estando fechado). Será que não seria mais interessante não aparecer nenhuma mensagem?

grato
Adal
![image](https://user-images.githubusercontent.com/30807716/43795146-da68c22e-9a56-11e8-9046-944840c4ce9c.png)

**Comment by sconetto** [comment]
@54adal fiz um commit com uma adição que oculta o texto do resultado caso o painel esteja fechado, se ele estiver aberto ele apresentará a informação normalmente!

**Comment by 54adal** [comment]
Muito obrigado!
