### ISSUE TITLE
Relatório de Presenças e Ausências de Parlamentares

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#212]
Recentemente o Morale implementou um novo relatório no SAPL 2.5, conforme pedido abaixo. Relatórios/Presença e o ticket é ticket n. 596103.

"Quero saber se é possível implementar um relatório no SAPL que liste as presenças e ausências dos Vereadores nas sessões legislativas. 
Ocorre que em uma câmara vizinha o MP solicitou que uma relação das presenças e ausências fosse disponibilizada para consulta da população com a finalidade de melhorar transparência. 
Sei que através do módulo sessão legislativa já é possível ver esta informação por sessão, porém, para ter um visão geral o cidadão terá que acessar sessão por sessão."

**Comment by eduardoedson** [comment]
Foi feito o relatório [http://localhost:8000/relatorios/presenca](http://localhost:8000/relatorios/presenca)
