### ISSUE TITLE
Exibição do Texto Articulado

### ISSUE THREAD

**Issue by CristianoCMLP** [interlegis/sapl#2121]
O texto articulado depois de publicado e fechado a publicação poderia mostrar abaixo da consulta da norma jurídica, na Câmara Municipal de Jatai em Go já funciona assim, eu acho que aumenta a transparência para o cidadão que está consultando uma lei.

**Comment by edwardoliveira** [comment]
Poderia nos mostrar um exemplo (screenshot) de como está aparecendo no site de Jataí?

/cc @LeandroRoberto

**Comment by CristianoCMLP** [comment]
Olhem o exemplo por por favor 
http://sapl.camarajatai.go.gov.br/sapl/consultas/norma_juridica/norma_juridica_mostrar_proc?cod_norma=281&autostart=off&pesquisa=

**Comment by LeandroRoberto** [comment]
A norma usada como exemplo no sapl em produção pode ser vista no sapl 3.1 em duas possibilidades

a) http://sapl31.camarajatai.go.gov.br/norma/281 - neste link é o detail norma 
b) http://sapl31.camarajatai.go.gov.br/ta/281/text - e neste link é a listagem do texto articulado

pois bem... o link de produção usado como exemplo mescla dados dos link (a) e (b)... já no 3.1 é feito em duas telas conforme os links acima... 

é possível essa mesclagem...
eu sugiro que o relatório (b) seja incrementado com os dados de (a), além disso, que o Crud que responde a (a) caso a norma possua TextoArticulado redirecione para o link (b), 

um screenshot dos três links:
![captura de tela de 2018-08-08 14-55-51](https://user-images.githubusercontent.com/9630623/43855187-389413f2-9b1b-11e8-8b84-cd3b775dbdad.png)
