### ISSUE TITLE
Período de Composição de Comissões deve estar dentro de uma legislatura (se não permanente)

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#2129]
O período indicado deve estar contido no período de uma legislatura.

**Comment by marimendes** [comment]
Bom dia @morale. Aqui nessa tela deve ter um campo legislatura e essa data deve estar contida nesse período? 
![captura de tela de 2018-08-10 10-07-02](https://user-images.githubusercontent.com/11450196/43959422-2a281c30-9c85-11e8-8be4-4e38d0d13730.png)

**Comment by morale** [comment]
@edwardoliveira o período de composição de Comissões tem a ver com alocação dos parlamentares que irão compor a comissão.  No caso das comissões temporárias a data fim do período de composição poderá estar limitada pela data fim da Comissão.

**Comment by morale** [comment]
@edwardoliveira ... a legislatura limita a participação do parlamentar na composição da comissão, uma vez que restringe o mandato. Então no caso das comissões permanentes o período de composição nunca será maior do que o período da legislatura. E nas temporárias certamente a data fim da comissão irá limitar o periodo de composição quando ela for menor que a data fim da legislatura.
