### ISSUE TITLE
1º Contato: Assembleia Legislativa de Sergipe , Mudança { Site da Câmara , Vereador }

### ISSUE THREAD

**Issue by daniel-Se** [interlegis/sapl#2132]
Bom dia, Trabalho na casa Legislativa de Sergipe e meu chefe, o direto de T.I. desta casa, solicitou me que entrasse em contato com os senhores, para ver se seria possível fazer algumas alterações simples nos layout do sistema. 

1 - Trocar o nome Site da Câmara ( Localizado no Rodapé ).   por = > Site . Ou outro nome que seja genérico.

2 - Trocar o nome de apresentação "Vereador"  por => Parlamentar .

No intuito de deixar genérico para que possa ser usado nesta casa como também em outas casas tanto do poder legislativo quanto das camarás municipais 

Grato.

**Comment by 54adal** [comment]
Boa tarde!

Agradeço pelas sugestões.

O item número 2, onde está escrito "Vereador"?

**Comment by 54adal** [comment]
Ok. Vamos atender à sua solicitação.
Obrigado
![image](https://user-images.githubusercontent.com/30807716/44098127-bda62500-9fb5-11e8-8e5b-01bc9aab6a85.png)
