### ISSUE TITLE
POP UP (Video, Audio)

### ISSUE THREAD

**Issue by BismarkLemke** [interlegis/sapl#2133]
Sugestão de melhoria

Na sessão plenária tem a opção de inserir o áudio e o vídeo "Conteúdo Multimídia", um link para os arquivos (URL Arquivo Áudio (Formatos MP3 / AAC), URL Arquivo Vídeo (Formatos MP4 / FLV / WebM)).  Na versão 2.5 ao inserir estes dados o usuário acessa o conteúdo através de uma pop-up onde tem um player para os exibir o conteúdo multimídia, já na nova versão o usuário e direcionado para o URL informado.

Gostaria que esta pop-up fosse adicionada na versão 3.1.

**Comment by edwardoliveira** [comment]
![image](https://user-images.githubusercontent.com/9326037/46965286-cf78ec80-d080-11e8-8833-775afe07c01e.png)

Agora será possível tocar os arquivos de media diretamente na página, com opção de Download (os três pontos a esquerda). Com a opção de tela inteira no caso do vídeo.
