### ISSUE TITLE
Relatório de Matérias em Tramitação: ordem

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2135]
Definir a ordem numérica do resultado.Vê-se, no exemplo abaixo, que os Pedidos de Informações aparecem embaralhados.
https://sapl.agudo.rs.leg.br/sistema/relatorios/materia-por-tramitacao?ano=2018&tipo=&tramitacao__unidade_tramitacao_local=&tramitacao__status=
![captura de tela de 2018-08-14 09-03-53](https://user-images.githubusercontent.com/19169882/44090692-7b44637a-9fa1-11e8-9055-1a9fcc96c13d.png)

**Comment by VictorFabreF** [comment]
Bom dia,
Isso foi corrigido no _commit_ da40234. Na próxima atualização do sistema a ordenação já estará por ano, tipo e número.
