### ISSUE TITLE
Parlamentar não aparece como autor

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2136]
O Ver. Carlito Schiefelbein, suplente, assumiu mandato no mês passado. Ela foi Vereador em outras legislaturas, autor de várias matérias legislativas. Ontem apresentou a Indicação 8/2018, mas não consigo incluí-lo como autor, pois seu nome não aparece na caixa se seleção, somente os dos oito demais parlamentares ativos. Como se trata do primeiro caso de volta de um parlamentar depois da migração, o problema não estaria nela? Ele, porém, está listado entre os autores nas Tabelas Auxiliares.

**Comment by VictorFabreF** [comment]
Bom dia,
Vi que o mandato do Vereador está com data fim para 01/08/2018, dessa forma, se a data de apresentação da matéria for posterior a esta data, ele não aparecerá na caixa de seleção.
Segue imagem em anexo:
![image](https://user-images.githubusercontent.com/19825887/44092687-9bda7178-9fa7-11e8-87d6-c272d976a5aa.png)

**Comment by andreagudo** [comment]
Bingo. Tal data está errada. Acabei deixando em branco, pois uso esse dado apenas para os titulares. No caso dos suplentes essa informação fica nas Observações. Obrigado.
