### ISSUE TITLE
1ª proposicao da sessão planaria get num Materia null

### ISSUE THREAD

**Issue by daniel-Se** [interlegis/sapl#2137]
Bom dia,

    Gostaria que tirassem uma dúvida sobre um erro que estava dando aqui.

    Quando é criada uma nova proposição referente a uma nova sessão planaria (Quando os números da matéria são renovados ). O sistema vai no banco resgatar o possível numero da matéria para aquelas proposição naquele ano, contudo, não existe numero e retorna null. 

    Está correto ou o caminho feito está errado?

 Arquivo sapl/materia/views.py Linha 704
         numm = MateriaLegislativa.objects.filter(tipo=p.tipo.tipo_conteudo_related,ano=p.ano).last()

**Comment by VictorFabreF** [comment]
Bom dia,
Você está se referindo ao trecho presente em `sapl/materia/views.py` linhas 709 a 717?
Qual versão você está usando?
Segue trecho citado:
`                        try:                            Numero = MateriaLegislativa.objects.filter(tipo=p.tipo.tipo_conteudo_related,                                                                       ano=p.ano).last().numero + 1                            messages.success(request, _(                                '%s : nº %s de %s <br>Atenção! Este número é apenas um provável '                                'número que pode não corresponder com a realidade'                                % (p.tipo, Numero, p.ano)))                        except ValueError:                            pass`

**Comment by daniel-Se** [comment]
Numero =  MateriaLegislativa.objects.filter(tipo=p.tipo.tipo_conteudo_related,ano=p.ano).last().numero  + 1
Isso, se não existe num da materia, ou seja  ( MateriaLegislativa.objects.filter(tipo=p.tipo.tipo_conteudo_related,ano=p.ano).last().numero ) retornar null, quando ele soma com + 1 ele gera erro.
Correto ?

**Comment by VictorFabreF** [comment]
Exato. Por isso este trecho do código está dentro de um `try/except` , caso não exista o número, o erro será tratado.
