### ISSUE TITLE
Layout mais sucinto

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#214]
Criar um layout do crispy-forms (o SaplLayout, provavelmente) inicializado com um yaml ou com uma string na forma:
```
"""legenda 1
    campo1 campo2 campo3
    campo4[9] campo5

legenda 2
    campo6[4] campo7[2] campo8
"""
```

O valor entre colchetes significa quantas colunas aquele campo ocupa. Se omitido é calculado automaticamente distribuindo o número de colunas restantes igualmente entre os demais campos.

No exemplo acima os campos ocupariam as colunas da seguite forma:
```
campo1, campo2 e campo3: 4 colunas cada
campo4: 9 colunas
campo5: 3 colunas

campo6: 4 colunas
campo7: 2 colunas
campo8: 6 colunas
```

**Comment by LeandroRoberto** [comment]
Concordo com a facilidade em escrever os formulários e as ideias colocadas... mas como eu já havia ponderado sobre isso, acho que seria interessante projetar isso prevendo placeholder e tooltip ou title. Algo do tipo: 
ps: não conheço a sintaxe yaml, seria aqui apenas um exemplo de ideia...

"""legenda 1
    campo1[None, 'placeholder do campo1', 'tooltip do campo 1'] campo2 campo3
    campo4[9, 'placeholder do campo4', 'tooltip do campo 4'] campo5[None, '', 'tooltip do campo5]

campo1, campo2 e campo3: 4 colunas cada sendo que campo1 tem placeholder e tooltip
campo4: 9 colunas com placeholder e tooltip
campo5: 3 colunas com tooltip

**Comment by marciomazza** [comment]
@LeandroRoberto Eu não coloquei as infos de placeholder e tooltip, pelo menos por enquanto, por alguns motivos:
* Precisamos avançar e, se for o caso, abrimos uma issue específica para essa melhoria
* Isso pode poluir bastante a configuração (agora nos arquivos em `layouts.yaml`) e torná-la complexa
* Se o uso dessas propriedades for raro (ocorrer em alguns campos apenas, e eventualmente) tenho em mente uma estratégia que talvez seja melhor: sobrescrever o método `get_layout` (`crispy_layout_mixin.CrispyLayoutFormMixin.get_layout`) na view que precisar e fazer os ajustes seguindo http://django-crispy-forms.readthedocs.org/en/latest/dynamic_layouts.html. Quando tiver um exemplo posso linkar aqui.

**Comment by marciomazza** [comment]
Obs.: Essa implementação foi revisada por @edwardoliveira
