### ISSUE TITLE
Adicionar norma jurídica: buscar indexação da matéria correspondente

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2141]
Ao adicionar uma norma jurídica, informa-se a matéria legislativa que a originou e o sistema busca a respectiva ementa. Sugiro que busque também a Indexação.

**Comment by andreagudo** [comment]
A ementa da matéria está sendo recuperada concatenada à indexação.
![captura de tela de 2018-09-19 10-42-40](https://user-images.githubusercontent.com/19169882/45757172-219d2e00-bbf9-11e8-9219-01da37a99856.png)

**Comment by edwardoliveira** [comment]
**Não reabra as issues passadas mesmo que seja sobre o mesmo assunto.** Melhor criar uma nova porque as issues antigas ficam perdidas lá atrás e daí podemos nunca ver.
