### ISSUE TITLE
Votação: discrepância entre presenças à Ordem do Dia e Total de presentes

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2152]
Houve uma discrepância entre o número de presentes à Ordem do Dia e Total de presentes considerado para votação (respectivamente, 7 e 14). Caso semelhante à #2031 . Ocorre em todas as matérias da Ordem do Dia de tal sessão.
https://sapl.agudo.rs.leg.br/sessao/2419/matordemdia/votsimb/5414/3503?

**Comment by VictorFabreF** [comment]
Bom dia, André
Vamos ver o que pode ter causado isso, mas caso você clique em "Salvar" na tela de presenças o problema é resolvido.
Att,
Victor Fabre
