### ISSUE TITLE
Protocolo Geral - Sugestões - Alterações

### ISSUE THREAD

**Issue by ricardo-simas** [interlegis/sapl#2153]
Prezad@s,
Prezad@s,
Quando efetuo o protocolo de uma matéria, eu preencho o Campo OBSERVAÇÃO.
![campo-observacao](https://user-images.githubusercontent.com/42471491/44271093-97376800-a20f-11e8-9dde-8001f6ed1566.jpg)

No entanto, este campo não está sendo gravado, pois quando vou CRIAR A MATÉRIA, o campo fica vazio.
![campo-observacao-vazio](https://user-images.githubusercontent.com/42471491/44271092-969ed180-a20f-11e8-8f1d-294c575f1e12.jpg)

**Comment by marimendes** [comment]
Boa tarde @ricardo-simas, o campo observação na página de criar matéria pertence a matéria e não ao protocolo.

**Comment by ricardo-simas** [comment]
Olá Mariana.
Observe o seguinte raciocínio.
Eu clico em Protocolo Geral, depois, clico no botão, na parte superior do formulário, PROTOCOLAR MATÉRIA.
Preencho todos os campos, conforme mostrado abaixo:
![tela-protocolar-materia](https://user-images.githubusercontent.com/42471491/44285487-f0b58c00-a23b-11e8-9cfb-ca6125a1a9f8.jpg)
Por fim, clico no botão ao pé da página PROTOCOLAR MATÉRIA.
Abre-se uma nova janela com quatro opções: (Imprimir Etiqueta - Imprimir Comprovante - Criar Matéria - Continuar
![cor-diferente](https://user-images.githubusercontent.com/42471491/44285539-25294800-a23c-11e8-9602-c75d020b4aac.jpg).

Eu escolho CRIAR MATÉRIA.
Todos os campos que eu digitei na primeira tela são transportados para a matéria criada, **EXCETO** o campo observações. Ou seja, o que eu digitar lá, e não importa o conteúdo digitado, não é aproveitado na matéria criada.
Os demais campos, Tipo de Matéria, Autor e Ementa, são aproveitados na matéria criada. Porque não aproveitar o conteúdo digitado em Observação?

**Comment by marimendes** [comment]
Boa tarde @ricardo-simas, é porque são observações diferentes. A matéria tem a sua observação, assim como o protocolo possui a sua. Elas não são as mesma observação por isso não se pode aproveitar o conteúdo de uma na outra. 
Os campos que são passados para a matéria criada são os campos obrigatórios e de maior importância, por esse motivo o campo de observação do protocolo não é passado para a matéria criada.
