### ISSUE TITLE
Destacar opção de Protocolar Matéria

### ISSUE THREAD

**Issue by ricardo-simas** [interlegis/sapl#2156]
Prezados,
Quando vou protocolar um novo documento, clico em PROTOCOLO e, depois, em PROTOCOLO GERAL.
A imagem que se apresenta é a seguinte:
![tela-protocolo](https://user-images.githubusercontent.com/42471491/44271291-25135300-a210-11e8-8fd4-cacbdf8d3a62.jpg)
Os botões que possuem destaque são: 
**PESQUISAR AUTOR**
**LIMPAR AUTOR**
**PESQUISAR**
O botão **PROTOCOLAR MATÉRIA** passa despercebido. 
Sugiro que seja feito um destaque no botão, para chamar a atenção, assim como acontece na opção CRIAR MATÉRIA.
![cor-diferente](https://user-images.githubusercontent.com/42471491/44271323-378d8c80-a210-11e8-9c8b-12c8b0a43d37.jpg)

**Comment by edwardoliveira** [comment]
Visto que é possível criar um matéria legislativa **sem** criar protocolo, não nos parece que seja de grande vantagem destacar esse campo no momento. Já é parte do fluxo criar protoclo --> criar matéria, mas caso isso não seja necessário dá pra fazer só criar matéria.
