### ISSUE TITLE
Dúvida - Gerar número de protocolo

### ISSUE THREAD

**Issue by ricardo-simas** [interlegis/sapl#2157]
Prezad@s,
Nas configurações do Sistema, definimos as regras de incorporação como NUNCA PROTOCOLOAR.
![regra-nunca-protocolar](https://user-images.githubusercontent.com/42471491/44278057-3ade4380-a223-11e8-95a5-3c7c3ed9e75f.jpg)
No entanto, quando criamos a matéria, o número do Protocolo é gerado.
![gera-protocolo](https://user-images.githubusercontent.com/42471491/44278091-51849a80-a223-11e8-8a6e-019a374f9c73.jpg)
Isto está correto??
Se a definição está como NUNCA protocolar, o campo NÚMERO DE PROTOCOLO não deveria estar vazio?

**Comment by tapumar** [comment]
Bom dia @ricardo-simas, você pode informar os passos que fez para criar a matéria? 
Pelo que vi na foto que mandou, você está criando a matéria depois de protocolar, logo já tem numero de protocolo.

**Comment by ricardo-simas** [comment]
Bom dia @tapumar 
Os passos são os seguintes:
1. Clico em Protocolo
2. Clico em Protocolo Geral
![passo01](https://user-images.githubusercontent.com/42471491/44346136-a0247580-a46b-11e8-852d-1db2ca4c1ff5.jpg)
3. Clico em Protocolar Matéria
![passo02](https://user-images.githubusercontent.com/42471491/44346147-a74b8380-a46b-11e8-847a-f524f5474e75.jpg)
4. Preencho os campos conforme marcado na figura abaixo e, após o preenchimento dos campos, clico no botão azul Protocolar Matéria. Note que NÃO preencho o campo Número do Protocolo
![passo03](https://user-images.githubusercontent.com/42471491/44346182-bd594400-a46b-11e8-834c-eef1ba030af6.jpg)
5. Na tela que se apresenta, clico em CRIAR MATÉRIA
![passo05](https://user-images.githubusercontent.com/42471491/44353706-36619700-a47e-11e8-89a1-2d29aa18539a.jpg)
6. Na próxima etapa, sem que eu tenha preenchido o número de protocolo inicial, o sistema gera um número de protocolo automaticamente.
![passo06](https://user-images.githubusercontent.com/42471491/44353858-a96b0d80-a47e-11e8-8a7c-7077a62bfb42.jpg)

**Comment by VictorFabreF** [comment]
Boa tarde, @ricardo-simas 
Esse é o comportamento esperado. Uma vez que a matéria é criada a partir do protocolo, seu número de protocolo será correspondente ao protocolo a partir do qual ela foi criada. Todo os protocolos possuem números gerados automaticamente pelo sistema ou então pegando o número informado no campo opcional "Número de Protocolo" no formulário de criação de protocolo. Espero ter sanado sua dúvida.
Atenciosamente,
Victor Fabre

**Comment by ricardo-simas** [comment]
Olá @VictorFabreF .
No entanto, se o campo NÚMERO DE PROTOCOLO é um campo OPCIONAL, não sendo obrigatório seu preenchimento, levou-me a crer que, deixando em branco não iria gerar um número de protocolo.
Ou seja, deixo o campo em branco porque não nos interessa esse número. Mas o sistema gera um número automático que tenho que apagar, depois.

**Comment by VictorFabreF** [comment]
O campo é opcional para o preenchimento do usuário, no entanto os números são gerados de maneira automática pelo sistema para que possa haver seu correto funcionamento.

**Comment by sconetto** [comment]
Boa tarde @ricardo-simas,
o campo NÚMERO DE PROTOCOLO é de preenchimento OPCIONAL caso o operador decida mudar o número inicial nos protocolos, ou seja, o número de protocolo é um sequencial numérico, mas caso ele queira que a sequência se inicie no número X, durante a protocolação deve ser preenchido o campo com o citado número X, salvo este caso o sistema vai gerar o próximo número na sequência a partir da numeração do último protocolo, ou seja, se o campo está em branco haverá um número do protocolo, ele sempre será gerado.

**Comment by ricardo-simas** [comment]
Prezad@s,
Entendo da necessidade de gerar um número de protocolo para fins de registro no banco de dados.
No entanto, esse número,  não é útil para nossa Casa Legislativa.
Haveria a possibilidade de colocar, nas Configurações do Sistema, a possibilidade de gerar ou não esse número?

**Comment by sconetto** [comment]
@ricardo-simas para ficar mais claro a sua dúvida, o que vocês não fazem uso é do Número do Protocolo na Matéria? Não seria o caso de apenas criar a Matéria sem antes protocolar a mesma?

**Comment by ricardo-simas** [comment]
Olá @sconetto 
Não sabia que era possível. Acreditava que deveria ser, sempre, protocolado antes.
Mas, vou experimentar.
Grato.

**Comment by sconetto** [comment]
@ricardo-simas por nada, segue um link onde há a documentação com o caderno de exercícios e o material de uso do SAPL, pode ser de grande ajuda para entender as funcionalidades e funcionamento do sistema: https://colab.interlegis.leg.br/wiki/ProjetoSapl3.1
