### ISSUE TITLE
Mudanças de nomes de partidos

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2161]
Estudar um modo de registrar mudanças de nomes de partidos, que não deveriam ser registrados como novos.

**Comment by sconetto** [comment]
A ideia seria registrar um histórico?

**Comment by sconetto** [comment]
Pensando até um pouco mais aqui acerca disso, a edição não seria bom para fins de histórico no SAPL

**Comment by edwardoliveira** [comment]
@sconetto Seria uma boa pensarmos na melhor forma de implementar isso... Porque, eu vejo que isso tem um impacto nas pesquisas (antes pegaríamos o nome/sigla em um campo do model, agora teria que ir em outro model e pegar o nome correspondente àquela data da matéria legislativa, por exemplo.

**Comment by andreagudo** [comment]
Bem, foi isso aí acima que o @sconetto sugeriu que eu fiz com o PMDB: criei um novo, MDB. Alías, fiz questão de criá-lo novo para não confundir com o antigo MDB, do qual o PMDB surgiu não como mera mudança de nome, mas fruto de reestruturação partidária.
