### ISSUE TITLE
Sugestões de mudança no Sapl 3.1

### ISSUE THREAD

**Issue by scherinf** [interlegis/sapl#2167]
Bom dia,
Estou gostando muito do novo Sapl! Gostaria apenas de dar algumas sugestões de mudança, caso sejam viáveis:
1) Na tela de adição de normas jurídicas: 
a) Sempre que uma norma é adicionada, é solicitado a esfera da federação. Não seria mais interessante informar esse dado apenas uma vez em Tabelas Auxiliares? 
b) O Campo "Complementar?" talvez poderia ser autocompletado como "não" pois leis complementares são exceção.
c) Acredito que o tamanho dos campos possam ser diminuídos, assim facilita o uso do sistema em apenas metade da tela, como consta na imagem anexa. Também sugiro diminuir a altura dos campos ementa, indexação e observação​, deixaria a página menos comprida.
2) Iria sugerir também para deixar como default o parâmetro iframe=0 mas vi agora mesmo que vocês implementaram isso e ainda adicionaram um botão para abrir o sistema completo, ficou excelente, parabéns!

Sendo essas modificações que gostaria de sugerir, agradeço desde já pelo esforço de tornar o sistema cada vez melhor.

![tamanho campos](https://user-images.githubusercontent.com/42675253/44587642-f1917500-a789-11e8-819d-bb1f5d76a721.png)

Atenciosamente,
Marcos Feltrin Scher

**Comment by edwardoliveira** [comment]
Obrigado pelas sugestões, vamos eventualmente voltar a elas, assim que possível.

**Comment by lizianem** [comment]
Também estou de acordo com as sugestões, principalmente do item 1. São pertinentes e ajudariam a Prefeitura d Porto Alegre no cadastro de suas normas.

**Comment by careassu** [comment]
Gostaria de sugerir o campo de ordenação na pesquisa das Normas Jurídicas, assim como já é disponível na pesquisa de Matérias Legislativas.

**Comment by scherinf** [comment]
Boa tarde, 
Gostaria de saber se alguma das minhas sugestões vai ser implantada no Sapl.
Obrigado.

**Comment by tapumar** [comment]
Boa tarde @scherinf, os itens "a" e "b" serão implantados no sapl 3.1

**Comment by edwardoliveira** [comment]
@scherif ficamos devendo a sugestão 1.B pq não tem como fazer por agora (quantidade de telas e falta de tempo), mas isso está registrado em outra issue e a seu tempo iremos fazer.

@careassu favor abrir uma nova issue pra  tua sugestão.
