### ISSUE TITLE
Indicação de matéria de origem da norma

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2168]
Uma questão para debate. Ao incluir uma nova norma, é possível indicar a matéria legislativa que a originou.O sistema importa a ementa da matéria para uso na norma, com possibilidade de edição para o caso da ementa ter sido mudada durante o processo legislativo. É uma funcionalidade muito útil.
Porém, quando a norma já está registrada e a editamos para indicar a matéria que a originou, o sistema substitui a ementa da norma pela da matéria, e nem sempre é isso que se quer. Embora seja perceptível a mudança, os desavisados podem alterar a ementa da norma sem querer. Estamos registrando matérias antigas, relacionando-as a normas já cadastradas, e tivemos tal problema. Percebi logo e, felizmente, foram poucos os casos a corrigir. O trabalho maior foi comparar as ementas originais com as alteradas. Sugiro que se pense em algo que alerte o operador sobre tal mudança.

**Comment by edwardoliveira** [comment]
Vc acha que a seguinte lógica solucionaria?

`Se norma contém ementa preenchida não importa, caso contrário importa de matéria legislativa`

**Comment by andreagudo** [comment]
Creio que resolva. Penso que isso deva ser implementado também para o campo Indexação, tratado em #2141 .

**Comment by edwardoliveira** [comment]
Verificamos aqui a seguinte situação:

A ementa é obrigatória então sempre será preenchida na criação e atualização. Acontece que na edição, se uma matéria for vinculada então ele puxa a ementa da matéria legislativa, mas não tem como saber quando/se devemos puxar ou não esta ementa. Pensamos em puxar somente se a ementa da norma e a ementa da matéria forem diferentes mas, como bem observou a @tapumar, geralmente elas vão ser diferentes nem que seja por uma vírgula, por exemplo. E voltaríamos ao problema inicial: as vezes não é o que o usuário quer. Estamos em dúvida como delimitar quando puxar ou não a ementa.

**Comment by andreagudo** [comment]
E se puxar a ementa da matéria somente se a da norma estiver em branco?

**Comment by edwardoliveira** [comment]
Pensamos nisso, mas ela nunca vai estar em branco porque é obrigatória.
