### ISSUE TITLE
Autoria de matéria por uma comissão

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#2171]
Matheus da CM de  Pato Branco relatou e eu constatei que: Ao criar uma matéria e designar uma COMISSÃO como autora, as comissões cadastradas com composição não aparecem para seleção. Por acaso, aquelas que ainda não foram compostas por parlamentares aparecem!

![image](https://user-images.githubusercontent.com/30807716/44695636-82967380-aa4a-11e8-9760-a43618514882.png)

**Comment by VictorFabreF** [comment]
Eu olhei a base deles e somente uma comissão está cadastrada como autora.

![image](https://user-images.githubusercontent.com/19825887/44753976-5df7d580-aaf6-11e8-8e44-720cce592ef0.png)

Eles devem então ir em "Adicionar Autor" e adicionar cada comissão como autora. Como na tela abaixo:

![image](https://user-images.githubusercontent.com/19825887/44754033-95ff1880-aaf6-11e8-99b9-ac52049e24ef.png)

Para a comissão aparecer nas opções ela deve também existir na data de apresentação da matéria.

**Comment by 54adal** [comment]
Positivo Victor! Faltou um pouco de observância às configurações!
muito obrigado
