### ISSUE TITLE
Sugestão para o SAPL 3.1

### ISSUE THREAD

**Issue by careassu** [interlegis/sapl#2180]
Gostaria de sugerir o campo de ordenação na pesquisa das Normas Jurídicas, assim como já é disponível na pesquisa de Matérias Legislativas.

**Comment by careassu** [comment]
@marimendes Foi aceita minha sugetão?

**Comment by careassu** [comment]
Bom dia! Queria saber se minha sugestão foi aceita. Obrigado.

**Comment by marimendes** [comment]
@careassu Bom dia, foi aceita e também já foi implementada.
