### ISSUE TITLE
Adicionar sessão plenária: verificação da data de encerramento

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2197]
Ao adicionar uma sessão plenária em a verificação da data de encerramento detecta inconsistência que não existe, já que 31/01/1969 está entre as datas de início e fim da legislatura e da sessão legislativa
![captura de tela de 2018-09-10 15-31-02](https://user-images.githubusercontent.com/19169882/45316961-fd619300-b50e-11e8-9148-6c9d84b24edb.png)
.

**Comment by sconetto** [comment]
Correção feita no PR #2198, assim que aprovado e mergeado a nova versão do SAPL terá a correção do bug citado.

**Comment by andreagudo** [comment]
Ainda não funciona.

**Comment by edwardoliveira** [comment]
**Não reabra as issues passadas mesmo que seja sobre o mesmo assunto.** Melhor criar uma nova porque as issues antigas ficam perdidas lá atrás e daí podemos nunca ver.
