### ISSUE TITLE
Limitar tamanho de arquivos no upload

### ISSUE THREAD

**Issue by eduardocalil** [interlegis/sapl#220]
- Caso o arquivo seja muito grande, o servidor fica lento

**Comment by edwardoliveira** [comment]
+1. Esta issue já tinha sido fechada porque o código foi adicionado ao master. Não faz mais sentido manter aberto. Por outro lado, porções deste trabalho (commit #0066bc1) foram desfeitas na migração pro CRUD automático, como, por exemplo, no forms.py de sessao (vide arqui https://github.com/interlegis/sapl/commit/fabcef2288bd792715c20732ed2f66115f8ec0ea#diff-b1c5928e44b71cda58ea992b924ecbf2 )

Eu vou fechar esta issue porque trabalho dela já foi feito. E abrimos uma issue para verficar como incorporar a checagem de tamanho do arquivo no CRUD automático, ok? @eduardoedson

**Comment by marciomazza** [comment]
Basta fazer um form com as validações necessárias e colocá-lo na CreateView e UpdateView. É bem semelhante ao que foi feito nessa issue. @eduardoedson fez ontem um exemplo disso em parlamentar.

**Comment by edwardoliveira** [comment]
Mas isso não é equivalente ao que tinhamos? A validação estava no form!

**Comment by marciomazza** [comment]
É equivalente, sim. O crud não faz tanta coisa: é só uma forma padronizar o código, reaproveitar fluxo (urls) e alguma interface (templates e layouts). Só isso. Para o resto procurei deixar a coisa o mais livre possível para estendermos alguns pontos e sem engessar demais.

**Comment by edwardoliveira** [comment]
O problema é que a **refatoração do crud está criando algumas (não muitas até onde vi) regressões, isto é, coisas que estavam funcionando no começo deste mês e agora não funcionam mais, ou funcionam parcialmente ou foram descartadas como o formulário simplificado**

_Temos que ficar mais atentos a isso pra não ficarmos dando passos para trás apesar do ganho de reaproveitamento de código, eliminação de duplicação, etc do CRUD_

**Comment by marciomazza** [comment]
É importante ficarmos atentos. Refatorar é sempre um *trade-off*, de fato.

Só peço que percebam que foi mostrado como refatorar esses casos sem perder código. Essa regressão foi apenas um esquecimento pontual. É natural que aconteça sem uma boa cobertura de testes.

O que eu gostaria que nós refletíssemos é que as refatorações que estamos fazendo são exatamente para evitar regressões. O plano é

1. Nós reduzimos a base de código retirando repetições
2. então podemos ter uma cobertura de testes alta
3. aí não teremos mais problemas com regressões

Essa mudança era necessária. Daqui a pouco teremos mais contribuidores da comunidade. É difícil controlar uma base de código como a nossa. Se não tivermos muita atenção com a qualidade interna, rapidamente voltaremos a ter os mesmos problemas do sapl 2.5 e nossa vida será menos feliz.

**Comment by edwardoliveira** [comment]
Concordo 100%. Acontece que tenho visto algumas regressões além dessa. Estamos dando um passo pra frente e dois pra trás em alguns **poucos** casos com essas refatorações. Vamos ter que verificar ao menos pra ver o que estamos perdendo com as refatorações pra abrimos tickets para consertar depois. Acho que estamos no caminho certo ao limparmos e enxugarmos o código, mas perder funcionalidade já implementada frusta demais!
