### ISSUE TITLE
Erro ao abrir documento acessório

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2201]
Não conseguimos abrir o documento acessório abaixo, nem no navegador (Mozilla ou Chorimiun), nem depois de baixado. O digitalizamos e o subimos várias vezes. O original, digitalizado, é aberto normalmente em nossas máquinas.
https://sapl.agudo.rs.leg.br/media/sapl/public/documentoacessorio/1987/5482/respi1487_yPfdho3.pdf

**Comment by edwardoliveira** [comment]
Somente esse PDF que vcs não estão conseguindo abrir?

**Comment by edwardoliveira** [comment]
Parece que este PDF está corrompido. Eu tentei abrir aqui e não consegui. Temos que ver se não foi um erro ainda no SAPL 2.5 (Plone) ou se aconteceu durante migração (trata-se de um documento muito antigo). @marciomazza  Poderia dar uma olhada nisso?

**Comment by edwardoliveira** [comment]
Poderia nos enviar o arquivo PDF via Telegram ou anexando por aqui no Github mesmo?

**Comment by andreagudo** [comment]
Todos os docs abaixo foram gerados e "subidos" hoje. O primeiro dá certo, os demais não:
https://sapl.agudo.rs.leg.br/media/sapl/public/documentoacessorio/1987/5481/respi1387.pdf
https://sapl.agudo.rs.leg.br/media/sapl/public/documentoacessorio/1987/5482/respi1487_yPfdho3.pdf
https://sapl.agudo.rs.leg.br/media/sapl/public/documentoacessorio/1987/5483/respi1587.pdf

**Comment by andreagudo** [comment]
Os arquivos originais são os seguintes:
[respi1387.pdf](https://github.com/interlegis/sapl/files/2371914/respi1387.pdf)
[respi1487.pdf](https://github.com/interlegis/sapl/files/2371915/respi1487.pdf)
[respi1587.pdf](https://github.com/interlegis/sapl/files/2371916/respi1587.pdf)

**Comment by edwardoliveira** [comment]
Estive conversando com o pessoal da INFRA. Pode ter acontecido um erro na hora de subir o primeiro pq as máquinas SAPL estavam em processo de migração. Sabe dizer se o erro se repete sempre que faz o upload do arquivo?

**Comment by edwardoliveira** [comment]
O problema surgiu de uma mudança na INFRA. Qualquer arquivo com mais de 64KB será corrompido. Estamos investigando desde segunda. Não há solução a vista. Não faça upload de arquivos até acharmos uma solução para o problema.

**Comment by andreagudo** [comment]
> Estive conversando com o pessoal da INFRA. Pode ter acontecido um erro na hora de subir o primeiro pq as máquinas SAPL estavam em processo de migração. Sabe dizer se o erro se repete sempre que faz o upload do arquivo?

O erro tem se repetido sempre. Na verdade, o upload é feito, mas o arquivo acaba não abrindo.

**Comment by VictorFabreF** [comment]
@andreagudo, o erro ainda continua ocorrendo?

**Comment by andreagudo** [comment]
Resolvido. Obrigado.
