### ISSUE TITLE
Erro (Server Error 500) em Tramitações em Lote!

### ISSUE THREAD

**Issue by Neybson** [interlegis/sapl#2202]
## Contexto
Desde a atualização para a versão 3.1.114 a tramitação em lote foi prejudicada, quando clicamos em salvar o sistema devolve com: Server Error 500

**Comment by edwardoliveira** [comment]
Se vcs executam localmente poderiam setar o debug para True e simular o erro de novo? Desta vez, deve aparecer a mensagem de erro explícita. Poderia realizar esse procedimento? 

No mais, acabamos de fazer o release da versão 3.1.115. Poderia testar com essa?

PS: Não se esqueça de rodar o `manage.py migrate`.

**Comment by Neybson** [comment]
Quando mudo pra Debug: True o problema é resolvido

**Comment by edwardoliveira** [comment]
Sim. Isso era esperado. Depois que escrevi a mensagem vimos o erro. A próxima versão estará com ele corrigido.
