### ISSUE TITLE
AVISO DE TRAMITAÇÃO

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#2205]
Sugiro a criação de um aviso de tramitação. Ou seja, um projeto foi protocolado e será encaminhado à Presidência - à presidência ao logar no SAPL - será informada com o aviso de tramitação. **Sugiro uma lâmpada vermelha e o aviso.**

**Comment by marimendes** [comment]
Duplicata das issues #1775 e #1505 e #2012
