### ISSUE TITLE
Impressos

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#2207]
Na capa processos - clicar em pesquisar - você preenche o formulário de ficha, pesquisa, seleciona o arquivo e quando vai gerar impresso dá erro - **404 Not Found.**

Exemplo: Requerimento - data inicial: 12/09/2018 - data final: 12/09/2018

Seleciona o arquivo - quando vai gerar o impresso dá erro. - 404 Not Found

**Comment by sconetto** [comment]
@paulot12 não consegui replicar o erro e percebi que na sua issue não tem as demais informações solicitadas pelo nosso novo padrão de issues, poderia prover mais informações, capturas de telas, talvez links para que possamos averiguar melhor? pois, novamente, aqui não replicou, funcionou normalmente.

**Comment by VictorFabreF** [comment]
@paulot12, você está hospedado aqui no Interlegis ou tem hospedagem própria? Qual a sua Casa Legislativa?
Att,
Victor Fabre

**Comment by marimendes** [comment]
Bom dia @paulot12. O erro persiste? você está hospedado aqui no Interlegis ou tem hospedagem própria? Qual a sua Casa Legislativa?
