### ISSUE TITLE
Bloquear matéria

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#2208]
Sugiro que o operador de matéria e sessão plenária possa bloquear a matéria votada, para que não haja nenhuma edição, logo após a votação.

**Comment by edwardoliveira** [comment]
Excelente ideia.

**Comment by edwardoliveira** [comment]
De acordo com as novas diretrizes adotadas no repositório do SAPL, as **novas _issues_** abertas para correções de erros (_bugs_)e solicitações de novas funcionalidades (_features_) devem ser abertas seguindo o mais novo [template](https://github.com/interlegis/sapl/blob/3.1.x/.github/ISSUE_TEMPLATE.md).  Segue imagem de exemplo:

![image](https://user-images.githubusercontent.com/11671985/45773325-65575e00-bc20-11e8-849a-c028aced04e4.png)

Como o GitHub suporta estilização via MarkDown os textos que estão entre `<!-- -->` são tidos como comentários e podem ser apagados, os textos ali
são apenas para auxiliar novos usuários a se orientarem na abertura. Nem todas as seções precisam ser preenchidas mas espera que ao menos essas contenham dados:
- Para bugs:
  - Comportamento Atual
  - Comportamento Esperado
  - Passos para reproduzir
  - Imagens

- Para features:
  - Comportamento Esperado
  - Possível solução
  - Contexto
  - Imagens (se possível e aplicável)

Mas **LEMBREM-SE** quanto mais informações e tópicos preenchidos, melhor fica a sua _issue_ e aumenta a chance de ser solucionada rapidamente e efetivamente.

Para saber mais sobre MarkDown acesse o link: https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf

Favor reabrir a _issue_ mantendo o padrão solicitado!
