### ISSUE TITLE
Matérias Legislativas: Local Origem como critério de diferenciação

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2210]
Apenas uma ideia para debate.
O campo Local Origem poderia ser usado como critério de diferenciação de matérias de mesmo tipo, número e ano. Há casas em que a numeração depende da origem, caso de Agudo até 1998. Ao registrar matérias antigas de origem no Legislativo, temos que usar numeração superior para diferenciá-las das de origem no Executivo (P. ex: PL 1/1998-E e PL 1001/1998L).

**Comment by edwardoliveira** [comment]
**Infelizmente** isso não é tecnicamente muito arriscado (mexe em muitas partes do sistema e gerar uma série de problemas de consistência e recuperação de dados), portanto **não será feito.**
