### ISSUE TITLE
Acesso restrito

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#2219]
Protocolei um documento administrativo e selecionei acesso restrito, mas fica visível para todos. Acesso restrito - sim.

**Comment by edwardoliveira** [comment]
O acesso restrito é somente para não mostrar esse documento para usuários externos não logados no sistema, caso o acesso aos documentos administrativos tenham sido marcados como "Ostensivo". Quaisquer usuários logados podem ter acesso ao arquivo ainda.
