### ISSUE TITLE
Definir tamanho do logotipo

### ISSUE THREAD

**Issue by eduardocalil** [interlegis/sapl#223]
Dependendo das dimensões (x,y) da imagem, se for muito grande, o logo fica desproporcional  com o resto da tela.

**Comment by edwardoliveira** [comment]
Essa issue é tranquila o suficiente então vou atribuir a vc, ok?

Vc tem uma forma de mitigar esse erro que é simples (passo 1):

1. definir o height e o width na tag <img> para o logo não ficar desproporcinal;
 
2. procurar uma forma de fazer crop na imagem de upload (segundo o Mazza, tem lib do Django que já faz isso).
