### ISSUE TITLE
A adição de matéria legislativa não está funcionando corretamente

### ISSUE THREAD

**Issue by eduardocalil** [interlegis/sapl#224]
A tela está lançando uma mensagem de erro quando não precisa

**Comment by marciomazza** [comment]
O problema é que o campo MateriaLegislativa.anexadas está obrigatório.
É um many-to-many, e é preciso entender melhor como será a interface a implementar. E me parece que não deve ser obrigatório.

**Comment by edwardoliveira** [comment]
Tá. Eu vou dar uma olhada nisso asap.

**Comment by eduardoedson** [comment]
Uma forma que vi de arrumar isso, seria colocar o campo 'anexadas' requerided=False no form, mas provavelmente teria que fazer uma nova view e não utilizar o crud automatico

**Comment by edwardoliveira** [comment]
O mais bizarro: se colocar ``blank=True`` no campo ``anexadas`` de ``MateriaLegislativa`` gera *outro* erro (**Cannot set values on a ManyToManyField which specifies an intermediary model. Use materia.Anexada's Manager instead.**), mas ainda assim o registro é salvo! :open_mouth:

**Comment by eduardoedson** [comment]
Ao que parece, se adicionar o campo 'anexadas' ao exclude e deixa-lo blank=True, resolve o problema. Porém não sei se é possível adicionar campos ao exclude no Crud

**Comment by edwardoliveira** [comment]
Boa @eduardoedson !!! O lance do blank=True eu já tinha descoberto ontem, mas esse lance de exclude é uma boa se pudermos estender o CRUD "auto-mágico" pra receber adicionar cláusulas de exclude. Eu vejo 3 possíveis soluções para esta issue:

1. Estender o CRUD automático pra receber este parâmetro de exclude (atualmente vai lista vazia). Vou olhar hoje pela manhã a viabilidade de se fazer isso.

2. Refazer o Editar Materia Legislativa como um form normal, sem geração automática, como é o ProtocoloSimplificado.
