### ISSUE TITLE
Pauta da Sessão - Impressão PDF erro 500

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#2244]
Em pauta da Sessão, ao clicar em impressão em pdf ocorre erro 500

http://sapl.camarabento.rs.gov.br/relatorios/pauta-sessao/434/

**Comment by edwardoliveira** [comment]
Reinicie o servidor como debugging=True e reproduza o erro. Envie o stack trace como texto pra gente.

**Comment by VictorFabreF** [comment]
Não consegui replicar o erro localmente com a minha base. Você poderia por favor disponibilizar um dump da sua base?

**Comment by DtiLegBG** [comment]
Environment:


Request Method: GET
Request URL: http://saplbeta.camarabento.rs.gov.br/relatorios/pauta-sessao/408/

Django Version: 1.9.13
Python Version: 3.5.2
Installed Applications:
('django_admin_bootstrapped',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_extensions',
 'djangobower',
 'bootstrap3',
 'crispy_forms',
 'easy_thumbnails',
 'image_cropping',
 'floppyforms',
 'haystack',
 'sass_processor',
 'rest_framework',
 'reversion',
 'reversion_compare',
 'whoosh',
 'speedinfo',
 'sapl.audiencia',
 'sapl.base',
 'sapl.crud',
 'sapl.parlamentares',
 'sapl.comissoes',
 'sapl.materia',
 'sapl.norma',
 'sapl.sessao',
 'sapl.lexml',
 'sapl.painel',
 'sapl.protocoloadm',
 'sapl.redireciona_urls',
 'sapl.compilacao',
 'sapl.api',
 'sapl.rules',
 'debug_toolbar',
 'rest_framework_docs')
Installed Middleware:
('debug_toolbar.middleware.DebugToolbarMiddleware',
 'reversion.middleware.RevisionMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')



Traceback:

File "/var/interlegis/.virtualenvs/sapl/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/var/interlegis/.virtualenvs/sapl/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/interlegis/sapl/sapl/relatorios/views.py" in relatorio_pauta_sessao
  1011.         sessao, casa)

File "/var/interlegis/sapl/sapl/relatorios/views.py" in get_pauta_sessao
  1109.              numeracao = numeracao.first()

Exception Type: AttributeError at /relatorios/pauta-sessao/408/
Exception Value: 'Numeracao' object has no attribute 'first'

**Comment by edwardoliveira** [comment]
Realmente introduzimos um bug semana passada. Verifique se foi consertado agora.

**Comment by DtiLegBG** [comment]
Resolvido ! Obrigado !
