### ISSUE TITLE
Erro Server Error (500) ao criar Frente Parlamentar

### ISSUE THREAD

**Issue by cintiaelisa** [interlegis/sapl#2245]
## Comportamento Esperado

Ao tentar criar uma frente parlamentar utilizando o menu Sistema > Tabelas Auxiliares > Frente parlamentares > Adicionar Frente Parlamentar. 
Ao adicionar o dados e clicar em Salvar o sistema retorna tela branca com o erro "Erro Server Error (500)".

## Comportamento Atual

Erro: Server Error (500)

## Passos para Reproduzir (para bugs)

1. Sistema > Tabelas Auxiliares > Frente parlamentares > Adicionar Frente Parlamentar.
2. Preencher os dados
3. Clicar em Salvar
4. Server Error (500)

## Imagens do Ocorrido

* Versão usada (_Release_): sapl:3.1.117
* Nome e versão do navegador: Firefox e Chrome
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Favor atualizar para a versão 3.1.118 e verificar se o erro ainda ocorre. Importante: estamos com problema na versão 3.1.119, portanto deve ser para a 3.1.118 mesmo.

**Comment by cintiaelisa** [comment]
O erro persiste na versão 3.1.118.

**Comment by cintiaelisa** [comment]
Edward
Poderia por gentielza informar o caminho completo onde se encontra o arquivo .env a qual vc se refere?
Desde já agradeço,

**Comment by edwardoliveira** [comment]
Vcs estão executando como o SAPL? Está hospedado no Interlegis? Estão usando instâncias Docker ou está sendo direto no host? O host é Linux?

**Comment by cintiaelisa** [comment]
Docker/ Linux Ubuntu

**Comment by cintiaelisa** [comment]
O erro persiste na versão 3.1.120

**Comment by cintiaelisa** [comment]
Edward, poderia orientar a localização do .env no Docker?
