### ISSUE TITLE
Tramitação

### ISSUE THREAD

**Issue by Matheuscmpb** [interlegis/sapl#2246]
Quando vamos tramitar alguma matéria que tem E-mail cadastrado na opção "acompanhar matéria", apresenta essa mensagem.
![image](https://user-images.githubusercontent.com/42938450/45958172-1ed17d00-bfed-11e8-83e9-135e72ee6672.png)

**Comment by edwardoliveira** [comment]
Sim, a imagem está correta. Este alerta significa que vocês não configuraram nenhum servidor de email para enviar o status da tramitação a possíveis interessados. Mas a tramitação ocorre normalmente.

Vamos estudar outras formas de colocar essa mensagem de forma menos intrusiva para as próximas versões. Por hora, pode ignorar essa mensagem específica. É apenas um alerta.
