### ISSUE TITLE
Erro ao adicionar Período de Composição das Comissões!!

### ISSUE THREAD

**Issue by Neybson** [interlegis/sapl#2249]
Fiz a atualização para aversão 3.1.119 e não consigo mais atribuir o período de composição das Comissões Técnicas, dá: Server Error 500!

**Comment by edwardoliveira** [comment]
A versão 3.1.120 vai resolver esse problema por hora, mas ainda deve demorar umas duas horas para terminar o build da imagem. Por enquanto utilizem a versão 3.1.118.
