### ISSUE TITLE
Quebra de página nos texto articulados

### ISSUE THREAD

**Issue by MaristelaKruger** [interlegis/sapl#2253]
## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Imagens do Ocorrido

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by MaristelaKruger** [comment]
Ao criar Projeto de Lei em texto articulado percebemos que a justificativa do projeto aparece na mesma página dos dispositivos do Projeto. Então gostaria de deixar como sugestão se possível ter uma quebra de página, para que a justificativa do Projeto seja iniciada em uma nova página.

**Comment by sconetto** [comment]
De acordo com as novas diretrizes adotadas no repositório do SAPL, as **novas _issues_** abertas para correções de erros (_bugs_)e solicitações de novas funcionalidades (_features_) devem ser abertas seguindo o mais novo [template](https://github.com/interlegis/sapl/blob/3.1.x/.github/ISSUE_TEMPLATE.md).  Segue imagem de exemplo:

![image](https://user-images.githubusercontent.com/11671985/45773325-65575e00-bc20-11e8-849a-c028aced04e4.png)

Como o GitHub suporta estilização via MarkDown os textos que estão entre `<!-- -->` são tidos como comentários e podem ser apagados, os textos ali
são apenas para auxiliar novos usuários a se orientarem na abertura. Nem todas as seções precisam ser preenchidas mas espera que ao menos essas contenham dados:
- Para bugs:
  - Comportamento Atual
  - Comportamento Esperado
  - Passos para reproduzir
  - Imagens

- Para features:
  - Comportamento Esperado
  - Possível solução
  - Contexto
  - Imagens (se possível e aplicável)

Mas **LEMBREM-SE** quanto mais informações e tópicos preenchidos, melhor fica a sua _issue_ e aumenta a chance de ser solucionada rapidamente e efetivamente.

Para saber mais sobre MarkDown acesse o link: https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf

Favor reabrir a _issue_ mantendo o padrão solicitado!
