### ISSUE TITLE
Usuário com role parlamentar não consegue editar parlamentares

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2264]
## Comportamento Esperado
O usário com role parlamentar pode editar dados dos parlamentares

## Comportamento Atual
O usário com role parlamentar não tem acesso à edição de dados dos parlamentares

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/parlamentar/61

## Contexto
O usuário com role adminstrador tem que poder fazer tal edição

## Imagens do Ocorrido
![captura de tela de 2018-09-26 16-21-38](https://user-images.githubusercontent.com/19169882/46104337-86ccc280-c1a9-11e8-825b-0db931391a0d.png)
![captura de tela de 2018-09-26 16-23-04](https://user-images.githubusercontent.com/19169882/46104359-95b37500-c1a9-11e8-926d-e6c6976ce4f8.png)

## Seu Ambiente
* Versão usada (_Release_): 3.1.120
* Nome e versão do navegador: Firefox Quantum 62.0 (32-bit)
* Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 32 bits

**Comment by edwardoliveira** [comment]
A role parlamentar era para votação e autoria de matérias. A role que permite editar os parlamentares é Operador Geral, que eu me lembro.

**Comment by andreagudo** [comment]
Ok... vou tentar.

Em Qua, 26 de set de 2018 4:43 PM, Edward <notifications@github.com>
escreveu:

**Comment by andreagudo** [comment]
Funcionou. Obrigado, @edwardoliveira !
