### ISSUE TITLE
Pauta de Sessão em HTML e PDF diferente quanto à situação atual de tramitação

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#2265]
## Comportamento Esperado
A situação para matérias do expediente e ordem dia deve ser igual para pauta de sessão em HTML e em PDF.

## Comportamento Atual
O status atual difere entre PDF e HTML

## Possível Solução
Portar o trecho de código que recupera a situação do HTML para o PDF (segundo o usuário o HTML está correto).

## Imagens do Ocorrido
![pauta sessao](https://user-images.githubusercontent.com/9326037/46163681-37969880-c262-11e8-932e-8e9b95f490a5.jpg)
![pauta sessao - pdf](https://user-images.githubusercontent.com/9326037/46163682-37969880-c262-11e8-9319-53a81c1bdcc6.jpg)

## Texto do usuário

"Boa tarde,
Quando pesquisamos uma determinada pauta e clicamos "impressão PDF" podemos verificar que o campo 'situação' é diferente em cada um. Na pauta em si traz o status correto, mas no PDF traz a primeira tramitação.
Segue anexo."

Nome da Cidade: | Pradópolis
Estado: | São Paulo

**Comment by edwardoliveira** [comment]
@marimendes O código do PDF é esse aqui: https://github.com/interlegis/sapl/blob/3.1.x/sapl/relatorios/views.py#L744-L762 

O código do HTML é esse: https://github.com/interlegis/sapl/blob/3.1.x/sapl/sessao/views.py#L2573-L2578

Provavelmente tem que fazer pra expediente_materia e ordemdia_materia.

**Comment by sconetto** [comment]
@edwardoliveira uma dúvida se dá devido ao fato de não conseguir replicar o comportamento, aqui em minha máquina trabalhando em conjunto com a @marimendes com o dump de Fortaleza o comportamento não se repetiu.
