### ISSUE TITLE
Código de certificado digital

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#2267]
## Comportamento Esperado

Incluir um código de verificação no próprio site do SAPL, para ser assinatura com certificado digital, nas proposituras elaboradas nos textos articulados. 

## Comportamento Atual

Atualmente não há a opção de assinar com certificado digital, ou seja código verificador de autenticidade, nos textos articulados.

**Comment by edwardoliveira** [comment]
Repetido em https://github.com/interlegis/sapl/issues/969
