### ISSUE TITLE
Impressos da tela Pesquisa Matéria Legislativas com links

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2270]
## Comportamento Esperado
O resultado da impressão das telas deve ser idêntica a elas, sem links.

## Comportamento Atual
Onde há links, são impressos também endereços. Ocorre no timbre e nos links de "Adicionar matéria", "Fazer nova pesquisa", identificação da matéria, Documentos acessórios, Texto original e Acompanhar Matéria.

## Passos para Reproduzir (para bugs)
Imprimir a seguinte página
https://sapl.agudo.rs.leg.br/materia/pesquisar-materia?tipo=3&numero=3&numeracao__numero_materia=&numero_protocolo=&ano=2018&data_apresentacao_0=&data_apresentacao_1=&data_publicacao_0=&data_publicacao_1=&autoria__autor=&autoria__primeiro_autor=&autoria__autor__tipo=&relatoria__parlamentar_id=&local_origem_externa=&tramitacao__unidade_tramitacao_destino=&tramitacao__status=&em_tramitacao=&o=&materiaassunto__assunto=&indexacao=&ementa=

## Contexto
Simples impressão da tela.

## Imagens do Ocorrido
![captura de tela de 2018-09-28 10-02-58](https://user-images.githubusercontent.com/19169882/46210030-f0fa7a00-c305-11e8-9aea-7e3b0749b938.png)

## Seu Ambiente
* Versão usada (_Release_): 3.1.120
* Nome e versão do navegador: Chromium Versão 69.0.3497.81 (Versão oficial); Firefox Quantum 62.0 (64-bit)
* Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by sconetto** [comment]
O pessoal irá atualizar a sua *release* para a versão mais nova onde tem a correção desse erro.

**Comment by edwardoliveira** [comment]
Não tiver solucionado basta reabrir a issue.
