### ISSUE TITLE
Inclusão de texto nas normas 

### ISSUE THREAD

**Issue by neynunes** [interlegis/sapl#2271]
## Comportamento Esperado

Sugiro que seja acrescentado o seguinte texto padrão ao final das normas jurídicas:

* O SAPL tem cunho informativo, educativo e é a fonte de publicação eletrônica desta Câmara dada sua capacidade de abrangência, porém, não dispensa a consulta aos textos oficiais impressos para a prova da existência de direito, nos termos do art. 337 do Código de Processo Civil.

* ALERTA-SE, quanto as compilações:
O Dicionário Jurídico Brasileiro Acquaviva define compilação de leis como a “reunião e seleção de textos legais, com o fito de ordenar tal material, escoimando-o das leis revogadas ou caducas. A compilação tem por finalidade abreviar e facilitar a consulta às fontes de informação legislativa. Na compilação, ao contrário do que ocorre na consolidação, as normas nem mesmo são reescritas.” 

PORTANTO:
A Compilação de Leis deste Município é uma iniciativa mantida pela Câmara, em respeito a sociedade e ao seu direito transparência, com o fim de contribuir com o moroso processo de pesquisa de leis e suas relações. Assim, dado às limitações existentes, a compilação ofertada é um norte relevante para constituição de tese jurídica, mas não resume todo o processo e, não se deve, no estágio atual, ser referência única para tal.

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Imagens do Ocorrido

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by sconetto** [comment]
De acordo com as novas diretrizes adotadas no repositório do SAPL, as **novas _issues_** abertas para correções de erros (_bugs_)e solicitações de novas funcionalidades (_features_) devem ser abertas seguindo o mais novo [template](https://github.com/interlegis/sapl/blob/3.1.x/.github/ISSUE_TEMPLATE.md).  Segue imagem de exemplo:

![image](https://user-images.githubusercontent.com/11671985/45773325-65575e00-bc20-11e8-849a-c028aced04e4.png)

Como o GitHub suporta estilização via MarkDown os textos que estão entre `<!-- -->` são tidos como comentários e podem ser apagados, os textos ali
são apenas para auxiliar novos usuários a se orientarem na abertura. Nem todas as seções precisam ser preenchidas mas espera que ao menos essas contenham dados:
- Para bugs:
  - Comportamento Atual
  - Comportamento Esperado
  - Passos para reproduzir
  - Imagens

- Para features:
  - Comportamento Esperado
  - Possível solução
  - Contexto
  - Imagens (se possível e aplicável)

Mas **LEMBREM-SE** quanto mais informações e tópicos preenchidos, melhor fica a sua _issue_ e aumenta a chance de ser solucionada rapidamente e efetivamente.

Para saber mais sobre MarkDown acesse o link: https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf

Favor reabrir a _issue_ mantendo o padrão solicitado!

**Comment by sconetto** [comment]
@neynunes se atente a escrever de acordo com cada tópico, para que o pedido fique logicamente coeso e não simplesmente o pedido em um único tópico da issue.
