### ISSUE TITLE
Resolução tabelas em telas pequenas

### ISSUE THREAD

**Issue by IsaacCastro** [interlegis/sapl#2272]
Comunidade, 

**Problema**:
Tenho observado uma quebra de layout do SAPL 3.1 em telas com resolução menor ou igual 512px de largura em média, quando se exibe o conteúdo de tabelas como: mesa-diretora, comissao, parlamentar, norma.
A disfunção estética do layout se dá pela relação das tabelas com o cabeçalho e rodapé em telas acima informadas.

**Solução**:
Não sou expert no assunto, mas pensei na criação de uma media queries dentro do app.css

```
@media screen and (max-width: 512px) {
.table{
    width: auto;
    white-space: normal;
    display:block;
    overflow-x: auto;}
}
```

Respeitosamente,
Isaac Castro (Câmara São José do Divino-PI)

**Comment by edwardoliveira** [comment]
Vc poderia testar essa mudança e nos reportar o resultado com screenshots?

Obrigado.

**Comment by IsaacCastro** [comment]
Bom dia Eduardo.
Estou com as mudanças prontas em screenshots. Existe outro local aqui no git pra tratarmos de código?
Tenho algumas sugestões de mudança de css.

**Comment by IsaacCastro** [comment]
**Problema**:

O problema reside basicamente na exibição das tabelas (com várias colunas), em resoluções menores, sobretudo, de 490px, conforme print abaixo.
![print_comissao_sapl_31](https://user-images.githubusercontent.com/43033220/46251208-32347c00-c423-11e8-8824-3e29f112a82c.jpg)

**Aplicação de Solução**:
Criei uma media querie (dentro de app.css) para exibição da classe (.table) a partir de 512px, conforme print abaixo: 
![print_comissao_sapl_31_uso_queries](https://user-images.githubusercontent.com/43033220/46251254-2d23fc80-c424-11e8-8f6a-e22ee03a7104.jpg)

Obrigado.

**Comment by edwardoliveira** [comment]
Se vc não souber fazer PR poderia anexar o snippet de código aqui para integramos?

**Comment by marimendes** [comment]
@IsaacCastro isso foi feito nesse merge: https://github.com/IsaacCastro/sapl/pull/1, certo?
