### ISSUE TITLE
Acesso restrito

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#2273]
## Comportamento Esperado

Acesso restrito a documentos administrativos e protocolos para só visualizarem nas unidades de tramitação na qual aquele documento está ou foi tramitado. 

## Comportamento Atual

Todos os logados visualizam os protocolos e documentos administrativos

**Comment by edwardoliveira** [comment]
Issue repetida: https://github.com/interlegis/sapl/issues/2262
