### ISSUE TITLE
Criar 'flag' que idique última tramitação

### ISSUE THREAD

**Issue by eduardocalil** [interlegis/sapl#228]
Criar uma 'flag' que diga se tramitação é a última de uma determinada matéria.

**Comment by marciomazza** [comment]
Essa "flag" não existia antes e a retiramos por ser redundante?
Por favor relatem qual a motivação da issue, para podermos pensar se há uma solução alternativa.

**Comment by eduardocalil** [comment]
Essa seria um possível solução para a pesquisa por Status da Tramitação.

**Comment by marciomazza** [comment]
Essa flag, de fato, existia antigamente e foi retirada por ser reduntante. É possível encontrar a última tramitação sem ela, com uma consulta.

Só consideraremos uma flag desse tipo como otimização, depois de:
* tentar fazendo consultas normais
* ajustar índices no banco, se necessário
* e ainda assim ficar lento
