### ISSUE TITLE
Docker para desenvolvimento

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#229]
Precisamos de uma configuração Docker para ambiente de desenvolvimento.
Deve ser montado de forma tal que o desenvolvedor tenha um ambiente rodando apenas seguindo esses dois passos:

1. Clonar o repositório
2. Rodar o docker (via docker compose)

**Comment by eduardoedson** [comment]
No caso já existe isso nesse branch: https://github.com/interlegis/sapl/tree/Docker

**Comment by eduardoedson** [comment]
Porém é necessário rodar um outro comando, caso queira restaurar o banco.

**Comment by marciomazza** [comment]
Poxa, que bom. Essa ramo não foi juntado ao `master` já?

**Comment by eduardoedson** [comment]
Ainda não

**Comment by marciomazza** [comment]
@edwardoliveira Existe algo impedindo que seja juntado ao master?

**Comment by edwardoliveira** [comment]
Não que eu saiba. Go ahead!

**Comment by marciomazza** [comment]
Essa tarefa é essencial para receber novos membros da comunidade no projeto. Sem ela vamos ser tragados em pedidos de ajuda de configuração de ambiente e dúvidas no gitec.

**Comment by eduardoedson** [comment]
Na forma atual está rodando, estou tentando melhorar algumas coisas
https://github.com/interlegis/sapl/tree/229-Docker

**Comment by edwardoliveira** [comment]
+1.
