### ISSUE TITLE
Anulação de proposição após envio e recepção

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#2293]
## Comportamento Esperado
Permitir que o autor possa sinalizar como nula ou cancelada, uma determinada proposição (indesejada) que foi enviada e recebida, caso necessite.

## Comportamento Atual
Constatado o engano ou erro por parte do autor após o envio e recepção de uma proposição, o sistema permitirá a exclusão da Matéria gerada, mas não a exclusão da proposição (por questões de segurança e/ou integridade do banco).

## Possível Solução
Permitir que o autor possa sinalizar em um campo tipo Observação, que aquela proposição apesar de enviada e recebida, não vigorou em função de algum erro ou engano constatado posteriormente.  E se a matéria correspondente for excluída, que seja sinalizado no campo CONTEÚDO GERADO (na lista de proposições) que a mesma matéria foi excluída, conforme exemplos a seguir:

![image](https://user-images.githubusercontent.com/30807716/46735811-b8e02900-cc6d-11e8-9440-62e109fe38fa.png)

![image](https://user-images.githubusercontent.com/30807716/46735606-13c55080-cc6d-11e8-97d0-358515b63bf8.png)

## Contexto
Caso o autor constate o erro posteriormente à recepção da matéria, não terá como apagar e nem sinalizar que a mesma não vigorou. Certamente enviará outra proposição no lugar desta e, a lista de proposições enviadas poderá ficar confusa entre as bem sucedidas e as fracassadas...

**Comment by edwardoliveira** [comment]
@LeandroRoberto Essa coluna _Conteúdo Gerado_ mexe com aquele _conteudo_gerado_related_ do qual eu não entendo nada, poderia nos indicar como colocar status de Excluído? Acho que seria um novo campo `excluido` (true/false) não? Da mesma forma que em protocolo...
