### ISSUE TITLE
Container Docker (postgresql:9.6.8-alpine) não inicia

### ISSUE THREAD

**Issue by FabioFM** [interlegis/sapl#2296]
## Descrição
Eu administro a instalação e administração local do SAPL 3.1 aqui na Câmara Mun. de Piedade - SP. Uso para instalar e atualizar o SAPL o Docker que roda na versão mais recente do Ubuntu (18.04 LTS) e nunca tive problemas no último ano, com a exceção da última atualização.

Atualizei o SAPL via Docker da versão 3.1.102 para a 3.1.124 e após esta atualização, o SAPL não iniciava mais.

Ao usar o comando "docker ps", notei que o container relativo ao postgresql não parava de reiniciar, como mostra a figura abaixo:
![git1](https://user-images.githubusercontent.com/44030550/46746319-36636380-cc85-11e8-96b0-8a897201127a.PNG)

Usei o comando "docker logs --tail 50 [ID do container Postgresql]" para saber o que ocorria e o comando retornava repetidamente esta mensagem:

> DETAIL: File "/var/lib/postgresql/data/PG_Version" does not contain valid data.
> FATAL: "/var/lib/postgresql/data" is not a valid data directory

Notei que nos arquivos docker-compose.yml anteriores publicados aqui no GitHub, a imagem especificada para o Postgresql era "postgres:latest" e que agora os novos arquivos docker-compose.yml especificam a imagem Postgresql para "postgres:9.6.8-alpine".
Editei o arquivo docker-compose.yml do meu servidor local para pegar a imagem "postgres:latest" e também com a última versão do SAPL (imagem "interlegis/sapl:3.1.124") para voltar a funcionar o SAPL e deu certo.

Não sei se instalações novas (sem dados) do SAPL não dá erro no container docker do postgresql, mas no meu caso que já tinha uma base de dados de versões anteriores, dá o erro do container docker não parar de reiniciar, como especificado acima.

## O Arquivo docker-compose.yml que tive que usar para o SAPL voltar a funcionar
[docker-compose.txt](https://github.com/interlegis/sapl/files/2465414/docker-compose.txt)
 OBS: Tirei as informações sensíveis do arquivo e mudei a extensão para .txt para poder fazer o upload.

## Considerações Finais
Não sei se o problema que relatei pode ser considerado um bug, mas achei melhor avisá-los sobre isso, além de eu ter ficado com receio de ficar sem poder atualizar o SAPL no futuro se não for mais possível usar a imagem docker "postgres:latest".

**Comment by FabioFM** [comment]
A versão do Postgresql que roda aqui (imagem docker "postgres:latest") é a 10.1

**Comment by edwardoliveira** [comment]
Atualizamos a versão para 10.5-alpine, pois é desaconselhável usar o "latest".
