### ISSUE TITLE
Alterar DockerFile para executar DBMigrations

### ISSUE THREAD

**Issue by fscpoa** [interlegis/sapl#2298]
Alterar DockerFile para executar DBMigrations

## Comportamento Esperado
Executar scripts de migração automaticamente ao gerar Container.

## Comportamento Atual
Não executa os scripts de migração, gerando a necessidade de execução manual ou problemas de ambiente.

## Possível Solução
Inclusão das linhas descritas abaixo no DockerFile:
RUN python manage.py makemigrations
         python manage.py migrate

**Comment by edwardoliveira** [comment]
Obrigado pela sugestão, mas para rodar estes comandos precisamos ter um DB configurado e acessível. Mas o banco é definido em outro container (sapldb). Estes comandos são a configuração de dados do sistema, portanto devem ser feitos no repositório de dados que vai ser efetivamente utilizado pelo sistema. Mesmo que tivéssemos acesso local a um banco de produção na hora de construir o build da imagem, não há garantia alguma de que esse banco seria o utilizado na execução do container do SAPL (e como faríamos isso nos builds automáticos do Docker Hub? Apontar pra um banco externo via internet?! :scared:). Pra instalar o sistema Django precisamos de um BD configurado e acessível, inclusive pra comandos que na minha opinião **não deveriam prescindir de conexão com o BD** (ex: collecstatic). Por isso optamos por rodar makemigrations e migrate na execução do container. É ideal? Não. Mas nessa fase já devemos apontar pro DB de produção e rodamos esse sistema em ambiente multi-tenant com centenas de instâncias, cada qual com seu BD dedicado. Rodar o BD e o sistema Django ambos dentro do mesmo container está fora de cogitação, pois precisamos de controle mais fino de memória, CPU, I/O entre as duas partes. E colocar tudo junto no mesmo container invalida a própria proposta de usar containers. Nossa solução encontrada foi criar um banco dummy baseado no SQLite no Dockerfile de tal forma que pudéssemos rodar coisas como collecstatic e django-bower sem se importar realmente com a conexão de BD. E no startup do container rodar os comandos stateful como migrate já com uma conexão real ao container final do BD.

Mas estamos abertos a sugestões, sempre. O que vc sugere pra resolver ou uma solução melhor para essas questões?
