### ISSUE TITLE
Matéria Legislativa: repetir o link da Dada de Votação na aba Início

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2305]
## Comportamento Esperado
O link Data de Votação poderia aparecer também nos detalhes da matéria, na aba Início, antes de Norma Jurídica Relacionada.

## Comportamento Atual
Tal link aparece somente na primeira tela de pesquisa de matéria.

## Contexto
É comum pesquisar-se matérias a partir das normas geradas. Nesse caso, ao encontrar-se a matéria desejada, vai-se diretamente a seus detalhes, onde não há o link Data de Votação, o que ocorre somente pesquisando diretamente pelas matérias. A implementação seria importante para o cidadão ter acesso fácil a detalhes da sessão, como a ata, o que o TCE/RS está cobrando no caso das aprovações de contas.

## Imagens do Ocorrido
![out-1](https://user-images.githubusercontent.com/19169882/47020160-1f15f180-d12f-11e8-8fac-47c279f44b3d.gif)

## Seu Ambiente
* Versão usada (_Release_): 3.1.121
* Nome e versão do navegador: Chromium Versão 69.0.3497.81 (Versão oficial)
* Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
![image](https://user-images.githubusercontent.com/9326037/47034165-f56bc300-d14c-11e8-9948-e65f7d0ecfe4.png)

Na próxima versão (127) estará disponível o link para Data de Votação no detalhe da matéria, se disponível.
