### ISSUE TITLE
Atividades Legislativas/Impressos/Capa Processo - faltando dados

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#2308]
Incluir os dados do protocolo na parte superior como constam na etiqueta com código de barras. Ou seja, número e data protocolo e o código de barras.

**Comment by marimendes** [comment]
@edwardoliveira Fiquei com uma dúvida. Quando uma matéria está em processo(capa do processo), ela já foi protocolada?

**Comment by edwardoliveira** [comment]
@marimendes Pelo que pude ver aqui no código, é uma impressão simples de matéria legislativa, isto é, ele não checa protocolo.
