### ISSUE TITLE
SUGESTÃO - Normas Jurídicas: Geração de relatórios e estatísticas

### ISSUE THREAD

**Issue by lizianem** [interlegis/sapl#2313]
## Comportamento Esperado
Sugiro possibilidade de emissão de relatórios e estatísticas para o módulo Normas Jurídicas, para que possamos controlar o acervo de atos, aqueles revogados, atos vigentes, atos faltantes, atos mais acessados, etc.

## Comportamento Atual
Atualmente não permite a pesquisa e tampouco a emissão de relatórios nesse módulo, por atos revogados por assunto, por exemplo.

## Possível Solução
Implementar uma pesquisa com mais campos e que possibilidade pesquisa combinada (avançada) através do uso de operadores boleanos. E também permitir a geração de relatórios pré-prontos para as seguintes situações:
1 - relatório de atos revogados
2 - relatório de atos vigentes
3 - relatório de atos faltantes
4 - relatório de atos mais acessados
5 - relatório de atos publicados por mês
6 - estatística de acesso por ano ou período temporal
7 - estatística de publicação: quantos atos foram inseridos no mês, ou ano, ou período x
8 - estatística de atos revogados

**Comment by edwardoliveira** [comment]
O que são `atos faltantes`?

**Comment by marimendes** [comment]
@edwardoliveira a ideia seria colocar esses outros relatórios na aba de relatórios mesmo ou pensou em algum lugar diferente?

**Comment by edwardoliveira** [comment]
@marimendes Mari, a idéia seria agrupá-los em uma tela de Relatórios de Norma. Mas temos que ver como calma porque alguns desses relatórios me parecem inviáveis de serem implementados no modelo atual do SAPL (1, 3, 4, 8). Outros (2, 5, 7) parecem passíveis de serem feitos.
