### ISSUE TITLE
Editor de Texto Articulado para Normas Juridicas

### ISSUE THREAD

**Issue by rosenocmcc** [interlegis/sapl#2318]
## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Imagens do Ocorrido

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Preencha os campos pedidos na abertura do ticket. Nós mudamos as regras e agora esses campos sao

**Comment by rosenocmcc** [comment]
Pois é. Eu não entendi. Preenchi o campo e só aparece o título. Vou refazer.
Obrigado.


Em sex, 19 de out de 2018 08:46, Edward <notifications@github.com> escreveu:
