### ISSUE TITLE
Anexada

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#2321]
## Comportamento Esperado

Quando anexar uma matéria visualizar o autor e disponibilizar já o arquivo. Como na versão 2.5. 

## Comportamento Atual

Não aparece o autor. Temos que clicar no nome do arquivo para ir à página e baixá-lo.

**Comment by tapumar** [comment]
Bom dia, @paulot12.
Pode dar mais detalhes? Quando anexar a matéria onde? Em proposição?

**Comment by tapumar** [comment]
Bom dia @paulot12, 
Pode dar mais detalhes? Onde você anexando a matéria? Em proposição?

**Comment by paulot12** [comment]
Bom dia!


Conforme exemplo da versão 2.5

![pastedimage](https://user-images.githubusercontent.com/26234950/47299995-d9a36980-d5f1-11e8-9633-b8a187b235b0.png)

Matéria anexada com nome do autor e já a disponibilização do arquivo

![pastedimage 1](https://user-images.githubusercontent.com/26234950/47300051-f9d32880-d5f1-11e8-9ac9-062078d51d2a.png)

**Comment by paulot12** [comment]
No envio da proposição eu informo a matéria a ser anexada.

**Comment by paulot12** [comment]
Bom dia!


Conforme exemplo da versão 2.5



[cid:46679db1-1f7b-4e0a-8f21-30e43ea21c96]

Matéria anexada com nome do autor e já a disponibilização do arquivo

[cid:6b51daac-36d6-44cb-a62b-f137f2e5524b]

________________________________
De: Talitha Pumar <notifications@github.com>
Enviado: segunda-feira, 22 de outubro de 2018 10:35
Para: interlegis/sapl
Cc: paulot12; Mention
Assunto: Re: [interlegis/sapl] Anexada (#2321)


Bom dia, @paulot12<https://github.com/paulot12>.
Pode dar mais detalhes? Quando anexar a matéria onde? Em proposição?

**Comment by paulot12** [comment]
No envio da proposição eu informo a matéria a ser anexada.


________________________________
De: Talitha Pumar <notifications@github.com>
Enviado: segunda-feira, 22 de outubro de 2018 11:55
Para: interlegis/sapl
Cc: paulot12; Mention
Assunto: Re: [interlegis/sapl] Anexada (#2321)


Bom dia @paulot12<https://github.com/paulot12>,
Pode dar mais detalhes? Onde você anexando a matéria? Em proposição?

**Comment by edwardoliveira** [comment]
As duas imagens que vc postou são do mesmo tipo de tela? A imagem que vc mostra do 2.5 é do detalhe da matéria enquanto a imagem que vc mostra do 3.1 é do resultado da pesquisa.

**Comment by edwardoliveira** [comment]
@tapumar O que ele estava tentando dizer é que na listagem resultante da pesquisa de matéria deveria aparecer um link para o texto original, como na versão 2.5 (vide figura abaixo):

![image](https://user-images.githubusercontent.com/9326037/47357970-bedafe80-d69e-11e8-8796-0719360598ae.png)

**Comment by paulot12** [comment]
A minha solicitação é que inclua nos detalhes das matérias, no SAPL 3.1, às matérias anexadas com autor e o arquivo para a visualização

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by paulot12** [comment]
Isso mesmo, @tapumar

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
