### ISSUE TITLE
Matéria legislativa: referir a audiência pública em que foi tratada

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2327]
## Comportamento Esperado
A Matéria legislativa deve informar a audiência pública em que foi tratada, se for o caso.

## Comportamento Atual
A matéria legislativa não mostra se foi tratada em audiência pública.

## Contexto
Ao pesquisar uma matéria legislativa, não há como saber se ela foi tratada em audiência pública.

## Seu Ambiente
* Versão usada (_Release_): 3.1.127
* Nome e versão do navegador: Chromium Versão 69.0.3497.81 (Versão oficial)
* Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
Vc diz na lista resultante da pesquisa?

**Comment by andreagudo** [comment]
Pode ser.

**Comment by edwardoliveira** [comment]
Eu perguntei porque cada nova informação de novas tabelas ocorre em mais lentidão na recuperação dos registros. Mas dá pra fazer, a princípio. Essa informação entraria no detalhe da matéria legislativa?

**Comment by andreagudo** [comment]
Desculpe pela demora. Essa implementação é importante especialmente porquê há matérias, como as orçamentárias, que exigem realização de audiência pública. Seria uma forma mais eficaz de controlar sua realização. Naturalmente, a conveniência de implementação, do ponto de vista da programação, cabe aos desenvolvedores.
