### ISSUE TITLE
Adicionar tabela e logo em Extrato de Sessão Plenária

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#2331]
@DtiLegBG O pessoal da Câmara Municipal de Guadalupe (PI) pediu umas alterações na tela que vc fez. O que vc acha? Teria condições de fazer e submeter um PR pra gente?

_"Parabenizo a equipe de desenvolvimento do Interlegis por acrescentar o Extrato Eletrônico no Resumo de Sessão.
Estamos com a intenção de usar esse Extrato Eletrônico como ata da sessão.
Para tanto gostaria de solicitar duas alterações nesse Extrato.
1º. - Ao imprimir o Extrato Eletrônico gostaria que colocado o Logotipo da Câmara no cabeçalho.
2º - No final onde fica a parte da assinatura dos Vereadores Presentes, peço que tenha uma tabela com os nome dos vereadores presentes para os mesmos assinarem em cima, pois fica mais fácil para identificar de quem é a assinatura.

Aguardando retorno."_

## Comportamento Esperado
Adicionar brasão e tabela para assinatura de presentes na tela de "Extrato" de Sessão Plenária.

## Comportamento Atual
Tela não dispõe da tabela e logo citado.

## Possível Solução
Adicionar a tabela e o logo;

## Imagens do Ocorrido
![image](https://user-images.githubusercontent.com/9326037/47497041-17d99c80-d82f-11e8-9f25-b42e8e333827.png)

**Comment by DtiLegBG** [comment]
Olá @edwardoliveira , claro que sim, durante a semana faço isso sim.

**Comment by DtiLegBG** [comment]
A questão do brasão o @LeandroRoberto já resolveu

**Comment by edwardoliveira** [comment]
Certo. Além disso, ele pediu também uma tabela com os nomes dos vereadores e espaço para assinatura. Podemos fazer assim?

**Comment by LeandroRoberto** [comment]
Por aqui adoraram a ideia da ata mas disseram que em nosso caso só a mesa assina a ata e não todos os presentes... Sugiro um choice em configurações da aplicação ou alguma outra estratégia para atender diferentes regras... No mínimo três... Assinam a ata:
Mesa do dia
Presidente do dia
Todos os presentes

**Comment by edwardoliveira** [comment]
@cesaraugc Veja acima que vamos precisar de uma lógica mais flexível para quem vai assinar essa "ata". Se tiver alguma dúvida fala comigo ou com o @VictorFabreF

**Comment by DtiLegBG** [comment]
Titulo das Assinatura do Extrato da Sessão
![image](https://user-images.githubusercontent.com/13314947/48018343-bf03e100-e117-11e8-8571-4bcde32ba2c0.png)

Seria interessante o título ser conforme a escolha ao invés de "Assinatura Parlamentares Presentes"
    ('M', _('Mesa do dia')),
    ('P', _('Apenas o presidente do dia')),
    ('T', _('Todos os presentes')),

Então:

"Assinatura da Mesa Diretora da Sessão"
"Assinatura do Presidente da Sessão"
"Assinatura de Todos os Parlamentares Presentes na Sessão"
