### ISSUE TITLE
Dúvidas gerais + instalação em ambiente de produção

### ISSUE THREAD

**Issue by rkhaotix** [interlegis/sapl#2332]
Bom dia.

Estamos em um movimento aqui na Casa Legislativa onde trabalho para readotar o SAPL. Visto que não usamos o mesmo desde a versão 2.4 percebi que este muito mudou. Estive lendo o README do repositório mas achei um pouco confuso por isso tenho dois questionamentos.

1) O SAPL 3.1 já pode ser usado em ambiente de produção? Se não, o que ainda falta para ele ser considerado estável o suficiente?
2)  Os procedimentos de instalação do ambiente de desenvolvimento são os mesmo para produção?

Desculpe se esse pode ser um ticket duplicado.
Muito obrigado.

**Comment by VictorFabreF** [comment]
Bom dia,
1) O SAPL 3.1 já está sendo usado em produção por diversas casas legislativas e é totalmente estável.
2) Os procedimentos do ambiente de produção são diferentes do ambiente de desenvolvimento. Instruções para deploy podem ser encontradas em https://github.com/interlegis/sapl/blob/master/docs/deploy.rst
