### ISSUE TITLE
Hora do protocolo de documento adiantada

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2334]
## Comportamento Esperado
O protocolo deve sair no horário vigente.

## Comportamento Atual
Está saindo com adiantado em uma hora.

## Contexto
Ocorre ao protocolar um documento.

## Passos para Reproduzir (para bugs)
Ocorreu com os seguintes protocolos somente, a partir do final da manhã de hoje.
https://sapl.agudo.rs.leg.br/protocoloadm/1297/protocolo-mostrar
https://sapl.agudo.rs.leg.br/protocoloadm/1296/protocolo-mostrar

## Seu Ambiente
* Versão usada (_Release_): 3.1.130
* Nome e versão do navegador: Firefox Versão 62.0.3
* Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 32 bits

**Comment by LeandroRoberto** [comment]
@edwardoliveira servidores com locale "pt_BR.UTF-8" estão com horário de verão.

**Comment by edwardoliveira** [comment]
Sim, estamos tentando uma forma de resetar isso aqui nos containeres, mas até agora não encontrei uma forma de fazer.

**Comment by edwardoliveira** [comment]
Resolvemos essa issue atualizando os pacotes do Linux. Estará disponível a partir da versão 3.1.130, a ser implantada hoje.
