### ISSUE TITLE
Campos data e hora marcados para remoção em Protocolo

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#2337]
Os campos data e hora em Protocolo estão marcados para remoção. No entanto, tenho interesse nesses campos. Minha sugestão é que adicione um campo user_data_hora_manual FK para auth.User.
Então, no formulário um botão "informar data e hora manualmente" e, feito isso, o sistema registre automaticamente o timestamp mas registre tb o que o usuário quis informar além de registrar que usuário fez isso.
![image](https://user-images.githubusercontent.com/9630623/47583213-20180180-d92d-11e8-8e43-6043c932d550.png)

**Comment by edwardoliveira** [comment]
> Os campos data e hora em Protocolo estão marcados para remoção. No entanto, tenho interesse nesses campos.

Fique a vontade para usá-los! :smile: :tophat: 

> Então, no formulário um botão "informar data e hora manualmente"
Eu concordo com a ideia de registrar que usuário protocolou o documento. Mas a ideia do timestamp é justamente não deixar o usuário informar manualmente. E permitir a ordenação por esse campo. Quais seriam as vantagens de colocar esse campo como manual?

**Comment by LeandroRoberto** [comment]
Em minha casa (quiçá em outras) existe horário limite para protocolar proposições e documentos administrativos (por exemplo licitações com horário limite de 14hs), no entanto, estava ocorrendo que muitos documentos chegavam nos últimos instantes. Com o acúmulo de digitalizações, o protocolo  não conseguia registrar tudo para sair na etiqueta antes dos horários limites referentes de cada documento...  Ainda bem que corrigi a tempo aqui em não tivemos problemas com empresas no que se refere a licitações... mas tivemos problemas com vereadores dizendo que entregou sua proposição no protocolo antes do horário limite mas a etiqueta do protocolo estava posterior ao horário limite...

**Comment by LeandroRoberto** [comment]
reitero que o campo timestamp juntamente com o reversion é necessário para auditar a informação e comprovar casos de má fé... mas o caso é real e corriqueiro e acho que a lógica deveria em todas as situações deveria levar em consideração timestamp e/ou data e hora quando diferentes de None

**Comment by edwardoliveira** [comment]
Entendi. Poderia submeter um PR pra adicionar isso? :sweat_smile:

**Comment by LeandroRoberto** [comment]
blz... em breve... deixa a issue aqui em espera atribuída a mim!
