### ISSUE TITLE
Edição de sessão legislativa

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2338]
## Comportamento Esperado
Deve ser possível editar as datas de início e fim da sessão legislativa.

## Comportamento Atual
Ao editar uma sessão legislativa, o sistema está tentando criar uma nova.

## Passos para Reproduzir
https://sapl.agudo.rs.leg.br/sistema/mesa-diretora/sessao-legislativa/54/edit

## Contexto
Edição de datas de início e fim de sessão legislativa.

## Imagens do Ocorrido
![captura de tela de 2018-10-29 10-33-14](https://user-images.githubusercontent.com/19169882/47653348-17127480-db67-11e8-9cd5-f8ab728d06fb.png)

## Seu Ambiente
Versão usada (Release): 3.1.130
Nome e versão do navegador: Versão 70.0.3538.67 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
O SAPL não está deixando porque o final da Sessão 2 faz interseção com o início da Sessão 3, conforme figura abaixo:

![image](https://user-images.githubusercontent.com/9326037/47658473-d409ce80-db71-11e8-8fb8-9134af222b2c.png)

**Comment by andreagudo** [comment]
Ok. Editei as datas a partir da última sessão legislativa, deu certo.
