### ISSUE TITLE
Sugestão: Não permitir da edição de tramitações de documentos administrativos

### ISSUE THREAD

**Issue by rkhaotix** [interlegis/sapl#2340]
Bom dia, pessoal!

Posso estar enganado quanto a seção de documentos administrativos do SAPL mas imagino que seja uma espécie de sistema de protocolo, correto? Se for o caso, penso que tramitações não deveriam ser editáveis pelos operadores mas por apenas alguns poucos usuários privilegiados. Digo isso dada a importância de tramitações de documentos no sentido de refletir a real situação dos mesmos no órgão.

Além disso, permitir a edição das tramitações pode levar a fraudes o que pode gerar uma série de problemas de ordem administrativa. Por fim, como últimas sugestões, as datas de tramitação e encaminhamento poderiam ser de preenchimento automático pois irão refletir a real data em que o usuário tomou alguma ação. Fora isso, os operadores do sistema poderiam ter um campo de unidade administrativa (setor de lotação) e o módulo e tramitação de documentos usasse esse campo para permitir que operadores tramitassem somente processo que foram enviados para suas respectivas unidades administrativas.

Acredito que com modificações simples esse seria uma solução muito completa para órgãos do Legislativo que buscam um sistema de tramitação de matérias legislativas e processos internos.

**Comment by edwardoliveira** [comment]
Obrigado pelas sugestões, muito pertinentes. 

> Posso estar enganado quanto a seção de documentos administrativos do SAPL mas imagino que seja uma espécie de sistema de protocolo, correto?

Sim, é um sistema **_rudimentar_** de protocolo, uma herança da versão anterior do SAPL que 

>  Se for o caso, penso que tramitações não deveriam ser editáveis pelos operadores mas por apenas alguns poucos usuários privilegiados.

No SAPL atual isso é possível através da criação de perfil customizado com permissão de edição para este perfil e atribuição a usuários selecionados.

> como últimas sugestões, as datas de tramitação e encaminhamento poderiam ser de preenchimento automático pois irão refletir a real data em que o usuário tomou alguma ação. 

Temos um campo (interno) que registra data e hora real que o documento foi efetivamente tramitado. Esses campos citados não são de preenchimento automático porque em alguns dos munícipios existiu essa necessidade de não serem de preenchimento automático (existe todo o tipo de situação "irreal" nas mais de 700 casas que usam o SAPL.

> Fora isso, os operadores do sistema poderiam ter um campo de unidade administrativa (setor de lotação) e o módulo e tramitação de documentos usasse esse campo para permitir que operadores tramitassem somente processo que foram enviados para suas respectivas unidades administrativas.

Essa sugestão já nos foi passada outras issues (#2262, #2273, #2304)

Entendemos sua importância, mas conforme discussão interna não iremos executar isso no SAPL. **_A decisão até o momento é criar um outro sistema menor de protocolo e tramitação de documentos integrável ao SAPL_** para suprir exatamente tudo o que vc sugere nesse ticket, e mais outras requisições (#969, #2274, #2263, #1506, #2267, #1503).

> Acredito que com modificações simples (...)

_**Dada a situação atual do código e grande quantidade de usuários antigos do sistema, estas alterações sugeridas não são simples**_. Precisamos compatibilizar várias necessidades atuais e futuras, incluindo as expressas nesse ticket. Portanto, isso ficará para um futuro a médio prazo, preferencialmente em um **outro** sistema que possa ser integrado ao SAPL.

**Comment by rkhaotix** [comment]
Obrigado pelos esclarecimentos @edwardoliveira .

Vou ver a viabilidade de fazer uma customização junto à minha equipe de desenvolvimento de software. Não temos experiência em Python/Django mas nada que uma boa estudada não resolva. :)

**Comment by eribeiro** [comment]
As contribuições de código são sempre bem vindas, se assim desejar.
