### ISSUE TITLE
Dúvida: Como desabilitar o uso de servidor de email?

### ISSUE THREAD

**Issue by rkhaotix** [interlegis/sapl#2342]
Estou fazendo a alimentação inicial do SAPL antes de colocá-lo em produção. Estou na etapa de associar parlamentares à usuários para permitir a autoria de matérias. Porém, tenho enfrentado alguns problemas, pois o sistema está tentando enviar um email para confirmação do cadastro do usuário ao parlamentar mas nosso serviço de email aqui não permite message relay.

## Comportamento Esperado
Gostaria de poder associar parlamentares à conta de usuários para redação de matérias sem a necessidade de envio de email.

## Comportamento Atual
O sistema gera um erro dizendo que falhou ao enviar email.

Variable | Value
```-- | --
assunto | 'SAPL - Confirmação de Conta'
destinatario | ['']
full_url | 'http://********/sistema/autor/create'
kwargs | {'token': '50w-ba596ccbe5170a328a73', 'uidb64': b'MTE'}
mensagem | ('Este e-mail foi utilizado para fazer cadastro no SAPL com o perfil de Autor. '  'Agora você pode criar/editar/enviar Proposições.\n'  'Seu nome de usuário é: *******\n'  'Caso você não tenha feito este cadastro, por favor ignore esta mensagem. '  'Caso tenha, clique no link abaixo\n'  'http://***********/email/validate/MTE/50w-ba596ccbe5170a328a73')
pk_autor | 8
remetente | ['']
self | <sapl.crud.base.Crud.get_urls.<locals>._add_base.<locals>.CrudViewWithBase object at 0x7f346a2bb390>
url_base | 'http://10.98.250.100'
url_reverse | '/sistema/autor/8'
user | <User: dep.*********>
```
## Possível Solução
Deixar opcional o uso de um servidor de email para entrega de mensagens de confirmação de cadastro de usuário.

## Passos para Reproduzir (para bugs)
1. Deixe os parâmetros de email no arquivo `.env` vazios.
2. Cadastre um parlamentar
3. Associe um parlamentar a uma conta de usuário no cadastro de Autores

## Imagens do Ocorrido
![sapl_eror](https://user-images.githubusercontent.com/2205476/47788588-e9593700-dcf0-11e8-90eb-a9ed3e39ce42.png)

## Seu Ambiente
* Versão usada (_Release_): 3.1.130
* Nome e versão do navegador: Chrome 69.0.3497.92 64 bits
* Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu Linux 16.04 LTS 
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
@LeandroRoberto Oi, quando vc tiver tempo poderia dar uma olhada nisso? :grimacing:

**Comment by LeandroRoberto** [comment]
https://github.com/interlegis/sapl/pull/2354
