### ISSUE TITLE
Impressos - Capa de Processo para Documentos Administrativos

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#2344]
A função imprime o resumo "Despacho" apenas para Matérias Legislativas. A AL Alagoas nos solicitou implementar também para Documentos Administrativos.

Adicionar  tipos dos documentos administrativos, pois existe a função. Coloca-se um título de identificação: matérias legislativas e documentos administrativos. Isso implica buscar os dados administrativos em outro local. 
Caso a opção seja duplicar a função, sugiro criar uma nova linha no menu de opções: Impressos - matérias administrativas, Impressos - Documentos Administrativos.

**Comment by edwardoliveira** [comment]
>  A AL Alagoas nos solicitou 

@morale Nos solicitou como? Não vi nenhum ticket aberto no OSTicket e vc que está abrindo aqui no github.

**Comment by VictorFabreF** [comment]
![image](https://user-images.githubusercontent.com/19825887/47854109-a023e880-ddbf-11e8-9811-213914039faa.png)
Seria essa tela para Documento Administrativo?

**Comment by morale** [comment]
Acrescida do número e ano do protocolo e sem essa parte inferior sobre norma jurídica.

**Comment by morale** [comment]
O Despacho Processo - quando a ementa da matéria é mais extensa, ela fica sobrepondo o texto "Despacho Inicial:" que suponho estar em posição fixa quando, nesse caso, deveria ser impressa mais abaixo.

**Comment by morale** [comment]
Outra questão é a impossibilidade de seleção de mais de uma matéria para impressão dessa etiqueta sem que seja necessária nova pesquisa.

**Comment by tapumar** [comment]
Fechada por descrição inválida

**Comment by edwardoliveira** [comment]
@morale Quando se abre uma issue não é pra apagar todo aquele texto e digitar um simples parágrafo. Siga o formulário e preencha os campos que achar necessário.
