### ISSUE TITLE
Ordem do dia

### ISSUE THREAD

**Issue by ivanlucio10** [interlegis/sapl#2346]
## Possível Solução
Seria possível deixar a ordem do dia pronta porem que ela fosse publicada automaticamente na data e horário estipulado. (Ex: fiz a ordem do dia na sexta-feira e a sessão ocorrerá na segunda-feira, porem quero que ela esteja no ar somente 24h antes da sessão)

**Comment by edwardoliveira** [comment]
Iremos analisar para uma versão futura do SAPL (sem previsão, entretanto).

**Comment by tapumar** [comment]
Fechada por descrição inválida
