### ISSUE TITLE
Usar URLField e EmailField onde possível

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#235]
Usar URLField e EmailField para todos os campos de Url e email.

Telas como Oradores Expediente e Explicações Pessoais possuem um campo de URL do discurso.
Identificar esse e outros campos de url e todos os campos de email e usar os campos específicos do django para isso.

https://docs.djangoproject.com/es/1.9/ref/forms/fields/#urlfield
https://docs.djangoproject.com/es/1.9/ref/forms/fields/#emailfield

**Comment by edwardoliveira** [comment]
@marciomazza e @LeandroRoberto, teria como revisar isso aqui rápido? Leandro, eu modifiquei o model de compilação, mas ele não deve causar maiores problemas :pray: porque o EmailField e URLField são CharField com validadores (d'uh!). Mas se preferir podemos voltar ao CharField/TextField.

**Comment by edwardoliveira** [comment]
Opa, esqueci de colocar o link do branch: https://github.com/interlegis/sapl/commits/235-usar-emailfield-urlfield

**Comment by LeandroRoberto** [comment]
na app compilação está ok!

**Comment by edwardoliveira** [comment]
Ok, eu testei nas outras telas e ficou bacana. Ele mostra um validador (JS?) pra URL e email. :+1:
