### ISSUE TITLE
Combo box para definir o ano em documentos? 

### ISSUE THREAD

**Issue by rkhaotix** [interlegis/sapl#2353]
Bom dia!

Gostaria de saber qual é o objetivo de se ter um combo box para definir o ano em documentos? Vi essa abordagem em vários formulários do sistema e achei um pouco estranho. Por ser um campo numérico de poucos dígitos não seria mais fácil/intuitivo se ter um campo de texto simples (com ou sem máscara porém validado) para que o usuário forneça o ano desejado? Se possível, o ano atual já viria preenchido. Digo isso pois vários usuários estão mais acostumados a preencher um campo para ano do que selecionar em um combo e, dependendo do volume de trabalho, fica mais difícil ter que ficar manuseando tal controle.

Obrigado

**Comment by edwardoliveira** [comment]
> não seria mais fácil/intuitivo se ter um campo de texto simples

Concordo com a tua colocação, mas não necessariamente seria desejável ter esse campo de livre prenchimento. Os usuários (e são muitos) por vezes digitam valores inválidos em campos de texto livre, o que causa toda sorte de problema de consistência. Abrir este campo para digitação geraria casos de campos com anos inválidos (2007 ao invés de 2017, 1908, etc). Já tivemos **vários** casos assim no preenchimeno de datas, por exemplo. 

> Se possível, o ano atual já viria preenchido


Concordo de novo. Mas optamos por deixar o usuário preencher esse campo porque, de novo, vários usuários reclamaram que desejavam incluir documentos com anos anteriores e daí o sistem preenchia automaticamente com o ano corrente e a pessoa salvava com o ano corrente.

A decisão de usar um campo de ano foi justamente pela quantidade de erros. Quanto mais limitarmos a quantidade de texto livre, melhor.
