### ISSUE TITLE
Observações da Matéria não aparecem na aba Resumo e no PDF na Ordem do Dia

### ISSUE THREAD

**Issue by cesaraugc** [interlegis/sapl#2355]
## Comportamento Esperado

A observação deveria aparecer na Ementa do Resumo e do PDF Gerado.

## Comportamento Atual

Apenas a observação do resultado da votação está aparecendo.

## Imagens do Ocorrido

![6a6062ba-df5a-4e26-9e90-9e68d5f5953f](https://user-images.githubusercontent.com/20192488/48022142-87019b80-e121-11e8-8a23-1a24fd4122dd.jpeg)
![e0fb2317-6ae0-44c2-be7f-40e2ac1c3424](https://user-images.githubusercontent.com/20192488/48022156-91239a00-e121-11e8-9db2-656d4f0e5313.jpeg)
![45dac3a4-04ef-46e1-bb58-fa368a4294fd](https://user-images.githubusercontent.com/20192488/48022183-9f71b600-e121-11e8-9a06-474e449f15fe.jpeg)

## Seu Ambiente

* Versão usada (_Release_): 3.1.131

**Comment by VictorFabreF** [comment]
Essa issue foi tirada de https://suporte.interlegis.leg.br/scp/tickets.php?id=26216, correto?

**Comment by cesaraugc** [comment]
Correto.

> Essa issue foi tirada de https://suporte.interlegis.leg.br/scp/tickets.php?id=26216, correto?

Correto.
