### ISSUE TITLE
Parlamentar não listado na combo Autor

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2358]
## Comportamento Esperado
Parlamentar cadastrado como autor deve aparecer na combo Autor.

## Comportamento Atual
Pedrinho Müller não aparece na combo Autor.

## Possível Solução
Se trata de um autor sem usuário de acesso ao SAPL. Aparentemente, isso evita que apareça entre os autores, indevidamente. 

## Passos para Reproduzir
https://sapl.agudo.rs.leg.br/materia/10658/autoria/create
https://sapl.agudo.rs.leg.br/sistema/autor/107/edit

## Contexto
Registro de autor de matéria legislativa.

## Imagens do Ocorrido
![captura de tela de 2018-11-06 08-14-10](https://user-images.githubusercontent.com/19169882/48058332-4a738580-e19d-11e8-86cd-cb50741b45c8.png)

## Seu Ambiente
Versão usada (Release): 3.1.130
Nome e versão do navegador: Versão 70.0.3538.67 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by VictorFabreF** [comment]
Bom dia, @andreagudo 
O parlamentar não está aparecendo no combo pois ele não tem mandato na data de apresentação dessa matéria. Como pode ser visto nas imagens abaixo.

![image](https://user-images.githubusercontent.com/19825887/48066882-ead5a400-e1b5-11e8-89dd-bfaa84178cb9.png)

![image](https://user-images.githubusercontent.com/19825887/48066889-f32ddf00-e1b5-11e8-95ce-eac18f17ec2e.png)

Att,
Victor Fabre
