### ISSUE TITLE
Rever lorem ipsum no rodapé

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#236]
Atualmente, antes da casa preencher seus dados aparecem dados stub *lorum ipsum...* no lugar deles no rodapé das páginas.

Rever se esse é o melhor comportamento.
Talvez seja o caso deixar simplesmente vazio. Nesse caso podemos colocar uma mensagem pedindo para preencher os dados, que só desaparece após estarem preenchidos.

**Comment by marciomazza** [comment]
@eduardoedson Dá uma olhadinha melhor na descrição da issue. A ideia era 1o pensar em qual seria o melhor comportamento, discutindo aqui nos comentários.

Mas vamos fazer assim:

O comportamento deve ser:

* se a casa não tiver seus dados cadastrados: 
  - não exibir o trecho dos dados da casa no rodapé (deixar só interlegis e licença no ropadé)
  - mostrar uma mensagem constante no site dizendo para preencher os dados, com um link para o ponto no sistema onde isso é feito
* se a casa tiver seus dados cadastrados:
  - exibi-los no rodapé

**Comment by eduardoedson** [comment]
@marciomazza https://github.com/interlegis/sapl/commit/f9b82cb496a6498f7fdcaab77eb3f181205c70e6

**Comment by edwardoliveira** [comment]
+1. Faltou a mensagem estática e link que o Mazza citou, mas adicionei uma provisória até termos uma redação melhor. Fechando essa issue pq já foi feito merge para o master.
