### ISSUE TITLE
Campo "Ementa" estoura a capa do processo.

### ISSUE THREAD

**Issue by VictorFabreF** [interlegis/sapl#2360]
Issue reportada pelo @morale em comentário na issue #2344 
## Comportamento Esperado

É esperado que a na capa do processo todos os campos possam ser visualizados.
## Comportamento Atual

Caso a ementa da matéria seja muito grande, ela fica por cima dos campos que vem abaixo.
## Possível Solução

Limitar a quantidade de caracteres da ementa que são mostrados na capa do processo e ao atingir esse limite não mostrar e acrescentar "..." ao final.
## Passos para Reproduzir (para bugs)

1. Criar uma matéria com uma ementa grande (mais de 20 linhas de texto)
2. Ir em impresso -> capa de processo
3. Ver que o campo sobrescreveu o local de assinatura e o despacho inicial
4.

## Imagens do Ocorrido

* Versão usada (_Release_):Versão 3.1.131

**Comment by VictorFabreF** [comment]
https://user-images.githubusercontent.com/19825887/48201791-56e91100-e34a-11e8-8c40-fb948fe55aa4.png

**Comment by VictorFabreF** [comment]
![image](https://user-images.githubusercontent.com/19825887/48201791-56e91100-e34a-11e8-8c40-fb948fe55aa4.png)

**Comment by edwardoliveira** [comment]
Minha sugestão é limitar esse campo a uma quantidade "X" de caracteres. Se esta página vai ser impressa numa etiqueta ou algo assim, não faz sentido colocar uma ementa gigantesca, melhor estipular um tamanho máximo e colocar três pontos para indicar que o texto continua, caso necessário.
