### ISSUE TITLE
Tecla V - Votação

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#2366]
## Comportamento Esperado

É necessário ao abrir a página de votação com a letra V, em qualquer página do SAPL

## Comportamento Atual

Atualmente só funciona o comando da tecla V na página de início do SAPL

**Comment by tapumar** [comment]
Bom dia @paulot12, não é possível colocar esta funcionalidade em todas as páginas do SAPL. 
Mas devido a necessidade, colocarei também nas páginas de matérias da Ordem do Dia e do Expediente.

**Comment by paulot12** [comment]
É necessário colocar no resumo da Sessão

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
