### ISSUE TITLE
Incluir Justificativa de ausências no extrato da sessão

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#2371]
No Extrato da Sessão seria interessante incluir as ausências cadastradas em Sessão/Abertura/Ausência:
http://sapl.camarabento.rs.gov.br/sessao/441/justificativaausencia

## Comportamento Esperado
O objetivo do extrato da sessão é funcionar como uma ata, ou mesmo se tornar a ata e para tanto as justificativas de ausências cadastradas são fundamentais que constem no extrato

![image](https://user-images.githubusercontent.com/13314947/48367188-11547d00-e697-11e8-864c-1f4b22789a80.png)

Poderia ser logo abaixo da lista de presença na sessão
Ausências Justificadas: Vereador..., ausente em ....., tipo de justificativa......, data....

![image](https://user-images.githubusercontent.com/13314947/48367226-2f21e200-e697-11e8-9e24-472b81c835d1.png)

**Comment by edwardoliveira** [comment]
@tapumar Por que abriu de novo essa issue? :) É isso mesmo?

**Comment by DtiLegBG** [comment]
para mim ainda não está disponível
http://sapl.camarabento.rs.gov.br/sessao/441/justificativaausencia

http://sapl.camarabento.rs.gov.br/sessao/441/resumo_ata

**Comment by DtiLegBG** [comment]
O Extrato resolveu parte dessa issue
https://github.com/interlegis/sapl/issues/1733
