### ISSUE TITLE
Sugestão de busca Normas Legislativa

### ISSUE THREAD

**Issue by rosenocmcc** [interlegis/sapl#2374]
Estamos cadastrando as normas juridicas com os texto articulado. Estamos recebendo algumas criticas pelos usuário por não possuirmos uma busca por palavra ou frase dentro do setor de texto. 
![github](https://user-images.githubusercontent.com/36698231/48384079-da4e8d80-e6cf-11e8-94ca-d46d13a200bb.JPG)
Esse é um exemplo de uma empresa terceirizada que faz a nossa divulgação das normas juridicas. Estamos trabalhando para passar todas para o Sapl,
http://www.cmcc.cespro.com.br/visualizarDiploma.php?cdMunicipio=7345&cdDiploma=20183337&NroLei=3.337&Word=&Word2=

**Comment by lizianem** [comment]
Bom dia. 
Vi no SAPL da Câmara de Capão da Canoa que está habilitado apenas a pesquisa pela ementa ou pela indexação. Vocês precisam habilitar a PESQUISA TEXTUAL, que fará uma varredura no texto:

![image](https://user-images.githubusercontent.com/39954049/48409787-f67c1a00-e723-11e8-9d81-a8390f656588.png)

**Comment by lizianem** [comment]
![image](https://user-images.githubusercontent.com/39954049/48409828-0dbb0780-e724-11e8-81d3-8af42135e7b4.png)

**Comment by lizianem** [comment]
Veja exemplo de Porto Alegre. Estamos iniciando o cadastro, porém sem compilação, apenas o texto original.
https://legislacaosirel.portoalegre.rs.gov.br/sistema/search/

**Comment by tapumar** [comment]
De acordo com as novas diretrizes adotadas no repositório do SAPL, as novas issues abertas para correções de erros (bugs)e solicitações de novas funcionalidades (features) devem ser abertas seguindo o mais novo template. Segue imagem de exemplo:

image

Como o GitHub suporta estilização via MarkDown os textos que estão entre  são tidos como comentários e podem ser apagados, os textos ali
são apenas para auxiliar novos usuários a se orientarem na abertura. Nem todas as seções precisam ser preenchidas mas espera que ao menos essas contenham dados:

Para bugs:

Comportamento Atual
Comportamento Esperado
Passos para reproduzir
Imagens
Para features:

Comportamento Esperado
Possível solução
Contexto
Imagens (se possível e aplicável)
Mas LEMBREM-SE quanto mais informações e tópicos preenchidos, melhor fica a sua issue e aumenta a chance de ser solucionada rapidamente e efetivamente.

Para saber mais sobre MarkDown acesse o link: https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf

Favor reabrir a issue mantendo o padrão solicitado!
