### ISSUE TITLE
Erro 500 ao salvar Ordenação do Resumo

### ISSUE THREAD

**Issue by VictorFabreF** [interlegis/sapl#2377]
## Comportamento Esperado

Ser possível salvar o formulário de Ordenação do Resumo.
## Comportamento Atual

Ao tentar salvar, o sistema retorna um erro 500 por estar faltando um campo no formulário e que ele tenta usar na view.
## Possível Solução

Acrescentar o campo necessário no formulário.
## Passos para Reproduzir (para bugs)

1. Entrar em ordenação de resumo
2. Salvar o formulário

## Seu Ambiente

* Versão usada (_Release_): 3.1.133

**Comment by marimendes** [comment]
Será resolvido no pr #2375
