### ISSUE TITLE
Pauta da Sessão 3.1

### ISSUE THREAD

**Issue by ivanlucio10** [interlegis/sapl#2379]
Voltando a Pauta da Sessão. Quando clica em pauta da sessão, esta abrindo direto a pauta (ERRADO), pois se tiver 2 sessões no mesmo dia, vai abri uma e a outra somente fazendo uma busca. O CERTO e abrir os link para as sessões, igual acontece na versão 2.5

**Comment by VictorFabreF** [comment]
Por favor, preencha todos os campos indicados na abertura da issue.
"Comportamento Esperado
Comportamento Atual
Possível Solução
Passos para Reproduzir (para bugs)
Contexto
Imagens do Ocorrido"
Isso é importante para que possamos identificar melhor a requisição ou o bug, de forma que facilita a implementação da solicitação ou a correção do bug.

**Comment by marimendes** [comment]
De acordo com as novas diretrizes adotadas no repositório do SAPL, as novas issues abertas para correções de erros (bugs)e solicitações de novas funcionalidades (features) devem ser abertas seguindo o mais novo template. Segue imagem de exemplo:

image

Como o GitHub suporta estilização via MarkDown os textos que estão entre são tidos como comentários e podem ser apagados, os textos ali
são apenas para auxiliar novos usuários a se orientarem na abertura. Nem todas as seções precisam ser preenchidas mas espera que ao menos essas contenham dados:

Para bugs:

Comportamento Atual
Comportamento Esperado
Passos para reproduzir
Imagens
Para features:

Comportamento Esperado
Possível solução
Contexto
Imagens (se possível e aplicável)
Mas LEMBREM-SE quanto mais informações e tópicos preenchidos, melhor fica a sua issue e aumenta a chance de ser solucionada rapidamente e efetivamente.

Para saber mais sobre MarkDown acesse o link: https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf

Favor reabrir a issue mantendo o padrão solicitado!
