### ISSUE TITLE
Campos de pesquisa de matéria legislativa

### ISSUE THREAD

**Issue by eduardoedson** [interlegis/sapl#238]
Os campos autor, localização atual e situação de matéria legislativa não estão sendo usados para filtrar.

**Comment by marciomazza** [comment]
Essa melhoria depende de #217.

**Comment by eduardocalil** [comment]
@eduardoedson Qual problema que está tendo? Testei aqui e está funcionando

**Comment by eduardoedson** [comment]
Os campos citados não foram implementados, só estão sendo mostrados mas não possuem utilidade

**Comment by marciomazza** [comment]
Será resolvido por #217.
