### ISSUE TITLE
Cronômetro de Discurso não aceita tempo maior que 23:59

### ISSUE THREAD

**Issue by marcoscamargo** [interlegis/sapl#2380]
## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Imagens do Ocorrido

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by marcoscamargo** [comment]
Verificando o Cronômetro referente a Discurso do Painel Eletrônico do SAPL, notei que ele não está aceitando tempo maior que 23:59 (como se fosse 24h o limite - mesmo o tempo sendo em minutos).

Notei esse problema pois no Município de Ibiúna o tempo para discurso é de 30 minutos.

Desde já agradeço a atenção.
![cronometro sapl](https://user-images.githubusercontent.com/43411281/48493590-3e2d9f00-e813-11e8-9821-272f9a94d0fb.png)
![cronometro 2359](https://user-images.githubusercontent.com/43411281/48493641-5b626d80-e813-11e8-9524-890c679ea94d.png)

**Comment by edwardoliveira** [comment]
Favor preencher os campos abaixo.
Comportamento Esperado
Comportamento Atual
Possível Solução
Passos para Reproduzir (para bugs)
Contexto
Imagens do Ocorrido

**Comment by edwardoliveira** [comment]
Os campos de cronômetro marcam hora:minuto. Então, pelas imagens acima vc está tentando marcar um discurso com 30 **horas** de duração. Se o tempo é 30 **minutos** vc deve preencher: *_00:30_* (vamos deixar isso mais explicito nessa tela de configuração).
