### ISSUE TITLE
Listas de presenças da sessão: partidos dos parlamentares

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2381]
## Comportamento Esperado
Nas listas de presenças à sessão e à Ordem do Dia devem aparecer os partidos dos parlamentares.

## Comportamento Atual
Estão aparecendo nomes de campos do banco de dados.

## Passos para Reproduzir
https://sapl.agudo.rs.leg.br/sessao/1486/presenca
https://sapl.agudo.rs.leg.br/sessao/1486/presencaordemdia

## Contexto
Consulta às listas de presença.

## Imagens do Ocorrido
![captura de tela de 2018-11-14 15-44-46](https://user-images.githubusercontent.com/19169882/48501835-4f7fa700-e825-11e8-90b2-34350bd714de.png)
![captura de tela de 2018-11-14 15-45-53](https://user-images.githubusercontent.com/19169882/48501854-5ad2d280-e825-11e8-9245-b3e4377a8ed8.png)

## Seu Ambiente
Versão usada (Release): 3.1.133
Nome e versão do navegador: Versão 70.0.3538.77 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
@LeandroRoberto Esse commit `d443a9b3354150a93490d6d1895d11985c187844P` quebrou a listagem de presença com usuário anônimo. Sabe dizer o que pode ter sido????

**Comment by LeandroRoberto** [comment]
@edwardoliveira e @andreagudo... só me resta pedir desculpas... me desculpem... corrigido!
