### ISSUE TITLE
Erro inesperado ao gerar resumo da sessão

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2382]
## Comportamento Esperado
O resumo da sessão deve ser gerado ao clicar em "resumo".

## Comportamento Atual
Está aparacendo a mensagem "Ocorreu um erro inesperado! Erro 500".

## Passos para Reproduzir
https://sapl.agudo.rs.leg.br/sessao/2739/resumo

## Contexto
Consulta ao resumo de uma sessão.

## Imagens do Ocorrido
![captura de tela de 2018-11-19 09-33-50](https://user-images.githubusercontent.com/19169882/48704975-1e192980-ebdf-11e8-8891-2a753c6549f1.png)

## Seu Ambiente
Versão usada (Release): 3.1.134
Nome e versão do navegador: Versão 70.0.3538.77 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by tapumar** [comment]
Bom dia @andreagudo, na ultima release foi adicionado um campo a mais na ordenação do resumo. Peço que reajuste a ordenação em Tabelas Auxiliares -> Ordenação do Resumo e veja se o erro continua ocorrendo

**Comment by andreagudo** [comment]
Funcionou. Obrigado.
