### ISSUE TITLE
PDF da Pauta com erro!

### ISSUE THREAD

**Issue by Neybson** [interlegis/sapl#2389]
A pauta da Sessão gerada em PDF não traz todas as matérias em pauta, ou seja a maioria das matérias que estão no expediente não são consignadas na impressão do PDF.

**Comment by marimendes** [comment]
De acordo com as novas diretrizes adotadas no repositório do SAPL, as novas issues abertas para correções de erros (bugs)e solicitações de novas funcionalidades (features) devem ser abertas seguindo o mais novo template. Segue imagem de exemplo:

image

Como o GitHub suporta estilização via MarkDown os textos que estão entre são tidos como comentários e podem ser apagados, os textos ali
são apenas para auxiliar novos usuários a se orientarem na abertura. Nem todas as seções precisam ser preenchidas mas espera que ao menos essas contenham dados:

Para bugs:

Comportamento Atual
Comportamento Esperado
Passos para reproduzir
Imagens
Para features:

Comportamento Esperado
Possível solução
Contexto
Imagens (se possível e aplicável)
Mas LEMBREM-SE quanto mais informações e tópicos preenchidos, melhor fica a sua issue e aumenta a chance de ser solucionada rapidamente e efetivamente.

Para saber mais sobre MarkDown acesse o link: https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf

Favor reabrir a issue mantendo o padrão solicitado!
