### ISSUE TITLE
Exibir campos HTML em telas do CRUD

### ISSUE THREAD

**Issue by eduardoedson** [interlegis/sapl#239]
Quando utilizados um widget de texto rico (vide imagem) ele salva o campo com códigos HTML.

![captura de tela de 2016-03-07 09-35-45](https://cloud.githubusercontent.com/assets/7716450/13569654/0765cece-e448-11e5-946f-4db28d389b8a.png)

Estes códigos não são renderizados quando a tela de CRUD exibe o texto sem renderizar o código HTML (vide imagem).

![captura de tela de 2016-03-07 09-36-32](https://cloud.githubusercontent.com/assets/7716450/13569670/23fbae1e-e448-11e5-8934-1dc9bd72a458.png)

**Comment by LeandroRoberto** [comment]
use o filter |safe

Em seg, 7 de mar de 2016 às 09:37, Eduardo Edson Batista Cordeiro Alves <
notifications@github.com> escreveu:

> Quando utilizados um widget de texto rico (vide imagem) ele salva o campo
> com códigos HTML.
>
> [image: captura de tela de 2016-03-07 09-35-45]
> <https://cloud.githubusercontent.com/assets/7716450/13569654/0765cece-e448-11e5-946f-4db28d389b8a.png>
>
> Estes códigos não são renderizados quando a tela de CRUD exibe o texto sem
> renderizar o código HTML (vide imagem).
>
> [image: captura de tela de 2016-03-07 09-36-32]
> <https://cloud.githubusercontent.com/assets/7716450/13569670/23fbae1e-e448-11e5-8934-1dc9bd72a458.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/interlegis/sapl/issues/239>.
>
-- 
att.
Leandro Roberto Silva
Câmara Municipal de Jataí

**Comment by edwardoliveira** [comment]
@LeandroRoberto Tem como revisar esta tela. Se estiver OK pra vc basta colocar um +1 ou LGTM. Valeu!

**Comment by LeandroRoberto** [comment]
+1
