### ISSUE TITLE
PDF da Pauta não mostra tudo!

### ISSUE THREAD

**Issue by Neybson** [interlegis/sapl#2390]
<A impressão do PDF da Pauta da Sessão não mostra tudo o que está cadastrado na Sessão Plenária, sobretudo o que está nas Matérias do Expediente>

## Comportamento Esperado
Deveria ser o PDF a íntegra do que tem na Sessão Plenária, ou seja, deveria aparecer em PDF tudo o que aparece no HTML da pauta daquela Sessão, mas quando gera o PDF só aparecem algumas matérias.

## Comportamento Atual
Só aparecem algumas matérias em PDF daquelas que estão cadastradas na Sessão Plenária
## Possível Solução
Corrigir o script para aparecer todas as matérias que tramitam naquela Sessão na geração do PDF.
## Passos para Reproduzir (para bugs)
http://sapl.virtuaserver.com.br/sessao/pauta-sessao/251
http://sapl.virtuaserver.com.br/relatorios/pauta-sessao/251/

1.
2.
3.
4.

## Contexto
Esse problema tem afeta tanto ao Departamento Legislativo, quanto aos assessores dos Vereadores que não conseguem gerar a pauta para enviá-la eletronicamente aos seus parlamentares.Reclamação geral.

## Imagens do Ocorrido

<!--- Se está descrevendo um bug poste imagens ou vídeos na repordução do bug citado, caso se aplique --:

## Seu Ambiente
* Usamos o SAPL 3.1.134
* Nome e versão do navegador: Qualquer Navegador
* Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by marimendes** [comment]
@Neybson Você sabe me disser em qual versão do sapl você está? Esse problema já havia sido resolvido anteriormente.

**Comment by marimendes** [comment]
Já encontrei aqui a versão.

**Comment by edwardoliveira** [comment]
Não consegui reproduzir aqui (em uma base de dados real). Poderia enviar um dump dessa base de dados que vc está usando?

**Comment by Neybson** [comment]
posso sim, envio pra onde?
