### ISSUE TITLE
Parlamentar Suplente, Ausência de Histórico

### ISSUE THREAD

**Issue by Neybson** [interlegis/sapl#2391]
Quando um parlamentar suplente assume ao mandato no lugar de um licenciado, temos como deixar consignado isso nas observações da aba "Mandatos", mas se esse parlamentar assumir por dois períodos distintos o primeiro período consignado será apagado do registro, ficando apenas nas observações. 

## Comportamento Esperado
Deveria ficar um registro de consignações dos períodos que esse parlamentar suplente assume.

## Comportamento Atual
Temos de apagar o registro anterior, quando de um novo período que ele irá assumir, nos campos de início e fim de mandato, ficando consignado apenas nas observações.

## Possível Solução
No Sapl 3.0 temos uma solução bem definida para isso, onde o titular quando se licencia já indica qual suplente assumirá em seu lugar, ficando o registro sequenciado de quantas vezes isso acontece.

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Contexto
A falta desse registro sequencial prejudica a memória da Câmara e também cerceia a informação clara ao cidadão

## Imagens do Ocorrido

* Versão usada (_Release_): 3.1.134
* Nome e versão do navegador: Todos
* Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by VictorFabreF** [comment]
Bom dia,
Será possível criar mais de um mandato apenas para parlamentares suplentes. Essa funcionalidade deve estar disponível já na próxima atualização.
Att,
Victor Fabre
