### ISSUE TITLE
Retirada de Pauta - Extrato da Sessão

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#2398]
É importante que apareça no extrato da sessão a retirada de pauta

## Comportamento Esperado
Penso que as informações de retirada de pauta:

![image](https://user-images.githubusercontent.com/13314947/48938394-38614900-eef8-11e8-9698-774f102048c6.png)

Poderia ser colocadas antes de ocorrências da sessão:
![image](https://user-images.githubusercontent.com/13314947/48938494-8a09d380-eef8-11e8-83dc-b1e118ccf177.png)

**Comment by VictorFabreF** [comment]
A retirada já aparece no extrato ao lado da matéria como se fosse o resultado de uma votação.

![image](https://user-images.githubusercontent.com/19825887/48945141-6c486880-ef10-11e8-9bfa-8e8b3250fcc3.png)

Fiz um PR para que apareça também no resumo.
