### ISSUE TITLE
Distinguir campos de texto rico

### ISSUE THREAD

**Issue by eduardoedson** [interlegis/sapl#240]
Todas as text areas do SAPL utilizam texto rico conforme a imagem abaixo. É realmente necessário? Não seria o caso de retirar o texto rico antes de inserir no banco? Todas as text areas precisam de texto rico? Inserir código HTML no banco não poderia dar problema em relatórios PDF que utilizam o trml2pdf, por exemplo?

![captura de tela de 2016-03-07 09-35-45](https://cloud.githubusercontent.com/assets/7716450/13569736/84a09f40-e448-11e5-98a6-c4953cd3ac50.png)

**Comment by eduardoedson** [comment]
Este ticket relaciona-se ao #239

**Comment by marciomazza** [comment]
Nem todas as textareas devem ser de texto rico. Devemos nos basear em duas coisas para decidir o que é texto rico:
* As telas do sapl 2.5: o campo usa editor rico originalmente?
* O conteúdo do campo na base legada: se tiver html no dado, deve ser texto rico

**Comment by marciomazza** [comment]
É fundamental pesquisar se é possível colocar essa informação (se o campo é de texto rico) no Model. Existe um campo específico para isso? Associamos um widget diferente?

Coisas para olhar:
http://stackoverflow.com/questions/20095936/add-rich-text-format-functionality-to-django-textfield
https://code.djangoproject.com/wiki/RichTextField

**Comment by LeandroRoberto** [comment]
Pelo que me lembro, só os expedientes em sessão plenária tem texto rico!
acredito que uma implementação interessante é possuir uma função como em https://github.com/interlegis/sapl/blob/master/static/js/compilacao.js#L1

ela seria é chamada sempre que preciso... em locais específicos ou chamadas JavaSrcript que, como no caso da compilação, é muito usado.

**Comment by edwardoliveira** [comment]
| Pelo que me lembro, só os expedientes em sessão plenária tem texto rico!

É. Faz sentido ser só lá mesmo.

**Comment by LeandroRoberto** [comment]
Hoje uso texto rico em biografia de parlamentar também, mas atualmente sem o tinymce, faço em um textarea simples mesmo com o html cru. Fica a sugestão para esse campo ser texto rinco também!

**Comment by edwardoliveira** [comment]
Mudei o tinyMCE pra modo "exact" que exige o ID das textareas para que somente algumas sjeam texto rico. Neste caso, somente biografia do parlamentar e informações da casa legislativa. O resto vira text area normal. 

https://github.com/interlegis/sapl/pull/257/files

**Comment by edwardoliveira** [comment]
Uma alternativa aos IDs explícitos é usar uma classe CSS "fictícia" e colocar "selector": ".richText" no tinyMCE, por exemplo. Funciona igual, mas nesse caso não teria que ficar alterando o app.js caso aparecendo mais casos de texto rico na aplicação.

**Comment by LeandroRoberto** [comment]
**veja a possíbilidade de integração com isso...** mudei ainda está no meu branch... as mudanças básicas de estilo me parece necessárias por, no padrão, a fonte do corpo do tinymce ficar muito pequena... preciso do remove para campo texto que sematicamente deve ir pra tela readonly... 

https://github.com/interlegis/sapl/blob/compilacao/static/js/app.js

**Comment by LeandroRoberto** [comment]
o remove é usado também devido a inserções e remoções via ajax... acharia prudente chamar initTinyMCE apenas nas telas necessárias em foot_js e não no base.html

**Comment by edwardoliveira** [comment]
Concordo. Por mim pode usar o teu app.js. :+1: Assim que possível, faça o merge no master.

**Comment by LeandroRoberto** [comment]
mas gostei do lance do exact... talvez sendo passado como parâmetro no init

**Comment by LeandroRoberto** [comment]
os elements

**Comment by edwardoliveira** [comment]
Informar os elementos pode ser bom pra ter mais controle, mas fica a critério. Tanto faz pra mim. :smile_cat:
