### ISSUE TITLE
Atualização

### ISSUE THREAD

**Issue by rosenocmcc** [interlegis/sapl#2405]
Fizemos a atualização para a versão 3.1.136 e deu um erro quando tentamos abrir o resumo ou extrato.

## Comportamento Esperado
Abrir o resumo ou extrato

## Possível Solução
Existe um erro na configuração da tabela ordenação da sessão. Está configurado duas vezes para ordenar no 10 e 11 como conteúdo de mídia
Mudar o 11 para ocorrências da Sessão.

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Imagens do Ocorrido

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by VictorFabreF** [comment]
Boa tarde,
Você conseguiu solucionar o erro ou ele ainda persiste?

**Comment by rosenocmcc** [comment]
Solucionado

Em qui, 29 de nov de 2018 12:46, Victor Fabre <notifications@github.com
escreveu:
