### ISSUE TITLE
Norma jurídica - sugestão de próxima numeração

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#2410]
A sugestão de próxima numeração no cadastro de novas normas jurídicas para em 10000.

## Comportamento Esperado
Deveria sugerir o próximo numero como até o 10000
10001, 10002

**Comment by edwardoliveira** [comment]
Você fez um commit que transformou o numero de Norma Jurídica em alfanumérico: #879 (para casos como 19-A, 20-B, etc). Assim sendo, a ordenação estranha da figura se deve a uma ordenação lexicográfica ("9" > "11" quando os dois são strings) e para de funcionar no 10000.
