### ISSUE TITLE
Justificativas de usências não aparecem no resumo e no pdf da sessão

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2412]
## Comportamento Esperado
As justificativas de ausências deveriam aparecer no resumo e no pdf do resumo da sessão.

## Comportamento Atual
Isso não vem ocorrendo.

## Passos para Reproduzir
https://sapl.agudo.rs.leg.br/sessao/2742/justificativaausencia
https://sapl.agudo.rs.leg.br/sessao/2742/resumo
https://sapl.agudo.rs.leg.br/relatorios/2742/sessao-plenaria

## Contexto
Consulta ao resumo da sessão.

## Seu Ambiente
Versão usada (Release): 3.1.134
Nome e versão do navegador: Versão 70.0.3538.77 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
Vai estar disponível na versão 3.1.137.
