### ISSUE TITLE
Registro de tramitações em matérias anexadas

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2415]
## Comportamento Esperado
As matérias, depois de anexadas, devem passar a receber as tramitações das matérias anexadoras, pelo menos as de fim de tramitação.

## Comportamento Atual
Isso não ocorre, deve-se dar tramitação em ambas.

## Contexto
Registro de tramitações.

## Imagens do Ocorrido
![captura de tela de 2018-12-11 10-34-58](https://user-images.githubusercontent.com/19169882/49801190-a5fed900-fd30-11e8-8db3-7261bd79d14e.png)
![captura de tela de 2018-12-11 10-35-35](https://user-images.githubusercontent.com/19169882/49801207-b1520480-fd30-11e8-9531-cc923a13b7b6.png)

## Seu Ambiente
Versão usada (Release): 3.1.137
Nome e versão do navegador: Versão 70.0.3538.77 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by DtiLegBG** [comment]
Esse comportamento deveria ser opcional, por exemplo com uma seleção "registrar tramitação para as matérias anexadas". Chegamos a seguinte situação. Um Projeto de Lei, com duas emendas anexadas(no nosso caso emendas são matérias), uma emenda aprovada, outra rejeitada e o Projeto aprovado. Quando tramitado o projeto com uma tramitação cuja descrição é (Projeto Aprovado e aguardando sanção) vai registrar tramitação errada para a emenda anexada que foi rejeitada.

**Comment by LeandroJatai** [comment]
vide comentário: https://github.com/interlegis/sapl/commit/1f41f44651c0392fb3e265c9f748df5fed46d21e#commitcomment-32417150

**Comment by edwardoliveira** [comment]
@ricardocanela
