### ISSUE TITLE
Campo Horário de Término (de reunião de comissão) obrigatório!

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#2419]
## Comportamento Esperado
Deixar o campo Horário de Término da reunião de comissão sem a obrigatoriedade de preenchimento.

## Comportamento Atual
Exigência do preenchimento do campo

## Contexto
Sem o preenchimento desse campo, o registro não pode ser salvo.

## Imagens do Ocorrido
![image](https://user-images.githubusercontent.com/30807716/49892621-8ea71500-fe30-11e8-931d-456d55f42c27.png)

**Comment by edwardoliveira** [comment]
Deixar esse campo não obrigatório é a certeza de nunca o preeencherem em 80% das vezes. Qual a justificativa pra tirar essa obrigatoriedade?
