### ISSUE TITLE
Campo Número de Protocolo desprotegido  ao criar matéria ou documento

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#2421]
## Comportamento Esperado
Bloquear o campo Número de Protocolo para não permitir a sua alteração após a criação do documento.

## Comportamento Atual
No ato de criar um documento ou matéria após a protocolização, o campo Número de Protocolo fica livre para alteração.

## Possível Solução
Bloquear o campo para impossibilitá-lo  de ser alterado.

## Contexto
Caso esse campo seja alterado (propositalmente ou não), obviamente o número alterado não corresponderá mais ao numero de protocolo criado automaticamente, o que poderá provocar confusão posteriormente.

## Imagens do Ocorrido
![image](https://user-images.githubusercontent.com/30807716/49893770-60770480-fe33-11e8-9e92-b6ed57ded9b2.png)

**Comment by edwardoliveira** [comment]
Se não me engano, isso ocorre porque existe a possibilidade do documento/matéria ser criado primeiro e só depois vinculado a um protocolo criado posteriormente (inverte-se a ordem de criação protocolo -> matéria/doc)
