### ISSUE TITLE
Votação em Bloco - Aberta para usuario anônimo

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#2437]
O menu - Ordem do dia, votação em bloco -  está aberto para os usuários anônimos

http://sapl.camarabento.rs.gov.br/sessao/448/votacao_bloco_ordemdia
## Comportamento Esperado
Deveria estar disponível somente para usuários com o perfil de operador da sessão

## Imagens do Ocorrido
![image](https://user-images.githubusercontent.com/13314947/50292964-a9ddda00-0459-11e9-856f-ed08d16fdfae.png)

## Seu Ambiente

* Versão usada (_Release_): Release: 3.1.138
* Nome e versão do navegador: Firefox
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
@cesaraugc consertei no commit 0c87632ffe8308e7a74aa57a60450cf834dd041f mas tem que checar se ficou OK.
