### ISSUE TITLE
PESQUISA TEXTUAL NORMAS JURÍDICAS TEXTO ARTICULADO 

### ISSUE THREAD

**Issue by rosenocmcc** [interlegis/sapl#2445]
Após consolidar uma norma, não temos como fazer uma busca por palavras ou frase no texto compilado.

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Contexto
Os usuários anônimos não tem como consultar alguma informação que os interessa. Teria que ler todo o conteúdo da norma até o final da mesma.
Seria colocar um campo onde se digitasse uma palavra ou frase e as mesmas seria destacadas. 
![pesquisa](https://user-images.githubusercontent.com/36698231/50737570-1bd05600-11b2-11e9-8e42-4032263a9aa7.JPG)

## Imagens do Ocorrido

* Versão usada (_Release_):3.1.1.40
* Nome e versão do navegador: Crome
* Nome e versão do Sistema Operacional (desktop ou mobile): Windows ou Linux
* Link para o seu projeto (Caso de fork deste projeto): sapl.cmcc.rs.gov.br
![pesquisa](https://user-images.githubusercontent.com/36698231/50737581-491d0400-11b2-11e9-87f1-e49a894d5a79.JPG)

**Comment by edwardoliveira** [comment]
Duplicada de #2055
