### ISSUE TITLE
Proposição por texto articulado não está gerando Código de Documento

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#2447]
## Comportamento Esperado
Gerar o código de documento após criar o texto articulado na proposição

## Comportamento Atual
Após criar a proposição somente com texto articulado, o mesmo não aparece o Código de Documento , impedindo assim de ser recebido pelo Operador

## Passos para Reproduzir (para bugs)

1.  Adicionar Proposição
2.  Escolher texto articulado 
3. Salva proposição somente com o texto articulado

## Imagens do Ocorrido

![image](https://user-images.githubusercontent.com/1524415/50857203-14f14100-1374-11e9-91fe-10e9999ce60d.png)

## Seu Ambiente

* Versão usada (_Release_): 3.1.140
* Nome e versão do navegador: Google Chrome
* Nome e versão do Sistema Operacional (desktop ou mobile): Windows 10

**Comment by LeandroRoberto** [comment]
@puera, foi resolvido. Estará disponível na release 3.1.141
