### ISSUE TITLE
Informações de e-mail inválidas fazem SAPL não iniciar

### ISSUE THREAD

**Issue by fabiorauber** [interlegis/sapl#2449]
## Comportamento Esperado
SAPL deve sempre iniciar com sucesso ou reportar um erro no log do container.

## Comportamento Atual
O SAPL, quando inicializado pela primeira vez com informações de e-mail inválidas, não responde a requisições HTTP e também não retorna um erro no log. O Nginx retorna erro 499 para o usuário que tenta acessar a raiz do site.

## Possível Solução
Retornar um erro caso alguma informação de e-mail seja considerada incorreta.

## Passos para Reproduzir (para bugs)

1. Inicialize um container do SAPL e um de Postgresql com as seguintes variáveis de ambiente (versão 3.1.140):
```
USE_TLS = false
TZ = America/Sao_Paulo
EMAIL_SEND_USER = no-reply@domain.net
EMAIL_PORT = 25
EMAIL_HOST = smtp.domain.net
DEBUG = false
DATABASE_URL = postgresql://sapl:altereme@sapl-postgresql:5432/sapl
ADMIN_PASSWORD = altereme
ADMIN_EMAIL = contato@tecnico.net
```
2. Espere o SAPL criar as tabelas no banco e efetuar as migrations
3. Tente acessar o SAPL (na raiz)

## Contexto
Ao tentar inicializar o SAPL em um cluster Kubernetes, através do Chart https://github.com/interlegis/il-charts/tree/master/sapl

## Seu Ambiente

* Versão usada (_Release_): 3.1.140
* Nome e versão do navegador: Firefox 63 
* Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 18.04 Desktop

**Comment by edwardoliveira** [comment]
Entra no container e pega o .env gerado pra gente? Pode enviar por Telegram.

**Comment by fabiorauber** [comment]
```
SECRET_KEY=a_secret_key
DATABASE_URL = postgresql://sapl:altereme@sapl-postgresql:5432/sapl
DEBUG = false
EMAIL_USE_TLS = false
EMAIL_PORT = 25
EMAIL_HOST = smtp.domain.net
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_SEND_USER = ''
DEFAULT_FROM_EMAIL = ''
SERVER_EMAIL = ''
USE_SOLR = False
SOLR_COLLECTION = sapl
SOLR_URL = http://localhost:8983
```

**Comment by ulyssesBML** [comment]
Segui os passos e não consegui reproduzir o erro, como a issue é antiga eu vou fechar presumindo que foi arrumado. Caso não esteja nos reabrimos.
