### ISSUE TITLE
Falta de submenus no parâmetro (?iframe=1)

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#2450]
## Comportamento Esperado
Na versão anterior do SAPL , quando busca qualquer opção dos menus (Parlamentar, Comissões, Normas Jurídicas) com iframe ativo (parametro ?iframe=1) o submenu como por exemplo Parlamentar (Início , Mandatos, Filiações Partidárias, Comissões) constava no frame.

## Comportamento Atual
A versão atual do SAPL (3.1.141) os submenus desapareceram no parâmetro (?iframe=1) , assim faltando informações de busca pelo site. 

## Seu Ambiente

* Versão usada (_Release_): 3.1.141
* Nome e versão do navegador: Google Chrome
* Nome e versão do Sistema Operacional (desktop ou mobile): Windows 10

**Comment by LeandroRoberto** [comment]
tem um link público de seu sapl?

**Comment by puera** [comment]
https://sapl.armacaodosbuzios.rj.leg.br:44380
https://armacaodosbuzios.rj.leg.br/

Se você for pelo site , você ira ver nas buscas ( com iframe=1) não está constando os subsmenus

**Comment by LeandroRoberto** [comment]
Você comentou o código que cuida do iframe:
![image](https://user-images.githubusercontent.com/9630623/51342623-84a1b300-1a7b-11e9-80d2-f5b789dfdadf.png)
