### ISSUE TITLE
Link para matérias em parlamentar não está funcionando

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#2452]
Em Parlamentares / Matérias clicando no tipo de matéria o resultado é "

Resultados
--
Nenhuma matéria encontrada com essas especificações

"

http://sapl.camarabento.rs.gov.br/parlamentar/45/materias

## Comportamento Esperado
Deveria ser filtradas as matérias pelo tipo para o vereador 

## Imagens do Ocorrido
![image](https://user-images.githubusercontent.com/13314947/51684444-32a8e200-1fd3-11e9-9d75-05804b8a247f.png)

## Seu Ambiente

* Versão usada (_Release_): 3.1.142
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
@LeandroRoberto Esse commit bd2bc3a4f7d71f6f7b387f13694defcebaca93ea introduziu esse bug. Como a gente tá atualizando o django_filter pode ter a ver com isso. Vc tem ideia de como resolver?

**Comment by LeandroRoberto** [comment]
Resolvido!

**Comment by edwardoliveira** [comment]
:+1:
