### ISSUE TITLE
Dúvida - Sistema Operacional

### ISSUE THREAD

**Issue by guilherme-dimius** [interlegis/sapl#2458]
Na documentação para instalação do ambiente de desenvolvimento é dito que o ambiente de produção testado foi o Ubuntu 16.94. Vocês sabem se também funciona corretamente no Debian 9 (Stretch)?

**Comment by edwardoliveira** [comment]
Não. Não testamos no Debian 9. Apesar do Ubuntu ser baseado no Debian, as bibliotecas do S.O. podem mudar muito.

**Comment by guilherme-dimius** [comment]
Entendi. Tudo bem então, obrigado!
