### ISSUE TITLE
Erro ao tentar gerar PDF quando a logo não é encontrada

### ISSUE THREAD

**Issue by cesaraugc** [interlegis/sapl#2461]
## Comportamento Esperado

O PDF deveria ser gerado mesmo sem a imagem.

## Comportamento Atual

Atualmente ocorre um erro sem tratamento.

## Possível Solução

Fazer a checagem se a imagem do caminho existe.

## Passos para Reproduzir (para bugs)

Tentar gerar PDF em alguma página que possui essa funcionalidade.

## Imagens do Ocorrido

![captura de tela de 2019-01-29 16-38-19](https://user-images.githubusercontent.com/20192488/51931652-8ad15100-23e4-11e9-9e57-b922be862129.png)

**Comment by edwardoliveira** [comment]
Fixed by 0cc296f
