### ISSUE TITLE
Votação - Teclas

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#2472]
## Incluir as teclas de votações V, S, N, A na página do resumo da sessão

**Comment by edwardoliveira** [comment]
Agora com respeito ao pedido em si: porque colocar as teclas de atalho na tela de resumo?????

**Comment by paulot12** [comment]
Pois na Câmara Municipal, os parlamentares utilizam a página resumo, para acompanhar as informações das sessões.
