### ISSUE TITLE
Tela de pesquisa de usuários

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#2475]
Sugestão enviada por usuário do SAPL hospedado no Interlegis.

Boa tarde.

Gostaria de sugerir para que seja incluído na tela de criação de usuários  um campo de pesquisa onde possamos digitar e mandar pesquisar por nome os usuários.

Quando há um número maior de usuários fica difícil a procura para alterar algumas informações e configurações do mesmo.

## Comportamento Esperado

Permitir a filtragem de usuários por um campo de pesquisa.

## Comportamento Atual
A listagem é estática, isto é, mostra todos os usuários na tela de administração.

## Possível Solução
Adicionar um campo de pesquisa ou botão que leve para uma tela de filtragem.

## Contexto
Em casas com muitos usuários a listagem dificulta o gerenciamento.

## Imagens do Ocorrido
![obohddlebdgooigm](https://user-images.githubusercontent.com/9326037/52363239-6b13db80-2a29-11e9-99a3-71770aa29f32.png)

## Seu Ambiente

* Versão usada (_Release_): 3.1.142
* Nome e versão do navegador: Chrome 
* Nome e versão do Sistema Operacional (desktop ou mobile): Linux 64 bits 
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by LeandroRoberto** [comment]
Refatorar essa interface e não só a paginação:
- impl paginação
- adequar layout dos botões de create, edit e delete ao formato usado no restante do sistema
- passar o delete por uma tela de confirmação e não apagar diretamente como está fazendo
- contornar tela de erro gerada ao tentar apagar um usuário que não pode ser excluido devido a  protected foreign key.
