### ISSUE TITLE
Registro de presença

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#2477]
Registrar a presença através de leitor biométrico. 

## Comportamento Esperado
O parlamentar registrar a sua presença através de um leitor biométrico, como também abrir a página de votação com o acionamento no leitor biométrico.

**Comment by edwardoliveira** [comment]
Vc deve apagar o texto que começa com `<!--` e termina com `-->` e substituir pelo que tá pedindo no template. É necessário preencher um minímo de informação, mas não todos as seções.

![image](https://user-images.githubusercontent.com/9326037/52357599-91cc1500-2a1d-11e9-93f6-5da05c8ae7ec.png)
