### ISSUE TITLE
Leitor biométrico

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#2479]
Registrar a presença através de leitor biométrico.

## Comportamento Esperado
O parlamentar registrar a sua presença através de um leitor biométrico, como também abrir a página de votação com o acionamento no leitor biométrico.

Exemplo: Ao acionar o leitor biométrico, aparecer no painel de votação a presença do parlamentar e  habilitá-lo para a votação.

**Comment by edwardoliveira** [comment]
Não temos pessoal para implementar esse tipo de solução. Mas podemos colaborar com consultores externos contratados pela casa legislativa para desenvolver e integrar junto ao SAPL em um esquema de colaboração.
