### ISSUE TITLE
Bloco de alteração nao está registrando alteração

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#2487]
## Comportamento Esperado
Poder selecionar o texto para ser alterado

## Comportamento Atual
ao ser atualizado para versão 43 parou de funcionar a seleção no bloco de alteração

## Passos para Reproduzir (para bugs)
1. Criar um bloco de alteração na norma jurídica 
2. Tentar registrar uma alteração.

## Seu Ambiente

* Versão usada (_Release_): 3.1.143
* Nome e versão do navegador: Chrome

**Comment by edwardoliveira** [comment]
Você está se referindo a que tela exatamente e qual a funcionalidade. Poste screenshots!!!!

**Comment by puera** [comment]
![image](https://user-images.githubusercontent.com/1524415/52578454-62e1e480-2e0b-11e9-9f13-5b23b21af9a2.png)

Clicar "Registrar Altereção"

![image](https://user-images.githubusercontent.com/1524415/52578485-6ffed380-2e0b-11e9-899e-5d86f76a46cc.png)

Ao clicar "Selecionar" , nada acontece

**Comment by edwardoliveira** [comment]
@LeandroRoberto

**Comment by LeandroRoberto** [comment]
@puera , antes de clicar em selecionar, 
abra o inspetor de código com ctrl-shit-i
na tela que aparecer, clique em console... 
deixe essa tela e clique o no botão "selecionar" novamente... me diga se aparece alguma informação em vermelho:
aqui não aparece e está funcionando como esperado...
![image](https://user-images.githubusercontent.com/9630623/52579520-73935a00-2e0d-11e9-95b5-9def9daf3719.png)
![image](https://user-images.githubusercontent.com/9630623/52579532-7a21d180-2e0d-11e9-9b8b-8e3e87e4cbdb.png)

**Comment by puera** [comment]
@LeandroRoberto 

![image](https://user-images.githubusercontent.com/1524415/52579746-eb618480-2e0d-11e9-86c1-f2894518c71e.png)

**Comment by LeandroRoberto** [comment]
dê ctrl-f5 em seu navegador algumas vezes ou limpe completamente o cache

**Comment by puera** [comment]
@LeandroRoberto tentei com ctrl + F5 e limpei o total dos navegadores do Chrome e Firefox , mesmo assim o problema persiste

**Comment by LeandroRoberto** [comment]
esse código aí que deu erro em sua tela... 
no arquivo app.js...
linha 202
_this.radio
é do sapl 3.1.140

ele foi retirado lá na 3.1.141... 
isso é um problema de cache... não é um problema da 143

**Comment by puera** [comment]
![image](https://user-images.githubusercontent.com/1524415/52580400-62e3e380-2e0f-11e9-911a-fc85062d10cf.png)

**Comment by LeandroRoberto** [comment]
pois é... a função OptionalCustomFrontEnd nem existe mais... e o cache do seu navegador está chamando ela... como o sapl 3.1.143 não conhece mais esse JS cacheado ta dando pau... pode ser cache inclusive do ser servidor de aplicação.. o cache da maquina 192.168.88.158... possivelmente um nginx, certo?
precisa resolver isso aí na sua infraestrutra... 

no mais, a partir da 3.1.144 o frontend (plataforma, e não layout) será foi todo reformulado e problemas com cache não devem mais acontecer...

**Comment by puera** [comment]
@LeandroRoberto Sim é um nginx, vou ver que poder ser aqui nele, procurar algo pra limpar totalmente o cache dele , vlw Leandro!
