### ISSUE TITLE
Refazer relatório de sessão plenária com html/css e weasyprint

### ISSUE THREAD

**Issue by ulyssesBML** [interlegis/sapl#2488]
## Comportamento Esperado

Gerar relatorio de resumo de reunião atraves do html

## Possível Solução

Ultilizar configurações de css para impressão com weasyprint

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:  Firefox quantum 65.0
* Nome e versão do Sistema Operacional (desktop ou mobile):  Ubuntu 16.04.5 LTS 64-bit
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by ulyssesBML** [comment]
Não necessario.

**Comment by cesaraugc** [comment]
Houve um engano, issue e PR reabertos.
