### ISSUE TITLE
Escrever um teste para ordering em models e satisfazê-lo

### ISSUE THREAD

**Issue by LeandroJatai** [interlegis/sapl#2491]
1 - Escrever um teste que pegue todos os models do sapl e lance um erro se não houver explicitamente a definição de um ordering em Meta.
2 - Refatorar todos os models acusados pelo teste definindo explicitamente um ordering para eles

**Comment by edwardoliveira** [comment]
Olha... tem ***muuuuuuitos**** models sem ordering explícito, mas sou totalmente a favor de fazer testes assim.

**Comment by edwardoliveira** [comment]
**update:** acabei de lembrar que várias partes do código supõe um determinado padrão de ordering implícito. Pegue Mandato, por exemplo, que assume que o mandato mais recente é o last. Enquanto Legislatura assume que o mais recente é o first. Isso vai exigir visitar literalmente *_todos_* os pontos onde mandato (e legislatura, e parlamentares, etc) é utilizado no sistema pois o potencial dessa mudança introduzir inúmeros bugs é imensa!

**Comment by LeandroRoberto** [comment]
que assim seja... o DRF (e não só por ele, mas por todas nossas paginações dentro sistema) me lançou uma warning e, me lembro de ter visto na documentação, acho... que models cuja query não possui "order by" não oferecem nenhuma garantia na paginação...

**Comment by LeandroRoberto** [comment]
outro detalhe... sobre realmente possuirmos uma API...
hoje temos bem definido o detail e delete...
o list possui essa instabilidade devido a falta de "order by"...
agora... muitos dos create e update carecem de regra de negócio - que não aplicamos nos models e sim nas views :((((
devido a isso, ja fiz um paleativo emergencial, como exemplo a ser feito, em DocumentoAdministrativo - veja aqui: https://github.com/interlegis/sapl/commit/7e9142e7c89246f3bc2df5e1ee705644c6ff8942

**Comment by edwardoliveira** [comment]
Tudo bem, vamos fazer isso aí, mas como um PR. Teremos que testar bastante, mas se é necessário, paciência. :+1:

**Comment by LeandroJatai** [comment]
a api já conta com filtro básico via parametros que segue a as regras do django-filter. Como o django-filter não é só para filtro mas serve para vários propósitos, inclusive seleção de ordenação, implementei um field "o = OrderingFilter" na api... com isso quem usar a api pode passar esse campo como paramentro seguindo as regras dos parametros a ser passado ao order_by do django.
