### ISSUE TITLE
Informar número de matéria na incorporação de proposição

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#2492]
Permitir na incorporação de proposições seja possível digitar manualmente o número da matéria... considerando que quando usamos protocolo sem proposições isso já é possível no ato da criação da matéria.. acho que deva disponibilizar de forma parametrizavel isso.

## Comportamento Esperado
Permitir a digitação do número de matéria manualmente.

## Comportamento Atual

protocolo -> materia o sapl já permite só nao pemite quando é proposicao -> incorporacao -> protocolo

## Possível Solução
Ao incorporar permitir que o usuário informe o número da matéria, **que deve ser único para um tipo de matéria e ano**.

## Contexto
O sapl dele não controla os números das matérias... quem faz isso é o dpto legislativo manualmente... pois segundo ele... o parlamentar liga no protocolo e pede vários números de matéria e é designado ao parlamentar... daí o documento já vem com número e o automático do sapl é descartado

## Imagens do Ocorrido
Não se aplica.

## Seu Ambiente

* Versão usada (_Release_): 3.1.143
* Nome e versão do navegador: Chrome
* Nome e versão do Sistema Operacional (desktop ou mobile): Linux
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by LeandroJatai** [comment]
1º) da forma que foi implementado não era a proposta, vide vídeo explicativo: https://www.youtube.com/watch?v=FwFkw0Xug7k&t=7s

2º) mesmo que a forma fosse essa: o campo numero_materia_futuro não está sendo armazenado... tanto no create quanto no update não adianta informar, não grava no banco... 
![image](https://user-images.githubusercontent.com/9630623/53436539-31a40f80-39da-11e9-81c1-3325e9d648d2.png)
![image](https://user-images.githubusercontent.com/9630623/53436683-821b6d00-39da-11e9-8aab-a720c5faee7c.png)

3º) o autor até pode informar, o que difere do item (1º), essa pretenção de um futuro número (já que pelo senário imaginado - de Divinópolis) a casa legislativa faz o controle externo ao sapl e envia ao autor para que ele coloque no papel. Desta forma o autor sabe o número mas pode errar... então o operador do protocolo tem que ter a opção de alterar, assim como acontece no vínculo (anexação)

**Comment by VictorFabreF** [comment]
@LeandroJatai, o erro de não salvar no banco continuar ocorrendo com você? Testamos em diversas máquinas e em produção e não conseguimos replicar o erro após rodar todas as migrations. A sugestão de mudança é que na hora da incorporação o campo possa ser editado também?

**Comment by LeandroJatai** [comment]
na ocasião do teste ele não salvou... e precisa ser editavel na incorporação... após o almoço testo e se ainda for necessário, testo debugando!!!
