### ISSUE TITLE
Erro ao indicar relator de matéria na câmara municipal de Divinopolis MG

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#2503]
Ticket Chamado #918405

Ao entrar na matéria e tentar indicar um relator, o sistema informa que a matéria deveria estar em uma comissão, e a ultima tramitação não poderia estar em branco. Ao verificar, de fato a matéria se encontra-se numa comissão. Foram checadas as datas de tramitação, data da criação da comissão, data da designação dos membros da comissão e não foram encontrados inconsistências.

 ## Comportamento Esperado
Aceitação do relator da matéria

## Comportamento Atual
informa que a matéria deveria estar numa comissão e não permite a designação de relator.

## Imagens do Ocorrido
![image](https://user-images.githubusercontent.com/30807716/52877592-9a210000-3141-11e9-95c4-e22f54ed6d11.png)

![image](https://user-images.githubusercontent.com/30807716/52877619-aefd9380-3141-11e9-86c9-a5ecd9305c3f.png)

**Comment by 54adal** [comment]
O problema constatado é que a referida comissão estava duplicada, conforme abaixo:

CJLR - Comissão de Justiça, Legislação e Redação - estava como COMISSÃO
CJLR - Comissão de Justiça, Legislação e Redação - estava como ÓRGÃO

A tramitação da PLOE 3 foi feita justamente para comissão que estava categorizada como ORGÃO, por isso mesmo, não se permitia designar um relator. Feita a alteração, ou seja, para o tipo COMISSÃO, foi resolvido o problema. No entanto é necessário  tirar as duplicidades, que foram constatados inclusive em outras unidades de tramitação, conforme a seguir:

- Comissão de Educação, Cultura, Esporte e Lazer - CECEL - ambos estão como ORGÃO;
- Comissão de Saúde, Meio Ambiente, Esporte e Lazer - CSMAEL - ambos como ORGÃO;
- Diretoria Legislativa - DILEG - ORGÃO
- e Terceiros - TERCEIROS -ÓRGÃO

grato
Adal

**Comment by edwardoliveira** [comment]
Como se trata de inconsistências de dados, irei fechar esse ticket para ficar somente no sistema interno.
