### ISSUE TITLE
Erro ao tentar alterar a titularidade de membro de comissão

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#2505]
Ao tentar alterar a titularidade do membro de comissão pra SIM ou pra NÃO, ocorre o erro, conforme descrito pelo solicitante. 

## Comportamento Esperado
Que se permitisse a alteração do campo Titular da tela Membro de comissão para SIM ou para NÃO.

## Comportamento Atual
ao tentar fazer a alteração e salvar, ocorre o erro (FORMULÁRIO INVÁLIDO. SUAS ALTERAÇÕES NÃO FORAM SALVAS), e o campo Parlamentar fica em branco.

## Imagens do Ocorrido
![image](https://user-images.githubusercontent.com/30807716/52883751-2be53900-3153-11e9-9828-e656aa1b05d7.png)

**Comment by cantuariavc** [comment]
Bug corrigido no commit 1b5fbd84573b7b96616d73aa0709dba08d26bc74.
