### ISSUE TITLE
Sem acesso anônimo de Documento Acessório de Audiencia Pública 

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#2509]
## Comportamento Esperado
Usuários anônimos poderem acessar documento acessório das Audiências Públicas 

## Comportamento Atual
Usuário anônimo não acessa a parte de "Documento Acessório" da Audiência Pública pedindo um login com a aplicação de documento administrativo "Restritiva", acredito que Audiência Pública não deveria se enquadrar nessa regra.

## Passos para Reproduzir (para bugs)

1. Com opção de Visibilidade de Documentos Administrativos "Restritiva" -Está deslogado - Institucional - Audiências Públicas - Acessar uma audiência cadastrada - clicar em Documento Acessório

## Seu Ambiente

* Versão usada (_Release_): 3.1.143
* Nome e versão do navegador: Chrome
* Nome e versão do Sistema Operacional (desktop ou mobile): Windows 10

**Comment by cantuariavc** [comment]
Criei uma nova issue com o segundo bug: https://github.com/interlegis/sapl/issues/2515.
