### ISSUE TITLE
Foto e nome do parlamentar quando estiver no uso da sua palavra. 

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#2512]
Foto e nome do parlamentar quando estiver no uso da sua palavra. 

## Comportamento Esperado
Aparecer no painel a foto e nome do parlamentar, quando o mesmo estiver no seu pronunciamento. 

Exemplo: Parlamentar X - Foto.

**Comment by cesaraugc** [comment]
Issue a ser considerada: #2186

**Comment by cesaraugc** [comment]
Funcionalidade adicionada ao sapl 3.2 com o commit 3c6509828505b7d950580abff6f457f417ab2711.
