### ISSUE TITLE
Resolver warnings p/ Django 1.10

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#252]
Rodando `./manage.py check` observamos esse *warning* para resolver:
```
.../sapl/sessao/urls.py:110: RemovedInDjango110Warning: Support for 
string view arguments to url() is deprecated and will be removed in Django 1.10
(got django.views.static.serve). Pass the callable instead.
  {'document_root': settings.MEDIA_ROOT}),
```

**Comment by edwardoliveira** [comment]
Só tinha uma pequena modificação a ser feita no master de hoje (que é pra pegar URL de imagem, arquivos "uppados", etc) então fiz direto no master. Duas linhas de código:  b136222
