### ISSUE TITLE
Adicionar filas para indexação Solr e envio de email

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#2526]
A indexação Solr e o envio de emails são disparados via signals. Estes sinais ainda são um processamento serializado o que pode ocasionar falhas se o servidor Solr (ou o servidor SMTP) estiverem fora do ar. Isto causa um erro na adição/atualização/remoção ou até tramitação de matérias.

Abaixo a documentação do RealtimeSignalProcessor ( https://django-haystack.readthedocs.io/en/v2.4.1/signal_processors.html?highlight=queued#realtime-realtimesignalprocessor )  

![image](https://user-images.githubusercontent.com/9326037/53097278-dcf72500-34ff-11e9-92e2-41574361bfcf.png)

Como o PR https://github.com/interlegis/sapl/pull/2523 irá adicionar o redis como componente de arquitetura do SAPL é uma boa oportunidade de desacoplar a indexação e o envio de email do fluxo de lógica principal do SAPL.

O enfileiramento de email deve ser de implementação relativamente simples. 

No caso da indexação textual, podemos utilizar parte ou todo o código de outros projetos (não me agrada o uso dessas libs pois muito antigas e sem alteração nos últimos anos):

* https://github.com/django-haystack/queued_search
* https://github.com/django-haystack/celery-haystack
* https://github.com/mandx/haystack-rqueue
* https://github.com/mixcloud/django-celery-haystack-SearchIndex

Referências: 

https://django-haystack.readthedocs.io/en/v2.4.1/best_practices.html?highlight=queued#use-of-a-queue-for-a-better-user-experience

https://django-haystack.readthedocs.io/en/v2.4.1/searchindex_api.html?highlight=queued#keeping-the-index-fresh

## Comportamento Esperado
Ao inserir/atualizar/remover uma matéria legislativa, norma jurídica ou documento acessório, o comando de indexação textual será enviado para uma fila no Redis e o processamento seguirá normalmente. Um processo periódico irá agrupar as mensagens desta fila e indexar em lote. Algumas vantagens desta abordagem:

  1. Desacoplar a indexação do fluxo principal torna o processamento mais rápido e otimiza as chamadas de rede ao Solr;
  2. Em caso de falha do(s) servidor(es) Solr, o processamento das matérias não será afetado.
  3. As mensagens não enviadas são guardadas até que o serviço Solr/SMTP volte a funcionar.

## Comportamento Atual
O processamento do envio de email ou indexação no Solr, apesar de rápidos, travam a thread de processamento do SAPL e podem até falhar por erros nestas duas peças de INFRA (Solr, SMTP).

## Possível Solução
1. A indexação textual e envio de email enfileiram as mensagens numa fila no Redis;
2. Dois processos periódicos (via cron job ou script simples) varrem periodicamente a fila e indexam ou enviam os emails.

## Contexto
Esta mudança trará mais confiabilidade ao custo de mais uma peça de arquitetura (Redis);
Podemos, opcionalmente, usar o celery e o django-celery para controle da fila de tarefas: https://github.com/ask/celery e https://github.com/ask/django-celery https://github.com/pmclanahan/django-celery-email/tree/master/djcelery_email

**Riscos:** Como a ideia é ter o Redis usado pra três coisas distintas (websockets, e-mail e indexação) não seria interessante que a aplicação tentasse indexar o email ou enviar o dados do websocket via smtp.

## Seu Ambiente

* Versão usada (_Release_): 3.1.144
* Nome e versão do navegador: Chrome
* Nome e versão do Sistema Operacional (desktop ou mobile): Linux
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by LeandroJatai** [comment]
@edwardoliveira e @VictorFabreF, começaram a mexer nessa issue? se não, poderiam mudar o milestone pra 3.2 e preparar-vos para abrir o branch 3.2.x? por favor!

**Comment by edwardoliveira** [comment]
Eu não tive tempo de abrir o branch 3.2 hoje, DESCULPA! Como vamos fazer? 

1. Matar  master e criar um novo master a partir do 3.1.x?

2. Criar um novo branch 3.2.x a partir do 3.1.x?

Estou tendendo pra primeira opção.

**Comment by LeandroJatai** [comment]
Ops...  fui impaciente!!!  Eu que devo pedir desculpas pelo comentário tosco...
