### ISSUE TITLE
Separar cadastro de Parlamentar de vinculação a Legislatura

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#2536]
Atualmente, o cadastro de parlamentares é feito mediante a seleção da legislatura e posterior clique no botão Adicionar Parlamentar. Esse tipo de operação induz ao erro pois o operador acaba por cadastrar o parlamentar mais de uma vez, uma para cada legislatura.

## Comportamento Esperado
Evitar a duplicidade de parlamentares cadastrados no SAPL. O cadastro deve ser único com vários mandatos.

## Comportamento Atual
O sistema permite que um mesmo parlamentar seja cadastrado múltiplas vezes no sistema, gerando inconsistência de dados.

## Possível Solução
A função do botão de 'Adicionar Parlamentar' é vincular um Parlamentar previamente cadastrado a uma Legislatura. A ideia é que a tela de cadastro do parlamentar seja movida para Tabelas Auxiliares (sendo chamada de Cadastrar Parlamentar) e uma nova tela (com form) que vincule parlamentares cadastrados a suas legislaturas através da criação de um mandato no botão Adicionar Parlamentar.

## Passos para Reproduzir (para bugs)
1. 
2.
3.
4.

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by LeandroJatai** [comment]
Maravilha!!!

**Comment by LeandroJatai** [comment]
Isso nos remete a uma separação:
- da tela administrativa do usuário que não precisa haver seleção legislatura para dar manutenção
- da tela anônima que pode inclusive concentra mesa diretora e parlamento numa interface só. vide: https://www.jatai.go.leg.br/parlamentar
