### ISSUE TITLE
Separar criação de mandato e parlamentar

### ISSUE THREAD

**Issue by cantuariavc** [interlegis/sapl#2541]
## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by LeandroJatai** [comment]
tem relação e é praticamente a mesma solução que deveria ser refatorada junto com #2536

**Comment by edwardoliveira** [comment]
É a mesma issue. :)
