### ISSUE TITLE
Formatação do Extrato do SAPL E ASSINATURA 

### ISSUE THREAD

**Issue by adrchaves** [interlegis/sapl#2553]
Solicito uma opção de gerar arquivo em PDF também no Extrato da Sessão Plenária do SAPL, assim como é feito no Resumo. Existe a opção de estar gerando o PDF no Chrome, porém aparece no rodapé informações como:

"Desenvolvido pelo Interlegis em software livre e
aberto. Release: 3.1.146 Conteúdo e dados sob licença Creative Commons
4.0
Câmara Municipal de Piraí (RJ)
Rua Dr. Luiz Antonio Garcia da Silveira, 16
CEP: 27175/000 | Telefone: (24)2411-9500
Site | Fale Conosco"

As informações do tipo abaixo até poderiam ficar como rodapé:

"Câmara Municipal de Piraí (RJ)
Rua Dr. Luiz Antonio Garcia da Silveira, 16
CEP: 27175/000 | Telefone: (24)2411-9500
Site | Fale Conosco"

OUTRA COISA SERIA, na configuração de aplicações, dentro de TABELAS AUXILIARES, termos mais opções na ASSINATURA.
Obrigada pela atenção e aguardo retorno.

Adriana Chaves

**Comment by edwardoliveira** [comment]
@ulyssesBML

**Comment by adrchaves** [comment]
> 
> 
> Solicito uma opção de gerar arquivo em PDF também no Extrato da Sessão Plenária do SAPL, assim como é feito no Resumo. Existe a opção de estar gerando o PDF no Chrome, porém aparece no rodapé informações como:
> 
> Desenvolvido pelo Interlegis em software livre e
> aberto. Release: 3.1.146 Conteúdo e dados sob licença Creative Commons
> 4.0
> Câmara Municipal de Piraí (RJ)
> Rua Dr. Luiz Antonio Garcia da Silveira, 16
> CEP: 27175/000 Telefone: (24)2411-9500
> Site Fale Conosco
> 
> As informações do tipo abaixo até poderiam ficar como rodapé:
> 
> Câmara Municipal de Piraí (RJ)
> Rua Dr. Luiz Antonio Garcia da Silveira, 16
> CEP: 27175/000 Telefone: (24)2411-9500
> Site Fale Conosco
> 
> OUTRA COISA SERIA, na configuração de aplicações, dentro de TABELAS AUXILIARES, termos mais opções na ASSINATURA.
> Obrigada pela atenção e aguardo retorno.
