### ISSUE TITLE
Adicionar pesquisa de parlamentar

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#2554]
O SAPL não dispõe de uma tela para pesquisar parlamentar. Atualmente deve-se varrer legislatura a legislatura para encontrar o parlamentar. 

## Comportamento Esperado
Uma tela de pesquisa de parlamentar que permita pesquisar, incluindo a opção de filtrar via checkbox por parlamentares ativos, por exemplo.

## Comportamento Atual
Não existe nenhuma tela nesse sentido.

## Possível Solução
Criar uma tela de pesquisa de parlamentar.

## Passos para Reproduzir (para bugs)
Não se aplica

## Contexto
Usabilidade do sistema.

## Imagens do Ocorrido
Não tem.

## Seu Ambiente

* Versão usada (_Release_): 3.1.146
* Nome e versão do navegador: Chrome.
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by DtiLegBG** [comment]
A pesquisa de parlamentares deixou de ser mostrada não sei exatamente em qual versão, mas na Release: 3.1.150 não aparece.
![image](https://user-images.githubusercontent.com/13314947/55398804-d2c53f00-551f-11e9-9f71-851ff13d9e20.png)

**Comment by edwardoliveira** [comment]
@ricardocanela poderia usar o git bisect pra descobrirmos qual commit removeu essa pesquisa? :)

**Comment by puera** [comment]
@edwardoliveira foi retirado no revert commit 3937a3c 
e reposto novamente no commit 9405129
