### ISSUE TITLE
INCLUIR RESUMO DE VOTAÇÃO COM AUTORES, VOTOS E TOTAL, NO EXTRATO 

### ISSUE THREAD

**Issue by adrchaves** [interlegis/sapl#2557]
Necessidade de inclusão no EXTRATO, da totalização de votos por matéria e voto nominal quando for o caso, no módulo Sessão Plenária.

**Comment by edwardoliveira** [comment]
Por favor, preencha com mais informações segundo o template na criação da issue (substituindo os `<!--` e `-->` pela descrição detalhada.. A gente fecha issues com um parágrafo só.

![image](https://user-images.githubusercontent.com/9326037/53429571-ade32680-39cb-11e9-9499-118ce21df637.png)

**Comment by adrchaves** [comment]
<!...Necessidade de inclusão no EXTRATO, da totalização de votos por matéria e voto nominal quando for o caso, no módulo Sessão Plenária...>
