### ISSUE TITLE
Vinculação de Matéria com a respectiva Norma Jurídica com algum problema

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#2558]
Ao inserir a Norma Jurídica e inserir os dados da matéria legislativa correspondente, o sistema está trazendo a ementa e indexação de uma outra matéria.

Matéria a ser a ser vinculada. (observe o campo indexação = MARIA RECLA - matéria de 2018)

![image](https://user-images.githubusercontent.com/30807716/53429144-cdc61a80-39ca-11e9-8798-b6fd839d2e3d.png)

Vinculação da Matéria à Norma: (observe o campo de indexação = ELCIA MARIA que corresponde à matéria de 2019)
![image](https://user-images.githubusercontent.com/30807716/53429109-bf77fe80-39ca-11e9-9635-602d20e8b174.png)

Matéria que está sendo relacionada:
![image](https://user-images.githubusercontent.com/30807716/53429367-45944500-39cb-11e9-8205-92affdf4cf33.png)

**Comment by edwardoliveira** [comment]
Só uma dica: pode colocar quantas screenshots quiser (isso é até muito bom), mas nos próximos siga o template da figura abaixo. Substituindo o '' pelo texto que vc deseja colocar. Um mínimo de duas seções pelo menos, e o mais detalhado possível.

![image](https://user-images.githubusercontent.com/9326037/53431597-96a63800-39cf-11e9-8b09-67cbe37cfff2.png)
