### ISSUE TITLE
Formatação do Extrato do SAPL E ASSINATURA

### ISSUE THREAD

**Issue by adrchaves** [interlegis/sapl#2561]
Solicito uma opção de gerar arquivo em PDF também no Extrato da Sessão Plenária do SAPL, assim como é feito no Resumo. Existe a opção de estar gerando o PDF no Chrome, porém aparece no rodapé informações como:

Desenvolvido pelo Interlegis em software livre e
aberto. Release: 3.1.146 Conteúdo e dados sob licença Creative Commons
4.0
Câmara Municipal de Piraí (RJ)
Rua Dr. Luiz Antonio Garcia da Silveira, 16
CEP: 27175/000 Telefone: (24)2411-9500
Site Fale Conosco

As informações do tipo abaixo até poderiam ficar como rodapé:

Câmara Municipal de Piraí (RJ)
Rua Dr. Luiz Antonio Garcia da Silveira, 16
CEP: 27175/000 Telefone: (24)2411-9500
Site Fale Conosco

OUTRA COISA SERIA, na configuração de aplicações, dentro de TABELAS AUXILIARES, termos mais opções na ASSINATURA.
Obrigada pela atenção e aguardo retorno

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Ainda não é isso. Tá tudo em branco.

**Comment by LeandroJatai** [comment]
@adrchaves 
fiz uma correção no seu texto... vc **não pode** escrever ou substituir a escrita dentro desse código...
`<!-- blablabal -->`

**Comment by adrchaves** [comment]
Obrigada 🙂

Adriana Chaves
Gerente Legislativo
CMPiraí-RJ

________________________________
De: Leandro Roberto Silva <notifications@github.com>
Enviado: quarta-feira, 27 de fevereiro de 2019 17:02
Para: interlegis/sapl
Cc: adrchaves; Mention
Assunto: Re: [interlegis/sapl] Formatação do Extrato do SAPL E ASSINATURA (#2561)


@adrchaves<https://github.com/adrchaves>
fiz uma correção no seu texto... vc não pode escrever ou substituir a escrita dentro desse código...

**Comment by edwardoliveira** [comment]
@adrchaves Como seria essa "configuração de assinaturas" ? Atualmente o extrato permite três tipos (mesa-diretora, presidente e todos). O que seria para alterar em relação a isso?

**Comment by adrchaves** [comment]
Olá Eduard,

Aqui na Câmara de Piraí somente o Presidente e o 1º Secretário que assinam, e não existe a opção para incluir somente eles

________________________________
De: Edward <notifications@github.com>
Enviado: quinta-feira, 7 de março de 2019 14:36
Para: interlegis/sapl
Cc: adrchaves; Mention
Assunto: Re: [interlegis/sapl] Formatação do Extrato do SAPL E ASSINATURA (#2561)


@adrchaves<https://github.com/adrchaves> Como seria essa "configuração de assinaturas" ? Atualmente o extrato permite três tipos (mesa-diretora, presidente e todos). O que seria para alterar em relação a isso?

**Comment by edwardoliveira** [comment]
@ulyssesBML A geração do PDF já está sendo feita, correto? Podemos estudar a melhor forma de fazer essa configuração de assinatura em outra issue, o que acha?

**Comment by adrchaves** [comment]
Pode ser.. Vou tentar preencher aquele martírio...rsss

________________________________
De: Edward <notifications@github.com>
Enviado: terça-feira, 19 de março de 2019 23:29
Para: interlegis/sapl
Cc: adrchaves; Mention
Assunto: Re: [interlegis/sapl] Formatação do Extrato do SAPL E ASSINATURA (#2561)


@ulyssesBML<https://github.com/ulyssesBML> A geração do PDF já está sendo feita, correto? Podemos estudar a melhor forma de fazer essa configuração de assinatura em outra issue, o que acha?

**Comment by VictorFabreF** [comment]
Resolvido no commit 6abe23936da004695b2fff4598eaf5d0406ecbf5
