### ISSUE TITLE
INCLUIR RESUMO DA TOTALIZAÇÃO DE VOTOS COM AUTORES E TOTAL, NO EXTRATO

### ISSUE THREAD

**Issue by adrchaves** [interlegis/sapl#2562]
Necessidade de inclusão no EXTRATO, da totalização de votos por matéria e voto nominal quando for o caso, no módulo Sessão Plenária.

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Ainda não é isso, mas tá quase lá.

**Comment by edwardoliveira** [comment]
@ulyssesBML Podemos fechar essa issue?
