### ISSUE TITLE
Dados de parlamentar Adriana Goltz não aparecem

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2568]
## Comportamento Esperado
A página de dados básicos do parlamentar Adriana Goltz devia aparecer para o usuário anônimo.

## Comportamento Atual
A página de dados básicos da parlamentar não é mostrada, embora para o usuário logado seja possível acessá-los.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/parlamentar/25

## Contexto
Acesso a dados básicos do parlamentar Adriana Goltz.

## Imagens do Ocorrido
![captura de tela de 2019-02-27 10-58-12](https://user-images.githubusercontent.com/19169882/53495611-0c1d1180-3a7f-11e9-9bc0-3129628a54e3.png)
![captura de tela de 2019-02-27 10-58-21](https://user-images.githubusercontent.com/19169882/53495632-12ab8900-3a7f-11e9-9612-c07fcf9c7a53.png)

## Seu Ambiente
Versão usada (Release): 3.1.146
Nome e versão do navegador: Versão 71.0.3578.98 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by VictorFabreF** [comment]
Bom dia,
Algum dado dessa parlamentar foi editado recentemente?

**Comment by andreagudo** [comment]
Não.

Em qua, 27 de fev de 2019 11:14 AM, Victor Fabre <notifications@github.com
escreveu:

**Comment by andreagudo** [comment]
Se houve, foi em janeiro ou dezembro.

Em qua, 27 de fev de 2019 11:28 AM, André Brum da Silva <
andrebrum2009@gmail.com escreveu:

**Comment by VictorFabreF** [comment]
@LeandroJatai o erro foi esse aqui:

```AttributeError at /parlamentar/25
'PngStream' object has no attribute 'chunk_tIME'
Request Method:  GET
Request URL:  https://sapl.agudo.rs.leg.br/parlamentar/25
Django Version:  1.11.20
Exception Type:  AttributeError
Exception Value:  
'PngStream' object has no attribute 'chunk_tIME'
Exception Location:  /usr/lib/python3.6/site-packages/PIL/PngImagePlugin.py in call, line 140
Python Executable:  /usr/bin/python3.6
Python Version:  3.6.6
Python Path:  
['/var/interlegis/sapl',
 '/usr/bin',
 '/usr/lib/python3.6/site-packages/_pdbpp_path_hack',
 '/usr/lib/python36.zip',
 '/usr/lib/python3.6',
 '/usr/lib/python3.6/lib-dynload',
 '/usr/lib/python3.6/site-packages']
Server time:  Qua, 27 Fev 2019 11:36:44 -0300```

Tem alguma dica ou ideia do que pode ser?

**Comment by LeandroJatai** [comment]
@VictorFabreF e @andreagudo, paleativamente resolvido, voltando a versão do Pillow para 5.1.0... mas esta imagem é uma imagem mal formada e deveria ser substituída... hora ou outra deveremos liberar a versão do Pillow e o erro pode voltar a ocorrer... veja... o simples fato de eu pegar a imagem, abrir ela no GIMP e gravá-la novamente, estando ainda no Pillow 5.4.1 o erro foi extinto... por algum motivo que não localizei numa pesquisa inicial, o Pillow passou a exigir que chunk_tIME esteja presente nas imagens... bem, por hora, fiquemos na 5.1.0...

**Comment by edwardoliveira** [comment]
Eu não tinha visto esse comentário então fiz isso. 

**Tudo indica que se tratam de arquivos PNG corrompidos (ou com metadados faltando). Eu não conheço o formato PNG, mas a biblioteca Python esperava um determinado metadado que não estava presente.

Eu corrigi convertendo a imagem original pra jpg (gerando uma nova imagem) e daí converti de novo para png (tudo usando o ImageMagick) e isso corrigiu o erro pra essa imagem.**
