### ISSUE TITLE
Melhoramento do header em mobile

### ISSUE THREAD

**Issue by IsaacCastro** [interlegis/sapl#2586]
## Problema 
Pessoal, depois da última atualização do SAPL, estou tendo problemas na exibição mobile do header do portal, ou seja, nome da Casa, o que dificulta a experiência do usuário.

## Causa
Aumento da fonte da classe "vcenter", bem como exibição do logo do portal em telas menores (classe "img-responsive").

## Comportamento Atual
Devido aos fatos anteriores, casas com nomes relativamente grandes, como é nosso caso aqui, apresentam esses problemas, que se arrastam para o footer, conforme imagens (Resolução 360px):
![imagem cabecalho](https://user-images.githubusercontent.com/43033220/53673908-20246700-3c69-11e9-8fe1-9256ddcfb30a.png)
![imagem rodape](https://user-images.githubusercontent.com/43033220/53673911-27e40b80-3c69-11e9-81eb-664375323c81.png)

## Possível Solução
A meu ver esse comportamento pode ser modificado inserindo outra Media Querie a partir de 600px, modificando as fontes e exibição em bloco da classe "vcenter" e alinhando os elementos da classe "masthead", conforme segue na imagem abaixo.

Modificação sugeria em global.e4ae5421.css:

SOLUÇÃO IMPLEMENTADA em resolução de 360px:
`@media (max-width:600px){
         .masthead .navbar-brand .vcenter{
             display:block;
             font-size:15px;
             line-height:1em;
    }    
    .masthead {text-align: center;}

    }`
![sapl saojosedodivino pi leg br_ galaxy s5](https://user-images.githubusercontent.com/43033220/53674121-8493f600-3c6a-11e9-804b-eba1f20092e9.png)

Obrigado pessoal.

**Comment by IsaacCastro** [comment]
Olá Leandro!

Qual a previsão de vcs implementaram minha solicitação?

Outrossim, Vcs pensam em subir o favicon de cada casa, fica interessante pra fins de institucionalização.

**Comment by LeandroJatai** [comment]
esta issue vou fazer agora...
quanto ao favicon, deixo para o @edwardoliveira resolver...

**Comment by IsaacCastro** [comment]
Até o exato momento, o SAPL daqui continua na versao 3.1.146, ou seja o bug continua.

**Comment by LeandroJatai** [comment]
as mudanças de desenvolvimento não entram imediatamente... a issue é fechada quando resolvemos o problema mas a ateração não vai de imediato para seu sapl.... só vai quando uma nova release é gerada e o dpto de infra do interlergis faz a atualização... a correção do problema dessa issue entra na release 3.1.147 que já foi criada na sexta-feira... agora depende da infra atualizar seu sapl...
