### ISSUE TITLE
Edição de Composição de Comissões

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#259]
em: http://localhost:8000/comissoes/15/composicao/37/parlamentar
- Trocar  o título formulário de cadastro
- Incluir o botão cancelar

em: http://localhost:8000/comissoes/15/composicao
- a ordem está sendo influenciada pela edição. Sugiro fixar em alfabética pelo nome, ou ainda melhor, sempre primeiro o presidente e vice... depois os membros sempre em ordem alfabética

**Comment by eduardoedson** [comment]
Tinha sido conversado que o botão voltar seria 'subtituido' pelo voltar do navegador.
Fora isso, as alterações do titulo do formulário e a listagem ordenada por nome foram feitas em https://github.com/interlegis/sapl/commit/c4984d395652e01dfc4b0cf3dba40cd72a9b6b4c

**Comment by LeandroRoberto** [comment]
fiquem a vontade para, nas issues que eu criar,  fechá-las ou marcá-las wontfix...  ;)

**Comment by marciomazza** [comment]
Importante: olhar se este é um caso de crud mestre-detalhe.

**Comment by eduardoedson** [comment]
Foi resolvido com uso do CRUD no PR #471
