### ISSUE TITLE
Extrato Sessão - Não é mostrada mais as ocorrências da Sessão

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#2591]
Não está sendo mostrada mais as ocorrências da sessão no extrato da sessão

## Comportamento Esperado
![image](https://user-images.githubusercontent.com/13314947/54032443-5f364900-4190-11e9-9b7e-70570b6a5658.png)

## Seu Ambiente

* Versão usada (_Release_): 3.1.146
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
@DtiLegBG Vc tem que referenciar a issue no comentário do commit com "FIX #<número do PR>", pois assim quando for feito o merge ele fecha automaticamente a issue.

**Comment by DtiLegBG** [comment]
Ok, obrigado!
