### ISSUE TITLE
Django-reversion

### ISSUE THREAD

**Issue by LeandroJatai** [interlegis/sapl#26]
Integrar django-reversion ao projeto.

- [ ] Testar o que está acontecendo quando um objeto é **apagado** e ver se é mesmo necessário registrar no sinal de delete (`sapl.rules.apps.revision_pre_delete_signal`)

**Comment by LeandroRoberto** [comment]
@eduardoedson @edwardoliveira essa issue devia ser fechada mesmo... desistiu-se desse procedimento?

**Comment by marciomazza** [comment]
Pelo menos parte disso foi implementado pelo @LucianoAlmeida em #115. Estou reabrindo para conferirmos se está funcionando 100%.

Numa rápida olhada percebi que a interface no `django-admin` não está ok.
Deve ser possível **ver as versões de cada model e reverter no django admin**.

O sistema precisa de log de auditoria e a possibilidade de reverter alterações de dados. Lembro que já existia exclusão lógica no sapl 2.5, que não parece suficiente para um sistema como esse.

A funcionalidade é importante por vários motivos:
* o suporte às hospedagens: os usuários muitas vezes cometem erros de cadastro e que precisamos poder rastrear e reverter
* segurança: é preciso saber indicar quem alterou dados
* gestão: sempre nos perguntam sobre a frequência de atualização dos sistemas e este log fornece a possibilidade de responder com algumas consultas

**Comment by marciomazza** [comment]
**Testar o que está acontecendo quando um objeto é apagado** e ver se é mesmo necessário registrar no sinal de delete (`sapl.rules.apps.revision_pre_delete_signal`)

**Comment by marciomazza** [comment]
Pergunta importante, para ser respondida nessa issue: **como o django-reversion trata mudanças em arquivos** (o que está no `media`)?

**Comment by edwardoliveira** [comment]
@LeandroJatai Podemos fechar essa issue?
