### ISSUE TITLE
Relatório Matérias em Tramitação inclui matérias arquivadas

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2610]
## Comportamento Esperado
Deveria apresentar apenas as matérias em tramitação.

## Comportamento Atual
Está incluindo as matérias arquivadas, pelo menos para o ano de 2019.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/sistema/relatorios/materia-por-tramitacao?ano=2019&tipo=&tramitacao__unidade_tramitacao_destino=&tramitacao__status=

## Contexto
Geração de relatório de Matérias em Tramitação em 2019.

## Imagens do Ocorrido
![Captura de tela de 2019-03-13 14-44-50](https://user-images.githubusercontent.com/19169882/54302059-eb84a980-459e-11e9-848e-079dfef29a46.png)
![Captura de tela de 2019-03-13 14-45-27](https://user-images.githubusercontent.com/19169882/54302083-f7706b80-459e-11e9-99c6-9a54a066b779.png)

## Seu Ambiente
Versão usada (Release): 3.1.146
Nome e versão do navegador: Versão 71.0.3578.98 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by VictorFabreF** [comment]
Bom dia,
O filtro usado para esse é relatório é baseado no campo "Em tramitação?" da matéria e não no seu histórico de tramitação. Dessa forma, todas as matérias do ano pesquisado que tenham esse campo marcado como "Sim" aparecerão na listagem, como é o caso do Projeto de Lei 10/2019 (foto 1) do exemplo da imagem acima. Mesmo matérias sem nenhuma tramitação e que tenham o campo em questão como "Sim" aparecem na listagem. 
O "Arquivo - ARQ" é apenas um órgão como qualquer outro no sistema, não tendo nenhuma diferença a nível de modelo para que o sistema possa excluir dos resultados as matérias que para este órgão tenham sido tramitadas, a mesma lógica se segue para o status de tramitação "Arquivado".
Pode-se adicionar, como sugestão para uma versão futura, alguma mudança que indique na unidade de tramitação ou então no status de tramitação que aquela unidade/status gera o fim da tramiatação da matéria e que dessa forma a mesma deve deixar de aparecer no relatório em questão. No entanto, na versão atual do sistema (3.1.146) isso não ocorre e a lógica de negócio completa seria após o arquivamento da matéria, mudar o campo "Em Tramitação?" para "Não", eliminando dessa forma a matéria dos resultados do relatório de matérias em tramitação.
Caso queira, você pode abrir uma issue com a sugestão supracitada, assim, no futuro, ela será implementada.

![image](https://user-images.githubusercontent.com/19825887/54351933-6d241800-462f-11e9-8240-37001cf389db.png)
Foto 1 -  detalhe do Projeto de Lei 10/2019
