### ISSUE TITLE
Geração de pdf para texto articulado

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#2613]
## Comportamento Atual
Com o merge do PR #2607 Os arquivos header-relatorio.css, relatorio.css estão sendo deletados ao dar build no sapl-frontend ocasionando perda de arquivos e deixando o arquivo gerado com erros

## Possível Solução
Incorporar esses .css ao projeto sapl-frontend

## Imagens do Ocorrido
![image](https://user-images.githubusercontent.com/1524415/54398810-68487e00-469a-11e9-8180-647216494fd9.png)

## Seu Ambiente

* Versão usada (_Release_): 3.1.146
* Nome e versão do navegador: Chrome 
* Nome e versão do Sistema Operacional (desktop ou mobile): Windows 10

**Comment by puera** [comment]
@LeandroJatai o que acha?

**Comment by LeandroJatai** [comment]
valeu @puera tem muito mais que isso...  reverti o PR e reabri a issue #2192

**Comment by LeandroJatai** [comment]
obrigado!!!
