### ISSUE TITLE
Sessão - Retirada de Pauta

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#2619]
Em Sessão Plenária / Abertura / Retirada de Pauta , o campo requente não mostra os parlamentares ativos

## Imagens do Ocorrido

![image](https://user-images.githubusercontent.com/13314947/54527479-d91cbe00-4958-11e9-9d80-a85c26066395.png)

## Seu Ambiente

* Versão usada (_Release_): 3.1.147
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
A sessão está aberta? Os parlamentares estão presentes? A matéria está na ordem do dia ou expediente?

**Comment by DtiLegBG** [comment]
Opa, testando agora percebi que lista os parlamentares que estão presentes na sessão, ou seja, está funcionando. Muito Obrigado
