### ISSUE TITLE
Erro ao gerar pdf do resumo da sessão

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2623]
## Comportamento Esperado
O pdf deve ser gerado.

## Comportamento Atual
Está apontando erro 500.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/relatorios/2752/sessao-plenaria

## Contexto
Impressão do pdf do resumo da sessão plenária.

## Imagens do Ocorrido
![Captura de tela de 2019-03-18 13-55-38](https://user-images.githubusercontent.com/19169882/54548148-0a5fb300-4986-11e9-91c1-62f1f30d811c.png)

## Seu Ambiente
Versão usada (Release): 3.1.147
Nome e versão do navegador: Versão 71.0.3578.98 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by VictorFabreF** [comment]
Problema resolvido já.
