### ISSUE TITLE
Extrato da Sessão

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#2628]
1- Seria interessante que em extrato, matérias da ordem do dia fossem mantida a mesma identidade visual do restante.
2 - O Campo Turno está vindo em branco.
3 - Não aparecem as assinaturas
4 - Erro 500 - #2627

## Comportamento Esperado

1 - Projeto de Lei Ordinária nº 6 de 2019; Descrição: AUTORIZA O PODER EXECUTIVO A CONCEDER A OCUPAÇÃO DE ESPAÇOS EM LOGRADOUROS PÚBLICOS PARA A INSTALAÇÃO DE PLACAS INDICATIVAS DE LOGRADOUROS, RECIPIENTES COLETORES DE LIXO, EQUIPAMENTOS ELETRO-ELETRÔNICOS DE DATA, HORA E TEMPERATURA, PROTETORES DE ÁRVORES E CANTEIROS, ABRIGOS PARA PONTOS DE PARADA DE ÔNIBUS E TÁXIS, E OUTROS EQUIPAMENTOS DE UTILIDADE PÚBLICA, CONTENDO PUBLICIDADE, E DÁ OUTRAS PROVIDÊNCIAS; Autor: Prefeito Municipal - Mandato 2017/2020 Número de Protocolo: 93; Processo: 6/2019; Turno: ; Tipo: Simbólica; Sim:16; Não:0; Abstenções:0; ;Resultado: Aprovado por Unanimidade

## Imagens do Ocorrido

http://sapl.camarabento.rs.gov.br/sessao/456/ordemdia
![image](https://user-images.githubusercontent.com/13314947/54621926-5b83ab80-4a47-11e9-83eb-3177148e1119.png)

Visual Atual
![image](https://user-images.githubusercontent.com/13314947/54621970-6f2f1200-4a47-11e9-8203-400dc7c552e6.png)

Visual Esperado
![image](https://user-images.githubusercontent.com/13314947/54621991-7b1ad400-4a47-11e9-9b56-7ea142c82030.png)

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
@ulyssesBML

**Comment by DtiLegBG** [comment]
Na formatação das matérias da Ordem do dia está aparecendo antes de cada uma delas matérias do expediente. 

![image](https://user-images.githubusercontent.com/13314947/54692622-0bb6ea00-4b04-11e9-9382-03c02f4ff589.png)


Penso também que as matérias da ordem do dia devam ser colocadas na sequencia, a exemplo do que é feito nas matérias do expediente

![image](https://user-images.githubusercontent.com/13314947/54692702-2db06c80-4b04-11e9-99a2-051354090f37.png)




http://sapl.camarabento.rs.gov.br/sessao/457/resumo_ata


E o erro 500 ainda acontece na geração do PDF

**Comment by DtiLegBG** [comment]
E o turno ainda está vindo vazio.

**Comment by DtiLegBG** [comment]
Erro 500 resolvido, porem o turno ainda está vazio e questão anterior a essa também está pendente

**Comment by edwardoliveira** [comment]
@ulyssesBML poderia olhar essas pendências?

**Comment by edwardoliveira** [comment]
@ulyssesBML
