### ISSUE TITLE
Tramitação de Matérias

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#2632]
Ao tramitar uma matéria o operador recebe a seguinte mensagem em tela "Tramitação criada, mas email de acompanhamento de matéria não enviado. Há problemas na configuração do e-mail"

Verificando no BD também pude perceber que as matérias tramitadas não tinham cadastro para acompanhamento.

Não é problema de configuração de e-mail, pude testar o cadastro de acompanhamento em uma matéria e o envio e recebimento de email aconteceu normalmente

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
No próximo release estará disponível.
