### ISSUE TITLE
Tramitação de Matéria/Documento

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#2650]
## Comportamento Esperado
Ao se tramitar uma matéria/documento, mudar automaticamente o campo "Em Tramistação?" para SIM, com o próximo fix #2629 ao dar fim a tramitação retorna ao NÃO

## Comportamento Atual
O que acontece que alguns usuários estão tramitando as matérias mesmo com o campo "Em tramitação" como NAO, isso impede por exemplo de um usuário acompanhar uma matéria/documento por e-mail.

## Seu Ambiente

* Versão usada (_Release_): 3.1.148
* Nome e versão do navegador: Chrome
* Nome e versão do Sistema Operacional (desktop ou mobile): Windows 10

**Comment by edwardoliveira** [comment]
A mudança de código de tramitação de 'Sim' para 'Não' (e vice-versa) vai ser controlado pelo código abaixo:

https://github.com/interlegis/sapl/blob/8b133e11065895a40e6a10b5b9a1b33df939025f/sapl/materia/views.py#L1277-L1281

O campo indicador do status da tramitação vai ser 'F' (final) ou 'R' (retorno). Se for 'R' o campo em_tramitacao é mudando para 'SIM'. Isso não está ocorrendo?

**Comment by puera** [comment]
@edwardoliveira esse commit é recente correto? Sim está funcionando

**Comment by VictorFabreF** [comment]
O comportamento solicitado foi implementado no commit 750748afce1cf90444ee199369515a190f51df4a referente à issue #1300

**Comment by edwardoliveira** [comment]
> @edwardoliveira esse commit é recente correto? Sim está funcionando

Esse commit é de Julho de 2017...
