### ISSUE TITLE
Lista de presença ordem do dia no Resumo/Extrato

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#2657]
## Comportamento Esperado

Deveria constar todos os presentes na ordem do dia no resumo e no extrato.

## Comportamento Atual
Não está aparecendo todos os presentes na ordem do dia.

## Imagens do Ocorrido

Presença na ordem do dia:
![image](https://user-images.githubusercontent.com/1524415/55021961-6951a780-4fd8-11e9-9dc7-d23d2bcfdc30.png)

Resumo só contendo 5 parlamentares
![image](https://user-images.githubusercontent.com/1524415/55021996-766e9680-4fd8-11e9-89d2-6d7da2cf9aa7.png)

Extrato só contendo 5 parlamentares
![image](https://user-images.githubusercontent.com/1524415/55022041-85eddf80-4fd8-11e9-9d6d-e832a553d0d4.png)

## Seu Ambiente

* Versão usada (_Release_): 3.1.149
* Nome e versão do navegador: Chrome 10
* Nome e versão do Sistema Operacional (desktop ou mobile): Windows 10

**Comment by edwardoliveira** [comment]
Poderia anexar o dump de tua base de dados?

**Comment by puera** [comment]
@edwardoliveira  
[sapl.zip](https://github.com/interlegis/sapl/files/3009904/sapl.zip)

**Comment by edwardoliveira** [comment]
A lista de presentes na ordem do dia está mostrando 8 e o resumo também (5ª Sessão Ordinária da 3ª Sessão Legislativa da 6ª Legislatura)

![image](https://user-images.githubusercontent.com/9326037/55027412-0239f000-4fe4-11e9-8361-d0a60ecd3126.png)


![image](https://user-images.githubusercontent.com/9326037/55027401-fa7a4b80-4fe3-11e9-8700-49f8dd57e926.png)

**Comment by puera** [comment]
@edwardoliveira 

que estranho .... de uma olhada aqui:

https://sapl.armacaodosbuzios.rj.leg.br:44380/sessao/8/resumo

nesse caso está aparecendo 7 dos 8

**Comment by edwardoliveira** [comment]
Inacessível: 
![image](https://user-images.githubusercontent.com/9326037/55027847-04e91500-4fe5-11e9-8172-5bd3ed10ec8b.png)

**Comment by puera** [comment]
Acabei de testar pela internet e no 4G abriu normal ...

**Comment by puera** [comment]
![image](https://user-images.githubusercontent.com/1524415/55028047-880a6b00-4fe5-11e9-8343-4e8caa31b769.png)

![image](https://user-images.githubusercontent.com/1524415/55028072-95275a00-4fe5-11e9-8b0e-1c40594ba68a.png)

**Comment by puera** [comment]
@edwardoliveira  cabei de ver ... vc ta olhando a presença do expediente

**Comment by edwardoliveira** [comment]
Um instante.

**Comment by edwardoliveira** [comment]
Identifiquei onde se encontra o erro, mas tenho que ver com a pessoa que programou essa parte o que ela queria com essa lógica. Amanhã vejo isso com ele.
