### ISSUE TITLE
Sinal sonoro de cronômetros sem repetição

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2658]
## Comportamento Esperado
Deve sinalizar a 30 segundos do final e ao final da cronometragem.

## Comportamento Atual
Não está sinalizando ao final da cronometragem de Aparte, Ordem e Discurso.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/sessao/2754/painel

## Contexto
Cronometragem de manifestações nas sessões plenárias.

## Seu Ambiente
Versão usada (Release): 3.1.149
Nome e versão do navegador: Versão 73.0.3683.75 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by arthurcmm** [comment]
A campainha dos 30s poderia ser opcional? Visto que algumas câmaras fazem uso do sinal sonoro de alerta de 30s para fim do discurso, e outras não.

**Comment by andreagudo** [comment]
Pode ser opcional.

Em qui, 11 de abr de 2019 2:02 PM, arthurcmm <notifications@github.com>
escreveu:

**Comment by andreagudo** [comment]
Na sessão de ontem, 16/04/2019, nenhum sinal sonoro automático funcionou.

**Comment by andreagudo** [comment]
Sessão de 22/04/2019, o sinal dos 30s funcionou. Por duas vezes sinal final não funcionou. Bem intermitente.

**Comment by edwardoliveira** [comment]
Sim, estamos cientes. Ainda não temos solução para este problema porque depende de alguns fatores além de nosso alcance como a conexão de rede na hora. Fosse o SAPL executado na rede local, por exemplo, muitos desses problemas não apareceriam. Vamos estudar uma forma de melhorar a confiabilidade do sinal.

**Comment by andreagudo** [comment]
Nas últimas sessões tal problema não voltou a ocorrer. A issue poderia ser fechada?
