### ISSUE TITLE
Eliminar duplicação da classe HorizontalRadioRenderer

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#266]
atualmente encontrada em
parlamentares/forms.py
norma/forms.py
protocoloadm/forms.py

e também vou utilizá-la em compilacao

**Comment by LeandroRoberto** [comment]
ao HorizontalRadioRenderer deve haver um modo de dizer ao WebDesigner(via classe) que a renderização é horizontal, não? Do modo que está, não será possível o designer ao menos poder optar por horizontal e vertical por ser reenderizado o padrão do crispy e bootstrap sem uma classe que diferencie... caso seja isso mesmo, não há sentido em exististir a palavra Horizontal no início da classe...

**Comment by edwardoliveira** [comment]
Na verdade, ela nem está funcionando nas telas onde se encontra :cry: Mas se vc consegue fazer funcionar me aponte o template/view/form que eu faço igual. Sim, vamos eliminar a duplicação ASAP!

**Comment by LeandroRoberto** [comment]
questão levantada sobre webdesigner, resolvido utilizando a classe InlineRadios da api de crispy forms. A classe HorizontalRadioRenderer para não é necessária... ao seguir a execução da construção do formulário, vi que método render não é executado e, ao retirar o atributo renderer do widget RadioSelect o formulário é construído da mesma forma!
