### ISSUE TITLE
Extrato da Sessão - Impressão PDF

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#2663]
### **No extrato da sessão não está aparecendo o turno, como exibido quando a matéria está na ordem do dia:**
![image](https://user-images.githubusercontent.com/13314947/55096764-4509cf80-5099-11e9-9366-5869d4277b5d.png)

![image](https://user-images.githubusercontent.com/13314947/55096832-5f43ad80-5099-11e9-975e-c9cde755e2df.png)

### **Para as matérias da ordem do dia seria interessante manter o padrão visual das materias do expediente**
![image](https://user-images.githubusercontent.com/13314947/55096956-a336b280-5099-11e9-821c-b3ba9e03a84c.png)

![image](https://user-images.githubusercontent.com/13314947/55096968-aaf65700-5099-11e9-9c86-d5d59ebc921e.png)

### **No pdf gerado não está aparecendo as ocorrências da sessão conforme o extrato**
![image](https://user-images.githubusercontent.com/13314947/55097084-e729b780-5099-11e9-8f09-a25b4fc44037.png)

![image](https://user-images.githubusercontent.com/13314947/55097174-16402900-509a-11e9-9a36-b9f4e5aac865.png)

### Extrato Eletrônico da 109ª Sessão Ordinária da 3ª Sessão Legislativa da 17ª Legislatura** 

![image](https://user-images.githubusercontent.com/13314947/55097395-80f16480-509a-11e9-8e94-e771a8bab2b7.png)

### **Também no cabeçalho seria importante que fosse mantido o padrão do sistema ao invés de "casa legislativa...."**
![image](https://user-images.githubusercontent.com/13314947/55097448-a1b9ba00-509a-11e9-90e1-d1e3ff736a41.png)

![image](https://user-images.githubusercontent.com/13314947/55097504-b9913e00-509a-11e9-9406-08cc8d2c074f.png)

## Comportamento Atual

http://sapl.camarabento.rs.gov.br/sessao/457/resumo_ata

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by DtiLegBG** [comment]
No PDF também não consta o bloco de assinaturas

**Comment by edwardoliveira** [comment]
> Para as matérias da ordem do dia seria interessante manter o padrão visual das materias do expediente
Não.

**Comment by edwardoliveira** [comment]
> No extrato da sessão não está aparecendo o turno, como exibido quando a matéria está na ordem do dia:

Quando existe um turno aparece assim: 
![image](https://user-images.githubusercontent.com/9326037/55099998-91580e00-509f-11e9-8448-04f355d065c8.png)

Quando não existe turno aparece assim:
![image](https://user-images.githubusercontent.com/9326037/55100197-0c212900-50a0-11e9-9550-a1f4240aff95.png)

Podemos colocar um `if` para não aparecer a palavra `Turno` se não tiver nada.

**Comment by edwardoliveira** [comment]
> No cabeçalho do pdf gerado seria importante que fosse exibido as informações da sessão ao invés de "Extrato da Reunião"
> Extrato Eletrônico da 109ª Sessão Ordinária da 3ª Sessão Legislativa da 17ª Legislatura**

![image](https://user-images.githubusercontent.com/9326037/55101836-cc5c4080-50a3-11e9-8cae-f40d722390f7.png)

**Comment by edwardoliveira** [comment]
> No pdf gerado não está aparecendo as ocorrências da sessão conforme o extrato

![image](https://user-images.githubusercontent.com/9326037/55102958-4ee5ff80-50a6-11e9-814d-4b208b182782.png)

Feito.

**Comment by edwardoliveira** [comment]
Também no cabeçalho seria importante que fosse mantido o padrão do sistema ao invés de "casa legislativa...."

![image](https://user-images.githubusercontent.com/9326037/55103599-8c975800-50a7-11e9-9361-11fd55e9cf15.png)

Feito.

**Comment by DtiLegBG** [comment]
O turno ainda não está aparecendo:
http://sapl.camarabento.rs.gov.br/sessao/458/ordemdia

![image](https://user-images.githubusercontent.com/13314947/55104090-7b028000-50a8-11e9-944c-fccc5109771d.png)


No resumo
http://sapl.camarabento.rs.gov.br/sessao/458/resumo_ata

![image](https://user-images.githubusercontent.com/13314947/55104146-979eb800-50a8-11e9-82f4-ef6e878480be.png)
