### ISSUE TITLE
Tramitação automática da matéria anexada não funciona corretamente se a matéria anexadora for tramitada em lote

### ISSUE THREAD

**Issue by EdersonCR** [interlegis/sapl#2665]
## Comportamento Esperado
Ao tramitar em lote uma matéria que possui uma matéria anexada a ela, a matéria anexada registra automaticamente a tramitação da matéria anexadora, da mesma forma que ocorre ao realizar a tramitação normal de uma matéria que possui uma matéria anexada.

## Comportamento Atual
Ao tramitar em lote um matéria que possui uma matéria anexada a ela, a matéria anexada não registra automaticamente a tramitação da matéria anexadora.

## Possível Solução
Implementar o mesmo mecanismo de tramitação automática das matérias anexadas para a tramitação em lote.

## Passos para Reproduzir (para bugs)
1. Anexe uma matéria a outra matéria já existente.
2. Realize a tramitação em lote da matéria anexadora.
3. Verifique se a matéria anexada realizou a mesma tramitação da matéria anexadora.

## Contexto
Em casos que há varias matérias e realizarão a mesma tramitação, utiliza-se a tramitação em lote para poupar tempo do usuário que realizará a tramitação das matérias.
Em caso de uma matéria com uma matérias anexada a ela, o sistema realiza automaticamente na matéria anexada a mesma tramitação da matéria anexadora, para poupar tempo do usuário que realizará a tramitação das matéria.
Portanto, para poupar tempo do usuário que realizará a tramitação das matéria, ao se tramitar em lote matérias que possuem matérias anexadas a elas, o sistema deveria realizar automaticamente na matéria anexada a mesma tramitação da respectiva matéria anexadora.

## Seu Ambiente
* Versão usada (_Release_): 3.1.149
* Nome e versão do navegador: Google Chrome Versão 73.0.3683.86 64 bits
* Nome e versão do Sistema Operacional (desktop ou mobile): Windowns 10 Home Silgle Language Versão 1803

**Comment by edwardoliveira** [comment]
@LeandroJatai @DtiLegBG @andreagudo O que vcs acham desta proposta?

**Comment by LeandroJatai** [comment]
Correto... tramitação em lote deve ter o mesmo comportamento que a tramitação individual... porém, deve-se levar as mesmas considerações ainda nao implementadas e citadas aqui: #2415
