### ISSUE TITLE
Finalizar a tramitação de uma matéria com varias matérias anexadas a ela não finaliza automaticamente a tramitação das matérias anexadas

### ISSUE THREAD

**Issue by EdersonCR** [interlegis/sapl#2666]
## Comportamento Esperado
Ao alterar o campo "Em tramitação?" de uma matéria para "Não" (seja manualmente ou através realizando uma tramitação de FIM), se houver mais de uma matéria anexada a ela, todas as matérias anexadas deveriam alterar seu campo "Em tramitação?" para "Não".

## Comportamento Atual
Ao alterar o campo "Em tramitação?" de uma matéria para "Não" (seja manualmente ou através realizando uma tramitação de FIM), se houver mais de uma matéria anexada a ela, apenas a primeira matéria anexada altera seu campo "Em tramitação?" para "Não", as demais matérias anexadas não alteram seu campo "Em tramitação?", permanecendo "Sim".

## Possível Solução
Implementar o mecanismo automático que altera o campo "Em tramitação?" das matérias anexadas, quando alterado esse capo da matéria anexadora, de forma que essa alteração ocorra em todas as matérias anexadas, quando houver mais de uma matéria anexada a mesma matéria anexadora.

## Passos para Reproduzir (para bugs)
1. Anexe mais de uma matéria a uma outra matéria que esteja em tramitação..
3. Realize a tramitação dessa matéria anexadora, de forma que as duas matérias anexadas entrem em tramitação  (campo "Em tramitação?" igual a "Sim").
4. Realize a tramitação dessa matéria anexadora, de forma que ela saía de tramitação (campo "Em tramitação?" igual a "Não").
5. Verifique que o campo "Em tramitação?" da primeira matéria anexada alterou para "Não", mas o da segunda matéria anexada permanece "Não".

## Contexto
Quando a um Projeto de Lei em que foram anexadas várias emendas, ao finalizar a tramitação desse projeto, posteriormente é necessário finalizar manualmente a tramitação das emendas, o que poderia ser realizado automaticamente, poupando tempo do usuário do sistema.

## Seu Ambiente

* Versão usada (_Release_): 3.1.149
* Nome e versão do navegador: Google Chrome Versão 73.0.3683.86 64 bits
* Nome e versão do Sistema Operacional (desktop ou mobile): Windowns 10 Home Silgle Language Versão 1803

**Comment by edwardoliveira** [comment]
@DtiLegBG @LeandroJatai O que pensa sobre isso?
