### ISSUE TITLE
Extrato Sessão Plenária - Ajustes

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#2682]
Alguns ajustes na exibição do extrato da Sessão Plenária

## Comportamento Esperado

![image](https://user-images.githubusercontent.com/13314947/55486778-48560b80-5603-11e9-8f94-51701f1e9fa3.png)

![image](https://user-images.githubusercontent.com/13314947/55486817-586deb00-5603-11e9-8739-29be42c06d30.png)

## Comportamento Atual

Em identificação básica, mesa diretora, lista de presença e oradores está ficando um ";" no final.

A exibição dos oradores do expediente está diferente do restante.

A sequência das informações mostradas nas matérias do expediente e nas matérias da ordem do dia está diferente
matérias do expediente:
Autor
Protocolo
Ementa

Matérias da Ordem do dia:
Ementa
Autor
Protocolo
Processo

Nas matérias do expediente, separar as informações com ","

## Possível Solução

Vou enviar PR

## Passos para Reproduzir (para bugs)

http://sapl.camarabento.rs.gov.br/sessao/459/resumo_ata

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by puera** [comment]
@edwardoliveira está ocorrendo Erro 500 na geração do pdf do extrato sessão plenária no release 151

**Comment by edwardoliveira** [comment]
Corrigido. Verifica se não tem mais nenhum bug desses. Se tiver, cria uma nova issue.
