### ISSUE TITLE
Ementa incompleta, embora esteja registrada corretamente

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2694]
## Comportamento Esperado
O campo Ementa deve mostrar todo seu conteúdo.

## Comportamento Atual
Tem aparecido apenas parte da ementa, embora seu conteúdo tenha sido registrado corretamente.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/norma/2594

## Contexto
Aparece parte da ementa em uma pesquisa e quando se inicia a elaboração da compilação da norma. Quando se tenta editar a ementa, seu conteúdo acaba aparecendo totalmente, embora com um pequeno retardo (o gif anexo mostra isso).

## Imagens do Ocorrido
![Captura de tela de 2019-04-05 13-57-13](https://user-images.githubusercontent.com/19169882/55644031-1089c800-57ab-11e9-8c0e-a4dd1532893d.png)
![Captura de tela de 2019-04-05 13-57-21](https://user-images.githubusercontent.com/19169882/55644043-17b0d600-57ab-11e9-8d4c-b944ccdca9a7.png)
![Captura de tela de 2019-04-05 13-57-31](https://user-images.githubusercontent.com/19169882/55644053-1d0e2080-57ab-11e9-8a82-0a5b7f72ca55.png)
![ementa_incompleta](https://user-images.githubusercontent.com/19169882/55644099-3adb8580-57ab-11e9-8417-9749622cdea4.gif)

## Seu Ambiente
Versão usada (Release): 3.1.152
Nome e versão do navegador: Versão 73.0.3683.75 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits
!

**Comment by edwardoliveira** [comment]
@LeandroJatai Isso não seria um bug do VueJS?

**Comment by edwardoliveira** [comment]
@cesaraugc Esse bug tem a ver com a issue https://github.com/interlegis/sapl/issues/2558 . Neste commit é feita uma chamada a `recuperar_materia();` **fora** do `onchange` dos campos tipo, ano e número de matéria, na linha 33 do arquivo `normajuridica_form.html`. É necessário?

**Comment by edwardoliveira** [comment]
@cesaraugc Eu retirei a linha em questão no commit 8d4a7f8, mas veja se isso não quebrou a parte de recuperação de matéria em criar e editar norma, por favor. :smile:
