### ISSUE TITLE
Pesquisa Textual - Normas Jurídicas

### ISSUE THREAD

**Issue by lizianem** [interlegis/sapl#2695]
## Comportamento Esperado
Não localizamos mais a Pesquisa Textual na versão, 3.1.150. Como podemos ativá-la????

**Comment by lizianem** [comment]
Temos uma dúvida quanto a versão 3.1.150. **A PESQUISA TEXTUAL, no módulo Normas Jurídicas, foi desabilitada?**
**Se foi desabilitada, como podemos ativá-la?** 
È fundamental essa forma de pesquisa para nós.

**Comment by VictorFabreF** [comment]
Bom dia,
Qual sua casa legislativa? Você está hospedada no Interlegis ou tem hospedagem local?

**Comment by lizianem** [comment]
VictorFabre, Bom dia. O SAPL está em hospedagem local, na PROCEMPA (PORTO ALEGRE - RS). Eis o link: https://legislacaosirel.portoalegre.rs.gov.br/
Usamos apenas o módulo NORMAS JURÍDICAS.

**Comment by edwardoliveira** [comment]
Duplicata de #2656

**Comment by edwardoliveira** [comment]
@lizianem Verifique se com esses passos nesse link https://github.com/interlegis/sapl/blob/0774d30ec2b14ca390f13863997639476cdd9592/docs/solr.rst vc consegue habilitar a busca textual, por favor. /cc @VictorFabreF

**Comment by puera** [comment]
@edwardoliveira fui pela documentação que você acabou de commitar e estou tendo problema na hora de indexar os arquivos no SOLR, estou obtendo o erro ao executar o comando na raiz  SAPL python3 solr_api.py -c sapl -u http://localhost:8983

 Traceback (most recent call last):
  File "solr_api.py", line 141, in <module>
    if not client.exists_collection(collection):
  File "solr_api.py", line 41, in exists_collection
    collections = self.list_collections()
  File "solr_api.py", line 38, in list_collections
    return dic['collections']
KeyError: 'collections'

O servidor está iniciado normalmente:

![image](https://user-images.githubusercontent.com/1524415/55747006-90b16700-5a11-11e9-93c2-76269a324966.png)

meu .env

![SOLR](https://user-images.githubusercontent.com/1524415/55747097-de2dd400-5a11-11e9-8c5d-f5c56795c6a9.png)

**Comment by edwardoliveira** [comment]
@puera Você não inicializou o Solr no modo `SolrCloud` (dá pra ver pelo screenshot do admin panel). Conforme o tutorial, vc deve entrar com `$SOLR_HOME/bin/solr start -c` (o parâmetro de `-c` é para o modo cloud). Pare o servidor e reinicie da forma correta.

**Comment by puera** [comment]
Vlw @edwardoliveira era isso mesmo! Estranho que tinha posto parâmetro ... provavelmente devo ter iniciado sem querer do modo normal ...

**Comment by edwardoliveira** [comment]
Um lembrete: o Solr **não deve** ser exposto na Internet. Ele deve estar atrás de firewalls/proxies/NAT assim como o Postgres. Só o servidor do SAPL deve ter acesso a ele.

**Comment by puera** [comment]
@edwardoliveira blz! Uma dúvida quanto a indexação do Solr, pelo que entendi de tempos e tempos tenho que rodar o comando para poder indexar novos arquivos certo? o comando python3 solr_api.py -c sapl -u http://localhost:8983 indexa os novos arquivos? ou teria que reindexar do zero com rebuild_index? pergunto isso pois estou querendo criar um script para crontab para indexar esses novos arquivos

**Comment by edwardoliveira** [comment]
> Uma dúvida quanto a indexação do Solr, pelo que entendi de tempos e tempos tenho que rodar o comando para poder indexar novos arquivos certo?

Errado. Cada novo documento inserido, atualizado, ou removido do SAPL dispara uma nova indexação somente daquele documento no Solr automaticamente. 

> o comando python3 solr_api.py -c sapl -u http://localhost:8983 indexa os novos arquivos? 

Não. Este comando é para construir a coleção do Solr a primeira vez e, por acaso, faz a indexação inicial. Não deve ser usado se a coleção já foi criada.

>  ou teria que reindexar do zero com rebuild_index? 

Pode acontecer do Postgres e o Solr se dessincronizarem (ex: o Solr ficou fora do ar por um dia e foram inseridos registros no SAPL). Ou por algum motivo se deseja refazer o índice do Solr. Neste caso deve-se refazer a indexação no Solr com o comando : **python3 manage.py rebuild_index** (direto na linha de comando, a partir da pasta raiz do SAPL). Esta semana vou atualizar a documentação com os comandos de manutenção dos dados do Solr via SAPL.

> pergunto isso pois estou querendo criar um script para crontab para indexar esses novos arquivos

Desnecessário.
