### ISSUE TITLE
Pdf do resumo da sessão duplicado

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2700]
## Comportamento Esperado
O pdf deve mostrar cada parte da sesão apenas uma vez.

## Comportamento Atual
Ao final da última parte, todas as anteriores são repetidas.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/relatorios/2756/sessao-plenaria

## Contexto
Geração do pdf do resumo da sessão.

## Seu Ambiente
Versão usada (Release): 3.1.152
Nome e versão do navegador: Versão 73.0.3683.75 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
Este erro é na parte de ordenação de seções do relatório. 


@rjoao isso tem a ver com o commit https://github.com/interlegis/sapl/commit/a8a41ea78cabfe7c1d87789bf0b6fd1dd6ab3696 (o 14o. parâmetro estava como 'Conteúdo Multimídia' ao invés de 'Oradores da Ordem do Dia' (tenho o dump para vc testar). Mudando para 'Oradores...'  e salvando na instância do SAPL em questão solucionou o problema. Vc poderia verificar o porquê desse erro gerar uma duplicação dos dados da sessão no relatório em PDF?
