### ISSUE TITLE
Dúvidas para acessar API no endpoint "api/materia/materialegislativa"

### ISSUE THREAD

**Issue by gacra** [interlegis/sapl#2728]
Bom dia estou acessando a API do SAPL do estado do Piauí (https://sapl.al.pi.leg.br/ - Release: 3.1.153), e estou com algumas dúvidas sobre o acesso ao endpoint "/api/materia/materialegislativa/​", que lista as proposições.​

A primeira dúvida é sobre a ordem padrão em que as proposições aparecem. Analisando os dados tive a impressão que a ordenação é realizada usando o campo "data_ultima_atualizacao​" (da data mais antiga a mais atual), mas gostaria de confirmar essa informação.

A segunda dúvida é: dado que a ordenação é realizada usado tal campo "data_ultima_atualizacao​", é possível ordenar na ordem inversa ao padrão (na mais recentemente atualizada para mais antiga)?​

Por fim, gostaria de saber se há alguma documentação da API elucidando quais são os parâmetros e retornos que cada endpoind possui. 

Agradeço desde já.

**Comment by LeandroJatai** [comment]
Olá...
1ª dúvida) Não só /api/materia/materialegislativa mas qualquer endpoint, é ordenado pelas regras do Django Framework. Portanto, caso haja customização na classe Meta do model em questão, a ordem do endpoint será o que está no atributo ordering da classe Meta [(vide django doc).](https://docs.djangoproject.com/pt-br/1.11/ref/models/options/#django.db.models.Options.ordering) No caso de MateriaLegislativa Meta.ordering não foi definido, portanto, não há ordem definida... Então como ordenar? Vamos falar já de filtro, paginação e ordering... Tudo é passado via parâmetros...

- A paginação foi customizada mas e está contida no dicionário pagination, as páginas ainda são fixas com 10 itens por páginas, mas o modo de chamar as páginas é o padrão do django e do DRF, ou seja, através do parametro _page_.
- Filtro segue as regras do django-filter. 
- Para ordenação a API do SAPL implementa para todos os endpoints uma solução via parâmetro "o" onde o valor de "o" segue as regras possíveis para order_by [(vide django doc)](https://docs.djangoproject.com/pt-br/1.11/ref/models/querysets/#order-by), exemplo:
  - `/api/materia/materialegislativa?o=tipo` : ordena pelo id do tipo em ordem crescente
  - `/api/materia/materialegislativa?o=-tipo__descricao` : ordena pela descrição do tipo em ordem decrescente - mesmo que no resultado não tenha a descrição do tipo
  - `/api/materia/materialegislativa?o=-tipo__descricao,ano` : ordena pela descrição do tipo em ordem decrescente e em ordem ascendente pelo campo ano.

2ª dúvida) a resposta a 1ª dúvida já responde esta.

3ª dúvida) Acesse esse link de seu sapl: `/api/docs/swagger/` (os parametros listados no doc de cada endpoint está correto, no entanto o doc do response de cada endpoint está com erro). Nele está todos os endpoints disponíveis à api automática além de alguns actions já criados...

PS: a api automática cria endpoint para todo Model do Sapl. Segue as regras do DRF e define o padrão do DRF para views, filters e serializers. Além disso define um decorator para customização que pode ser percebido funcionamento com demais docs em sapl/api/views.py. Além do já dito no referido arquivo e neste comentário, carece de detalhamento na documentação.

**Comment by gacra** [comment]
Cara, muitíssimo obrigado pela resposta, não poderia ser mais completa. :smiley:
