### ISSUE TITLE
MIGRAÇÃO de dados para o SAPL

### ISSUE THREAD

**Issue by lizianem** [interlegis/sapl#2729]
Migração de dados de um sistema proprietário para o SAPL

## Comportamento Esperado
Considerando a intenção de migrar dados de um sistema proprietário para o SAPL, perguntamos:
	Existe algum webservice ou rotina para carga/migração de dados para o sistema SAPL?
	Qual o formato dos dados a serem disponibilizados para esta carga/migração?

**Comment by lizianem** [comment]
Aguardando auxílio

**Comment by edwardoliveira** [comment]
> Existe algum webservice ou rotina para carga/migração de dados para o sistema SAPL?

Não. Vcs terão que fazer as rotinas em SQL para a carga dos dados na tabela do banco PostgreSQL. O usuário do banco é sapl, senha sapl, caso não tenha sido alterada.

> Qual o formato dos dados a serem disponibilizados para esta carga/migração?

Vcs tanto podem gerar arquivos no formato CSV quanto gerar scripts SQL com os inserts.

Eu aconselho usar a ferramenta pgAdmin para conectar ao BD e visualizar as tabelas. Por exemplo, aquelas referentes a normas jurídicas estão listadas na imagem em anexo.

![image](https://user-images.githubusercontent.com/9326037/56734846-54347980-673a-11e9-83d1-a4602cef1c9d.png)
