### ISSUE TITLE
Protocolo - Protocolar Matéria

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#2737]
Ao protocolar uma matéria em protocolo, é apresentada a seguinte mensagem.

**É preciso definir a sequencia de numeração na tabelas auxiliares!** 

## Comportamento Atual

A mensagem é exibida mesmo a sequencia estando definida nas tabelas auxiliares. Com isso o protocolo não é criado.

## Passos para Reproduzir (para bugs)

Protocolo
Protocolo Geral
Protocolar Matéria

## Imagens do Ocorrido

![image](https://user-images.githubusercontent.com/13314947/56497560-6f9e4b00-64d4-11e9-9801-90726bf5f5af.png)

![image](https://user-images.githubusercontent.com/13314947/56497580-82188480-64d4-11e9-93a4-17edb8ab5ecf.png)

## Seu Ambiente

* Versão usada (_Release_): 3.1.153
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Corrigido por a6e63842b92927cef06adf79bd8b7516896a315a

**Comment by DtiLegBG** [comment]
Está com o seguinte erro:


Environment:


Request Method: POST
Request URL: http://sapl.camarabento.rs.gov.br/protocoloadm/protocolar-mat

Django Version: 1.11.20
Python Version: 3.5.2
Installed Applications:
('django_admin_bootstrapped',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_extensions',
 'crispy_forms',
 'floppyforms',
 'drf_yasg',
 'rest_framework',
 'django_filters',
 'easy_thumbnails',
 'image_cropping',
 'reversion',
 'reversion_compare',
 'haystack',
 'speedinfo',
 'webpack_loader',
 'sapl.audiencia',
 'sapl.base',
 'sapl.crud',
 'sapl.parlamentares',
 'sapl.comissoes',
 'sapl.materia',
 'sapl.norma',
 'sapl.sessao',
 'sapl.lexml',
 'sapl.painel',
 'sapl.protocoloadm',
 'sapl.redireciona_urls',
 'sapl.compilacao',
 'sapl.api',
 'sapl.rules',
 'debug_toolbar')
Installed Middleware:
['reversion.middleware.RevisionMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'speedinfo.middleware.ProfilerMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']



Traceback:

File "/var/interlegis/.virtualenvs/sapl/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/var/interlegis/.virtualenvs/sapl/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/var/interlegis/.virtualenvs/sapl/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/interlegis/.virtualenvs/sapl/lib/python3.5/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/var/interlegis/.virtualenvs/sapl/lib/python3.5/site-packages/django/contrib/auth/mixins.py" in dispatch
  92.         return super(PermissionRequiredMixin, self).dispatch(request, *args, **kwargs)

File "/var/interlegis/.virtualenvs/sapl/lib/python3.5/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/var/interlegis/.virtualenvs/sapl/lib/python3.5/site-packages/django/views/generic/edit.py" in post
  217.         return super(BaseCreateView, self).post(request, *args, **kwargs)



File "/var/interlegis/.virtualenvs/sapl/lib/python3.5/site-packages/django/views/generic/edit.py" in post
  183.             return self.form_valid(form)

File "/var/interlegis/sapl/sapl/protocoloadm/views.py" in form_valid
  729.         numeracao = sapl.base.models.AppConfig.objects.last(

Exception Type: AttributeError at /protocoloadm/protocolar-mat
Exception Value: 'AppConfig' object has no attribute 'sequencia_numeracao_materia'

**Comment by edwardoliveira** [comment]
Vc rodou o `manage.py migrate`?

**Comment by DtiLegBG** [comment]
sim

**Comment by edwardoliveira** [comment]
Me passa tua base de dados.

**Comment by edwardoliveira** [comment]
Se estiver usando a partir do branch 3.1.x execute o comando `git reset --hard origin/3.1.x`

**Comment by DtiLegBG** [comment]
> 
> 
> Se estiver usando a partir do branch 3.1.x execute o comando `git reset --hard origin/3.1.x`

rodando o comando, mesmo erro
'AppConfig' object has no attribute 'sequencia_numeracao_materia'

**Comment by edwardoliveira** [comment]
Qual a saída de `git log -p`. Posta um screenshot das primeiras duas

**Comment by DtiLegBG** [comment]
rodei git fetch, testei novamente e erro persiste

![image](https://user-images.githubusercontent.com/13314947/56502751-c7937c80-64e9-11e9-800a-c0623d1d11e7.png)

![image](https://user-images.githubusercontent.com/13314947/56502787-e5f97800-64e9-11e9-88d5-20b7fbac0b7b.png)

**Comment by edwardoliveira** [comment]
Me passa o acesso remoto a essa máquina via DM no Telegram.
