### ISSUE TITLE
Extrato da Sessão - Assinaturas

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#2739]
No PDF do extrato da sessão, as assinaturas estão ficando em uma folha separada.

## Comportamento Esperado

Mesmo que algumas assinaturas ficassem sozinhas na ultima folha, o bloco de assinaturas deveria iniciar imediatamente abaixo do texto

## Passos para Reproduzir (para bugs)

http://sapl.camarabento.rs.gov.br/relatorios/461/resumo_ata

## Imagens do Ocorrido

![image](https://user-images.githubusercontent.com/13314947/56589230-34c31280-65bb-11e9-964a-672dbb8b3e30.png)

## Seu Ambiente

* Versão usada (_Release_):3.1.153
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Será? Por favor, discuta isso com a galera da comunidade (Telegram, WhatsApp, GITEC) antes pra ver se todos, ou a maioria, concordam. Eu não quero receber tickets depois de gente dizendo pra deixar sem quebras.

/cc @LeandroJatai @andreagudo
