### ISSUE TITLE
Erro na inclusão de tramitação de matérias

### ISSUE THREAD

**Issue by LeandroJatai** [interlegis/sapl#2741]
A inclusão de matérias está acusando de erro na seleção da unidade local. Unidade esta que já vem preenchida de forma errada pelo sistema

## Comportamento Esperado
Deve ser identificado corretamente a unidade local como sendo a última adicionada na matéria

## Comportamento Atual
![image](https://user-images.githubusercontent.com/9630623/56604746-179d3c80-65d9-11e9-8d33-2dfc0eb58324.png)
Na imagem acima veja que existem duas tramitações... elas são e devem ter a mesma data e respectivamente id 32088 e 32089, portanto deveria vir como unidade local para uma futura inserção a unidade de destino da tramitação id=32089, ou seja, "Departamento Legislativo - DL"

no entanto, a tela abaixo é apresentada ao clicar no botão "Adicionar Tramitação"
![image](https://user-images.githubusercontent.com/9630623/56605094-baee5180-65d9-11e9-9bdf-76bd52fa20f0.png)

como o usuário é impelido a confiar na informação, preenchendo sem observar o detalhe, se depara com essa tela:
![image](https://user-images.githubusercontent.com/9630623/56604812-38659200-65d9-11e9-96ea-52cc234a5992.png)

**Comment by cesaraugc** [comment]
A unidade local neste caso deve ser mesmo PROTOCOLO. A tramitação mais recente aparece mais acima na lista de tramitações. O que ocorreu neste caso provavelmente foi uma inconsistência de dados. Favor me corrija se estiver errado.

**Comment by LeandroJatai** [comment]
Obrigado @cesaraugc ... meu importador do 2.5 para 3.1 estava importando em ordem reversa de id, o que fazia o campo timestamp do id mais alto ficar anterior ao id mais baixo, gerando a inconsistência.
