### ISSUE TITLE
Criar testes para telas

### ISSUE THREAD

**Issue by eduardoedson** [interlegis/sapl#275]

**Comment by eduardoedson** [comment]
https://github.com/interlegis/sapl/commit/804bd783dbebe7bc561bfd7181f9ceffd4cb0cad
https://github.com/interlegis/sapl/commit/2d7df01fecef97ea9993022d957b362904bec55d

**Comment by eduardoedson** [comment]
https://github.com/interlegis/sapl/commit/ac4e0e8ebca12e3b6ee385cbf69454c7cc3b1bc1
https://github.com/interlegis/sapl/commit/bf8f5eccd1bbd222f81d2980885fc9718ee21bde

**Comment by edwardoliveira** [comment]
+1. Ainda não são *todos* os testes que precisamos, mas é um bom avanço. :+1:
