### ISSUE TITLE
Numeração automático ao cadastrar matéria legislativa

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2774]
## Comportamento Esperado
O sistema deve oferecer o número seguinte para o tipo de matéria e ano selecionado

## Comportamento Atual
Não está sendo oferecido o próximo número.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/materia/create

## Contexto
Cadastro de matéria legislativa.

## Imagens do Ocorrido
![Captura de tela de 2019-05-13 16-21-46](https://user-images.githubusercontent.com/19169882/57648221-4b95cd00-759b-11e9-9453-e3ac409c1f75.png)

## Seu Ambiente
Versão usada (Release): 3.1.154
Nome e versão do navegador: Versão 73.0.3683.86 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by cesaraugc** [comment]
Já resolvido na release 3.1.155.
