### ISSUE TITLE
Relatório de Normas por Vigência

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2781]
## Comportamento Esperado
Pelo critério "não vigente", deveria excluir as vigentes.

## Comportamento Atual
Inclui no relatório norma vigente, excluindo as revogadas.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/sistema/relatorios/relatorio-por-vigencia?ano=2008&vigencia=False

## Contexto
Consulta a relatório de normas vigentes.

## Imagens do Ocorrido
![Captura de tela de 2019-05-15 16-33-54](https://user-images.githubusercontent.com/19169882/57804209-82e9b280-7730-11e9-86e0-4d7b94d6bc64.png)

## Seu Ambiente
Versão usada (Release): 3.1.155
Nome e versão do navegador: Versão 73.0.3683.86 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
Poderia ser mais claro?
