### ISSUE TITLE
Erro ao listar tramitações de matéria

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2796]
## Comportamento Esperado
Estando-se nos detalhes de uma tramitação de matéria legislativa, todas as tramitações devem ser listadas ao "Listar tramitações".

## Comportamento Atual
Está dando erro 404.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/materia/10960/tramitacao

## Contexto
Consulta a tramitações

## Imagens do Ocorrido
![Captura de tela de 2019-05-21 07-47-40](https://user-images.githubusercontent.com/19169882/58091573-4db1ea00-7ba0-11e9-8ede-d60d10a74f36.png)

## Seu Ambiente
Versão usada (Release): 3.1.156
Nome e versão do navegador: Versão 73.0.3683.86 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
@andreagudo Essa matéria legislativa com id 10960 não existe.

**Comment by andreagudo** [comment]
Tentemos esta: https://sapl.agudo.rs.leg.br/materia/10703

**Comment by andreagudo** [comment]
![tramitacao](https://user-images.githubusercontent.com/19169882/58116137-f3ca1800-7bd1-11e9-93a6-d1150c6c30cd.gif)

**Comment by edwardoliveira** [comment]
A URL está mal formada, mas isso só é possível detectar por esse passo-a-passo aí.

**Comment by edwardoliveira** [comment]
A correção virá na próxima versão. Obrigado @LeandroJatai
