### ISSUE TITLE
Critério secundário de ordem das normas relacionadas

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2802]
## Comportamento Esperado
As normas relacionadas a uma matéria legislativa aparecem por critério de data, crescente. Sugiro que apareçam também pelo critério secundário de número, crescente.

## Comportamento Atual
AS normas são listadas apenas pelo critério data.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/norma/pesquisar?tipo=&numero=735&ano=&data_0=&data_1=&data_publicacao_0=&data_publicacao_1=&ementa=&assuntos=&data_vigencia_0=&data_vigencia_1=&o=&indexacao=

## Contexto
Pesquisa de matéria legislativa.

## Imagens do Ocorrido
![Captura de tela de 2019-05-22 10-12-44](https://user-images.githubusercontent.com/19169882/58182645-5e3b9080-7c84-11e9-8056-d12ef02038d1.png)

## Seu Ambiente
Versão usada (Release): 3.1.156
Nome e versão do navegador: Versão 73.0.3683.86 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
@andreagudo Na próxima versão estará disponível em ordem crescente.
