### ISSUE TITLE
Tramitação de anexadas como opcional

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#2805]
Relaciona-se à issue https://github.com/interlegis/sapl/issues/2415

"Esse comportamento deveria ser opcional, por exemplo com uma seleção "registrar tramitação para as matérias anexadas". Chegamos a seguinte situação. Um Projeto de Lei, com duas emendas anexadas(no nosso caso emendas são matérias), uma emenda aprovada, outra rejeitada e o Projeto aprovado. Quando tramitado o projeto com uma tramitação cuja descrição é (Projeto Aprovado e aguardando sanção) vai registrar tramitação errada para a emenda anexada que foi rejeitada."

## Comportamento Esperado
Customizar a tramitação para matérias anexadas.

## Comportamento Atual
Ao tramitar a matéria, tramita-se também as anexadas.

## Possível Solução
Criar duas opções de configuração (default=True, tramita anexadas) para tramitação de matérias legislativas e documentos administrativos.

## Contexto
Tramitação de matérias.

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador: Chrome
* Nome e versão do Sistema Operacional (desktop ou mobile): 3.1.156
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Consertada pelo commit #9e65baf

**Comment by DtiLegBG** [comment]
Obrigado !
