### ISSUE TITLE
Ordenação do Resumo é confuso

### ISSUE THREAD

**Issue by cantuariavc** [interlegis/sapl#2806]
## Comportamento Esperado

Ver somente as opções que ainda não foram selecionadas.

## Comportamento Atual

Mostra todas as opções em todas as escolhas.

## Possível Solução

Ocultar opções selecionadas ou ordenar arrastando as opções.

## Passos para Reproduzir

1. Sistema
2. Tabelas Auxiliares
3. Módulo Sessão Plenária
4. Ordenação do Resumo

<!-- * Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by cesaraugc** [comment]
Mergeado na master.
