### ISSUE TITLE
Valor inválido na Ordenação do Resumo

### ISSUE THREAD

**Issue by cantuariavc** [interlegis/sapl#2807]
## Comportamento Esperado

Todas as opção de Ordenação do Resumo deveriam ser válidas e únicas.

## Comportamento Atual

Se Ordenação do Resumo não for previamente configurado, dá erro por valor inválido.

## Possível Solução

Verificar na migração se foi previamente configurado. Se não tiver sido, remover e criar o objeto ResumoOrdenacao novamente.

<!-- * Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by cesaraugc** [comment]
#2800

**Comment by edwardoliveira** [comment]
@cantuariavc Verificar o PR do @cesaraugc que acabei de "mergear" ao 3.1.x
