### ISSUE TITLE
Parlamentares não listados para Adicionar Oradores ao Expediente

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2812]
## Comportamento Esperado
Deve aparecer a lista de parlamentares ativos para inserir entre os Oradores do Expediente.

## Comportamento Atual
Os parlamentares não são listados. Precisamos de solução para elaborar a sessão de hoje.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/sessao/2767/oradorexpediente/create

## Contexto
Adicionamento de Oradores do Expediente da sessão.

## Imagens do Ocorrido
![Captura de tela de 2019-05-27 13-35-32](https://user-images.githubusercontent.com/19169882/58431626-06869600-8085-11e9-94b4-db7e7575fb72.png)

## Seu Ambiente
Versão usada (Release): 3.1.156
Nome e versão do navegador: Versão 73.0.3683.86 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
Você tem que colocar a presença **antes** de adicionar oradores. As presenças estão vazias.

**Comment by andreagudo** [comment]
Sempre foi possível preencher os Oradores do Expediente antes das presenças. Até poque isso permite fazer um boletim de orientação sobre o que vai ocorrer na sessão, como faço há muito tempo. Solicito que permaneça dessa forma.

**Comment by edwardoliveira** [comment]
Em versão futura, irá aparecer mesmo os não presentes.
