### ISSUE TITLE
Critério secundário de ordem das normas jurídicas

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2815]
## Comportamento Esperado
As normas aparecem por critério de data, decrescente, e de número, decrescente.

## Comportamento Atual
O critério secundário número está em ordem crescente.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/norma/pesquisar?page=1&tipo=1&numero=&ano=2018&data_0=&data_1=&data_publicacao_0=&data_publicacao_1=&ementa=&assuntos=&data_vigencia_0=&data_vigencia_1=&o=&indexacao=

## Contexto
Consulta a normas jurídicas.

## Imagens do Ocorrido
![Captura de tela de 2019-05-28 09-15-24](https://user-images.githubusercontent.com/19169882/58477628-5b301c80-812a-11e9-9594-9602cfcf7d6e.png)

## Seu Ambiente
Versão usada (Release): 3.1.156
Nome e versão do navegador: Versão 73.0.3683.86 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by cesaraugc** [comment]
O comportamento esperado era o comportamento do sistema até a alteração da issue #2802 .

**Comment by andreagudo** [comment]
São situações diferentes. Esta issue trata de consulta de normas, a #2802 da relação de normas relacionadas.

**Comment by cesaraugc** [comment]
A alteração estará disponível na próxima versão.
