### ISSUE TITLE
Normas Juridicas - Alterar menu "Texto" para "Texto Compilado"

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#2822]
Alterar o nome do menu "Texto" para "Texto Articulado" para ficar com a mesma nomenclatura utilizada pelo senado

![image](https://user-images.githubusercontent.com/13314947/58648147-71330e00-82df-11e9-987d-40bb999aba2f.png)

## Comportamento Esperado

![image](https://user-images.githubusercontent.com/13314947/58647828-c4589100-82de-11e9-987d-df3e60b0e8d7.png)

![image](https://user-images.githubusercontent.com/13314947/58647885-dfc39c00-82de-11e9-850b-92e487959987.png)

## Comportamento Atual

![image](https://user-images.githubusercontent.com/13314947/58647978-0d104a00-82df-11e9-9573-4603bf2d1755.png)

![image](https://user-images.githubusercontent.com/13314947/58648001-1b5e6600-82df-11e9-9f2d-7ed930a937fe.png)

## Possível Solução

Alterar para 'Texto Articulado'
https://github.com/interlegis/sapl/blob/3.1.x/sapl/templates/norma/subnav.yaml#L18

Alterar para 'Texto Articulado'
https://github.com/interlegis/sapl/blob/3.1.x/sapl/templates/compilacao/subnav.html#L22

## Passos para Reproduzir (para bugs)

http://sapl.camarabento.rs.gov.br/ta/101/text

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Vc colocou no título 'Texto compilado' mas no corpo da issue colocou 'Texto Articulado':

![image](https://user-images.githubusercontent.com/9326037/58652963-1acbcc80-82eb-11e9-9789-38a4c84de8f5.png)


![image](https://user-images.githubusercontent.com/9326037/58652945-11dafb00-82eb-11e9-8ba9-77a0c5004f50.png)

**Comment by DtiLegBG** [comment]
Desculpe, o correto é "Texto Compilado" para ficar com a mesma nomenclatura do Senado
