### ISSUE TITLE
Player de video na tela de sessão

### ISSUE THREAD

**Issue by ulyssesBML** [interlegis/sapl#2837]
## Comportamento Esperado

Mostrar player de videos na tela de detalhes da sessao
## Comportamento Atual

Mostra o link para o video.
## Possível Solução

Usar o iframe do youtube.
## Contexto

Relacionado ao ticket: #[266861](https://suporte.interlegis.leg.br/scp/tickets.php?id=30384)

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by cesaraugc** [comment]
Mergeado na master.
