### ISSUE TITLE
Relatórios Administrativos

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#2841]
## Comportamento Esperado
Possibilidade de imprimir pdf ou preparar para impressão  para os resultados de todos os relatórios gerados (Matérias  em tramitação, Matérias por autor e etc)

## Comportamento Atual
Não é possível  gerar nenhum pdf  ou preparar para impressão para os relatórios ( somente visualização)

## Imagens do Ocorrido

![image](https://user-images.githubusercontent.com/1524415/59527342-b7789780-8eb1-11e9-9933-f3b95978f2a2.png)

## Seu Ambiente

* Versão usada (_Release_): Release: 3.1.157-RC5

**Comment by ricardocanela** [comment]
Resolvido pelo commit 4e0e9a06d026de0c4b782a700a3e0613839e3b01
