### ISSUE TITLE
Normas Jurídicas - Normas de Destaque

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#2854]
Existem algumas normas que tem um destaque maior do que outras, por exemplo os Códigos, o Regimento Interno, a Lei Orgânica.
Pensando em tornar mais rápido o acesso a essas Normas faço a seguinte sugestão:

## Comportamento Esperado

Que o operador de Normas ao editar a norma tenha como opção "Norma de Destaque" Sim | Não, que a opção default seja não. Que as normas marcadas como sim sejam listadas em:
No menu superior '"Normas Jurídicas" seja incluído um sub-menu chamado "Normas de Destaque" clicando nele que seja mostrada uma lista como a retornada pela pesquisa de Normas, porém só com as normas marcadas pelo operador como "Sim"

## Seu Ambiente

* Versão usada (_Release_): 3.1.158
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by LeandroJatai** [comment]
Concordo com isso aí... quero pra ontem...

**Comment by LeandroJatai** [comment]
neste caso, insira um apelido tb e não só a pergunta de Sim/Não e, na listagem das Normas de destaque, apresente esse apelido como título do item da lista e a epígrafe tradicional como subtitulo.

**Comment by DtiLegBG** [comment]
Não poderia ser utilizado o campo já existente "observação" para registrar o apelido da Lei, e na listagem de Normas de destaque exibir esse campo?

**Comment by LeandroJatai** [comment]
não concordo!
