### ISSUE TITLE
Botão "Acompanhar Matéria" não aparecendo em matérias em tramitação

### ISSUE THREAD

**Issue by cintiacmsjp** [interlegis/sapl#2865]
O botão "Acompanhar Matéria" para cadastro de e-mail para recebimento de notificações não está aparecendo em nenhuma matéria, mesmo elas estando em tramitação.

## Comportamento Esperado

O botão "Acompanhar matéria" deve aparecer enquanto o status for "Em tramitação".

## Comportamento Atual

O botão "Acompanhar Matéria" não está aparecendo.

## Passos para Reproduzir (para bugs)

1. Matérias Legislativas > Pesquisar Matéria Legislativa
2. Escolher uma matéria que está em tramitação
3. O botão acompanhar matéria não aparece.

## Imagens do Ocorrido

![image](https://user-images.githubusercontent.com/42623015/60443574-eef57c80-9bf1-11e9-9cae-a03f20a84ba6.png)

## Seu Ambiente

* Versão usada (_Release_):3.1.157-RC5
* Nome e versão do navegador: Chrome
* Nome e versão do Sistema Operacional (desktop ou mobile): Desktop
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Versões com o sufixo "-RC[0-9]" pode vir com erros e não são versões finais (sem sufixo). Poderia atualizar para a versão 3.1.158 e dizer se o erro continua?

Vcs estão hospedados no Interlegis?

**Comment by DtiLegBG** [comment]
Para contribuir, na Release: 3.1.159-RC0 está funcionando.

**Comment by edwardoliveira** [comment]
As versões com sufixo `-RC + [numero]` não são versões de produção. É preferível usar somente as versões maiores 3.1.157, 3.1.158, 3.1.159, etc. Só a pena usar as versões -RC para testes e abrir issues como essa que vc abriu. Não em produção! Eu testei aqui na versão 3.1.158 o erro não se reproduziu. 

Faça o teste na versão 3.1.158 e nos reporte se tudo está OK, por favor. Se não estiver, reabra a issue.

**Comment by cintiacmsjp** [comment]
Infelizmente na versão 3.1.158 o problema persiste:

**Comment by cintiacmsjp** [comment]
Infelizmente o erro persiste na versão 3.1.158

![image](https://user-images.githubusercontent.com/42623015/60453802-8796f700-9c08-11e9-81b2-d3dc205e4828.png)
![image](https://user-images.githubusercontent.com/42623015/60453835-a09fa800-9c08-11e9-943a-9dde12deab86.png)

**Comment by edwardoliveira** [comment]
Isso indica algum erro na configuração de email do SAPL de vocês. Existe uma checagem que verifica se o servidor foi configurado. Em caso negativo ele desabilita o botão de acompanhar matéria também. Por isso não conseguimos reproduzir o erro aqui conosco (nos dois testamos): o nosso SAPL está configurado e com acesso ao servidor de email. Verifique as suas conexões de email configuradas no arquivo .env ou nas variáveis de ambiente do docker-compose.yml.

**Comment by cintiacmsjp** [comment]
Edward
Existe alguma outra forma de testar?
Fazendo telnet do servidor a conexão está OK.
O sistema aceita IP?
Ao configurar o e-mail precisa iniciar o ambiente do zero ou mudando as configurações fica ok?

![image](https://user-images.githubusercontent.com/42623015/60455437-bca54880-9c0c-11e9-9912-defb07764894.png)
![image](https://user-images.githubusercontent.com/42623015/60455479-d8105380-9c0c-11e9-9938-3867bd05b540.png)

**Comment by edwardoliveira** [comment]
**Tá faltando um parâmetro de configuração aí no teu docker-compose.yml***
É o EMAIL_SEND_USER que deve ser o mesmo usuário do EMAIL_HOST_USER. Tem que ter os dois.

Vc deve entrar dentro do container do SAPL (não do Postgres) e digitar:

`$ python3 manage.py shell_plus`

Depois insira o seguinte código (identação é importante!): 

```
from django.core.mail import send_mail

send_mail(
    'Subject here',
    'Here is the message.',
    'sapl@cmsjp.pr.gov.br',
    ['to@example.com'],
    fail_silently=False,
)
```
Lembre-se de trocar o 'to@example.com' por um email válido de destino.

Se vc tiver com erro deve aparecer uma mensagem.

**Comment by cintiacmsjp** [comment]
Edward
Obrigada pela resposta!
Adicionei o parâmetro EMAIL_SEND_USER e com os comandos enviados consegui debugar o ambiente.
Precisei colocar a senha de e-mail inicial da criação do container no docker-compose.yml. Trocar após acontece erro. Essa senha inicial aparece nas mensagens de erro do shell. Está funcionando agora. Obrigada pelo auxílio.
