### ISSUE TITLE
PAUTA DA SESSÃO

### ISSUE THREAD

**Issue by adrchaves** [interlegis/sapl#2869]
## Comportamento Esperado

Incluir na pauta da Sessão "EXPEDIENTE"
## Comportamento Atual

Hoje na Pauta da Sessão não existe o Expediente, acho extremamente necessário, visto que colocando só as matérias de expediente e da ordem do dia, ficam faltando os itens do EXPEDIENTE

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Seu Ambiente

Versão Release: 3.1.158
Firefox 67.0.4
Sistema Windows 7 Professional 64 bits

**Comment by edwardoliveira** [comment]
Realizado pelo commit 879444ec41ee21cf859c5db5593efdd7e72ba1d2

**Comment by puera** [comment]
@edwardoliveira ao invés de incluir todos itens do expediente(Todos os campos) na pauta , poderia ter uma opção de selecionar o que gostaria por na pauta? Por exemplo aqui na câmara temos o expediente dividido por Pequeno e Grande Expediente , usamos muitos campos do expediente para por alguns dados como oradores como exemplo no expediente diversos ... 
Acredito que por todo conteúdo do expediente diversos na pauta ficaria muito conteúdo e não compatível com a pauta já que a mesma deveria ser sucinta

**Comment by edwardoliveira** [comment]
@puera @adrchaves O PR já foi feito há tempos pelo @ulyssesBML e está pronto para uso. Vcs chegaram a um consenso se coloca ou não essa mudança nas próximas versões do SAPL?

**Comment by puera** [comment]
@edwardoliveira na minha opinião a pauta ficará pesada com essas mudanças(Que é ser clara em relação as matérias), esperando o que o @adrchaves  acha sobre essas colocações que falei anteriormente
