### ISSUE TITLE
Filtrar somente anos de Norma Jurídica pelo Model

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#287]
Atualmente, o campo de ano em pesquisa de norma jurídica traz todos os anos de um intervalo. Fazendo uma pesquisa no model podemos trazer somente os anos que tiveram norma, devidade de-duplicados por um DISTINCT.

**Comment by eduardoedson** [comment]
https://github.com/interlegis/sapl/tree/287-Filtrar_Anos_De_Norma

**Comment by eduardoedson** [comment]
@edwardoliveira Pode revisar :+1:
