### ISSUE TITLE
Idéia: Possibilidae de vinculação de mais contas de usuários a entidade Autor

### ISSUE THREAD

**Issue by cintiacmsjp** [interlegis/sapl#2877]
Sugestão para que mais contas de usuários possam ser vinculados a um Autor.
Acontece aqui na CMSJP que nos gabinetes a proposição de indicações e projetos de lei fica a cargo de assessores diferentes. Para evitar compartilhamento de contas e facilitar auditoria o ideal é que cada usuário tenha seu login e senha individuais, porém vinculado a um mesmo autor.
Hoje só é possível vincular apenas uma conta de usuário ao Autor para uso da funcionalidade "Atividade Legislativa" > "Proposições".

## Comportamento Esperado

Possibilidade de vincular diversas contas de usuário a uma entidade Autor para uso da funcionalidade "Atividade Legislativa" > "Proposições". 

n:1

## Comportamento Atual

Hoje só é possível vincular um login de usuário a um Autor 1:1.

Caminho:
Sistema > Tabelas Auxiliares > Autor > selecionar autor > Editar 
![image](https://user-images.githubusercontent.com/42623015/60686249-08aaf400-9e7e-11e9-8d1a-8d15ea94bb1e.png)

## Possível Solução

Transformar o vínculo da tabela de 1:1 para n:1.

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Contexto

A alteração evitará compartilhamento de senhas e facilitará auditoria em caso de incidentes com envios de proposições equívocas.

## Seu Ambiente

* Versão usada (_Release_): 3.1.159
* Nome e versão do navegador: Chrome
* Nome e versão do Sistema Operacional (desktop ou mobile): Desktop
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
O custo de se implementar essa solução (criação de um relacionamento M-N ou N-1 onde atualmente é 1-1, migração dos dados inseridos, etc) não compensa o ganho. Isso sem falar em problemas que isso vai gerar como, por exemplo, quando um usuário logar que autor pegar dentre os possíveis?

**Comment by alessandroasac** [comment]
Também temos a mesma necessiadade. Nos foi informado pelo @morale que seria implementado apenas na versão 3.2, a qual não sabemos quando será disponibilizada.
Aqui estamos criando 1 autor para cada assessor e modificando o nome no momento em quem é recebida uma proposição.
Penso que a solução sugerida por @cintiacmsjp antenderia nossa demanda, vinculando o autor parlamentar aos usuários assessores, assim quando um usuário logar só terá associação com um único autor.
Não é a solução ideal mas é a que geraria menos impacto.
Talvez outra forma seria criar a entidade Gabinete no módulo parlamentar onde seria possível incluir os usuários que pertencem ao gabinete do parlamentar e compartilhariam o autor do mesmo e se tornariam inativos/impedidos de operar o sapl automaticamente ao final da legislatura.

**Comment by edwardoliveira** [comment]
@alessandroasac O Morale lhe informou errado. Ainda estamos avaliando se vamos ou não incorporar isso ao SAPL. Devido à complexidade e impacto de uma mudança desse tipo, devemos olhar a possibilidade de fazer algo assim somente em 2020, e, mesmo assim, está bem abaixo na lista de prioridades. Se vc deseja muito esse tipo de coisa, pode desenvolver e submeter um PR que iremos avaliar e eventualmente integrar ao ramo do projeto que futuramente será o 3.2.

**Comment by alessandroasac** [comment]
Entendo. Fico imaginando como é o funcionamento em casas legislativas maiores com o compartilhamento do usuário do parlamentar com os assessores, a cada exoneração de assessor seria necessário mudar a senha. Ou é criado um usuário e um autor para cada assessor?
Pretendemos desenvolver assim que possível, vemos como necessária essa mudança. 
Obrigado.

**Comment by cintiacmsjp** [comment]
@alessandroasac Se o assessor é exonerado deve-se excluir sua conta e criar uma nova para o novo assessor e vincular novamente ao autor (vereador) que ele representa. Aqui na CMSJP usamos o padrão nome.sobrenome. Evitamos ao máximo compartilhamento de senhas.
