### ISSUE TITLE
Bug: Relatório "Tramitações de Matérias por fim de prazo" não está sendo gerado corretamente

### ISSUE THREAD

**Issue by cintiacmsjp** [interlegis/sapl#2878]
O relatório "Tramitações de Matérias por fim de prazo" não está sendo filtrado conforme os parâmetro colocados no filtro, aparecendo matérias com status diverso ao escolhido.

![image](https://user-images.githubusercontent.com/42623015/60723949-7cdfa900-9f0b-11e9-8455-fa1b5ff7def9.png)

## Comportamento Esperado

Que o filtro traga as matérias apenas no prazo e status escolhido.

## Comportamento Atual

Está trazendo matéria com status e prazo diverso ao selecionado.

## Possível Solução

Corrigir query.

## Passos para Reproduzir (para bugs)

1. Na página inicial menu "Relatórios" 
2. Selecionar relatório "Tramitações de Matérias por fim de prazo"
3. Selecionar um período e um status.
4. Clicar em pesquisar.
5. Verifica-se que a pesquisa não confere com os filtros escolhidos.

## Contexto

Realizar pesquisa de matérias que estão com status selecionado no período selecionado em determinada comissão.

## Imagens do Ocorrido

Segue um exemplo:

![image](https://user-images.githubusercontent.com/42623015/60724324-77369300-9f0c-11e9-89b4-60d71da3a8e8.png)

Esta lei, por exemplo, nem tramitou no prazo escolhido:

![image](https://user-images.githubusercontent.com/42623015/60724279-58d09780-9f0c-11e9-846b-2f44f0f0b931.png)

## Seu Ambiente

* Versão usada (_Release_): 3.1.159-RC0 Ambiente de testes e 3.1.157 produção.
* Nome e versão do navegador: Chrome
* Nome e versão do Sistema Operacional (desktop ou mobile): Desktop
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Esse relatório causa muita confusão. Ele deveria trazer todos as matérias que já estiveram com um status de tramitação 'X'. Mas pelo visto frequentemente é usado como que para encontrar todas as matérias que tenham como último status de tramitação 'X'. 

Estamos olhando a data fim prazo para entender o que houve.

**Comment by cesaraugc** [comment]
A filtragem por data fim prazo aqui funcionou normalmente. Pode enviar um screenshot dos detalhes da Tramitação em questão?

**Comment by cesaraugc** [comment]
Caso a issue ainda seja pertinente, pode reabrir.
