### ISSUE TITLE
Thumbnails no crispy-forms

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#288]
Dar uma solução global para os trechos de `HTML` nos crispy forms semelhantes a esse:
https://github.com/interlegis/sapl/blob/56-valida-tipo-imagem-texto/base/forms.py#L91

A ideia é tentar sobrescrever o template adequado segundo
http://django-crispy-forms.readthedocs.org/en/latest/layouts.html#overriding-project-templates

Se isso não funcionar encontrar outra solução.

**Comment by edwardoliveira** [comment]
O código ficou bem legal, @eduardoedson. Os únicos problemas (regressões) foram:

    1. Vamos ver uma forma de fazer clipping da imagem para reduzir o tamanho do preview. 
![image](https://cloud.githubusercontent.com/assets/9326037/14602175/ecf39dc6-053c-11e6-9a91-30c58f4c8ee9.png)

    2. A página de detalhe do Parlamentar não mostra mais o preview da imagem.

![image](https://cloud.githubusercontent.com/assets/9326037/14602226/265e0380-053d-11e6-95d6-44bac11fd48f.png)

    Teria que alterar o CRUD automático pra fazer isso funcionar. Veja com o @marciomazza como fazer isso, por favor. Até lá, vou retornar esta issue para "Fazendo", ok?
