### ISSUE TITLE
Registro de modificações feitas na base após migração

### ISSUE THREAD

**Issue by LucianoAlmeida** [interlegis/sapl#289]
Para ter certeza que o administrador do site saiba quais foram as modificações e adições feitas da base de dados durante a migração, faz-se necessário criar uma model usando GenericForeignKey para referenciar os objetos que foram modificados.

----------------------
*Descrição de #135 (duplicada):*

O banco legado não tinha restrição de integridade. Então o processo de migração cria stubs pais para todos os registros órfãos.

Construir uma interface (um relatório com links) para inspeção de todos esses stubs criados (e não excluídos durante a migração).

**Comment by LucianoAlmeida** [comment]
Essa issue acabou sendo feita juntamente com o com a #320, por conta do dos erros encontrados durante a migração.

**Comment by marciomazza** [comment]
Eu sei que olhamos isso juntos mas fiquei um pouco na dúvida: o código dessa issue está no ramo
320-mudar-exclusao-stubs e faz parte da PR #329 ?

**Comment by LucianoAlmeida** [comment]
@marciomazza, sim o código que resolve o problema está lá.
