### ISSUE TITLE
Normas Juridicas - Criar na pesquisa um filtro de vigência

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#2896]
Seria interessante colocar na pesquisa de Normas Jurídicas um campo "YES_NO_CHOICES " com o label Vigência:

## Comportamento Esperado

O usuário poderia pesquisar somente por normas que estão vigentes

## Comportamento Atual

Colocando a data de final de vigência é possível filtrar as normas que não estão vigentes, porem não é possível filtrar somente as que estão vigentes.

## Possível Solução

Vigência:

Não
data_vigencia < data_atual

Sim
data_vigencia > data_atual ou data_vigencia = ' '

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by DtiLegBG** [comment]
O que acha @LeandroJatai @andreagudo @edwardoliveira  ?

**Comment by edwardoliveira** [comment]
@ulyssesBML Lembra de colocar o texto "Fix #<issue>" pra fechar automaticamente a issue!
