### ISSUE TITLE
Erro em Configurações do Portal Modelo

### ISSUE THREAD

**Issue by wagnermedeirosdossantos** [interlegis/sapl#2898]
https://www.joaopessoa.pb.leg.br/@@portalmodelo-settings
Ao tentar atualizar os dados da Câmara no link acima ocorre erro e não é atualizado.

Desculpe, mas parece haver um erro…
Aqui está a mensagem de erro completa:

Visualizar traceback como texto

Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module plone.z3cform.layout, line 66, in __call__
Module plone.z3cform.layout, line 50, in update
Module plone.z3cform.fieldsets.extensible, line 59, in update
Module plone.z3cform.patch, line 30, in GroupForm_update
Module z3c.form.group, line 145, in update
etc

**Comment by edwardoliveira** [comment]
Não damos suporte ao PM nesse projeto Github. **Aqui é somente para o SAPL 3.1.** Para o PM continue a usar o OSTicket.
