### ISSUE TITLE
Criar teste null=False em todos os CharField e TextField

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#290]
Criar um teste que verifique que null=False em todos os CharField e TextField de todos os models.

A rigor isso deveria ter sido parte de #121.

**Comment by eduardoedson** [comment]
É para verificar se no model existe null=False, ou para verificar se existe campos salvos com null?

**Comment by marciomazza** [comment]
Na declaração da classe mesmo.

Vide segundo parágrafo de
https://docs.djangoproject.com/en/1.9/ref/models/fields/#django.db.models.Field.null

**Comment by eduardoedson** [comment]
Ah sim, estava fazendo certo então. :+1:

**Comment by eduardoedson** [comment]
https://github.com/interlegis/sapl/commit/87607ad6b13e6a64e416b3d44804885fa171bdcf

**Comment by marciomazza** [comment]
Maravilha.

@interlegis/sapl Sei que sugeri antes não fazermos PRs para mudanças pequenas, mas estamos mudando a orientação: Para as próximas funcionalidades **criamos sempre um ramo à parte, com uma pull request**, mesmo que seja uma alteração pequena.

No caso dessa funcionalidade, por exemplo, tínhamos um commit apenas, mas, com as sugestões incorporadas, acabamos gerando 4 commits. Isso é prefeitamente normal, mas seria melhor se esses commits estivessem num ramo à parte. Faríamos até um `squash` no final, na verdade. O `master` está protegido contra `git push --force` então não fazemos squash nele.

Outra vantagem de sempre fazer uma PR:
* ao visitar https://github.com/interlegis/sapl/pulls o revisor vê uma lista de tudo que precisa ser revisado
* o GitHub nos ajuda a revisar listando todas as mudanças juntas na guia *Files changed* da PR

Escrevi esses motivos detalhadamente para que todos entendam a recomendação.
