### ISSUE TITLE
Salvar data e hora de últimas edições

### ISSUE THREAD

**Issue by rjoao** [interlegis/sapl#2909]
## Comportamento Esperado

Salvar data e hora da última alteração (criação ou edição) de Matéria Legislativa, Tramitação de Matéria Legislativa, Norma Jurídica e Tramitação de Documento Administrativo.

## Comportamento Atual

Esse dado não é salvo.

**Comment by edwardoliveira** [comment]
@rjoao Podemos fechar essa issue? :)

**Comment by rjoao** [comment]
> @rjoao Podemos fechar essa issue? :)

O PR dela (PR #2919) ainda não foi mergeado.
