### ISSUE TITLE
Entender Numeração de matérias

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#291]
Pra que é usado o model `materia.models.Numeracao`???

@morale explicou que Ségio Damiati (Campinas) introduziu essa funcionalidade como forma (genérica, eu acho) de agregar matérias a "processos". Vamos conversar com ele para entender melhor. Tb conversar com Rogério Frá (Bento Gonçalves - RS), que usa essa funcionalidade. Ambos hospedam o sapl fora do interlegis.

Seria interessante pesquisar em todas as bases hospedadas no interlegis quem usa essa tabela.

**Comment by eduardocalil** [comment]
Após ter isso resolvido. Colocar o campo "Número de Processo"  em Pesquisa de Matéria.

**Comment by morale** [comment]
O número de processo é um valor que o sapl não tem qq controle, apenas uma variável a mais.

**Comment by edwardoliveira** [comment]
Feito.
