### ISSUE TITLE
Prévia de URL de youtube das sessões não exibe corretamente

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#2911]
## Comportamento Esperado
A prévia ser exibida corretamente tanto quanto local , quanto como externo

## Comportamento Atual
Após o merge de  #2838 as URL que contém o link do youtube ficaram sem exibição caso seja acessada externamente.

## Passos para Reproduzir (para bugs)
1. Acessar o SAPL externamente - verificar os links 

## Imagens do Ocorrido

SAPL em rede LOCAL

![image](https://user-images.githubusercontent.com/1524415/62372595-4139fe00-b50e-11e9-99f4-855d52380d71.png)

SAPL em acesso externo

![image](https://user-images.githubusercontent.com/1524415/62372631-5a42af00-b50e-11e9-82b3-22e66d7e0ad7.png)

## Seu Ambiente

* Versão usada (_Release_): 3.1.159

**Comment by cesaraugc** [comment]
Resolvido com o commit 47138cb. Poderia verificar @puera ?

**Comment by puera** [comment]
@cesaraugc resolvido!
