### ISSUE TITLE
Certificado SSL do SAPL

### ISSUE THREAD

**Issue by IsaacCastro** [interlegis/sapl#2937]
## Problema

Comunidade, não sei se esse é o local adequado, mas pergunto se alguém tem uma ideia de quando irão renovar o certificado do SAPL. Apesar de poder acessar o site, contudo, alguns usuários, deixam de abrir a aplicação por conta da mensagem (conforme abaixo)

![image](https://user-images.githubusercontent.com/43033220/63166188-0488ff00-c004-11e9-8c5c-12efe2595b5c.png)

**Comment by edwardoliveira** [comment]
Não é aqui não. Isso é configuração de deployment do SAPL. Se o SAPL é hospedado no Interlegis deve abrir um ticket em https://suporte.interlegis.leg.br.
