### ISSUE TITLE
Menus - #FakeLink

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#2942]
Quando clicado nos menus, na url o endereço montado é /#fakeLink e não é direcionado para a página solicitada

## Passos para Reproduzir (para bugs)

Pagina inicial, menu superior , qualquer um deles....

## Imagens do Ocorrido

![image](https://user-images.githubusercontent.com/13314947/63343672-efbeab00-c324-11e9-8278-5764edddfacf.png)

## Seu Ambiente

Instalação Local
* Versão usada (_Release_): 3.1.160-RC0
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Não entendi. Esses menus 'Abertura', 'Expedientes', 'Ordem Dia', etc não devem ir pra página nenhuma. Eles devem abrir sub-menus que vão direcionar pra telas específicas.

**Comment by DtiLegBG** [comment]
Isso mesmo, não abrem os menus e na url é mostrado #FakeLink como na imagem. O erro acontece só com o SAPL em Debug=False

**Comment by edwardoliveira** [comment]
Se vc voltar para o release 3.1.159 o erro persiste?

**Comment by DtiLegBG** [comment]
git log --oneline -n 5
3882e3e Conserta release.sh (#2905)
fffc11b Release: 3.1.159
ef92e24 Mudanças em release.sh
ff5f517 Revert "Release: 3.1.159"
f499744 Release: 3.1.159

Neste ponto está funcionando

**Comment by edwardoliveira** [comment]
Se vc estiver fazendo o checkout via github então vai subindo até encontrar o commit em que ele pare de funcionar, por favor.

**Comment by DtiLegBG** [comment]
O commit que gerou o erro foi esse
https://github.com/interlegis/sapl/commit/8d9bd75c2562cbe7f520f3a8bfedc77db9b555a1

**Comment by DtiLegBG** [comment]
sim, rodei, mas pelo que entendi aqui foi algum cache do Browser, depois de limpar está funcionando ok.
Muito Obrigado
