### ISSUE TITLE
Adicionando participação em comissão: parlamentares não aparecem

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2951]
## Comportamento Esperado
Os parlamentares ativos deviam aparecer na caixa de seleção, com excessão dos que não foram adicionados, como o Presidente Cardosinho. Caso dos Vereadores Auro e Rosa, recentemente ativados.

## Comportamento Atual
Nem todos os Veradores ativos aparecem.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/comissao/92/participacao/create

## Contexto
Adição de participação de Vereador em comissão.

## Imagens do Ocorrido
![Captura de tela de 2019-09-03 08-03-39](https://user-images.githubusercontent.com/19169882/64168748-8b224680-ce22-11e9-81f9-06e75f73e3b5.png)

## Seu Ambiente
Versão usada (Release): 3.1.158
Nome e versão do navegador: Versão 76.0.3809.100 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by andreagudo** [comment]
Acrescento que, em 2018, foi possível incluir os parlamentares Auro e Rosa nas comissões, em 10/08/2019. E em 16/07 deste ano consegui incluir o Ver. Carlito.

**Comment by edwardoliveira** [comment]
Essa tela não vai listar parlamentares cujo mandato não contemple o período da comissão em questão. Auro teve mandato somente em 2018 (vide imagem), portanto não vai ser possível acrescentá-lo em comissões de 2019.

![image](https://user-images.githubusercontent.com/9326037/64369482-d2f7c800-cff2-11e9-8414-d3fabe6df50a.png)
