### ISSUE TITLE
Instalação da versão mais recente falha devido a ausência de cairocffi

### ISSUE THREAD

**Issue by rkhaotix** [interlegis/sapl#2954]
Estou tentando atualizar uma nova versão do SAPL (a mais recente disponível) porém ao seguir os passos iniciais (disponível aqui https://github.com/interlegis/sapl/blob/3.1.x/docs/instalacao31.rst) o seguinte comando retorna um erro:

`mkvirtualenv -a /var/interlegis/sapl -p python3 -r requirements/requirements.txt sapl`

`
ERROR: cairosvg 2.4.1 requires cairocffi, which is not installed.
ERROR: weasyprint 44 requires cairocffi>=0.9.0, which is not installed.
...
AssertionError: cairocffi>=0.9.0 .dist-info directory not found`

## Comportamento Esperado
Conseguir instalar o SAPL pelos procedimentos fornecidos no repositório do projeto.

## Comportamento Atual
Vide arquivo de log:
[sapl_install_error.log](https://github.com/interlegis/sapl/files/3571041/sapl_install_error.log)

## Passos para Reproduzir (para bugs)
Execute o processo de instalação (ambiente de desenvolvimento) conforme https://github.com/interlegis/sapl/blob/3.1.x/docs/instalacao31.rst até o comando abaixo

`mkvirtualenv -a /var/interlegis/sapl -p python3 -r requirements/requirements.txt sapl`

## Seu Ambiente
* Versão usada (_Release_): 3.1.158
* Nome e versão do navegador: Google Chrome Versão 76.0.3809.132 (Versão oficial) 64 bits
* Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04

P.S.: existe algum documento oficial que me auxilie a apenas atualizar o código do SAPL e o banco de dados (estrutura de tabelas)? Essa é a única coisa que preciso fazer no momento mas estou esbarrando nos erros que reportei acima.

**Comment by edwardoliveira** [comment]
Vc tem a biblioteca `libffi-dev` e `libffi` instaladas? Tentaram instalar em uma versão mais moderna do Ubuntu com a 18.04?

**Comment by rkhaotix** [comment]
> Vc tem a biblioteca libffi-dev e libffi instaladas (apt-get)?
Sim

> Tentaram instalar em uma versão mais moderna do Ubuntu com a 18.04?
Não, mas poderia tentar.

**Comment by edwardoliveira** [comment]
> Uma outra dúvida, instalando uma nova versão do SAPL eu conseguiria utilizar a base de dados de uma versão um pouco mais antiga? Digamos atualizando da 3.1.130 para a 3.1.160 seria possivel usar a base de dados da primeira na segunda, isso após rodar as migrations devidamente.

Sim, vc deve atualizar diretamente da 130 pra 160, inclusive. Por via das dúvidas faça um backup do banco antes, mas não deve ter maiores problemas atualizando não.

**Comment by rkhaotix** [comment]
Obrigado @edwardoliveira 
Eu vou fazer a instalação novamente mas no Ubuntu 18 e dou um retorno.

**Comment by rkhaotix** [comment]
@edwardoliveira Obtive sucesso ao instalar o sapl mais novo no Ubuntu 18.04. A única questão que estou enfrentando é que ele está exibindo uma infinidade de informações de debug ao rodapé da tela, porém no meu `.env` tenho `DEBUG=False`. O que eu posso ter errado?

![sapl_install](https://user-images.githubusercontent.com/2205476/64647145-d920e680-d3ee-11e9-8541-8d8ef6111c69.png)

**Comment by edwardoliveira** [comment]
Fechando essa issue pq pela data e último comentário parece ter sido resolvido. Caso contrário é só reabrir e comentar.
