### ISSUE TITLE
Erro ao cadastrar período de composição

### ISSUE THREAD

**Issue by rkhaotix** [interlegis/sapl#2956]
Ao tentar cadastrar um período de composição de comissão recebo o seguinte erro:
`Cannot assign "''": "Composicao.comissao" must be a "Comissao" instance.`

## Comportamento Esperado
Ter um período de composição de comissão cadastrado, para prosseguir com o cadastro de participação em comissão.

## Comportamento Atual
Na primeira tentativa de cadastro de um período de composição de comissão recebo o erro em anexo.
[Erro ao cadastrar Periodo de Composição da Comissão](https://github.com/interlegis/sapl/files/3579810/Erro.ao.cadastrar.Periodo.de.Composicao.da.Comissao.pdf)

Se tento prosseguir com o cadastro sem o periodo de composição e tento adicionar uma participação em comisssão recebo o seguinte erro:

[Erro ao Adicionar Participação em Comissão](https://github.com/interlegis/sapl/files/3579820/Erro.ao.Adicionar.Participacao.em.Comissao.pdf)

O que eu pude perceber foi que mesmo com o período de composição cadastrado (vide anexo a seguir) na tela de composição de comissões o período que eu cadastrei não é listado no combo "Selecione o Período". A partir daí se tento algum dos dois cadastros "Adicionar Composição de Comissão" ou "Adicionar Participação em Comissão" recebo os erros reportados acima.

[Telas SAPL.pdf](https://github.com/interlegis/sapl/files/3579832/Telas.SAPL.pdf)

## Seu Ambiente
* Versão usada (_Release_): 3.1.130
* Nome e versão do navegador: Chrome Versão 76.0.3809.132 (Versão oficial) 64 bits
* Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04

**Comment by cesaraugc** [comment]
A release utilizada é de fato a 3.1.130? Atualmente já estamos com a release 3.1.160-RC0.

**Comment by rkhaotix** [comment]
Sim. Incluse tentei atualizar para a 3.1.158 na tentativa de ver se isso foi eventualmente atualizado e os procedimentos de instalação falham conforme reportei aqui https://github.com/interlegis/sapl/issues/2954

**Comment by cantuariavc** [comment]
Resolvido no comia 88f5287ba722ba143d2f737211d49e813e9efc06
A correção já está na versão 3.1.160-RC14.
