### ISSUE TITLE
Há possibilidade de enviar PR com pequena alteração no relatório de pauta da sessão?

### ISSUE THREAD

**Issue by alessandroasac** [interlegis/sapl#2967]
Gostaria de saber se há possibilidade de enviar PR com pequena alteração no relatório de pauta da sessão.

Seria apenas para deixar em caixa alta "MATÉRIAS DO EXPEDIENTE" e "MATÉRIAS DA ORDEM DO DIA".

Também gostaria de saber se há possibilidade de continuar com o sapl na interlegis porém utilizando um fork nosso.

## Comportamento Esperado

Onde lê-se "Matérias do Expediente" e "Matérias da Ordem do Dia" ficariam respectivamente "MATÉRIAS DO EXPEDIENTE" e "MATÉRIAS DA ORDEM DO DIA".

## Possível Solução

```
sapl/relatorios/templates/pdf_pauta_sessao_gerar.py

#expediente_materia
    tmp += '<para style="P1">MATÉRIAS DO EXPEDIENTE</para>\n\n'

#votacao
    tmp += '<para style="P1">MATÉRIAS DA ORDEM DO DIA</para>\n\n'
```

## Contexto
Nos foi solicitado a fim de melhorar a leitura do relatório impresso.

## Seu Ambiente
* Versão usada (3.1.159) hospedada na interlegis: Câmara Municipal de João Pessoa
* Nome e versão do navegador: Qualquer um

**Comment by edwardoliveira** [comment]
> Gostaria de saber se há possibilidade de enviar PR com pequena alteração no relatório de pauta da sessão.
Sim.
> Também gostaria de saber se há possibilidade de continuar com o sapl na interlegis porém utilizando um fork nosso.
Não.

**Comment by sesostris** [comment]
No caso do fork, o Interlegis não consegue manter em produção versões diferentes do sistema, pois os procedimentos de instalação e atualização são automatizados, e manter forks diferentes traria várias possibilidades de falhas. A melhor alternativa é abrir issues com as alterações que você deseja fazer no fork, discutir essas alterações com a equipe de desenvolvimento e, sendo aprovadas, implementá-las e incorporá-las ao SAPL oficial.
