### ISSUE TITLE
Envio de arquivo (texto original) problema

### ISSUE THREAD

**Issue by fabiobelo** [interlegis/sapl#2975]
## Comportamento Atual
Ao enviar uma propositura ou editar: quando adicionamos um arquivo em qualquer formato, contendo mais de 50 caracteres ou havendo alguma pontuação no mesmo, leva ao erro 500.

## Possível Solução
Tratar o arquivo antes do envio: renomeando-o por um md5 ou qualquer outro padrão, que não exija do usuário a renomeação do arquivo. 

## Passos para Reproduzir (para bugs)
Ao enviar qualquer arquivo.

## Seu Ambiente

* Versão usada (_Release_): 3.1.160-RC0

**Comment by edwardoliveira** [comment]
Vc se refere ao nome do arquivo ter mais de 50 caracteres? 

Se for o caso, infelizmente, uns usuários reclamaram de renomeação automática. Eles querem que preserve o nome original (lei-8919-2019.pdf), e para tanto tivemos que modificar o código do SAPL para não sobreescrever.

**Comment by fabiobelo** [comment]
Isso! Nesse caso, poderíamos deixar essa opção a escolha da casa legislativa? De imediato, qual linha modificar para subscrever o arquivo, independente do tamanho de número de caracteres do arquivo original?

**Comment by edwardoliveira** [comment]
Não tem como deixar de escolha da casa legislativa no momento. Nem é minha intenção deixar.
