### ISSUE TITLE
Incluir na opção de incluir Audiência Pública, a proposição que autorizou a mesma

### ISSUE THREAD

**Issue by babigott** [interlegis/sapl#2977]
Adicionar um campo que link a proposição (requerimento) a Audiência Pública criada. 

Outro campo que também link a imagem da publicação no jornal da mesma.

**Comment by edwardoliveira** [comment]
O campo 'Anexo da Audiência Pública' pode ser usado para fazer o upload do link da imagem. Como essa issue, de certa forma, é repetição da issue https://github.com/interlegis/sapl/issues/2978, vamos fechá-la.

**Comment by edwardoliveira** [comment]
Os campos Tipo de Matéria, Número de Matéria, e Ano de matéria não poderiam ser utilizadas pra indicar o requerimento que deu origem à matéria?
