### ISSUE TITLE
Em adicionar Audiência pública falta o campo para adicionar o parlamentar responsável e a proposição que a criou

### ISSUE THREAD

**Issue by babigott** [interlegis/sapl#2978]
- Incluir um campo que liste o parlamentar autor da audiência.

- Incluir um campo que liste as proposições do autor para linkar a proposição solicitada de autorização e aprovação da audiência. 

ex.: toda audiência precisa ser aprovada em plenário através de um requerimento.

**Comment by edwardoliveira** [comment]
Os campos Tipo de Matéria, Número de Matéria, e Ano de matéria não poderiam ser utilizadas pra indicar o requerimento que deu origem à matéria?

**Comment by edwardoliveira** [comment]
Uma audência é **SEMPRE** aberta via REQUERIMENTO? Não existe outro tipo de documento que seja utilizado para abrir em outras casas legislativas?
