### ISSUE TITLE
Retirar na votação simbólica a OBRIGATORIEDADE de preenchimento dos campos SIM e NÃO e ABSTENÇÕES 

### ISSUE THREAD

**Issue by jonasrn** [interlegis/sapl#2986]
## Comportamento Esperado

Ser FACULTATIVO para o usuário o preenchimento na VOTAÇÃO SIMBÓLICA, de quantos votaram SIM NÃO E AS ABSTENÇÕES, deixar apenas o resultado da votação como obrigatório, isso devido ao seguinte fato, embora tenha na assembleia por exemplo uma ordem do dia {X} com 10 projetos a serem votados, entre um projeto e outro, deputados DEIXAM a sessão na apreciação de determinada matéria, voltam a SESSÃO na apreciação de outra, de modo que nem sempre os deputados que estão presente na ordem do dia {X} , de fato estarão presentes em todo o decorrer dos projeto apreciados naquele ordem do dia , tornando quase impossível para o usuário do SAPL realizar essa soma, baseado nisso fundamenta-se nosso pedido.

## Comportamento Atual

Como está hoje, você é obrigado a informar quantos votaram SIM, NÃO é as ABSTENÇÕES 

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Imagens do Ocorrido

![DEIXARFACULTATIVO](https://user-images.githubusercontent.com/2423695/65993911-8f18a700-e468-11e9-9140-bdecd536503a.png)

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Fazer isso abre a possibilidade de uma série de bugs para atender um caso específico. Portanto, essa issue **não será implementada**. Talvez num futuro possamos vir a reconsiderar isso, quando tivermos a oportunidade de refazer esse módulo.

**Comment by jonasrn** [comment]
De todo modo isso é muito importante para a assembleia do tocantins

**Comment by edwardoliveira** [comment]
Esteja livre para forkar o projeto e modicar de acordo com suas necessidades.
