### ISSUE TITLE
Definição de número de início diferente para protocolo

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#2987]
## Comportamento Esperado
A numeração de início diferente para protocolo de documentos não deve depender do operador de protocolo, deve ser uma política da casa. Tal alteração deveria ser uma opção nas Tabelas Auxiliares.

## Comportamento Atual
O operador de protocolo pode alterar o número de início, o que pode ocorrer de forma involuntária.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/protocoloadm/protocolar-doc

## Contexto
Protocolo de documento.

## Imagens do Ocorrido
![Captura de tela de 2019-10-02 09-01-58](https://user-images.githubusercontent.com/19169882/66042690-87521480-e4f3-11e9-8de3-7c8bb4d1c226.png)

## Seu Ambiente
Versão usada (Release): 3.1.158
Nome e versão do navegador: Versão 77.0.3865.90 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
De fato, temos tido mais que um punhado de problemas com pessoas que digitam números errados. 

André, poderia fornecer mais detalhes de como vc imagina essa operação? O que seria essa permissão em tabelas auxiliares? Somente pessoas com algum privilégio poderiam gerar números fora de ordem?

**Comment by andreagudo** [comment]
Penso que deva ser possível a qualquer operador das tabelas auxiliares
fazer tal mudança. O ideal, porém, é faze-la apenas quando se inicia o uso
do SAPL, depois não há mais necessidade  e causa problemas. Assim, sugiro
que,  mesmo que se insista em mudar novamente , o sistema alerte para
eventuais problemas e apresente o tradicional "tem certeza"?


Em qua, 2 de out de 2019 12:08 PM, Edward <notifications@github.com>
escreveu:

**Comment by edwardoliveira** [comment]
Estou pensando em algo assim:

Uma opção de "permitir numeração manual de protocolo" na tela de configuração da aplicação. O default é 'Não'. Daí se o usuário colocar sim aparece aquele campo no rodapé da página. Dá pra colocar um alerta para o usuário também.
