### ISSUE TITLE
Seria importante o SAPL permitir a validação de presença do parlamentar nas sessões através de ponto de leitor de digitais

### ISSUE THREAD

**Issue by jonasrn** [interlegis/sapl#2991]
## Comportamento Esperado

Seria importante o SAPL permitir a validação de presença do parlamentar nas sessões através de ponto de leitor de digitais, assim o painel eletrônico seria mais bem aceito nas casas legislativa, da forma que é hoje é muito fácil de burlar a presença de um parlamentar.

## Comportamento Atual

Hoje é preciso um computador para o parlamentar marcar sua presença, deixando muita facilidade de o sistema ser burlado.

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Issue repetida de https://github.com/interlegis/sapl/issues/2479
