### ISSUE TITLE
URL arquivo vídeo não carrega na sessão

### ISSUE THREAD

**Issue by BismarkLemke** [interlegis/sapl#3015]
Ao editar a sessão plenária e salvar a url do vídeo (Youtube, facebook) o vídeo não é carregado por padrão, apenas após o usuário clicar em "carregar scripts não seguros".

## Comportamento Esperado
Salvar a URL do vídeo na sessão plenária e ao carregar a página o iframe com o vídeo ser exibido.
![image](https://user-images.githubusercontent.com/23421504/66752122-100f6f80-ee67-11e9-85f3-0d1cb88bf319.png)

## Comportamento Atual
Ao salvar a URL do vídeo na Sessão o vídeo não efetua o carregamento do iframe
![image](https://user-images.githubusercontent.com/23421504/66752041-db9bb380-ee66-11e9-91b2-018af98c1896.png)

## Possível Solução
O iframe apenas carrega após o usuário clicar em "carregar scripts não seguros".
![image](https://user-images.githubusercontent.com/23421504/66751965-ab541500-ee66-11e9-8530-99d804b21738.png)

## Contexto
Para os utilizadores do sistema ao acessarem a sessão, podem não observar a restrição de scripts do navegador. Podendo questionarem sobre a alimentação desde campo.

## Seu Ambiente
* Versão usada (_Release_): 3.1.159
* Nome e versão do navegador: Chrome 77.0.3865.120 (Versão oficial) 64 bits
* Nome e versão do Sistema Operacional (desktop ou mobile): Desktop Windows 10 1903

**Comment by edwardoliveira** [comment]
Autalize para a versão 3.1.160-RC1.

**Comment by edwardoliveira** [comment]
Se preferir fazer a alteração manualmente, o commit que conserta esse erro é esse: https://github.com/interlegis/sapl/commit/47138cbda12c1a52aca8d245170e7d19d214775f

**Comment by edwardoliveira** [comment]
Atualize para a versão 3.1.160-RC1

**Comment by edwardoliveira** [comment]
Procure também na documentação do Chrome para verificar a possibilidade de configurar o carregamento automático do conteúdo do iframe.

**Comment by edwardoliveira** [comment]
Se preferir alterar na versão atual, o commit que conserta esse bug é esse aqui: https://github.com/interlegis/sapl/commit/47138cbda12c1a52aca8d245170e7d19d214775f
