### ISSUE TITLE
Substituir para "Texto Integral Original"

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3031]
## Comportamento Esperado
Nos dados iniciais da norma, substituir "Texto Integral" por "Texto Integral Original".

## Comportamento Atual
Consta "Texto Integral". Pode gerar confusão para os leigos que, ao acessarem o texto da norma, pensam se tratar do texto compilado.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/norma/1456

## Contexto
Pesquisa do texto de norma jurídica.

## Imagens do Ocorrido
![Captura de tela de 2019-11-05 15-09-04](https://user-images.githubusercontent.com/19169882/68234135-5fb50700-ffdf-11e9-9f93-45603c4f7a01.png)

## Seu Ambiente
Versão usada (Release): 3.1.158
Nome e versão do navegador: Versão 77.0.3865.90 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by LeandroJatai** [comment]
Sugiro mudar para "Norma Digitalizada"

**Comment by andreagudo** [comment]
Considero importante a expressão "original".

Em ter, 5 de nov de 2019 3:38 PM, Leandro Roberto Silva <
notifications@github.com> escreveu:

**Comment by edwardoliveira** [comment]
@andreagudo @LeandroJatai Talvez seja interessante postar na lista de discussão do GITEC para mais feedback?

**Comment by edwardoliveira** [comment]
@LeandroJatai @andreagudo Então, fica "Texto Integral", "Texto Integral Original", "Norma Digitalizada" ou "Norma original Digitalizada"? :)

**Comment by edwardoliveira** [comment]
@LeandroJatai  @andreagudo Chegou-se a algum consenso nessa issue?
