### ISSUE TITLE
Relatório Atas das Sessões Plenárias 

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#3038]
## Comportamento Esperado
Ao clicar pesquisar retornar alguma mensagem de Erro ( Pois há obrigatoriedade no campo) 

## Comportamento Atual
Ao clicar Pesquisar sem nenhum parâmetro preenchido , nada é retornado

## Seu Ambiente

* Versão usada (_Release_): 3.1.160-RC7

**Comment by cesaraugc** [comment]
Foi retirada a obrigatoriedade deste campo no commit 7801e6575e3c2ab0a8c8fcaa6ad6891c53ac261b.
