### ISSUE TITLE
Tipos de Expediente em ordem diferente na Pauta da Sessão

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3053]
## Comportamento Esperado
A ordem dos tipos de expediente na Pauta da Sessão, em Expedientes, deve ser a definida nas Tabelas Auxiliares.

## Comportamento Atual
A ordem está invertida.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/sessao/pauta-sessao/2800/

## Contexto
Pesquisa da Pauta da Sessão.

## Imagens do Ocorrido
![Captura de tela de 2019-12-10 16-15-55](https://user-images.githubusercontent.com/19169882/70561018-757e9480-1b68-11ea-81b9-9767d311269d.png)

## Seu Ambiente
Versão usada (Release): 3.1.160-RC7
Nome e versão do navegador: Versão 78.0.3904.108 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

## Seu Ambiente
Versão usada (Release): 3.1.160-RC7
Nome e versão do navegador: Versão 78.0.3904.108 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by rjoao** [comment]
Problema solucionado.
