### ISSUE TITLE
Extrato de ata confuso quando se adiciona URL e OBS em Oradores

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#3054]
## Comportamento Esperado
Que seja clicável a URL adiciona em URL vídeo e destaque para cada orador caso adiciona URL e Observação
## Comportamento Atual
Ao adicionar uma URL de vídeo não é possível abrir diretamente no extrato além de ser confuso as informações quando é adicionada (Url de vídeo e Observação)

## Seu Ambiente

* Versão usada (_Release_): 3.1.160-RC11

**Comment by edwardoliveira** [comment]
>  destaque para cada orador caso adiciona URL e Observação

Que tipo de destaque colocar? Negrito e itálico?

**Comment by puera** [comment]
@edwardoliveira eu fiz um pr #3055 com a mudança , dá uma olhada lá

**Comment by edwardoliveira** [comment]
**SEMPRE** que vc for trabalhar numa issue faça o favor de se atribuir (assignee) antes, pois assim evita que eu me atribua ou passe pra outra pessoa.

**Comment by puera** [comment]
@edwardoliveira eu não tenho permissão no repositório , por isso não me atribuí no issue hehehe

**Comment by edwardoliveira** [comment]
Então pede ou fala que vai fazer um PR pra essa issue que eu coloco vc como assignee.
