### ISSUE TITLE
Relatório Tramitações de Matérias incorreto

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3067]
## Comportamento Esperado
Deve filtrar conforme critérios definidos na pesquisa.

## Comportamento Atual
Está incluindo matérias de outro ano na pesquisa da figura e dos links abaixo.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/sistema/relatorios/data-fim-prazo-tramitacoes
https://sapl.agudo.rs.leg.br/sistema/relatorios/data-fim-prazo-tramitacoes?tramitacao__data_fim_prazo_0=01%2F01%2F2019&tramitacao__data_fim_prazo_1=31%2F12%2F2019&tramitacao__unidade_tramitacao_local=&tramitacao__unidade_tramitacao_destino=&tipo=1&tramitacao__status=8&pesquisar=Pesquisar

## Contexto
Emissão de relatório.

## Imagens do Ocorrido
![Captura de tela de 2019-12-17 17-09-55](https://user-images.githubusercontent.com/19169882/71030729-cce4ad80-20f0-11ea-9284-add6973ce6c5.png)
![Captura de tela de 2019-12-17 17-13-12](https://user-images.githubusercontent.com/19169882/71030761-d9690600-20f0-11ea-9a7b-f11d04640aab.png)

## Seu Ambiente
Versão usada (Release): 3.1.160-RC11
Nome e versão do navegador: Versão 79.0.3945.79 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by rjoao** [comment]
Essas matérias de 2018 são listadas porque possuem uma ou mais tramitações com a Data Fim Prazo dentro do período pesquisado.
