### ISSUE TITLE
Resultados de votações deixaram de aparecer

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3072]
## Comportamento Esperado
Os resultados das votações das matérias devem aparecer.

## Comportamento Atual
Não estão aparecendo para matérias votadas antes de 04/06/2018, embora apareçam as observações das votações (o que mostra que os resultados foram registrados).

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/sessao/1978/ordemdia
https://sapl.agudo.rs.leg.br/sessao/1988/ordemdia
https://sapl.agudo.rs.leg.br/sessao/1486/ordemdia
https://sapl.agudo.rs.leg.br/sessao/1486/matordemdia/votsimb/view/3283/6619

## Contexto
Pesquisa da relação de matérias na Ordem do Dia.

## Imagens do Ocorrido
![Captura de tela de 2019-12-26 10-17-54](https://user-images.githubusercontent.com/19169882/71477699-27090100-27ca-11ea-824e-2f9eca324e02.png)
![Captura de tela de 2019-12-26 10-21-55](https://user-images.githubusercontent.com/19169882/71477701-2c664b80-27ca-11ea-8222-c938548e71d0.png)
![Captura de tela de 2019-12-26 10-22-29](https://user-images.githubusercontent.com/19169882/71477702-312aff80-27ca-11ea-9321-4412b42a9412.png)

## Seu Ambiente
Versão usada (Release): 3.1.160-RC11
Nome e versão do navegador: Versão 79.0.3945.79 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by andreagudo** [comment]
Parece ser mais complexo. Ha resultados de matéria antigas que aparecem.

**Comment by edwardoliveira** [comment]
Identificamos um bug relacionado a votação simbólica, que foi introduzido ao adicionar novos tipos de ação (retirada de pauta, leitura de matéria). Sabe dizer se outras votações que não sejam simbólicas também deixaram de aparecer?

**Comment by edwardoliveira** [comment]
Identificamos a razão do bug, mas estamos investigando mais um pouco porque alguns registros estão assim.

**Comment by edwardoliveira** [comment]
Fixed by commit https://github.com/interlegis/sapl/commit/5ce0e3091c32f297db78a2b86290ba00894b28ef
