### ISSUE TITLE
Total de votos não corresponde à quantidade de votantes

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3075]
## Comportamento Esperado
O registro do resultado da votação deve corresponder ao número de votantes presentes.

## Comportamento Atual
O resultado 8x0 (sem o voto do Presidente) não está sendo aceito.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/sessao/912/matordemdia/votsimb/6219/6257?

## Contexto
Registro de resultado da votação simbólica do Requerimento 16/1997 realizada na sessão de 07/07/1997.

## Imagens do Ocorrido
![Captura de tela de 2019-12-31 09-18-21](https://user-images.githubusercontent.com/19169882/71621607-09afaa80-2baf-11ea-8083-f6b1a2fdf945.png)

## Seu Ambiente
Versão usada (Release): 3.1.160-RC11
Nome e versão do navegador: Versão 79.0.3945.79 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
Os parlamentares precisam estar ativos para que a votação seja contabilizada. Vamos alterar esta mensagem de erro para que seja mais clara sobre o porque de não ter sido salva.

**Comment by edwardoliveira** [comment]
![image](https://user-images.githubusercontent.com/9326037/72368593-22ef4580-36dd-11ea-82e7-96b520e3af0e.png)

**Comment by edwardoliveira** [comment]
Os registros de votação só podem ser alterados se os parlamentares estiverem **ativos**. Tem que ativar para poder cadastrar o resultado dessa votação, e depois desativar.

Vamos alterar a mensagem de erro para que possa ser mais elucidativa, conforme abaixo:

![image](https://user-images.githubusercontent.com/9326037/72439398-9c427300-3785-11ea-9810-9f81709b3aa1.png)

**Comment by edwardoliveira** [comment]
Conforme explicado, tem que colocar os usuários como ativo se quiser atualizar votação antiga.
