### ISSUE TITLE
#issue 2927 - implementação

### ISSUE THREAD

**Issue by IsaacCastro** [interlegis/sapl#3087]
Pessoal a solicitação da issue #2927 foi implementada?

Aqui em nosso SAPL (release 3.1.159) continua o mesmo problema!

![73298177-9e77e900-41eb-11ea-9dbe-2d394028348f](https://user-images.githubusercontent.com/43033220/73375872-41d40700-429b-11ea-87ed-5ba6927cfee9.jpg)

**Comment by edwardoliveira** [comment]
Sim, foi. Mas a modificação só se encontra na versão 3.1.160-RC11. Se tudo der certo, até semana que vem sai a versão final do 3.1.160.

**Comment by edwardoliveira** [comment]
Vc está na versão 3.1.159. Aí não vai aparecer mesmo.
