### ISSUE TITLE
[Dúvida] Padrão de código de barras adotado pelo SAPL

### ISSUE THREAD

**Issue by rkhaotix** [interlegis/sapl#3088]
Boa tarde. 

Estamos com um alto volume de proposições sendo enviados e o setor responsável não está conseguindo acompanhar. Então para facilitar o trabalho deles estamos organizando a compra de  leitoras de código de barras, para tanto, gostaria de saber dos senhores qual é o padrão utilizado na geração de código de barras no SAPL? 

Adicionalmente, vocês têm algum modelo que já é certo que funcionam sem problemas no sistema?

Obrigado.

**Comment by sesostris** [comment]
Boa tarde,

As issues do github são para reportar bugs (erros do sistema) e para propor melhorias ou novas funcionalidades. Dúvidas sobre como utilizar as funcionalidades existentes devem ser encaminhadas para a lista GITEC (inscreva-se na lista em colab.interlegis.leg.br e envie um e-mail com a dúvida).
