### ISSUE TITLE
Erro de grafia em template de parlamentar

### ISSUE THREAD

**Issue by rkhaotix** [interlegis/sapl#3089]
A tabela onde se lista os parlamentares da Casa Legislativa tem erro de grafia em duas colunas *Parido* e *Titlar* ao invés de *Partido* e *Titular*. Eu até encontrei onde estão os erros (no meu ambiente é ```/var/interlegis/sapl/sapl/templates/parlamentares```) mas alterando os arquivos não causa nenhum efeito. Como posso aplicar as alterações até que a correção oficial seja feita? Obrigado.

## Imagens do Ocorrido
![sapl_titlar_parido](https://user-images.githubusercontent.com/2205476/73842301-0eddc600-47fb-11ea-8e5c-12f9e0a0fd4f.png)

## Seu Ambiente
* Versão usada (_Release_): 3.1.160-RC11
* Nome e versão do navegador: Versão 79.0.3945.130 (Versão oficial) 64 bits
* Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 18.04.3 LTS

**Comment by ulyssesBML** [comment]
Já foi resolvido, nas próximas atualizações já vai esta concertado.
