### ISSUE TITLE
Na versão Release: 3.1.160-RC11 do SAPL ao editar o parlamentar e deixar ele inativo, ele continua aparecendo como ativo na listagem

### ISSUE THREAD

**Issue by jonasrn** [interlegis/sapl#3101]
Na versão Release: 3.1.160-RC11 do SAPL ao editar o parlamentar e deixar ele inativo, ele continua aparecendo como ativo na listagem.
## Comportamento Esperado

Ao desativar um parlamentar deveria aparecer na listagem de parlamentares ele como inativo

## Comportamento Atual
Ao desativar um parlamentar ele continua na listagem como ATIVO

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Imagens do Ocorrido

![1](https://user-images.githubusercontent.com/2423695/74264360-4e1a8400-4cdf-11ea-8a18-47cd98e0abf0.png)
![2](https://user-images.githubusercontent.com/2423695/74264361-4eb31a80-4cdf-11ea-8998-70b8c04a895c.png)

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by ulyssesBML** [comment]
Isso já foi resolvido, quando seu SAPL for atualizado esse problema não existira mais.
