### ISSUE TITLE
Usar crud em Norma

### ISSUE THREAD

**Issue by eduardoedson** [interlegis/sapl#311]

**Comment by edwardoliveira** [comment]
@eduardoedson Esta issue não é uma duplicação (ou nova incursão) de #17? E também não tem a ver, mesmo que indiretamente, com #145? Vamos olhar isso juntos amanhã, ok? :)

**Comment by eduardoedson** [comment]
A #17 era fazer as telas porque não tinha nada, essa #311 é para usar o CRUD do mazza. Na #145 precisa do detail das normas.

**Comment by edwardoliveira** [comment]
👍☺️

**Comment by edwardoliveira** [comment]
+1. :+1:

**Comment by LeandroRoberto** [comment]
Ao aplicar o Crud... esta url (https://github.com/interlegis/sapl/blob/master/norma/urls.py#L22) foi perdida... bem como a opção no menu de detalhe que chama o texto e as funcionalidade de compilação.
