### ISSUE TITLE
Receber Proposições - Erro 500 Registro de Incorporação - Regime de tramitação -> Normal

### ISSUE THREAD

**Issue by ksrenan** [interlegis/sapl#3110]
Receber Proposições - Ocorreu um erro inesperado! Erro 500 Registro de Incorporação - Regime de tramitação -> Normal

## Comportamento Esperado

Menu: protocolo>Receber proposições>Proposições Não Recebidas
Seleciona a proposição
Na seção Registro de Incorporação
Opção Regime de tramitação* -> Normal
Ao clicar no botão incorporar
Mensagem de sucesso em verde na tela.

## Comportamento Atual

Menu: protocolo>Receber proposições>Proposições Não Recebidas
Seleciona a proposição
Na seção Registro de Incorporação
Opção Regime de tramitação* -> Normal
Ao clicar no botão incorporar
mensagem de erro: Ocorreu um erro inesperado! Erro 500
LOG do Docker:
sapldb_1  | 2020-02-18 17:22:27.103 UTC [51754] ERROR:  duplicate key value violates unique constraint "protocoloadm_protocolo_numero_ano_ed766469_uniq"
sapldb_1  | 2020-02-18 17:22:27.103 UTC [51754] DETAIL:  Key (numero, ano)=(14002, 2020) already exists.
sapldb_1  | 2020-02-18 17:22:27.103 UTC [51754] STATEMENT:  INSERT INTO "protocoloadm_protocolo" ("numero", "ano", "data", "hora", "timestamp_data_hora_manual", "user_data_hora_manual", "ip_data_hora_manual", "timestamp", "tipo_protocolo", "tipo_processo", "interessado", "autor_id", "assunto_ementa", "tipo_documento_id", "tipo_materia_id", "numero_paginas", "observacao", "anulado", "user_anulacao", "ip_anulacao", "justificativa_anulacao", "timestamp_anulacao") VALUES (14002, 2020, NULL, NULL, '2020-02-18T17:22:27.102468+00:00'::timestamptz, '', '', '2020-02-18T17:22:27.102482+00:00'::timestamptz, 1, 1, 'Gilberto Mello', 146, 'Ao Poder Executivo, que através da Secretaria Competente, realize estudos técnicos para melhorias de escoamento de água na Rua Alameda Artex, entre as ruas Sezinando Ferreira da Cruz e Noel Gomes de Almeida.', NULL, 6, NULL, '', false, '', '', '', NULL) RETURNING "protocoloadm_protocolo"."id"

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Seu Ambiente

* Versão usada (_Release_): Release: 3.1.160-RC12
* Nome e versão do navegador: Mozilla Firefox 73.0 (64-bit)
* Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 18.04.4 LTS
* Link para o seu projeto (Caso de fork deste projeto): sapl.cmsjp.pr.gov.br/

**Comment by edwardoliveira** [comment]
Em geral esse tipo de erro ocorre na incorporação porque alguém mudou a geração de números de protocolo na configuração da aplicação. O sistema tá reclamando que aquele protocolo já existe, especificamente o 14002/2020.

`sapldb_1 | 2020-02-18 17:22:27.103 UTC [51754] DETAIL: Key (numero, ano)=(14002, 2020) already exists.`

**Comment by edwardoliveira** [comment]
@ksrenan Se o erro ainda persiste, favor reabrir essa issue.

**Comment by ksrenan** [comment]
Em contato com o suporte do Interlegis foi me passado o seguinte procedimento que resolveu o problema:
"Vimos um problema semelhante no passado em uma casa que hospedávamos aqui. 
A configuração de geração de número de protocolo foi alterada. Por isto, números duplicados podem estar sendo gerados, causando este erro. 
Na próxima Release o erro será melhor tratato e acreditamos que o problema não irá mais acontecer ou então exibirá uma mensagem de erro melhor explicada.. No seu caso acreditamos que seja necessário voltar a configuração de numeração para a anterior.
Sistema > Tabelas Auxiliares > Configurações da aplicação > Sequência de numeração de protocolos."
Aqui isso resolveu o problema.
Obrigado.
