### ISSUE TITLE
Personalizar perfil de usuário

### ISSUE THREAD

**Issue by rjoao** [interlegis/sapl#3111]
Solicitação de usuário: [Chamado #262915](https://suporte.interlegis.leg.br/scp/tickets.php?id=34935)

## Comportamento Esperado

Possibilidade de criar e personalizar um perfil de usuário e suas permissões.
"Exemplo: Um usuário que tenha permissão apenas para lanças a ordem do dia."

## Comportamento Atual

Não é possível. Os perfis estão predefinidos.

**Comment by eribeiro** [comment]
Isso já é possível de ser feito pela interface `admin`. 

@LeandroJatai eu percebi que se reiniciar o container ele reseta as permissões dos perfis padrão (operador matéria, operador sessão, etc). Sabe me dizer se ele apaga as novas roles criadas?

**Comment by LeandroJatai** [comment]
@edwardoliveira, o post_migrate reestrutura apenas os perfis padrão, portanto:
- não interfere nas associações entre usuários e esses perfis;
- não interfere em perfis criados por usuários/admins;
- não interfere em permissões associadas isoladamente a usuários.

a ideia da app rules foi fixar os perfis defaults e deixar o admin livre para criar novos perfis e/ou associar permissões isoladamente de acordo com sua administração.

**Comment by andreagudo** [comment]
Considerar #2535
