### ISSUE TITLE
Implementar possibilidade de inclusão de figuras na compilação de normas

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3115]
## Comportamento Esperado
Que seja possível incluir figuras nos dispositivos.

## Comportamento Atual
Não tem sido possível.

## Contexto
Compilação de normas.

## Seu Ambiente
Versão usada (Release): 3.1.160-RC11
Nome e versão do navegador: Versão 79.0.3945.79 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by LeandroJatai** [comment]
#279
