### ISSUE TITLE
Bug painel eletrônico sessão 

### ISSUE THREAD

**Issue by IsaacCastro** [interlegis/sapl#3116]
O nome dos vereadores estão sendo exibidos de forma duplicada no painel eletrônico da sessão, conforme print abaixo:
![Screenshot_20200303-212943_Chrome](https://user-images.githubusercontent.com/43033220/75833238-2f1b8900-5d97-11ea-9dd8-dbbc06c95452.jpg)

* Versão usada: 3.1.160-RC10

**Comment by edwardoliveira** [comment]
Vc saberia me dizer se esse problema também ocorre na versão RC13?

**Comment by IsaacCastro** [comment]
Não, porque minha versão é RC10
