### ISSUE TITLE
View de mesa diretora quebrada

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#3142]
## Comportamento Esperado
Poder escolher parlamentares para compor a mesa diretora

## Comportamento Atual
Não aparece opções para inclusão de parlamentar para composição da mesa

## Imagens do Ocorrido

![mesa-diretora](https://user-images.githubusercontent.com/1524415/79505427-bc92ff80-800a-11ea-8709-882f5bae8040.png)

![parlamentares](https://user-images.githubusercontent.com/1524415/79505560-eea46180-800a-11ea-9072-ff461c5a2099.png)

## Seu Ambiente

* Versão usada (_Release_): 3.1.160 (Estável)

**Comment by edwardoliveira** [comment]
Qual a última versão que vc rodou? 3.1.159?

**Comment by puera** [comment]
@edwardoliveira sim , última versão estável 3.1.159

**Comment by rjoao** [comment]
O problema foi identificado e solucionado. Em breve, estará disponível uma versão que contenha a correção.

**Comment by puera** [comment]
@rjoao mesmo com o HOT-FIX ainda continua quebrada , apareceu a mesa , porém nao tem como modificar e o select de legislatura não está exibindo corretamente as mesas

**Comment by rjoao** [comment]
Você está testando direto no repositório?

**Comment by puera** [comment]
> Você está testando direto no repositório? O que há de errado na exibição?

ela voltou a exibir depois do HOT-FIX , só que os filtros (Selects) não estão surtindo nenhum efeito , ou seja , só aparece a mesa diretora atual

**Comment by edwardoliveira** [comment]
Eu atualizei os assets JS/CSS do branch 3.1.x. Poderia testar pra ver se o erro nessas issues (esta, #3143, #3144) ainda ocorre?
