### ISSUE TITLE
Painel eletrônico não carrega dados da sessão 

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#3143]
## Comportamento Esperado
Carrega os cronômetros e dados da sessão no painel eletrônico

## Comportamento Atual
Nenhum dado é carregado 

## Imagens do Ocorrido
![cronometro](https://user-images.githubusercontent.com/1524415/79507220-b9e5d980-800d-11ea-9588-bd15c27dbf4b.png)

![painel](https://user-images.githubusercontent.com/1524415/79507274-d7b33e80-800d-11ea-809c-41f8aea023dc.png)

## Seu Ambiente

* Versão usada (_Release_): 3.1.160 (Estável)
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Acredito que vc precisa reconfigurar os cronômetros na tela de configurações da aplicação. Verifique se após isso surte efeito.

**Comment by puera** [comment]
@edwardoliveira tentei salvar novamente e não surtiu efeito z continua sem tempo e dados da sessão não aparecem no painel

**Comment by edwardoliveira** [comment]
Vc verificou se o migrate rodou com sucesso?

**Comment by puera** [comment]
> Vc verificou se o migrate rodou com sucesso?

Sim , tanto instalação dos requerimentos , migrate e collectstatic

**Comment by edwardoliveira** [comment]
O campo checkbox justamente deve ser o que deve surtir efeito. Esta issue e a issue #3144 me parecem ser erros de consistência de dados, visto que a gente não consegue reproduzir aqui. Poderia testar em um SAPL zerado (incluindo os dados mínimos necessários para testar as duas telas)?

**Comment by edwardoliveira** [comment]
Se puder passar um dump pra gente da tua base, melhor.

**Comment by puera** [comment]
> O campo checkbox justamente deve ser o que deve surtir efeito. Esta issue e a issue #3144 me parecem ser erros de consistência de dados, visto que a gente não consegue reproduzir aqui. Poderia testar em um SAPL zerado (incluindo os dados mínimos necessários para testar as duas telas)?

o SAPL testado é em uma base de teste, não tem praticamente nenhum dado

> Se puder passar um dump pra gente da tua base, melhor.

vou testar usando a base oficial rodando as migrate e testar , se der o mesmo problema já lhe envio a base

**Comment by edwardoliveira** [comment]
Pode enviar essa base de testes também, se preferir.

**Comment by puera** [comment]
@edwardoliveira segue link da base > https://www.mediafire.com/file/f1tqunq2eb2gqcs/sapl/file, assim que baixar por gentileza retirar o link por quetões de segurança (ps: a base já está migrada)

**Comment by cantuariavc** [comment]
Não consegui reproduzir o erro relatado com a base de dados fornecida, @puera .

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21143590/79585968-e863c300-80a6-11ea-963a-d61276f0b3c8.gif)

**Comment by edwardoliveira** [comment]
@puera Pode fechar essa issue também? Pelo que vi semana passada a causa do erro era a mesma que mostrava a opção "Leitura" no select box de adição de matéria legislativa, e que foi consertado pelo @LeandroJatai

**Comment by puera** [comment]
> @puera Pode fechar essa issue também? Pelo que vi semana passada a causa do erro era a mesma que mostrava a opção "Leitura" no select box de adição de matéria legislativa, e que foi consertado pelo @LeandroJatai

@edwardoliveira tudo certo, estou fechando a issue
