### ISSUE TITLE
Campo "apenas leitura" duplicado e box sem efeito

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#3144]
## Comportamento Esperado
Haver apenas uma opção

## Comportamento Atual
Há 2 campos leitura , um no select e outro no checkbox (campo checkbox não está surtindo efeito)

## Imagens do Ocorrido

![select](https://user-images.githubusercontent.com/1524415/79507778-b010a600-800e-11ea-8c15-4557daca204e.png)

## Seu Ambiente

* Versão usada (_Release_): 3.1.160 (Estável)

**Comment by edwardoliveira** [comment]
O campo checkbox justamente deve ser o que deve surtir efeito. Esta issue e a issue #3143 me parecem ser erros de consistência de dados, visto que a gente não consegue reproduzir aqui. Poderia testar em um SAPL zerado (incluindo os dados mínimos necessários para testar as duas telas)?

**Comment by edwardoliveira** [comment]
Favor passar um dump da tua base de dados pra que a gente possa testar.

**Comment by edwardoliveira** [comment]
@puera Limpa o cache do browser e testa esta tela de novo.

**Comment by puera** [comment]
> @puera Limpa o cache do browser e testa esta tela de novo.

sem sucesso , lhe enviei a base de dados em outra issue

**Comment by cantuariavc** [comment]
Não consegui reproduzir o erro relatado com a base de dados fornecida, @puera .

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21143590/79584706-24962400-80a5-11ea-9159-33a2a0916225.gif)

**Comment by puera** [comment]
@cantuariavc @LeandroJatai @edwardoliveira  por acaso a branch 3.1.x do repo sapl-frontend está atualizada? o erro parece que se encontra no sapl-frontend

**Comment by ulyssesBML** [comment]
Acredito que não, pois o sapl frontend não meche com essa pagina.

Não conseguimos simular o erro com o seu banco, como os problemas são relacionados com javascript recomendamos que desligue o servidor e limpe o cache antes de tentar de novo, também se possível testar com outros navegadores.

**Comment by puera** [comment]
> Acredito que não, pois o sapl frontend não meche com essa pagina.
> 
> Não conseguimos simular o erro com o seu banco, como os problemas são relacionados com javascript recomendamos que desligue o servidor e limpe o cache antes de tentar de novo, também se possível testar com outros navegadores.

@ulyssesBML acabei de efetuar o teste, limpei totalmente o a pasta static e desativei o sapl-frontend no .env e voltou a funcionar , ao dar build no sapl-frontend voltou a ocorrer os problemas

**Comment by puera** [comment]
com frontend do próprio repositório
![Captura de tela de 2020-04-17 12-44-41](https://user-images.githubusercontent.com/1524415/79587677-45f90f00-80a9-11ea-9747-421fe172868c.png)

![Captura de tela de 2020-04-17 12-46-00](https://user-images.githubusercontent.com/1524415/79587782-6cb74580-80a9-11ea-9df7-6e1fa96a43bf.png)

com frontend buildado do sapl-frontend

![Captura de tela de 2020-04-17 12-47-25](https://user-images.githubusercontent.com/1524415/79587925-9ff9d480-80a9-11ea-8c5d-25478477c0d0.png)

![Captura de tela de 2020-04-17 12-47-50](https://user-images.githubusercontent.com/1524415/79587958-ab4d0000-80a9-11ea-91bf-a9df2d85cf84.png)

**Comment by puera** [comment]
Ok pessoal executei alguns testes, o problema se encontra no branch 3.1.x no sapl-frontend , o master do sapl-frontend está funcionando normalmente

**Comment by edwardoliveira** [comment]
Como assim? Poderia ser mais específico? 

Vc se certificou de que todos os dois projetos, sapl e sapl-frontend, estão executando no mesmo branch? Se vc mudou para o master somente do sapl-frontend e o sapl continuou no 3.1.x e funcionou então tua instalação pode estar com algum problema.

Vc chegou a testar a imagem Docker?

**Comment by LeandroJatai** [comment]
@puera seu sapl_frontend é customizado... ouve mudanças no oficial... vc tem acompanhado!? feito os merges necessários!? aí é contigo!!!

**Comment by puera** [comment]
> Como assim? Poderia ser mais específico?
> 
> Vc se certificou de que todos os dois projetos, sapl e sapl-frontend, estão executando no mesmo branch? Se vc mudou para o master somente do sapl-frontend e o sapl continuou no 3.1.x e funcionou então tua instalação pode estar com algum problema.
> 
> Vc chegou a testar a imagem Docker?

@edwardoliveira o que funcionou foi , Repo sapl: 3.1.x com repo sapl-frontend: master
o problema aconteceu com repo sapl: 3.1.x com sapl-frontend: 3.1.x

Não testei com docker

**Comment by puera** [comment]
> @puera seu sapl_frontend é customizado... ouve mudanças no oficial... vc tem acompanhado!? feito os merges necessários!? aí é contigo!!!

sim de fato meu sapl-frontend é custom , mas os testes efetuados foram exatamente o que esta no repositório , ou seja, repositório zerado e atualizado

**Comment by LeandroJatai** [comment]
```
@edwardoliveira o que funcionou foi , Repo sapl: 3.1.x com repo sapl-frontend: master
o problema aconteceu com repo sapl: 3.1.x com sapl-frontend: 3.1.x
```
deve ter commit invertido então!

**Comment by edwardoliveira** [comment]
Mas não seria o caso do Puera entrar no branch `3.1.x` do `sapl-frontend` e rodar `yarn run build`, estando o `sapl` no branch 3.1.x também?

**Comment by puera** [comment]
> Mas não seria o caso do Puera entrar no branch `3.1.x` do `sapl-frontend` e rodar `yarn run build`, estando o `sapl` no branch 3.1.x também?

sim , é exatamente esse problema que ocorre quando builda o sapl-frontend no branch 3.1.x com o branch sapl 3.1.x (isso tratando que os repos estão totalmente atualizados)

A questão é , ao buildar o sapl-frontend vocês estão usando o master? por que ele esta com 22 comits a frente do 3.1.x

**Comment by edwardoliveira** [comment]
> A questão é , ao buildar o sapl-frontend vocês estão usando o master? 
Não usamos o master. Nem vc deveria. Pra todos os efeitos, esquece o master, por enquanto. O que a gente faz lá é colocar funcionalidades pra uma versão futura do SAPL, coisas que não entrarão no 3.1.x. Por isso ele tem commits na frente em ambos os repos: sapl-frontend e sapl.

**Comment by puera** [comment]
> > A questão é , ao buildar o sapl-frontend vocês estão usando o master?
> 
> Não usamos o master. Nem vc deveria. Pra todos os efeitos, esquece o master, por enquanto. O que a gente faz lá é colocar funcionalidades pra uma versão futura do SAPL, coisas que não entrarão no 3.1.x. Por isso ele tem commits na frente em ambos os repos: sapl-frontend e sapl. **Não se deve rodar o master de um repo com 3.1.x do outro repo.**

Certo, porém só ele que funcionou, talvez possa ter algum problema de commit que o @LeandroJatai mencionou no branch 3.1.x

**Comment by edwardoliveira** [comment]
> Certo, porém só ele que funcionou, talvez possa ter algum problema de commit que o @LeandroJatai mencionou no branch 3.1.x

Aí que tá, se fosse o caso a gente conseguiria replicar o erro aqui. E a gente não tá conseguindo até o momento replicar o problema que vc tá tendo. Pode ser que em algum momento teus repos ficaram inconsistentes.  Eu aconselho vc baixar dois repos originais e testar neles, sem customização alguma, usando os branches corretos (3.1.x) no caso. Se funcionar aplica tuas customizações por cima e testa novamente.

**Comment by puera** [comment]
@edwardoliveira foi exatamente que eu fiz , eu baixei os repos (sapl e sapl-frontend) do zero, não apliquei nada custom , e deu o erro , você pode ver que a imagem da issue é justamente o front original

**Comment by puera** [comment]
Pra ficar claro o que eu fiz:

1 - clonei repo sapl
2 - clonei repo sapl-front (ambos estão na mesma pasta interlegis)
3 - entrei na pasta sapl-frontend , instalei todas as depedencias com o yarn , depois yarn build
4 - entrei na pasta sapl, configurei normalmente o .env e dei um collectstatic
5 - ao abrir a pagina , o front está lá , porém operações que usam o javascript parece que ficam quebradas 

se eu apagar tudo que foi feito pelo build do sapl-frontend e usar o collecstatic novamente sem buildar nada, o front volta a funcionar.

**Comment by edwardoliveira** [comment]
> A única forma que funcionou é nem usar o sapl-frontend, simplesmente usar o que está buildado por padrão no repositório sapl

Sim, também tem isso. Vc não precisa usar o sapl-frontend se não estiver desenvolvendo na da na parte do sapl-frontend. Nem na instalação. Eu raramente uso o sapl-frontend, a não ser que precise adicionar alguma nova lib JavaScript, ou um outro CSS.

**Comment by puera** [comment]
> > A única forma que funcionou é nem usar o sapl-frontend, simplesmente usar o que está buildado por padrão no repositório sapl
> 
> Sim, também tem isso. Vc não precisa usar o sapl-frontend se não estiver desenvolvendo na da na parte do sapl-frontend. Nem na instalação. Eu raramente uso o sapl-frontend, a não ser que precise adicionar alguma nova lib JavaScript, ou um outro CSS.

sim mais no meu caso eu tenho uma custom de cores do sapl então eu preciso editar pelo sapl-frontend, pra buildar com a configuração de css que eu tenho

**Comment by edwardoliveira** [comment]
Infelizmente nesse caso eu não sei como te ajudar. Talvez o @LeandroJatai saiba.

**Comment by puera** [comment]
> Se vc está **instalando** o SAPL não precisaria do passo 3. Me parece que vc está misturando instalação com ambiente de desenvolvimento.

Antigamente a View era acoplado ao projeto SAPL ( nesse caso eu trabalhava diretamente no estilos), quando teve a desacoplamento do front para Vue.js, ele fica responsável por buildar só o frontend ( eu não consigo / nem posso mexer nos arquivos mimificados do sapl) 

> Infelizmente nesse caso eu não sei como te ajudar. Talvez o @LeandroJatai saiba.

@edwardoliveira  esquenta a cabeça não , continuando com meu custom eu uso o master do sapl-frontend que está funcionando e vou me virando, mas fica de alerta pra quem for trabalhar com o branch 3.1.x do sapl-frontend está enfrentando esses erros

**Comment by edwardoliveira** [comment]
@puera se vc puder fazer um fork do sapl-frontend com as tuas customizações inclusas, a gente pode fazer um clone desse repo e tentar rodar pra ver se reproduzimos o erro aqui. Ou, sei lá, compactar esses dois diretórios e disponibilizar um link pra gente baixar.

**Comment by puera** [comment]
> @puera se vc puder fazer um fork do sapl-frontend com as tuas customizações inclusas, a gente pode fazer um clone desse repo e tentar rodar pra ver se reproduzimos o erro aqui. Ou, sei lá, compactar esses dois diretórios (sapl e sapl-frontend) e disponibilizar um link pra gente baixar.

@edwardoliveira segue o fork com o sapl-frontend 3.1.x buildado no sapl 3.1.x

**Comment by edwardoliveira** [comment]
Não foi isso que eu pedi: foi um fork do repo do sapl-frontend. Tudo bem, deixa pra lá, provavelmente não vai nos ajudar tanto.

Poderia fazer o seguinte teste?
1. Execute os seguintes comandos no repo do `sapl` (branch `3.1.x`): `git clean -df` e `git reset --hard HEAD`

2. No repo `sapl-frontend` (branch `3.1.x`) altere o arquivo `package.json` e altere a entrada abaixo da versão 4.9.7 para 4.9.2
"tinymce": "^4.9.7",

3. Rode os comandos de `yarn install` e depois `yarn run build`

4. Inicie o servidor do SAPL

5. Limpe os caches do browser e teste de novo.

**Comment by LeandroJatai** [comment]
@puera @edwardoliveira ... por favor, testem o interlegis/sapl:3.1.x com as atualizações de frontend feitas ainda a pouco... interlegis/sapl-frontend:master ainda não foi refatorado... não faça cherry-pick... para reparar o ambiente de dev de frontend de vocês, exclua a pasta node_modules e rode `yarn install`. yarn.lock deve versionado como adicionado agora e não apagado... yarn.lock faz com que todos os ambientes de desenvolvimento sejam idênticos.

**Comment by puera** [comment]
@LeandroJatai com essa sua atualização nos pacotes não vou conseguir usar o node 32bits 8.15 (o servidor é uma maquina antiga e não suporta 64 bits ) , ao tentar instalar as dependências ele pede a versão 10.13.0 ou superior , e não tem essa versão ou pra cima pra linux 32bits.
Mais é uma limitação da estrutura do meu trabalho, vou ter que por outra maquina que suporte essa arquitetura.
Eu vou instalar uma maquina virtual 64 bits para testar e lhe retorno com o feedback

**Comment by LeandroJatai** [comment]
vou avaliar... essa exigência tem que vir em último recurso...

**Comment by LeandroJatai** [comment]
é... realmente... é uma limitação não para a produção mas para o dev... atualizei vue-cli versão 4.3.1... meu servidor de produção é 32bits e o sapl de testes está funcionando normalmente com o build... como é uma limitação apenas para o dev, não interfere no build e o custo benefício para os demais programadores e para o código de configuração do dev é relevante a ida para a versão 4.3.1, estou mantendo o package.json como se encontra!

**Comment by puera** [comment]
@LeandroJatai finalizei a VM aqui, eu tive problema com o ultimo commit do sapl-frontend branch 3.1.x ao rodar o build:

![Captura de tela de 2020-04-24 10-55-57](https://user-images.githubusercontent.com/1524415/80220660-8d881980-861a-11ea-8a0c-ebf04e5d61d1.png)

dei um revert no seu ultimo commit ( feb117b0 )  e voltou a buildar 



> é... realmente... é uma limitação não para a produção mas para o dev... atualizei vue-cli versão 4.3.1... meu servidor de produção é 32bits e o sapl de testes está funcionando normalmente com o build... como é uma limitação apenas para o dev, não interfere no build e o custo benefício para os demais programadores e para o código de configuração do dev é relevante a ida para a versão 4.3.1, estou mantendo o package.json como se encontra!

Sim, podemos da build em uma VM e enviar isso pra produção , acabei pensando nisso também!

**Comment by LeandroJatai** [comment]
apaga node_modules e roda novamente "yarn install".... com esse build: https://github.com/interlegis/sapl-frontend/commit/feb117b02227254027905d928d381a1c76d1253d

**Comment by LeandroJatai** [comment]
eita.... deu pau mesmo... isso é uma coisa simples de eslint... já resolvo aqui.

**Comment by LeandroJatai** [comment]
@puera testa por favor um novo commit aí

**Comment by puera** [comment]
> @puera testa por favor um novo commit aí

show de bola @LeandroJatai, o branch 3.1.x do sapl-frontend está funcionando normalmente agora com o sapl 3.1.x

**Comment by LeandroJatai** [comment]
oba!!!
