### ISSUE TITLE
Períodos de parlamentares sumiram

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3148]
## Comportamento Esperado
Devem aparecer todos os períodos dos parlamentares, correspondentes às legislaturas.

## Comportamento Atual
Aparecem apenas da 6ª legislatura à atual.

Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/parlamentar/

## Contexto
Pesquisa de parlamentares por legislatura.

## Imagens do Ocorrido
![Captura de tela de 2020-04-22 08-08-12](https://user-images.githubusercontent.com/19169882/79975386-4579c300-8471-11ea-95b9-96459516774f.png)

## Seu Ambiente
Versão usada (Release): 3.1.160-RC11
Nome e versão do navegador: Versão 80.0.3987.163 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
Existia uma limitação na quantidade máxima de legislaturas que a API do SAPL estava trazendo sem paginação. Consertamos isso e na próxima versão essa semana esse erro não mais aparecerá.
