### ISSUE TITLE
Pauta das Sessões

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#3149]
Verificando as informações que são apresentadas no menu "Pauta das Sessões" em matérias do expediente e matérias da ordem do dia é mostrada a coluna "situação".

A informação mostrada nessa coluna é sempre da ultima tramitação da matéria.

O que ocorre, é que quando da consulta de sessões anteriores,  onde a matéria já tramitou, a informação apresentada não reflete o que aconteceu naquela pauta da sessão.

## Comportamento Atual

![image](https://user-images.githubusercontent.com/13314947/80004684-02334a80-8499-11ea-9d49-b40a4efbbe0a.png)

## Possível Solução

sugiro que seja tirada essa coluna "situação" da Pauta das Sessões.

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Seu Ambiente

* Versão usada (_Release_): Release: 3.1.160
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
<img width="954" alt="Screen Shot 2020-06-29 at 10 15 50" src="https://user-images.githubusercontent.com/9326037/86010261-881bc680-b9f1-11ea-8a5c-dbb4d444b235.png">

@DtiLegBG  Tá vendo porque é complicado retirar campos e telas do SAPL? Pra alguma pessoa sempre é importante.

**Comment by edwardoliveira** [comment]
Revertido pelo commit 567ee6371dbf79a9d9ed043f1482ce070cf2da29 a pedido de outros usuários do SAPL.

**Comment by DtiLegBG** [comment]
Entendo, mas não foi uma decisão sem consultar a comunidade.
![image](https://user-images.githubusercontent.com/13314947/86170833-1e371600-baf2-11ea-961a-fc272392b711.png)

**Comment by edwardoliveira** [comment]
Eu tentei convencer a pessoa desta casa a manter do jeito que está, isto é, sem esta coluna. Por mim não tem problema nenhum tirar. O problema é que parte dos usuários age como comunidade -- o que é o correto visto que é software livre -- e outra parcela, que eu suspeito seja maior, age como usuário/cliente com demandas urgentes e as vezes únicas. 

A casa é essa:
  Nome da Cidade: | Carlos Barbosa
  Estado: | Rio Grande do Sul

e a pessoa que abriu o ticket no OSTicket se chama __Wiliam Irani Giacomelli__. Tente conversar com ele, pra ver se convence a deixar sem essa coluna. Eu tentei convencer a pessoa a deixar como está, isto é, sem a coluna, mas não consegui. Em geral, eu consigo convencer a seguir a maioria da comunidade, mas atualmente estou cansado de ter que ficar contra-argumentando. Conseguir mais gente da comunidade pra embasar essa decisão de deixar sem a coluna me ajuda bastante a embasar esse tipo de mudança.

**Comment by puera** [comment]
@edwardoliveira  a meu ver e boa parte dos usuários da câmara onde eu trabalho concordaram não ter essa coluna, a pauta de sessão é sucinta , com informações de matérias do dia , essa coluna "Situação" já se encontra em resumo de sessão plenária e não faz sentido ficar em "Pauta" .... a comunidade deveria entender que existe hoje a opção de resumo de sessão , que nem era usado pelo fato de ter essa informação duplicada na pauta.

**Comment by edwardoliveira** [comment]
Bom, eu posso reverter o revert e pedir pra pessoa entrar na lista do GITEC e discutir isso com vcs lá. Se houver algum consenso eu coloco de novo ou deixo sem. Agora precisa que mais __casas__ se manifestem!

**Comment by puera** [comment]
@edwardoliveira acabei de ver aqui e me confundi , o campo situação não está e sim o resultado da votação, o que poderia ser estudado seria, migrar esse campo situação para o resumo de sessão, que no caso ficaria o resultado da votação mais a situação atual daquela matéria, e deixar a Pauta somente com a matéria e ementa , fica aqui uma ideia

**Comment by DtiLegBG** [comment]
@edwardoliveira , conversei com o pessoal da Câmara de Carlos Barbosa, eles argumentam o seguinte "Queremos comentar que para nós seria importante o acesso a situação da proposição até a data da votação, pois também colocamos na Ordem do Dia, os projetos que baixam para análise das comissões. Assim, sem a situação, quando o munícipe entrar na pauta não saberá, qual proposição será votada e qual apenas foi protocolada e ainda estará em análise.Mas entendo o ponto que você colocou no e-mail em relação às pautas das sessões anteriores, por isso seria bom verificar o que os demais falaram sobre, até mesmo para avaliarmos se a forma como fazemos está correta, para ajustar nosso Regimento e nossa dinâmica caso necessário. "

**Comment by edwardoliveira** [comment]
Bom, muito bom! Obrigado @DtiLegBG pela iniciativa! 🙏  Assim, se precisar de uma tela/relatório a gente pode fazer e disponibilizar sem problema pra eles. O que acha dessa ideia? Se vc puder ver com ele o que mais teria nesse relatório podemos fazer e disponibilizar já na semana que vem.

**Comment by DtiLegBG** [comment]
@edwardoliveira , pensamos no seguite: Sempre que a sessão estiver com o status "Sessão Finalizada = Não" nos seus dados básicos, a coluna é mostrada, se o status for "Sessão Finalizada = Sim"  então a coluna deixa de ser mostrada. O que acha?
