### ISSUE TITLE
Integrar infra de hospedagem ao SEIT

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#315]
Integrar a infra feita em #138 aos processos do SEIT (setor responsável pela infra do Interlegis), considerando, p. ex., a estrutura de cloud montada recentemente.

Trabalhar com @fabiorauber.

**Esta tarefa deve ser considerada feita** quando o SEIT for capaz de criar **sozinho** uma instância do sapl 3.1 de produção, como se estivesse atendendo a solicitação de uma casa legislativa.

**Comment by eduardoedson** [comment]
Relacionada a #375

**Comment by eliseuegewarth** [comment]
Resolvido em #1023
