### ISSUE TITLE
Faltam Vereadores na 15ª legislatura

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3154]
## Comportamento Esperado
Na lista de parlamentares devem aparecer todos os Vereadores, inclusive suplentes que assumiram.

## Comportamento Atual
Os Vereadores Carlito, Auro e Rosa, todos suplentes que já atuarem na legislatura, não aparecem. Porém, os suplentes Izabel e Sandro aparecem.

Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/parlamentar/

## Contexto
Pesquisa de parlamentares por legislatura.

## Seu Ambiente
Versão usada (Release): 3.1.160-RC11
Nome e versão do navegador: Versão 81.0.4044.122 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
Esses parlamentares estão sem fim de mandato cadastrado. Vá em Pesquisar Parlamentar e digite o primeiro nome dele, depois vá em mandato e edite colocando um final de mandato no mandato da última legislatura.
