### ISSUE TITLE
Sessão Plenária / Resumo / Impressão em PDF 

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#3155]
Em impressão de PDF do resumo da sessão plenária estão sendo mostrados os tipos de expediente que não tem nada cadastrado para aquela sessão.

No resumo está correto, são mostrados apenas os que tem algo cadastrado para a sessão
![image](https://user-images.githubusercontent.com/13314947/81591391-bdf9e280-9392-11ea-9646-6d7d4ff6c1c9.png)

Em PDF também deveriam ser ocultados
![image](https://user-images.githubusercontent.com/13314947/81591483-e1249200-9392-11ea-8cc8-8f9354f96318.png)

## Comportamento Esperado

No PDF os expedientes que não tem nada cadastrado para a sessão deveriam ser ocultados

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Seu Ambiente

* Versão usada (_Release_): Release: 3.1.160
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by puera** [comment]
Esse comportamento acontece em "Pautas das Sessões" ... campos que não são preenchidos e aparecem em tela do SAPL e no PDF: Issue #3156
