### ISSUE TITLE
Inabilitação de recursos textos articulados

### ISSUE THREAD

**Issue by IsaacCastro** [interlegis/sapl#3167]
## Comportamento Atual
Na edição de textos articulados, percebi que quando se utiliza o editor Tinymce para trabalhar cópia externa de textos com formatação, fica desabilitado o recurso de Aumentar e diminuir texto. O que a meu ver perde bastante usabilidade.
![image](https://user-images.githubusercontent.com/43033220/83039177-35c34080-a014-11ea-94e4-3574611a94b2.png)

## Link para verificação do erro
https://sapl.saojosedodivino.pi.leg.br/ta/25/text?

## Comportamento Esperado
Espera-se que independente da forma de edição escolhida pelo operador (editor simples ou avançado), o sistema ofereça o recurso de aumentar ou diminuir a fonte

**Comment by IsaacCastro** [comment]
Foi implementada essa solicitação #3167.? Continuo com o mesmo problema aqui.

**Comment by LeandroJatai** [comment]
Por aqui os botões estão aparecendo normalmente...
acessado em: https://sapl.saojosedodivino.pi.leg.br/ta/25/text

infelizmente o preço que se paga ao usar tinymce é que dependendo da forma que suas funcionalidades foram acionadas, ele fixa o tamanho da fonte... aí os botões "a" e "A" não conseguem manipular visto que é uma relação simples de percentuais de tamanho e tamanhos fixos foge dessa abordagem...

conforme imagens abaixo:
![image](https://user-images.githubusercontent.com/9630623/98272103-73d37180-1f6f-11eb-987d-3837573c82a0.png)

![image](https://user-images.githubusercontent.com/9630623/98272219-9b2a3e80-1f6f-11eb-9d81-7c8137892234.png)

**Comment by IsaacCastro** [comment]
Sim, os botões estão funcionando a questão como você colocou é o uso do Tinymce. Se entendi, o fato é que o Tinymce é um editor externo e por isso não se consegue manipular sua fontes, né isso?

Quanto vc diz "dependendo como suas funcionalidade são acionadas", seja mais claro! Porque fiquei com dúvida se há possibilidade de se usar apenas determinadas funcionalidade e ser possível manipular suas fontes.

**Comment by LeandroJatai** [comment]
Fiz um vídeo: https://youtu.be/03JaufMgb5U

**Comment by IsaacCastro** [comment]
Poxa Leandro, primeiro te agradecer pelo video, muito esclarecedor.

Vou aplicar e orientar o pessoal aqui da Casa, quanto a essas ideias de limpeza de texto para colagens no SAPL, a exemplo do que já faço no portal modelo. Estamos dando os primeiros passos nesse nicho de texto articulado, porque é um trabalho maçante.

Quanto às formatações de trechos da Norma, mesmo não sendo ipsis litteris, são as mesmas às vezes inevitáveis, sob pena de a grande massa textual dificultar até mesmo a leitura.

Fiz alguns testes usando o próprio bloco de notas pra depois jogar o texto no tinymce e pareceu convincente, as configurações
style foram automaticamente aplicadas, inclusive fonte e tamanho 1.15em da folha de estilo e alcance das configs de zoom, ou seja tive um padrão do corpo do texto (que é minha preocupação).

Agora claro, estamos falando de um texto corrido. Imagina trabalhar uma tabela seja ela simples ou complexa, ai o negócio é "mais em baixo", ou faço diretamente no editor de tabela do tinymce (o que é trabalhooooosso) e às vezes impossível, ou opto por usar alguma formatação mínima de um editor externo (sob pena de perder algumas características de experiência para o usuário).
