### ISSUE TITLE
Listar forms de busca feitos sem o django-filter

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#317]
Listar todos nessa issue

**Comment by edwardoliveira** [comment]
Só tem dois! Pesquisa Matéria e pesquisa Protocolo.

**Comment by edwardoliveira** [comment]
PS: sendo que o @eduardocalil fez a Pesquisa Matéria então sobra a de Protocolo. Se tiver mais alguma no 2.5, não foi implementada ainda.
