### ISSUE TITLE
Permitir associar para cada titular da comissão um suplente.

### ISSUE THREAD

**Issue by jonasrn** [interlegis/sapl#3176]
Ao adicionar um participante nas comissões,   só é permitido um suplente por comissão, na casa em que trabalho para cada membro existe um suplente para aquele membro respectivamente.

## Comportamento Esperado

Poder adicionar um suplente para cada membro

## Comportamento Atual

Só permite cadastrar um suplente

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Imagens do Ocorrido

![suplente](https://user-images.githubusercontent.com/2423695/83768030-b0afdb00-a654-11ea-9089-651ace9c7979.png)

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Em Tabelas Auxiliares -> 'Cargo em Comissão', os cargos tem uma coluna chamada 'Único' que diz se o cargo deve ser único ou não. Vc deve colocar esse campo como 'Falso' para que o SAPL permita criar mais de um parlamentar com aquele cargo na comissão.
