### ISSUE TITLE
sapl mobile

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#319]
Avaliar o seguinte:
- Fazemos apps para android, IOS, etc?
- Qual o futuro do app sapl mobile que @LeandroRoberto fez? Ele pode evoluí-lo para uso no sapl 3.1?

**Comment by LeandroRoberto** [comment]
A motivação inicial do SaplMobile foi atender o plenário e,  apesar de
pensar mais alto,  até hoje não passou disso...  Por que decidi por uma app
nativa e não um HTML? Devido a disponibilidade imediata dos arquivos em
PDF... Da forma que foi feita,  todos os arquivos referentes a uma sessão
são baixados para o dispositivo mobile aos abrir o app se assim estiver
configurado... O app não chama todos de uma vez mas faz chamadas aleatórias
até todos serem baixados... Baixar antes é crucial para agilidade no
plenário... Atualmente mesmo com mudanças durante a sessão como um entrada
de projetos de última hora,  retirada ou entrada de emendas esses arquivos
são baixados assim que possível...  Em Jataí usamoa tablets a 2 anos e
meio...  Será inevitável o sapl 3.1 gerar o mesmo XML que o 2.5 gera ou
tudo ser refeito... Nóis junto ou eu sozinho...  Eu por exemplo só migro
para o 3.1 quando os tablets estiverem funcionando com o 3.1

Em seg, 11 de abr de 2016 13:37, Marcio Mazza <notifications@github.com>
escreveu:

> Avaliar o seguinte:
>
>    - Fazemos apps para android, IOS, etc?
>    - Qual o futuro do app sapl mobile que @LeandroRoberto
>    <https://github.com/LeandroRoberto> fez? Ele pode evoluí-lo para uso
>    no sapl 3.1?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/interlegis/sapl/issues/319>
>
-- 
att.
Leandro Roberto Silva
Câmara Municipal de Jataí

**Comment by LeandroRoberto** [comment]
portando diálogo feito pelo telegram nessa data...
Leandro:
rapaaaaaazz... acabo de terminar uma exportação do meu sapl (sem os pdfs) e da minha base de leis compiladas... ta linnndo... se não fosse os tablets eu já colocava sapl 3.1 em produção.

@marciomazza:
o que tá pegando com os tablets? é pq eles usam o sapl mobile?

Leandro:
o que tá pegando com os tablets? 
saplmobile é um appnativo que faz requisições para um pythonscript do sapl3 ou 2.5 que devolve xmls... para o 3.1 terei que desenvolver a app sapl/api no 3.1 e no app mobile converter tudo que lê xml para ler json

 é pq eles usam o sapl mobile?
decisão de projeto... porque os tables usam um app nativo e não uma versão com htmls e css adaptaveis??? também sou a favor de que deve ser nativo se e somente se, existir uma exigência fundamental para o ser... bem, ela existe... os arquivos em pdf de matérias e docs acessórios... o SaplMobile foi feito para dar informações em tempo real para os parlamentares na sessão... isso significa que os pdfs tem que abrir instantaneamente quando os parlamentares quiserem visualizá-los... na minha rede já existia latência para abrir um pdf de 5 ou 10MB... imagina uma casa usando o saplmobile lá no fim do mundo que está hospedado no interlegis... em tempo de discussão e votação é inadmissível esperar download para visualização.

pois bem... saplmobile é nativo para oferecer os pdfs instantaneamente... como? existe uma configuração para download e uma lógica implementada que assim que uma sessão plenária é aberta no app os documentos relativos a aquela sessão começam ser baixados para o tablet... aqui ligamos tablets 30 minutos antes das sessões, com isso quando começa a sessão, todos os arquivos já estão nos tablets... no app existe uma lógica de atualização... se depois de baixado, o arquivo for atualizado ou outros arquivos entrarem no meio  da sessão os tablets são atualizados imediatamente...

**Comment by marciomazza** [comment]
App SAPLMobile:
https://play.google.com/store/apps/details?id=br.leg.interlegis.saplmobile&hl=pt_BR

**Comment by LeandroRoberto** [comment]
SaplMobile sendo implementado para Sapl 3.1 neste repositório:
https://github.com/cmjatai/SaplMobile

funcionalidades no 3.1 que atenderão ao SaplMobile, neste branch:
https://github.com/interlegis/sapl/tree/319-api-sapl_mobile
