### ISSUE TITLE
Filtro para vide em texto compilado

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3227]
## Comportamento Esperado
Deve buscar os dispositivos da norma escolhida no filtro.

## Comportamento Atual
Várias normas são buscadas. Aparentemente está buscando pelo caracter informado no campo número, não propriamente pelo número, pois retorna várias normas com tal caracter nesse mesmo campo.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/ta/52/text?

## Contexto
Adição de vide em texto compilado.

## Imagens do Ocorrido
![Captura de tela de 2020-07-16 08-36-53](https://user-images.githubusercontent.com/19169882/87667239-62f0bd00-c740-11ea-8a0a-026fffdfe829.png)

## Seu Ambiente
Versão usada (Release): 3.1.161-RC2
Nome e versão do navegador: Versão 81.0.4044.138 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by LeandroJatai** [comment]
Olá @andreagudo, este número é textual e o comparativo é feito com a função "contido" e não "igual"... ou seja... o sistema pede para o banco **normas que contenham** no campo número armazenado o que o usuário digitou no formulário->campo_numero... o que vc pede é que o sistema peça para o banco **normas possuam exatamente** no campo número armazenado o que o usuário digitou no formulário->campo_numero...
particularmente não concordo... masssss... 
caso resolvam (vide @edwardoliveira), no arquivo compilacao/views.py aparece apenas uma única vez o código abaixo
```
AND1_NUMERO="AND ta.numero ~* '{}'".format(
                    num_ta) if num_ta else '',
```

só mudar para:
```
AND1_NUMERO="AND ta.numero = '{}'".format(
                    num_ta) if num_ta else '',
```

**Comment by andreagudo** [comment]
Pensei que estivesse ocorrendo um erro. Na minha opinião, a issue pode ser fechada.
