### ISSUE TITLE
Texto Multivigente - Preparar para Impressão quebrado

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#3234]
## Comportamento Esperado
ao clicar em "Preparar para Impressão" ser redirecionado para a página para impressão

## Comportamento Atual
Nada acontece

## Imagens do Ocorrido

![texto multivigente](https://user-images.githubusercontent.com/1524415/88311482-4d9f0400-cce7-11ea-9c40-fad02f3df2a8.png)

## Seu Ambiente

* Versão usada (_Release_):  3.1.161-RC4

**Comment by edwardoliveira** [comment]
@LeandroJatai

**Comment by puera** [comment]
O que acontece que no template text_list__embedded.html em compilacao está com a seguinte URL
` <a href="{{base_url}}?print" class="btn btn-outline-primary" id="btn_impressao">{% trans 'Preparar para impressão' %}</a>`
Como houve uma incorporação no Texto Compilado no início da norma jurídica nas recentes versões do SAPL, esta URL só funcionaria pela aba "Texto Compilado" que aceita o parâmetro ?print pela URL do texto articulado

**Comment by LeandroJatai** [comment]
corrigido em https://github.com/interlegis/sapl/commit/929f7ecbe6281d16b0eff19f40f61ce57b72c2ee
