### ISSUE TITLE
Bug inserção matéria expediente/ordem do Dia das sessões

### ISSUE THREAD

**Issue by IsaacCastro** [interlegis/sapl#3240]
## Problema
Sistema não abre campo de inserção do número da matéria no cadastro de matérias no expediente/Ordem do Dia das sessões.

Consequência: Não está sendo possível cadastrar matérias nas sessões.

![screencapture-sapl-saojosedodivino-pi-leg-br-sessao-162-expedientemateria-create-2020-07-30-17_46_19](https://user-images.githubusercontent.com/43033220/88972977-c88a9080-d28c-11ea-91d6-0be688d7a951.png)

## versão de teste:
Release: 3.1.161-RC4

**Comment by IsaacCastro** [comment]
Essa questão tá acontecendo com outra Câmara? Estou preocupado, porque amanhã (08/08) já temos sessão aqui.

**Comment by rjoao** [comment]
Esse erro é causado pela utilização de uma extensão do Kaspersky. Essa extensão bloqueia alguns campos do SAPL. O que não deveria acontecer. Desative a extensão e tente novamente.
