### ISSUE TITLE
Permitir que o número de matéria legislativa seja alfanumérico

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3243]
## Comportamento Esperado
Que seja aceita numeração alfanumérica, como ocorre com as normas jurídicas.  #729

## Comportamento Atual
Somente são aceitos caracteres numéricos.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/materia/3713/edit
https://sapl.agudo.rs.leg.br/materia/create

## Contexto
Edição ou inclusão de matéria legislativa.

## Seu Ambiente
Versão usada (Release): 3.1.161-RC2
Nome e versão do navegador: Versão 84.0.4147.105 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
Infelizmente, permitir que o número de norma fosse alfa numérico nos trouxe uma série de problemas que ainda hoje não conseguimos resolver direito. Então, **definitivamente isso não cometeremos o mesmo erro com matéria legislativa.**
