### ISSUE TITLE
[Regressão] Edição/preview/remoção de imagem em Casa Legislativa

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#325]
Com a mudança para um model field específico de imagem a funcionalidade de visualizar e remover o logotipo da casa legislativa foi perdido. Como esta tela provavelmente será convertida para CRUD do Mazza então incorporar mudanças semelhantes a de Parlamentares.

**Comment by eduardoedson** [comment]
Relacionado #43

**Comment by eduardoedson** [comment]
Casa legislativa já está com preview, mas não me lembro em qual issue foi feito.

![captura de tela de 2016-04-26 11-16-50](https://cloud.githubusercontent.com/assets/7716450/14821260/784221d6-0ba0-11e6-8f5f-83a078886eee.png)
