### ISSUE TITLE
Refatora pesquisa Protocolo django filter

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#327]
A outra tela -- além de Pesquisa Matéria -- que pode se valer do django-filter e éssa de Pesquisa Protocolo. De fato, ela é até mais simples que a de Pesquisa Matéria em termos de número de campos, valores possíveis, etc.

PS: Lembrando que se existe alguma outra tela -- além dessas duas --, não foi portada para o SAPL31, que eu saiba.

**Comment by edwardoliveira** [comment]
@eduardocalil se vc quiser pegar essa issue, sinta-se a vontade, já q vc fez a outra pesquisa. Não se sinta obrigado, entretanto.

**Comment by edwardoliveira** [comment]
@eduardocalil Vc me pediu pra revisar o #217, mas o @marciomazza estava trabalhando neste ticket, não? Arrumando os commits, e melhorias no código? Acho que ele estava fazendo isso como parte do processo de revisão, mas, caso contrário, eu posso fazer.

**Comment by marciomazza** [comment]
Eu já revisei uma boa parte, @eduardocalil já avançou mas esse ticket tinha bastante coisa.

Se vc puder concluir será ótimo, @edwardoliveira

**Comment by edwardoliveira** [comment]
:+1:
