### ISSUE TITLE
Implementar na Lista de inconsistências as normas sem textos compilados

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3296]
## Comportamento Esperado
Relatório de normas que não tem texto compilado.

## Contexto
Lista de Inconsistências.

## Seu Ambiente
Versão usada (Release): 3.1.161-RC2
Nome e versão do navegador: Versão 84.0.4147.105 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
No meu entender, tudo bem uma norma não tem texto compilado associado. Isso não seria uma inconsistência, visto que não é uma obrigatoriedade. O que acha @LeandroJatai ?

**Comment by andreagudo** [comment]
Não é inconsistência, mas seria bom contar com esse tipo de relatório.
Noutro lugar, quem sabe?

Em qui, 15 de out de 2020 12:32 PM, Edward <notifications@github.com>
escreveu:

**Comment by LeandroJatai** [comment]
fiz há 13 dias... em breve você verá esse menu seu caso tenha permissão de edição de T.A.s
![image](https://user-images.githubusercontent.com/9630623/96167311-94228a00-0ef5-11eb-84cf-1b6691c4b884.png)
