### ISSUE TITLE
Implementar na Lista de inconsistências as normas com textos compilados e não publicados

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3297]
## Comportamento Esperado
Relatório de normas que têm texto compilado, mas não estão publicados.

## Contexto
Lista de Inconsistências.

## Seu Ambiente
Versão usada (Release): 3.1.161-RC2
Nome e versão do navegador: Versão 84.0.4147.105 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by LeandroJatai** [comment]
@rjoao isso já está feito... 3.1.161-RC15 já tem isso
