### ISSUE TITLE
Visualização de Audiências Públicas

### ISSUE THREAD

**Issue by MarceloPasquini** [interlegis/sapl#3315]
Estamos utilizando o módulo de audiências públicas, mas temos várias pessoas que não entendem que ao clicar no número você acesso o conteúdo.
No módulo de sessões plenárias, este problema não acontece, pois pessoa vê o link no nome da sessão e clica para ver o conteúdo.
Existe alguma forma de montar a visualização da sessão plenária com os dados das audiências públicas?
Segue anexo imagens relacionadas.
[VisualizaçãoAudienciaPublica.pdf](https://github.com/interlegis/sapl/files/5523487/VisualizacaoAudienciaPublica.pdf)

https://sapl.saojoaodaboavista.sp.leg.br/

**Comment by cantuariavc** [comment]
Bom dia, Marcelo, a alteração feita foi como está na imagem abaixo. Estará disponível na próxima versão do SAPL que tem como previsão de ser lançada na semana que vem.
<img width="1071" alt="Screen Shot 2020-11-11 at 11 45 25" src="https://user-images.githubusercontent.com/21143590/98825917-d0bda480-2413-11eb-8f41-16a20b495841.png">
