### ISSUE TITLE
Erro ao buildar frontend

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#3327]
## Comportamento Esperado
buildar frontend com sucesso

## Comportamento Atual

retorna o seguinte erro no terminal:

![Captura de tela de 2020-12-18 15-56-21](https://user-images.githubusercontent.com/1524415/102650404-a5805080-4149-11eb-8f78-8b85d4376db9.png)

## Seu Ambiente

* Versão usada (_Release_): 3.1.161

**Comment by puera** [comment]
@LeandroJatai eu vi que foi migrado o frontend para repo principal do sapl e que está tendo manutenção feita por aqui e não no repositório front: https://github.com/interlegis/sapl-frontend, nesse caso o repo do sapl-frontend será descontinuado ?

**Comment by LeandroJatai** [comment]
Isso... Até onde sei o repo sapl-frontend, inclusive, está para ser apagado!

**Comment by puera** [comment]
> Isso... Até onde sei o repo sapl-frontend, inclusive, está para ser apagado!

@LeandroJatai blz , esse erro tá acontecendo quando gera build no próprio repositório sapl, foi adicionado o copy plugin e ao gerar a build da esse erro conforme a imagem, existe alguma variável de ambiente a ser adicionado?

**Comment by LeandroJatai** [comment]
corrigido em https://github.com/interlegis/sapl/commit/94549985471f600b38fe98361515f3445b92eefb
