### ISSUE TITLE
Erro ao adicionar nova legislatura

### ISSUE THREAD

**Issue by cintiaelisa** [interlegis/sapl#3330]
Está aparecendo Erro 500 ao tentar adicionar uma nova legislatura.
## Comportamento Esperado

Deveria adicionar a nova legislatura.
## Comportamento Atual

Está aparecendo Erro 500. Não há mensagem de erros no log.
## Possível Solução

Corrigir o bug. 
## Passos para Reproduzir (para bugs)

1. Sistemas > Tabelas Auxiliares > Legislatura > Adicionar Legislatura
2. Preencher as datas de Eleição, início e fim.
3. Clicar em Salvar
4. Aparece Erro 500

## Imagens do Ocorrido

![image](https://user-images.githubusercontent.com/19416887/103439347-de74f680-4c1a-11eb-9b51-858a4e5ce83f.png)
![image](https://user-images.githubusercontent.com/19416887/103439353-edf43f80-4c1a-11eb-8027-00b1f9dee69e.png)

## Seu Ambiente

* Versão usada (_Release_): 3.1.160-RC12. Testado em 3.1.161, 3.1.161-RC20 e o erro persiste.
* Nome e versão do navegador: Chrome Versão 87.0.4280.88
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto): http://sapl.cmsjp.pr.gov.br/

**Comment by eribeiro** [comment]
Vocês poderiam anexar o arquivo sapl.log (ele se encontra no diretório raiz do projeto SAPL) aqui nessa issue? Simula o erro antes.

**Comment by edwardoliveira** [comment]
Vocês poderiam anexar o arquivo sapl.log (ele se encontra no diretório raiz do projeto SAPL) aqui nessa issue? Simula o erro antes.

**Comment by cintiaelisa** [comment]
Prezado Edward
O sistema voltou a funcionar inexplicavelmente.
Agradeço todo o apoio e suporte.
