### ISSUE TITLE
Nome parlamentar diferente do cadastrado

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3334]
## Comportamento Esperado
O nome parlamentar disponível na caixa de seleção do autor deve ser o cadastrado.

## Comportamento Atual
O nome parlamentar disponível está diferente. Caso do Vereador Professor Tiago Janner, pois aparece Tiago Janner.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/materia/create

## Contexto
Adição de matéria legislativa.

## Imagens do Ocorrido
![Captura de tela de 2021-01-08 14-58-34](https://user-images.githubusercontent.com/19169882/104052644-c710ad00-51c8-11eb-8ed4-82013d0b963c.png)

## Seu Ambiente
Versão usada (Release): 3.1.161-RC2
Nome e versão do navegador: Versão 87.0.4280.66 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
Experiemente pesquisar o autor em Sistema -> Tabelas Auxiliares -> Pesquisar Autor. Pesquise o autor em questão, clique no nome dele, clique em Editar e clique somente em Salvar. Nesse processo o SAPL deve copiar o novo nome parlamentar para o campo respectivo da tabela de autor. Me avise se funcionou ou não, mas em caso afirmativo pode fechar essa issue.

**Comment by eribeiro** [comment]
Realizei os passos acima e agora aparece o nome parlamentar correto em autor.

**Comment by edwardoliveira** [comment]
Realizei os passos acima e agora aparece o nome parlamentar correto em autor.
