### ISSUE TITLE
Erro na instalação

### ISSUE THREAD

**Issue by fabiobelo** [interlegis/sapl#3335]
Estou tentando executar o comando python manage.py generate_secret_key, seguindo o passo de instalação, entretanto, me deparo com essa tela. Estou seguindo como na doc.
<img width="1097" alt="Captura de Tela 2021-01-29 às 23 00 57" src="https://user-images.githubusercontent.com/5943692/106343786-dd6cce80-6285-11eb-9cf8-818a04243e5c.png">

**Comment by edwardoliveira** [comment]
Vc experimentou rodar o comando `pip install -r requirementst/dev-requirements.txt` antes?

**Comment by fabiobelo** [comment]
Tentei o comando acima sim, porém, sem sucesso.

Estava tentando na versão: 3.1.161-RC12, então coloquei a versão 3.1.160 e funcionou perfeitamente. 

Entretanto, ainda não identifiquei o que ocasionou, pois, não foi realizado nada fora do comum.

**Comment by edwardoliveira** [comment]
Eu não consegui reproduzir o erro. O que fiz foi criar um virtualenv do zero usando os seguintes comandos:

1) `virtualenv sapl3` (como era para testes não especifiquei a localização do virtualenv)
2) `source sapl3/bin/activate`
3) `cd projects/sapl` (diretório raiz do SAPL)
4) `pip install -r requirements/dev-requirements.txt`
5) `./manage.py generate_secret_key`
`f^d^2=_(!^71^0fof3ad08tecf!im*cv_xw)*+qj+74yq=s=80`

**Comment by LeandroJatai** [comment]
Este erro foi corrigido na versão 3.1.162-RC0.
