### ISSUE TITLE
Vincular matéria

### ISSUE THREAD

**Issue by jonasrn** [interlegis/sapl#3336]
Ao protocolar uma matéria existe a opção de vincular aquela matéria a uma existente, qual o momento ideal para vincular uma matéria a outra? Nas apostilas do SAPL não fala nada a respeito! Seria quando as matérias têm assunto correlacionados? Outra coisa um VETO por exemplo hoje coloco ele em ANEXADA, seria o ideal colocar ele como vinculado? No momento de fazer o vínculo não é pedido o TIPO DE MATÉRIA, ou seja, mesmo colocando o número lá sempre diz que a matéria não existe!
## Comportamento Esperado

Ao vincular a matéria não aparece a opção para vc escolher o tipo de matéria, no sistema por exemplo terá a matéria 01/2020 de vários tipos, como sistema fará esse vínculo?

## Comportamento Atual

O SAPL nunca encontra a matéria a ser vinculada
![saplImagem](https://user-images.githubusercontent.com/2423695/106784896-99821c80-662b-11eb-952b-d00d3ec918d5.jpeg)

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Essas dúvidas devem ser sanadas no grupo de usuários do SAPL. Tem a lista de usuários do SAPL no GITEC (https://listas.interlegis.gov.br/mailman/listinfo), o grupo de usuários do SAPL no WhatsApp (https://chat.whatsapp.com/Lya1Ych1eQFGVUNVztHH2l). Ainda pode abrir um ticket de suporte no OSTicket ( https://suporte.interlegis.leg.br/ ) . Inclusive para a questão relativa a atualização das apostilas, que será encaminhada a pessoa responsável por essa parte.
