### ISSUE TITLE
Ao dar build no frontend quebra todos os scripts

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#3338]
## Comportamento Atual
Ao buildar o frontend , quebra todos os scripts 

## Seu Ambiente

* Versão usada (_Release_): 3.1.162-RC0

**Comment by puera** [comment]
@LeandroJatai após algumas atualizações feitas no frontend pós commit 94782c5, todos os scripts param de funcionar

**Comment by puera** [comment]
![image](https://user-images.githubusercontent.com/1524415/107129969-1ae5e300-68a8-11eb-8a69-3b1bcb3f9309.png)

![image](https://user-images.githubusercontent.com/1524415/107129991-584a7080-68a8-11eb-80b2-abada155a1a5.png)

**Comment by LeandroJatai** [comment]
Olá @puera, execute apenas **yarn** antes do **yarn build**... houve atualizações de versão, de código e de configuração... seu _node_modules_ deve estar desatualizado...

**Comment by puera** [comment]
> Olá @puera, execute apenas **yarn** antes do **yarn build**... houve atualizações de versão, de código e de configuração... seu _node_modules_ deve estar desatualizado...

foi feito isso @LeandroJatai , vou tentar novamente deletando o node_modules e instalando todas as dependências novamente

**Comment by LeandroJatai** [comment]
resolveu @puera ??? aqui está funcionando como esperado!

**Comment by puera** [comment]
@LeandroJatai desculpa a demora para o retorno, era realmente algum cache do yarn e node_modules o problema, fiz um clean e baixei todas as deps novamente e voltou a funcionar
