### ISSUE TITLE
Erro no tamanho do NOME arquivo ao autuar matéria.

### ISSUE THREAD

**Issue by jonasrn** [interlegis/sapl#3344]
O tamanho do NOME do arquivo anexado pelo deputado acima de 200 caracteres não pode ser autuado, pois ocorre um erro informando que o NOME desse arquivo está acima desse valor.
## Comportamento Esperado

Já que não pode autuar arquivo acima de 200 caracteres, não permitir que arquivo acima de 200 caracteres sejam anexados.
## Comportamento Atual

Hoje ocorre um erro ao autuar arquivo com o NOME acima de 200 caracteres.
## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
O SAPL está permitindo anexar documentos acessórios com nomes acima de 200 caracteres? Ou é o texto original da norma? Ou o texto do própria matéria?

**Comment by jonasrn** [comment]
![saplIMAGEM_TAMANHO ARQUIVO](https://user-images.githubusercontent.com/2423695/107644107-c353c880-6c55-11eb-926b-9ef4584d588d.jpeg)

**Comment by jonasrn** [comment]
![SAPL_TAMANHO_ARQUIVO](https://user-images.githubusercontent.com/2423695/107644325-0f067200-6c56-11eb-8002-4ac5334cfac5.png)

**Comment by edwardoliveira** [comment]
Sim, o sistema está correto. Existe esse limite de 200 caracteres e ele não será aumentado.

**Comment by jonasrn** [comment]
Mas pq então o deputado conseguiu anexar o arquivo ? já o o DJANGO não permite ? o arquivo já está anexado, a matéria só vai ser autuada

**Comment by edwardoliveira** [comment]
> só quero que já que o sistema não vai aceitar acima de 200 caracteres que nem permita a proposição ser enviada, só isso.

Então, foi isso que eu perguntei. 

O parlamentar utilizou o módulo de proposições?

**Comment by jonasrn** [comment]
> > só quero que já que o sistema não vai aceitar acima de 200 caracteres que nem permita a proposição ser enviada, só isso.
> 
> Então, foi isso que eu perguntei.
> 
> O parlamentar utilizou o módulo de proposições?

Sim, usou e fez o cadastro da proposição
