### ISSUE TITLE
Campo Observação não aparece no extrato da sessão

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3352]
## Comportamento Esperado
O conteúdo do campo Observação de Matéria do Expediente deve aparecer no extrato da sessão e no pdf.

## Comportamento Atual
Aparece apenas o nome do campo.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/sessao/2849/resumo_ata

## Contexto
Apresentação do extrato da sessão.

## Imagens do Ocorrido
![Captura de tela de 2021-02-19 16-39-29](https://user-images.githubusercontent.com/19169882/108553417-64cfbf80-72d1-11eb-8784-2bf61786af1d.png)
![Captura de tela de 2021-02-19 16-37-21](https://user-images.githubusercontent.com/19169882/108553455-73b67200-72d1-11eb-9b5a-3b89db64b94c.png)
![Captura de tela de 2021-02-19 16-37-42](https://user-images.githubusercontent.com/19169882/108553499-83ce5180-72d1-11eb-9964-e3b866989923.png)

## Seu Ambiente
Versão usada (Release): 3.1.162-RC1
Nome e versão do navegador: Versão 87.0.4280.66 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
Pelo que vi rapidamente ontem (vou confirmar) essa "Obs" parece ser a observação do resultado de votação. Pode perceber que ela aparece depois do resultado. No caso é pra colocar as duas observações: do resultado e da ementa, certo?

**Comment by andreagudo** [comment]
Não se trara de observações na Ordem do Dia (onde está tudo ok), mas nas
Mateiras do Expediente.

Em qua, 24 de fev de 2021 10:27, Edward <notifications@github.com> escreveu:

**Comment by edwardoliveira** [comment]
Sim, é disso que estou falando justamente isso. **Existem DUAS observações: uma da ementa e outra do resultado da votação.** 

Tanto em matérias da ordem do dia quanto expediente, esse campo observação que aparece no relatório de ata **_é o campo de observação do resultado da votação_**. Veja que na imagem 1 para a matéria em questão não foi cadastrado nenhum texto pra esse campo (o de observação de resultado da votação). Eu vou colocar pra aparecer a observação
