### ISSUE TITLE
Matéria Legislativa não aparece no relatório de matérias em tramitação

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3353]
## Comportamento Esperado
Tramitação de arquivamento excluída deve fazer retornar à tramitação matéria indevidamente arquivada.

## Comportamento Atual
A matéria não aparece no relatório de matérias em tramitação.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/sistema/relatorios/materia-por-tramitacao?materia__ano=2021&materia__tipo=&tramitacao__unidade_tramitacao_destino=&tramitacao__status=&materia__autores=&pesquisar=Pesquisar
https://sapl.agudo.rs.leg.br/materia/10857/tramitacao

## Contexto
O Requerimento nº 2/2021 foi arquivado, tramitação que acabou sendo excluída, mas ele não está no relatório de matérias em tramitação.

## Imagens do Ocorrido
![image](https://user-images.githubusercontent.com/19169882/108704400-ba32e900-74ea-11eb-94a3-7fc6e1f5c0d8.png)
![image](https://user-images.githubusercontent.com/19169882/108704464-d0d94000-74ea-11eb-8023-75cf402f8245.png)

## Seu Ambiente
Versão usada (Release): 3.1.162-RC1
Nome e versão do navegador: Versão 87.0.4280.66 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
Existia um bug que não mudava o status da matéria em questão para 'Em Tramitação' = SIM. Isso foi corrigido e estará disponível nos próximos releases, mas para esta matéria em questão deve-se editar os dados básicos da matéria e colocar Em Tramitação como SIM e salvar.
