### ISSUE TITLE
Defeito - Botão "Votar Matéria" desaparece após troca de senha

### ISSUE THREAD

**Issue by cintiaelisa** [interlegis/sapl#3366]
Logo após o vereador trocar a senha, logar. novamente, o botão "Votar Matéria" não fica mais disponível, apesar do usuário estar vinculado corretamente como usuário votante. É necessário excluir o usuário votante e recolocar.
## Comportamento Esperado

Após a troca de senha o botão "Votar Matéria" continue disponível ao vereador.
## Comportamento Atual

O botão "Votar Matéria" desaparece logo após o vereador trocar a senha. 

## Passos para Reproduzir (para bugs)

1. O usuário parlamentar loga. É verificado que o botão "Votar matéria" está disponível.
2. É efetuada a troca de senha.
3. É feito novamente o login.
3. O botão "Votar Matéria" não está mais disponível.
4. É excluído o usuário votante e recolocado. O botão volta a aparecer.

## Seu Ambiente

* Versão usada (_Release_): 3.1.160-RC12
* Nome e versão do navegador: Chrome
* Nome e versão do Sistema Operacional (desktop ou mobile): Desktop - Windows 10
* Link para o seu projeto (Caso de fork deste projeto): http://sapl.cmsjp.pr.gov.br/

**Comment by edwardoliveira** [comment]
Sim, tinha um bug nessa linha aqui que removia indevidamente a role de 'Votante'. Acabei de resolver nesse commit https://github.com/interlegis/sapl/commit/1b7cfee9e23f4db8b6e01d5b3e8698d84b756e1d

Mas não precisava excluir o usuário. Isso poderia ser remediado indo no detalhe do Parlamentar, na aba 'Usuário', excluindo o vinculo com o usuário e criando de novo. Assim ele reestabeleceria a ROLE de 'Votante'.

**Comment by cintiaelisa** [comment]
Acho que me expressei mal, não estávamos excluindo o usuário todo, somente realizando o vínculo novamente.
Obrigada pelo fix super rápido!
