### ISSUE TITLE
Os nomes de todos os autores não aparecem na listagem 'Matérias Expediente' em 'Sessão Plenária'

### ISSUE THREAD

**Issue by cintiaelisa** [interlegis/sapl#3376]
O nome de todos os primeiros autores da matérias não aparecem 'Matérias Expedientes' da Sessão Plenária. Somente aparece o nome de um, aparentemente, obedecendo ordem alfabética.
## Comportamento Esperado

Que o nome de todos os autores aparece na lista de 'Matérias do Expediente' em 'Sessão Plenária'.
## Comportamento Atual

Está aparecendo o nome de apenas um dos autores, obedecendo ordem alfabética.
## Possível Solução

Realizar alteração para que o nome de todos os primeiros autores aparecessem. 
## Passos para Reproduzir (para bugs)

1. Na página inicial clicar em 'Sessão Plenária'
2. Listar as sessões plenárias
3. Selecionar sessão plenária
4. Clicar em Expedientes > Matérias do Expediente
5. Verificar na lista que na Coluna 'Matéria' que somente o nome de um autor aparece, mesmo quando a matéria tem mais de um autor.

## Contexto

O problema tem causado divergências entre os vereadores que protocolam matérias em conjunto, porém na lista só aparece o nome de um. 
## Imagens do Ocorrido

O exemplo abaixo ilustra o caso. O requerimento nº35 de 2021 tem dois autores:
http://sapl.cmsjp.pr.gov.br/materia/142683/autoria
![image](https://user-images.githubusercontent.com/19416887/112047559-39d4c780-8b2c-11eb-85f0-b62362b2a1bc.png)

Porém ao listar matérias aparece apenas o nome de um:
http://sapl.cmsjp.pr.gov.br/sessao/188/expedientemateria

![image](https://user-images.githubusercontent.com/19416887/112047789-756f9180-8b2c-11eb-9746-2cc9cfc8f51c.png)

O problema NÃO ocorre na "Pauta da Sessão", onde aparece o nome dos dois:
http://sapl.cmsjp.pr.gov.br/sessao/pauta-sessao/188/
![image](https://user-images.githubusercontent.com/19416887/112047896-9932d780-8b2c-11eb-9191-b305939db083.png)

## Seu Ambiente

* Versão usada (_Release_): 3.1.162-RC3
* Nome e versão do navegador: Chrome
* Nome e versão do Sistema Operacional (desktop ou mobile): Desktop
* Link para o seu projeto (Caso de fork deste projeto): http://sapl.cmsjp.pr.gov.br/

**Comment by edwardoliveira** [comment]
Ele está filtrando somente o primeiro registro de primeiro autor: https://github.com/interlegis/sapl/blob/3.1.x/sapl/sessao/views.py#L209

**Comment by edwardoliveira** [comment]
Estou reabrindo essa issue pq fiquei com uma dúvida: vc gostaria de que os nomes de todos os autores aparecessem, incluindo aqueles que não são autores principais? 

Eu estou perguntado pq já vi casos de casas onde todos os parlamentares são autores de várias matérias. Assim, tem 11-15 nomes o que eu acho que bagunçaria a formatação da tela. Eu tô com uma ideia aqui que talvez seja um meio termo entre mostrar somente os autores principais e mostrar todos...

**Comment by cintiaelisa** [comment]
Boa noite! Somente os configurados como "Primeiros autores", ou seja, os autores principais. Obrigada!

**Comment by cintiaelisa** [comment]
No caso, a matéria aceita vários "primeiros autores".

**Comment by edwardoliveira** [comment]
Ah, tudo certo então. A solução que eu fiz atende esse requisito. Fechando a issue.
