### ISSUE TITLE
Defeito - Login do usuário editado aparece no menu de login após edição

### ISSUE THREAD

**Issue by cintiaelisa** [interlegis/sapl#3377]
Após editar um usuário em 'Administração de Usuários' o nome do usuário aparece no menu, como se fosse ele o logado no sistema.
## Comportamento Esperado

Que o nome do usuário logado continue aparecendo no menu normalmente.
## Comportamento Atual

O nome do usuário editado aparece no menu após edição.
## Possível Solução

Correção do bug.
## Passos para Reproduzir (para bugs)

1. Sistema > Administração de Usuários > Buscar o usuário
2. Clicar em "Editar Usuário"
3. Editar qualquer campo.
4. Clicar em 'Salvar Alterções' 
5. Clicar no menu de login
6. O nome do usuário editado aparece no menu como se ele fosse o usuário logado.

## Imagens do Ocorrido

Usuário logado é o admin:
![image](https://user-images.githubusercontent.com/19416887/112159227-acdf4c00-8bc7-11eb-83d9-084c57595fed.png)

Após salvar a edição o nome do usuário editado aparece no lugar do real usuário logado:
![image](https://user-images.githubusercontent.com/19416887/112159422-ea43d980-8bc7-11eb-8fa4-3aaa3af55608.png)

## Seu Ambiente

* Versão usada (_Release_): 3.1.162-RC3
* Nome e versão do navegador: Chrome
* Nome e versão do Sistema Operacional (desktop ou mobile): 
* Link para o seu projeto (Caso de fork deste projeto): http://sapl.cmsjp.pr.gov.br/

**Comment by edwardoliveira** [comment]
Essa parte de 'Administração de Usuários' sofreu uma recente modificação que, em termos práticos, refez toda a  administração de usuários, graças `a grande contribuição do @LeandroJatai. Por isso, esse erro não ocorre mais no branch 3.1.x. Devemos lançar uma nova versão amanhã cedo com essa alteração.
