### ISSUE TITLE
Erro 403 Forbidden - Receber proposições - Histórico Proposições

### ISSUE THREAD

**Issue by cintiaelisa** [interlegis/sapl#3382]
Está acontecendo "Erro 403 Forbidden" quando a funcionalidade Proposições > Receber Proposições > Histórico de Proposições é acessada com conta de usuário.
É possível acessar a funcionalidade utilizando a conta 'admin'.
## Comportamento Esperado

A funcionalidade deveria ser acessada corretamente para contas de usuário que tenham a devida permissão.
## Comportamento Atual

Ao acessar a funcionalidade o usuário recebe erro 403.
## Possível Solução

Corrigir problema de permissão na página.
## Passos para Reproduzir (para bugs)

1. Logar com conta de usuário
2. Navegar: Protocolo > Receber Proposições > Histórico de Proposições

## Imagens do Ocorrido

![image](https://user-images.githubusercontent.com/19416887/112205667-c7c7b580-8bf3-11eb-9203-2821def3c32f.png)

## Seu Ambiente

* Versão usada (_Release_): 3.1.162-RC3
* Nome e versão do navegador: Chrome
* Nome e versão do Sistema Operacional (desktop ou mobile): Desktop
* Link para o seu projeto (Caso de fork deste projeto): http://sapl.cmsjp.pr.gov.br/

**Comment by edwardoliveira** [comment]
Vc poderia me dizer quais as permissões (roles) deste usuário para o qual aparece esse erro?

**Comment by cintiaelisa** [comment]
As roles são estas:

![image](https://user-images.githubusercontent.com/19416887/112402473-59feb500-8ceb-11eb-9b1c-353ef268c547.png)
