### ISSUE TITLE
PDF Pauta da Sessão com formatação diferente

### ISSUE THREAD

**Issue by cintiaelisa** [interlegis/sapl#3387]
Os links de geração de pauta da sessão em pdf fornecem formatação diferentes. No ícone de PDF na listagem de pauta das sessões um formato e dentro da sessão outro formato. Segundo o processo legislativo local o formato mais adequado é o gerado pelo botão interno, na tela da pauta.

## Comportamento Esperado

Que as duas formas gerassem pautas idênticas em PDF.
## Comportamento Atual

Cada botão está gerando um formato de pauta diferente.
## Possível Solução

Padronizar a geração de PDF para um único formato.

## Passos para Reproduzir (para bugs)

1. Pauta da Sessões > Pesquisar Pauta da Sessão > Pesquisar
2. Clicar no ícone de PDF:
![image](https://user-images.githubusercontent.com/19416887/114190689-f4810a00-9921-11eb-906f-cecf856d81bd.png)

3. Pauta gerada tem um formato:
![image](https://user-images.githubusercontent.com/19416887/114190778-0fec1500-9922-11eb-9ac6-e4a703dbdd69.png)

4. Clicando no link da pauta e depois no botão "Impressão PDF"
![image](https://user-images.githubusercontent.com/19416887/114190901-37db7880-9922-11eb-92f6-91354808f7e5.png)

5. A pauta tem outro formato:

![image](https://user-images.githubusercontent.com/19416887/114190992-4f1a6600-9922-11eb-936c-9cb6c1f5fc97.png)

## Contexto

Quando os usuários imprimem a pauta, dependendo do botão utilizado, imprimem pautas diferentes para mesma sessão.

## Imagens do Ocorrido

Segue acima.
## Seu Ambiente

* Versão usada (_Release_): 3.1.162-RC2
* Nome e versão do navegador: Chrome
* Nome e versão do Sistema Operacional (desktop ou mobile): Desktop
* Link para o seu projeto (Caso de fork deste projeto): http://sapl.cmsjp.pr.gov.br/

**Comment by edwardoliveira** [comment]
Obrigado por capturar isso! De fato, o arquivo em 5 vem de uma versão antiga do SAPL e não deveria mais estar acessível. Vou removê-la e unificar os dois links.
