### ISSUE TITLE
Extrato da Sessão não exibe a votação nominal ocorrida no expediente

### ISSUE THREAD

**Issue by Danpeli** [interlegis/sapl#3388]
## Comportamento Esperado
Em uma sessão, apos ocorrer a votação nominal de uma proposição localizada em Matérias Expediente, emitir o extrato da sessão para utilizar como ata, e nesta conter como cada vereador votou na proposição que passou por votação nominal, em Matérias Expediente

## Comportamento Atual
Em uma sessão, apos ocorrer a votação nominal de uma proposição localizada em matérias do Expediente, imprime-se o extrato da sessão para utilizar como ata, e esta não contem  como cada vereador votou na proposição que passou por votação nominal, em Materias Expediente

## Possível Solução
...

## Passos para Reproduzir (para bugs)
1. Registrar a proposição em **"Expediente>Materias Expediente"** da sessão e colocar o **Tipo de votação Nominal**;
2. Registrar a votação da proposição;
3. Emitir o Extrato da Sessão .

## Contexto
Utilizamos o Extrato da Sessão como ata eletrônica, e com essa discrepância não há como utilizá-la, por não traduzir o ocorrido durante a sessão

## Imagens do Ocorrido
...

## Seu Ambiente

* Versão usada (_Release_): 3.1.162-RC5
* Nome e versão do navegador:  Firefox 87.0 / Chromium 89.0.4389.114 
* Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 20.04
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Este commit https://github.com/interlegis/sapl/commit/3108c9d5c0b043a94f236f39af4aaaf9d5ca6c8e conserta essa issue. Estará disponível na próxima versão do SAPL, ainda esta semana.
