### ISSUE TITLE
Permitir na aba [Proposições Incorporadas] imprimir recibo das proposições e apresentar data de envio da proposição

### ISSUE THREAD

**Issue by jonasrn** [interlegis/sapl#3401]
Na parte de receber proposições, na aba [Proposições Incorporadas], não há possibilidade de pesquisar nenhuma proposição incorporada, muitas vezes o usuário que recepcionou a proposição quer imprimir o recibo daquela proposição, além disso na listagem não aparece a data de envio.
Isso é importante pois funcionaria como uma espécie de auditoria pelo o usuário que recepciona a matéria, ele teria mais facilmente em mãos a data de envio, a data de recebimento e o que a proposição se tornou.

## Comportamento Esperado

Na aba [Proposições Incorporadas], apresentar data de envio, possibilitar imprimir o recibo e além disso ter possibilidade de pesquisa nessa aba

## Comportamento Atual

Hoje na aba [Proposições Incorporadas], não tem como imprimir o recibo, não apresenta a data de envio pelo deputado e não tem como pesquisar.

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Imagens do Ocorrido

![ProposicoesIncorporadas](https://user-images.githubusercontent.com/2423695/119825704-9efebd80-becd-11eb-9e45-9f5988aab00a.jpg)

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Adicionei a data de envio e a impressão do recido da proposição. A parte de pesquisa de proposições será objeto de uma outra issue, pois provavelmente será estendida para a tela de proposições não recebidas e proposições não incorporadas.

<img width="1083" alt="Screen Shot 2021-05-31 at 13 35 04" src="https://user-images.githubusercontent.com/9326037/120221836-74866a80-c215-11eb-9f0a-0dc1f6ce798a.png">

**Comment by edwardoliveira** [comment]
#3407
