### ISSUE TITLE
Ao apresentar informações sobre uma matéria, o item [última ação] não é apresentado  conforme a imagem

### ISSUE THREAD

**Issue by jonasrn** [interlegis/sapl#3403]
Ao apresentar informações sobre uma matéria, o item [última ação] não é apresentado  conforme a imagem
## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Imagens do Ocorrido

![UltimaAcao](https://user-images.githubusercontent.com/2423695/119844001-6f0be600-bede-11eb-8c5e-e6754af15244.jpg)

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
O texto deste campo vem do campo "Texto da Ação" da Tramitação mais recente. Se não for preenchida não aparece. Vou modificar a lógica dessa tela pra só mostrar esse campo se existir texto preenchido.

<img width="1159" alt="Screen Shot 2021-05-31 at 12 24 01" src="https://user-images.githubusercontent.com/9326037/120215451-202abd00-c20c-11eb-82ab-5ba0b0ea213e.png">

<img width="1113" alt="Screen Shot 2021-05-31 at 12 24 26" src="https://user-images.githubusercontent.com/9326037/120215465-23be4400-c20c-11eb-8368-6c1658214b98.png">
