### ISSUE TITLE
O item { status } deve informar se a matéria foi aprovada, e não apresentar o último status

### ISSUE THREAD

**Issue by jonasrn** [interlegis/sapl#3404]
O item [status] apresenta a última tramitação da matéria.
Por exemplo, essa matéria apresentada na imagem foi aprovada, depois de aprovada ela vai para o arquivo da casa, porém o sistema apresenta esse status de arquivado.
Deve existe um item  informando se a matéria foi aprovada ou não.
Para apresentar o último status, já temos o item última ação. 

## Comportamento Esperado

O  item [status] mostrar se a matéria foi aprovada
## Comportamento Atual

Apresenta o último [status], sendo que o último não terá essa informação, se a matéria foi aprovada ou não

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Imagens do Ocorrido

![statusAprovado](https://user-images.githubusercontent.com/2423695/119846150-4258ce00-bee0-11eb-87ec-d7234320a338.png)

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Eu concordo. 

Ocorre que isso veio do SAPL 2.5 e muitas casas usam esse campo colocando o status de tramitação como "Aprovada em 1o. turno", "Aprovada em 2o. Turno", "Arquivada", etc. Mudar isso **agora** iria trazer muitas reclamações, portanto, não tem como ser mudada. Uma coisa que poderia ser feita seria a criação de um outro campo, talvez chamado "resultado", por exemplo, que traria se a matéria foi lida/aprovada/rejeitada, mas isso de certa forma duplicaria o que as casas já colocam em "status". O que sugere?

**Comment by jonasrn** [comment]
@edwardoliveira entendi, concordo em colocar uma campo, [Resultado] ou [Situação] etc.
