### ISSUE TITLE
Usar protocolo em papel bobina

### ISSUE THREAD

**Issue by Jachelen** [interlegis/sapl#3426]
## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by LeandroJatai** [comment]
Olá @Jachelen ... aqui usamos a Brother QL-700... só você comprar uma que a etiqueta do protocolo está pronta pra ela.
