### ISSUE TITLE
Migração

### ISSUE THREAD

**Issue by fabiobelo** [interlegis/sapl#3428]
Amigos, estou com o SAPL funcionando em um servidor local na casa legislativa. Para dar mais segurança e escalabilidade, iremos para uma cloud; Existe ou sugerem algum procedimento e qual seria mais indicado para levar o backup das matérias, tanto a pasta media, quanto o banco?

**Comment by GabrielSchiochet** [comment]
Bom dia, Fábio.
Sua base também é no MySQL?
Eu não sou expert aqui, mas o Senado atualmente está armazenando as bases de dados das novas Câmaras direto nos servidores do Senado. Ou seja, as Câmaras não precisam armazenar em um servidor local.
Se a intenção é colocar na nuvem e em um local em que vocês nem terão que pagar pelo armazenamento, tente abrir um Ticket lá no Interlegis (link abaixo) e questione se eles podem achar um lugar para armazenar sua base de dados e configurar seu SAPL para acessar estes dados.
https://suporte.interlegis.leg.br/open.php

Aí você informa também qual o tamanho da sua base de dados atual, pois não sei se há alguma restrição ou limite de espaço que cada Câmara pode utilizar.

**Comment by LeandroJatai** [comment]
@fabiobelo não existe um tutorial oficial com um "faça você mesmo" para essa migração de servidores. Você tem duas opções:
1) em sequencia: busque aprender fazer o backup do postgresql; depois como fazer backup dos arquivos armazenados de um projeto django; como restaurar banco postgresql; e, como restaurar os arquivos armazenados de um projeto django; se seu sapl está dentro do docker, tem que aprender essas etapas aí e ainda como executá-las no docker, lembrando que docker parece mais difícil  num primeiro momento, mas configurar o ambiente nativamente sem docker, principalmente com busca textual (configurando o solr) é quase que o fim do mundo... 

2) me contratar pra fazer;

@GabrielSchiochet se a base é MySql então o buraco é mais embaixo, quer dizer que é o sapl antigo, a migração é mais complicada, muito mais coisa para fazer e entender - a opção 2 acima está a disposição.

**Comment by LeandroJatai** [comment]
@fabiobelo 

produzi três vídeos para instalação e migração do sapl com docker. Se seu sapl não está no docker, é diferente mas existem semelhanças no processo. O resumo está publicado no meu apoia.se

#Diário - 22/09/2021
Hoje gravei vídeos sobre como utilizar o SAPL com Docker. 
O vídeo deste post é o primeiro vídeo de uma série de 3 vídeos sobre SAPL com Docker. 

Os vídeos estão distribuídos assim:
 1) Instalação do SAPL via docker: https://youtu.be/2xGN1IfjOSI
 2) Restauração: https://youtu.be/gOTefJvgtvY
 3) Backup: https://youtu.be/F17hwS_DcI8

Nesta tarefa foram dedicadas 3 horas de colaboração

publicação original: https://apoia.se/leandrojatai/contents/view/Diario-Como-usar-o-SAPL-com-Docker-Intalacao-restauracao-e-backup-Bx_Mujch4

Att.
Leandro Jataí
---------------------
https://apoia.se/leandrojatai
Abra meu "apoia-se" e saiba mais sobre esta ideia.
