### ISSUE TITLE
Pesquisa por palavra chave na ementa - API

### ISSUE THREAD

**Issue by EscrevendoCodigo** [interlegis/sapl#3432]
Olá,
notei que na API existe a possibilidade de localizar a matéria através da ementa (api/materia/materialegislativa/?ementa=), porém ao pesquisar por apenas uma palavra, nada é retornado, então realizei um teste e colei o texto completo de uma ementa, neste caso a API retorna a matéria. Se possível, seria interessante tornar a pesquisa mais flexível, semelhante ao input de pesquisa textual. 

Obrigado.

**Comment by LeandroJatai** [comment]
Resolvido com https://github.com/interlegis/sapl/commit/9ae1f401ae7ae11a56d3392d003f2b4151767937 

Você pode realizar pesquisas usando os lookups do django, por exemplo:
api/materia/materialegislativa/?ementa__icontains=

em sua instancia, acesse: api/schema/swagger-ui e veja todas as novas possilidades de busca para todos os campos

**Comment by LeandroJatai** [comment]
Segue link do vídeo tutorial para maior esclarecimento sobre as mudanças e novas possibilidades: https://youtu.be/nnulLW8rNgg

**Comment by EscrevendoCodigo** [comment]
Olá Leandro, agradeço imensamente o feedback, estarei realizando alguns testes.

**Comment by EscrevendoCodigo** [comment]
Olá Leandro, a pesquisa por ementa funcionou exatamente como esperado, porém durante os testes notei que foi removido da chamada "materia/materialegislativa" a opção de pesquisa por autor, que poderia ser feito anteriormente da seguinte forma "api/materia/materialegislativa/?o=-data_apresentacao&autores=id" onde retornava os documentos relacionados, esta foi a única maneira funcional que encontrei de realizar o filtro. A falta desta opção acabou quebrando o funcionamento do sistema, será que estou fazendo algo errado?

OBS: Existem mais duas chamadas específicas mas que aparentemente não são eficientes:

api/parlamentares/parlamentar/{id}/proposicoes/ - Não retorna nenhum dado;
api/materia/autoria/?autor=id  - Não retorna todos os dados da matéria. Neste caso seria necessário combinar algumas chamadas, mas não sei como ficará a performance disso.

Grato desde já.

**Comment by LeandroJatai** [comment]
De fato, no default, só existiam filtros 'exatos'... o m2m "autores", de forma default, é um filtro exato... a biblioteca que monta os filtros, os montava incluído além dos campos apenas com exact, também os m2m que são exact...

**o que eu fiz?** sobrescrevi o método da biblioteca que monta os filtros exact por um método que monta filtros com todos os tipos de lookups e não só o exact... só que na hora de remontar, eu incluí deliberadamente apenas os campos, deixando de fora os m2m: está explicito aqui:
https://github.com/interlegis/sapl/blob/3.1.x/sapl/api/core/filters.py#L53-L55
```
                f = model._meta.get_field(f_str)
                if f.many_to_many:
                    continue
```
Vou analisar, acredito que de forma rápida da pra deixar os m2m voltarem para o filtro com apenas o lookup exact

**Comment by LeandroJatai** [comment]
Feito, entra quando for criada a release: 3.1.162-RC14
https://github.com/interlegis/sapl/commit/f35add6d2fa76e5501c38101bc0fd176b9fe2b76

**Comment by EscrevendoCodigo** [comment]
Olá Leandro, muito obrigado pelo ajuste, estarei aguardando o RC14. Gostaria de parabeniza-lo pelo empenho neste projeto.

Gratíssimo.
