### ISSUE TITLE
Bug staticfiles em PDFs gerado externamente

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#3452]
Estou com um problema aqui na questão de staticfile no PDF ao ser gerado no SAPL (Pauta)

Ao gerar localmente a pauta fica formatada com imagem, css, etc

![pauta-com-formatacao](https://user-images.githubusercontent.com/1524415/134987335-da1d8b82-9bd2-4fee-88ba-b0509ed71876.png)

Ao ser acessado em um endereço externo como exemplo no link: https://sapl.armacaodosbuzios.rj.leg.br/sessao/pauta-sessao/226/pdf 

o pdf fica totalmente sem formatação

![image](https://user-images.githubusercontent.com/1524415/134987964-43721d9c-d337-43a2-af54-03c371003fb1.png)

minhas configurações do NGINX:

```
upstream sapl.armacaodosbuzios.rj.leg.br {
   server unix:/var/interlegis/sapl/run/gunicorn.sock fail_timeout=0;
}

server {

    listen 80 default_server;
    listen 443 ssl;
    include snippets/self-signed.conf;	
    server_name sapl.armacaodosbuzios.rj.leg.br;
    client_max_body_size 4G;

    access_log /var/log/nginx-access.log;
    error_log /var/log/nginx-error.log;

    location /static/ {
        alias   /var/interlegis/sapl/collected_static/;
	gzip_static on;
	expires max;
	add_header Cache-control public;
    }

    location /media/ {
        alias   /media/sapl/media/;
    }

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_redirect off;
	proxy_set_header Connection "";
        if (!-f $request_filename) {
           proxy_pass http://sapl.armacaodosbuzios.rj.leg.br;
            break;
        }
         
         if (-f  /usr/share/nginx/html/index.html) {
                return 503;
           }

    }

    # Error pages
   error_page 500 502 503 504 /500.html;
   location = /500.html {
       root /var/interlegis/sapl/sapl/static/;
    }

    #Manutencao
    # error_page 503 @index;
    #location @index{
    #     rewrite ^(.*)$ /index.html break;
    #   }

}
```

Estranhamente todo css, imagem pelo próprio sistema funciona normalmente, somente em PDF tenho esse problema

**Comment by puera** [comment]
@edwardoliveira @LeandroJatai podem me dar uma luz sobre esse issue?

**Comment by LeandroJatai** [comment]
@puera, não consegui identificar o erro... aparentemente seu nginx está ok.

sites hospedados no interlegis: https://sapl.agudo.rs.leg.br/sessao/pauta-sessao/2887/pdf

e mesmo uma instalação que sei que está fora do interlegis: http://leg.camarapirangi.sp.gov.br:8080/sessao/pauta-sessao/194/pdf

estão ambas na versão 3.1.162-RC8 e estão funcionando como esperado... localmente simulei um servidor de produção e está tudo ok tb.

seu arquivo relatorio.css está acessível em https://sapl.armacaodosbuzios.rj.leg.br/static/sapl/css/relatorio.css

então não é falta de rodar ./manage.py collectstatic --clear --noinput

acabei de verificar todo o código que envolve a geração da pauta e ele não sofre alteração a mais de 12 meses... seu sapl, possivelmente é de fevereiro de 2021, digo possivelmente pq vc alterou o rodapé do sapl indicando uma release que não existe a 3.1.162... na verdade vc está na https://github.com/interlegis/sapl/releases/tag/3.1.162-RC0 que é de fevereiro... onde realmente isto é relatado? aqui: https://sapl.armacaodosbuzios.rj.leg.br/api/base/casalegislativa/

então... tudo leva a crer que é aí e não código oficial.
