### ISSUE TITLE
Matéria Legislativa não lida no expediente no resumo

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3457]
## Comportamento Esperado
Matéria não lida no expediente deve aparecer como "Matéria não lida".

## Comportamento Atual
Está aparecendo como "Matéria lida".

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/sessao/2888/resumo

## Contexto
Consulta ao resumo da sessão.

## Imagens do Ocorrido
![Captura de tela de 2021-10-04 15-00-10](https://user-images.githubusercontent.com/19169882/135901616-5ee673b6-3a6d-4421-99a7-23f9269bfb93.png)
![Captura de tela de 2021-10-04 15-00-55](https://user-images.githubusercontent.com/19169882/135901643-1643b32d-eb9b-44d8-8f95-459c845b819b.png)

## Seu Ambiente
Versão usada (Release): 3.1.162-RC8
Nome e versão do navegador: Versão 90.0.4430.72 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by edwardoliveira** [comment]
Isso foi corrigido algum tempo atrás mas ainda estamos com problema na infraestrutura para publicar novas versões do SAPL. Geramos uma versão manualmente e implantamos hoje em Agudo-RS. Por favor, confirme a resolução do problema.

**Comment by andreagudo** [comment]
Solucionado. Obrigado.
