### ISSUE TITLE
texto da matéria a ser votada aparece na parte central do painel eletrônico, e sai da tela principal quando se tem um numero grande de parlamentares

### ISSUE THREAD

**Issue by 54adal** [interlegis/sapl#3461]
Quando se tem uma grande quantidade de parlamentares votantes (120 no Parlasul), durante a exibição do painel eletrônico as informações da matéria em votação é centralizada no painel. Por esse motivo, essa informação não aparece na primeira tela do painel, sendo necessário fazer a rolagem da tela pra que o mesmo seja visto.

## Comportamento Esperado
fixar as informações da matéria em votação na parte superior do painel para que as mesmas possam ser vistas na primeira tela.

## Comportamento Atual
aparece no meio da tela do painel e não aparece na tela de entrada.

## Possível Solução
fixar essas informações na parte superior

## Imagens do Ocorrido

![image](https://user-images.githubusercontent.com/30807716/136421460-4b9cc413-713f-45e0-b52e-bc03d4c61955.png)

**Comment by 54adal** [comment]
ops... não sei como fiz isso, mas havia fechado involuntariamente!

**Comment by AlGouvea** [comment]
Bom dia, você teria como me dizer em qual instância do SAPL foi feito o exemplo?

**Comment by 54adal** [comment]
https://sapl-r1.interlegis.leg.br/

**Comment by 54adal** [comment]
Não saberia te informar. O Sussumo poderia te dar essa informação!
