### ISSUE TITLE
Pesquisa textual em atas

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3464]
## Comportamento Esperado
Que seja implementada pesquisa textual em atas, como existe para documentos administrativos (https://sapl.agudo.rs.leg.br/sistema/search/ ). Tal pesquisa poderia ser acrescentada em https://sapl.agudo.rs.leg.br/sistema/relatorios/atas .

## Comportamento Atual
Não existe tal funcionalidade.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/sistema/relatorios/atas

## Contexto
Pesquisa de texto em documento ata.

## Imagens do Ocorrido
![Captura de tela de 2021-10-18 14-17-22](https://user-images.githubusercontent.com/19169882/137778008-acc0c9f0-0b8f-4189-b9b9-7ea0cd602a42.png)

## Seu Ambiente
Versão usada (Release): 3.1.162-RC11
Nome e versão do navegador: Versão 90.0.4430.72 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by LeandroJatai** [comment]
@andreagudo a solução foi criada e integrada à pesquisa textual acessada a partir da pesquisa de sessões, no entanto, apenas aí e não nos relatórios onde indicaste... a solução indexa e permite a busca nos três tipos de arquivos passíveis de inclusão na Sessão Plenária - ata, anexo e pauta.

**Comment by andreagudo** [comment]
O resultado não é completo. Ao consultar por "Jivago" a resposta se limita à sessão de 28/03/2022 e deveria trazer também a de 20/12/2021. Além disso, para a pesquisa por "Eilton" a resposta é nula, embora devesse ser as sessões 12/07/2021 e 27/09/2021.

**Comment by edwardoliveira** [comment]
Refiz o índice textual hoje. Estamos trabalhando para detectar e consertar esses erros de indexação de forma automática.
