### ISSUE TITLE
interlegis/sapl Solicitud Proyecto PARLASUR

### ISSUE THREAD

**Issue by ingrinaldi** [interlegis/sapl#3469]
<Replicar ambiente de Produccion en un nuevo ambiente de Testing>

## Comportamento Esperado
Necesitamos tener un nuevo ambiente de Testig, identico a lo que hoy tenemos en el de produccion

https://sapl.parlamentomercosur.org/

incluyendo todo el contenido y los Usuarios existentes.

quedamos a la espera y datos de la nueva URL

saludos y gracias!!

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by 54adal** [comment]
Solicitação atendida em 26/10/21 (Sussumo)
