### ISSUE TITLE
Incluir pauta de reuniões de comissões passadas

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3472]
## Comportamento Esperado
Deve ser possível incluir matérias já votadas na pauta de reuniões de comissões.

## Comportamento Atual
Não é possível incluir matérias já votadas.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/comissao/1/pauta/add?materia__tipo=&materia__ano=&materia__numero=&materia__data_apresentacao_0=&materia__data_apresentacao_1=

## Contexto
Registro de reuniões de comissões já ocorridas.

## Imagens do Ocorrido
![Captura de tela de 2021-10-26 13-51-27](https://user-images.githubusercontent.com/19169882/138925194-7df100bf-6389-41fe-a20c-b99c0632545d.png)

## Seu Ambiente
Versão usada (Release): 3.1.162-RC11
Nome e versão do navegador: Versão 90.0.4430.72 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 16.04 64 bits

**Comment by andreagudo** [comment]
Poderia ser incluída pesquisa https://sapl.agudo.rs.leg.br/comissao/1/pauta/add a possibilidade de optar entre matérias votadas e não votadas. O ideal seria manter salva a última opção.

**Comment by GiliardGodoi** [comment]
Olá André, tudo certo com vc?

Quando eu clico nos links que vc postou, eu sou redirecionado para a página de Login do SAPL da sua  Casa Legislativa. 

Você poderia dar maiores informações sobre o contexto? Por exemplo, um projeto já foi votado em primeira votação (ou em segunda, ou mesmo tornado lei, não sei) e ele precisou voltar para a Comissão de Legislação e Justiça por algum motivo. E você não está conseguindo incluir esse projeto na pauta da reunião da Comissão? Certo?

**Comment by andreagudo** [comment]
As reuniões das comissões não foram registras e precisamos registrá-las. Mas matérias já votadas não ficam disponíveis para serem incluídas na pauta da reunião.

**Comment by andreagudo** [comment]
Issue superada. Adiciono tramitação às matérias de que preciso e as insiro nas reuniões. Depois excluo as tramitações adicionadas.
