### ISSUE TITLE
Resultado Pesquisa Matéria Legislativa: lista opcional do "resultado" da votação

### ISSUE THREAD

**Issue by ClaudioMorale** [interlegis/sapl#3478]
## Comportamento Esperado
<!-- Apresentação do Conteúdo "Resultado" apenas se houver algum resultado. --!>

**Comment by ClaudioMorale** [comment]
Apresentar o resultado apenas se houver conteúdo; caso contrário, omitir o campo "resultado"

**Comment by edwardoliveira** [comment]
O comportamento do sistema já é assim.

**Comment by ClaudioMorale** [comment]
Algumas câmaras têm reportado que apesar de não utilizarem a função no módulo sessão plenária, aparece  "Resultado: matéria não votada" na pesquisa... veja por exemplo sapl.portonacional.to.leg.br

**Comment by ClaudioMorale** [comment]
![consulta-materia-legislativa-sapl-portonacional-to](https://user-images.githubusercontent.com/63022315/140354723-ad7f1fbd-1285-471b-b439-4818631b304d.png)
