### ISSUE TITLE
Botão ou status "confecção de pauta em andamento"

### ISSUE THREAD

**Issue by brendelkiwi** [interlegis/sapl#3491]
Criar um botão ou aviso que a pauta disponível 

Criar um botão ou aviso que a pauta disponível em determinado momento ainda está em confecção; ou possibilidade de fechar a pauta até estar pronta - possibilitando que eu a mantenha fechada até estar pronta para visualização pública.## Comportamento Esperado

Pauta livre pra qualquer pessoa com acesso ao link do site. ## Comportamento Atual

Criar a opção de que eu possa fechar a pauta até sua finalização dentro do sistema; OU criar botão "pauta em confecção" para que possa ser mudado para "pauta final" quando pronta.## Possível Solução

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

Vereadores e asessores acusam presidência de alterar a pauta, sendo que fazemos a entrega via meios corretos apenas quando está pronta; oposição se utiliza do link do site de má fé para criar conflito, tratando um problema técnico como viés político.## Contexto

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Criamos um campo "publicar pauta" em Dados Básicos de Sessão Plenária. A pauta irá aparecer somente quando este campo estiver como 'Sim'. Além disso, consertamos um bug no status de tramitação no relatório de pauta.

**Comment by edwardoliveira** [comment]
https://github.com/interlegis/sapl/pull/3532
