### ISSUE TITLE
Integrar LexML no SAPL

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#35]
O SAPL 2.5 possui alguma integração com o LexML. Replicar isto no novo SAPL.

**Comment by edwardoliveira** [comment]
@marciomazza @LeandroRoberto Vocês que estão fazendo levantamento das casas que utilizam esse feature, existe uma necessidade deste feature entrar na 3.1? Se forem poucas estou fortemente inclinado no sentido de postergar isso um pouco mais (3.2) enquanto estudamos a melhor maneira de implementar. WDYT?

**Comment by LeandroRoberto** [comment]
A meu ver tem que estar na 3.1.

**Comment by edwardoliveira** [comment]
:rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage:

**Comment by marciomazza** [comment]
116 casas têm um entrada na tabela `lexml_registro_provedor`. Segundo @morale isso significa que usam o LexML.

**Comment by JDias** [comment]
Não sei se interessa ...

http://www.wikiwand.com/en/LexML

Vi alguns vídeos sobre o lexml, e acho um tema importante, os metadados da lei.

Mais importante que suportar o lexml é aplica-lo.
O que dá pra fazer e onde esta suas limitações (afinal, outros países o abandonaram), my 0,20 cents.

**Comment by edwardoliveira** [comment]
Não @marciomazza... Isso **NÃO** significa que usam o LexML. Significa que 116 casas de dispuseram a registrar o exportador do LexML no SAPL e para mandar os dados pro Senado pra serem indexados pelos servidores do LexML. Se alguém realmente pesquisa esses dados dessas casas ou isso simplesmente é dado que fica mofando por aí somente a equipe do LexML poderia nos dizer, via log de acessos a pesquisas dessas casas. No mais, esse número representa cerca de 11,7% de todas as instâncias SAPL 2.5 instaladas no ILB, um número notadamente tímido, o que me faz questionar a real utilidade dessa ferramenta (LexML). **Me mostre números de usuários mensais, porque instalação por instalação eu tenho um Apple TV instalado em casa que não uso há 3 anos.**


__Se o LexML principal não parece ser um sucesso de público, eu sinceramente duvido MUITO que alguém pesquise leis municipais ou estaduais por ele.__  Como bem disse o @JDias: "mais importante que suportar o lexml é aplicá-lo"

**Comment by JDias** [comment]
Só para clarificar, sou curioso do pq o baixo público 
(Para não dar a impressão que sou contra suportar o lexml)

Imagina fazer um plugin p/ o atom do lexml, ele cobre todo o escopo?

https://youtu.be/bBYfU_tiFtI

(Não gosto de falar do que não conheço, acho os sistemas do congresso muito bons, mas não consigo imaginar como dirimir dúvidas sem expo-las, e acho que fugiria ao escopo do sapl)

**Comment by morale** [comment]
O sapl é um provedor de dados sobre normas jurídicas das casas legislativas para o LeXML. Para isso, utiliza um produto oai_server que, periodicamente em horário não nobre, quando acionado pelo LexML, transfere em formato xml dados sobre normas que foram incluídos/alterados a partir de uma data informada.
