### ISSUE TITLE
Erro ao pesquisar parlamentar

### ISSUE THREAD

**Issue by andremarcelocs** [interlegis/sapl#3505]
Uma mensagem de erro (Página não encontrada, ERRO 404). É apresentada ao tentar listar os parlamentares cadastrados.

## Comportamento Esperado
Ao entrar e clicar na pagina 1, e após clicar na página 2 (ou vice-versa), não apresentar a página de erro.

## Comportamento Atual
No módulo parlamentares, quando clicado em Pesquisar Parlamentar, a pagina 1 dos resultados aparece em branco (Figura 1 em anexo). Quando clica na pagina 2, aparece listado somente os últimos parlamentares da lista (Figura 2 em anexo). Após, se clicar na pagina 1 ou em anterior, é apresentado uma mensagem de erro (Figura 3 em anexo). No entanto, quando acessada a pagina Pesquisar Parlamentar e em seguida clicar na pagina 1 é listado os primeiros dez parlamentares. Contudo ao clicar na pagina 2, aparece novamente a mensagem de pagina não encontrada. Único método de não apresentar erro na consulta é clicar no botão pesquisar imediatamente após acessar a pagina de pesquisar parlamentar.

## Possível Solução
Ao entrar em pesquisar parlamentar, já mostrar a lista dos parlamentares, sem a necessidade de clicar na página 1, página 2 ou em pesquisar para listar os parlamentares. E não apresentar mensagem de erro ao alternar entre as páginas. 

## Passos para Reproduzir (para bugs)
1. Acesse o modulo parlamentar
2. Acesse pesquisar parlamentar
3. Clique na pagina 2
4. Clique na página 1

## Imagens do Ocorrido
![1](https://user-images.githubusercontent.com/99340689/153220384-2f8179d0-7907-4e1b-a592-dce21129f696.png)
![2](https://user-images.githubusercontent.com/99340689/153220420-d03e87a9-65a8-469a-9506-b395843afb84.png)
![3](https://user-images.githubusercontent.com/99340689/153220454-bbfbf91d-ac27-438e-b789-cc536ed0b56e.png)

## Seu Ambiente
* Versão usada (_Release_): Release: 3.1.162-RC19
* Nome e versão do navegador: Chrome 98.0.4758.82 (Versão oficial) 64 bits
* Nome e versão do Sistema Operacional (desktop ou mobile): Windows 10 PRO
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by edwardoliveira** [comment]
Esse erro foi consertado no release 3.1.162-RC20. Favor confirmar.
