### ISSUE TITLE
  Anexação de Documentos Administrativos

### ISSUE THREAD

**Issue by lucasdinizpn** [interlegis/sapl#3509]
## Comportamento Esperado

Venho através desta solicitação requerer, caso seja possível, uma mudança no SAPL para que possam ser anexados documentos administrativos nas matérias legislativas. Com esta mudança poderíamos anexar ofícios e respostas que sejam relacionados as indicações e requerimentos, demostrando assim todo processo da matéria. No campo 'anexada' só é possível anexar documentos da mesma natureza ficando sem anexar ofícios e reposta relativos a esta matéria.

Desde já agradeço a atenção!

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Contexto

Anexar documentos administrativos nas matérias legislativas.

## Seu Ambiente

* Versão usada (_Release_): 3.1.162-RC19
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by andreagudo** [comment]
Issue semelhante/alternativa: #3326

Em qua, 16 de fev de 2022 13:06, lucasdinizpn ***@***.***>
escreveu:

**Comment by RuiterSilva** [comment]
Bom dia. Também gostaria muito que tivesse essa funcionalidade. Para direcionar os documentos administrativos para os documentos acessórios, no momento de subir o texto integral eu salvo o link da página referente ao documento que quero anexar e salvo faço em um arquivo .htm que direciona o conteúdo, para eu não precisar ficar subindo o documento 2 vezes.
Segue o código que uso para direcionamento em html.
[Reenvio TXT.txt](https://github.com/interlegis/sapl/files/8261715/Reenvio.TXT.txt)


Evidentemente, seria bem melhor se quando o Documento Administrativo fosse criado após o protocolo, tivesse a opção de anexá-lo a uma Matéria Legislativa.

**Comment by LeandroJatai** [comment]
Foi resolvida pela #3326 na aba Matérias Vinculadas nos documentos administrativos.
