### ISSUE TITLE
Erro no extrato da Sessão Plenária

### ISSUE THREAD

**Issue by neynunes** [interlegis/sapl#3515]
O SAPL da Câmara Municipal de Formosa (Versão 3.1.162-RC19) está apresentando um erro ao gerar a ata eletrônica no módulo Sessão Plenária. A ata gerada pelo Sistema apresenta o resultado de votação (Sim, Não, Abstenção), mesmo marcando a matéria como somente Leitura. 

## Comportamento Esperado
Suprimir o resultado de votação no extrato da Sessão Plenário quando tratar-se de matérias para leitura

Nas matérias selecionadas como somente leitura devem aparecer somente as seguintes informações:
1. Identificação da matéria;
2. Autor;
3. Número de Protocolo; e 
4. Tipo.

## Comportamento Atual
Ao gerar a ata eletrônica (extrato da Sessão Plenária), o SAPL inclui o resultado das votações nas matérias marcadas como somente leitura.

## Passos para Reproduzir (para bugs)
Segue o link de uma ata com o erro descrito: 
https://sapl.formosa.go.leg.br/sessao/603/resumo_ata

## Contexto
<Da forma como o problema está ocorrendo, além de gerar um extrato da Sessão mais extenso, ainda confunde os parlamentares.>

## Seu Ambiente
* Versão usada: 3.1.162-RC19
* Nome e versão do navegador: Google Chrome
* Nome e versão do Sistema Operacional (desktop ou mobile): Windows 10

**Comment by edwardoliveira** [comment]
Este erro foi corrigido ontem e estará disponível na nova versão do SAPL, a ser lançada no início da semana que vem.

**Comment by neynunes** [comment]
Grato! 
--
Enviado do aplicativo Universal Email App para Android sexta-feira, 04 março 2022, 09:47AM -03:00 de Edward  ***@***.*** :
