### ISSUE TITLE
Verificar existência de texto compilado de normas

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3522]
## Comportamento Esperado
Verificar a existência do texto compilado das Leis 1054/1996 e 1201/1998.

## Comportamento Atual
Meus registros indicam que elas foram compiladas e publicadas, mas os textos compilados não aparecem no sistema.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/norma/pesquisar

## Contexto
Verificação de texto compilado.

## Seu Ambiente
Versão usada (Release): 3.1.162-RC18
Nome e versão do navegador: Versão 99.0.4844.51 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 18.04 64 bits

**Comment by edwardoliveira** [comment]
Este tipo de solicitação deve ser feito pelo OSTicket para os sistemas hospedados no Interlegis. No caso ano=1996, numero=1054 não possui TextoCompilado enquanto ano=1998, numero=1201 possui.

**Comment by andreagudo** [comment]
Obrigado. Porém, no caso da  ano=1998, numero=1201, o texto compilado não aparece.
