### ISSUE TITLE
Numeração automática de sessão plenária

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3523]
## Comportamento Esperado
Ao adicicionar sessão plenária o sistema deve oferecer o número da sessão seguinte, conforme o tipo.

## Comportamento Atual
O sistema funcionava corretamente até meados de 2021, mas passou a oferecer o número 1 para qualquer tipo.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/sessao/create

## Contexto
Adição de sessão plenária.

## Imagens do Ocorrido
![Captura de tela de 2022-03-22 09-34-05](https://user-images.githubusercontent.com/19169882/159483524-dc629fd0-b19c-4bc2-b38a-d7e179cdce22.png)

## Seu Ambiente
Versão usada (Release): 3.1.162-RC18
Nome e versão do navegador: Versão 99.0.4844.51 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 18.04 64 bits

**Comment by edwardoliveira** [comment]
Segundo consta, esse erro já foi corrigido. Mas se ainda persistir na casa de vcs, podem reabrir esse ticket.

**Comment by andreagudo** [comment]
Infelizmente ainda tenho que editar o número. Considerar #3494

**Comment by Gustavo274** [comment]
Conforme informado este erro aparentemente já foi resolvido. Se esse erro persistir mesmo com a nova versão, por favor nos informar que iremos tentar ver o que pode ser feito.

**Comment by andreagudo** [comment]
Issue resolvida na Release: 3.1.163-RC1
