### ISSUE TITLE
Adicionar filtro à pesquisa de norma jurídica

### ISSUE THREAD

**Issue by robsonscuzziato** [interlegis/sapl#3525]
Boa tarde, me foi solicitado pelo dpto. Legislativo da nossa Câmara, a inserção de um campo na pesquisa de norma jurídica do sistema SAPL:
https://sapl.toledo.pr.leg.br/norma/pesquisar

Eles gostariam que houvesse um campo para filtrar os resultados por norma jurídica vigente e não vigente. Um campo assim: "Vigente?", com as opções Sim e Não. Assim, poderiam pesquisar todas as normas já revogadas ou as não revogadas.

**Comment by edwardoliveira** [comment]
O SAPL já dispõe de um relatório de normas por vigência. Fica em Atividade Legislativa -> Relatórios -> Normas por Vigência.
