### ISSUE TITLE
Pesquisa textual de norma jurídica

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3529]
## Comportamento Esperado
Deve ser possível a pesquisa textual dentro das normas jurídicas

## Comportamento Atual
Tal pesquisa deixou de funcionar.

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/sistema/search/

## Contexto
Pesquisa textual em normas jurídicas.

## Imagens do Ocorrido
![Captura de tela de 2022-03-28 14-10-26](https://user-images.githubusercontent.com/19169882/160451725-a2fdf60d-42ea-4626-b7b0-8732b461127f.png)
![Captura de tela de 2022-03-28 14-10-55](https://user-images.githubusercontent.com/19169882/160451744-02e0d3d9-65f3-4f9b-b860-cbead26122a3.png)

## Seu Ambiente
Versão usada (Release): 3.1.162-RC18
Nome e versão do navegador: Versão 99.0.4844.84 (Versão oficial)
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 20.04 64 bits

**Comment by Gustavo274** [comment]
O problema já foi resolvido com a release do Sapl 3.1.162-RC20.

**Comment by andreagudo** [comment]
Ainda não consigo encontrar a lei 781/1991 a partir da pesquisa textual da expressão "WILHEIN". O que pode estar havendo?

**Comment by edwardoliveira** [comment]
O texto foi escaneado como imagem. Nós desabilitamos o OCR automático de PDFs quando do upload para o SAPL por questões técnicas e de hospedagem. Estamos trabalhando para suportar isso em breve. Enquanto isso, a sugestão é reescanear o texto com o OCR habilitado e subir um novo PDF para que este possa ser indexado adequadamente no SAPL.
