### ISSUE TITLE
Adicionar filtro à pesquisa de norma jurídica

### ISSUE THREAD

**Issue by robsonscuzziato** [interlegis/sapl#3535]
Boa tarde, me foi solicitado pelo dpto. Legislativo da nossa Câmara, a inserção de um campo na pesquisa de norma jurídica do sistema SAPL:
https://sapl.toledo.pr.leg.br/norma/pesquisar

Eles gostariam que houvesse um campo para filtrar os resultados por norma jurídica vigente e não vigente, além dos outros campos que já existem na pesquisa. 
Atualmente, o SAPL tem um  relatório de normas por vigência, porém esse relatório não permite escolher o tipo de matéria, ele mostra todas. Eles querem pesquisar, por exemplo, todas as resoluções vigentes, e esse relatório só permite pesquisar TODAS as matérias vigentes ou não vigentes, não permite selecionar um tipo de matéria. A página de pesquisa de normas jurídicas permite selecionar o tipo de matéria a ser pesquisada, porém não permite filtrar por vigente ou não vigente.

**Comment by edwardoliveira** [comment]
Neste caso, é mais prático adicionar um campo opcional 'Tipo de Norma' no relatório de normas por vigência.

**Comment by edwardoliveira** [comment]
<img width="1097" alt="Screen Shot 2022-04-19 at 12 01 32" src="https://user-images.githubusercontent.com/9326037/164034576-da41dccf-6740-4501-868c-b042570ef966.png">

Adicionamos esse parâmetro no relatório de Norma por Vigência. Estará disponível na versão do SAPL posterior a 3.1.162.

**Comment by robsonscuzziato** [comment]
Era isso mesmo Eduardo, obrigado.

**Comment by edwardoliveira** [comment]
Meu nome é Edward, não Eduardo.
