### ISSUE TITLE
Relatório Administrativo usando como filtro “Data Fim Prazo”

### ISSUE THREAD

**Issue by informaticacmcl** [interlegis/sapl#3538]
## Comportamento Esperado

Relatório que tenha como filtro “Matéria Legislativa”, Ano, “Status” e o campo “Data Fim Prazo” inserido na Tramitação para sabermos quais prazos estão vencidos.
Exemplo: Requerimento; 2022; “Aguardando resposta”; 10/04/2022.

## Comportamento Atual

Hoje é possível filtrar as Matérias Legislativas pelo “Status” inserido na tramitação, Ano e “Matéria Legislativa”, o que não nos atende por completo.

## Possível Solução

Relatório que tenha como filtro “Matéria Legislativa”, Ano, “Status” e o campo “Data Fim Prazo” inserido na Tramitação para sabermos quais prazos estão vencidos.
Exemplo: Requerimento; 2022; “Aguardando resposta”; 10/04/2022.

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Contexto

Os relatórios administrativos nos ajudam bastante por reunir as informações que queremos em um só arquivo, porém não é possível, hoje, saber quais Requerimentos ou Pareceres em Projetos estão vencidos, o que seria muito útil no cotidiano das Câmaras.

## Seu Ambiente

* Versão usada (_Release_): Sistema de Apoio ao Processo Legislativo SAPL, Release: 3.1.162-RC19
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by Gustavo274** [comment]
Bom dia. É possível fazer essa pesquisa através do Relatório Administrativo "Tramitações de Matéria" que fica dentro da aba Relatórios conforme a imagem:
![image](https://user-images.githubusercontent.com/51173319/165324539-90d4a42f-1380-4204-b6d4-0ed4c907b356.png)

Nele foi adicionado o campo "Ano" que estava faltando. Os demais campos solicitados já existiam nessa área de pesquisa.
![image](https://user-images.githubusercontent.com/51173319/165324828-fc639206-474a-4524-a104-3451e38ea4ca.png)

**Comment by informaticacmcl** [comment]
Olá, obrigada por responder.
O campo ano não aparece na nossa versão do SAPL.
Daniella I. Barros
Analista de Sistemas
Câmara Municipal de Conselheiro Lafaiete - MG
(31) 3769-8103 - 7 às 13h

26 de Abril de 2022 11:38, "Gustavo274" ***@***.*** ***@***.******@***.***>)> escreveu:
	Bom dia. É possível fazer essa pesquisa através do Relatório Administrativo "Tramitações de Matéria" que fica dentro da aba Relatórios conforme a imagem:
 (https://user-images.githubusercontent.com/51173319/165324539-90d4a42f-1380-4204-b6d4-0ed4c907b356.png) 

	Nele foi adicionado o campo "Ano" que estava faltando. Os demais campos solicitados já existiam nessa área de pesquisa.
 (https://user-images.githubusercontent.com/51173319/165324828-fc639206-474a-4524-a104-3451e38ea4ca.png)
