### ISSUE TITLE
Revogação de Normas na Compilação

### ISSUE THREAD

**Issue by geandranka** [interlegis/sapl#3562]
## Comportamento Esperado
Sugere-se que na Compilação das Normas, especificamente na Revogação de Norma Integralmente, seja possível constar a informação logo abaixo do número da lei, como por exemplo é realizado na Câmara Municipal de Jataí/GO.

## Comportamento Atual
Atualmente consta a informação de Revogado logo abaixo do dispositivo escolhido, porém quando é revogada integralmente a norma, não consta essa informação.

## Possível Solução
Uma ideia de como implementar a mudança é seguir o exemplo da Câmara Municipal de Jataí/GO, conforme foto abaixo:

![image](https://user-images.githubusercontent.com/57186085/172438443-dd8b54c5-bfc4-414a-a88f-36664b0e84ed.png)

## Passos para Reproduzir (para bugs)
Não possui.

## Contexto
O problema afeta no sentido de que a informação de revogação não fica claramente exposta ao usuário

## Imagens do Ocorrido
Não possui

## Seu Ambiente
Versão usada (Release): 3.1.163-RC1
Nome e versão do navegador: Chrome
Nome e versão do Sistema Operacional (desktop ou mobile): Desktop Windows
Link para o seu projeto (Caso de fork deste projeto):

**Comment by LeandroJatai** [comment]
Feito:
![image](https://user-images.githubusercontent.com/9630623/172847428-fa55afb8-58ce-4ee4-bdb7-20341a5d44ff.png)
