### ISSUE TITLE
Parametrizar linearidade de tramitação de matérias

### ISSUE THREAD

**Issue by LeandroJatai** [interlegis/sapl#3574]
O Sapl 3.1 foi implementado com as tramitações de matérias lineares, sendo possível o registro de unidades sequenciais. No entanto até a versão 3.0 essas tramitações poderiam ser registradas com múltiplos encaminhamentos, para tornar isso possível no 3.1, existem  duas saídas: a) permitir via Configurações da Aplicação que seja parametrizado o congelamento do sequenciamento único dando ao gestor a decisão se assim será; e b) transformar o registro em um grafo.

**Comment by edwardoliveira** [comment]
Vc fez o PR e este foi integrado ao 3.1.x. Podemos fechar essa issue?
