### ISSUE TITLE
Menu secundário incorreto nos cadastros nas tabelas auxiliares.

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#358]
Ao concluir um adição ou entrar em uma edição de registros nas tabelas auxiliares, o menu secundário (MS) que é adicionado está incorreto. Está sendo adicionado o de sua funcionalidade principal, por exemplo, ao adicionar um Tipo de Matéria legislativa, aparece no detail e no edit, o MS da edição de MatériaLegislativa... ao adicionar um Tipo de Comissão, o MS que aparece em detail e em edit o MS de Comissão.

**Comment by eduardoedson** [comment]
Relacionada a #387

**Comment by marciomazza** [comment]
Fechei a issue #387 como duplicada desta.

**Comment by edwardoliveira** [comment]
@LeandroRoberto @eduardoedson Esta issue foi corrigida, não?

**Comment by eduardocalil** [comment]
Era para estar corrigida. Entretanto, o menu continua incorreto nas telas de proposições.

**Comment by LeandroRoberto** [comment]
o subnav pode ser retirado de funcionalidades que estão dentro da mesma app... feito aqui:
https://github.com/interlegis/sapl/commit/8181e0c3e1544a3fd1b273b0c91ba7a8ab2e9470
Caso a Proposições necessite de um menu particular, basta criar um arquivo, por exemplo subnav_proposicao.yaml, e colocar o caminho no contexto.
