### ISSUE TITLE
Reduzir tamanho das entrelinhas no relatório Matérias em Tramitação

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3580]
## Comportamento Esperado
O espaço das entrelinhas deve ser o mesmo de outros relatórios, como o de Matérias Legislativas. Deve ser mantido um espaço maior entre cada matéria.

## Comportamento Atual
O espaço está muito grande.

## Passos para Reproduzir (para bugs)
Acessar Relatórios, Matérias em Tramitação, selecionar ano 2022.

## Contexto
Relatório de Matérias em tramitação.

## Imagens do Ocorrido
![Captura de tela de 2022-07-05 15-04-10](https://user-images.githubusercontent.com/19169882/177389073-f5e4f3de-383e-4ff1-b15e-c5e3f6c82c87.png)
![Captura de tela de 2022-07-05 15-04-53](https://user-images.githubusercontent.com/19169882/177389140-a35e8c80-23e0-487b-bf52-46b68277d16a.png)

## Seu Ambiente
Versão usada (Release): 3.1.163-RC2
Nome e versão do navegador: Versão 103.0.5060.53 (Versão oficial) snap 64 bits
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 20.04.4 64 bits

**Comment by edwardoliveira** [comment]
Novo layout para relatório Matérias em Tramitação

<img width="1123" alt="Screen Shot 2022-07-06 at 19 28 24" src="https://user-images.githubusercontent.com/9326037/177653890-967fac0e-51ba-4edf-b8dc-5dc9954037ee.png">
