### ISSUE TITLE
Título divergente em tabelas auxiliares.

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#359]
Em /sistema/ no módulo de Comissões aparece na segunda linha de links, "Tipo de Proposição" mas é um link para "Tipo de Comissão"

**Comment by edwardoliveira** [comment]
@LeandroRoberto Sabe me dizer se essa issue foi resolvida??? Em tabelas auxiliares, "Tipo de Proposição" aponta para o link correto, não?

**Comment by LeandroRoberto** [comment]
registrando aqui... encaminhei imagem...

**Comment by edwardoliveira** [comment]
![image_2016-05-16_13-25-17_304227149349388337](https://cloud.githubusercontent.com/assets/9326037/15296224/bc0f6c6e-1b6a-11e6-855c-708b8285a11d.png)
