### ISSUE TITLE
Erro ao adicionar anexado em lote em documento administrativo

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3590]
## Comportamento Esperado
A adição deve retornar todos os documentos que atendam as critérios da pesquisa.

## Comportamento Atual
Erro 500. 

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/docadm/1273/anexado_em_lote

## Contexto
Adição de documento administrativo anexado em lote a outro documento administrativo.

## Imagens do Ocorrido
![Captura de tela de 2022-08-19 13-22-36](https://user-images.githubusercontent.com/19169882/185664956-45f4258e-1b0e-4404-ba2c-95ceb1e6593b.png)
![Captura de tela de 2022-08-19 13-22-57](https://user-images.githubusercontent.com/19169882/185664965-0058cd88-0903-40e0-9a95-ff19ea6c7361.png)

## Seu Ambiente
Versão usada (Release): 3.1.163-RC4
Nome e versão do navegador: Versão 104.0.5112.79 (Versão oficial) snap 64 bits
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 20.04.4 64 bits

**Comment by edwardoliveira** [comment]
O conserto deste bug estará disponível no próximo release do SAPL
