### ISSUE TITLE
Impressão da Tramitação de Matéria Específica.

### ISSUE THREAD

**Issue by hljuninho** [interlegis/sapl#3608]
## Comportamento Esperado
Funcionalidade que gere uma impressão ou arquivo pdf das tramitações de uma matéria específica.

## Comportamento Atual
Não existe.

## Possível Solução
Botão de impressão na guia de trâmites da matéria.
Relatório de trâmites de matéria.

## Contexto
Embora seja uma situação simples, é de grande importância para compor as capas impressas das matérias da Câmara Municipal de Varginha.

## Imagens do Ocorrido
![image](https://user-images.githubusercontent.com/27967696/192026604-ded4c1cf-6059-4c0f-ae8b-6fda770e63f6.png)

## Seu Ambiente

* Versão usada (_Release_): 3.1.163-RC6

**Comment by edwardoliveira** [comment]
Essa funcionalidade encontra-se implementada atualmente no SAPL.
