### ISSUE TITLE
Erro ao acessar link Ajuda

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#361]
Erro ao clicar no link indice
![sapl31-ajuda](https://cloud.githubusercontent.com/assets/2106377/14924996/84b39d46-0e1b-11e6-9694-cf9851b5748d.png)

**Comment by morale** [comment]
Ao clicar na opção índice no rodapé apresenta essa falha...

**Comment by morale** [comment]
reaberto

**Comment by marciomazza** [comment]
@morale em que tela no sistema vc achou esse link?
