### ISSUE TITLE
Ordem de reuniões de comissões

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3617]
## Comportamento Esperado
A ordem deve ser pelos critérios de dada e de nome, ambos decrescentes.

## Comportamento Atual
Há apenas o critério de data decrescente. 

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/comissao/15/reuniao

## Contexto
Pesquisa por reuniões de comissão.

## Imagens do Ocorrido
![Captura de tela de 2022-10-19 16-14-42](https://user-images.githubusercontent.com/19169882/196783539-047a029f-579a-4cd5-b416-0b57ecee792d.png)

## Seu Ambiente
Versão usada (Release): 3.1.163-RC8
Nome e versão do navegador: Versão 104.0.5112.79 (Versão oficial) snap 64 bits
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 20.04.4 64 bits

**Comment by edwardoliveira** [comment]
Fizemos a alteração. Mas como o nome da reunião é um campo texto e vcs numeraram as reuniões, as ordenação vão sair assim:

```
19/10/2022          1
19/10/2022         10
....
19/10/2022         2
19/10/2022.        20
...
19/10/2022.        3

```

Pra evitar isso teria que colocar um número de '0' (zeros) na frente: 001, 002, 003, etc. Desta forma a ordenação vai sair:

```
19/10/2022          001
19/10/2022          002
....
19/10/2022         010

...
19/10/2022.        020

```
