### ISSUE TITLE
Legislaturas - bug no link Ajuda e falta indicação ordinal

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#362]
1. falha ao clicar no link Ajuda
2. faltando a indicação ordinal da legislatura

**Comment by morale** [comment]
nota: o ordinal deve ser no feminino ... 1ª, 2ª ... e não 1º, 2º por tratar-se de legislaturas

**Comment by morale** [comment]
Deverá ser possível ao usuário indicar qual a Legislatura.

**Comment by edwardoliveira** [comment]
A questão do ordinal feminino foi resolvido no commit 722392f , as outras ainda estão em aberto.

**Comment by marciomazza** [comment]
A questão da ajuda está delegada a issue #470.

Não entendi o que quer dizer
> faltando a indicação ordinal da legislatura

@morale pode explicar melhor?

**Comment by marciomazza** [comment]
Estou concluindo que essa issue está em parte resolvida pelo commit 722392f e em parte delegada à issue #470.
