### ISSUE TITLE
Erro ao realizar arquivo - /api/materia/proposicao - Erro ao adicionar arquivo

### ISSUE THREAD

**Issue by ikarofsouza** [interlegis/sapl#3627]
Preciso de um exemplo de request com status de sucesso quando se é enviado o parâmetro "texto_original", pois tentei enviar como base64 e link com e sem extensão de arquivo, mas dava erro dizendo que o arquivo não e aceito e quando envio em multipart/form-data dá erro 500. Alguém tem alguma solução para esse problema?

curl --location --request PUT 'https://sapl.xxxxxx.mg.leg.br/api/materia/proposicao/125834' \
--header 'accept: application/json' \
--header 'Content-Type: multipart/form-data' \
--header 'Authorization: token xxxxx' \
--form 'texto_original=@"/F:/-Meus Documentos/Downloads/TESTE.pdf"'

- O campo texto_original é um arquivo, há restriçoes com relaçao aos formatos aceitos, mas, basicamente sao aceitos arquivos texto (pdf,doc,txt), no uso da api, essa variavel deve ser enviada como Multipart file, voce pode realizar a operacao em duas etapas, criando o registro da proposicao e depois utilizando o request PUT para alterar/incluir dados em qualquer um dos campos disponiveis.

Tentei a solução acima, mas sem sucesso.

**Comment by LeandroJatai** [comment]
@ikarofsouza a issue foi resolvida, podemos fechar?
