### ISSUE TITLE
Coligação - Fazer tela mestre-detalhe para Partidos que compõem a coligação

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#363]
1. Faltando selecionar os partidos que compõem a coligação - (selecionar a sigla partir dos existentes não extintos)

**Comment by morale** [comment]
Deve disponibilizar uma função via link - composição - onde o usuário possa selecionar os partidos que compõem a coligação.

**Comment by eduardoedson** [comment]
Fazer um mestre-detalhe dos partidos. Semelhante a parlamentares em comissão.
