### ISSUE TITLE
Alteração nos Relatórios do SAPL - Relatório Presença nas Sessões

### ISSUE THREAD

**Issue by InterlegisPI** [interlegis/sapl#3642]
Então pessoal, somos um setor que funciona dentro da Assembleia Legislativa com intuito de sermos multiplicadores dos serviços do Interlegis em nosso estado, no caso o Piauí, e também nós damos suporte aos setores aqui da ALEPI no dia a dia, dentro dos usos do SAPL e do PM.

Durante as utilizações do SAPL, e também por conta de algumas notícias veiculadas na mídia local, encontramos alguns problemas, mas especificamente falaremos de um problema dentro de Relatório de Presenças.

Saiu na mídia um baixo número de presença dos Deputados, mas os mesmo deputados fizeram as suas justificativas, e essas justificativas são cadastradas diretamente na sessão, e mesmo que esteja cadastrada esta justificativa, o número de presenças obviamente não subirá.

Por isso chegamos na conclusão em uma possível alteração que pelo menos para o problema atual da ALEPI irá resolver, e creio que possa ser uma solução viável para o uso comum de todas as casas legislativas.

 - A solução:
         Criação de mais uma coluna que fique no "Relatórios Administrativos - Presença nas Sessões". Qual seria essa coluna? A coluna seria "Presenças Justificadas", que ficaria logo depois da coluna "Ordem do Dia", trazendo as informações através dos cadastros dentro das sessões.

Gostaríamos de solicitar também a criação dentro desse módulo de "Relatórios", a inclusão de um campo de observações, por exemplo:

- Dentro desse campo poderíamos incluir observações Legais, em que citamos o Regimento Interno da casa, informação que valida o prazo de 15 dias em que o parlamentar pode apresentar a justificativa da sua ausência naquela sessão que ele faltou.

Ainda solicitando para dentro dos relatórios, gostaríamos que no Módulo de Relatórios dentro de Tabelas Auxiliares, pudessem existir a opção de mostrar ou ocultar algum tipo de relatório que fosse ou não fosse considerado útil pela casa legislativa.

Tivemos uma reunião com o Adalberto, onde apresentamos nosso problema e ele concordou com a efetiva necessidade dessas mudanças.

* Versão usada (Release: 3.1.163-RC12)
* https://sapl.al.pi.leg.br

Segue uma imagem ilustrando como gostaríamos que ficasse.
[Presença dos parlamentares nas sessões.pdf](https://github.com/interlegis/sapl/files/11566466/Presenca.dos.parlamentares.nas.sessoes.pdf)

Grato, pela atenção! 

@morale 

Att. James Medeiros
Coordenador Interlegis-PI

**Comment by LeandroJatai** [comment]
@edwardoliveira essa issue foi resolvida por https://github.com/interlegis/sapl/commit/a85080891ff3b8d95f056fe5b4a39f2f4def7bba ?

#3676 é uma duplicata de #3642?? para o usuário que criou #3676, dei o feedback que o commit citado acima resolveu a questão, deixo pra vc atestar e fechar as issues cabíveis.

**Comment by joaohortsenado** [comment]
Issue duplicada, conforme informado pelo @LeandroJatai , já foi atendida pelo commit https://github.com/interlegis/sapl/commit/a85080891ff3b8d95f056fe5b4a39f2f4def7bba
