### ISSUE TITLE
Sessão Legislativa - Permitir às casas controlar a numeração da Sessão Legislativa

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#365]
O número da sessão legislativa não deve ser controlado pelo sistema. Algumas casas fazem a numeração seguida independente da legislatura.

**Comment by LeandroRoberto** [comment]
existem três questões relevantes no cadastro de dados básicos de sessão legislativa:
1) dar mais uma coluna para número tirando uma coluna de legislatura
2) data de encerramento  não pode ser menor que data de abertura
3) hora de encerramento (se preenchida) não pode ser menor que hora de abertura
4) os campos de horários estão aceitando qualquer coisa, limitado ao espaçamento da máscara
 uma quase solução seria:
`
.mask("Hh:Mm", {placeholder:"hh:mm",
    	translation: {
			  H:{pattern:/[012]/},
			  h:{pattern:/[0-9]/},
			  M:{pattern:/[0-5]/},
			  m:{pattern:/[0-9]/}
			  }
		  });
`
mas ainda fica com problemas para horas igual ou acima de 20... pois ainda permite ter 24, 25,... 29 horas

**Comment by eduardoedson** [comment]
Fechado pois o número é um campo que pode se preenchido pelo usuário.
