### ISSUE TITLE
Criar pesquisa simplificada de matérias legislativas

### ISSUE THREAD

**Issue by gustavokrm** [interlegis/sapl#3658]
**Problema**

Ao abrir a pesquisa de matérias legislativas, o usuário encontra diversos campos para serem preenchidos, e esse comportamento pode confundi-lo, dificultando que ele encontre a matéria ou norma desejada. 

Todos esses campos extras a partir da label "Como listar os resultados de pesquisa" não são tão necessários caso o usuário deseje apenas buscar uma matéria, pois são filtros avançados. Usuários que não possuam conhecimento do processo legislativo ou de informática podem entender que necessitam preencher vários desses campos para poderem ter acesso à matéria.
 
Normalmente, um usuário que deseje buscar informações sobre uma matéria de um determinado político, buscaria com as informações providas no campo de Pesquisa Básica.

Devido à quantidade de campos na pesquisa padrão, algumas casas legislativas têm optado por colocar, por padrão, uma pesquisa pronta dentro de um iframe. Isso não é o ideal, pois, dependendo da quantidade de matérias, dificultaria a pesquisa, e não há uma maneira fácil de retornar à interface de pesquisa. O ideal seria que a pesquisa fosse fácil de fazer. Por exemplo, se eu quero buscar os projetos de lei de um Vereador X, eu tenho o tipo de matéria e o autor dela, mas não vou saber preencher os outros campos.

**Possível solução**

O usuário, ao clicar na pesquisa de matérias legislativas, teria acesso a um interface simplificada, com os campos da pesquisa básica somente (tipo de matéria, pesquisar expressões, número, número do protocolo, ano da matéria), e os demais campos dentro de uma aba chamada "Pesquisa avançada", a qual pode ser descoberta através de um clique. Isso ajudaria na acessibilidade do sistema, pois permitiria que fosse mais fácil realizar buscas simples dentro do sistema, tanto para servidores quanto para os eleitores.

**Contexto**

Essa issue surgiu de uma discussão no Discord em que algumas pessoas relataram o mesmo problema, de que seus usuários teriam reclamado da acessibilidade da página de pesquisa atual, gerando dificuldade em encontrar as matérias que precisam.

**Comment by hermesalvesbr** [comment]
É uma excelente idéia, uma alternativa de solução seria criar um endpoint de busca na api , pois assim qualquer site poderia integrar na busca.

**Comment by gustavokrm** [comment]
Fiz um protótipo de como ficaria a tela de pesquisas de matérias legislativas.
![SAPL - protótipo pesquisa matérias(4)](https://github.com/interlegis/sapl/assets/1418584/13d8f590-9e62-4929-b201-2554a1d84c6a)

Adicionei um aviso mostrando ao usuário que não é necessário preencher todos os itens para poder reaver uma matéria de seu interesse. 
Os demais campos ficariam escondidos, e seriam ativados quando o usuário clicar em Pesquisa Avançada. 
[Link do design no figma](https://www.figma.com/file/9vwYcRWdO5HMqfv1QeczUm/SAPL---prot%C3%B3tipo-pesquisa-mat%C3%A9rias?type=design&node-id=0%3A1&mode=design&t=KnmxHz6s4MrFNaPq-1)

**Comment by cristian-longhi** [comment]
Com base no protótipo da tela, fiz a implementação das alterações.

Sem exibir os campos para pesquisa avançada - padrão de tela inicial:

![image](https://github.com/interlegis/sapl/assets/22030378/fde18f44-bbdc-4845-bc0d-413f991db933)

E com a pesquisa avançada sendo exibida:

![image](https://github.com/interlegis/sapl/assets/22030378/d367ac6d-606c-4bfa-a58c-a2bb1ef29544)

**Comment by joaohortsenado** [comment]
Issue atendida pelo PR 3662
