### ISSUE TITLE
Exibir a ementa nas matérias das comissões

### ISSUE THREAD

**Issue by hjuninho00** [interlegis/sapl#3665]
## Comportamento Esperado
Exibir a ementa nas informações da lista de matérias legislativas em tramitação de uma comissão específica.

## Comportamento Atual
O SAPL traz algumas informações como autor, situação e prazos na exibição das matérias em tramitação de uma comissão específica, no entanto, para uma identificação mais ágil da matéria seria necessário incluir o dado da ementa.

## Possível Solução
Incluir a coluna da ementa da matéria na consulta do banco de dados que traz a lista de matérias em tramitação da comissão.

## Imagens do Ocorrido
![image](https://github.com/interlegis/sapl/assets/114252780/23e3a250-0345-40d0-9dfd-d6e65fd03e6b)

## Seu Ambiente
* Versão usada (Release: 3.1.163-RC13)

**Comment by joaohortsenado** [comment]
@hjuninho00 o problema de colocar a ementa é que muitas casas escrevem ementas imensas, e isso já levaria a termos reclamaçoes por conta da desfiguraçao do relatorio. Estou pensando aqui se, caso estipulassemos um tamanho máximo pra ementa... Na tela é razoavelmente simples de resolver, poderiamos usar um efeito accordeon (menu de recolher) na parte da ementa pro caso dela ser muito grande... mas ainda teriamos que encontrar uma soluçao de design para a impressao... :(

**Comment by hjuninho00** [comment]
Uma ideia seria tabular o conteúdo e adicionar a emento em uma coluna à esquerda, da mesma forma que é exibida nas matérias da pauta da sessão:

![image](https://github.com/interlegis/sapl/assets/114252780/af45bcc3-145d-4be1-a6b6-e3e9d4e8293f)

**Comment by joaohortsenado** [comment]
@hjuninho00 obrigado pela sugestao, o PR https://github.com/interlegis/sapl/pull/3684 foi criado para atender esta issue.
