### ISSUE TITLE
Visibilidade dos números dos cronômetros no painel eletrônico

### ISSUE THREAD

**Issue by hjuninho00** [interlegis/sapl#3667]
## Comportamento Esperado
Legibilidade adequada dos cronômetros é fundamental para garantir o bom andamento das reuniões, votações e demais procedimentos.

## Comportamento Atual
O SAPL traz um tamanho inadequado para a fonte dos cronômetros no painel eletrônico, comprometendo a visibilidade dessas informações por parte pelos parlamentares e servidores presentes nas sessões plenárias.

## Possível Solução
Revisar e adequar o tamanho e a posição dos cronômetros no painel eletrônico, dando ênfase aos números, em um tamanho similar ao do relógio.

## Imagens do Ocorrido
![image](https://github.com/interlegis/sapl/assets/114252780/4a583778-e429-4b32-bc05-97a7c3564bdc)

## Seu Ambiente
* Versão usada (Release: 3.1.163-RC13)

**Comment by robsonsda** [comment]
Gostaria de pedir muito a colaboração para a implementação dessa sugestão, para o painel ter um cronômetro com números maiores, em negrito e bem aparentes e destacado. Nas sessões os vereadores reclamaram muito de:
1) Por ter 4 tipos de cronômetros que confundem eles ao observar o tempo.
2) Pelo fato dos números serem pequenos e de fonte fina, sem destaque. Eles alegam que não enxergam. Muitos já são idosos, com problemas de visão. Reclamam que não ajuda na acessibilidade.

Com isso, os vereadores várias e várias vezes pedem para arrumar o cronômetro e até para mudar o sistema. E eu como operador passo aperto nas sessões, fato que deve ocorrer em outras Casas Legislativas. Há outras sugestões aqui no Github sobre painéis e cronômetros que devem ser vistas a fim de aprimorar o painel da sessão.

Peço encarecidamente ajuda nesse sentido.

**Comment by joaohortsenado** [comment]
@hjuninho00 @robsonsda fiz um PR propondo uma solucao pra essa situacao, basicamente um script pra alterar o tamanho da fonte das secoes de cronometos e resultados. Postei uma imagem no #3691 , se quiserem baixar para testar localmente, é importante o feedback da comunidade pra afinar as melhorias
