### ISSUE TITLE
Sugestão para informar Licitação e Contratos

### ISSUE THREAD

**Issue by CMSP00** [interlegis/sapl#3670]
Gostaria de sugerir a inclusão de campos para informar os editais de licitação e contratos. O SAPL atual não fornece os campos necessários para informar licitação por completo. Faltam campos para anexar mais de uma documento. Segue em anexo o modelo do que precisamos. 
![Print 1](https://github.com/interlegis/sapl/assets/142620989/5e64e0ad-5f1e-4f02-bd15-20dd9683fd29)
![Print 2](https://github.com/interlegis/sapl/assets/142620989/1ef47231-cbe9-4adf-9458-43bc654e7392)
![Print 3](https://github.com/interlegis/sapl/assets/142620989/282f98f2-02dd-4e8d-9729-81d3b9be087c)
![Print 4](https://github.com/interlegis/sapl/assets/142620989/a57dbcbc-2ccd-4188-b279-61d8ee823fe1)
![Print 5](https://github.com/interlegis/sapl/assets/142620989/b0349ffd-4e3d-4051-94bf-5d8f7e500b79)

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Seu Ambiente

* Versão usada (_Release_):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by angelomarcondes** [comment]
Bom dia @CMSP00. 

Obrigado pela sua sugestão, é sempre bom ter pessoas como você contribuindo para podermos evoluir este grande projeto que é o SAPL.

Como você já deve ter observado o SAPL é o **sistema de apoio ao processo legislativo**, e tem como seu principal objetivo atender os anseios do **processo legislativo** de uma parlamento (câmara, assembléia, dentre outros).

No caso os processos de licitações, compras, contratos e afins, não são processos legislativos, mas sim tratam-se de processos administrativos. 

Assim, sabendo que eu posso não ter entendido bem a sua sugestão/contribuição. Gostaria que explicasse melhor, qual seria a finalidade de informar editais de licitação e contatos, no SAPL.

Abraços.

PS: Creio que o portal modelo, seja a ferramenta ideal para atender a sua demanda. Já que nela você poderá publicar qualquer tipo de conteúdo, inclusive criar uma seção só para licitações. Veja este exemplo [https://www.iturama.mg.leg.br/transparencia/licitacoes-e-contratos/anos-anteriores/contratos](https://www.iturama.mg.leg.br/transparencia/licitacoes-e-contratos/anos-anteriores/contratos)

**Comment by CMSP00** [comment]
Boa tarde!
A minha dúvida mesmo é se eu consigo por meio da SAPL informação as licitações realizadas pela câmara. Eu fiz esse caminho: Documento Administrativo - Pesquisar Documento Administrativo - Adicionar documento administrativo. Nesse caminho eu consigo informar as licitações/contratos ou seria por um sistema diferente do SAPL?

![Sem título](https://github.com/interlegis/sapl/assets/142620989/480b0378-3ff8-4c87-b452-6b4503e2a228)

**Comment by angelomarcondes** [comment]
Boa tarde @CMSP00, 

Que bom que você respondeu. Eu fico muito feliz em podermos conversar sobre isso.

IMHO esta não será a melhor ferramenta para a publicação de processos licitatórios e contratos, já que a quantidade de informações contidas nos campos é bem restrita. Sugiro novamente a utilização do portal modelo.

Creio que o foco do SAPL seja o processo legislativo, e a aba documentos administrativos são para catálogo de **documentos administrativos** ligados ao processo legislativo, veja neste link um exemplo de uso de interessante [https://sapl.piumhi.mg.leg.br/docadm/pesq-doc-adm](https://sapl.piumhi.mg.leg.br/docadm/pesq-doc-adm)

**Comment by CMSP00** [comment]
Ok. Vou usar o Portal Modelo para isso. Obrigado!
