### ISSUE TITLE
Link para abrir as correspondência e as matérias em uma nova aba na tela Pauta da Sessão 

### ISSUE THREAD

**Issue by roberiorebeca** [interlegis/sapl#3675]
Na tela de Pauta da Sessão, onde os parlamentares da casa acompanha a pauta da sessão, não tem um link para abrir as correspondências recebidas, ficando a cargo da secretaria incluir o hiperlink para facilitar para o secretário fazer a leitura das correspondência.
Hoje temos o link somente nas matérias do expediente, e ele abre na mesma guia. Se o secretário não se atentar, ele fecha a tela da matéria que acabou de ler, e pra dar seguimento precisa abrir o navegador, consultar a sessão e procurar qual o próximo documento a ser lido.

## Comportamento Esperado

Abrir as Correspondências direto da tela de Pauta da Sessão em uma nova guia, e as Matérias também colocar a opção para abrir em nova aba, pois quando o secretaria acabar de fazer a leitura, ele pode voltar na aba anterior e dar sequencia nos trabalhos.

## Comportamento Atual

Nas correspondências não tem o hiperlink, e nas matérias tem, porem abre na mesma aba.

## Possível Solução

Incluir um hiperlink nas Correspondências abrindo em uma nova guia, e nas matérias que ja tem o hiperlink também colocar a opção para abrir em nova aba.

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Imagens do Ocorrido

- **Imagem 1** As correspondência que aparece na pauta sem o link pra abrir
![image](https://github.com/interlegis/sapl/assets/14880091/1e9a5e1e-76cd-403e-876d-843238341346)
- **Imagem 2** As matérias tem o link, porem abre na mesma aba.
![image](https://github.com/interlegis/sapl/assets/14880091/8c8fd232-2ef2-419c-adde-a4b93f459d30)
![image](https://github.com/interlegis/sapl/assets/14880091/f56dc44f-deee-4cda-ba2d-c62568c5628a)

## Seu Ambiente

* Versão usada (_Release_): Release: 3.1.163-RC13
* Nome e versão do navegador: Google Chrome - Versão 116.0.5845.141 (Versão oficial) 64 bits
* Nome e versão do Sistema Operacional (desktop ou mobile): Desktop
* Link para o seu projeto (Caso de fork deste projeto): https://github.com/roberiorebeca/sapl

**Comment by joaohortsenado** [comment]
O PR https://github.com/interlegis/sapl/pull/3683 foi criado para atender essa issue

**Comment by joaohortsenado** [comment]
issue atendida
