### ISSUE TITLE
Ajuste no relatório de Presença nas Sessões

### ISSUE THREAD

**Issue by j7info** [interlegis/sapl#3676]
## Comportamento Esperado

Precisamos que no relatório, seja levado em consideração as ausências justificadas.

## Comportamento Atual

No relatório aparece o percentual de ausência e presença sem levar em consideração as ausências que foram justificadas.

## Possível Solução

Sugerimos duas possibilidades.
1. Que as ausências justificadas sejam somadas às presenças.
2. Em havendo possibilidade, inserir uma coluna com o percentual de ausência justificadas, adotando essa solução, creio que seria necessário mai suma coluna com o total de presença.

## Passos para Reproduzir (para bugs)

1.
4.
5.
6.

## Imagens do Ocorrido

![Captura de Tela 2023-09-06 às 09 36 29](https://github.com/interlegis/sapl/assets/15069082/c92eabcb-4b84-4420-82c1-1b67ec42d6d6)

## Seu Ambiente

* Versão usada (3.1.163-RC13):
* Nome e versão do navegador:
* Nome e versão do Sistema Operacional (desktop ou mobile):
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by joaohortsenado** [comment]
Issue duplicada, conforme informado pelo @LeandroJatai , já foi atendida pelo commit https://github.com/interlegis/sapl/commit/a85080891ff3b8d95f056fe5b4a39f2f4def7bba
