### ISSUE TITLE
Link para matéria relatada

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#3680]
# Comportamento Esperado
Disponibilizar link para as matérias relatadas no rol de relatorias do parlamentar.

## Comportamento Atual
Tal link não existe. 

## Passos para Reproduzir (para bugs)
https://sapl.agudo.rs.leg.br/parlamentar/relatoria/785
https://sapl.agudo.rs.leg.br/parlamentar/146/relatoria

## Contexto
Consulta de relatorias do parlamentar.

## Imagens do Ocorrido
![Captura de tela de 2023-09-28 16-48-15](https://github.com/interlegis/sapl/assets/19169882/9ac0625d-7a34-43b2-99f0-27168786759b)
![Captura de tela de 2023-09-28 16-48-32](https://github.com/interlegis/sapl/assets/19169882/723bde58-cab3-417c-b63a-949346b3024f)

## Seu Ambiente
Versão usada (Release): 3.1.163-RC9
Nome e versão do navegador: 117.0.5938.92 (Versão oficial) snap 64 bits
Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 20.04.4 64 bits

**Comment by joaohortsenado** [comment]
@andreagudo criei um PR para atender essa issue, deve estar em breve em uma release, assim que for aprovado.

**Comment by andreagudo** [comment]
Essa mudança deveria estar funcionando? Se está, penso não está adequada.
1) A tela está indicando a matéria, mas sem link: https://sapl.agudo.rs.leg.br/parlamentar/146/relatoria
2) Há link para a matéria nas relatorias de uma mesma matéria, o que não é necessário, pois a tela já é da própria matéria: https://sapl.agudo.rs.leg.br/materia/11340/relatoria
Parece que houve confusão entre relatorias do parlamentar e relatorias da matéria.
