### ISSUE TITLE
Validar tipo de parlamentar, comissão, orgão, externo em Autor

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#369]
tipo: parlamentar - validar com os parlamentares cadastrados
tipo: comissão     - validar com as comissões cadastradas

**Comment by morale** [comment]
tipo: órgão - validar com os órgãos cadastrados
tipo: externo - adicionar os atributos:  cargo/função  e local

**Comment by LeandroRoberto** [comment]
#706
