### ISSUE TITLE
Unidade de Tramitação - listar por órgão, comissão, tipo e adicionar checkbox

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#372]
listar por tipo: orgão, comissão e parlamentar, o nome e uma box para selecionar/marcar "SIM" ou "NÃO", deixando marcado como default "NÃO".

**Comment by eduardoedson** [comment]
Vide #388

**Comment by eduardoedson** [comment]
Talvez fazer um calculado no model.

**Comment by marciomazza** [comment]
@morale Pode explicar melhor?

**Comment by eduardocalil** [comment]
O @morale me explicou aqui. No final das contas o que ele sugeriu é uma pesquisa por matérias em tramitação. Entretanto, isso já é feito na pesquisa comum de matérias.
