### ISSUE TITLE
Campo de pesquisa Regime de Tramitação

### ISSUE THREAD

**Issue by RodrigoNishimori** [interlegis/sapl#3722]
Foi solicitado a seguinte demanda ao nosso setor.
Solicito uma adequação nos filtros da pesquisa avançada de matéria legislativa no SAPL (https://sapl.fozdoiguacu.pr.leg.br/materia/pesquisar-materia).

Como sabem, as matérias legislativas dividem-se, quanto ao regime de tramitação, em ordinária e extraordinária (urgente).

Exemplo de tramitação em regime ordinário: [https://sapl.fozdoiguacu.pr.leg.br/materia/41372](https://sapl.fozdoiguacu.pr.leg.br/materia/41372%5B)

Exemplo de tramitação em regime extraordinário: https://sapl.fozdoiguacu.pr.leg.br/materia/43042

Como é possível observar na imagem abaixo, o regime de tramitação fica em destaque nas informações sobre o projeto (ver retângulo vermelho).
![download](https://github.com/interlegis/sapl/assets/173936174/1ec9bc4c-9805-4b24-9a2b-bdd82206e5ae)

 

Ocorre que ao pesquisar a matéria legislativa utilizando a "Pesquisa Avançada", o Regime de Tramitação não é uma opção de filtro disponível.

Nesse sentido, solicito que procedam aos encaminhamentos pertinentes para que, se possível, seja efetivada a implementação do filtro "Regime Tramitação" na pesquisa de matéria legislativa, uma vez que tal funcionalidade permitirá encontrarmos, com muita rapidez e facilidade, aquelas Matérias que estão tramitando em regime extraordinário/urgente e que, por tal caráter, merecem atenção diferenciada dos servidores, especialmente em razão do prazo da tramitação, que é muito mais exíguo do que no regime ordinário.

## Comportamento Esperado
Que no campo de pesquisa tenha o campo "Regime de Tramitação"

## Comportamento Atual
Atualmente não possui esse campo para pesquisa

## Passos para Reproduzir (para bugs)

1.
2.
3.
4.

## Contexto
A funcionalidade permitirá encontrarmos, com muita rapidez e facilidade, aquelas Matérias que estão tramitando em regime extraordinário/urgente e que, por tal caráter, merecem atenção diferenciada dos servidores, especialmente em razão do prazo da tramitação, que é muito mais exíguo do que no regime ordinário.

## Imagens do Ocorrido
![download](https://github.com/interlegis/sapl/assets/173936174/b6de1a56-ccc9-4f35-97a6-106af15efada)
![image](https://github.com/interlegis/sapl/assets/173936174/2b321e17-7a8f-42ed-b0b6-c79b4c200e6a)

## Seu Ambiente

* Versão usada (_Release_): 3.1.163-RC20
* Nome e versão do navegador:Google Chrome Versão 126.0.6478.114
* Nome e versão do Sistema Operacional (desktop ou mobile): Windows 10 pro
* Link para o seu projeto (Caso de fork deste projeto):

**Comment by robsonsda** [comment]
Apoiamos a sugestão.
Em Varginha-MG estamos com a mesma necessidade, pois temos vários projetos em regime de urgência que demandam consultas recorrentes.
Sugiro ainda que o regime de tramitação seja inserido após o autor (linha vermelha) quando se faz buscas de matérias para quem pesquisar saber a qual regime se tramita.
![Captura de tela 2024-06-27 155921](https://github.com/interlegis/sapl/assets/128762742/36d974af-cee1-418d-ae2e-0b37da2882dc)
