### ISSUE TITLE
[Melhoria] Incluir na pagina de Pesquisar Matéria Legislativa o campo Relatoria

### ISSUE THREAD

**Issue by kevingmq-alero** [interlegis/sapl#3727]
## Contexto

Segue sugestão de melhoria no portal SAPL do Interlegis:

Seria possível incluir na pagina de "Pesquisar Matéria Legislativa" o campo Relatoria nos resultados obtidos, logo a baixo do campo "Autor" ?? Além disso, existe a possibilidade de alimentar (cadastrar) as informações do relator, tanto nas Comissões, como também no plenário?

Segue uma imagem ilustrando a sugestão.  

![Imagem do WhatsApp de 2024-07-12 à(s) 09 19 39_46c577f8](https://github.com/user-attachments/assets/9a2bafeb-fee3-487c-a2f3-19c6ff6fae76)

## Justificativa

Essa melhoria tem sua importância, uma vez que essa informação contribui com a transparência das matérias legislativas e facilita a obtenção da informação clara e precisa do nome do relator da matéria nos resultados da busca.

**Comment by LeandroJatai** [comment]
@kevingmq-alero desenvolvi a parte de sua issue que pede a inclusão de relatorias nos resultados de pesquisa de matérias e fecharei a issue. Você faz outras sugestões na issue, sugiro que abra issues para tais questões.
