### ISSUE TITLE
Fixar tipos de autores com listagem exaustiva

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#373]
fixar somente 4 tipos. Talvez não seja necessária essa função....

1-parlamentar 
2-comissão
3-orgão  
4-externo

**Comment by eduardoedson** [comment]
Os tipos de autor são cadastrados livremente em http://localhost:8000/sistema/materia/tipo-autor/

**Comment by edwardoliveira** [comment]
@LeandroRoberto andreagudo O que vc acha? Fixamos essa lista ou deixamos de livre edição?

**Comment by LeandroRoberto** [comment]
A questão de autoria no sapl é complexa... sou contra a limitação, porém temos um problema de implementação no 3.1 que vi agora superficialmente... no sapl em produção, ou autores de comissão, parlamentar, bancada estão ligados aos registros do modelo Comissões, Parlamentares, Bancadas... como fica essa ligação? qual a relevância dessa ligação no novo SAPL? Quanto aos registros de autoria, em uma combobox com todos os autores, sem busca, pode parecer complicado... aqui em minha casa, por exemplo, só de parlamentares são mais 250, ficaria uma combo box complicada!!!

**Comment by morale** [comment]
@LeandroRoberto essa lista pode ser reduzida se considerar o mandato... a data de apresentação deve estar contida nesse período definido pelo mandato do parlamentar.

**Comment by LeandroRoberto** [comment]
com certeza... boa... isso acontece no antigo mesmo ao cadastrar matérias e ao registrar mais autorias... não sei se @edwardoliveira, @eduardoedson fizeram assim... mas a lista lá te grande... dica crucial... fica então o problema do desacoplamento de tipos de autores e os novos modelos

**Comment by morale** [comment]
@LeandroRoberto @edwardoliveira essa lista de tipos de autores é discreta e penso que se  quiserem podem prefixar num combobox.

**Comment by morale** [comment]
@LeandroRoberto poderia reescrever os tipos assim:
1-parlamentar
2-comissao
3-orgao (mesa, presidência, ...)
4-bancada
5-partido
6-externo (prefeito, tce, tcm, ...)

**Comment by LeandroRoberto** [comment]
+1
Alem da preocupação com o desapontamento!

**Comment by morale** [comment]
@LeandroRoberto como assim?

**Comment by LeandroRoberto** [comment]
Ops...  Desculpe...  Digitando pelo celular nem vi que foi errado...  A palavra é desacoplamento...  Autor da forma como está foi desacoplado,  desvinculado de usuários e de outros modelos....  No novo sapl,  Autor devia ter fks para User,  Comissoes,  Parlamentares,  Bancadas....  Ou nenhum deles

**Comment by LeandroRoberto** [comment]
#706
