### ISSUE TITLE
Cadastro de composição de comissão

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#375]
1. composição da comissão - trata-se dos parlamentares que compõem a comissão. Os parlamentares compõem a Comissão num determinado período (períodos de composição). Devem ser cadastrados num período de composição. Uma Comissão pode ter vários períodos de composição e em cada período deve ser possível cadastrar os parlamentares daquele período observando que o período de composição deve estar dentro do mandato do parlamentar.

**Comment by eduardoedson** [comment]
Esse é um mestre-detalhe de um mestre-detalhe
