### ISSUE TITLE
Parlamentar - Manter nome do parlamentar após acionamento de links de consulta

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#376]
indicar "Selecione a Legislatura" ao invés de "Selecione o período"

**Comment by morale** [comment]
Manter o nome do parlamentar após o acionamento dos links de consulta: mandatos, filiações partidárias, dependentes e proposições (este último está faltando).

**Comment by eduardoedson** [comment]
Rever templates para usar titulo e sub-titulo.

**Comment by edwardoliveira** [comment]
Estou fechando essa issue, pois como o @eduardoedson falou, as demais pendências serão resolvidas por outras issues já cadastradas.
