### ISSUE TITLE
Validar datas de Legislaturas (tabelas Auxiliares)

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#378]
1. Faltando validação entre datas. A data de Início deve ser MENOR que a de Término do período. A data da eleição também deve ser MENOR que a de início do período.

**Comment by morale** [comment]
2. O Menu mostrado na parte superior direita é indevido, portanto, não deve constar.

**Comment by eduardoedson** [comment]
A questão do menu será resolvido por #387
