### ISSUE TITLE
sapl 31: datas digitadas exigem uso de barras

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#381]
As datas estão exigindo o uso de barras em caso de digitação, o mais fácil em muitos casos. Percebi isso ao adicionar parlamentar e comissão. Vale a pena investigar outros casos.

**Comment by edwardoliveira** [comment]
Desculpa, não entendi o que seria esta issue. Poderia adicionar mais dtalhes?

**Comment by andreagudo** [comment]
Ao digitar a data, não basta digitar ddmmaaaa, como usamos no SAPL 2.5, são necessárias as barras.

**Comment by marciomazza** [comment]
Então no sapl 2.5 havia máscara nos campos de data.

**Comment by edwardoliveira** [comment]
Ah, input mask de data. :+1:

**Comment by edwardoliveira** [comment]
O plugin jQuery para adicionar máscara de data, dentre outras, já estava lá. Só faltava habilitar (pq não tinha sido ainda, não sei). Agora é procurar telas que não esteja com a classe CSS 'dateinput' que permite ao jQuery aplicar a máscara (parlamentar é uma delas, mas tem outras). A maioria das telas que vi parece que já está com a máscara.

**Comment by andreagudo** [comment]
Na tela abaixo ocorre tal problema
http://sapl31agudo.interlegis.leg.br/comissao/create

**Comment by andreagudo** [comment]
Na tela abaixo ocorre tal problema nos campos Datas de Extinção, Criação, Instalação, Prevista Término, Novo Prazo e Término
http://sapl31agudo.interlegis.leg.br/comissao/10/edit

**Comment by andreagudo** [comment]
ok.
