### ISSUE TITLE
Mesa Diretora de Sessão Legislativa anterior para o usuário operador

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#385]
A sessão legislativa que aparece para o usuário operador, logo que acessa esse módulo, não é a mais atual, como deveria.

**Comment by eduardoedson** [comment]
Colocar ordenação no model pelo campo data inicio descendente.

**Comment by andreagudo** [comment]
Vale o mesmo para o usuário anônimo: deve aparecer a Mesa Diretora atual, da Legislatura atual. Está aparecendo a da 1ª Legisaltura.

**Comment by andreagudo** [comment]
Resolvido.
