### ISSUE TITLE
Configurações de Ostensivo/Restritivo

### ISSUE THREAD

**Issue by eduardocalil** [interlegis/sapl#394]
No settings.py, deve-se criar uma constante que diga se o site seguirá a política Ostensiva ou Restritiva. Isso será decidido na instalação do sistema, de acordo com a decisão da Câmara em questão. Caso seja Ostensiva, qualquer usuário (anônimo) pode pesquisar por Documentos Administrativos. Caso seja Restritiva, usuários anônimos poderão pesquisar somente por Matérias Legislativas.

**Comment by marciomazza** [comment]
De onde veio esse requisito? Funciona assim no sapl 2.5? @morale

**Comment by morale** [comment]
a variável parâmetro de instalação que está definida no zope em sapl_documentos/props_sapl na aba properties

**Comment by paulot12** [comment]
Funcionará no SAPL 3.1?

**Comment by eribeiro** [comment]
@paulot12 Sim. Foi integrado no código do novo SAPL há 7 meses atrás. Se ninguém apagou ainda está lá. :)

**Comment by eduardocalil** [comment]
Sim. Ele pode ser configurado em Sistema -> Tabelas Auxliares -> Configurações da Aplicação

**Comment by paulot12** [comment]
O modo restritivo será configurado para os documentos administrativos?

**Comment by eduardocalil** [comment]
Será exatamente da mesma forma como é feito no SAPL 2.5

**Comment by eribeiro** [comment]
Cara, pergunta na lista do GITEC. A issue do Github NÃO É PARA RESPONDER DÚVIDA DE ISSUE FECHADA!
