### ISSUE TITLE
Sessão Plenária: botões Editar e Excluir não funcionam

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#399]
Os botões Editar e Excluir da função Sessão Plenária não funcionam (em Mesa e Ordem do Dia.., ver em outras funções da Sessão).

**Comment by edwardoliveira** [comment]
Ah, eu *acho* que a idéia é que estes botões de Editar e Excluir estejam presentes somente na tela de detalhe da Sessão (ex: /sessao/5 )

**Comment by eduardoedson** [comment]
Sim, os botões editar/excluir devem aparecer somente no detalhe. Se aparecem nas telas de sub-menu da tela, é um bug que ainda não foi resolvido.

**Comment by edwardoliveira** [comment]
@eduardoedson Sabe me dizer se isso ainda ocorre? Olhei no master e só está aparencendo no detalhe de Sessão Plenária...

**Comment by andreagudo** [comment]
A edição funciona, mas a exclusão não. Tentei excluir uma sessão, mas dá a msg abaixo:
![captura de tela de 2016-10-24 09 48 55](https://cloud.githubusercontent.com/assets/19169882/19644572/401bf15c-99cf-11e6-97c3-eb4829354e94.png)

**Comment by eduardoedson** [comment]
@andreagudo Acabei de consertar, não tem nem 5 minutos. As máquinas estão sendo atualizadas.

**Comment by edwardoliveira** [comment]
@andreagudo Se ainda não estiver funcionando pode abrir.

**Comment by andreagudo** [comment]
Resolvido.
