### ISSUE TITLE
Installation process in ubuntu

### ISSUE THREAD

**Issue by johnfelipe** [interlegis/sapl#4]
https://docs.google.com/document/d/1pDoo-C49BREhjV3qshvKuTE05Up22lpNoz48HQlAv4Y/edit?usp=sharing

Please tell me if all steps are fine, because:

![sapll](https://cloud.githubusercontent.com/assets/428820/8801316/53cb67b6-2f7f-11e5-9f78-c7b74d768c1d.png)

**Comment by marciomazza** [comment]
The version 3.1 is under development.
Most of the interface is not in place yet.

If you visit ``192.168.1.6:8000/admin`` (after creating an admin user with ``./manage.py createsuperuser``) you will be able to see the models structure.

Please stay tuned, as we advance in the next months.

**Comment by johnfelipe** [comment]
Hi please tell me about realese?

**Comment by johnfelipe** [comment]
Hi do u have date of realese

**Comment by johnfelipe** [comment]
Hi im here again, pls tell me if can i use for colombian instance, is beta release?
