### ISSUE TITLE
Inclusão de várias matérias na Ordem do Dia ou Expediente

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#40]
O SAPL deve permitir a inclusão de várias matérias simultâneamente na ordem do dia ou expediente.

**Comment by LeandroRoberto** [comment]
De a opção de escolha para a montagem da lista de matérias possíveis de inserir: 1) visualizar apenas matérias em tramitação,  independente do status...  2) filtro por status... Guarde em cookies a última escolha do usuário

**Comment by eribeiro** [comment]
O sistema atual permite apenas incluir as matérias cuja tramitação mais recente seja o plenário. Mas sim, pode ser uma boa abrir o espectro de opções.

**Comment by edwardoliveira** [comment]
O sistema atual permite apenas incluir as matérias cuja tramitação mais recente seja o plenário. Mas sim, pode ser uma boa abrir o espectro de opções.

**Comment by LeandroRoberto** [comment]
Sim te garanto que é uma boa...  Em dias de sessão e com o advento do painel de votação será cada vez mais comum a manipulação do sapl em tempo real com a sessão...   Já houve casos de eu ter que incluir várias matérias simultaneamente que não estavam previstas pra entrar e,  mesmo assim,  entraram...  Foi  sufoco...  Depois disso,  ocorreram outras vezes mas o sistema já tinha sido customizado com a alternativa de listar tudo que está em tramitação...  Voilà... Interatividade e agilidade perfeita...
