### ISSUE TITLE
Pesquisar Normas Jurídicas por assunto catalogado + bugs diversos

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#406]
Não consta opção de pesquisa da norma por assunto catalogado.

**Comment by morale** [comment]
A partir da 7a. pagina no mecanismo de paginação, desaparece o tipo de norma da lista de resultado da consulta.

**Comment by morale** [comment]
Na lista de normas - resultante da pesquisa - não consta indicação de que a norma tem texto integral e nem opção para acesso.

**Comment by LeandroRoberto** [comment]
A base de dados que serviu para essa analise, apesar de ser de Jataí, está totalmente furada e descontextualizada... sem os tipos de norma jurídica corretos e sem o Texto Articulado...

**Comment by LeandroRoberto** [comment]
sugiro que se use outras nomenclaturas para textos e mídias. Se não for possível reconhecer o tipo de mídia, talvez que se peça ao usuário que informe que tipo de mídia ele está adicionando... 
por exemplo:
- "Texto Integral" é o texto articulado gerado para visualização em html
- "Arquivo Digital" é um arquivo texto em formato .doc, .docx, .odt, .pdf, etc
- "Arquivo Digital Assinado" uma variação do tipo acima mas com assinatura digital
- "Documento Digitalizado" um documento escaneado, possivelmente em pdf.

**Comment by eduardoedson** [comment]
Duplicada #688
