### ISSUE TITLE
Adicionar opção para criar relacionamentos entre normas jurídicas

### ISSUE THREAD

**Issue by morale** [interlegis/sapl#409]
Falta a opção que permita criar relacionamentos entre normas jurídicas.

**Comment by morale** [comment]
@edwardoliveira na versão 2.5 os diversos tipos de relacionamentos encontram-se no código. Deveria criar uma tabela auxiliar para contemplar essas atualizações no sapl 31.

**Comment by eduardoedson** [comment]
@LeandroRoberto Qual a relação disso com o módulo de compilações?

**Comment by LeandroRoberto** [comment]
o módulo compilação saberá dizer os relacionamentos entre normas, porém ao nível de dispositivo e quando começarem a usar. No entanto a base legada faz isso e tem informações relevantes na tabela vinculo_norma_juridica.
![image](https://cloud.githubusercontent.com/assets/9630623/15402101/cedda8fa-1dc8-11e6-90af-d061ebf503bf.png)

essas letras no campo tip_vinculo estão fixas no código como abaixo:
![image](https://cloud.githubusercontent.com/assets/9630623/15402077/b59c0206-1dc8-11e6-9063-9e356e2bc6de.png)

**Comment by LeandroRoberto** [comment]
@eduardoedson tarefa grande aqui...

**Comment by aloysioy** [comment]
Pessoal,

Olhei o código e as tabelas rapidamente e comparando com a versão 2.5, no meu entendimento as alterações que poderiam ser feitas são:
- Alterar a tabela norma_vinculonormajuridica, acrescentando 2 colunas do tipo TEXT para os textos que irão aparecer no resultado dos vínculos (ATIVO e PASSIVO)
- Uma vez com essa alteração implementar a relação de volta (PASSIVO)

Adiantando, por enquanto estou analisando esta alteração pois como queremos implementar o SAPL e essa funcionalidade é essencial para isso. Caso algum de vocês esteja pensando diferente por favor escreva aqui. Pois irei tentar implementar o código futuramente.

**Comment by andreagudo** [comment]
Ao "Adicionar Norma Jurídica" deu o seguinte erro:
![captura de tela de 2017-02-23 09 05 01](https://cloud.githubusercontent.com/assets/19169882/23258491/46d587f0-f9a7-11e6-8b23-c2e2676c1d51.png)

**Comment by LeandroRoberto** [comment]
@edwardoliveira a maquina sapl31agudo parece estar desatualizada, esta tabela norma_vinculonormajuridica não existe mais!!!

**Comment by eribeiro** [comment]
A coluna em questão foi renomeada e a instância de teste deve ter dado algum problema na hora de atualizar o esquema de banco. Acabei de chegar e vou olhar isso.

**Comment by LeandroRoberto** [comment]
sim... está atualização tem que responder um yes/no

**Comment by edwardoliveira** [comment]
Será que tem uma opção pra colocar como "always yes"? O update é automatizado, aí esse tipo de mudança trava o processo! :hankey:

**Comment by LeandroRoberto** [comment]
acho que só dando uma ordem expressa dentro do arquivo migrations recem gerado... fazendo isso manualmente como parte do processo desenvolvimento que decidiu mudar o nome ou excluir um model... acredito que na hora de rodar o migrate não haverá pergunta

**Comment by edwardoliveira** [comment]
Não sei se vale a pena mudar isso só pq duas instâncias estão automatizadas não compensa, a meu ver. No dia a dia podemos recomendar a atualização e restart manual, não?
