### ISSUE TITLE
Revisar URLs do SAPL

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#41]
Algumas URLs do SAPL dispõe o código da matéria, por exemplo, ao invés do id (PK). Neste caso, é necessário passar também o ano da matéria. Adicionalmente, deve ser revisado todo o esquema de URLs para deixá-lo consistente.

**Comment by marciomazza** [comment]
É muito importante também **revisar os caminhos em si**: vários estão abreviados demais nesse momento, o que diminui a qualidade das urls tanto para o usuário como para os mecanismos de busca.

**Comment by LeandroRoberto** [comment]
foi adicionado o teste test_urlpatterns que está em
https://github.com/interlegis/sapl/blob/master/sapl/test_urls.py e estabelece os padrões de prefixos que cada app pode ser iniciada e aponta as quais não estão dentro das possibilidades.
