### ISSUE TITLE
sapl 31: Implementar a possibilidade de alterar a ordem padrão das partes de uma sessão plenária

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#414]
Isso poderia ser feito nas Tabelas Auxiliares para permitir que a ordem das partes de uma sessão fique de acordo com o Regimento Interno.

**Comment by LeandroRoberto** [comment]
+1... excelente, como conversamos via telegram...

**Comment by edwardoliveira** [comment]
@andreagudo Poderia detalhar mais o funcionamento disso?

**Comment by andreagudo** [comment]
No SAPL a ordem de cada um das partes da sessão plenária é inalterável (Mesa Diretora, Presenças, Expedientes, Matérias, ...). Tal ordem não corresponde à que o nosso Regimento Interno determina. Imagino que ocorra o mesmo no caso de outras casas legislativas. A possibilidade de alteração da ordem em que as partes da sessão aparecem no resumo e no pdf seria importante. Inclusive porquê os parlamentares recebem, para acompanhamento durante as sessões, um pdf impresso.

**Comment by eduardocalil** [comment]
@andreagudo Teste, por favor, se está do jeito que gostaria. A ordenação pode ser feita nas Tabelas Auxiliares de Sessão.

**Comment by andreagudo** [comment]
O operador-geral não chega na tela para editar a ordenação, pede usuários e senha novamente.

**Comment by andreagudo** [comment]
Tudo resolvido.
