### ISSUE TITLE
Módulo Bancadas das Tabelas Auxiliares sem links

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#415]
Não há links para Bancadas e Cargo de Bancada no Módulo Bancadas, em Tabelas Auxiliares.

**Comment by eduardoedson** [comment]
@edwardoliveira @marciomazza Mesmo caso de #416, em qual App cria?

**Comment by edwardoliveira** [comment]
``sessao``

**Comment by andreagudo** [comment]
ok.
