### ISSUE TITLE
Módulo Administrativo das Tabelas Auxiliares sem links

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#416]
Não há links para Tipo de Documento, Tipo de Instituição e Status de Tramitação no Módulo Administrativo, em Tabelas Auxiliares.

**Comment by eduardoedson** [comment]
@edwardoliveira @marciomazza Pra criar o model desses de Módulo Administrativom seria em qual App?

**Comment by edwardoliveira** [comment]
``protocoloadm``

**Comment by andreagudo** [comment]
ok.
