### ISSUE TITLE
sapl 31: Protocolo: resultado de pesquisa com ordem indefinida

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#418]
Ao acessar a função Protocolo, o usuário operador é levado a uma pesquisa; abaixo da tela de critério da pesquisa é apresentado um relatório sem ordem definida. Para ordenar, nova pesquisa pode ser feita nessa própria tela usando o campo Ordenação que está funcionando corretamente. Assim, penso que o primeiro resultado é desnecessário, até por não estar ordenado.

**Comment by andreagudo** [comment]
Ocorre o mesmo problema na função Matérias Legislativas. Ao Pesquisar Matéria Legislativa, não abre apenas uma tela de pesquisa, mas também um resultado aleatório desnecessário.
http://sapl31agudo.interlegis.leg.br/materia/pesquisar-materia

**Comment by eduardocalil** [comment]
@andreagudo Conversei com o @marciomazza  e ele concordou com a mudança proposta. Feito.

**Comment by andreagudo** [comment]
Continua ocorrendo o mesmo problema em Matérias Legislativas relatado em um comentário posterior:
http://sapl31agudo.interlegis.leg.br/materia/pesquisar-materia

**Comment by andreagudo** [comment]
O problema da ordem do resultado da pesquisa de protocolo persiste:
![captura de tela de 2016-09-26 13 40 02](https://cloud.githubusercontent.com/assets/19169882/18843361/e3927000-83ee-11e6-9b37-3eb47aba4c40.png)

**Comment by eduardoedson** [comment]
Feito

**Comment by andreagudo** [comment]
ok.
