### ISSUE TITLE
sapl 31: Função Protocolo sem opção Protocolar

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#419]
Na função Protocolo há possibilidade de pesquisa, mas não há como protocolar nada.

**Comment by eduardoedson** [comment]
No caso, teria que pesquisar primeiro, entrar em uma das opções que aparecem na listagem e, após isso, irá aparecer o menu para poder protocolar.

[protocolo](http://localhost:8000/protocoloadm/240/2016/protocolo_mostrar)

**Comment by andreagudo** [comment]
ok.
