### ISSUE TITLE
Criar Unidade de Tramitação no módulo Administrativo de Tabelas Auxiliares

### ISSUE THREAD

**Issue by eduardocalil** [interlegis/sapl#420]
A unidades de tramitação de Documentos Administrativos não são os mesmos de Matéria Legislativa.

**Comment by eduardoedson** [comment]
Seria essa http://localhost:8000/sistema/materia/unidade-tramitacao/ ?

**Comment by edwardoliveira** [comment]
@eduardocalil Alguma novidade nessa issue?

**Comment by eduardoedson** [comment]
PR #456
