### ISSUE TITLE
Criar conexões de links no App ProtocoloAdm

### ISSUE THREAD

**Issue by eduardocalil** [interlegis/sapl#421]
Há várias URL's que só podem ser acessadas se seus links forem colocados na url do browser. Devem ser criadas conexões entre as telas por botões com links que redirecionam para outras Views.

**Comment by marciomazza** [comment]
Que urls? que views?

**Comment by eduardocalil** [comment]
Muitas das telas do APP ProtocoloAdm não tem links. Por exemplo, não tem como acessar as tramitações de um documento administrativo sem ser diretamente pela URL.
