### ISSUE TITLE
Implementar informações sobre normas relacionadas nas normas jurídicas

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#422]
No resultado da pesquisa de normas jurídicas não há informações sobre normas relacionadas. O Morale já relatou a necessidade de criar os relacionamentos em #409 .

**Comment by eduardoedson** [comment]
@LeandroRoberto Qual a relação disso com o módulo de compilações?

**Comment by eduardoedson** [comment]
![normas](https://cloud.githubusercontent.com/assets/7716450/15398556/6e009546-1dba-11e6-97db-914c9355e86f.png)

**Comment by LeandroRoberto** [comment]
Mesma resposta que em #409

**Comment by LeandroRoberto** [comment]
Resolvido pela issue #409 em https://github.com/interlegis/sapl/commit/30f9ca5ec95ddd50410938ede7b0319b0105ae58
