### ISSUE TITLE
Pesquisas e resultados

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#428]
Há funções que apresentam, correta e imediatamente, resultados:
http://sapl31agudo.interlegis.leg.br/mesa-diretora/
http://sapl31agudo.interlegis.leg.br/comissao/
http://sapl31agudo.interlegis.leg.br/parlamentar/
http://sapl31agudo.interlegis.leg.br/materia/proposicao_list

Há outras que deveriam apresentar apenas telas de pesquisa:
http://sapl31agudo.interlegis.leg.br/protocoloadm/protocolo
http://sapl31agudo.interlegis.leg.br/materia/
http://sapl31agudo.interlegis.leg.br/sessao/
http://sapl31agudo.interlegis.leg.br/pauta-sessao

**Comment by eduardoedson** [comment]
Caso de matéria será debatido em #441

**Comment by andreagudo** [comment]
Apenas na Pauta da Sessão é que persiste um resultado com todas as pautas abaixo da tela de pesquisa. Penso que não há maior problema se permanecer assim, pois as últimas aparecem acima e com a tela de pesquisa disponível é possível refinar o resultado.
