### ISSUE TITLE
sapl 31: definir ordem de apresentação dos mandatos do parlamentar

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#429]
Na função Parlamentar, definir a ordem de apresentação dos mandatos do parlamentar. Penso que a ordem decrescente é a adequada.
Exemplo: http://sapl31agudo.interlegis.leg.br/parlamentar/21/mandato

**Comment by andreagudo** [comment]
Ainda não resolvido:
![captura de tela de 2016-09-28 08 08 13](https://cloud.githubusercontent.com/assets/19169882/18911316/c859ae92-8552-11e6-976b-923a3ec6fa71.png)

**Comment by eduardoedson** [comment]
Agora é possivel determinar a ordenação clicando no titulo da coluna desejada.

**Comment by andreagudo** [comment]
Ficou ótimo. Somente a ordem pelo critério Legislatura não altera. Penso que o problema esteja nos números iguais das Legislaturas, o que deve ser resolvido com a issue #705 .
