### ISSUE TITLE
Inconsistência dos dados das Sessões Legislativas

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#433]
Há inconsistência entre dados das Sessões Legislativas rgistrados nas Tabelas Auxiliares (onde a contagem reinícia cada legislatura) e na pesquisa da Mesa Diretora (reinício da contagem das legislaturas é única). Exemplo para a legislatura atual:
http://sapl31agudo.interlegis.leg.br/sistema/mesa-diretora/sessao-legislativa/?page=6
http://sapl31agudo.interlegis.leg.br/mesa-diretora/
Investigar se é um problema real ou se trata de medida de segurança do ambiente de testes.

**Comment by andreagudo** [comment]
Tal inconsistência, se for o caso, repercute em "Adicionar Sessão Plenária", onde as sessões legislativas seguem a ordem das Tabelas Auxiliares:
http://sapl31agudo.interlegis.leg.br/sessao/create

**Comment by eduardoedson** [comment]
Depois da #103 conferir com os dados reais de Agudo.

**Comment by edwardoliveira** [comment]
Oi @andreagudo, se ainda existirem inconsistências podem ser por conta de algum bug na migração de dados. Se quiser podemos fazer uma nova migração e aí chegar os dados. O que acha? Poderia verificar?

/cc @LucianoAlmeida

**Comment by andreagudo** [comment]
Acho que está correto.
