### ISSUE TITLE
sapl 31: Implementar pesquisa de sessões plenárias

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#435]
Há uma lista de todas as sessões plenárias, com várias páginas. Seria interessantes manter a pesquisa que existe no SAPL 2.5.
http://sapl.agudo.rs.leg.br/consultas/sessao_plenaria/sessao_plenaria_index_html

**Comment by andreagudo** [comment]
Continua havendo uma lista desnecessária de sessões na primeira tela. Bastaria que a função Sessões Plenárias levasse diretamente à tela já existente dos critérios de pesquisa. Além disso, a pesquisa de sessões existente hoje no SAPL 2.5 está bem dinâmica, apresentando um resultado filtrado ao selecionar cada critério.

**Comment by eduardoedson** [comment]
Verifique, por favor.

**Comment by andreagudo** [comment]
A pesquisa funciona, mas poderia ser bem dinâmica, como já é no SAPL 2.5.
