### ISSUE TITLE
Buscar número seguinte ao adicionar sessão plenária

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#436]
Ao adicionar uma sessão plenária, que o usuário defina o tipo e o sistema indique o número da sessão criada, dentro da legislatura corrente (com possibilidade de alteração para o caso do registro de uma sessão anterior).

**Comment by edwardoliveira** [comment]
O número da sessão plenária varia de acordo com o tipo? Ou é somente o próximo maior número da legislatura corrente?

**Comment by eduardoedson** [comment]
Verifique, por favor

**Comment by andreagudo** [comment]
O número da sessão varia com o tipo. Isso funciona. Apenas o campo Sessão Legislativa devia estar pré-preenchido com a mais atual (aparece "-------------")

**Comment by andreagudo** [comment]
Agora está aparecendo assim em Sessão Legislativa:
![captura de tela de 2016-10-10 10 41 15](https://cloud.githubusercontent.com/assets/19169882/19238164/98e0f264-8ed6-11e6-9164-dc5648d8676b.png)

**Comment by eduardoedson** [comment]
Tem que mudar a legislatura antes, mesmo ela vindo pré-selecionada.
@eduardocalil

**Comment by eduardoedson** [comment]
Resolvido?

**Comment by andreagudo** [comment]
Resolvido.
