### ISSUE TITLE
Erro ao acessar Votação Nominal de Ordem do Dia.

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#439]
Ao acessar a URL ``/5/matordemdia/votnom/1484/309`` aparece um erro conforme tela abaixo:

![image](https://cloud.githubusercontent.com/assets/9326037/15182385/8998a04a-1762-11e6-9de4-4f32fa5579f4.png)

**Comment by eduardoedson** [comment]
Isso, provavelmente, foi resolvido na PR #518 e a issue #517 trata disso, então irei fechar.
