### ISSUE TITLE
Questão para debate; acesso à pesquisa Matérias Legislativa passa por relatório desnecessário

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#441]
Para acessar a pesquisa Matérias Legislativa passa-se por relatório desnecessário, na minha opinião, que apresenta todas elas. Poderia levar direto à tela de definição dos critérios da pesquisa.
http://sapl31agudo.interlegis.leg.br/materia/

**Comment by eduardoedson** [comment]
No 2.5 vai para a tela de pesquisa primeiro com opção de adicionar, como estamos fazendo uma 'cópia' dele, o melhor caso seria fazer isso, mas foi discutido antes que faríamos da forma que está atualmente, mostrando uma listagem geral com opção de pesquisa e adição.

**Comment by marciomazza** [comment]
Coloquei isso no milestone (marco) `Futuro` para depois avaliarmos depois do lançamento do 3.1.

**Comment by andreagudo** [comment]
Considero resolvido. Fechamento depende de observação acima do @marciomazza .

**Comment by marciomazza** [comment]
Concordo.
