### ISSUE TITLE
Usuário operador com acesso indevido a proposições.

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#449]
O usuário operador está com acesso indevido a proposições via função Atividade Legislativa. Há relação com a #103

**Comment by marciomazza** [comment]
Excelente vc ter identificado esse vículo com outra issue, @andreagudo.
A issue #28 estava vaga e editei sua descrição.
A issue que trata de autorização (quem pode fazer o que e onde) é a #103.

**Comment by andreagudo** [comment]
Ver #565

**Comment by andreagudo** [comment]
Ver #565
