### ISSUE TITLE
Layouts muito grandes

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#450]
A maioria das telas estão muito grandes, com os botões "salvar" e "pesquisar" bem abaixo. Penso que entrelinhas e/ou campos podem ser reduzidos para melhorar a usabilidade. Como uso monitor 19", a issue deve ser debatida.

**Comment by DtiLegBG** [comment]
Pois é, o pessoal aqui em Bento Gonçalves também acha que as telas  de cadastro pelas entrelinhas e tamanho acabam gerando muita rolagem

**Comment by DtiLegBG** [comment]
@andreagudo , o edward e o leandro deram uma diminuida nas entrelinhas, você acha que continua grande?

**Comment by andreagudo** [comment]
Acho que ainda pode melhorar. Mas muito menor do que está vai amontoar muito.

**Comment by edwardoliveira** [comment]
Vocês ainda consideram o layout grande? /cc @LeandroJatai @DtiLegBG @andreagudo

**Comment by LeandroJatai** [comment]
Acho que está ok.

**Comment by DtiLegBG** [comment]
O pessoal aqui não tem comentado mais sobre o assunto, acho que está bom

**Comment by andreagudo** [comment]
Acho que está bom.
