### ISSUE TITLE
Traduzir o README para português

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#452]
Há algum tempo decidimos usar português em todo o projeto, que iniciou em inglês.
Entretanto nos esquecemos de traduzir de volta o README para português.

**Comment by LeandroRoberto** [comment]
abri issue #451... instalei um ubuntu 16.04 64bits em uma máquina virtual (acabei de terminar...) e comecei fazer alterações no readme.rst... como pensei nessa questão de traduzir mas não tinha autorização... estava pensando: "vou terminar o que é necessário e fazer um readme_pt.rst" em português e detalhado... não mandando para documentações dos passos intermediários, mas colocando elas no próprio readme... agora fica a dica da mistura da #451 com a #452 e com esse pensamento ideia citada do detalhamento!

**Comment by marciomazza** [comment]
Adicionei a parte de tradução à #451 e fecho essa como duplicada.
