### ISSUE TITLE
Títulos mais claros para issues

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#454]
Algumas issues foram criadas com títulos muito vagos.
Cada issue deve conter uma tarefa específica e seu título deve expressar de forma **sucinta, mas que identifique bem** o que deve ser feito.

Melhorar os títulos de cada uma das issues abaixo.

É importante retirar tb o prefixo `sapl31 - ` de cada uma delas. Nós já agrupamos as issues em milestones e se outro tipo de classificação for necessário é possível usar os labels para isso.

_(número  título)_
#430  sapl31 - ld usuário
#409  sapl31 - normas jurídicas
#406  sapl31 - normas jurídicas
#405  sapl31 - normas jurídicas
#404  sapl31 - normas jurídicas
#396  sapl31 - ld usuário
#378  sapl31 - Legislaturas
#376  sapl31-parlamentar
#373  sapl31- tipo de autor
#372  sapl31 - unidade de tramitação
#371  sapl31 - tipo de matéria legislativa
#370  sapl31 - órgãos
#369  sapl31- autor
#368  sapl31 - status de tramitação
#367  sapl31 - partidos
#366  sapl31 - tipo de comissão
#365  sapl31 - Sessão Legislativa
#363  sapl31-coligação
#362  sapl31 - Legislaturas
#361  sapl31 - Ajuda

**Comment by marciomazza** [comment]
Sobraram essas:

#376	sapl31-parlamentar
#372	sapl31 - unidade de tramitação
#369	sapl31- autor
#365	sapl31 - Sessão Legislativa
#363	sapl31-coligação

**Comment by edwardoliveira** [comment]
Feito.
