### ISSUE TITLE
Listagem sessão plenária - pauta sessão plenária

### ISSUE THREAD

**Issue by eduardoedson** [interlegis/sapl#457]
Cada uma tem sua listagem, mantém assim ou padroniza? Se for padronizar, qual das duas mantém?

http://localhost:8000/sessao/
http://localhost:8000/pauta-sessao

**Comment by edwardoliveira** [comment]
Por **mim** deixa só a primeira (e a segunda vira um link para a 1a., talvez escondendo os links de adicionar/editar?). Sempre achei a pauta-sessao extremamente feia, mas essa é minha opinião.

**Comment by edwardoliveira** [comment]
Ah, lembrei de uma coisa: o que acha de colocar a listagem de sessão plenária em ordem decrescente? Assim, o usuário não tem que percorrer N páginas até a sessão mais recente.

**Comment by eduardoedson** [comment]
Pra mim, a pauta é basicamente essa tela: http://localhost:8000/4/resumo

**Comment by edwardoliveira** [comment]
Sim, vc tem razão. :+1:

**Comment by eduardoedson** [comment]
Não recordo, era para remover a tela de pauta da sessão?
