### ISSUE TITLE
[Regressão] Funcionalidade de reordenar matérias em Sessão Plenária

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#461]
Tinhamos uma funcionalidade de reordenar matéria legislativa tanto para ordem do dia como para expediente. Com a conversão para o CRUD esta funcionalidade se perdeu.

**Comment by morale** [comment]
Aqui há 2 situações: 1ª) tanto em ordem do dia como matérias de expediente constam uma ou mais matérias que serão objeto de discussão na ordem ou no expediente. Essas matérias são apresentadas numa ordem sequencial consecutiva. Quando o usuário exclui uma ou mais matérias da ordem do dia ou do expediente, a numeração fica com "buracos" ou seja de forma não consecutiva e, nesse caso, há necessidade de se reordenar; e 2ª situação é o caso em que o usuário deseja alterar a posição na qual uma matéria se encontra. Por exemplo, possui nº ordem 5 e ele deseja colocar na ordem 8. Hoje o sapl não tem mecanismo que permita ao usuário resolver essa 2a. situação. Neste caso, a solução disponível que utilizam é a de se fazer exclusões e reinclusões até que as matérias fiquem na ordem desejada e, em seguida, clica em reordenar.

**Comment by morale** [comment]
nb:
a situação ideal seria permitir arrastar pra cima ou pra baixo e largando na posição desejada com renumeração automática.

**Comment by LeandroRoberto** [comment]
+1 para o morale...
e quanto ao o botão reordenar... 
criei o campo ord_tipo_materia... é como um peso nos tipos... esse peso quem dá é o regimento interno que define a ordem de precedência... ou seja... principio, ao clicar em reordenar, coloca em em ordem, mas segundo o regimento de cada casa... e depois... de forma manual, a possibilidade de um drag and drop como o morale disse...

(https://cloud.githubusercontent.com/assets/9630623/15335683/cadb2410-1c49-11e6-87e2-649d18377b20.png)
