### ISSUE TITLE
Proposições com menu superior indevido

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#462]
Ao visualizar ou editar uma proposição, o usuário tem acesso a um menu superior que só faz sentido para matérias legislativas:
http://sapl31agudo.interlegis.leg.br/proposicao/1331
http://sapl31agudo.interlegis.leg.br/proposicao/1331/edit

**Comment by andreagudo** [comment]
Penso que é importante priorizar a segregação do acesso dos usuários com perfil de operador e de autor ( #103 ). Isso evitará o post de issues "desnecessárias".

**Comment by edwardoliveira** [comment]
@eduardoedson Este é mais um exemplo de erro no CRUD automático, certo? Aquele _mesmo_ erro?

**Comment by andreagudo** [comment]
O operador_autor deixou de ter onde criar/editar proposições, seu único papel. Ver issue #564

**Comment by LeandroRoberto** [comment]
#706
