### ISSUE TITLE
Tipo de arquivo de Complemento de proposição

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#463]
Embora o sistema aceite outro tipo de arquivo (testei odt), há informação de que o complemento deve ser um pdf.

**Comment by edwardoliveira** [comment]
@eduardocalil Vc que fez essa checagem, não? Poderia confirmar isso, por favor?

André, **se não me engano**, os complementos aceitos são PDF, DOC, ODT, e RDT, mas vamos olhar isso, asap.

**Comment by edwardoliveira** [comment]
@eduardoedson Esqueci dessa issue. Vc ainda está trabalhando nela??? :)

**Comment by eduardoedson** [comment]
Tá revisando, acho que já deve ter sido feito

**Comment by eduardoedson** [comment]
Já deve ter feito merge até

**Comment by andreagudo** [comment]
Tirar "(PDF)" de Texto Original
![captura de tela de 2016-11-23 10 37 54](https://cloud.githubusercontent.com/assets/19169882/20562126/3908ad54-b169-11e6-8b2e-1a1d5e51a1d1.png)

**Comment by LeandroRoberto** [comment]
em proposição (título da issue) não está mais assim... porém, o erro está correto sobre o detail e update de MateriaLegislativa.

**Comment by LeandroRoberto** [comment]
em proposição (título da issue) não está mais assim... porém, o erro apontado sobre o detail e update de MateriaLegislativa ainda ocorre.

**Comment by edwardoliveira** [comment]
@LeandroRoberto @andreagudo Pessoal, desculpa, essa issue ficou "perdida" no meio das outras tantas... Consertei para Matéria Legislativa. Se ainda não estiver a contento, André, favor reabrir.

Obrigado!

**Comment by andreagudo** [comment]
Ok.
