### ISSUE TITLE
Alterações nos dados básicos da Casa Legislativa não ficam salvos

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#477]
As alterações nos dados básicos da Casa Legislativa não ficam salvos, retornam sempre aos dados originais.

**Comment by edwardoliveira** [comment]
Oi André, vc diz com relação ao logo e título da casa ou a outros dados da casa legislativa, tipo endereço?

**Comment by andreagudo** [comment]
Nada era salvo. Agora não está salvando apenas o logotipo (usei jpg).

**Comment by edwardoliveira** [comment]
Estranho. Vamos verificar

**Comment by edwardoliveira** [comment]
@andreagudo Podemos fechar esta issue? Vc está conseguindo salvar/editar os dados da casa? Não estou considerando o #487 e #488, que ainda continuam abertos.

**Comment by andreagudo** [comment]
Revolvido.
