### ISSUE TITLE
Campos nulos no Models de TramitacaoAdministrativo

### ISSUE THREAD

**Issue by eduardocalil** [interlegis/sapl#478]
Todos os campos nesse Model podem ser nulos (exceto documento(fk) e id(pk)). Diferentemente do SAPL 2.5, onde 'data_tramitacao', 'unidade_local', 'status' e 'texto' são obrigatórios. 

Além disso, esse model possui o campo 'ultima', que já foi retirado da tramitação de matérias por ter dado alguns problemas.

Teria algum problema na migração eu retirar o campo 'ultima' e colocar os citados acima como obrigatórios? @marciomazza @LucianoAlmeida

**Comment by LucianoAlmeida** [comment]
@eduardocalil, até onde eu sei, não haveria problema algum durante a migração por causa dos campos que serão obrigatórios.
Agora, caso retire o campo `ultima`, provavelmente dará algum erro, mas seria bem tranquilo ajusta a migração pra ignorar as entradas desse campo.
