### ISSUE TITLE
Nome da Casa Legislativa

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#488]
O Noma da Casa Legislativa é uma combinação do que se edita (Câmara Municipal) com o que é definido nos campos Município e Estado. Isso faz repetir o nome do município. Como, necessariamente, o SAPL é de uma "Câmara Municipal de", basta concatenar essa expressão ao que for definido em Município e Estado, sendo desnecessário o campo Nome.

**Comment by LeandroRoberto** [comment]
quanto ao nome, acho que não pode ser como o @andreagudo disse devido ao uso por Assembleias... devia ficar só com relação ao nome... no máximo [nome - estado], mesmo assim, atrapalha a customização do nome... "Assembleia de Goiás - GO"?? ficou ruim... poderia ser só a primeira parte... ou se eu colocar em nome "Câmara Municipal de Jataí - Goiás", o resultado seria "Câmara Municipal de Jataí - Goiás - GO"... estranho também... sugiro apenas o nome no título
sem essa parte:
`{% trans 'de' %} {{ municipio }} - {{ uf }}`

**Comment by edwardoliveira** [comment]
Na parte de edição da casa legislativa aparece também:

``CasaLegislativa object``

**Comment by edwardoliveira** [comment]
Relacionado a #487

**Comment by wesleylima247** [comment]
No caso para assembleias legislativas o nome da casa legislativa fica por exemplo:  Assembleia Legislativa do Piauí de Teresina - PI.

Nesse caso está customizada para camaras municipais.

**Comment by wesleylima247** [comment]
No rodapé também está personalizado para Câmara:

Site da Câmara | Fale Conosco

**Comment by andreagudo** [comment]
ok.
