### ISSUE TITLE
Padronizar confirmação de remoção

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#49]
Em algumas telas do sistema existe a confirmação de remoção do registro (Deseja prosseguir? [S/N]) enquanto outras (algumas que eu fiz, :cry:) simplesmente apagam o registro. Precisamos padronizar este comportamento, talvez com a inserção de JavaScript, pois a rotina de remoção de registro redireciona para uma outra tela de confirmação.

**Comment by eduardoedson** [comment]
Com o uso do CRUD essa issue foi resolvida.
