### ISSUE TITLE
[Regressão] Sumiu links de Composição e Matérias em Tramitação de Comissões

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#491]
Conforme título.

**Comment by eduardocalil** [comment]
#490

**Comment by eduardocalil** [comment]
Esse erro foi gerado pela solução encontrada para eliminar os links indesejados da nav-bar nas telas de Tabelas Auxiliares. Isso ocorreu pelo fato de que o link base do app **"parlamentares"** é **"parlamentar"**, e de **"comissoes"** é **"comissao"**, o que quebrou a lógica implementada. Irei procurar outra solução para o problema inicial.
