### ISSUE TITLE
Analisar flexibilização de numeração de normas jurídicas

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#494]
Existe um problema histórico no sapl quanto a variação da numeração de normas jurídicas, conforme nesta mensagem:
http://colab.interlegis.leg.br/archives/thread/gitec/normas-juridicas#msg-156338

não só nesta mensagem é possível ver a dificuldade, mas também nas mensagens que antecedem e procedem...

**Comment by marciomazza** [comment]
Foi resolvido pela pull request https://github.com/interlegis/sapl/pull/879.
