### ISSUE TITLE
Analisar flexibilização arquivos para normas jurídicas

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#495]
assim como em #494, no mesmo link citado, existe a demanda da anexação de arquivos extras as normas jurídicas, arquivos que funcionam como anexos... como acontece em matérias legislativas, que existem os documentos acessórios, porém, em norma jurídica, os anexos, são parte integrante, e não um documento acessório... enfim, seria interessante haver a possibilidade de inclusão de vários arquivos nominados anexos.

**Comment by marciomazza** [comment]
Vide #697.

**Comment by tapumar** [comment]
Fixed #2128
