### ISSUE TITLE
Padronização para utilização em instalações pip requirements

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#497]
o projeto sapl não está no padrão para reuso via pip install.

historinha: lendo a documentação do django e alguns blogs, entendi que é possível alguns tipos de reusabilidade em novos projetos:
1. crio um novo projeto e copio a app antiga e reconfiguro (altamente não recomendável)
2. clono o sapl todo implemento funcionalidades que nativamente seria de outro projeto, outras apps, outras configurações e tento manter isso tudo independente e ainda, sabe-se lá como, fazer pull-requests de contribuições para a versão oficial (não recomendável)
3. faço o projeto sapl fazer parte do requirements do meu novo projeto e importo as apps que eu quiser... _voílà_...  dessa forma, se eu for colaborador do projeto oficial mesmo através de fork, posso manter um virtualenv para isso e, além disso, no meu novo projeto, posso adicionar no requirements e usar as apps que eu quiser do sapl inclusive, adicionando controle de versão...

a princípio, e já testei em um fork do sapl, é só adicionar o arquivo setup.py com configuração básica que em outro projeto, independente do sapl ir para o  pypi, pode ser instalado adicionando git+git://github.com/interlegis/sapl.git nos requirements

**o que não está no padrão?**

1. os arquivos na raiz do projeto, nada que está na raiz que será usado em uma app pode ficar na raiz, como por exemplo crispy_layout_mixin.py. Esses arquivos não vão para a instalação, só vão as apps secundárias e a app principal, ou seja, tudo que está na raiz do projeto fica de fora... sendo assim, qualquer app que use esse arquivo, ao adicioná-la em um novo projeto, não funcionará...
2. o nome das apps, são genéricos e ficam soltos site-packages... a chance de colidir com outros produtos dentro do site-packages é enorme, por exemplo as app base, compilacao, sessao, 

A melhor solução me parece ser que as apps possam ir para dentro da app sapl, isso é possível, apps secundárias, dentro da app principal do projeto... mudanças no settings e nos imports. Além disso todos os arquivos relevantes que estão na raiz do projeto, devem ser movidos para a app principal.

**Comment by LeandroRoberto** [comment]
Na configuração atual, todas os templates também ficam de fora...

**Comment by LeandroRoberto** [comment]
Na configuração atual, todos os templates também ficam de fora... por que estou tão interessado nessa padronização? Estou a pouco tempo na plataforma django, mas estou convencido de migrar minhas soluções para esta plataforma. Uma delas é uma que tenho aqui que se chama siscam, que é uma web app feita em java+flex, semelhante ao saap (fiz antes de o conhecer)... hoje o siscam possui 29000 pessoas cadastradas ligadas aos gabinetes, possuindo registro de 12000 processos de solicitação... Atualmente é uma demanda da casa o melhoramento do siscam e, sendo mais viável migrá-lo para django, o farei, porém, quero aproveitar a app parlamentares, bem como funcionalidade genéricas como o Crud e MasterDetail, sem mudanças e evoluir a ferramenta sempre compatível a evolução da app parlamentares...

**Comment by marciomazza** [comment]
Essa refatoração é bem vinda. Se quiser pode fazer já.

**Comment by edwardoliveira** [comment]
Isso aí. Siga em frente!

**Comment by LeandroRoberto** [comment]
putz... legal... faço sim... é trabalhosa pacas... é import pra caramba que estão de formas variadas, ora com from, ora sem from, ou com variações... hehehe... mas nesse novo projeto consegui encapsulá-lo... não será difícil no sapl... só trabalhoso...

**Comment by edwardoliveira** [comment]
Podemos dividir o trabalho a partir da semana q vem. Crie um branch q vamos modificando. :)
