### ISSUE TITLE
Translate virtual machine

### ISSUE THREAD

**Issue by johnfelipe** [interlegis/sapl#5]
Hi, please tell me how translate to spanish, virtual appliance:
https://colab.interlegis.leg.br/wiki/MaquinaVirtual
Path, folders and files
Tnks

**Comment by marciomazza** [comment]
The virtual machine setup described at https://colab.interlegis.leg.br/wiki/MaquinaVirtual
is for the old 2.5 release.

This project only deals with the new 3.x series releases and on.
