### ISSUE TITLE
Erro em /parlamentar se a base está vazia. 

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#501]
Espera-se que Legislaturas sejam cadastradas antes de qualquer parlamentar, porém, não seria comum um usuário dar clicadas gerais no sistema? Sim... Ao clicar em parlamentar, se a base estiver vazia, sem legislatura, a função `take_legislatura_idx` que está em na classe ParlamentarCrud, subclasse ListView, gera erro nesta linha `legislatura_id = legislaturas.first().id`

DICA: Sempre que usar first().[attr/metod] ou last().[attr/metod], use antes um exists().

**Comment by edwardoliveira** [comment]
Valeu. Vamos olhar isso asap
