### ISSUE TITLE
Internacionalizar yaml's

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#502]

**Comment by LeandroRoberto** [comment]
- As leituras dos arquivos subnav.yaml e layouts.yaml foram
  refatoradas para suportar internacionalização.
- Falta fazer neste branch:
  - Mover todos os arquivos [app_label]/layouts.yaml para
    templates/[app_label]/layouts.yaml
  - aplicar a tag {% load i18n %} no início de todo arquivo layouts.yaml
  - aplicar a tag {% trans '' %} em todo texto a ser internacionalizado
  - DICA: deixe os ":" (dois pontos) de fora da tag trans.

**Comment by LeandroRoberto** [comment]
O que falta fazer é com você @edwardoliveira e sua equipe!!!

**Comment by LeandroRoberto** [comment]
os exemplos a serem seguidos estão nos arquivos:
  -  templates/parlamentares/subnav.yaml
  -  templates/parlamentares/layouts.yaml

**Comment by edwardoliveira** [comment]
Aí meus sais, hehehe... ei, vc não estaria interessado em tocar o processo de finalizar a autenticação com a gente na próxima semana? Seu know how de SAPL será de grande ajuda. Poderia coordenar com o @eduardosaidcalil -- que já começou a trabalhar nisso --, e comigo. Precisamos disso até o final deste mês pra ter uma versão beta usável. 😁

**Comment by edwardoliveira** [comment]
Eu estou lendo o horário certo? Vc abriu este PR 1 h da manhã?! 😱😱😱
