### ISSUE TITLE
Adicionar application level logging

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#52]
O SAPL não conta com logging a nível de aplicação (views, models, etc).

**Comment by LeandroRoberto** [comment]
as exceções já estão sendo logadas com:
https://github.com/interlegis/sapl/blob/master/sapl/settings.py#L268

o caminho para configuração completa do log já está iniciado aqui:

**Comment by LeandroRoberto** [comment]
as exceções já estão sendo logadas com:
https://github.com/interlegis/sapl/blob/master/sapl/settings.py#L268

o caminho para configuração completa do log já está iniciado aqui:
https://github.com/interlegis/sapl/blob/master/sapl/settings.py#L246 dentre outras melhorias, falta direcionar para arquivo.

Na aplicação, de modo geral, os logs necessários deveriam ser registrados com:
https://github.com/interlegis/sapl/blob/master/sapl/utils.py#L27 que é usado já em alguns locais, principalmente em na app api

**Comment by edwardoliveira** [comment]
https://github.com/interlegis/sapl/blob/master/sapl/settings.py#L295-L315

**Comment by LeandroRoberto** [comment]
deveria ser melhor analisado... e possivelmente ativar isso aqui:
https://github.com/interlegis/sapl/blob/master/sapl/settings.py#L322

**Comment by edwardoliveira** [comment]
Poderia elaborar mais no 'melhor analisado'? Vamos olhar essa issue nesta semana então qualquer dica é bem vinda. :)

**Comment by LeandroRoberto** [comment]
é uma configuração básica, não fui a fundo pra deixar a funcionalidade bem configurada,
por exemplo, não tenho certeza de como está a persistência dos log em arquivos... o correto é investigar a função e continuar o desenvolvimento dela

além disso não sei bem pq foi comentado a seguinte instrução 
# sys.excepthook = excepthook
em
https://github.com/interlegis/sapl/blob/master/sapl/settings.py#L322

mas o propósito dela é fazer com que tudo que passe por um except vá para o logging

**Comment by LeandroRoberto** [comment]
varrer prints do sistema implementando mais e substituindo except prints por logger

**Comment by edwardoliveira** [comment]
Realizado pelo commit b4c430ff9a732c7c558ffb6ca68d71b1e7f37f67
