### ISSUE TITLE
Tela de Impressos

### ISSUE THREAD

**Issue by eduardoedson** [interlegis/sapl#542]
[Impressos](http://devsapl25.interlegis.leg.br:8080/cm_agu/sapl/generico/impressos/materia_impresso_form)
Como funciona?

**Comment by marciomazza** [comment]
@morale @LeandroRoberto Nos ajudam a entender?

**Comment by LeandroRoberto** [comment]
dei uma olhada aqui... não sei... não uso!!!
mas veja o caso de Agudo por exemplo, http://sapl.agudo.rs.leg.br/generico/impressos/materia_impresso_form
não é um link público, mas acessa anonimamente via url
diz, Selecionada (Norma) mas ao clicar aparece um filtro de tipo de matérias e período.
mandado gerar, monta um checklist de  matérias do período selecionado,
ao selecionar matérias, e clicar em outro gerar, pede senha de usuário...

**Comment by DtiLegBG** [comment]
no caso de Bento Gonçalves, usamos  impresso/ficha/selecionada

![image](https://user-images.githubusercontent.com/13314947/28427479-b7a9a2d6-6d4c-11e7-8656-f28258951773.png)
