### ISSUE TITLE
Validação de tipos de imagem e texto integral

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#56]

**Comment by marciomazza** [comment]
Essa issue tratava originalmente de validações de URL e email mais outra coisa foi feita.
Como um ramo já foi aberto para ela, seu título foi ajustado e outra issue foi aberta para o problema original: #235

**Comment by marciomazza** [comment]
A implementação tem problemas que se misturaram a uma boa quantidade de código desnecessário.
Está bloqueada até as refatorações de #230 e #233 serem concluídas.

**Comment by marciomazza** [comment]
** Precisamos ver se é importante mesmo validar tipo de imagem! **
