### ISSUE TITLE
Opção de numeração do protocolo deve ficar nas Tabelas Auxiliares

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#562]
Essa opção não deve ser alterada pelo operador, já que deve ser definida pela Casa. O ideal seria estar nas Tabelas Auxiliares. No SAPL 2.5 já foi mudado.

**Comment by eduardocalil** [comment]
Você quer dizer que tem uma lista pré-definida de números de protocolo? @andreagudo

**Comment by andreagudo** [comment]
Ao protocolar um documento. o sistema permite ao operador_protocoloadm optar entre numeração "sequencial por ano" e numeração "sequencial único". Se cada operador fizer uma opção diferente, ter-se-á confusão na numeração. Por isso sugiro que o operador_protocoloadm não possa fazer opção nenhuma. Isso cabe ao operador_geral, nas Tabalas Auxiiares, pois deve ser uma opção da Casa Legislativa, não dos operadores de protocolo.

**Comment by edwardoliveira** [comment]
@eduardocalil Contrariando o que te falei agora há pouco pessoalmente, vamos criar uma tabela appconfig para guardar esta e outras configurações que possam surgir. :grimacing:

**Comment by eduardocalil** [comment]
resolvido na #580

**Comment by andreagudo** [comment]
Tal configuração não está disponível nas Tabelas Auxiliares, Configurações da Aplicação: 
![captura de tela de 2016-09-19 18 16 14](https://cloud.githubusercontent.com/assets/19169882/18649391/a546de48-7e95-11e6-9b2d-a3b893b6e611.png)

**Comment by eduardocalil** [comment]
Resolvido
