### ISSUE TITLE
Informações de protocolo não aparecem em pesquisas

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#563]
As seguintes informações não são mostradas: Assunto e Número de Páginas. E o horário do protocolo não muda (Horário: 08:09:00).

**Comment by eduardocalil** [comment]
Em qual tela isso ocorre? Como assim o horário deve mudar? @andreagudo

**Comment by eduardoedson** [comment]
[http://sapl31demo.interlegis.leg.br/protocoloadm/protocolo](http://sapl31demo.interlegis.leg.br/protocoloadm/protocolo) Nessa tela?

**Comment by eduardoedson** [comment]
Caso seja, o assunto tem, mas número de páginas não. O caso do horário não entendi.

![captura de tela de 2016-09-12 15-17-55](https://cloud.githubusercontent.com/assets/7716450/18447250/2f847916-78fc-11e6-9c12-9915f26e49b4.png)

**Comment by andreagudo** [comment]
Veja o campo Assunto em branco. E o horário fica sempre o mesmo, apesar de ter passado algum tempo entre cada protocolo.

![captura de tela de 2016-09-12 14 40 04](https://cloud.githubusercontent.com/assets/19169882/18448171/5bd11ec6-7900-11e6-8651-6babf5e62b09.png)

A página de detelhes é a seguinte
![captura de tela de 2016-09-12 14 40 04](https://cloud.githubusercontent.com/assets/19169882/18448259/bd505f36-7900-11e6-8eab-6011fcb5f96e.png)

**Comment by andreagudo** [comment]
Veja o campo Assunto em branco. E o horário fica o mesmo, apesar de haver intervalo entre cada protocolo.
![captura de tela de 2016-09-12 15 47 47](https://cloud.githubusercontent.com/assets/19169882/18448331/1ace3aca-7901-11e6-9f8c-115b0058a5ea.png)

Veja o campo Número de Páginas:
![captura de tela de 2016-09-12 15 50 50](https://cloud.githubusercontent.com/assets/19169882/18448355/308fd044-7901-11e6-9440-80f8180a4ab5.png)

**Comment by eduardoedson** [comment]
Isso é no sapl31demo?

**Comment by eduardoedson** [comment]
O meu o horário muda e não tem número de páginas

![captura de tela de 2016-09-12 15-57-27](https://cloud.githubusercontent.com/assets/7716450/18448469/b1d8a112-7901-11e6-8fea-9547cf820851.png)

**Comment by eduardoedson** [comment]
Pode passar o link dessa pesquisa que você fez?

**Comment by andreagudo** [comment]
http://sapl31agudo.interlegis.leg.br/protocoloadm/protocolo?numero=&ano=2016&data_0=&data_1=&tipo_documento=&tipo_protocolo=&tipo_materia=&interessado=&assunto_ementa=&autor=&tipo_processo=&o=&salvar=Pesquisar

**Comment by andreagudo** [comment]
O campo Assunto continua não sendo mostrado no resultado da pesquisa, nem na tela abaixo, nem na demais detalhes (seguinte)
![captura de tela de 2016-09-28 07 58 11](https://cloud.githubusercontent.com/assets/19169882/18911103/6d9bb92e-8551-11e6-9f2d-a16384853663.png)
.

**Comment by eduardocalil** [comment]
Não possui assunto, pois não há assunto nesse protocolo.

**Comment by andreagudo** [comment]
Então o campo assunto não está salvando. Acabei de testar novamente.

**Comment by edwardoliveira** [comment]
@andreagudo Não entendi essa issue. Ainda não está aparecendo? Como faz pra simular?

**Comment by andreagudo** [comment]
Disseste "Não possui assunto, pois não há assunto nesse protocolo." Parece que os protocolos migrados estão corretos. E que a falta de Assunto ocorre nos protocolos feitos agora, pois em nenhum de 2016 aparece o conteúdo de tal campo  Fiz o Protocolo 000005/2016, tenho certeza que preenchi o campo Assunto, mas parece que não foi salvo.

**Comment by edwardoliveira** [comment]
@andreagudo O @eduardoedson corrigiu este bug! Valeu, Edu. :+1:

**Comment by andreagudo** [comment]
Resolvido.
