### ISSUE TITLE
Usuários e tabelas auxiliares.

### ISSUE THREAD

**Issue by wesleylima247** [interlegis/sapl#564]
Outros usuários não tem acesso a tabelas auxiliares na aba sistema. Além do superuser.

**Comment by edwardoliveira** [comment]
#103

**Comment by andreagudo** [comment]
O operador_autor está com acesso indevido às Tabelas Auxiliares.

**Comment by andreagudo** [comment]
O operador_geral acessa as Tabelas Auxiliares, mas não consegue acessar a função Casa Legisaltiva. O sistema pede login e senha novamente.

**Comment by eduardocalil** [comment]
Somente operador_geral e superuser tem acesso às tabelas, @wesleylima247.

Agora o operador_geral tem acesso Casa Legislativa, @andreagudo

**Comment by andreagudo** [comment]
Infelizmente, @eduardocalil , o operador_geral ainda não tem acesso à Casa Legislativa, em Tabelas Auxiliares.

**Comment by eduardoedson** [comment]
É porque a atualização foi feita na área de desenvolvimento, a máquina de testes ainda precisa ser atualizada.

**Comment by wesleylima247** [comment]
A máquina de testes já foi atualizada? @eduardoedson

**Comment by andreagudo** [comment]
ok.
