### ISSUE TITLE
Acesso a proposições somente para os respectivos autores

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#565]
Do usuário anônimo e ao operador_geral têm acesso indevido às proposições. Elas devem ser acessadas apenas pelos respectivos autores, até porquê pode haver algumas em elaboração. O acesso irrestrito deve ser às matérias legislativas.

**Comment by andreagudo** [comment]
Prefiro reabrir, pois o operador_geral ainda vê o link Proposições.
![captura de tela de 2016-09-28 07 48 11](https://cloud.githubusercontent.com/assets/19169882/18910809/08751f3c-8550-11e6-8293-dc7447c90476.png)

**Comment by andreagudo** [comment]
Penso que, para evitar confusão, o anônimo e outros usuários (exceto o próprio autor) deviam acessar apenas matérias. Assim, retire-se o link para proposições.

**Comment by eduardoedson** [comment]
Se for o que penso, você diz que o autor só deve ter acesso a suas proposições [aqui](http://sapl31agudo.interlegis.leg.br/proposicao/) e isso já está sendo validado.
@andreagudo @marciomazza @edwardoliveira

**Comment by LeandroRoberto** [comment]
o tema da issue está resolvido... o que aconteceu foi uma confusão de terminologias em parlamentares que começou a ser mudada... sugiro que feche esta issue e siga com o que falta e está relatado em #622

**Comment by andreagudo** [comment]
Sugestão aceita.
