### ISSUE TITLE
Implementar acesso à Mesa Diretora e à página inicial

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#571]
Implementar no menu superior acesso à Mesa Diretora e à página inicial. O usuário anônimo não tem como chegar a elas depois de acessar outras partes.

**Comment by eduardoedson** [comment]
Para chegar a tela inicial, basta clicar na imagem no topo

**Comment by andreagudo** [comment]
Resolvido.

**Comment by andreagudo** [comment]
Nos testes de hoje percebi que o acesso direto à página inicial, antes implementado, deixou de existir. Foi proposital?

**Comment by eduardocalil** [comment]
Sim, pois estava deixando a barra superior muito grande

**Comment by andreagudo** [comment]
Revolvido.
