### ISSUE TITLE
Erro aos passar por uma legislatura futura em pesquisa

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#572]
Registrei uma legislatura futura para testes. Numa sequência de pesquisas, aparentemente depois de se passar por ela, está aparecendo o erro abaixo. Depois disso, ao voltar à página anterior. aparece a legislatura correta.
![captura de tela de 2016-09-12 14 40 04](https://cloud.githubusercontent.com/assets/19169882/18446054/dc67663a-78f6-11e6-8d22-0f56bf5add9b.png)

**Comment by eduardoedson** [comment]
Em que tela esse erro ocorre?

**Comment by andreagudo** [comment]
Em parlamentares. Aparentemente resolvido.

**Comment by eduardocalil** [comment]
Pode fechar? @andreagudo
