### ISSUE TITLE
Pesquisa de parlamantares: legislatura atual na primeira pesquisa

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#573]
Mostrar os parlamentares da legislatura atual na primeira pesquisa de parlamentares. Há uma legislatura futura registrada e é esta, a última, que está aparecendo.

**Comment by eduardoedson** [comment]
[http://sapl31demo.interlegis.leg.br/parlamentar/](http://sapl31demo.interlegis.leg.br/parlamentar/) Essa tela? A legislatura pré-selecionada deve ser a atual mesmo existindo uma futura?

**Comment by andreagudo** [comment]
Isso mesmo para as duas pesguntas.

**Comment by andreagudo** [comment]
Issue resolvida.

**Comment by andreagudo** [comment]
Resolvido informando a legislatura atual, mas seu número de ordem está errado (todas da caixa de seleção aparecem como sendo 1ª)

**Comment by eduardocalil** [comment]
Resolvido

**Comment by andreagudo** [comment]
ok.
