### ISSUE TITLE
Resumo sessão plenária: implementar entrelinhas nos textos dos Expedientes diversos

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#575]
Implementar entrelinhas nos textos dos Expedientes diversos das sessões. 
![captura de tela de 2016-09-12 14 59 54](https://cloud.githubusercontent.com/assets/19169882/18446726/0081e876-78fa-11e6-8c71-f37fa724c056.png)

**Comment by andreagudo** [comment]
Ainda não está correto. Verificar no modo edição dos Expedientes Diversos onde deve haver entrelinas.

**Comment by eduardoedson** [comment]
Poderia postar uma imagem da forma correta?

**Comment by andreagudo** [comment]
Veja http://sapl31agudo.interlegis.leg.br/328/expediente

Comforme o xemplo abaixo, mas tem que ser implementado nas demais partes dos Expedientes Diversos (ATENÇÃO: no caso de Agudo há uma parte dos Expedientes Diversos com o mesmo nome; no 2.5 os nomes são, respectivamente, Expedientes e Expedientes Diversos).
![captura de tela de 2016-09-12 17 05 06](https://cloud.githubusercontent.com/assets/19169882/18450998/a472a856-790b-11e6-88df-f2006d967332.png)

**Comment by andreagudo** [comment]
Resolvido
