### ISSUE TITLE
Usuário anônimo visualiza botão "Editar Texto" de norma jurídica

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#592]
Usuário anônimo visualiza, indevidametne, o botão "Editar Texto" de norma jurídica. Isso ocorre ao pesquisar norma, acessando o link "Tipo da Norma Jurídica", botão Texto, O correto seria aparecer um botão "Texto Integral da Norma".

**Comment by edwardoliveira** [comment]
Corrigido,obrigado. Favor testar assim que possível. :)

**Comment by edwardoliveira** [comment]
@LeandroRoberto Isto faz parte de compilação, certo? Poderia dar uma olhada? :grimacing: Eu fechei por acidente, mas reabri a issue. Obrigado!

**Comment by andreagudo** [comment]
Sim, o anônimo não deve editar nada. Se for para compilação, cabe a um operador específico.

**Comment by LeandroRoberto** [comment]
O serviço de permissões em Compilação será tratado em breve!

**Comment by LeandroRoberto** [comment]
#546
