### ISSUE TITLE
Autorização em Painel

### ISSUE THREAD

**Issue by eduardocalil** [interlegis/sapl#595]
Foi discutido na issue #574 algumas permissões. Entretanto, houve uma discordância sobre o painel. Resolvam aqui se ele deve ficar aberto para o usuário anônimo ou não.

**Comment by eduardocalil** [comment]
@LeandroRoberto

**Comment by LeandroRoberto** [comment]
sou a favor do meio termo... um controle no config para ter uma view publica do painel...
talvez seria legal assistir um sessão ao vivo(por youtube por exemplo)  e em outra tela ter o painel informativo do que ta rolando e sobre o que ta rolando...
@andreagudo @wesleylima247

**Comment by andreagudo** [comment]
É isso: anónimo pode visualizar.

Em 21/09/2016 11:05, "Leandro Roberto da Silva" <notifications@github.com>
escreveu:
