### ISSUE TITLE
Autorização do Administrador (Superusuário)

### ISSUE THREAD

**Issue by eduardocalil** [interlegis/sapl#598]
De acordo com uma conversa que eu tive há algum tempo com o @morale, ele me disse que a única função do admin era criar usuários e atribuir roles. Realmente é algo que faz muito sentido, pois nós temos várias regras de negócios no nosso sistema e o admin pode "burlar" elas facilmente. Gostaria de saber a opinião de vocês sobre isso. 

Além disso, caso a decisão seja restringir o admin, teremos que mudar a forma como as seções do admin são criadas.

**Comment by eduardocalil** [comment]
@LeandroRoberto

**Comment by LeandroRoberto** [comment]
quanto a proposições, a lógica de mostrar a listagem de proposições apenas para o autor é suficiente...
deixe o superuser em paz... não mexa com "super vacas"...
