### ISSUE TITLE
Implementar entrelinha no Título do resumo da Pauta da Sessão em pdf

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#599]
O título do resumo está muito grande, necessária entrelinha.
![captura de tela de 2016-09-22 08 47 44](https://cloud.githubusercontent.com/assets/19169882/18747101/ae28fc18-80a1-11e6-8be1-4f593acba092.png)

**Comment by andreagudo** [comment]
Que tal centralizar?

**Comment by andreagudo** [comment]
Corrigir "1ª (2013 - 2016) (Atual)ª Legislatura" para "1ª (2013 - 2016) Legislatura (Atual)"
![captura de tela de 2016-09-27 14 33 06](https://cloud.githubusercontent.com/assets/19169882/18884870/aed53614-84bf-11e6-9044-631f807ff70d.png)

**Comment by edwardoliveira** [comment]
@eduardocalil :arrow_up:

**Comment by andreagudo** [comment]
Ok.
