### ISSUE TITLE
Botões de edição disponíveis para usuário anônimo em Matérias do Expediente da Sessão Plenária

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#602]
Botões de edição disponíveis para usuário anônimo, indevidamente, em Matérias do Expediente da Sessão Plenária: "Registrar votação" e "Abrir votação" (o primeiro pede senha, o segundo apresenta o erro abaixo).

![captura de tela de 2016-09-22 09 21 06](https://cloud.githubusercontent.com/assets/19169882/18747944/5060dab0-80a6-11e6-824a-82bd8def7f54.png)

![captura de tela de 2016-09-22 09 25 30](https://cloud.githubusercontent.com/assets/19169882/18747978/8c636e6a-80a6-11e6-9bd1-e6a037f5d4f6.png)

**Comment by edwardoliveira** [comment]
@eduardocalil Vc poderia dar uma olhada nisso?

**Comment by andreagudo** [comment]
Resolvido.
