### ISSUE TITLE
Expedientes Diversos da sessão plenária mostra ferramentas de edição ao usuário anônimo

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#603]
Expedientes Diversos da sessão plenária mostra ferramentas de edição, indevidamente, ao usuário anônimo (embora estejam elas indisponíveis). O ideal seria apresentar apenas o conteúdo de cada parte, sem botões, (como ocorre, corretamente, no resumo da sessão plenária).
![captura de tela de 2016-09-22 09 38 50](https://cloud.githubusercontent.com/assets/19169882/18748393/65368956-80a8-11e6-9907-80dde6fb761e.png)

**Comment by edwardoliveira** [comment]
@eduardocalil Poderia olhar isso?

**Comment by eduardoedson** [comment]
Esse problema é porque os campos nessa tela tem a classe 'texto-rico' (algo assim), teria que tirar essa classe quando fosse usuário anônimo

**Comment by edwardoliveira** [comment]
Favor testar, obrigado.

**Comment by andreagudo** [comment]
Resolvido.
