### ISSUE TITLE
Ordem do Dia sem resultados de votação

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#604]
A Ordem do Dia das sessões não apresenta os resultados de votação. No caso de Agudo, matéria que consta na Ordem do Dia sempre tem resultado.

**Comment by eduardoedson** [comment]
Acredito que seja algum problema na migração dos dados. (@edwardoliveira)
Ao fazer uma nova votação, o resultado apareceu.
[http://sapl31agudo.interlegis.leg.br/sessao/326/ordemdia](http://sapl31agudo.interlegis.leg.br/sessao/326/ordemdia)

**Comment by edwardoliveira** [comment]
Vou olhar isso, @eduardoedson e @andreagudo. Valeu!

**Comment by edwardoliveira** [comment]
@andreagudo André, vc poderia nos fornecer uma Sessão Plenária que no SAPL 2.5 tenha resultado de votação e no sapl31agudo não esteja aparecendo?

**Comment by andreagudo** [comment]
http://sapl.agudo.rs.leg.br/consultas/sessao_plenaria/agenda_sessao_plen_mostrar_proc?cod_sessao_plen=289&dat_sessao=25/08/2014

**Comment by eduardoedson** [comment]
@andreagudo Foi resolvido?

**Comment by andreagudo** [comment]
Resolvido.
