### ISSUE TITLE
Conteúdo dos Expedientes Diversos, no resumo da sessão plenária, sem entrelinhas #575 #603

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#605]
O conteúdo dos Expedientes Diversos, no resumo da sessão plenária, não tem entrelinhas. Esse problema das entrelinhas foi tratado também na issue #575, onde a solução dada não é a melhor por mostrar ferramentas de edição ao usuário anônimo (#603). Já o formafo geral do resumo está adquado, com exceção das entrelinhas. Concluindo: para o usuário anônimo, tanto na pesquisa dos Expedientes Diversos quando no resumo da sessão, nesta mesma parte, o ideal seria: formato geral do resumo (sem botões), mas com entrelinhas.

**Comment by eduardoedson** [comment]
Não entendi muito bem, o meu está aparecendo assim, o que teria que mudar?

![captura de tela de 2016-09-22 14-50-56](https://cloud.githubusercontent.com/assets/7716450/18759721/2644bb74-80d4-11e6-81fb-63e7218d0ddb.png)

**Comment by andreagudo** [comment]
Veja, por exemplo, o conteúdo de Oradores do Pequeno Expediente. Está assim:
1. Cleber Cassel2. Gerson Halberstadt3. Itamar Puntel4. M&aacute;rcio Halberstadt5. Paulo Unfer6. Vilson Dias7. Alexandre Neu8. Carlito Schiefelbein

Deveria ser:
1. Cleber Cassel
2. Gerson Halberstadt
3. Itamar Punte
4. M&aacute;rcio Halberstadt
5. Paulo Unfer
6. Vilson Dias
7. Alexandre Neu
8. Carlito Schiefelbein

Essas entrelinhas foram copiadas (recurso muito usado) de um lugar em que estão corretas, mas não estão funcinando em nenhum dos campos dos Expedientes diversos. Perceba-se no item 5 que um "á" é colado como "&aacute;"; deveria ser "Márcio".

**Comment by andreagudo** [comment]
Ok.
