### ISSUE TITLE
Ao adicionar sessão, selecionar o tipo para o sistema informar o próximo número

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#607]
Mudar o layout para que Tipo fique antes do Número. Legislatura e Sessão Legislativa também deve ser oferecidos, mas para edição, já que deve ser possível incluir sessões anteriores.

**Comment by eduardoedson** [comment]
Possui essa funcinalidade no 2.5?

**Comment by andreagudo** [comment]
Em parte. No 2.5, ao adicionar sessão, já apresenta o número da próxima do tipo Ordinária. Apesar disso, tem-se que informar o tipo no seu campo. Os campos Legislatura e Sessão Legislativa aparecem corretamente preenchidos, valendo o mesmo para a data, que mostra a atual.

**Comment by edwardoliveira** [comment]
@andreagudo Favor testar, obrigado.

**Comment by andreagudo** [comment]
Número da próxima sessão resolvido, mas não está salvando a sessão, apesar de não mostrar erro. Sugiro colocar o campo Tipo antes do Número. E que Legislatura e Sessão Legislativa atuais sejam informados automaticamente.

**Comment by eduardocalil** [comment]
Verifique se está do jeito que você gostaria, @andreagudo

**Comment by andreagudo** [comment]
Resolvido. Melhoraria com o Campo Tipo antes do Número, pois seguiria uma ordem de preenchimento de campos.

**Comment by andreagudo** [comment]
Essa funcionalidade deve permitir incluir sessões futuras e sessões do passado. Sendo assim, o ideal seria o sistema informar somente as sessões legislativas correspondentes à legislatura informada. Então, se o operador mudar a legislatura para inserir uma sessão antiga, seriam oferecidas apenas as sessões legislativas daquela legislatura. Hoje ele pode optar por uma sessão legislativa não correspondente, já que estão sendo listadas todas. Então, o ideal seria: definidas Legislatura, Sessão Legislativa e Tipo, o sistema ofereceria o próximo número de sessão correspondente a esses três critérios.

**Comment by andreagudo** [comment]
Estrutura correta. Ajustes necessários: 1) oferecer inicialmente, no campo Legislatura, a mais atual; 2) havendo erro ao salvar a sessão por falta de dado obrigatório, o campo Sessão Legislativa volta à mais atual da Legislatura correspondendente, enquanto o correto seria manter a selecionada antes da tentativa de salvar.

**Comment by andreagudo** [comment]
Ao editar dados básicos de uma sessão existente, no campo Sessão Legislativa não apecere o dado original correto. A tela fica assim:
![captura de tela de 2016-10-05 13 47 46](https://cloud.githubusercontent.com/assets/19169882/19122767/539e46e8-8b02-11e6-9d98-d3d047dac617.png)
