### ISSUE TITLE
Relatórios não carregam

### ISSUE THREAD

**Issue by eduardoedson** [interlegis/sapl#613]

**Comment by eduardocalil** [comment]
Desinstale e instale novamente o trml2pdf. Pare o servidor e rode novamente.

**Comment by edwardoliveira** [comment]
Siga o passos que o @eduardocalil falou e veja se o problema ainda persiste. :+1:

**Comment by eduardoedson** [comment]
Não funciounou.
`'NoneType' object has no attribute 'nome'`

**Comment by eduardoedson** [comment]
Dá erro quando a casa legislativa não está configurada.
