### ISSUE TITLE
Menu: Proposições X Matérias Legislativas

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#622]
O menu abaixo, para qualquer usuário, indica o acesso a proposições; na verdade, deveria indicar acesso a matérias; de qualquer modo, não tem apresentado resultado nenhum. Sugiro mudar para uma palavra mais genérica para evitar confusões (propostas ou matérias mesmo?) .

![captura de tela de 2016-09-26 10 00 57](https://cloud.githubusercontent.com/assets/19169882/18835697/d3aa5eda-83d2-11e6-92f2-2b464e3e8cb0.png)

**Comment by edwardoliveira** [comment]
@andreagudo A falta de informações pode ser resultado da migração. Ela foi feita há muito tempo atrás e pode ter ocorrido algum problema na hora de migrar os dados para o SAPL 3.1. Talvez seja necessário refazer uma nova migração para verificar isso.

**Comment by LeandroRoberto** [comment]
Na revisão feita no Crud, eu coloquei no menu "proposições" que está dentro de parlamentares todas uma listagem e visualização simples de proposições incorporadas, mas é válida a colocação de André, onde diz que deveria ser Matérias.... sim, Matérias de sua Autoria, ou Co-autoria... a rotina que faz essa tarefa atualmente é um crud resumido para apenas list e detail apontado para Proposicao... basta renomear o crud, algumas variáveis internas do crud, subnav.yaml e url.

**Comment by LeandroRoberto** [comment]
@edwardoliveira Decidiram apenas fazer o que foi feito em 6a1df22??? Porque é muito mais que isso...

**Comment by eduardoedson** [comment]
É pq, caso mudasse no model, iria mexer na tela de proposições também

**Comment by LeandroRoberto** [comment]
a solução sugerida por @andreagudo não mexe com model... apenas neste crud https://github.com/interlegis/sapl/blob/master/sapl/parlamentares/views.py#L94

**Comment by eduardoedson** [comment]
Pode verificar se ficou correto, por favor?

**Comment by LeandroRoberto** [comment]
o intuito não é trazer proposições incorporadas como está ocorrendo, o que @andreagudo levantou é que a listagem deve trazer todas as matérias em que determinado Autor é registrado no model Autoria

**Comment by edwardoliveira** [comment]
Ah, acho que entendi (???): seria referenciar MateriaLegislativa ao invés de Proposição?

**Comment by LeandroRoberto** [comment]
isso mesmo... não mexe... é um levatamento atráves do model Autoria das matérias que se relacionam com o parlamentar em visualização

**Comment by edwardoliveira** [comment]
Preciso de férias. Ainda bem que o Mazza volta semana que vem. :sweat:
