### ISSUE TITLE
Criação de PDF quandoa  casa não está configurada

### ISSUE THREAD

**Issue by LucianoAlmeida** [interlegis/sapl#624]
Quando a casa legislativa não está cadastrada/configurada a criação de PDFs falha quando tenta pegar o cabeçalho do site. O bug aparece quando tenta-se visualizar o PDF da pauta da sessão, por exemplo.

**Comment by edwardoliveira** [comment]
Estou na dúvida qual seria a melhor forma de tratar esse erro... :thought_balloon: Configurar a Casa Legislativa deve ser um dos primeiros passos após a instalação do SAPL, mas ainda assim, podemos ver muita gente ignorando isso... O que sugere?
