### ISSUE TITLE
Repetir os dados resumidos da sessão em todas as telas

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#627]
Tais dados não aparecem em: Explicações Pessoais, Matérias do Expediente, Oradores do Expediente e Matérias da Ordem do Dia. Em Mesa e Painel não foi possível verificar, pois pede login (#574).
![captura de tela de 2016-09-26 15 37 55](https://cloud.githubusercontent.com/assets/19169882/18847225/bd94a704-83ff-11e6-8791-1e5cfe295edd.png)

**Comment by andreagudo** [comment]
Não está coforme um padrão em: Explicações Pessoais consta "Oradores das Explicações Pessoais (100ª Sessão Ordinária da 3ª Sessão Legislativa da 1ª Legislatura); vale algo parecido para Matérias do Expediente, Oradores do Expediente e Matérias da Ordem do Dias. em Abertura, Mesa, Presença, Expedientes Diversos, e Presenças na Ordem do Dia consta apenas "100ª Sessão Ordinária da 3ª Sessão Legislativa da 1ª Legislatura".

**Comment by LeandroRoberto** [comment]
@eduardoedson pega essa issue pra gente amanhã?? Concorda @edwardoliveira? 
se sim, o fato é... onde aparace "Texto texto texo (textinho textinho textinho)" é porque é uma viu de um masterdetail  o que tá diferente tem é porque são templates isolados e devem ser adaptados....
o mais tranquilo a fazer para não mexer nos templates, isso se os templetes isolados mantiveram o padrão do title do base... é implementar como fiz pra resolver na sub-aba Mesa....
https://github.com/interlegis/sapl/commit/e110f3c21644434096f52830f6736f3e08373676
para manter esse padrão é só copiar e adaptar

**Comment by andreagudo** [comment]
Resolvido.
