### ISSUE TITLE
Criação de operador autor de proposições

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#628]
Há dificuldade na criação de operador autor de proposições. Foi criado, com o admin, um operador_autor2, perfil do grupo Autor e perfil individual para add, change e edit proposições. Como operador_geral e admin tentei incluir esse operador_autor2 como autor (informei a senha), o resultado é o seguinte:
![captura de tela de 2016-09-26 16 36 40](https://cloud.githubusercontent.com/assets/19169882/18849068/8facd192-8407-11e6-95b0-51831111431f.png)

No SAPL 2.5, ao selecionar o tipo, são listadas as alternativas correspondentes. o que não está ocorrendo no 3.1.

**Comment by LeandroRoberto** [comment]
#706
