### ISSUE TITLE
Ordem dos resultados de pesquisas

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#629]
A ordem dos resultados de pesquisas pode ser um dos parâmetros da pesquisa (crescente ou decrescente e por critério de data, tipo, ano e número, conforme o caso). Isso serve para Matérias Legislativas, Sessão Plenária e Pauta da Sessão.

**Comment by eduardoedson** [comment]
Já existe uma opção para ordenar a pesquisa.

![captura de tela de 2016-09-28 14-46-49](https://cloud.githubusercontent.com/assets/7716450/18925495/9013ade8-858a-11e6-85a8-b663cf197039.png)

**Comment by andreagudo** [comment]
Verdade.
