### ISSUE TITLE
Repetir o nome do parlamentar em todas as funções

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#630]
Repetir o nome do parlamentar em todas nas telas Mandatos, Filiações Partidárias, Dependentes, Comissões, Proposições, Relatorias e Frentes, como ocorre na tela Início.
![captura de tela de 2016-09-26 18 18 02](https://cloud.githubusercontent.com/assets/19169882/18852157/9d986f38-8415-11e6-969e-f594f00d7ae7.png)

**Comment by LeandroRoberto** [comment]
o esquema de títulos de telas vai mudar e será feito pela issue #648
