### ISSUE TITLE
Composição de comissão: botão "Incluir parlamentar" disponível para usuário anônimo

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#632]
Botão "Incluir parlamentar" disponível indevidamente para usuário anônimo, embora adiante peça login.
![captura de tela de 2016-09-27 07 57 54](https://cloud.githubusercontent.com/assets/19169882/18870708/5e24ffe2-8488-11e6-8b85-33b3865ddd3d.png)

![captura de tela de 2016-09-27 08 15 04](https://cloud.githubusercontent.com/assets/19169882/18871169/9092d6d2-848a-11e6-8322-c7e656d3bdb1.png)

**Comment by LucianoAlmeida** [comment]
Verificarei essa issue.

**Comment by andreagudo** [comment]
Resolvido.
