### ISSUE TITLE
Composição de comissão: implementar caixa de escolha do período de composição

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#633]
O link "Composição" apresenta imediatamente todos os períodos de composição da comissão, o que pode gerar uma tela muito grande. O ideal é que  tal link levasse a uma caixa na qual o usuário selecionasse o período de composição desejado, no formato ddmmaaaa.
![captura de tela de 2016-09-27 08 23 42](https://cloud.githubusercontent.com/assets/19169882/18871515/0e394dc2-848c-11e6-8dfb-9f770b53e4cb.png)

**Comment by eduardoedson** [comment]
Acredito que isso iria quebrar a padronização das telas de listagem. O que acha @edwardoliveira ?

**Comment by LeandroRoberto** [comment]
Sim.. .é é algo como Mesa diretora...

**Comment by LeandroRoberto** [comment]
![image](https://cloud.githubusercontent.com/assets/9630623/23028904/e1bfcb0c-f44f-11e6-9c3e-2716e7f72503.png)

**Comment by edwardoliveira** [comment]
Putz, bem fazer o quê, né? Mais uma tela que não será pelo CRUD... /cc @eduardoedson

**Comment by eduardoedson** [comment]
@andreagudo Veja se está ok

**Comment by andreagudo** [comment]
Ok.
