### ISSUE TITLE
Repetir o nome da comissão na função Composição

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#634]
Repetir o nome da comissão na função Composição, como ocorre em Matérias em Tramitação. Talvés substituir "Composição de Comissões" pelo nome da comissão, já que o menu indica que a tela trata da composição.
![captura de tela de 2016-09-27 08 30 02](https://cloud.githubusercontent.com/assets/19169882/18871665/cd845726-848c-11e6-8813-0c8451c7abb8.png)
![captura de tela de 2016-09-27 08 30 18](https://cloud.githubusercontent.com/assets/19169882/18871667/d19f9262-848c-11e6-8408-dda308e0bc82.png)

**Comment by andreagudo** [comment]
Ainda não corrigido.

**Comment by LeandroRoberto** [comment]
@andreagudo, vou fechar esta issue e todas que falam dos títulos... o esquema de títulos de telas vai mudar e será feito pela issue #648 
Assim que tiver pronto comunico e daí, se possível, vc dá uma repassada geral no comportamento dos títulos.
