### ISSUE TITLE
"Matérias em Tramitação" atualmente em comissão

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#635]
A pesquisa "Matérias em Tramitação" em comissão deve apresentar as que nela tramitam atualmente. O resultado está mostrando matérias que dela já saíaram, inclusive já arquivadas. No caso abaixo, além disso, apresenta duas vezes uma mesma matéria que passou duas vezes pela comissão. O resultado correto dessa pesquisa seria "Nenhuma matéria em tramitação nesta comissão atualmente".
![captura de tela de 2016-09-27 08 45 44](https://cloud.githubusercontent.com/assets/19169882/18872342/4dab4c86-8490-11e6-81c2-32ba02ea907a.png)

**Comment by edwardoliveira** [comment]
Duplicada em #636

**Comment by andreagudo** [comment]
Então fiquemos com a #636 que é mais ampla.
