### ISSUE TITLE
"Matérias em Tramitação" em comissão

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#636]
A pesquisa "Matérias em Tramitação" em comissão deve apresentar as que nela tramitam atualmente. O resultado está mostrando matérias que dela já saíaram, inclusive já arquivadas. No caso abaixo, além disso, apresenta duas vezes uma mesma matéria que passou duas vezes pela comissão. O resultado correto dessa pesquisa seria "Nenhuma matéria em tramitação nesta comissão atualmente".
![captura de tela de 2016-09-27 08 45 44](https://cloud.githubusercontent.com/assets/19169882/18872342/4dab4c86-8490-11e6-81c2-32ba02ea907a.png)

Outro aspecto é que essa pesquisa, nas duas comissões ativas (CCJ e CFOM), apresentam o mesmo resultado (em ordem diferente, embora não apareça na captura da tela), o que é incorreto por dois motivos: porquê as matérias já foram arquivadas e porquê não é possível que as matérias listas estajam em duas comissões ao mesmo tempo.
![captura de tela de 2016-09-27 09 02 41](https://cloud.githubusercontent.com/assets/19169882/18872637/e6782e56-8491-11e6-812b-46ddc78be790.png)
![captura de tela de 2016-09-27 09 03 04](https://cloud.githubusercontent.com/assets/19169882/18872646/ef47d4e6-8491-11e6-819e-54356cedeaea.png)

**Comment by eduardoedson** [comment]
Errei no commit [https://github.com/interlegis/sapl/commit/25f16834412e91f82e40921643e1d8178418e0a6](https://github.com/interlegis/sapl/commit/25f16834412e91f82e40921643e1d8178418e0a6)

**Comment by andreagudo** [comment]
Resolvidas as questões originalmente relatadas. Porém, as matérias em tramitação atualmente nas comissões não estão aparecendo (na CCJ os PL's 16 e 18/2015 e na CFOM o PL 1/2016).
![captura de tela de 2016-09-29 09 57 04](https://cloud.githubusercontent.com/assets/19169882/18954843/24f3c11e-862b-11e6-95c1-e408f22d56a7.png)

**Comment by eduardoedson** [comment]
@andreagudo Verifique agora, por favor.

**Comment by andreagudo** [comment]
Resolvido.
