### ISSUE TITLE
"Tramitação em Lote" e "Acessório em Lote" visíveis para usuário anônimo

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#637]
"Tramitação em Lote" e "Acessório em Lote" visíveis, indevidamente para usuário anônimo (o sistema pede login em ambos os casos).
![captura de tela de 2016-09-27 09 11 53](https://cloud.githubusercontent.com/assets/19169882/18872824/c0b0f2b0-8492-11e6-8e37-8ce04ff5c1b7.png)

**Comment by edwardoliveira** [comment]
@eduardocalil Teria como ver isso pra gente?

**Comment by eduardocalil** [comment]
Que operador que deve cuidar disso?

**Comment by andreagudo** [comment]
Operador_materia.

**Comment by andreagudo** [comment]
Resolvido.
