### ISSUE TITLE
Pesquisa de tramitação de matérias incorreta: verificar inconsistência ou mascaramento de dados

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#638]
As datas de tramitação estão corretas, mas informações sobre Unidade Local, Unidade Destino e status estão confusas (exemplo abaixo do Projeto de Lei 1/2015).
![captura de tela de 2016-09-27 09 19 14](https://cloud.githubusercontent.com/assets/19169882/18873104/29762f9e-8494-11e6-8fcc-ea354a9ffde2.png)

**Comment by eduardocalil** [comment]
Poderia explicar um pouco mais detalhadamente?

**Comment by andreagudo** [comment]
Abaixo a captura da tramitação do mesmo PL no SAPL 2.5, onde a ordem está correta. Veja que Unidade Destino deve suceder a Unidade Local, o que não está ocorrendo no 3.1. Segunda e terceira tramitações estão invertidas; quarta e quinta também; sexta e sétima também. Os Status estão correspondendo ás mudanças de Unidade. Então, parece que temos somente um problema de ordem das tramitações.
![captura de tela de 2016-09-27 15 47 43](https://cloud.githubusercontent.com/assets/19169882/18887299/dcfb36c4-84c9-11e6-85f1-66b0d1b4ef0f.png)

**Comment by andreagudo** [comment]
Resolvido.
