### ISSUE TITLE
Repetir o nome da matéria legislativa em todas as funções

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#639]
Repetir o nome da matéria legislativa nas funções Anexada, Autoria, Despacho Inicial, Documento Acessório, Legislação Citada, Numeração, Tramitação e Relatoria (em Texto está ok). 
![captura de tela de 2016-09-27 09 28 03](https://cloud.githubusercontent.com/assets/19169882/18873304/0d7154bc-8495-11e6-98a3-1209bc6664a4.png)

Talvés substituir o nome da função pela materia, já que a tela destaca a função. Se a opção for por manter repetida o nome da função, retirar os plurais (ou colocar plurais no menu).
 
![captura de tela de 2016-09-27 09 34 25](https://cloud.githubusercontent.com/assets/19169882/18873384/9bee5622-8495-11e6-91df-6ebfb6d45e0e.png)

**Comment by LucianoAlmeida** [comment]
Verificarei isso agora.

**Comment by LeandroRoberto** [comment]
o esquema de títulos de telas vai mudar e será feito pela issue #648
