### ISSUE TITLE
Usuário anônimo visualiza botão "Editar Texto" de matéria legislativa

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#640]
Usuário anônimo visualiza, indevidamente, o botão "Editar Texto" de matéria legislativa. Ver #592 
![captura de tela de 2016-09-27 09 54 35](https://cloud.githubusercontent.com/assets/19169882/18874529/792a0fa2-8498-11e6-8164-2a5b9994863c.png)

Tal link, indevido para o anônimo, está apresentando erro:
![captura de tela de 2016-09-27 09 56 15](https://cloud.githubusercontent.com/assets/19169882/18874597/c409a5be-8498-11e6-9f84-c5e013410ba9.png)

**Comment by LucianoAlmeida** [comment]
Verificarei isso agora.

**Comment by edwardoliveira** [comment]
@andreagudo Favor verificar se issue corrigida

**Comment by andreagudo** [comment]
Corrigida.
