### ISSUE TITLE
Matérias Legislativas e usuário anônimo

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#641]
Na pesquisa de matéria legislativa, o link Texto abaixo
![captura de tela de 2016-09-27 10 16 16](https://cloud.githubusercontent.com/assets/19169882/18875276/7c197b8c-849b-11e6-9446-ce02696ff661.png)

leva à seguinte tela:
![captura de tela de 2016-09-27 10 18 21](https://cloud.githubusercontent.com/assets/19169882/18875327/c1213792-849b-11e6-9a28-c61d7ec86723.png)

onde Publicações apresenta a tela seguinte, com "Adicionar Publicação" levando indevidamente à tela para salvar (embora as caixas de seleção não estejam funcionando)
![captura de tela de 2016-09-27 10 20 25](https://cloud.githubusercontent.com/assets/19169882/18875416/0970981c-849c-11e6-8a2f-e3a8714fd95d.png)

O botão Notificações leva à tela abaixo, onde os links abaixo do nome da matéria, que não funcionam, não deveriam aparecer
![captura de tela de 2016-09-27 10 24 13](https://cloud.githubusercontent.com/assets/19169882/18875546/9cf149d8-849c-11e6-9666-e9210c4292eb.png)

Verificar para que servem as funções Publicações (deve ser da matéria) e Notificações.

**Comment by LucianoAlmeida** [comment]
@andreagudo, sobre o botão de "Adicionar Publicação" que leva pra página não desejada, este já foi removido.
Sobre o que há na página de Notificações, eu não entendi ao certo o que deseja. Os links que não fazem nada na verdade são filtros. Esta tela lista todas as notificações dos textos, caso haja alguma (no exemplo da foto não tem nenhuma). Se houvessem notificações, você poderia selecionar nos filtros os tipos de notificações que seriam listadas e assim que apertasse o botão de filtrar somente as filtradas apareceriam na lista.
Neste caso, como não há notificações, gostaria que aparecesse um texto ao invés dos filtros e da lista vazia?

**Comment by andreagudo** [comment]
O problema de adicionar publicação permanece. Sobre Notificações, eu não sei do que se trata, nem com usar. No caso de Agudo, em testes, não há notificações para testar. Há que se ver na domentação para que serve tal função.

**Comment by LucianoAlmeida** [comment]
Sobre o botão, ele ainda permanece porque ainda não foi feito autalização do código na máquina de homologação.
Sobre as funcionalidades de Publicação e Notificação, acho que o @LeandroRoberto poderia nos ajudar a entender um pouco melhor como funciona.

**Comment by LeandroRoberto** [comment]
A partir de amanhã passo a mexer com Proposição. As coisas vão ficar mais claras com esse botão Texto e as telas a que são levados... tanto quanto a permissões quanto a ligação que existe existe entre Proposição -> MatériaLegislativa -> Norma Jurídica.

**Comment by andreagudo** [comment]
Ok.
