### ISSUE TITLE
Não há paginação no resultado da pesquisa de Materia Legislativa

### ISSUE THREAD

**Issue by LucianoAlmeida** [interlegis/sapl#644]
A paginação do resultado da pesquisa de Matéria Legislativa não está sendo mostrada. A paginação atual só mostra botões para página anterior e para a próxima, quando deveria aparecer os números das páginas.

**Comment by andreagudo** [comment]
No caso de Agudo mostra sim:
![captura de tela de 2016-09-27 14 26 01](https://cloud.githubusercontent.com/assets/19169882/18884601/7403c268-84be-11e6-970b-1b71f467b571.png)
