### ISSUE TITLE
Correções Ortográficas

### ISSUE THREAD

**Issue by wesleylima247** [interlegis/sapl#647]
Corrigir em Tabelas Auxiliares --> Módulo Parlamentares --> Nível de Intrução para Nível de Instrução. (falta um s).

Corrigir em Tabelas Auxiliares --> Módulo Parlamentares --> TIPO DE DEPENDENTE --> Ao listar os tipos o nome descrição está descricao --> Colocar Descrição.

**Comment by edwardoliveira** [comment]
@wesleylima247 Corrigi estes dois erros. Já está atualizado nas máquinas de homologação. Vou deixar a issue aberta caso vc encontre mais erros. Me avisa quando atualizar esta issue, ok?

**Comment by wesleylima247** [comment]
@edwardoliveira ok!

**Comment by wesleylima247** [comment]
Em sistema -> tabelas auxiliares -> Ao listar o Total de Regimes Tramitação, está -> descricao --> Corrigir para Descrição

Ao clicar em Adicionar Regimes de Tramitação --> está Descricao* --> corrigir para Descrição.

**Comment by eduardoedson** [comment]
Feito @wesleylima247
