### ISSUE TITLE
Implementar Configuração da Aplicação nativa padrão, editável

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#651]
Facilitará a vida do operador_geral. Há que indicar em tutorial que editá-la, se for o caso, é providência prioritária.

**Comment by eduardocalil** [comment]
Assim como Casa Legislativa deverá ser configurada inicialmente pelo operador_geral, então, seguindo essa lógica, ele deverá criar configurações da aplicação.

**Comment by andreagudo** [comment]
Erro:
![captura de tela de 2016-09-28 13 39 27](https://cloud.githubusercontent.com/assets/19169882/18922977/0fbe5926-8581-11e6-9b24-58b9736b8dad.png)

**Comment by eduardocalil** [comment]
@andreagudo verifique se resolveu, por favor

**Comment by andreagudo** [comment]
Resolvido.
