### ISSUE TITLE
Erro na edição das Leis e Projetos de Lei

### ISSUE THREAD

**Issue by adrchaves** [interlegis/sapl#653]
Pesquisando Leis e Projetos de Lei , na parte de EDITAR TEXTO, nesse caso Lei nº 89025 de 08 de Setembro de 2016, aparece o seguinte erro:
 
![sapl](https://cloud.githubusercontent.com/assets/22500466/18922433/fb74e87e-857e-11e6-9bef-b2e0cfc4f999.png)

**Comment by LeandroRoberto** [comment]
@edwardoliveira @adrchaves ... Isso só funciona na minha base, pois falta configuração inicial para injetar os parâmetros em outras bases... o inject já ta pronto só não está no master ainda... assim que encerrar o Crud vou fazer o  merge da app "compilacao" e passar homologação para se divertirem...

**Comment by adrchaves** [comment]
Ok @LeandroRoberto !

**Comment by LeandroRoberto** [comment]
@adrchaves foi implementado... ta funcionando agora.. vou fechar essa issue
