### ISSUE TITLE
Cadastro de matéria legislativa: partido do autor

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#655]
O sistema pede para informar o partido do autor, indevidamente.

**Comment by edwardoliveira** [comment]
A tabela de AUTORIA tem uma coluna para PARTIDO. Mas como vc disse, não se deve informar este dado. Recomenda-se pegar o partido atual do candidato e preencher este campo ou simplesmente remover esta coluna da tabela AUTORIA?

**Comment by andreagudo** [comment]
Remover, pois partido é um dado do autor, não da matéria.

**Comment by edwardoliveira** [comment]
Sim, vi aqui que nem existe no SAPL 2.5. Não sei quem incluiu esta coluna, mas estou removendo já.

**Comment by edwardoliveira** [comment]
@andreagudo Verifique se a solução está ok, agora.

**Comment by andreagudo** [comment]
Resolvido.
