### ISSUE TITLE
Cadastro de matéria legislativa: edição do autor

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#656]
Ao editar um autor responde que ele já foi cadastrado e não edita, o que torna necessário excluí-lo e incluí-lo novamente.

**Comment by eduardoedson** [comment]
Esse erro só ocorre caso esteja tentando editar e salvar com as mesmas informações novamente, correto?
Nesse caso seria necessário o uso do botão cancelar. Pois, no teste que fiz, ao mudar o autor, salvou normalmente.

**Comment by andreagudo** [comment]
Ok, é isso mesmo.
