### ISSUE TITLE
Cadastro de matéria legislativa: Legislação Citada

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#660]
Não há botão para incluir Legislação Citada.

**Comment by eduardoedson** [comment]
O botão para adicionar existe, porém o titulo e o label do botão estão incorretos.

![captura de tela de 2016-09-29 16-32-04](https://cloud.githubusercontent.com/assets/7716450/18969192/6d78b41c-8662-11e6-932a-3a2710377dea.png)

**Comment by eduardoedson** [comment]
Os nomes já foram consertados.

**Comment by edwardoliveira** [comment]
@andreagudo Favor verificar se esta issue pode ser fechada.

**Comment by andreagudo** [comment]
No teste com dados de Agudo ainda não aparece o botão Adicionar:
![captura de tela de 2016-09-30 08 02 37](https://cloud.githubusercontent.com/assets/19169882/18989810/5dc66992-86e4-11e6-8326-b05435a432ba.png)

**Comment by eduardoedson** [comment]
Logado como admin no sapl31agudo, consigo visualizar, então acredito que seja um problema na permissão.
@LeandroRoberto

![captura de tela de 2016-09-30 13-35-54](https://cloud.githubusercontent.com/assets/7716450/18999251/fc959f38-8712-11e6-9c22-691f58dbd2d2.png)

**Comment by andreagudo** [comment]
Testado agorinha, ainda sem premissão para o operador_materia.

**Comment by LeandroRoberto** [comment]
@andreagudo acho que tá arrumado... só conferir!

**Comment by edwardoliveira** [comment]
Sim, testei aqui com operador_materia e parece estar funcionando agora.

**Comment by andreagudo** [comment]
ok.
