### ISSUE TITLE
Cadastro de matéria legislativa: Tramitação

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#661]
A tramitação deve oferecer Data e Unidade Local atual. Dentre as Unidades Local e Destino, no caso de comissões listar apenas as ativas na data da tramitação. Talvés mudar o layout, com Data de Tramitação antes da Unidade Local.

**Comment by andreagudo** [comment]
A Unidade Local atual deve ser a Unidade Destino anterior.

**Comment by eduardocalil** [comment]
O sistema oferece a que seja inserida a Data e a Unidade Local na **criação** da tramitação. Após isso, na edição, esses campos não podem mais ser modificados. Por isso não aparecem.

Essa medida foi tomada para garantir que durante a edição de uma tramitação, a origem desta não seja diferente do destino da anterior e que sua data de tramitação não seja menor que a anterior.

**Comment by andreagudo** [comment]
Sim, estou tratando da criação de uma tramitação. Veja ta tela abaixo que Unidade Local (= Unidade Destino anterior) e Data da Tramitação (data atual) deveriam aparecer preenchidas ao "Adicionar Tramitação".
![captura de tela de 2016-09-30 08 11 58](https://cloud.githubusercontent.com/assets/19169882/18990086/15f4e68c-86e6-11e6-91ac-12763b0f6d28.png)

**Comment by andreagudo** [comment]
Resolvido o principal. Apenas penso que já poderia vir com Data da Tramitação preenchida com a data atual.
