### ISSUE TITLE
Cadastro de matéria legislativa: Relatoria

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#662]
Na caixa de seleção Parlamentar são listados todos. Devem ser listados apenas os membros atuais da Comissão. Selecionei um parlamentar inativo e o sistema o aceitou como relator, indevidamente.

**Comment by andreagudo** [comment]
Resolvido.Ok.

**Comment by eduardoedson** [comment]
Deve ser listado somente os parlamentares que participam da comissão atual? Ou todos os ativos, independente da comissão que participa?

**Comment by andreagudo** [comment]
Todos os membros atuais da comissão em que a matéria está.

**Comment by eduardoedson** [comment]
A comissão possui várias composições, dependendo do período, deve pegar os membros de todos os períodos ou só do mais recente?

**Comment by andreagudo** [comment]
Deve pegar os membros do período em que está sendo indicado o relator. normalmente o atual.

**Comment by LeandroRoberto** [comment]
@andreagudo @eduardoedson acho que foi resolvido, qdo der pra verificar...

**Comment by andreagudo** [comment]
Não, estão sendo listados todinhos os parlamentares, de todos os tempos.

**Comment by LeandroRoberto** [comment]
@andreagudo um link de exemplo??

**Comment by andreagudo** [comment]
http://sapl31agudo.interlegis.leg.br/materia/1942/relatoria/create

**Comment by LeandroRoberto** [comment]
Estão todos... sua base tem 108 parlamentares cadastrados... pode conferir aqui o total...
http://sapl31agudo.interlegis.leg.br/admin/parlamentares/parlamentar/
vai pedir senha... acessar com admin,admin
depois disso na combo de parlamentares desse link:
http://sapl31agudo.interlegis.leg.br/materia/1942/relatoria/create
é possível ver que estão os 108
como... ctrl-shit-i
abrir a console da inspeção de elemento:
rode isso

$('#id_parlamentar option').length
vai mostrar 109 por causa do item 'Selecione...'

**Comment by andreagudo** [comment]
Devem ser listados na caixa de seleção apenas os quatro membros da composição atual da comissão.

**Comment by LeandroRoberto** [comment]
haha... sabe a vírgula desse comentário...
"Não, estão sendo listados todinhos os parlamentares, de todos os tempos."

**Comment by eduardoedson** [comment]
@andreagudo Foi resolvido?

**Comment by andreagudo** [comment]
Não, ainda aparecem todos os parlamentares, de todos os tempos.

**Comment by edwardoliveira** [comment]
@andreagudo Esse erro ainda persiste???

**Comment by edwardoliveira** [comment]
@andreagudo O @eduardoedson Já tinha colocado um filtro para parlamentares ativo lá atrás então eu acho que os dados podem estar inconsistentes, isto é, todos os parlamentares estão como ativos no sapl31agudo. De qualquer forma coloquei mais uma restrição para filtrar somente os que fazem parte daquela comissão. Por favor veja se o bug ainda persiste. E abra a issue, caso contrário.

**Comment by andreagudo** [comment]
@edwardoliveira o bug persiste. Não são todos os parlamentares que estão ativos. O filtro deve ser parlamentares da comissão no período de composição atual.

**Comment by eduardoedson** [comment]
@andreagudo Verifique, por favor

**Comment by andreagudo** [comment]
Melhorou, mas deve ser adicionado mais um critério: apenas os titulares da comissão devem ser listados.

**Comment by LeandroRoberto** [comment]
@eduardoedson seu commit 	0b64341 causou erro no travis
https://travis-ci.org/interlegis/sapl/builds/203938530

**Comment by eduardoedson** [comment]
O que seria um titular da comissão?

**Comment by eduardoedson** [comment]
@andreagudo verifique novamente

**Comment by andreagudo** [comment]
Primeiro: a inclusão de relator está sendo feita pelo operador_materias, mas não devia ser pelo operador_comissoes?
Segundo: ainda estão listados todos os membros da comissão; deivam ser apenas os titulares.

**Comment by eduardoedson** [comment]
Verifique na comissão se não estão todo como titulares

**Comment by eduardoedson** [comment]
A questão do operador melhor verificar com o @LeandroRoberto

**Comment by eduardoedson** [comment]
@andreagudo Eu tinha esquecido de enviar na sexta, poderia verificar o caso dos parlamentares? Verifiquei em: 
http://sapl31agudo.interlegis.leg.br/materia/1983/relatoria/create
http://sapl31agudo.interlegis.leg.br/comissao/15/composicao
E me parece estar correto

**Comment by LeandroRoberto** [comment]
@eduardoedson, feito em: f3bc43f

**Comment by edwardoliveira** [comment]
:fireworks: :fireworks: :clap: :clap:

**Comment by andreagudo** [comment]
Operador: ok.
Listagem membros titulares: ok.
Issue Resolvida.
