### ISSUE TITLE
Sessão Plenária: operador_sessão editando Mesa Diretora

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#667]
Botões Editar e Excluir juntos não funcionam. Botão Excluir vermelho não funciona e não é necessário, pois qualquer mudança na Mesa deve ser feita pelo botão Editar que deve funcionar do mesmo modo da primeira inclusão dos membros da Mesa (quando as inclusões e exclusões funcionam bem).

![captura de tela de 2016-09-29 15 16 49](https://cloud.githubusercontent.com/assets/19169882/18966499/c8330fb6-8657-11e6-9212-53d3e7a14e85.png)

**Comment by andreagudo** [comment]
Agora o botão Excluir que restou não funciona.

**Comment by LeandroRoberto** [comment]
está ok... testado em.. http://sapl31agudo.interlegis.leg.br/sessao/346/mesa

**Comment by LeandroRoberto** [comment]
Resolvido na #684

**Comment by andreagudo** [comment]
O botão Excluir ainda não funciona.

**Comment by LeandroRoberto** [comment]
o sentido do é a exclusão de um item da mesa e não da mesa como um todo... ou seja deve clicar em cima do nome daquele que vc quer remover...
@edwardoliveira com isso foi possível ver que o botão excluir está confuso, e dando a entender que é para excluir a mesa... clicá-lo sem ter selecionado nada causa, realmente a impressão de que nada está ocorrendo

**Comment by edwardoliveira** [comment]
+1. @eduardocalil poderia desabilitar esse botão. Sei que tem em outros lugares pq vi na semana passada.

**Comment by edwardoliveira** [comment]
![image](https://cloud.githubusercontent.com/assets/9326037/19084990/00b352f2-8a3f-11e6-92e3-b27c7617b2ce.png)

O @eduardocalil já resolveu isso.

**Comment by LeandroRoberto** [comment]
não é isso @edwardoliveira...  e não estava resolvido... mas resolvi... tinha outro problema aí também, qdo troca a seleção de legislatura ele tentava achar parlamentares dentro da sessão legislativa anterior, o que é incorreto pois... veja o que foi feito em:
https://github.com/interlegis/sapl/commit/0dfb6c306dfeb29c19b3c1a18f607ad9020089fc#diff-51916774ef55dd6d98fe71461b360a22R248

Classe MesaDiretoraView

**Comment by edwardoliveira** [comment]
Ok, entendi errado.

**Comment by LeandroRoberto** [comment]
Olha que lindo esse TODO:
https://github.com/interlegis/sapl/blob/master/sapl/sessao/views.py#L750

**Comment by edwardoliveira** [comment]
Que escreveu isso... Ops, fui eu... Um ano atrás. :fearful:

**Comment by andreagudo** [comment]
Resolvido.
