### ISSUE TITLE
Sessão Plenária: operador_sessao incluindo Matéria do Expediente - Data ordem

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#670]
Campo Data ordem\* não é desnecessário? Não basta a data da sessão? Vale o mesmo para Adicionar Matéria da Ordem do Dia.

**Comment by andreagudo** [comment]
Deve ser mudado o nome do campo "Data ordem*" para "Data da Sessão". Isso bastará para resolver.

**Comment by edwardoliveira** [comment]
Oi @andreagudo, favor checar se resolveu. Obrigado!

**Comment by andreagudo** [comment]
Resolvido.
