### ISSUE TITLE
Sessão Plenária: Pesquisa do botão Adicionar Várias Matérias na Ordem do Dia não funciona

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#672]
O resultado sempre é "Nenhuma matéria encontrada com essas especificações".
![captura de tela de 2016-09-29 15 54 46](https://cloud.githubusercontent.com/assets/19169882/18967939/69941008-865d-11e6-82b4-c19a07550b6e.png)

**Comment by eduardocalil** [comment]
Manda o print da tela de pesquisa e da tela de resultados. Isso só acontece se não houver nenhuma matéria com o status atual "Ordem do Dia".

**Comment by andreagudo** [comment]
Agora funcionou: selecionei opções Tipo=PL e Ano=2015; marquei os que queria e foram para a Ordem do Dia.

**Comment by andreagudo** [comment]
Resolvido.

**Comment by andreagudo** [comment]
Voltou a não funcionar.

**Comment by eduardocalil** [comment]
Essa pesquisa já pega automaticamente as que estão com status='Ordem do Dia'. Entretanto, a falta de resultados se deve ao fato de não haver nenhuma PL de 2015 com esse status. Pode conferir pesquisando alguma matéria com esses parâmetros.

**Comment by andreagudo** [comment]
Realmente, funciona. Porém, se o status já está automaticamente definido (corretamente), por quê pode-se adicinar critérios, além daquele? Não bastaria o critério automático? De quelquer modo, depois da explicação do @eduardocalil , percebi que está funcionando.

**Comment by LeandroRoberto** [comment]
@eduardocalil mude a estratégia... o sapl não pode entrar em produção assim
`
def filtra_tramitacao_ordem_dia():
    lista = pega_ultima_tramitacao()
    return Tramitacao.objects.filter(
        id__in=lista,
        status__descricao='Ordem do Dia').distinct().values_list(
        'materia_id', flat=True)
`
primeiro pela questão, de imediato menos importante, que é a tradução,
segundo, esse texto é dinâmico e cada casa chama isso de um geito... aqui,
por exemplo esse texto seria: "Proposição inclusa na Ordem do Dia"
@edwardoliveira tome nota!

**Comment by edwardoliveira** [comment]
Certo. Anotado. :+1:

**Comment by andreagudo** [comment]
Teria que ser filtrado pelo número identificador do status Ordem do Dia. Se uma casa usar outro texto, bastaria editá-lo. O identificador seri mantido. Poderia ser?

**Comment by LeandroRoberto** [comment]
o identificar também não é fixo... se isso é uma regra de negócio, o ideal que parece ser criar um campo lá em configurações da aplicação onde esteja listados todos os status e um deles selecionado, como status de ordem do dia.
