### ISSUE TITLE
Sessão Plenária: adicionar critério Status em pesquisa

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#673]
Adiconar o critério Status na Pesquisa do botão Adicionar Várias Matérias na Ordem do Dia.

**Comment by edwardoliveira** [comment]
@andreagudo Que critério é esse? É um critério de tramitação da Matéria Legislativa?

**Comment by andreagudo** [comment]
Sim, critério de tramitação.

Em 29/09/2016 17:44, "Edward" <notifications@github.com> escreveu:

**Comment by eduardocalil** [comment]
Até onde sabemos, não pode ter 'Status'. Pois para Adicionar Várias Matérias, já assumimos que o Status dela é 'Ordem do Dia'.

**Comment by andreagudo** [comment]
Ok. Se há issue sobre sobre "esse status padrão para colocar na inclusão de várias matérias', esta pode ser fechada.
