### ISSUE TITLE
Mandatos do parlamentar: votos da coligação

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#676]
Na pesquisa do usuário anônimo pelos mandatos do parlamentar apresentar também os votos do partido/coligação. Tal informação consta nas Tabelas Auxiliares, mas não aparece em nenhuma pesquisa. As colunas ficariam nessa ordem: Legislatura, Votos Recebidos, Partido, Coligação, Votos Recebidos do Partido/Coligação, ... A interpretação seria: havendo coligação, a coluna Votos Recebidos do Partido/Coligação diria respeito à coligação, senão, seria do partido.

**Comment by andreagudo** [comment]
Funciona para alguns, outros não.
Legislatura atual Ver. Carlito Schiefelbein
AttributeError at /parlamentar/19/mandato

'NoneType' object has no attribute 'numero_votos'

Request Method: 	GET
Request URL: 	http://sapl31agudo.interlegis.leg.br/parlamentar/19/mandato
Django Version: 	1.9.7
Exception Type: 	AttributeError
Exception Value: 	

'NoneType' object has no attribute 'numero_votos'

Exception Location: 	/home/sapl31/sapl/sapl/parlamentares/views.py in get_rows, line 136
Python Executable: 	/home/sapl31/.virtualenvs/sapl/bin/python3
Python Version: 	3.4.3
Python Path: 	

['/home/sapl31/sapl',
 '/home/sapl31/.virtualenvs/sapl/bin',
 '/home/sapl31/sapl',
 '/home/sapl31/.virtualenvs/sapl/lib/python3.4',
 '/home/sapl31/.virtualenvs/sapl/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/sapl31/.virtualenvs/sapl/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/sapl31/.virtualenvs/sapl/lib/python3.4/site-packages']

Server time: 	Seg, 3 Out 2016 15:56:36 -0300

**Comment by andreagudo** [comment]
Votos da coligação = "None" quando tal campo não é informado. O ideal seria em branco.

**Comment by edwardoliveira** [comment]
Isso é um *erro*. Devemos tratar.

**Comment by LeandroRoberto** [comment]
Isso??? 
![image](https://cloud.githubusercontent.com/assets/9630623/19052395/001354da-898d-11e6-98e7-a276d90240e4.png)

**Comment by edwardoliveira** [comment]
@LeandroRoberto Me parece que sim, mas não sei dizer.

**Comment by andreagudo** [comment]
Tem que ser assim mesmo.

**Comment by edwardoliveira** [comment]
@LeandroRoberto Uma dúvida: essas mudanças em sapl/crud/base.py fazem parte de https://github.com/interlegis/sapl/issues/648 ?

**Comment by LeandroRoberto** [comment]
@edwardoliveira depois que fiz o merge hoje de madruga, já houve algumas correções e melhorias ao longo do dia... o que está neste commit https://github.com/interlegis/sapl/commit/23187f959a3280bf8b69619f7a528dad9b6fe7bd mesmo é algo que eu tinha deixado pra depois, mas fiz hoje mesmo!

**Comment by andreagudo** [comment]
Resolvido.
