### ISSUE TITLE
Usuário anônimo vê botões e tem acesso a funcionalidades de editar e excluir publicações

### ISSUE THREAD

**Issue by LucianoAlmeida** [interlegis/sapl#678]
Quando um usuário não autenticado acessa a página de detalhe de alguma publicação, caso haja publicações cadastradas, ele consegue ver botões de editar e excluir. Além de conseguir ver os botões, essas funcionalidades não estão sendo barradas, podendo um usuário anônimo editar e excluir estas publicações.
Para acessar o detail da publicação, deve-se acessar a listagem de publicações que fica no detail de uma  materia legislativa -> texto -> publicações.

**Comment by LeandroRoberto** [comment]
essa funcionalidade é da app compilacao  que ainda não é controlada pelas permissões

**Comment by LeandroRoberto** [comment]
Será resolvido por #546
