### ISSUE TITLE
Faltam as ementas das Matérias do Expediente da sessão

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#681]
![captura de tela de 2016-10-04 08 07 37](https://cloud.githubusercontent.com/assets/19169882/19072085/acf27498-8a09-11e6-8742-d5471e30a924.png)

**Comment by eduardoedson** [comment]
Acredito que essa matéria não possue ementa ou ocorreu algum erro na migração de alguma(s). Pois teste em [http://sapl31agudo.interlegis.leg.br/sessao/325/expedientemateria](http://sapl31agudo.interlegis.leg.br/sessao/325/expedientemateria) e todas as matérias listadas possuem ementa.

**Comment by eduardoedson** [comment]
@andreagudo Verifique se foi corrigido, por favor.

**Comment by andreagudo** [comment]
Corrigido.
