### ISSUE TITLE
Sessão Plenária: campo URL vídeo de Oradores do Expediente também para observações

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#682]
É possível usar o campo URL vídeo para observações? No caso de Agudo as incrições para Oradores do Expediente são prévias à sessão e, caso alguém abra mão do uso da palava, seria bom registrar tal decisão.

**Comment by andreagudo** [comment]
O campo está aceitando texto, mas teria também que aceitar URL, o que não está ocorrendo.
![captura de tela de 2016-10-04 10 59 15](https://cloud.githubusercontent.com/assets/19169882/19077128/b79535da-8a21-11e6-8eb3-b4246328a37a.png)

**Comment by eduardoedson** [comment]
@andreagudo Veja se agora ficou de seu agrado

**Comment by andreagudo** [comment]
Apenas corrigir o campo URL, pois não está funcionando como tal.

**Comment by edwardoliveira** [comment]
@eduardoedson @andreagudo Não sei se gostei dessa solução. Por que não adicionar um campo observação à tabela???????

**Comment by andreagudo** [comment]
Sim, @edwardoliveira , foi feito isso e funciona bem. Mas o campo URL não reconhece o conteúdo como tal.

**Comment by edwardoliveira** [comment]
Sim, testamos aqui e vimos isso. Vou ver o que aconteceu _agora_.

**Comment by eduardoedson** [comment]
Veja se foi resolvido.

**Comment by andreagudo** [comment]
O conteúdo do campo URL vídeo ainda não é um link.
![captura de tela de 2016-10-06 08 13 23](https://cloud.githubusercontent.com/assets/19169882/19150361/ce87201a-8b9c-11e6-88fa-683d5e31ec2a.png)

**Comment by edwardoliveira** [comment]
Acho que agora foi! :smile: Favor verificar, obrigado!

**Comment by andreagudo** [comment]
Funcionando. No campo Observação, porém, não há necessidade de reconhecer URL, pois a ideia é que contenha texto simples. Havia colocado URL's nesse campo somente para testes.
