### ISSUE TITLE
Sessão Plenária: mudar a tela dos botões Listar e Adicionar

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#683]
Os botões Listar Sessões Plenárias e Adicionar Sessão Plenária deveriam aparecer na primeira tela da função Sessão Plenária. junto com a pesquisa de sessões. Onde eles estão, misturam-se com informações sobre uma determinada sessão.
![captura de tela de 2016-10-04 09 22 32](https://cloud.githubusercontent.com/assets/19169882/19074510/df337c38-8a16-11e6-9c6e-4a193a99cc5a.png)

**Comment by LeandroRoberto** [comment]
não... eles podem até ser desativados para sessões, mas essas telas de visualização de detalhes são tela padrão... em que estando na visualização de algo, e tendo direito, vc pode:
- ir para listagem,
- adicionar um novo de um mesmo,
- editar o que está vendo,
- excluir o que está vendo
é mais fácil perceber isso entrando com operador_geral e navegando por comissoes, parlamentares, matérias... onde as telas são mais padronizadas...
toda tela que vc entrar de um cadastro tradicional, terá esse formato, 
somado a isso existem algumas telas que possuem pesquisa, o que precisa então é ser possível trocar esse botão listar para nova pesquisa nestes casos...

**Comment by andreagudo** [comment]
Sendo esse o padrão, bastaria que tais botões estivessem também na tela de pesquisa de sessões, que é a primeira que aparece em Sessões Plenárias.

**Comment by LeandroRoberto** [comment]
@andreagudo 
a issue foi fechada automaticamente, mas valide por favor...
![image](https://cloud.githubusercontent.com/assets/9630623/19123127/d8123640-8b03-11e6-9c27-0fad397f64c9.png)

![image](https://cloud.githubusercontent.com/assets/9630623/19123151/ea0ddb10-8b03-11e6-8a97-e6b39afd8f5c.png)

![image](https://cloud.githubusercontent.com/assets/9630623/19123173/0078bd7a-8b04-11e6-84c1-2336d4bc4e16.png)

**Comment by andreagudo** [comment]
Resolvido.
