### ISSUE TITLE
Sessão Plenária: mudar a ordem dos cargos na caixa de seleção de cargos da Mesa

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#684]
Mudar a ordem de cargos da caixa de seleção dos membros da Mesa da Sessão Plenária para Presidente, Vice e Secretário.

**Comment by LucianoAlmeida** [comment]
Verei isso agora.

**Comment by LeandroRoberto** [comment]
@LucianoAlmeida ... issue ligada a #667 que está funcionando, testei em http://sapl31agudo.interlegis.leg.br/sessao/346/mesa
falta fazer essa... ficar na ordem e fechar as duas

**Comment by LucianoAlmeida** [comment]
Pull request criado para corrigir essa issue.

**Comment by LucianoAlmeida** [comment]
Agora entendi o que gostaria nessa issue. Estou subindo um código pra master, logo mais deve ser possível fazer testes novamente desse problema.

**Comment by andreagudo** [comment]
Resolvido.
