### ISSUE TITLE
Sessão Plenária: retornar à lista de Matérias do Expediente depois de Adicionar Várias Matérias

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#686]
Depois de Adicionar Matérias Selecionadas fica o sistema na tela de seleção, embora as matérias recentemente adicionadas estejam salvas entre as Matérias do Expediente.

**Comment by LucianoAlmeida** [comment]
Verificarei essa issue.

**Comment by andreagudo** [comment]
Resolvido.
