### ISSUE TITLE
Pesquisa Normas Juridicas

### ISSUE THREAD

**Issue by adrchaves** [interlegis/sapl#688]
Pesquisa normas jurídicas, não possui campo para pesquisa por assunto ou ementa.

**Comment by eduardocalil** [comment]
Você poderia me dizer o que seria o campo termos? Além disso, o campo assunto é uma caixa de opções com uma lista de assuntos pré-definidos?

**Comment by LeandroRoberto** [comment]
@eduardocalil é pesquisar no campo ementa... 
e sobre o resultado... a paginação está aparecendo duas vezes

**Comment by adrchaves** [comment]
Obrigada @LeandroRoberto por ter respondido. Só vi agora.

**Comment by eduardoedson** [comment]
Pesquisa por assunto foi feito.

**Comment by eduardoedson** [comment]
@LeandroRoberto @adrchaves @edwardoliveira  Na pesquisa por ementa, tem que ser informado toda a ementa ou só parte dela para ser feita a busca?

**Comment by LeandroRoberto** [comment]
só parte dela... palavras desconexas ou parte delas...
algo assim, é o mínimo:
https://github.com/interlegis/sapl/blob/master/sapl/crud/base.py#L510-L516
