### ISSUE TITLE
Listar comissões em Unidade de Tramitação

### ISSUE THREAD

**Issue by wesleylima247** [interlegis/sapl#695]
Em tabelas auxiliares--> unidade de tramitação --> adicionar unidade de tramitação, está listando os órgãos e parlamentares. Mas comissão não. Mesmo tendo adicionado as comissões no módulo comissões de tab auxiliares.

![screen shot 2016-10-05 at 08 29 09](https://cloud.githubusercontent.com/assets/19570385/19111800/d216d5ec-8ad7-11e6-8389-3964c6b2f42d.png)

**Comment by eduardoedson** [comment]
Testei localmente, no sapl31agudo e no sapl31demo, e nos três caso é possivel adicionar comissão.

**Comment by LucianoAlmeida** [comment]
Fiz testes também e está tudo funcionando corretamente.

**Comment by eduardoedson** [comment]
Resolvido?

**Comment by wesleylima247** [comment]
Resolvido. Era um problema local que não estava atualizado.
