### ISSUE TITLE
Permitir a adição de mais de um documento a uma norma ou matéria

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#697]
Na lista de discussão do Engitec:

```
"Gostaria de sugerir a possibilidade de se adicionar mais de um documento a uma norma ou matéria no SAPL 3.1.
 Recentemente houveram fiscalizações dos TC e alguns apontaram que os documentos são disponibilizados em apenas um formato, seria interessante poder disponibilizar os documentos em um formato não proprietário como o ODT por exemplo."
```

**Comment by edwardoliveira** [comment]
Acho que podemos tentar ainda esse mês... :thinking:

**Comment by LeandroRoberto** [comment]
#495

**Comment by edwardoliveira** [comment]
@eduardoedson @LeandroRoberto Desculpa, na época estava super otimista. Deixamos isso para release futuro?

**Comment by LeandroRoberto** [comment]
li seu primeiro comentário em 5/10/2016. São urgências e coisas diferentes, veja:
I) adicionar vários arquivos com diferentes formatos dos dados, seja matéria ou norma, é relevante, mas obviante pode ser uma melhoria futura... 
II) adicionar vários arquivos para adição das partes de um documento não é uma realidade no 2.5 mas é uma funcionalidade necessária.
ex: uma grande norma digitalizada como imagem (a maioria do país faz assim) que possui anexos é um documento inviável de se publicar em apenas um pdf... minha LOA deste ano, por exemplo,  possui 167 páginas, sendo que o corpo da lei são apenas 7 páginas, o resto está distribuindo em 7 ou 8 anexos que poderiam estar publicados separadamente dando mais facilidade e objetividade no download dos usuários...  ou seja... uma norma precisa poder receber vários arquivos...

do ponto de vista técnico, seria relevante fazer isso agora... veja... hoje o campo FileField é único e está no Model NormaJuridica. No futuro, decidindo que uma norma possa ter mais de um arquivo, possivelmente, um datamigrate de arquivo terá que ser criado... duas ideias técnicas para isso:
1) dependendo da lógica que se decida... é possível que se mantenha esse arquivo em NormaJuridica como o principal e único possível da norma e que se crie um model AnexoNormaJuridica e seus anexos sejam adicionados aí... 
2) (prefiro esta, nos dá a possibilidade inclusive de publicação de páginas independentes, o D.O.U. faz assim - parece) o arquivo principal também seja migrado para um model como ArquivoNormaJuridica onde pode haver metadados informado se é principal, principal-tipado (parece resolver ou ser o caminho para resolver (I) acima), anexo, paginado, ou qualquer outra coisa que se pense mais seriamente na hora da implementação.

é... 2 com (I) parece ser a melhor opção, 
é resolvida com NormaJuridica, ArquivoNormaJuridica, VersaoDeArquivoNormaJuridica
modelo sai em um dia, 
views e layout sai em uma semana.

**Comment by edwardoliveira** [comment]
Obrigado pelo feedback! :+1:

**Comment by lizianem** [comment]
Gostaria de saber se há previsão de implantação desta melhoria: adição de mais arquivos/documentos à norma jurídica.

O Plano Diretor de Porto Alegre, Lei Complementar 433/199, é complexo, possui várias atualizações anuais, possui vários tipos de anexos (como podem verificar no link http://leismunicipa.is/ugljb ). É impraticável juntar o corpo do Plano Diretor aos mais de 11 Anexos (composto de subitens e imagens muito pesadas).

Outra situação: para as REPUBLICAÇÕES de um mesma norma, seria interessante também manter os dois arquivos (o original e a Republicação).

@edwardoliveira
