### ISSUE TITLE
Faltam os horários de abertura e de encerramento no resumo da sessão plenária

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#698]
![captura de tela de 2016-10-05 13 42 27](https://cloud.githubusercontent.com/assets/19169882/19122609/a10f5c2e-8b01-11e6-923d-b5a3f90bf68b.png)

**Comment by andreagudo** [comment]
Ainda não resolvido:
http://sapl31agudo.interlegis.leg.br/sessao/348/resumo

**Comment by eduardoedson** [comment]
![captura de tela de 2016-10-06 14-01-47](https://cloud.githubusercontent.com/assets/7716450/19162288/9b61a1b6-8bcd-11e6-9dbc-452916b4815c.png)

**Comment by andreagudo** [comment]
Resolvido.
