### ISSUE TITLE
Implementar geração de pdf do resumo da sessão plenária

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#699]
Implementar o pdf para usuários anônimo e operador.

**Comment by eduardocalil** [comment]
O usário anônimo tem alguma restrição ou pode ter acesso ao relatório pdf completo?

**Comment by andreagudo** [comment]
Acesso completo ao pdf da sessão.

Em 06/10/2016 19:59, "eduardocalil" <notifications@github.com> escreveu:

**Comment by eduardocalil** [comment]
Já existe o relatório da Sessão. Qual seria a diferença entre o relatório da Sessão e do Resumo da Sessão? 

Exemplo: http://sapl31agudo.interlegis.leg.br/relatorios/311/sessao-plenaria

**Comment by andreagudo** [comment]
@eduardocalil , realmente, não há diferença. Mas não há onde gerar o pdf de dentro da sessão.

**Comment by edwardoliveira** [comment]
@andreagudo Colocamos um link para a impressão do PDF no Resumo. Veja se ficou a contento. Senão pode reabrir o ticket.

**Comment by andreagudo** [comment]
Está ok.
