### ISSUE TITLE
Cadastro de legislaturas

### ISSUE THREAD

**Issue by wesleylima247** [interlegis/sapl#700]
Erro ao cadastrar nova legislatura.

![screen shot 2016-10-06 at 09 40 59](https://cloud.githubusercontent.com/assets/19570385/19152968/e02be57c-8baa-11e6-8c5c-ef2a726f68c4.png)

**Comment by wesleylima247** [comment]
@edwardoliveira

**Comment by LucianoAlmeida** [comment]
Verei isso agora.

**Comment by edwardoliveira** [comment]
@wesleylima247 Eu fiz um quick-fix pra te permitir incluir legislatura, mas o @LucianoAlmeida está trabalhando nessa tela, inclusive ele tem uma dúvidas com relação a criação de legislatura.
