### ISSUE TITLE
Inconsistência nos dados das Legislaturas

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#705]
Os números das legislaturas se repetem.
![captura de tela de 2016-10-06 14 04 38](https://cloud.githubusercontent.com/assets/19169882/19162344/dc413a2a-8bcd-11e6-8ec7-6fd9d8a7a303.png)

**Comment by eduardoedson** [comment]
@edwardoliveira Parece ser um problema nos dados da maquina, pois na minha, local, está correto.

**Comment by edwardoliveira** [comment]
Consertado.

**Comment by andreagudo** [comment]
Resolvido.
