### ISSUE TITLE
Sessão Plenária: O form de edição não está carregando a Sessão Legislativa.

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#707]

**Comment by edwardoliveira** [comment]
Que bizarro! Não tenho idéia do que pode ser. Talvez um renomeação...

**Comment by eduardoedson** [comment]
Na verdade parece que no create também. Ela só é preenchida depois de mudar a legislatura, sendo que ja vem uma legislatura selecionada, então devia vim os dados dela.

**Comment by edwardoliveira** [comment]
Me parece o seguinte: na criação, vamos selecionando os campos e recuperando dinamicamente via JS. Na edição, os valores chegam à página ao mesmo tempo, mas como ainda não criamos o segundo select então este valor "se perde". Pelo menos foi isso que me pareceu na sexta...
