### ISSUE TITLE
Compilação: não há como inserir alínea seguinte

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#708]
![captura de tela de 2016-10-07 14 53 45](https://cloud.githubusercontent.com/assets/19169882/19200249/64f8d6c2-8c9e-11e6-90b7-f6836637ea7a.png)
![captura de tela de 2016-10-07 14 58 40](https://cloud.githubusercontent.com/assets/19169882/19200294/91e5e79c-8c9e-11e6-8100-fd353f68cda3.png)

**Comment by LeandroRoberto** [comment]
Alteração feita.

**Comment by andreagudo** [comment]
Resolvido.
