### ISSUE TITLE
Compilação: não há como inserir inciso seguinte

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#709]
![captura de tela de 2016-10-07 15 00 22](https://cloud.githubusercontent.com/assets/19169882/19200345/e9a3d854-8c9e-11e6-974c-f5d23d5b1871.png)
![captura de tela de 2016-10-07 15 00 31](https://cloud.githubusercontent.com/assets/19169882/19200349/f085e220-8c9e-11e6-8fcc-37d8565f3574.png)

**Comment by LeandroRoberto** [comment]
Alteração feita.

**Comment by andreagudo** [comment]
Funcionou.
