### ISSUE TITLE
Pesquisa Matéria Legislativa e Adicionar Várias Matérias

### ISSUE THREAD

**Issue by eduardoedson** [interlegis/sapl#719]
Cadastrei duas novas matérias e a pesquisa não encontra elas.
Deixando todos os campos em branco ou mesmo preenchendo, a pesquisa nao encontra.

![captura de tela de 2016-10-11 09-12-38](https://cloud.githubusercontent.com/assets/7716450/19269855/20aa5c0a-8f93-11e6-85cc-729ba843e9de.png)
![captura de tela de 2016-10-11 09-12-01](https://cloud.githubusercontent.com/assets/7716450/19269854/20a90cce-8f93-11e6-80f7-217380d4843a.png)
![captura de tela de 2016-10-11 09-11-48](https://cloud.githubusercontent.com/assets/7716450/19269853/20a379a8-8f93-11e6-8c95-b3d09f79194e.png)

**Comment by eduardoedson** [comment]
Acontece o mesmo em adicionar várias matérias (Expediente e Ordem)

**Comment by eduardocalil** [comment]
Qual o status da tramitação delas?

**Comment by eduardocalil** [comment]
Elas devem estar como ordem do dia para aparecer

**Comment by eduardoedson** [comment]
Era um status teste que eu criei pois estava usando um banco vazio

**Comment by eduardocalil** [comment]
Confere se arrumou, por favor
