### ISSUE TITLE
Mesa Diretora com erro

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#727]
'NoneType' object has no attribute 'composicaomesa_set'

**Comment by LeandroRoberto** [comment]
Olá, @DTILegBG...
não deu pra saber quem é mas vi que é da Câmara Municipal de Bento Gonçalves...
bem vindo ao ambiente de desenvolvimento do Sapl3.1, agradecemos pela iniciativa em testá-lo.

Quanto ao erro, poderia detalhar um pouco mais...
Estava logado ou com acesso anônimo?
Foi logo ao clicar em Instituicional -> Mesa Diretora?
Pode mandar um print screen da tela, aqui mesmo?

**Comment by LeandroRoberto** [comment]
Levando em consideração o erro apontado por você nesta issue e na #728... preciso pedir a você que vá na pasta raiz do seu projeto e verifique em em que versão voc está... digite, por favor...

git log
O topo da tela precisa estar assim
![image](https://cloud.githubusercontent.com/assets/9630623/19279440/d18a374c-8fb7-11e6-8d9e-facb2e38b548.png)

**Comment by DTILegBG** [comment]
Opa, Boa tarde Leandro.

Desculpe o mau jeito.

Sim, Rogério aqui da Câmara de Bento / RS, espero poder contribuir pelo 
menos nos testes.

com usuário anônimo, clicando em institucional/mesa diretora

http://sapl31demo.interlegis.leg.br/mesa-diretora/

gera o erro

Exception Value:

'NoneType' object has no attribute 'composicaomesa_set'

Abraço


Em 11/10/2016 13:32, Leandro Roberto da Silva escreveu:

**Comment by LeandroRoberto** [comment]
eeeeiiitaa... no demo online????? vixi... @edwardoliveira

**Comment by LeandroRoberto** [comment]
Valeu Rogério @DTILegBG ... acho que a maquina do endereço sapl31demo ficou louca

**Comment by DTILegBG** [comment]
Rs. pois é, pensei que tava atualizada.

Desculpe pelos post então.

Vou colocar uma vm aqui e vou rodar o projeto aqui.

Na sequencia reporto.



Em 11/10/2016 13:38, Leandro Roberto da Silva escreveu:

**Comment by LeandroRoberto** [comment]
não não... não há o que desculpar... vc não encontrou um bug realmente no sapl mas encontrou na VM do sapl31demo... faz parte também!!!

**Comment by edwardoliveira** [comment]
@DTILegBG 

Só uma dica de git. Faça assim: 

     git log --oneline -n 10 

Isso vai trazer os últimos 5 commits (-n 5), do *mais recentes para o mais antigo* em uma linha somente. O que importa é a primeira coluna alfa-numérica. Ela diz qual foi o último commit. Rodando na repo atual a saída foi essa:

       6123d26 Fix #723
       b6b9e2a Corrige erro na separação de str em list de teste
       2e373e2 Merge pull request #726 from interlegis/falso-positivo
       c4cf398 Remove arquivo teste
       b2f47e6 Fix urls_publicas_excecoes

Neste caso, o último commit foi ``6123d26``.

**Comment by DTILegBG** [comment]
Ok, obrigado, consegui fazer a instalação e estou com a versão atualizada.

Estou tentando fazer a migração do banco mysql para o postgres, este 
procedimento já está pronto?

Segui isto:

#####

a configuração para o banco do 3.1 é feita no .env...
para a solução de migração saber onde está seu sapl 2.5, vc deve 
configurar esse arquivo
https://github.com/interlegis/sapl/blob/master/sapl/legacy_migration_settings.py

fazê-lo apontar para o banco do 2.5, além de dar as devidas permissões 
lá no mysql...

ATENÇÃO: faça cópia antes... talvez até restaure com outro nome de banco 
de dados e aponte o legacy, citado acima, para essa restauração

com o banco configurado, vc deve entrar no prompt no python assim:
  ./manage.py shell_plus --settings=sapl.legacy_migration_settings

estando no prompt, digitar:
%run sapl/legacy/migration.py
migrate()

enquanto executa o migrate, vá beber um café! ;)

se der algum problema,
possivelmente a estrutura de sua base 2.5 está diferente da oficial, 
encontrada aqui:
https://colab.interlegis.leg.br/browser/publico/ILSAPL/trunk/instalacao/sapl.sql

diferenças na base são permitidas na migração mas pode ocorrer de causar 
erro...
por exemplo:
se na base oficial do 2.5 um campo é VARCHAR(30), na versão oficial do 
3.1 também é de tamanho 30. Se, por algum motivo, alguém da sua casa 
legislativa, alterou isso para VARCHAR(50) e existe registros que usa 
esse espaço excedente, na migração ocorrerá erro... caberá a você, 
ajustar sua base, para rodar novamente o migrate

###,

Rodando este cara  ./manage.py shell_plus 
--settings=sapl.legacy_migration_settings

dá erro , o django reclama de modulos

  Error loading MySQLdb module: No module named 'MySQLdb'

instalando o modulo

sudo pip install MySQL-python


dá erro e reclama do modulo    ImportError: No module named 'ConfigParser'




Em 11/10/2016 14:59, Edward escreveu:

**Comment by edwardoliveira** [comment]
@LeandroRoberto @DTILegBG Na verdade, isto é um erro de dados que expôs a falta de tratamento de casos especiais. Assim, se criar uma Legislatura nova, sem Sessões Plenárias associadas, esta tela dá um erro. Eu alterei para mostrar uma mensagem, mas a falta de sessão plenária na última legislatura ainda causa um monte de erro esquisito. /cc @eduardoedson 

ps: Devo retomar na próxima quinta.

**Comment by edwardoliveira** [comment]
@DTILegBG Sobre a tua questão se a migração estar pronta? Não. Ainda estamos terminado o novo SAPL. ;) Mas é *muito importante* que tenhamos o máximo de gente testando pra que possamos identificar bugs não somente no sistema, mas nas rotinas de migração também. Assim, aconselho a testar conforme o README e nos reportar se alguma coisa não ocorrer conforme o planejado.

**Comment by edwardoliveira** [comment]
@DTILegBG Favor confirmar a solução. :smiley:
