### ISSUE TITLE
installation process in ubuntu 14.04

### ISSUE THREAD

**Issue by johnfelipe** [interlegis/sapl#730]
Hi bro, installation process in readme is working for 14.04 to?

**Comment by eduardocalil** [comment]
@marciomazza

**Comment by johnfelipe** [comment]
@marciomazza, bro pls tell me if u share me a cheatsheet for 14.04
Tnks

**Comment by edwardoliveira** [comment]
Hi, our staging machines are Ubuntu 14.04, even though my development box is 15.04.

**Comment by johnfelipe** [comment]
And where is installation commands?

**Comment by edwardoliveira** [comment]
I have followed the installation process as listed here: https://github.com/interlegis/sapl/blob/master/README.rst

The libraries installed through ``sudo apt-get`` are the ones that could have changed since I installed last time, I guess.

**Comment by edwardoliveira** [comment]
As I wrote above, it has been some time, so we would be more than happy if you could validate the installation process and let us know if anything goes awry. Thanks! :)
