### ISSUE TITLE
Refatorar Proposições

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#738]

**Comment by andreagudo** [comment]
Usuário criou a proposição, a enviou e o operador_protocoloadm a recebeu. Considerações. O operador_protocoloadm não visualiza como chegar ao link http://sapl31agudo.interlegis.leg.br/proposicao/receber/ ; deve-se colocar tal link no menu, talvez em Atividade Legislativa.

**Comment by andreagudo** [comment]
Em Tabelas Auxiliares, ao Adicionar Tipo de Proposição, por quê se deve preencher a Descrição se o texto será um dos tipos disponíveis para seleção? Não bastaria marcar e assumir o texto marcado?

**Comment by LeandroRoberto** [comment]
a questão do link foi resolvida... era um erro de digitação que fez o menu sumir... quanto ao cadastro de descrição, está convicto? @edwardoliveira, opinião?
