### ISSUE TITLE
Matéria Legislativa: resultado de pesquisa deve apresentar data de votação

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#740]
A tela abaixo deveria apresentar a data de votação da proposição:
![captura de tela de 2016-10-17 15 55 07](https://cloud.githubusercontent.com/assets/19169882/19448953/97084666-9482-11e6-9d47-e94049774675.png)

Isso já ocorre no SAPL 2.5, como abaixo:
![captura de tela de 2016-10-17 15 56 29](https://cloud.githubusercontent.com/assets/19169882/19449018/ba334866-9482-11e6-87d5-57635ceac945.png)

**Comment by edwardoliveira** [comment]
@andreagudo Acabei de fazer uma alteração que adiciona o hyperlink para votação. Ainda estou na dúvida se isto resolve 100%. Teria como testar?

**Comment by andreagudo** [comment]
Está apontando para a sessão certa, mas para os Dados Básicos da sessão. O ideal seria apontar para a parte da sessão onde ocorreu a votação (Matérias do Expediente ou Ordem do Dia, dependendo do caso).

**Comment by edwardoliveira** [comment]
@andreagudo Fiz as alterações  para permitir que ele vá direto para a listagem de matérias. Veja se está a contento. Senão basta abrir a issue de novo (ele fechou automaticamente).

**Comment by andreagudo** [comment]
Está ok. Funciona para matérias votadas tanto na Ordem do Dia quanto em Matérias do Exepediente.
