### ISSUE TITLE
Testar e validar notificação de email's no cadastro de autor

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#741]
@edwardoliveira Gostaria que fosse testado o serviço de email do cadastro de Autor...
mudei pouca coisa em get_success_url mas como houve mudanças é necessário testar... tanto na criação autor, quanto na alteração.

**Comment by edwardoliveira** [comment]
:+1:

**Comment by eliseuegewarth** [comment]
![screenshot from 2017-08-10 10-24-44](https://user-images.githubusercontent.com/5272409/29172414-3f63bea4-7db6-11e7-9687-74a4aa3c2701.png)
email de confirmação foi enviado pelo Django usando a configuração
```
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
```
para teste local. 

Substituir pela configuração
```
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
```
em produção e configure o servidor smtp do seu sistema.

**Comment by LeandroRoberto** [comment]
@eliseuegewarth não entendi bem o que vc quis dizer...
significa que existe configuração diferente para modo debug 

se sim e o exemplo abaixo estiver certo, sugiro que implemente como aqui:
https://github.com/interlegis/sapl/blob/master/sapl/settings.py#L42

exemplo:
```
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
```

**Comment by eliseuegewarth** [comment]
Parece adequado. Vou implementar verificar umas coisas e já subo o PR.
