### ISSUE TITLE
Menu participação

### ISSUE THREAD

**Issue by eduardoedson** [interlegis/sapl#743]
Se estiver na tela de participação [(essa)](http://localhost:8000/comissao/138/participacao/create), o menu fica quebrado.

**Comment by LeandroRoberto** [comment]
???
![image](https://cloud.githubusercontent.com/assets/9630623/19600061/15f221ac-9782-11e6-8b95-ea7baddcbc2f.png)

**Comment by eduardoedson** [comment]
Quando clica em alguma opção no menu, o link tá quebrado

**Comment by LeandroRoberto** [comment]
ok... vi aqui que apenas o create está com problema, confirme daí se a edição e exclusão está ok...

**Comment by eduardoedson** [comment]
Só o create mesmo :+1:
