### ISSUE TITLE
Informações no resultado da pesquisa em modo anônimo de matérias legislativas

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#744]
No sapl 2.5, quando existiam matérias anexadas a matéria pesquisada, era mostrado desta forma:
##### 

PLO 105/2016 - Projeto de Lei Ordinária
ACRESCE O ART. 12-A NA LEI N° 4.430 DE 13 DE AGOSTO DE 2008.
Apresentação: 08/07/2016
Processo: 134/2016
Protocolo Geral: 1096/2016 - Data de Entrada: 08/07/2016
Autor: Moacir Antônio Camerini
Votação em:  18/07/2016
Localização Atual: Arquivo
Situação: Proposição aprovada
Última Ação: PROJETO VETADO E ARQUIVADO. VETO ACATADO. (VIDE VETO Nº 4/2016)  -  Em: 06/09/2016
Matéria Anexada: VETO 4/2016 - Data Anexação: 11/08/2016

VETO 4/2016 - Veto
Veto Integral ao Projeto de Lei n° 105/2016, que "ACRESCE O ART. 12-A NA LEI N° 4.430, DE 13 DE AGOSTO DE 2008".
Apresentação: 11/08/2016
Processo: 134/2016
Protocolo Geral: 1262/2016 - Data de Entrada: 11/08/2016
Autor: Prefeito Municipal - Mandato 2013/2016
Votação em:  05/09/2016
Localização Atual: Arquivo
Situação: Proposição aprovada
Última Ação: VETO ACATADO E ARQUIVADO. OFÍCIO DE ENCAMINHAMENTO Nº 446/2016/DEP/LEG.  -  Em: 06/09/2016
Matéria Anexadora: PLO 105/2016 - Data Anexação: 11/08/2016
#### 

Agora isso não ocorre mais

IND 1/2016 - Indicação
Autores:
Localização Atual:  
Status:  
Data da última Tramitação:  
Ementa: Ementa de teste da indicação de nº1

Também acho interessante que quando não existir a informação, não apareça o label Autores: , Status.........e assim por diante

Também quando uma matéria vira lei, a norma jurídica referencia a matéria. Então na matéria deveria ficar disponível essa informação, como ocorre no 2.5
Na pesquisa de matéria legislativa:
Norma Jurídica Vinculada
Texto Integral:Texto integral    LEI ORDINÁRIA 6146/2016

**Comment by edwardoliveira** [comment]
@DTILegBG O que ainda falta dessa issue para resolver? As últimas alterações relacionadas foram os commits https://github.com/interlegis/sapl/commit/97c9dddf2ae2d4947f72d347666d70e4633ef9b5 e https://github.com/interlegis/sapl/commit/daa9492eacd42a1137b6c67e102409abc996f0a2

**Comment by DTILegBG** [comment]
A principio está ok
