### ISSUE TITLE
Implementar media_protected para Proposições e Documentos Administrativos

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#751]
Links para arquivos de Proposições ainda não incorporadas e Documentos Administrativos com o sapl configurado para Docs restritivos deve ser protegidos... exitem diversas formas de se fazer isso, mas o que me parece mais viável é uma pequena mudança ao declarar os campos filefield nesses dois modelos citados, bem como uma customização nas configurações entre django e nginx onde o nginx interage como o django antes da entrega do arquivo solicitado.

**Comment by LeandroRoberto** [comment]
uuid4 + filenames diversos apesar de tornar url de um arquivo praticamente
impossível de ser localizado não está controlando o acesso.
Exemplo: o SAPL está configurado para ser docs adm restritivo porém 
alguem resolve perga o link e mostrar o tal arquivo para um amigo, ou um
vizinho de departamento que não possui acesso... ou mesmo alguem que nem ao
menos está logado... este arquivo estará livre

outro caso, um funcionário bem intencionado, mas com um computador infectado
que consegue pegar todos os links da página que ele está acessando e esse
funcionário possui permissão para ver arquivos de docs administrativos. 
Consequentemente os arquivos se tornarão públicos pois podem ser acessados
via url sem controle de acesso.

* texto de replicado em sapl.protocoloadm.models.py

**Comment by eduardoedson** [comment]
Uma dúvida: Fizemos uma url diferente para os arquivos que necessitam de permissão para ser acessado e fizemos as devidas verificamos na view, com isso, ainda é necessário fazer a validação do nginx?

**Comment by edwardoliveira** [comment]
@LeandroRoberto Me lembro que o @eduardoedson e eu implementamos essa solução de URL diferente. Essa issue ainda é relevante em face disso?

**Comment by LeandroRoberto** [comment]
entregar arquivos diretamente com o django, por uma view fazendo a validação de acesso é seguro mas segundo o que já estudei sobre o assunto não é eficiente... o eficiente seria a comunicação com o nginx para validação porém, isso não impede manter a solução atual que segundo vcs já funcionam e a suposta solução mais eficiente, seja uma issue de qualidade para o futuro.

**Comment by edwardoliveira** [comment]
Sim, não é eficiente como está hoje enquanto estudávamos isso também. Uma coisa que me preocupou na época foi que delegando a configuração pro nginx, então se o operador não configurasse corretamente os arquivos ficassem abertos para acesso público. Além de uma certa complexidade no tráfego de headers entre nginx e django para verificar se o usuário está logado, se tem permissão, etc.

Vc deu uma excelente idéia. Vou abrir uma issue para o futuro para habilitar que o admin do SAPL possa escolher entre os dois métodos (URL alternativa ou nginx). Daí a pessoa usa o que quiser.
