### ISSUE TITLE
Presenças na Ordem do Dia: erro ao ir direto da tela de votação

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#755]
Há o erro abaixo ao ir direto da tela de votação, sem registrá-la, para a tele de Presenças na Ordem do Dia.
![captura de tela de 2016-10-24 10 24 50](https://cloud.githubusercontent.com/assets/19169882/19645573/2218fc54-99d4-11e6-9caf-acc0912cfedf.png)

**Comment by eduardocalil** [comment]
Esse erro ocorre quando se está em uma votação nominal e tenta clicar em Presenças no subnav. Não ocorre em votação secreta e nem na votação simbólica. Votação nominal é gerada pelo template sessao/votacao/nominal e os outros dois por sessao/votacao/votacao. 

Quando clica em Presença, o último valor da url ((?P<mid>\d+)) é substituido por 'presença', ao invés de chamar a url de de presença.

Acredito que seja algo na construção da URL pelo CRUD. @marciomazza @LeandroRoberto @eduardoedson
