### ISSUE TITLE
Ajustar relatórios de acordo com a refatoração de Autor.

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#756]
https://github.com/interlegis/sapl/commit/70d0b721a9e15d6ddcfcc7ff8516e60dfc5f97a0

**Comment by LeandroRoberto** [comment]
fiz comentários inline no commit...

**Comment by eduardoedson** [comment]
@LeandroRoberto Esse problema ainda está acontecendo?

**Comment by LeandroRoberto** [comment]
Não sei...

**Comment by eduardoedson** [comment]
Olhamos em pauta da sessão e os autores estão vindo. Então pode fechar, @edwardoliveira ?

**Comment by LeandroRoberto** [comment]
esta issue se referia aos scripts que que estão na app relatorios... pasta templates...
