### ISSUE TITLE
Refatorar Painel Eletrônico

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#758]
Ditto.

**Comment by edwardoliveira** [comment]
Relaciona-se a #757

**Comment by wesleylima247** [comment]
@edwardoliveira essa se relaciona com a #762 e #757 .
Presença interativa e votação por parlamentares

**Comment by wesleylima247** [comment]
TESTES DO PAINEL:

- Painel não está computando os votos .
Os votos seriam da ordem do dia ou do expediente? 
- Seria interessante mostrar na tela do painel o Orador principal.
- O cronômetro do discurso seria das explicações pessoais ou da matéria do expediente? Poderia ter a opção de escolhermos.
- Ao ficar próximo e ao finalizar o tempo do cronômetro poderia soar um aviso sonoro.
- Aumentar a fonte do crônometro (do contador).
- Ao clicar em controlador painel ele abre uma outra aba no navegador, ex: ao clicar em abrir painel, e salvar. Deveria ter a opção de fechar a aba ou voltar para a tela prinicpal de painel eletrônico.

O operador_painel controla o painel, o operador_sessao por enquanto controla as votações, ao ele abrir votação e registrar a votação deveria enviar para a tela do operador_painel atualizando as votações. (enquanto não for votação interativa)

@eduardocalil @edwardoliveira

**Comment by LeandroRoberto** [comment]
@wesleylima247 consegue fazer um rascunho a caneta (ou no corel... hahaha) de um layout base para o painel???

**Comment by eduardocalil** [comment]
@wesleylima247 

- Estamos refatorando a lógica do Painel, pois estava com alguns problemas. Ele funcionará da seguinte forma: Primeiro verifica se há uma Ordem aberta. Se sim, mostra ela no painel. Caso contrário, verifica se há um Expediente. Se não houver verifica se há algumas Ordem ou Expediente já votado, respectivamente. Você concorda com essa lógica? Sugere algo?

- Você quer que aumente a fonte dos cronômetros de Discurso/Aparte/Questão de Ordem?

**Comment by wesleylima247** [comment]
1. Concordamos com essa lógica.
2. Isso, aumentar a fonte: dos cronômetros de Discurso/Aparte/Questão de Ordem.

Nessa refatoração entra a votação interativa por parlamentares? Mesmo a votação pelo operador_sessao não está aparecendo os votos.

@eduardocalil

**Comment by eduardocalil** [comment]
Como assim interativa? O que você quer que tenha?

**Comment by wesleylima247** [comment]
Ao abir ou fechar o painel em /painel/controlador , o botão VOLTAR não funciona.

Em /sessao/X/painel como operador_painel eu inicio o cronômetro. 
Ao abrir a mesma tela com outro usuário por exemplo como operador_geral o croômetro começa a contar do início. Não estão sincronizados.

**Comment by edwardoliveira** [comment]
@wesleylima247 O botão voltar vamos consertar. 

Mais de um operador por painel, sim, estamos cientes desse bug, mas é que é **absurdamente complexo** sincronizar relógios entre máquinas e até mesmo entre tabs de um mesmo browser em JavaScript (ressalva: da forma como estamos fazendo **hoje**), mas vamos quebrar a cabeça pra ver como implementar. Vai demorar, talvez. A idéia é que não tenha mais de um operador por vez, mas podemos ver como implementar mais de um mantendo os relógios sincronizados.

/cc @eduardocalil

**Comment by wesleylima247** [comment]
@edwardoliveira certo. 
No caso o operador_painel compartilharia a tela com o plenário (janela do navegador)? E como ficaria o usuário anônimo?

**Comment by edwardoliveira** [comment]
Sim, isso. Estamos estudando uma forma de vários usuários acessarem o painel.

Não existe possibilidade do usuário anônimo ter acesso ao painel. Painel é só pra Plenário, mas vamos implementar uma tela pra usuário anônimo com os dados do Painel na semana que vem :pray:

**Comment by eduardocalil** [comment]
@wesleylima247 Você testou o Painel esses últimos dias? Essa issue é para a refatoração que já foi feita e, por isso, será fechada. Por favor, crie outra issue solicitando as mudanças que acha importante.
