### ISSUE TITLE
Votação Nominal: registro de votação sem preencher presenças

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#759]
Na Ordem do Dia, ao registrar uma votação nominal sem preencher a lista de presenças na OD, o sistema deveria avisar que  o número de votos não corresonde aos presentes. Apresenta apenas a tela abaixo, característica de votação simbólica.
![captura de tela de 2016-10-24 13 53 26](https://cloud.githubusercontent.com/assets/19169882/19652910/54b8d6a8-99f1-11e6-8892-fa20a71b8906.png)

**Comment by eduardoedson** [comment]
Veja se foi resolvido, por favor.

**Comment by andreagudo** [comment]
Resolvido.
