### ISSUE TITLE
Remoção de TipoMateriaLegislativa não funciona

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#761]
TipoMateriaLegislativa não funciona a deleção, conforme screenshot abaixo. 

PS: @LeandroRoberto vc tem idéia do que seja isso????

![image](https://cloud.githubusercontent.com/assets/9326037/19688315/01e5a944-9aa8-11e6-9229-22159baf406c.png)

**Comment by LucianoAlmeida** [comment]
Esse erro está acontecendo também durante a migração.
