### ISSUE TITLE
Implementar Votação Eletrônica

### ISSUE THREAD

**Issue by wesleylima247** [interlegis/sapl#762]
O parlamentar está presente na ordem do dia, no painel está aparecendo o parlamentar e a matéria para votação.

O parlamentar está cadastrado como autor e com usuário. Mas esse parlamentar/usuário náo fica disponível para votar

Tela abaixo do operador_geral que abriu a votação:
![screen shot 2016-10-25 at 10 20 22](https://cloud.githubusercontent.com/assets/19570385/19689109/a37cb6ea-9aa2-11e6-9d6c-ac9508c43fb7.png)

Tela do parlamentar

![screen shot 2016-10-25 at 10 21 43](https://cloud.githubusercontent.com/assets/19570385/19689129/af1effb2-9aa2-11e6-84e7-4b5f225e4c0a.png)

**Comment by edwardoliveira** [comment]
Até onde eu entendo, esta tela é de registro de votos não de votação. Assim, o operador registra os votos obtidos, mas o sistema não prevê, **que eu saiba** um sistema de votação interativa. Outros colegas como @eduardoedson @LeandroRoberto @marciomazza @morale @andreagudo podem me corrigir se eu estiver enganado?

**Comment by andreagudo** [comment]
No 2.5 não ha votação interativa, um operador registra os votos. Tentei testar o 3.1 pensando do nisso.

**Comment by wesleylima247** [comment]
Então é o operador_sessao que vai registrar os votos?
Pensei que no 3.1 ia ser interativa. Pq os parlamentares terão acesso ao sistema com login, tem também lá em tabelas auxiliares --> cadastros de computadores. Pensei que era para isso.

**Comment by andreagudo** [comment]
@wesleylima247 , penso que estás correto: parlamentares com acesso e votando. Eu é que fiz um teste pensando que seria o operador_sessao que faria os registros. O ideal seria, porém, o sistema facultar as duas opções nas Tabelas Auxiliares. Mas há que se resolver isso para que os testes ocorram corretamente.

**Comment by LeandroRoberto** [comment]
@wesleylima247 está correto na questão de votação interativa mas existem duas frentes... quando se fala de sapl 2.5 não existe painel eletrônico e existe um registro operacional (operador_sessao) do que aconteceu em tal documento... isso passa apenas por registrar a votação. Não existe, pelo que me lembre, de opções "abrir votação", "registrar votação"... além disso, parlamentares possuem acesso com perfil de Autor par lidar apenas com proposições...

já no sapl 3.0 (que não entrou em produção) foi implementado quase que totalmente o perfil Parlamentar... ou seja, um usuário do sistema poderia ter outro perfil ou ainda duplo perfil => ['Parlamentar', 'Autor']. Nesse cenário, o usuário poderia criar suas proposições e, através dos cadastros e confirmações de mac e ips... registrar presença na sessão... não me recordo se havia votação interativa nem nesse caso...

**Comment by edwardoliveira** [comment]
Bem, se assim for então isso muda *muito* o requisito de painel. Até então estávamos trabalhando com o registro de votação, e status no Painel. Não votação interativa. Penso que votação interativa deva ficar pra uma próxima versão. Não daria tempo de mudar esse requisito + consertar os bugs mais urgentes da versão atual + apresentar no Engitec. Concorda, @marciomazza ?

**Comment by edwardoliveira** [comment]
@eduardoedson Podemos ver como é feito o registro de presença do Parlamentar no 3.0 e fazer o mesmo para o 3.1. Creio que isto será o embrião de votação interativa... :thinking:

**Comment by wesleylima247** [comment]
@edwardoliveira  @LeandroRoberto  Etendo. A nossa expectativa com o SAPL 3.1 seria o parlamentar votar interativamente. Penso que em uma casa legislativa com muitos parlamentares seria sujeito a erros de um operador_sessao registrar um voto errado. :(

**Comment by LeandroRoberto** [comment]
com certeza!!!
@edwardoliveira  vai refatorar o painel e resolver a questão de presença interativa... quando todas as validações de segurança estiverem ok, minha experiência que votação interativa será um detalhe.

**Comment by wesleylima247** [comment]
Legal. Vai ser muito boa essa feature.
