### ISSUE TITLE
Email de confirmação de usuário demorando muito para ser entregue

### ISSUE THREAD

**Issue by eribeiro** [interlegis/sapl#763]
Segundo testes do André, um usuário criado na quinta-feira teve email de confirmação recebido somente na terça seguinte.

**Comment by LeandroRoberto** [comment]
acabei de fazer testes a partir de sapl31demo.interlegis.leg.br para dois servidores de emails bem distintos...
@gmail.com
@camarajatai.go.gov.br

esses dois não possuem relação entre si... 
a notificação de uso de email no cadastro foi instantânea.

**Comment by edwardoliveira** [comment]
Estou fechando esta issue, se houver algum tipo de problema assim abrimos outra.
