### ISSUE TITLE
Criar subnav_pauta.yaml e associar nas views  

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#764]
a subnav de pauta está apontando para sessão... criar a subnav referente a pauta de sessão e refatorar as views adicionando no contexto a variável subnav_template_name para o o yaml criado.

**Comment by edwardoliveira** [comment]
@LeandroRoberto Poderia fornecer pra gente umas dicas de como fazer isso. Eu e o @eduardoedson estamos meio perdidos nessa alteração. Valeu!

**Comment by LeandroRoberto** [comment]
**Nossa Referência de Pauta:** http://sapl.agudo.rs.leg.br/consultas/pauta_sessao/pauta_sessao_plen_mostrar_proc?cod_sessao_plen=402&dat_sessao=05/12/2016

**Nossa Referência de Sessão:**
http://sapl.agudo.rs.leg.br/consultas/sessao_plenaria/agenda_sessao_plen_mostrar_proc?cod_sessao_plen=402

na verdade quando eu disse sobre a necessidade de haver um  subnav_pauta.html é que os menus da pauta não pode apontar para as funcionalidades da sessão... aliás... ao montar esse comentário, verifiquei, dados os links acima que pauta não tem menu.... 

além disso... o link pdf está com erro: 
http://sapl31agudo.interlegis.leg.br/relatorios/366/sessao-plenaria

na pauta não se diz sobre resultado da votação... e sim sobre situação:
![image](https://cloud.githubusercontent.com/assets/9630623/23136190/4428d90a-f77a-11e6-9e3d-c6dfa4e1b2b4.png)

**Comment by edwardoliveira** [comment]
Sim, o Edu acabou de subir uma mudança pra não apontarem mais. Vou olhar esse erro do PDF agora.

**Comment by edwardoliveira** [comment]
@LeandroRoberto O @eduardoedson retirou o os sub-menus de Pauta de Sessão e eu troquei Resultado de Votação por situação atual da Matéria. Vou fechar essa issue, mas se vc detectar algo mal feito ou uma pendência, pode abrir. :smile:
