### ISSUE TITLE
O que são os models AssuntoMateria e MateriaAssunto?

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#766]
não há implementação qualquer para eles...

**Comment by eduardoedson** [comment]
Encontrei isso no 2.5:
![2](https://cloud.githubusercontent.com/assets/7716450/19732142/93132578-9b7e-11e6-937a-7015c24a76c7.png)
![1](https://cloud.githubusercontent.com/assets/7716450/19732143/934da7b6-9b7e-11e6-9a3b-b6803db8c949.png)

**Comment by eduardoedson** [comment]
Na verdade o assunto só pode ser adicionado na edição.

**Comment by edwardoliveira** [comment]
Tá me cheirando a **tags** ou **labels** que podem ser buscadas depois...

**Comment by LeandroRoberto** [comment]
vixi... isso na 3.0 foi até tirado, acabei de olhar... no sapldemo.interlegis.leg.br (2.5) da erro quando entra nas tabelas auxiliares -> Assunto matéria... 

deixa a issue aberta???
a implementação do modelo está ruim mas pode ser tags mesmo... 
alias, tem esse e os assuntos de norma jurídica que poderiam ser resolvidos com app taggit... mas envolve mais migração... :-1:

**Comment by marciomazza** [comment]
É bom fazer consultas a todos os bancos da nossa hospedagem e ver o que isso nos diz.

**Comment by marciomazza** [comment]
São classificações de assunto mesmo, segundo @morale. 
A funcionalidade é semelhante aos assuntos de norma.
A tabela assunto_materia do sapl 2.5 está na parte de sistema e contém os termos de classificação (os assuntos). A tabena materia_assunto é um ligação N-N entre materia e assunto_materia.

Abri a issue #983 para implementarmos esta funcionalidade.
Abri a issue #984 para implementarmos a migração.

Em tempo, fiz umas consultas aqui e vi que 7 casas usam a funcionalidade (dentre as quase 900 que temos hospedadas)
