### ISSUE TITLE
Pesquisa por sessões plenária: mudar a ordem do campo Ano

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#768]
Mudar a ordem do campo Ano para decrescente pois, normalmente, se busca as sessões de anos mais recentes.

**Comment by edwardoliveira** [comment]
@andreagudo Favor testar mais tarde pra confirmar resolução. Obrigado.

**Comment by andreagudo** [comment]
Resolvido.

Em 31/10/2016 12:59, "Edward" <notifications@github.com> escreveu:

**Comment by andreagudo** [comment]
Resolvido.
