### ISSUE TITLE
Protocolo Geral

### ISSUE THREAD

**Issue by wesleylima247** [interlegis/sapl#771]
Permissões para operador_protocoloadm só recebe proposições, mas não protocola.

operador_geral nem superuser tem a permissão também

**Comment by LeandroRoberto** [comment]
As funções básicas e visualização de botões de acesso a protocolar matérias, documentos e anulação de protocolo foram restauradas porém há várias refatorações a serem feitas.  No mínimo fazer o código funcionar como está, porém seria mais prudente transportar as ações de clean e save pra dentro dos forms

**Comment by wesleylima247** [comment]
certo

**Comment by eduardoedson** [comment]
Resolvido?

**Comment by marciomazza** [comment]
@LeandroRoberto Vcs sabe se essa issue ainda é válida?

**Comment by LeandroRoberto** [comment]
Sim
