### ISSUE TITLE
"Protocolar Matéria" volta para tela de pesquisa de protocolos

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#775]
Ao "Protocolar Matéria" o sistema volta para a tela de pesquisa de protocolos, apesar do protocolo ter sido gerado. A matéria correspondente, porém, não é criada.

**Comment by edwardoliveira** [comment]
@andreagudo *Quase certeza* que deve existir um erro no fluxo de protocolo de doc adm também. Teria como verificar isso também? Obrigado.

**Comment by LeandroRoberto** [comment]
#771

**Comment by andreagudo** [comment]
Protocolo de doc adm está funcionando.

Em 01/11/2016 12:11, "Leandro Roberto da Silva" <notifications@github.com>
escreveu:

**Comment by edwardoliveira** [comment]
Obrigado, @andreagudo e @LeandroRoberto. Vamos priorizar essa issue. :+1:

**Comment by eduardoedson** [comment]
@andreagudo Verifique, por favor

**Comment by andreagudo** [comment]
Resolvido.
