### ISSUE TITLE
Formulário de protocolar incorreto

### ISSUE THREAD

**Issue by eduardoedson** [interlegis/sapl#779]
Deveria ser:
![1](https://cloud.githubusercontent.com/assets/7716450/19977511/f9f48392-a1da-11e6-8991-0d9988d383ca.png)
Como está:
![2](https://cloud.githubusercontent.com/assets/7716450/19977518/fd785b88-a1da-11e6-9f61-b24e35bda558.png)

**Comment by eduardoedson** [comment]
@edwardoliveira @LeandroRoberto Houve mudanças, ou está incorreto mesmo?

**Comment by eduardoedson** [comment]
E, em protocolar documento, tem a opção de envio, mas não poderia ter a opção de 'Ambos'.

**Comment by LeandroRoberto** [comment]
vi isso quando fiz esse commit https://github.com/interlegis/sapl/commit/8a1c5660027f8ce66d7989c99afdc914899408c7 
Essa questão do ambos me é estranha, porém esse enviado e recebido existe no 3.0, não sei se existe no 2.5 para protocolo de documentos... não existe para protocolo de matéria.

sobre a opção de numeração, foi transferida para as Tabelas auxiliares em "Configurações da Aplicação"... houve um início de dialogo sobre isso em #189

**Comment by eduardoedson** [comment]
Segui o template do 2.5 e removi essa opção do protocolar matéria
