### ISSUE TITLE
Composição de uma comissão nova

### ISSUE THREAD

**Issue by eduardoedson** [interlegis/sapl#79]
Ao criar uma nova comissão, o menu de composição retorna um erro.
'NoneType' object has no attribute 'id'

**Comment by eduardoedson** [comment]
http://localhost:8000/comissoes/create

**Comment by edwardoliveira** [comment]
Oi @eduardoedson, estou tentando simular este erro, mas não consegui. :disappointed: Quer dizer, consegui criar com sucesso agora há pouco. Acho que sei o que pode ser o problema, mas vemos isso juntos, ok?
