### ISSUE TITLE
Verificar se lógica da última tramitação foi implementada

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#80]
No SAPL 2.5, o Mazza identificou um campo ind_ult_tramitacao que deve ser setado para 1 na última tramitação e todas as anteriores devem ser setadas para zero. Acho que este campo passou batido nesta versão nova do SAPL porque geralmente não importamos os campos ind_* nas tabelas do novo esquema de banco. :grin: 

Temos que implementar isto conforme abaixo:

     Ao adicionar nova tramitação:
     1. atribuir o valor 1 (um) a ``ind_ult_tramitacao`` da nova tramitação;
     2. marcar todos os ``ind_ult_tramitacao`` das tramitacoes anteriores como 0 (zero).

**Comment by eduardoedson** [comment]
Pronto (y)

**Comment by marciomazza** [comment]
Na verdade podemos excluir esse campo do model, pois ele simplesmente marca a última tramitação, que pode ser obtida com uma query simples.
