### ISSUE TITLE
Exclusão Normas Jurídicas

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#807]
Ao tentar excluir uma norma jurídica, é apresentado o seguinte erro
Request Method: 	GET
Request URL: 	http://sapl31demo.interlegis.leg.br/norma/3623/delete
Raised by: 	sapl.crud.base.CrudDeleteView

**Comment by LeandroRoberto** [comment]
Problema no delete do Crud... vou pegar essa issue.

**Comment by LeandroRoberto** [comment]
@DTILegBG verifique, por favor!
