### ISSUE TITLE
Implementar pesquisa textual em PDF de Documento Acessório

### ISSUE THREAD

**Issue by eduardocalil** [interlegis/sapl#809]

**Comment by LeandroRoberto** [comment]
esta funcionalidade é mais abrangente e deve contemplar qualquer pdf/odt/doc do sistema

**Comment by edwardoliveira** [comment]
Criei o branch https://github.com/interlegis/sapl/tree/809-busca-textual para tentar implementar isso. Por enquanto ele _parece_ funcionar com os campos do Model de DocumentoAcessório, mas não para PDFs anexados. Aí vem o problema: dos backends suportados pelo Haystack somente o Solr suporta extração de dados em PDF. Isto é, não é possível fazer o mesmo, *por enquanto* com o Whoosh e o ElasticSearch.

**Comment by edwardoliveira** [comment]
Ah... **ótimo** (not)! Parece que o Solr >=5 não trabalha bem com o Haystack. :angry:

http://stackoverflow.com/questions/32774796/can-anyone-offer-a-full-example-of-django-haystack-with-solr-5-x

**Comment by eduardocalil** [comment]
#27

**Comment by LeandroRoberto** [comment]
Falta fazer para NormaJuridica e, quiçá, para o model Dispositivo da app compilação.

**Comment by eduardocalil** [comment]
#27

**Comment by eduardocalil** [comment]
Feito para Normas. Como ainda não foi decidido se será feito para o model Dispositivo da app compilação, fecharei essa issue. A pesquisa para Dispositivo poderá ser feita em outra issue.
