### ISSUE TITLE
Arquivo da proposição não fica salvo sem estar ativado o uso de textos articulados

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#812]
Proposição não fica salva sem estar ativada, nas Tabelas Auxiliares, o uso de textos articulados para proposições.

**Comment by LeandroRoberto** [comment]
o arquivo, certo?

**Comment by andreagudo** [comment]
Isso mesmo, o arquivo não fica salvo.

**Comment by LeandroRoberto** [comment]
Resolvido.
