### ISSUE TITLE
Proposição: não há como informar o texto

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#815]
Não há como informar qual o texto de uma proposição, pois as opções "Texto Digital" e "Texto Articulado" não estão disponíveis. O autor tem que salvá-la e editá-la para, somente aí, aparecer onde indicar o texto.

**Comment by andreagudo** [comment]
Resolvido.

**Comment by LeandroRoberto** [comment]
Resolvido.

**Comment by andreagudo** [comment]
Ok.
