### ISSUE TITLE
Matéria Legislativa: pesquisa pelo critério Autor não seleciona o autor

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#817]
A tela de seleção do autor não o seleciona para incluir na tela de pesquisa. Clica-se em Pesquisar, mas não sai dessa tela.
![captura de tela de 2016-11-23 16 27 42](https://cloud.githubusercontent.com/assets/19169882/20574228/9becd72a-b19a-11e6-8bdb-26346a28c6f6.png)

**Comment by LeandroRoberto** [comment]
acabei de testar em sapl31agudo, funcionou no chrome... não funcionou no firefox... verifiquei erro de javascript e ocorre algo externo ao javascript do sapl

**Comment by andreagudo** [comment]
No Chromiun tb não funciona.

**Comment by edwardoliveira** [comment]
Que estranho, aqui no meu Firefox funciona. Poderiam me passar o erro JavaScript pra que eu possa verificar o que está acontecendo?

**Comment by edwardoliveira** [comment]
Alterei as permissões para ``AutorListView``. Acho que isso deve consertar pelo menos o outro erro que vi aqui (testei e funcionou comigo). Por favor, veja se ainda apresentam erro. Se possível, com a mensagem em JavaScript do erro (pode ser um screenshot também).

**Comment by andreagudo** [comment]
Resolvido no Firefox e no Chromium.
