### ISSUE TITLE
Manutenção de conta de usuário

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#818]
Não há onde fazer manutenção da conta de usuário.

**Comment by edwardoliveira** [comment]
Oi, por padrão, a plataforma Django tem uma tela de admin (http://localhost:8000/admin/) que seria a responsável por gerenciar estes usuários (criação, exclusão, atualização, etc). Pelo menos é assim que as aplicações feitas em Django trabalham ( @LeandroRoberto e @marciomazza, me corrijam se falei besteira).

**Comment by LeandroRoberto** [comment]
como no sapl, criação de usuário não será auto-create, o manutenção por conta do admin pode até ficar na interface de administração, porém, a tela de login deve ser refatorada com, no mínimo,

  "Esqueci minha senha" e
  "Alterar minha senha".

**Comment by LeandroRoberto** [comment]
diferentemente do sapl2.5 que "alterar senha" fica em um menu pós-longin, no 3.1 poderia fica na tela de login...

outro fato, sobre username, o que está sendo usado no Colab, (foi uma solução django?), e o que está sendo usado SAAP, não serve?... é hora de transformarmos isso para email, depois não diga que eu não avisei... hehehe...

**Comment by LeandroRoberto** [comment]
![image](https://cloud.githubusercontent.com/assets/9630623/20967315/f5c9068a-bc65-11e6-89ae-f514861f1f13.png)

**Comment by eribeiro** [comment]
Concordo Leandro. Podemos fazer como o Colab que, sim, usa Django. O recuperar senha podemos usar o mecanismo que já vem "de fábrica" no Django. Para o create fizemos uma tela básica que podemos reutilizar também.

**Comment by marciomazza** [comment]
Eu acho que essa issue consiste, basicamente, em implementar a sugestão de @LeandroRoberto de adicionar à tela de login:

- "Esqueci minha senha" e
- "Alterar minha senha".

Acho que esse "alterar minha senha" pode ir depois para uma tela de perfil do usuário.

**Comment by LeandroRoberto** [comment]
@marciomazza,  isso:
"Esqueci minha senha" e
"Alterar minha senha"

Já foi feito...  Essa issue pode ser fechada!
