### ISSUE TITLE
Matéria Legislativa: colocar o texto original na primeira tela do resultado da pesquisa

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#819]
O texto original aparece na tela de detalhes. Penso que também poderia estar na tela abaixo.
![captura de tela de 2016-11-24 08 37 20](https://cloud.githubusercontent.com/assets/19169882/20595529/5e514234-b221-11e6-9be4-7c8d5e98d056.png)

**Comment by andreagudo** [comment]
Resolvido para texto arquivos. Não deveria ser assim também para os textos articulados?

**Comment by LeandroRoberto** [comment]
@andreagudo verifique, por favor... a listagem está sem um layout apropriado, mas a questão foi solucionada!
