### ISSUE TITLE
Refatorar todos os forms que possuem upload de arquivos

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#820]
- pautar-se também por #751 
- **em caso de troca de arquivos, nos saves dos forms ou outra estratégia (exemplos: manutenções feitas diratamente no post), os arquivos antigos devem ser removidos.**
- o caso acima pode é desnecessário se for retirado a aceitação e normalização de nomes de arquivos feitas pela função texto_upload_path (observar comentários dessa função) e registrando sempre o mesmo nome de arquivo, ignorando o nome do arquivo que acompanha o upload do usuário.
- ao remover um registro que possui FileField, com a reimplementação de save e delete feita, atualmente, nos models, os arquivos estão sendo removidos, porém, as pastas permanecem... remoção de pastas com  nome igual a pk e, em casos como sessão plenária, onde possuem subpastas pauta e ata, não deveriam permanecer no filesystem sem arquivos.

**Comment by eduardoedson** [comment]
Todos os FileField que encontrei usando grep, já estão com delete e save alterados no model. Teria algum faltando que você lembre? @LeandroRoberto

**Comment by LeandroRoberto** [comment]
opa... não me lembro... seria isso mesmo que vc fez no que tange a localização e aplicação do metodo delete e save... porém, como estão as funções... nenhuma deve usar a propria instance pra criar path... isso induz ao uso do __str__ as funções devem ser observadas refatorá-las no sentido de usar ou texto_upload_path ou outra bem semelhante

**Comment by eduardoedson** [comment]
No caso, seria mudar somente os arquivos de documento administrativo para direcionar para a pasta private. Acho que resolveria o problema do @edwardoliveira

**Comment by eduardoedson** [comment]
Então, nesse caso, a issue pode ser fechada? @LeandroRoberto

**Comment by LeandroRoberto** [comment]
proposição também são privadas... e hora acesso será apenas para o autor dono, se ainda não não incorporada... hora de acesso anônimo se incorporada!

**Comment by edwardoliveira** [comment]
Sim. Tô ligado. @LeandroRoberto
