### ISSUE TITLE
Envio de proposição sem arquivo: implementar mensagem de erro

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#825]
Implementar mensagem de erro quando do envio de proposição sem arquivo.

**Comment by LeandroRoberto** [comment]
lembrete: o módulo de proposições não permite enviar mas também não avisa porque não permitiu...

**Comment by LeandroRoberto** [comment]
@edwardoliveira `from django.contrib import messages` não está funcionando nas maquinas de homologação... 
constatação de ser problemas nas maquinas de homologação:
- localmente com execução de desenvolvimento está normal... 
- em meu servidor de produção para o SAAP (configuração trivial de produção que conhecemos) as messages também funcionam como esperado... 

um exemplo básico, é estar logado com usuário admin e tentar acessar '/proposicao'. Como admin não é autor... devia mostrar mensagem... "O Usuário (admin) não está registrado como (Autor)."

**Comment by andreagudo** [comment]
Resolvido.
