### ISSUE TITLE
Migração - Resultado de Votação

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#829]
Os resultados de votação de matérias estão todos como "Não há resultado"

Na tabela do 2.5 ordem_dia existe a coluna txt_resultado e essa coluna está toda null
no 3.1 na tabela sessao_ordemdia existe a coluna resultado.

Pelo que entendi, no 3.1 o resultado da votação é exibido levando em conta o que está nessa coluna "resultado" e como é importada vazia não mostra nada.

Acho que teria que preencher essa coluna baseado na tabela sessao_registrovotacao. Onde os nomes dos tipos estão na tabela sessao_tiporesultadovotacao

**Comment by edwardoliveira** [comment]
Um dúvida: essa issue tem a ver com a migração de dados do SAPL 2.5 para o 3.1, certo?

**Comment by DTILegBG** [comment]
Certo, as que tem a ver com a migração estou abrindo com o título de 
"Migração - assunto " para facilitar como foi o caso da issue 830


Em 13/12/2016 18:00, Edward escreveu:

**Comment by DTILegBG** [comment]
Resolvido, agora falta colocar as observações junto ao resultado, como é feito no 2.5
![image](https://cloud.githubusercontent.com/assets/13314947/25089116/a5bd0454-2351-11e7-9a70-67573c77926a.png)
