### ISSUE TITLE
Migração - Usuários

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#830]
Nas telas de pesquisa de usuários a lista fica em branco para muitos.
Na tabela do 3.1 base_autor o no campo "nome" está para muitos registros como ' '
No meu caso, neste campo não foram importados os nomes dos autores do tipo parlamentar e comissão. 
Deixando o registro em branco e não retornando o nome nas pesquisas.

**Comment by edwardoliveira** [comment]
Sim, o nome de comissão e parlamentar ficam em outras tabelas. Vamos fazer um join @LucianoAlmeida.

**Comment by LeandroRoberto** [comment]
o  campo nome em base_autor só não está sendo preenchido via migração, certo? via cadastro está normal?

**Comment by edwardoliveira** [comment]
Boa pergunta @LeandroRoberto, também gostaria de saber...

**Comment by DTILegBG** [comment]
Isso, exatamente


Em 13/12/2016 17:27, Edward escreveu:

**Comment by LucianoAlmeida** [comment]
Aparentemente o campo nome não era preenchido no 2.5 quando o autor era um parlamentar.
Em todos os bancos que tenho disponíveis aqui pra teste, o campo nome de autor está nulo para parlamentares. Provavelmente, para exibir essa lista de nomes, pegava-se o numero em autor.cod_parlamentar e exibia provavelmente o valor de parlamentar.nom_parlamentar.
Neste caso, devo preencher o que era nulo com esse valor de nome do parlamentar?

**Comment by LucianoAlmeida** [comment]
Feito.
