### ISSUE TITLE
Migração - Comissões

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#831]
As comissões estão sendo importadas todas como inativas
Na tabela do 3.1 comissoes_comissao campo ativa=false

**Comment by edwardoliveira** [comment]
Oi @LucianoAlmeida, teria como dar uma olhada nisso? Obrigado! :)

**Comment by LucianoAlmeida** [comment]
Qual o indicativo de que ela está deve ativa ou desativa?

**Comment by DTILegBG** [comment]
No Sapl 2.5 é a data na tabela comissao, coluna dat_extincao


Em 09/01/2017 18:40, Luciano Henrique Nunes de Almeida escreveu:
> Qual o indicativo de que ela está deve ativa ou desativa?

**Comment by LucianoAlmeida** [comment]
Feito.
