### ISSUE TITLE
Migração - Vínculo Normas Jurídicas (Normas Relacionadas)

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#832]
Os relacionamentos não estão sendo importados corretamente.
3.1 - tabela norma_vinculonormajuridica
1;"''";"''"
2;"''";"''"
3;"''";"''"
4;"''";"''"
5;"''";"''"
.......segue até id 5139
3.1 - tabela norma_normarelacionada
tabela vazia

2.5 - tabela vinulo_norma_juridica
'1', '452', '148', 'P', ''
'2', '3457', '1075', 'R', ''
.......segue até id 5139

**Comment by LeandroRoberto** [comment]
houve mudança no modelo, @LucianoAlmeida está ciente?

**Comment by cristian-longhi** [comment]
Existe um modelo disponível para consulta? Se sim, qual o endereço?
Em relação ao vínculo, na consulta a uma Norma Jurídica, a referência à Matéria Legislativa respectiva não está com o link, somente com o texto "Projeto de Lei nº XXX de XXXX". Deve ter o link ou não?

**Comment by LeandroRoberto** [comment]
Olá @cristian-longhi bem vindo por aqui,

o modelo que citei acima é com relação a modelagem de dados na programação...

mas existe um sapl em sapl31demo.interlegis.leg.br que é atualizado de hora em hora automaticamente...

sobre os vínculos estes que o @DTILegBG citou é sobre as normas relacionadas... não envolve matéria legislativa...

sobre o link... acredito que deva ter link sim, se não tem, precisa ser colocado... abra uma issue relatando essa questão... 

entre no telegram, se vc ainda não tiver... https://web.telegram.org/#/login....
e me passe seu usuário pra te colocar no grupo de discussão de testes e desenvolvimento...

**Comment by cristian-longhi** [comment]
Olá, @LeandroRoberto!
Criei o usuário no Telegram: @cristian_longhi
Estava mesmo querendo entrar nesse grupo. Obrigado!
Vou abrir essa issue nova

**Comment by LeandroRoberto** [comment]
Te adicionei lá...

**Comment by LucianoAlmeida** [comment]
@LeandroRoberto, a mudança ocorrida na model foi qual?
O que entendi foi que o que antigamente era VinculoNormaJuridica agora é o tipo do vínculo e o NormaRelacionada que deve ser migrado pra antiga tabela vinculo_norma_juridica. Estou certo?

Mais perguntas: na tabela vinculo_norma_juridica, no SAPL 2.5, havia o campo de tip_vinculo, mas ele é do tipo char. Havia antigamente alguma tabela que guardava o tipo e sua descrição ou não existe isso? Esse tipo e essa descrição são invariáveis?

**Comment by marciomazza** [comment]
@edwardoliveira Vc tb está por dentro dessas mudanças?
@LeandroRoberto Poderia explicar aqui?

**Comment by LeandroRoberto** [comment]
Apesar do debate aqui... 
a solução foi efetuada em https://github.com/interlegis/sapl/commit/30f9ca5ec95ddd50410938ede7b0319b0105ae58
pelo @eduardoedson e @edwardoliveira atraves da issue #409 
eles estão a par e facilmente poderão debater ao vivo, aí, com a equipe de migração...

**Comment by marciomazza** [comment]
É importante conferir se o código de migração popula o `TipoVinculoNormaJuridica` com valores iniciais correspondentes ao código antigo do sapl 2.5 como mencionado em https://github.com/interlegis/sapl/issues/409#issuecomment-220385707

**Comment by LeandroRoberto** [comment]
sem me ater ao algoritmo, presumo que a função `fill_vinculo_norma_juridica` em https://github.com/interlegis/sapl/blob/master/sapl/legacy/migration.py
não esteja adequada ao model TipoVinculoNormaJuridica
