### ISSUE TITLE
Matérias Legislativas - Busca por número de processo / Identificação Básica

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#833]
O número de processo é o que consta no cadastro como "Numeração".
Não está disponível o campo para consulta e nem é exibido na identificação básica da matéria

**Comment by eduardoedson** [comment]
Essa numeração que tá falando?

![a](https://cloud.githubusercontent.com/assets/7716450/20709982/54188794-b61f-11e6-82ee-fa494c0085f5.png)

**Comment by DTILegBG** [comment]
Isso ai.

No 2.5 ela é tratada como Processo:


Em 29/11/2016 10:34, Eduardo Edson Batista Cordeiro Alves escreveu:

**Comment by eduardoedson** [comment]
Mas então tem um erro de modelagem no caso?
@edwardoliveira @LeandroRoberto

**Comment by LeandroRoberto** [comment]
muito sem sentido mas, de fato, ocorre com @DTILegBG afirmou...

![image](https://cloud.githubusercontent.com/assets/9630623/20750181/a6cfa842-b6dc-11e6-82e3-e1b2ca7c99cb.png)

![image](https://cloud.githubusercontent.com/assets/9630623/20750247/0006fffa-b6dd-11e6-8723-f51e127e7090.png)

**Comment by eduardoedson** [comment]
Então fiquei sem entender o que é pra fazer kk

**Comment by LeandroRoberto** [comment]
segundo sapl 2.5
o que vc cadastrar lá... na aba numeração

deve aparecer aqui em detalhes:
![image](https://cloud.githubusercontent.com/assets/9630623/20750478/44a2bcac-b6de-11e6-94f9-0806f12c01b2.png)

o model "Numeracao" está para isso... aceitará qualquer coisa em numero_materia... view e form não deve exigir que exista na base uma matéria com o conjunto de características... (tipo_materia, numero_materia, ano_materia) isso é qualquer coisa...

**Comment by DTILegBG** [comment]
O campo Numerações aparece com um ponto fora do padrão dos outros campos. Na tela de pesquisa não tem um campo para pesquisar por essa numeração. Acho interessante o nome destes campos ser de Processo, seguindo o que é no 2.5
