### ISSUE TITLE
Matérias Legislativas - Despacho Inicial

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#834]
Seria interessante exibir para seleção de despacho inicial somente as comissões ativas.

**Comment by andreagudo** [comment]
Ocorre que o despacho inicial pode ocorrer para outros órgãos, com o a Procuradoria. Depende do Regimento Interno. Nem sempre é para comissão, especialmente em Câmaras pequenas.

**Comment by DTILegBG** [comment]
Entendo, mas de qualquer forma  no caso das comissões só deveriam ser 
passiveis de despacho as ativas


Em 29/11/2016 13:56, André Brum da Silva escreveu:

**Comment by andreagudo** [comment]
Isso mesmo.

**Comment by eduardocalil** [comment]
@DTILegBG Confere lá se está do jeito que gostaria. Se sim, feche esta issue, por favor.
