### ISSUE TITLE
Matéria Legislativa - Excluir

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#836]
Erro ao excluir Matéria.
Request Method: 	GET
Request URL: 	http://sapl3.camarabento.rs.gov.br:8001/materia/12586/delete
Raised by: 	sapl.crud.base.CrudDeleteView

**Comment by LeandroRoberto** [comment]
Resolvido também neste a questão do campo assuntos em pesquisa de normas, para seleção unitária.
