### ISSUE TITLE
Protocolo - Anular Protocolo

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#841]
Depois de anulado um protocolo não fica qualquer informação que ele foi anulado. Também é possível ainda criar documento a partir de um protocolo já anulado.

**Comment by edwardoliveira** [comment]
O único lugar que fica é no recibo, pelo que me lembro. Mas devemos colocar na listagem/detalhe também. Além de não permitir criar documento a partir dele. Seria isso?

**Comment by DTILegBG** [comment]
Exato, penso isso.


Em 06/12/2016 15:23, Edward escreveu:
