### ISSUE TITLE
Protocolo - Protocolar Matéria

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#844]
Os campos tipo, Número de Páginas e Observação não estão como obrigatórios, porem se não preenchidos é retornado erro.

**Comment by wesleylima247** [comment]
Eles estão dando erro, mesmo eu preenchendo.

**Comment by wesleylima247** [comment]
TypeError at /protocoloadm/protocolar-mat

unsupported operand type(s) for +: 'NoneType' and 'int'

359.     protocolo.numero = numero['numero__max'] + 1

**Comment by wesleylima247** [comment]
@eduardoedson depois do seu commit ainda está dando erro.




name 'numero__max' is not defined

 356           protocolo.numero = (numero['numero__max'] + 1) if numero__max else 1

     ...

**Comment by edwardoliveira** [comment]
@wesleylima247 Teste agora, por favor.

**Comment by DTILegBG** [comment]
Ok, agora parece estar resolvida a questão, porem deixemos aberta a issue porque falta a questão da obrigatoriedade dos campos.

**Comment by wesleylima247** [comment]
Deu certo.
