### ISSUE TITLE
Mesa Diretora - Escolha da Composição

### ISSUE THREAD

**Issue by DtiLegBG** [interlegis/sapl#846]
Seria interessante que só os parlamentares ativos fossem passíveis de ser incluídos na composição da mesa. Estão disponíveis para inclusão todos os parlamentares da legislatura, inclusive os que não estão ativos.

**Comment by LeandroRoberto** [comment]
Temos outro problema com mesa diretora... (sugir na noitada do EnGITEC... ;)

Se a mesa mudar no meio de uma sessão legislativa? o SAPL não mantei o histórico desse registro.

**Comment by DTILegBG** [comment]
Pois é, isso sim seria muito importante resolver. Aqui acontece e não é 
tão raro assim.

Talvez teria que tratar como são tratadas as comissões onde são criados 
períodos de composição


Em 30/11/2016 15:04, Leandro Roberto da Silva escreveu:

**Comment by edwardoliveira** [comment]
@marciomazza O SAPL 2.5 tem um campo `cod_periodo_comp` que referencia a tabela   `periodo_comp_mesa`. Ambos não foram migrados para 3.1. Podemos começar por aí, certo? Uma rápida olhada com o @LucianoAlmeida revelou que as bases de dados que dispomos aqui não tem nem essa tabela nem esse campo **embora esteja presente no arquivo sapl.sql** no subversion. Assim, por algum motivo, ela ficou de fora da migração de dados.

**Comment by marciomazza** [comment]
Voltando ao tema da issue: Na verdade é possível cadastrar mesas de legislaturas antigas, onde é necessário poder usar parlamentares não ativos.

**Comment by DtiLegBG** [comment]
hoje no sapl 2.5 é feito da seguinte forma, para matéria, mesa e demais, o parlamentar é editado e ativado, cadastrado para matéria, mesa... e depois editado o parlamentar novamente e desativado

**Comment by edwardoliveira** [comment]
@DtiLegBG O problema dessa issue ainda persiste?

**Comment by edwardoliveira** [comment]
https://github.com/interlegis/sapl/issues/525

**Comment by cesaraugc** [comment]
Caso o erro ainda persista, favor reabrir a issue.
