### ISSUE TITLE
Norma jurídica - vínculo com a matéria

### ISSUE THREAD

**Issue by cristian-longhi** [interlegis/sapl#847]
Na tela de consulta à Norma Jurídica, o campo materia apresenta o nome da Matéria Legislativa (ex: Projeto de Lei n° xxx de 2016), porém não faz o link para a mesma. Penso que deveria ter o link, por praticidade, e para espelhar o comportamento do SAPL 2.5.
Ainda, trocar o rótulo do campo para 'Matéria', padronizando com os demais campos da tela, com a primeira letra maiúscula.

**Comment by eduardocalil** [comment]
Confere lá se está do jeito que gostaria. Se sim, feche a issue, por favor.

**Comment by cristian-longhi** [comment]
Ok, Eduardo, é isso!
