### ISSUE TITLE
Protocolar matéria - Ementa/Observação.

### ISSUE THREAD

**Issue by wesleylima247** [interlegis/sapl#851]
Ao protocolar materia, vi que está faltando o campo Ementa na tela inicial assim como no sapl 2.5
quando clico em protocolar materia, no campo EMENTA ele pega automatico o que está em observação.

**Comment by edwardoliveira** [comment]
Desculpe, estamos **sem acesso** ao SAPL 2.5 de testes aqui. Por isso vou ter que esclarecer contigo: no SAPL 2.5 **existe** o campo EMENTA?

**Comment by LeandroRoberto** [comment]
veja no modelo protocoloadm.models.Protocolo que existe o campo assunto_ementa.

Em protocoloadm.forms.ProtocoloDocumentForm esse campo é tratado como 'assunto' e, depois, no post em form_valid da view ProtocoloDocumentoView, é readequado...

Já em protocoloadm.forms.ProtocoloMateriaForm, o campo assunto_ementa foi ignorado...

**Comment by LeandroRoberto** [comment]
@edwardoliveira 
![image](https://cloud.githubusercontent.com/assets/9630623/21179892/5530b358-c1dd-11e6-8179-7a7664ce3e54.png)

sugiro que resolva isso para que possamos consultar quando necessário...
ademais, por si só.. http://sapldemo.interlegis.leg.br/ está desativado, apesar de o portal do interlegis, na área produtos, estar direcionando para esse endereço.

**Comment by eduardoedson** [comment]
@wesleylima247 Veja se está de acordo.

**Comment by edwardoliveira** [comment]
Vou falar com o povo da infra aqui pra subir o http://sapldemo.interlegis.leg.br/ também.
