### ISSUE TITLE
Protocolar Materia - Está como documento administrativo

### ISSUE THREAD

**Issue by wesleylima247** [interlegis/sapl#852]
![photo304227149805627461](https://cloud.githubusercontent.com/assets/19570385/20800168/5919e1ca-b7c3-11e6-9508-56e5de3031e9.jpg)
![photo304227149805627462](https://cloud.githubusercontent.com/assets/19570385/20800169/5a3649b8-b7c3-11e6-9c3c-73ff01b34a1a.jpg)
![photo304227149805627463](https://cloud.githubusercontent.com/assets/19570385/20800171/5b1b130e-b7c3-11e6-8ffc-1e8077d03537.jpg)

**Comment by edwardoliveira** [comment]
Poderia descrever com mais detalhes o bug e as inconsistências? Tipo, isso ocorre no protocolo de matéria legislativa, certo? Mas funciona com documento administrativo? Obrigado!

**Comment by wesleylima247** [comment]
@LeandroRoberto
