### ISSUE TITLE
Matéria Legislativas - Autoria

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#855]
No cadastro de autoria para matérias legislativas deveriam ficar disponível para seleção só os possíveis autores que estão ativos no sistema. Estão ficando todos, inclusive os parlamentares inativos.
Seria interessante ter uma forma de incluir várias autorias, como é feito no 2.5.

**Comment by edwardoliveira** [comment]
Fechando pois duplicata de #860
