### ISSUE TITLE
Matéria Legislativa - Incluir várias autorias

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#860]
É comum uma matéria ter a subscrição de vários parlamentares, então se manter a opção existente no 2.5 de incluir várias autorias é bem importante.
![image](https://cloud.githubusercontent.com/assets/13314947/20974537/bd4b10d2-bc83-11e6-9f76-4c1cebc69900.png)

**Comment by edwardoliveira** [comment]
Pelo que eu me lembro esta tela de adição de autor no SAPL 3.1 tem (ou tinha) a possibilidade de adicionar mais de um autor, inclusive informando qual o primeiro autor. Vc tentou adicionar mais de um autor no SAPL 3.1?

**Comment by DTILegBG** [comment]
Sim, a inclusão de vários autores funciona, mas no 2.5 existia outro 
botão de incluir várias autorias para a matéria, deixando o operador 
marcar vários autores de uma única vez.


Em 13/12/2016 17:57, Edward escreveu:

**Comment by LeandroRoberto** [comment]
![image](https://cloud.githubusercontent.com/assets/9630623/21179583/cf16cbaa-c1db-11e6-97bb-cc5f47b88af8.png)
é isso que o 2.5 faz no botão Incluir várias autorias... no 3.1 isso pode ser resumido para apenas um formulário... semelhante ao de presença de em Sessão Plenária, porém, levando em conta a primeira autoria que, inclusive, penso eu, deve ser também, um checkbox e não um radio button

**Comment by edwardoliveira** [comment]
_"No cadastro de autoria para matérias legislativas deveriam ficar disponível para seleção só os possíveis autores que estão ativos no sistema."_

**Comment by LeandroRoberto** [comment]
o que é um autor ativo no sistema?
