### ISSUE TITLE
Mesa Diretora - Sessão Legislativa

### ISSUE THREAD

**Issue by cristian-longhi** [interlegis/sapl#869]
Boa tarde! Na exibição da Mesa Diretora, após escolher a Sessão Legislativa, o campo retorna sempre para mais atual da legislatura. A composição é atualizada conforme a escolha, porém não aparece qual foi a Sessão Legislativa escolhida. Além disso, por já conter essa informação no campo, não é possível selecionar a composição da Sessão Legislativa que é mostrada, apenas acessando novamente o link Mesa Diretora.

**Comment by edwardoliveira** [comment]
O campo retorna para a última *sessão legislativa** escolhida, não? Ele mantém a legislatura escolhida.

**Comment by cristian-longhi** [comment]
Correto, mantém a legislatura, mas retorna sempre para a sessão legislativa mais recente. Ex:
legislatura - 15ª (2009 - 2012);
sessão legislativa - seleciono 2ª (2010 - 2010);
a composição da mesa atualiza pela 2ª, mas o valor do campo volta para 4ª (2012 - 2012).

**Comment by LeandroRoberto** [comment]
Corrigido!
