### ISSUE TITLE
Sessão Plenária - anexos

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#882]
Falta a possibilidade de anexos à sessão conforme sapl 2.5
![image](https://cloud.githubusercontent.com/assets/13314947/21485505/a2501d4c-cb8b-11e6-946a-e1c2bc50a114.png)

**Comment by edwardoliveira** [comment]
Pelo teste rápido que fiz aqui, o SAPL 2.5 só permite adicionar um anexo. É isso mesmo?

**Comment by DTILegBG** [comment]
sim, no sapl 2.5 é isso mesmo.

até tem um pull esperando sobre isso, pode-se dar uma olhada se dá para 
aproveitar


Em 10/01/2017 15:20, Edward escreveu:

**Comment by edwardoliveira** [comment]
Fiz o merge deste PR. Teria como testar pra ver se está ok?

**Comment by edwardoliveira** [comment]
Estou reabrindo pq não entendi uma coisa: ficou faltando adicionar o menu 'Anexo' com a respetiva tela de formulário, não? @DTILegBG

**Comment by DTILegBG** [comment]
Resolvido!
