### ISSUE TITLE
Perfil de vereador com acesso somente a matérias específicas.

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#891]
**Sugestão via lista GITEC, título do email: TI TI**

_"Bom dia a todos, queria saber se tem como cadastrar vários usuários (vereadores) para eles colocarem apenas algumas matérias legislativas tipo, indicações, requerimentos, mocões etc. (quando logarem só terem acesso a estas matérias).
Não quero que eles tenham acesso para cadastrar Projetos de Leis dentre outras."_

**Comment by LeandroRoberto** [comment]
Não acho prudente... o caminho para isso já existe e controle de deferimento/indeferimento já está implementado via Proposições

**Comment by edwardoliveira** [comment]
Entendo. Vou fechar essa issue como `won't fix`, ok?
