### ISSUE TITLE
Mover choices dos forms para os models

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#90]
Ao invés de definir o campo como Choices nas views.py, é preferível definir no models.py, economizando declarações e simplificando os ModelForms.

**Comment by edwardoliveira** [comment]
Oi @marciomazza (/cc @eduardoedson) , eu concordo que o choices devam ser migrado para o models.py e este ticket é para acompanhar isso, mas tem as situações como as listadas abaixo, onde estes snippets especificam a forma de renderizar o campo (no caso, como um Textarea). Não creio que isto seja migrado para o models.py, o que vc acha? Mas pode ter uma forma melhor de fazer do que a que a gente faz atualmente, é claro.

```
    informacao_geral = forms.CharField(widget=forms.Textarea, 
                                       label='informacao_geral', 
                                       required=True)
```

**Comment by marciomazza** [comment]
Existe um campo TextField, para isso:
https://docs.djangoproject.com/es/1.9/ref/models/fields/#textfield

**Comment by edwardoliveira** [comment]
Uh?! Não entendi.

**Comment by marciomazza** [comment]
@edwardoliveira Estava respondendo ao comentário anterior, onde citaste o snippet:
```
    informacao_geral = forms.CharField(widget=forms.Textarea, 
                                       label='informacao_geral', 
                                       required=True)
```
Estou imaginando que este seja um campo de um `ModelForm`, que foi definido para trocar o widget.
Neste caso, ao invés de usar `widget=forms.Textarea` no form seria mais interessante que o campo do model fosse um `TextField`. O widget padrão de um TextField é um `forms.Textarea`.

Além disso existe outra forma de trocar o widget de um campo em um `ModelForm`, mexendo apenas no `Meta`: https://docs.djangoproject.com/en/1.9/topics/forms/modelforms/#overriding-the-default-fields

**Essa issue está falando só de migrar os *choices*. Talvez seja o caso de expandirmos mesmo a refatoração para toda metainformação que puder ser movida das views/forms para os models**.

**Comment by edwardoliveira** [comment]
ah, sim. Concordo! :+1:

**Comment by eduardocalil** [comment]
@marciomazza @edwardoliveira Está pronto, podem revisar assim que puderem. Depois de revisado, poderei implementar a validação de foto e texto integral nos models.
