### ISSUE TITLE
Fotos Parlamentares

### ISSUE THREAD

**Issue by rafagregs** [interlegis/sapl#901]
Testando a versao 3.1 notei que nem na Mesa Diretora, nem na lista de parlamentares temos as fotos dos nobres vereadores como na versão 2.5.
Essa parte cosmética será disponibilizada?

**Comment by eribeiro** [comment]
Sim. A versão atual de cadastro/edição de parlamentares já permite a inclusão de foto do parlamentar. Então precisamos recuperar estas fotos nas telas citadas.

**Comment by edwardoliveira** [comment]
Sim. A versão atual de cadastro/edição de parlamentares já permite a inclusão de foto do parlamentar. Então precisamos recuperar estas fotos nas telas citadas.

**Comment by eduardoedson** [comment]
Se não me engano, as fotos aparecem na tela de detalhe do parlamentar com usuário anonimo

**Comment by edwardoliveira** [comment]
Sim, o @eduardoedson tem razão. Além disso, quando se cadastra a foto do parlamentar, ela já aparece na listagem de parlamentares.

**Comment by rafagregs** [comment]
Testando rapidamente aqui verifiquei isso, na Mesa Diretora que ainda não.

**Comment by edwardoliveira** [comment]
A mesa diretora vai ser modificada, mas provavelmente não na primeira versão. Durante essa modificação podemos ver a possibilidade de incluir as fotos. Mas isso irá exigir uma mudança no layout da tela.

**Comment by rafagregs** [comment]
Foi realmente o que reparei, o layout da tela anônima é o mesmo da tela de operador.

**Comment by edwardoliveira** [comment]
Um... Podemos fazer uma tela anônima com a foto.

Sugestão: feche essa issue e abra uma para que a tela anônima apenas liste os parlamentares com suas respectivas fotos, por favor. Conforme é feito no SAPL 2.5.
