### ISSUE TITLE
Alterações em Proposições

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#911]
Receber as proposições sem precisar colocar o código do documento. Quando clicar em **proposições não recebidas** ter como autorizar o recebimento. 

Disponibilizar modelos de proposições para ajudar na elaboração dos documentos, com o timbre do Poder Legislativo.

**Comment by paulot12** [comment]
Na hora de VOTAR - ter a opção de confirmar o voto e colocar botões de fácil visualização para a votação.

**Comment by edwardoliveira** [comment]
@paulot12 No título da issue vc coloca a descrição breve do bug ou do feature que vc quer. Assim: _"Receber Proposições sem precisar de número de documento"_ :wink:

**Comment by VictorFabreF** [comment]
Já é possível receber proposições sem precisar colocar o código.
