### ISSUE TITLE
Listar relacionamentos ativos e passivos entre normas nos resultados de pesquisa também

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#913]
Os relacionamentos entre normas jurídicas estão nod detalhes, em Normas Relacionadas, Deveriam estar também na primeira tela do resultado da pesquisa por normas, seguindo o padrão do SAPL 2.5.

**Comment by edwardoliveira** [comment]
@andreagudo Favor verificar se agora está OK. Caso contrário, favor reabrir a issue! :+1:

**Comment by andreagudo** [comment]
1) penso que está ok, mas ainda faltam os dados, o que uma nova migração deve resolver; 2) que tal incluir a mensagem "Norma sem alterações posteriores" quando for o caso, como no 2.5?

**Comment by edwardoliveira** [comment]
OK. Adicionaremos a mensagem.

**Comment by edwardoliveira** [comment]
@andreagudo Adicionada a mensagem para quando não houverem normas relacionadas. :+1:
