### ISSUE TITLE
Para que não seja permitido votar as matérias constantes no expediente

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#914]
Sugiro que  não seja permitido votar as matérias constantes no expediente, só para a leitura. A votação se dá na ordem do dia.

**Comment by andreagudo** [comment]
Em Agudo só há votação na Ordem do Dia. Mas a realidade das Câmaras por aí afora é complexa.

**Comment by DtiLegBG** [comment]
Em Bento Gonçalves / RS são votadas matérias que estão no expediente

**Comment by edwardoliveira** [comment]
Como o @andreagudo e o @DtiLegBG bem responderam, não é possível desabilitar a votação em expediente porque a realidade das casas legislativas varia muito. Em mais de uma são votadas matérias tanto em expediente quanto em matéria, enquanto em outras somente em ordem do dia.
