### ISSUE TITLE
Inclusão indevida de mandato já existente

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#920]
Está sendo possível incluir um mandato já existente, engano que deve ser evitado.
![captura de tela de 2017-03-08 16 52 25](https://cloud.githubusercontent.com/assets/19169882/23721198/c482cd5c-041f-11e7-9d9c-08613187b3f5.png)

**Comment by edwardoliveira** [comment]
@eduardoedson Poderia dar uma olhada nessa issue? :sweat_smile: Quero ver contigo pra aprender! Kkkkkkk

**Comment by eduardoedson** [comment]
@andreagudo Verifique, por favor

**Comment by andreagudo** [comment]
Resolvido.
