### ISSUE TITLE
Documento administrativo vinculado a documento protocolado deve mencionar número e ano

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#922]
Estão sendo mencionados apenas Tipo e Assunto.

**Comment by edwardoliveira** [comment]
Qual a tela?

**Comment by andreagudo** [comment]
No caso de Agudo, http://sapl31agudo.interlegis.leg.br/protocoloadm/136/protocolo-mostrar

**Comment by edwardoliveira** [comment]
Por favor, veja se está OK. Senão, pode reabrir.

**Comment by andreagudo** [comment]
Funcionou. Sugiro que a ordem mude: tipo, número/ano. Assunto pode sair, pois o link levará ao doc adm.

**Comment by edwardoliveira** [comment]
OK. :+1:
