### ISSUE TITLE
Usuário votante não consegue acessar para alterar senha

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#923]
Pede login ao clicar em Usuário, mas não avança.

**Comment by edwardoliveira** [comment]
@andreagudo Estamos cogitando a possibilidade de deixar toda a parte de criação de Usuário com a tela admin do sistema. Assim, as telas que antes criavam usuários (votante, autor) ficariam só com a vinculação destes perfis de autor e votante a usuários já existentes. O que acha @LeandroRoberto ? @eduardoedson

**Comment by LeandroRoberto** [comment]
é uma solução... simplifica muita coisa... em autor não há muito o que fazer... há o que desativar/excluir código

**Comment by marciomazza** [comment]
Acho que todos concordamos com a ideia de @edwardoliveira.
Além disso @eduardocalil relatou que qualquer usuário do sistema consegue alterar a própria senha na tela de login, usando a função "Esqueceu sua senha".

Vamos então fechar essa issue e restringir a criação em #1370.
