### ISSUE TITLE
Criação de documentos administrativos a partir de documento protocolado

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#924]
Possibilitar que sejam criados diversos documentos adminstrativos a partir de um documento protocolado.

**Comment by edwardoliveira** [comment]
Vc diz colocar o botão de "Criar Documento" mesmo após a adição de um primeiro documento administrativo????

![image](https://cloud.githubusercontent.com/assets/9326037/23872022/7fd4eb96-080b-11e7-8b77-86e9c5e93c64.png)

**Comment by andreagudo** [comment]
Isso mesmo. Como os documentos  já vinculados já estão sendo listados nessa tela, ajuda a evitar confusão.

**Comment by eduardoedson** [comment]
@andreagudo Verifique, por favor
(Espere a máquina atualizar)

**Comment by andreagudo** [comment]
Resolvido.
