### ISSUE TITLE
Citar documentos administrativos vinculados na primeira tela de documento protocolado

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#925]
Citar documentos administrativos vinculados na primeira tela de documento protocolado. E também as repícprocas: os documentos protocolados na primeira tele de documentos administrativos.

**Comment by edwardoliveira** [comment]
Vc diz na tela de pesquisa???? As telas abaixo?

![image](https://cloud.githubusercontent.com/assets/9326037/23871941/3d7f7856-080b-11e7-9595-5b012ae0ae19.png)

![image](https://cloud.githubusercontent.com/assets/9326037/23871954/4818292a-080b-11e7-9223-ca9c5e69d0e4.png)

**Comment by andreagudo** [comment]
Penso que essas informações devem estar nas telas abaixo (docs adms na primeira e protocolos na segunda):
![captura de tela de 2017-03-14 08 48 43](https://cloud.githubusercontent.com/assets/19169882/23899231/1734ca10-0893-11e7-9c88-9a077b5dc8ae.png)
![captura de tela de 2017-03-14 08 49 47](https://cloud.githubusercontent.com/assets/19169882/23899257/36c95cc4-0893-11e7-88b4-7a896ff1247b.png)
