### ISSUE TITLE
Permitir que um documento protocolado tenha vinculo com mais de um documento administrativo

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#926]
Ao vincular um segundo documento administrativo a um mesmo documento protocolado, está dando o seguinte erro:
![captura de tela de 2017-03-09 15 07 18](https://cloud.githubusercontent.com/assets/19169882/23763878/2b621496-04da-11e7-9ce1-dd360529504a.png)

**Comment by edwardoliveira** [comment]
@andreagudo André, verifique por favor se a issue foi resolvida.

**Comment by andreagudo** [comment]
Resolvido.

**Comment by eduardoedson** [comment]
@andreagudo Verifique, por favor
