### ISSUE TITLE
Permitir criação de documento administrativo a partir de protocolo de ano diferente

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#927]
O sistema está oferecendo a criação de um doc adm do mesmo ano do protocolo. O ideal seria oferecer o próximo número do ano corrente.

**Comment by edwardoliveira** [comment]
Ele permite a mudança do ano e número. Vc diz já vir por *padrão* o ano corrente e sequencial correspondente?

**Comment by andreagudo** [comment]
Sim, vir por padrão ano corrente e o número da seqüencia. O SAPL 2.5 não faz isso, mas também permite editar (como o 3.1). Mas há o risco do operador não editar por engano e registrar um documento do ano atual com número e ano que já passaram.

**Comment by edwardoliveira** [comment]
Entendi. Farei assim então.

**Comment by edwardoliveira** [comment]
@andreagudo Favor verificar se a issue foi resolvida. Caso contrário, favor reabrir.

**Comment by edwardoliveira** [comment]
@eduardocalil Vou reabrir essa issue porque provavelmente vamos ter que colocar a numeração por ano também. Algumas linhas acima:

```
        numero_max = DocumentoAdministrativo.objects.filter(
            tipo=protocolo.tipo_documento
        ).aggregate(Max('numero'))['numero__max']
```

Seria

```
        curr_year = datetime.datetime.now().date().year
        numero_max = DocumentoAdministrativo.objects.filter(
            tipo=protocolo.tipo_documento, ano=curr_year
        ).aggregate(Max('numero'))['numero__max']
```
não???

**Comment by edwardoliveira** [comment]
@LeandroRoberto @andreagudo A numeração dos documentos administrativos é assim mesmo? A maior pra cada tipo de documento (ofício, convite, etc)? Concordam que devemos limitar por ano?

**Comment by LeandroRoberto** [comment]
por ano...

**Comment by eduardocalil** [comment]
Confere aí @andreagudo, por favor

**Comment by andreagudo** [comment]
Não está ficando o vínculo no protocolo. E a data do documento acessório deve ser atual.
![captura de tela de 2017-03-15 08 00 23](https://cloud.githubusercontent.com/assets/19169882/23946443/2f187322-0959-11e7-901c-2b68750edfd2.png)
![captura de tela de 2017-03-15 08 00 41](https://cloud.githubusercontent.com/assets/19169882/23946445/3171c24a-0959-11e7-89f5-2ce4bbdf0f7c.png)

**Comment by edwardoliveira** [comment]
@andreagudo Essa issue foi consertada???

**Comment by andreagudo** [comment]
Sim, resolvido. Criarei outra issue para o problema acima relatado.
