### ISSUE TITLE
Link no rodapé para configuração da Casa não funciona

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#931]
Quando a configuração da Casa ainda não foi feita existe um link no rodapé do portal, à direita, para configurar.

1) o link não está correto
2) o link não deveria aparecer para um usuário não logado (e está aparecendo).

**Comment by marciomazza** [comment]
O linke deveria levar para algo como `/sistema/casa-legislativa/edit` que deveria criar uma única casa se não existir.

**Comment by edwardoliveira** [comment]
Oi @marciomazza, favor verificar se issue resolvida. Senão favor reabrir.
