### ISSUE TITLE
Erro ao protocolar documento

### ISSUE THREAD

**Issue by eduardocalil** [interlegis/sapl#933]
![captura de tela de 2017-03-13 15 40 47](https://cloud.githubusercontent.com/assets/14843060/23869909/7db5932c-0803-11e7-9d29-991d25b09054.png)

**Comment by edwardoliveira** [comment]
Temos que ver esse erro na tua máquina pq na minha máquina não deu. E estou com o último commit aqui.

![image](https://cloud.githubusercontent.com/assets/9326037/23870944/208fb214-0807-11e7-9a6f-200462883fb4.png)

**Comment by eduardocalil** [comment]
O erro era quando tentava criar
