### ISSUE TITLE
Revisar destino de link da votação de proposição em "Matérias Legislativas"

### ISSUE THREAD

**Issue by mgbf** [interlegis/sapl#935]
Ao clicar no link sou redirecionado para a sessão em que a matéria foi votada, em Matérias do Expediente. A sugestão é que a página seja redirecionada ao painel de votação específico da matéria, ou para a página de Matérias da Ordem do Dia, onde a mesma se encontrará na lista. Creio que desta forma ficaria mais fácil a compreensão pelo cidadão.

**Comment by eduardoedson** [comment]
Poderia postar uma imagem ou link dessa tela?

**Comment by VictorFabreF** [comment]
Issue já resolvida.
