### ISSUE TITLE
Tipo e número e data de documento administrativo gerado a partir de protocolo de ano diferente

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#938]
Fazer com que o número do documento admistrativo gerado a partir de protocolo de ano diferente seja o próximo, de acordo com o ano e o tipo escolhidos. E que a data do documento adminstrativo seja a atual.

**Comment by edwardoliveira** [comment]
@andreagudo Teria como checar se essa issue foi resolvida? Lembro de termos testado dois dias atrás...

**Comment by edwardoliveira** [comment]
Acabamos de subir mais uma modificação que agora parece ter endereçado finalmente essa issue (e a #938). Favor verificar.

**Comment by andreagudo** [comment]
Resolvido.
