### ISSUE TITLE
Documento protocolado em ano anterior não informa documento adminstrativo vinculado

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#939]
Será que não está havendo confusão entre protocolos de mesmo número, mas anos diferentes?

![captura de tela de 2017-03-15 11 18 56](https://cloud.githubusercontent.com/assets/19169882/23952760/3ba6563c-0971-11e7-805e-339fda046946.png)
![captura de tela de 2017-03-15 11 18 23](https://cloud.githubusercontent.com/assets/19169882/23952762/3ea6e3f6-0971-11e7-877d-bbc3105f9d66.png)

**Comment by edwardoliveira** [comment]
@andreagudo Acho que esse também foi resolvido ontem. Poderia confirmar? Reabrir se for o caso. Obrigado!

**Comment by andreagudo** [comment]
Resolvido.
