### ISSUE TITLE
Rever subnavs das actions sections

### ISSUE THREAD

**Issue by LeandroRoberto** [interlegis/sapl#94]
Estamos usando nas actions sub-nav com dd dl a... colocando na tag "a" a class button... conceitualmente na biblioteca foundation, não se usa sub-navs com a classe button, além disso, sub-navs é para dar o sentido de navegabilidade em profundidade... para o nosso propósito, o mais adequado é usar o conjunto ul li a, em que ul recebe a classe button-group e "a" recebe a classe button

**Comment by marciomazza** [comment]
Resolvida por #160.
