### ISSUE TITLE
Erro no alter sequence antes de salvar objeto

### ISSUE THREAD

**Issue by LucianoAlmeida** [interlegis/sapl#951]
```
File "[...]/sapl/sapl/legacy/migration.py", line 267, in alter_sequence
    exec_sql('ALTER SEQUENCE %s RESTART WITH %s;' % (sequence_name, id))
django.db.utils.DataError: RESTART value (-1) cannot be less than MINVALUE (1)
```

Esse erro está acontecendo em alguns bancos de dados testados. Aparentemente, o primeiro valor dessa sequência é negativa ou igual a zero, o que gera o erro acima.

**Comment by marciomazza** [comment]
Isso deve ser uma entrada com pk zero.... o que não deveria existir.

Deve ser uma linha estragada do banco específico.

**Comment by marciomazza** [comment]
Seria interessante fazer consultas em todos os bancos p ver se o problema acontece em muitas tabelas em muito bancos...

**Comment by marciomazza** [comment]
Simplesmente resolvi habilitando pks negativas.
Isso não deve dar nenhum problema e obedece a nossa diretriz de não alterar as pks na migração.
