### ISSUE TITLE
AssertionError em SessaoPlenaria

### ISSUE THREAD

**Issue by LucianoAlmeida** [interlegis/sapl#952]
```
File "[...]/sapl/sapl/legacy/migration.py", line 592, in adjust_sessaoplenaria
    assert not old.tip_expediente
AssertionError
```
A primeira vez que esse erro foi visto era por conta de uma entrada inválida onde todos os valores de um objeto no banco legado eram iguais a zero (pk inclusive), mas pelo visto ele pode ter outro motivo.

**Comment by marciomazza** [comment]
Provavelmente eu coloquei esse assert pq nos bancos que analisei estava sempre vazio.... O assert era justamente para pegar algum onde estivesse preenchido e entender....

Precisamos ver para que o campo é usado...

**Comment by LucianoAlmeida** [comment]
Esse assert foi excluido da migração.
