### ISSUE TITLE
Erro de valor máximo de CharField

### ISSUE THREAD

**Issue by LucianoAlmeida** [interlegis/sapl#953]
```
django.db.utils.DataError: value too long for type character varying(X)
```

O erro acima apareceu duas vezes durante a migração. Uma onde valor de **X** no 'varying(X)' era 60 (na model Comissao, campo 'nome') e outra com valor 50 (na model AssuntoMateria, campo 'dispositivo').
Verificar se o tamanho máximo para esses campos não deveria ser maior.

**Comment by LucianoAlmeida** [comment]
@marciomazza
Qual seria a melhor abordagem pra resolver esse problema? Aumenta o valor do max_length desses campos?

**Comment by marciomazza** [comment]
Aumentar o valor no Model, sim!
