### ISSUE TITLE
Erro durante a migração de Autor onde a Comissão não existe

### ISSUE THREAD

**Issue by LucianoAlmeida** [interlegis/sapl#954]
```
sapl.comissoes.models.DoesNotExist: Comissao matching query does not exist.
```

O erro acima aparece quando a tabela de autores aponta para uma comissão que não existe. Esse erro aparece somente no ajuste de autores, deve-se criar um stub caso a comissão não exista. Verificar também caso Autor aponte para um Parlamentar que não exista.

**Comment by LucianoAlmeida** [comment]
@marciomazza, depois que mudamos nosso jeito de migrar os dados, acho que esta issue não se aplica mais.

**Comment by marciomazza** [comment]
Concordo.
