### ISSUE TITLE
Loop infinito na exclusão de objetos marcados com ind_excluido=1

### ISSUE THREAD

**Issue by LucianoAlmeida** [interlegis/sapl#955]
Isso é causado por uma objeto que está marcada como protected (Autor ou TipoAutor). Verificar como essa exclusão poderia ser feita para sair do loop infinito.

**Comment by marciomazza** [comment]
Relaccionado a #977

**Comment by LucianoAlmeida** [comment]
Estou fechando essa issue porque foi concluída na #977.
