### ISSUE TITLE
Data com valor nulo na migração da model NormaJuridica

### ISSUE THREAD

**Issue by LucianoAlmeida** [interlegis/sapl#957]
```
django.db.utils.IntegrityError: null value in column "timestamp" violates not-null constraint
```

Esse erro é muito recorrente. Aparentemente o campo `timestamp` de NormaJuridica não deveria ser nulo, mas provavelmente no banco legado ele não tem nenhum valor.

**Comment by marciomazza** [comment]
Precisamos saber qual o significado desse campo `timestamp`. Se for só pra log de auditoria essa informação precisa ir pro `Django Reversion`.

@LeandroRoberto Ajuda?

**Comment by LeandroRoberto** [comment]
campo desnecessário!

**Comment by marciomazza** [comment]
Certo... mas vc sabe o que significa esse campo, @LeandroRoberto ?

**Comment by LeandroRoberto** [comment]
Resolveu? eu disse desnecessário pois vc cantou a pedra correta: "Se for só pra log de auditoria essa informação precisa ir pro Django Reversion."

**Comment by LucianoAlmeida** [comment]
Deveria mudar o campo no model pra ser nulável então?
Durante a migração, se existir valor nesse campo, mesmo que seu objetivo seja somente de auditoria e seja nulável, ele será migrado. Sendo migrado, automaticamente ele já será marcado no django reversion.
