### ISSUE TITLE
Erro de "content_type_id" nulo durante criação de um stub

### ISSUE THREAD

**Issue by LucianoAlmeida** [interlegis/sapl#958]
```
django.db.utils.IntegrityError: null value in column "content_type_id" violates not-null constraint
DETAIL:  Failing row contains (7, ????????????, null, null).
```
Erro aconteceu quando se estava migrando a model Proposicao e um stub foi criado. O campo `content_type_id` do stub não pode ser nulo.

**Comment by LucianoAlmeida** [comment]
Assim como foi comentado na issue #954, acho que esta daqui também não se aplica.

**Comment by marciomazza** [comment]
Concordo.
Para referência, mudamos a abordagem de migração em #1376.
