### ISSUE TITLE
CÓDIGO FONTE DO SAPL

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#963]
Como consigo o código fonte do SAPL?

**Comment by edwardoliveira** [comment]
Você está no site que disponibiliza o código fonte, isto é, basta pegar o código fonte daqui mesmo.

Se vc souber como utilizar o Git basta clonar o repositório. Senão, na página principal, `https://github.com/interlegis/sapl` clique em `clone or download`, e escolha a opção download.
