### ISSUE TITLE
Vereador sem mandato atualmente designado relator; composição atual não registrada

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#967]
É o caso do Vereador Sandro Goltz. Para ser relator tem que ter mandato atualmente, estar ativo e ser membro da comissão. O problema ocorreu porquê o sistema assumiu como atual uma composição anterior, já que a atual não foi cadastrada. Não devia listar os membros de uma composição anterior, mas avisar que não há composição atual.
![captura de tela de 2017-03-21 14 17 38](https://cloud.githubusercontent.com/assets/19169882/24160724/626acc7e-0e41-11e7-845a-052c6abab1fa.png)

**Comment by eduardoedson** [comment]
a atual seria uma que tem o ano de inicio e fim no ano atual?

**Comment by andreagudo** [comment]
Boa pergunta. No nosso caso, sim. Mas não sei se, em algumas casas, uma composição pode terminar em outro ano. Sugiro verificar com é isso no 2.5.

**Comment by eduardoedson** [comment]
@edwardoliveira @LeandroRoberto @morale

**Comment by andreagudo** [comment]
Testei hoje. Parece resolvido. Ao incluir relator, aparecem apenas os atuais membros da comissão. Sugiro apenas uma pequena mudança. Ao clicar em "Adicionar Relatoria", Parlamentar já aparece preenchido com o primeiro da lista. O ideal seria como está no 2.5
![captura de tela de 2017-05-12 08 26 10](https://cloud.githubusercontent.com/assets/19169882/25996267/e9df5412-36ec-11e7-8929-3f7d4a90730c.png)

**Comment by eliseuegewarth** [comment]
@andreagudo crie uma nova issue para essa sugestão, para efeitos de controle de tarefas, se ainda for necessário.
