### ISSUE TITLE
Inclusão de Modelo de Textos Articulados

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#970]
Como incluir modelo de proposições no editor de texto do SAPL 2.5? E também no demo do SAPL 3.1?

**Comment by LeandroRoberto** [comment]
no 2.5 não sei dizer, melhor questionar na lista gitec... aqui estamos focados no 3.1...
quanto ao 3.1, ainda não existem modelos de documentos apenas configuração das partes de modelos. Essas partes podem ser criadas e customizadas no django-admin da aplicação.

**Comment by edwardoliveira** [comment]
Podemos fechar essa issue????

**Comment by LeandroRoberto** [comment]
#888
