### ISSUE TITLE
Tirar DELETE CASCADE dos Models

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#973]
Os models devem ser DELETE CASCADE=False por padrão.

**Comment by LeandroRoberto** [comment]
não altere nada nesse quesito na app compilacao

**Comment by eduardoedson** [comment]
@LeandroRoberto TipoProposição também não?

**Comment by edwardoliveira** [comment]
Sim. Fiquei na dúvida, mas é melhor colocar mesmo...
