### ISSUE TITLE
Reduzir migrations (squash)

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#976]

**Comment by marciomazza** [comment]
Fiz várias tentativas e encontrei diversos problemas:

* Existe uma dependência cíclica entre as apps `materia` e `compilação`:
    `materia.models.TipoProposicao.perfil` aponta para `compilacao.models.PerfilEstruturalTextoArticulado`
  Isso poderia ser contornado, mas é bem enrolado
* Existem alguns `RunPython` em migrações. O `squashmigrations` pára de otimizar as migrações no ponto onde encontra um `RunPython`... o efeito disso é ter vários `AddField`, `AlterField` e até `RemoveField` de um campo depois do `CreateModel` onde esse campo apareceria apenas uma vez (ou não apareceria no caso do `RemoveField`.
* Nessas situações, onde a migration não é otimizada, quando um campo é removido depois de ser criado... acontecem erros bem bizarros. Se parecem com esses erros:
  - https://code.djangoproject.com/ticket/25530 (aberto)
  - https://code.djangoproject.com/ticket/25521 (esse está resolvido no django 1.10... poderíamos até avançar a versão para ele e ver o que sai...)
* Mesmo depois de remover os RunPython (os nossos não eram necessários depois do squash) não há um caminho simples para rodar a otimização do squash novamente... Seria preciso transformar a migração *squashed* numa migração normal para fazer isso: ele não aceita fazer squash de squash.
  Transformar um migração *squashed* numa normal é um processo manual e só poderia ser feito depois de todos terem rodado `./manage.py migrate`. Ou seja... bem chato.

Tentei várias coisas... até fazer edições manuais da migration gerada. Isso é difícil, trabalhoso e tem grande chance de introduzir erros. O estado do banco de dados é algo bem precioso e não dá pra arriscar introduzir erros nisso, de fato.

Por tudo isso... acho que devemos largar mão de tentar squash e refazer as migrations do zero. Eu achava **erroneamente** que teríamos de refazer nossos bancos. A boa notícia é que parece que basta:

1. Paramos de comitar mudanças no banco por um dia.
1. Todo mundo atualiza eu repo local (`git pull` no `master`)
1. Todos rodam `./manage.py migrate` para ficarem com a última versão do banco
1. Todos rodam a query `delete from django_migrations;` no seu banco
1. Todos baixam um ramo específico em que as migrations estarão zeradas (posso fazer esse ramo)
1. Todos rodam `./manage.py migrate --fake`

Assim ninguém perde seus dados e resolvemos esse problema.

Vou testar em breve essa solução, que achei em https://blog.tyk.nu/blog/cleaning-up-django-migrations, e aviso se dá certo de verdade.

**Comment by LeandroRoberto** [comment]
vamos fazer a solução apresentada... hoje, uma segunda-feira, é ideal pra fazer isso.

**Comment by marciomazza** [comment]
Vamos lá:

### Roteiro para zerar as migrações

Cada uma faça o seguinte e me reporte que fez:
```
git checkout master
git pull
git checkout pre-zera-migrations
./manage.py migrate
```

Se deu tudo certo agora seu banco está em sincronia com o código!

Apague agora todas as linhas da tabela `django_migrations` rodando em seu banco:
```
delete from django_migrations;
```

Finalmente, mude para o master (que já está com as migrations zeradas) e sincronize o banco com o código.
```
git checkout master
./manage.py migrate --fake
```
Pronto. Agora me avise que fez isso.

**Comment by LeandroRoberto** [comment]
comigo ok... para sapl rodando como principal e para sapl instalado como app.

**Comment by DTILegBG** [comment]
aqui ok também.

**Comment by edwardoliveira** [comment]
OK pra mim também.

**Comment by cristian-longhi** [comment]
Aqui também ok.

**Comment by eduardoedson** [comment]
ok

**Comment by marciomazza** [comment]
Ótimo. Estou encerrando essa issue então.
