### ISSUE TITLE
Migração - Problema ao excluir objetos protegidos marcados para exclusão.

### ISSUE THREAD

**Issue by LucianoAlmeida** [interlegis/sapl#977]
Durante a exclusão de alguns objetos que estão marcados com `ind_excluido=1`, não há qualquer checagem se os objetos relacionados a este também podem ser excluídos. Como essa checagem não é feita, os objetos estavam sendo excluídos em cascata. Esse problema já foi parcialmente resolvido na issue #973, mas a migração agora precisa lidar agora com os que estão com proteção contra exclusão.

**Comment by LeandroRoberto** [comment]
outro fato acontece... a restrição de exclusão não permite o migração rodar novamente... se dá erro lá na frente, ou cria-se o banco novamente, ou saí tabela por tabela dando um trancate cascade pra rodar a migração novamente
