### ISSUE TITLE
Nome dos parlamentares da composição da mesa não são clicaveis

### ISSUE THREAD

**Issue by DTILegBG** [interlegis/sapl#981]
O nome dos parlamentares que fazem parte da mesa não são clicáveis.

**Comment by eduardoedson** [comment]
Pode postar o link da tela?

**Comment by DTILegBG** [comment]
opa, claro
![image](https://cloud.githubusercontent.com/assets/13314947/24467904/bf94a68a-148c-11e7-8461-183efb73368e.png)

**Comment by eduardoedson** [comment]
Verifique por favor

**Comment by DTILegBG** [comment]
Resolvido!


Em 29/03/2017 15:05, Eduardo Edson Batista Cordeiro Alves escreveu:
