### ISSUE TITLE
Erro ao excluir Tipo de matéria legislativa

### ISSUE THREAD

**Issue by eliseuegewarth** [interlegis/sapl#982]
Ao executar a funcionalidade de excluir um tipo de matéria legislativa, o sistema retorna uma exceção "ProtectedError", conforme imagem abaixo.

![delete_tipo_materia_legislativa](https://cloud.githubusercontent.com/assets/5272409/24471783/9524d57a-1499-11e7-97f4-8d9d5d8a31b1.jpg)

**Comment by eduardoedson** [comment]
É porque esse tipo está sendo usado em alguma matéria legislativa, então, caso exclua, a matéria ficaria sem tipo. Mas precisa fazer uma mensagem melhor.

**Comment by edwardoliveira** [comment]
Opa, taí uma primeira issue pro @eliseuegewarth :grimacing:

**Comment by edwardoliveira** [comment]
Mas como disse o @eduardoedson, a intenção era essa! Mas a tela amarela tem que ser substituída por uma mensagem de erro na app, se possível.

**Comment by edwardoliveira** [comment]
Corrigido pelo commit 95227452ba4fcbe1f10eed0cfa1e33e33ddd764a
