### ISSUE TITLE
Adição de extensão em arquivos na migração

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#988]
Conforme conversamos na semana passada, o `textract` não consegue fazer o parsing de arquivos sem extensão PDF. O @eduardocalil está colocando um filtro no SAPL 3.1 para bloquear o upload de arquivos sem extensão. Seria interessante que a rotina de migração de documentos pudesse tratar os documento do SAPL 2.5 sem extensão, adicionando-a automaticamente. É possível fazer isso com um script BASH por exemplo, mas os paths dos arquivos são armazenados no banco então seria melhor adicionar esse passo no script de migração dos arquivos.

/cc @marciomazza @LucianoAlmeida

**Comment by marciomazza** [comment]
@eduardocalil Sabe algo sobre isso?

**Comment by marciomazza** [comment]
Sim, a migração de documentos migra todos os arquivos com extensão.

https://github.com/interlegis/sapl/blob/38a852554fa50270dfd1edd983b3137686b8530e/sapl/legacy/migracao_documentos.py#L138
