### ISSUE TITLE
MANUAL SAPL 3.1

### ISSUE THREAD

**Issue by paulot12** [interlegis/sapl#992]
Já está disponível o manual do SAPL 3.1? Quando será disponibilizado o sistema?

**Comment by eduardocalil** [comment]
@paulot12 Essa seção Issues do GitHub foi criada única e exclusivamente para discutir o desenvolvimento de funcionalidades para o SAPL. É uma listagem do que deve ser feito e implementado para organizar o nosso trabalho. Questões desse tipo devem ser feitas no GITEC.

**Comment by edwardoliveira** [comment]
@paulot12 Respondi via email o teu questionamento. Att, Edward

**Comment by sesostris** [comment]
Paulo, estamos iniciando a atualização do manual. Em breve será criado um outro repositório onde colocaremos a documentação do SAPL 2.5 e então faremos, por partes, a atualização para a versão 3.1. Quando este repositório estiver montado, te aviso para que você tenha a oportunidade de ajudar nesta atualização, assim teremos manuais melhores e de forma mais rápida.
