### ISSUE TITLE
Avaliar outras libs para extração de texto de PDF para indexação

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#993]
Atualmente estamos usando o `textract`, mas essa lib é bem "gorda" (várias dependências que não precisamos) e tem um bug com PDFs sem extensão que dão pau no parsing. Seria interessante vermos a possibilidade de substituir por outra lib python pura que nos permita extrair o texto do PDF. Sugestões

* slate (imatura?)
* PDFMiner
* pyPdf (abandonware?)

/cc @eduardocalil @LeandroRoberto

**Comment by eduardocalil** [comment]
Obs: o textract não suporta arquivos do tipo .xml

**Comment by eduardocalil** [comment]
Isso abre uma discussão sobre os arquivos que estão no SAPL. Na migração foram encontrados arquivos em formatos que não fazem sentido para documentos, como por exemplo Normas com arquivos no formato **.c**
