### ISSUE TITLE
Migrar tabela tipo_numeracao_protocolo

### ISSUE THREAD

**Issue by marciomazza** [interlegis/sapl#995]
A tabela tipo_numeracao_protocolo foi criada depois do `inspectdb` inicial.
Verificar se a funcionalidade foi implementada no sapl 3.1.
Avaliar se existe variação no conteúdo dessa tabela no diferentes bancos da hospedagem.
Migrar.

**Comment by marciomazza** [comment]
A funcionalidade que usa essa tabela foi parcialmente implementado no 3.1. Apenas sequenciais por **ano** e **único**. O 2.5 hoje tb tem a opção **por legislatura**.

Segundo @morale a tabela do 2.5 armazena a partir e quando cada opção entrou em vigência.

**Comment by marciomazza** [comment]
No 3.1 esta informação está em `sapl.base.AppConfig.sequencia_numeracao`.

O que há estado real nessa tabela é somente a data de vigência, que é uma espécia de log de quando a forma de numeração foi alterada.

Como se trata de log, uma estratégia de migração então é simplesmente gerar `Revision`s do *django-reversion* que expressem as alterações da opção `sapl.base.AppConfig.sequencia_numeracao`.

**Comment by marciomazza** [comment]
Já temos um ramo iniciado 
https://github.com/interlegis/sapl/tree/995-migrar-tipo-numeracao-protocolo
onde acrescentei o model `TipoNumeracaoProtocolo` ao legacy em 885f90088545cd78d9d8dbed58265026524fe551

**Comment by marciomazza** [comment]
Cosiderando as simplificações de #1376 acho que devemos apenas usar a informação disponível em `legacy.models.TipoNumeracaoProtocolo` descrito acima para alimentar o campo `sapl.base.models.AppConfig.sequencia_numeracao`. Isso provavelmente deve ser feito considerando o registro de `legacy.models.TipoNumeracaoProtocolo` com data mais recente para saber qual o tipo de numeração vigente e ignorando os demais.

**Comment by marciomazza** [comment]
Cosiderando as simplificações de #1376 acho que devemos apenas usar a informação disponível em `legacy.models.TipoNumeracaoProtocolo` descrito acima para alimentar o campo `sapl.base.models.AppConfig.sequencia_numeracao`. Isso provavelmente deve ser feito considerando o registro de `legacy.models.TipoNumeracaoProtocolo` com data mais recente para saber qual o tipo de numeração vigente e ignorando os demais.

**Comment by marciomazza** [comment]
A propósito, abri uma issue para implementarmos numeração por legislatura #1377.
É preciso fazer isso antes dessa issue para migrar corretamente esses casos.

**Comment by DtiLegBG** [comment]
para constar, porque deve ter mais casos assim, na minha base do 2.5 não tenho essa tabela. Fui dar uma olhada e recebo o erro (SAPL 2.5)

Tipo do Erro: ProgrammingError
Valor do Erro: (1146, "Table 'interlegis.tipo_numeracao_protocolo' doesn't exis
